### ISSUE TITLE
There's no way of unblocking a blocked project

### ISSUE THREAD

**Issue by augerm** [taigaio/taiga-front#1001]
I have a project that I have lost access to because I had two private projects. I'd be happy to make both projects public but I don't have the ability to do this even though I am the owner of this project, because I can't get past the "Blocked" page.

**Comment by superalex** [comment]
Hello @augerm 

Just write to support@taiga.io indicating your username/email and projects and we'll temporary unblock them so you can make them fit in your paying plan.

Regards!,

**Comment by praveenscience** [comment]
What about for self-hosted projects @superalex?

**Comment by bameda** [comment]
In the superadmin panel you can block/unblocked project in the project list or in the detail page.

![image](https://cloud.githubusercontent.com/assets/877218/18788997/795d4d5a-81a9-11e6-9871-ee59b0a08dc5.png)

**Comment by praveenscience** [comment]
@bameda Awesome... How do I access this panel?

**Comment by bameda** [comment]
in `http://taiga-back-host/admin/`

**Comment by praveenscience** [comment]
@bameda I have used vagrant taiga. And not sure if there's a `back-host` here. Please help?

**Comment by bameda** [comment]
http://vagran-ip/admin/

**Comment by bameda** [comment]
In `conf.json` file copy the value of `api`. This is the url of taiga-back. So now change `/api/v1/` to `/admin/` (with the last / too).

**Comment by praveenscience** [comment]
@bameda Yes, did that. Should I restart the server or something? Now my `conf.json` looks like this:

```
{
    "api": "/admin/",
    "eventsUrl": null,
    "debug": "true",
    "publicRegisterEnabled": true,
    "feedbackEnabled": false,
    "privacyPolicyUrl": null,
    "termsOfServiceUrl": null,
    "maxUploadFileSize": null,
    "gitHubClientId": null,
    "contribPlugins": []
}
```

**Comment by bameda** [comment]
You did not have to change conf.json. You only had to use it to check exactly what is the taiga-back url.

**Comment by bameda** [comment]
OK, you have change nginx configuration to enable the access.

Edit `/etc/nginx/sites-available/taiga` and add

```
  # Django admin access (/admin/)
    location /admin {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://127.0.0.1:8001$request_uri;
        proxy_redirect off;
    }
```
between `location /api/` and `location /static/`

Then restart the nginx server with `sudo service nginx restart` (o the vagrant container)

And now you can access to (I think) `http://localhost:8000/admin/`

I change taiga-vagrant to enable it by default so if this is complicate for you, you can reinstall it again.

**Comment by praveenscience** [comment]
@bameda Awesome... I am able to see the admin login, but unfortunately I am unable to use `admin` and `123123` as the password. Oh wait. I guess I changed it. Let me check and get back to you.

**Comment by praveenscience** [comment]
@bameda Awesome... And what about the number of private projects to the self hosted one? Unlimited?

**Comment by bameda** [comment]
The number of private project is unlimited by default. you can change it in `taiga-back-settings/local.py`

```python
MAX_PRIVATE_PROJECTS_PER_USER = None    # None == no limit
MAX_PUBLIC_PROJECTS_PER_USER = None     # None == no limit
MAX_MEMBERSHIPS_PRIVATE_PROJECTS = None # None == no limit
MAX_MEMBERSHIPS_PUBLIC_PROJECTS = None  # None == no limit
```

or you can change the limit for a concrete user in the superadmin panel.

**Comment by praveenscience** [comment]
@bameda Awesome. Thanks for your time.

**Comment by bameda** [comment]
you are welcome

**Comment by jimeney** [comment]
@bameda please note there's been a recent commit to the taiga-scripts repository whereby the edit breaks Taiga by not allowing nginx to start... essentially, the suggested workaround is not what was committed, and errors are thrown around the nginx proxy variables being incomplete.

Edit /etc/nginx/sites-available/taiga and add

  # Django admin access (/admin/)
    location /admin {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://127.0.0.1:8001$request_uri;
        proxy_redirect off;
    }

**Comment by bameda** [comment]
fixed, sorry for the inconvenience.

**Comment by jimeney** [comment]
no apology necessary, just took me tracking back to this as the source of the change and I had it back up and running!

**Comment by bameda** [comment]
I miss scape $ symbol, so now should work again
