### ISSUE TITLE
Adding users to hosted/open source without invitation

### ISSUE THREAD

**Issue by oozypal** [taigaio/taiga-front#1003]
Is it possible and how to add users to taiga without the invitation process?

**Comment by superalex** [comment]
You could use the django admin area to create users and memberships and assign them to projects.

**Comment by oozypal** [comment]
Gr8
How to access Django admin?

I added the following to Nginx with no help

    location /admin {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://mydomain.com:8001/admin;
        proxy_redirect off;
    }

I could access the page. It gives error.

**Comment by superalex** [comment]
What error did you receive?, and what url did you use to access?
