### ISSUE TITLE
Bug in kanban view when revisiting page with collapsed columns

### ISSUE THREAD

**Issue by aginiewicz** [taigaio/taiga-front#1005]
Illustrated in 3 steps:

1. Start with kanban view:
![step1](https://cloud.githubusercontent.com/assets/141273/15214394/0d9aae48-184d-11e6-8b28-a412ba4f63fb.png)

2. Collapse column:
![step2](https://cloud.githubusercontent.com/assets/141273/15214547/e827e968-184d-11e6-8a8f-a23d106240cb.png)

3. Refresh or revisit page:
![step3](https://cloud.githubusercontent.com/assets/141273/15214562/052b2ffc-184e-11e6-8020-c602627fe304.png)

As you can see, first column is open but empty. Happens on tree.taiga.io and on-premises install of Taiga 2.1. It worked with Taiga 2.0 in same system/browser combination, so I think this is some regression.

It is true - this is quite old version of Firefox (29.0.1 - kind of ancient), but I keep it for other reasons (like testing stuff). Anyway, it would be nice if it could work also on "slightly" older browsers.

**Comment by Xaviju** [comment]
Hi @aginiewicz 
I'm sorry but we don't support layout fixes for very old versions at the moment. I tried to reproduce this behaviour in taiga.io in Firefox 29 in a virtual machine with Windows. I found some layout problems, but I cannot reproduce that behavior.
