### ISSUE TITLE
Compiling sass error

### ISSUE THREAD

**Issue by davidperis92** [taigaio/taiga-front#1008]
When I clone the project, install all dependencies and execute gulp, it shows an error:

[08:28:41] Plumber found unhandled error:
 Error in plugin 'gulp-sass'
Message:
    app/styles/components/list-items.scss
Error: ".list-itemtype-project h2" failed to @extend "%normal".
       The selector "%normal" was not found.
       Use "@extend %normal !optional" if the extend should be able to fail.
        on line 11 of app/styles/components/list-items.scss
>>         @extend %normal;
   --------^

Details:
    formatted: Error: ".list-itemtype-project h2" failed to @extend "%normal".
       The selector "%normal" was not found.
       Use "@extend %normal !optional" if the extend should be able to fail.
        on line 11 of app/styles/components/list-items.scss
>>         @extend %normal;
   --------^

    column: 9
    line: 11
    file: /home/david/Proyectos/taiga-front/app/styles/components/list-items.scss
    status: 1
    messageFormatted: app/styles/components/list-items.scss
Error: ".list-itemtype-project h2" failed to @extend "%normal".
       The selector "%normal" was not found.
       Use "@extend %normal !optional" if the extend should be able to fail.
        on line 11 of app/styles/components/list-items.scss
>>         @extend %normal;
   --------^

    messageOriginal: ".list-itemtype-project h2" failed to @extend "%normal".
The selector "%normal" was not found.
Use "@extend %normal !optional" if the extend should be able to fail.
    relativePath: app/styles/components/list-items.scss

**Comment by Xaviju** [comment]
Are you cloning master or stable? 
We moved from ```extend``` to ```include``` to avoid CSS bloating, but it should be working.

**Comment by davidperis92** [comment]
I've fixed the issue, I've had to do a pull on stable branch
