### ISSUE TITLE
Custom US points issue when creating new US

### ISSUE THREAD

**Issue by bmcarlson** [taigaio/taiga-front#1011]
Hello, 
I have customized the point values and names in my admin settings to better represent my team's relative estimation process. This is a great feature- love the customizability. The issue is, now when I go to create a new US I am unable to select points for any of my team members (I could before I customized it). This happens in both the backlog view and the kanban view. To fix this, I have to create my new US, then go back in a second time to add in any US points. Has anyone else had this issue? Is there a fix? Thanks :)

**Comment by juanfran** [comment]
Hello @bmcarlson 

thanks for reporting! it's already fixed
