### ISSUE TITLE
When assigning tasks the first name in the list should be the current user's.

### ISSUE THREAD

**Issue by stephaniehobson** [taigaio/taiga-front#1012]
My name is last in my team and I always have to filter to find it. I only ever assign tasks to myself so it'd be great if my name was always first in the list.

**Comment by Xaviju** [comment]
Makes sense, I agree.
Please, upvote this enhancement on Taiga: https://tree.taiga.io/project/taiga/issue/4220

**Comment by mikaoelitiana** [comment]
Hello guys, I am interested to work on this one

**Comment by superalex** [comment]
Hello @mikaoelitiana that would be great :)

Thanks!

**Comment by mikaoelitiana** [comment]
This should be also closed in Taiga https://tree.taiga.io/project/taiga/issue/4220, right?

**Comment by superalex** [comment]
Yes!, I've just updated it too ;)

**Comment by mikaoelitiana** [comment]
Thanks

Le jeu. 16 juin 2016 10:47, Alejandro <notifications@github.com> a écrit :

> Yes!, I've just updated it too ;)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/taigaio/taiga-front/issues/1012#issuecomment-226412303>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AApLawv-U3QOdtyZQC_VD3BgsssKi045ks5qMP95gaJpZM4IiZ_C>
> .
>
-- 

Mika Andrianarijaona
+261340722394
http://mikaoelitiana.name
