### ISSUE TITLE
Task-text is shown badly in some cases.

### ISSUE THREAD

**Issue by IagoLast** [taigaio/taiga-front#1014]
<img width="321" alt="captura de pantalla 2016-05-20 a las 1 07 01" src="https://cloud.githubusercontent.com/assets/2657897/15412434/ca34f858-1e27-11e6-8530-7443407909cb.png">

As you can see in the picture, task text overflows kanban-task div

A simple fix could be adding the following rule to the [kanban-task.scss](https://github.com/taigaio/taiga-front/blob/0fd334398fe2432595be3bb9c0a9338a6498f21b/app/styles/components/kanban-task.scss)

```css
.kanban-task {
    word-break: break-word;
}
```

Resulting in:
<img width="319" alt="captura de pantalla 2016-05-20 a las 1 18 47" src="https://cloud.githubusercontent.com/assets/2657897/15412572/dfe13d8c-1e28-11e6-8518-ec0913161d09.png">

**Comment by Xaviju** [comment]
If you found the bug and the fix. Why don't you make a PR of this? :)
