### ISSUE TITLE
Websocket connection failure

### ISSUE THREAD

**Issue by coevolving** [taigaio/taiga-front#1018]
I've posted on "New taiga installation on AWS, websocket connection failed" at https://groups.google.com/forum/#!topic/taigaio/ykvEJMxdWCg, but haven't received any help in 5 days.

Could this be caused by ...

-- begin paste --
Error: Cannot find module 'base64-url' 
-- end paste --
... or is that a red herring?

Some advice would be welcomed.  Thanks.

**Comment by littleyanglovegithub** [comment]
I have the same issue .Do you fix it?

**Comment by bameda** [comment]
Have you read the complete thread at https://groups.google.com/forum/#!topic/taigaio/ykvEJMxdWCg @littleyanglovegithub ?

It was a DNS problem
