### ISSUE TITLE
Problem with https

### ISSUE THREAD

**Issue by jas01** [taigaio/taiga-front#1021]
Hi everybody

I try to install taiga following the official documentation (so everything is from github)

After loosing lot of time I find out the problem come from https.

If I change my nginx configuration to use https everything work fine (I guess, at least I got some beautiful page in my browser)

If I swap to https I got a blank page.

I try to use firebug and find out they got a

  SecurityError: The operation is insecure.

inside

  app.js (line 2)

Regards

**Comment by superalex** [comment]
Hello @jas01 

What url are you using to access Taiga?, could you please show us your conf.json and nginx taiga config files?.

Regards

**Comment by jas01** [comment]
>What url are you using to access Taiga?, could you please show us your conf.json and nginx taiga config files?.


I'm not sure to understand your question but :

  I use

      https://my_taiga/

To be clear, when I say I got a blank page, it's blank in the browser, the broswer indeed get something (javascript & Cie) and If I show the source of the page it's plenty of thing but nothing in
the broswer

Here the configuration of  local.py

  from .common import *
  from .celery import *


  # Pour le mode async
  BROKER_URL = 'amqp://guest:guest@127.0.0.1:5672//'
  CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'
  CELERY_ENABLED = True


  # Config de taiga
  MEDIA_URL = "https://my_taiga/media/"
  STATIC_URL = "https://my_taiga/static/"
  ADMIN_MEDIA_PREFIX = "https://my_taiga/static/admin/"
  SITES["front"]["scheme"] = "https"
  SITES["front"]["domain"] = "my_taiga"

  SECRET_KEY = "theveryultratopsecretkey"

  DEBUG = False
  TEMPLATE_DEBUG = False
  PUBLIC_REGISTER_ENABLED = True

  DEFAULT_FROM_EMAIL = "no-reply@my_taiga"
  SERVER_EMAIL = DEFAULT_FROM_EMAIL

  # Uncomment and populate with proper connection parameters
  # for enable email sending. EMAIL_HOST_USER should end by @domain.tld
  EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
  EMAIL_USE_TLS = False
  EMAIL_HOST = "localhost"
  EMAIL_HOST_USER = ""
  EMAIL_HOST_PASSWORD = ""
  EMAIL_PORT = 25

  # Uncomment and populate with proper connection parameters
  # for enable github login/singin.
  #GITHUB_API_CLIENT_ID = "yourgithubclientid"
  #GITHUB_API_CLIENT_SECRET = "yourgithubclientsecret"


  # Pour les events

  EVENTS_PUSH_BACKEND = "taiga.events.backends.rabbitmq.EventsPushBackend"
  EVENTS_PUSH_BACKEND_OPTIONS = {"url": "amqp://taiga:XXXXX@localhost:5672/taiga"}


  DATABASES = {
      'default': {
          'ENGINE': 'django.db.backends.postgresql_psycopg2',
          'NAME': 'taiga',
          'USER': 'taiga',
          'PASSWORD': 'xxxxxxxx',
          'HOST': '127.0.0.1',
          'PORT': '',
      }
  }


and my conf.json


  {
    "api": "https://my_taiga/api/v1/",
    "eventsUrl": "ws://my_taiga/events",
    "debug": "true",
    "publicRegisterEnabled": true,
    "feedbackEnabled": true,
    "privacyPolicyUrl": null,
    "termsOfServiceUrl": null,
    "maxUploadFileSize": null,
    "contribPlugins": []
  }

**Comment by superalex** [comment]
It seems to be ok, could you please show us your nginx config file for Taiga?.

What happens if If you access directly to https://my_taiga/api/v1/ from your browser?

Could you please attach an screenshot from the network tab of your javascript console when the error happens?

**Comment by jas01** [comment]
>
>It seems to be ok, could you please show us your nginx config file for Taiga?.

Yes off course :

# MANAGED BY PUPPET
server {
  listen       *:443 ssl;
  server_name  my_taiga;

  ssl on;

  ssl_certificate           /etc/ssl/certs/my_taiga.pem;
  ssl_certificate_key       /etc/ssl/private/my_taiga.key;
  ssl_session_cache         shared:SSL:10m;
  ssl_session_timeout       5m;
  ssl_protocols             TLSv1 TLSv1.1 TLSv1.2;
  ssl_ciphers               ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA;
  ssl_prefer_server_ciphers on;
  ssl_trusted_certificate   /etc/ssl/certs/cru-tcs-chain.pem;

  client_max_body_size 50m;

  access_log            /var/log/nginx/my_taiga.access.log combined;
  error_log             /var/log/nginx/my_taiga.error.log;


  location /admin {

    proxy_pass            http://127.0.0.1:8001$request_uri;
    proxy_read_timeout    90;
    proxy_connect_timeout 90;
    proxy_redirect        off;
    proxy_set_header      Host $http_host;
    proxy_set_header      X-Real-IP $remote_addr;
    proxy_set_header      X-Scheme $scheme;
    proxy_set_header      X-Forwarded-Proto $scheme;
    proxy_set_header      X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location /media {

    alias /var/www/taiga/taiga-back/media;
  }

  location / {

    root      /var/www/taiga/taiga-front-dist/dist;
    try_files $uri $uri/ /index.html;
  }

  location /static {

    alias /var/www/taiga/taiga-back/static;
  }

  location /api {

    proxy_pass            http://127.0.0.1:8001/api;
    proxy_read_timeout    90;
    proxy_connect_timeout 90;
    proxy_redirect        off;
    proxy_set_header      Host $http_host;
    proxy_set_header      X-Real-IP $remote_addr;
    proxy_set_header      X-Scheme $scheme;
    proxy_set_header      X-Forwarded-Proto $scheme;
    proxy_set_header      X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}

>
>What happens if If you access directly to https://my_taiga/api/v1/ from your browser?

Get a nice page with something like

  Api Root

  GET
  Api Root

  GET /api/v1/

  HTTP 200 OK
  Content-Type: application/json
  Vary: Accept
  Allow: GET, HEAD, OPTIONS

  {
      "applications": "https://my_taiga/api/v1/applications",
      "userstories/attachments": "https://my_taiga/api/v1/userstories/attachments",
      "project-templates": "https://my_taiga/api/v1/project-templates",
      "issues/(?P<resource_id>\\d+)/voters": "https://my_taiga/api/v1/issues/(?P<resource_id>\\d+)/voters",
      "gitlab-hook": "https://my_taiga/api/v1/gitlab-hook",
      "milestones/(?P<resource_id>\\d+)/watchers": "https://my_taiga/api/v1/milestones/(?P<resource_id>\\d+)/watchers",
      "resolver": "https://my_taiga/api/v1/resolver",
      "user-storage": "https://my_taiga/api/v1/user-storage",
      "invitations": "https://my_taiga/api/v1/invitations",
      "projects": "https://my_taiga/api/v1/projects",
      "application-tokens": "https://my_taiga/api/v1/application-tokens",
      "tasks/(?P<resource_id>\\d+)/watchers": "https://my_taiga/api/v1/tasks/(?P<resource_id>\\d+)/watchers",
      "severities": "https://my_taiga/api/v1/severities",
      "notify-policies": "https://my_taiga/api/v1/notify-policies",
      "issues/custom-attributes-values": "https://my_taiga/api/v1/issues/custom-attributes-values",
      "issues/attachments": "https://my_taiga/api/v1/issues/attachments",
      "tasks/custom-attributes-values": "https://my_taiga/api/v1/tasks/custom-attributes-values",
      "users": "https://my_taiga/api/v1/users",
      "tasks": "https://my_taiga/api/v1/tasks",
      "userstories/(?P<resource_id>\\d+)/voters": "https://my_taiga/api/v1/userstories/(?P<resource_id>\\d+)/voters",
      "memberships": "https://my_taiga/api/v1/memberships",
      "history/task": "https://my_taiga/api/v1/history/task",
      "points": "https://my_taiga/api/v1/points",
      "userstories": "https://my_taiga/api/v1/userstories",
      "task-statuses": "https://my_taiga/api/v1/task-statuses",
      "milestones": "https://my_taiga/api/v1/milestones",
      "userstories/custom-attributes-values": "https://my_taiga/api/v1/userstories/custom-attributes-values",
      "search": "https://my_taiga/api/v1/search",
      "wiki/(?P<resource_id>\\d+)/watchers": "https://my_taiga/api/v1/wiki/(?P<resource_id>\\d+)/watchers",
      "auth": "https://my_taiga/api/v1/auth",
      "tasks/attachments": "https://my_taiga/api/v1/tasks/attachments",
      "userstory-custom-attributes": "https://my_taiga/api/v1/userstory-custom-attributes",
      "projects/(?P<resource_id>\\d+)/fans": "https://my_taiga/api/v1/projects/(?P<resource_id>\\d+)/fans",
      "priorities": "https://my_taiga/api/v1/priorities",
      "exporter": "https://my_taiga/api/v1/exporter",
      "tasks/(?P<resource_id>\\d+)/voters": "https://my_taiga/api/v1/tasks/(?P<resource_id>\\d+)/voters",
      "bitbucket-hook": "https://my_taiga/api/v1/bitbucket-hook",
      "timeline/user": "https://my_taiga/api/v1/timeline/user",
      "roles": "https://my_taiga/api/v1/roles",
      "task-custom-attributes": "https://my_taiga/api/v1/task-custom-attributes",
      "history/issue": "https://my_taiga/api/v1/history/issue",
      "history/wiki": "https://my_taiga/api/v1/history/wiki",
      "issue-custom-attributes": "https://my_taiga/api/v1/issue-custom-attributes",
      "userstory-statuses": "https://my_taiga/api/v1/userstory-statuses",
      "wiki-links": "https://my_taiga/api/v1/wiki-links",
      "webhooklogs": "https://my_taiga/api/v1/webhooklogs",
      "timeline/project": "https://my_taiga/api/v1/timeline/project",
      "issue-statuses": "https://my_taiga/api/v1/issue-statuses",
      "timeline/profile": "https://my_taiga/api/v1/timeline/profile",
      "importer": "https://my_taiga/api/v1/importer",
      "locales": "https://my_taiga/api/v1/locales",
      "issues": "https://my_taiga/api/v1/issues",
      "userstories/(?P<resource_id>\\d+)/watchers": "https://my_taiga/api/v1/userstories/(?P<resource_id>\\d+)/watchers",
      "github-hook": "https://my_taiga/api/v1/github-hook",
      "webhooks": "https://my_taiga/api/v1/webhooks",
      "wiki": "https://my_taiga/api/v1/wiki",
      "wiki/attachments": "https://my_taiga/api/v1/wiki/attachments",
      "issue-types": "https://my_taiga/api/v1/issue-types",
      "history/userstory": "https://my_taiga/api/v1/history/userstory",
      "projects/(?P<resource_id>\\d+)/watchers": "https://my_taiga/api/v1/projects/(?P<resource_id>\\d+)/watchers",
      "issues/(?P<resource_id>\\d+)/watchers": "https://my_taiga/api/v1/issues/(?P<resource_id>\\d+)/watchers"
  }

>Could you please attach an screenshot from the network tab of your javascript console when the error happens?

  Here

NB: I change in the text the URL to prevent google index it. But of course it's not my_taiga the url.  In the screenshot you get the real url.

Regards
![taiga1](https://cloud.githubusercontent.com/assets/11524096/15511408/a32f4526-21db-11e6-9f9c-786faf168ac9.png)

**Comment by superalex** [comment]
Everything seems to be ok, could you try using chrome to see if there is any more info in the console?

**Comment by jas01** [comment]
Ok chrome tell me where the problem are.

In fact it's my fault, I forget to add a « s » at ws in the

  {
  "api": "https://my_taiga/api/v1/",
  "eventsUrl": "ws://my_taiga/events",
}

inside conf.json

So the websocket don't work with ssl. After I add a « s »

  {
  "api": "https://my_taiga/api/v1/",
  "eventsUrl": "wss://my_taiga/events",
}

everything work fine now.

Thanks a lot.

Regards

**Comment by superalex** [comment]
Great! :+1:

**Comment by vincewly** [comment]
it's the same with my condition, thanks.

**Comment by velis74** [comment]
Thanks for this issue: I also just spent a while dealing with this issue. Might I suggest amending the documentation to also describe what needs to be changed when HTTPS is activated?
