### ISSUE TITLE
Task Board responsive

### ISSUE THREAD

**Issue by pinkra** [taigaio/taiga-front#1026]
As a user i want a more responsive task board in order to see all tasks and lanes without the need to reduce the page size.

**Comment by bameda** [comment]
Hi @pinkra we are working in a new redesing of the taskboard and kanban for next release and we will add a "zoom" option (https://projects.invisionapp.com/share/5U7C5B9PX#/screens/159767291)

More info at:

- card UI refactor: https://tree.taiga.io/project/taiga/us/2928
- improve colums display: https://tree.taiga.io/project/taiga/us/3166
- filters: https://tree.taiga.io/project/taiga/us/1775
