### ISSUE TITLE
Customization of task's tags color

### ISSUE THREAD

**Issue by AlbertoGuerreroMartin** [taigaio/taiga-front#1028]
Implement an option (maybe a color picker, or something similar) for customizing task's tags color.

**Comment by bameda** [comment]
This is ready for the  next release. 

The story: https://tree.taiga.io/project/taiga/us/1906?kanban-status=57868
The PRs:   https://github.com/taigaio/taiga-front/pull/1010

Thanks for your feedback

**Comment by AlbertoGuerreroMartin** [comment]
Great! Thanks

**Comment by bameda** [comment]
you are welcome
