### ISSUE TITLE
Save All Button in Edit User Story Screen

### ISSUE THREAD

**Issue by dwarakanathjagadeesan** [taigaio/taiga-front#1029]
Hi,

We have a self hosted version of taiga and it is certainly fitting the bill for us. Kudos to you guys for making this happen.
However, We have very weak internet connection in our organisation and it takes easily 7-9s to save every US fields and this is taking lot of time. 

Is there a way where we can save all changes made in US in one shot if not can there be a small fix to overcome this. 

Cheers,
Dwarak

**Comment by superalex** [comment]
Hello @dwarakanathjagadeesan 

Thank you very much for your comments about Taiga!. Right now you can't do all those changes just in one show and I'm afraid it's not a small fix, it would affect a lot to the front application. I'm tagging this issue as enhancement so we can keep your feedback and check if the community has more interest in such feature.

Regards!,
