### ISSUE TITLE
Paste file from transfer area to attachments

### ISSUE THREAD

**Issue by diegogurgel** [taigaio/taiga-front#1030]
On comment or creating a task, storie or issue it be nice if user could paste file and send it directly to attachments. And if user paste an image in the text area would be like the drop functionality.

**Comment by superalex** [comment]
Hello @diegogurgel right now you can drag&drop attachments when creating any item, just use the box "Drop attachments here!" from the lightbox:

![image](https://cloud.githubusercontent.com/assets/1579633/15664504/c1d61c06-2704-11e6-968e-457e52374ec7.png)

Regards!,

**Comment by diegogurgel** [comment]
Hi @superalex i know about this feature. But my suggestion, for instance, if user press cmd+ctrl+shift+4, select area and press cmd+v in comment area in lightbox, the image is automatically uploaded to attachments and image would be embedded to markdown like github does.

**Comment by superalex** [comment]
Ok!, thanks for your suggestion, we had an existing enhancement request for that one too (https://tree.taiga.io/project/taiga/issue/2004), I've just copied your comments there.

Regards!
