### ISSUE TITLE
ScrumBoard refresh

### ISSUE THREAD

**Issue by gregoirelemoulant** [taigaio/taiga-front#1031]
Hello, I have installed taiga on a VM. When I move a ticket, the other person connected to this scrumboard has to refresh his page to see the changement. Is it possible to make it dynamic as it is on taiga.io ?
thanks a lot

**Comment by superalex** [comment]
Sure just follow the steps to install taiga-events: https://taigaio.github.io/taiga-doc/dist/setup-production.html#_events_installation

**Comment by gregoirelemoulant** [comment]
thanks !!

**Comment by gregoirelemoulant** [comment]
i followed the steps,
then, at the step : start taiga events, I have got :"program taiga-events not found". Even if I added [watcher:taiga-events] in my circus file.

thanks
