### ISSUE TITLE
WebSocket events

### ISSUE THREAD

**Issue by gregoirelemoulant** [taigaio/taiga-front#1032]
I finished the installation of taiga events by folowing your steps. Everything seems to work fine. ( In the console there is HeartBeat Pong receiving and ping sending). But nothing happened when I move a task on the scrumboard. (I proceed the test with two computers) . The console dislays only ping and pong , but no errors. Do you have any idea ?

thanks

**Comment by superalex** [comment]
Hello @gregoirelemoulant ,

Are you receiving any errors on your logs folder?, could you please show us your circus config file?, it sounds like a backend configuration problem.

Regards,

**Comment by gregoirelemoulant** [comment]
Hello, thanks again,

circus config file : 
```
[circus]
check_delay = 5
endpoint = tcp://127.0.0.1:5555
pubsub_endpoint = tcp://127.0.0.1:5556
statsd = true

[watcher:taiga]
working_dir = /home/vagrant/taiga-back
cmd = gunicorn
args = -w 3 -t 60 --pythonpath=. -b 127.0.0.1:8001 taiga.wsgi
uid = vagrant
numprocesses = 1
autostart = true
send_hup = true
stdout_stream.class = FileStream
stdout_stream.filename = /home/vagrant/logs/gunicorn.stdout.log
stdout_stream.max_bytes = 10485760
stdout_stream.backup_count = 4
stderr_stream.class = FileStream
stderr_stream.filename = /home/vagrant/logs/gunicorn.stderr.log
stderr_stream.max_bytes = 10485760
stderr_stream.backup_count = 4

[watcher:taiga-events]
working_dir = /home/vagrant/taiga-events
cmd = /usr/local/bin/coffee
args = index.coffee
uid = vagrant
numprocesses = 1
autostart = true
send_hup = true
stdout_stream.class = FileStream
stdout_stream.filename = /home/vagrant/logs/taigaevents.stdout.log
stdout_stream.max_bytes = 10485760
stdout_stream.backup_count = 12
stderr_stream.class = FileStream
stderr_stream.filename = /home/vagrant/logs/taigaevents.stderr.log
stderr_stream.max_bytes = 10485760
stderr_stream.backup_count = 12

[env:taiga]
PATH = /home/vagrant/.virtualenvs/taiga/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
TERM=rxvt-256color
SHELL=/bin/bash
USER=taiga
LANG=en_US.UTF-8
HOME=/home/vagrant
PYTHONPATH=/home/vagrant/.local/lib/python3.4/site-packages


```

My file taigaevents.stdout.log and taigaevents.stderr.log are empty..

**Comment by gregoirelemoulant** [comment]
just in case, here is my taiga-front conf.json

```
{
    "api": "http://192.168.0.50:8000/api/v1/",
    "eventsUrl": "ws://192.168.0.50:8000/events",
    "eventsMaxMissedHeartbeats": 5,
    "eventsHeartbeatIntervalTime": 60000,
    "debug": true,
    "debugInfo": false,
    "defaultLanguage": "en",
    "themes": ["taiga"],
    "defaultTheme": "taiga",
    "publicRegisterEnabled": true,
    "feedbackEnabled": true,
    "privacyPolicyUrl": null,
    "termsOfServiceUrl": null,
    "maxUploadFileSize": null,
    "contribPlugins": []
}
```

**Comment by superalex** [comment]
Could you please execute "circusctl" to check if taiga-events is active?.

I think your conf.json isn't valid, by default taiga-events is served in port 8888 so you should have something like:

`    "eventsUrl": "ws://192.168.0.50:8888",
`

**Comment by gregoirelemoulant** [comment]
I changed the url to "eventsUrl": "ws://192.168.0.50:8888", but still dowing nothing.

after executing circusctl I have :
```
circusctl 0.13.0
circusd-stats: active
taiga: active
taiga-events: active
(circusctl)
```

**Comment by superalex** [comment]
Everything seems to be ok, could you try executing manually taiga-events?

```
cd /home/vagrant/taiga-events
/usr/local/bin/coffee index.coffee
```

**Comment by gregoirelemoulant** [comment]
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
  at errnoException (net.js:901:11)
  at Server._listen2 (net.js:1039:14)
  at listen (net.js:1061:10)
  at net.js:1143:9
  at dns.js:72:18
  at process._tickCallback (node.js:415:13)
  at Function.Module.runMain (module.js:499:11)
  at startup (node.js:119:16)
  at node.js:902:3

```

**Comment by gregoirelemoulant** [comment]
I stopped taiga-events then after running /usr/local/bin/coffee index.coffee , it seems to work (websocket recived ping...).
But it is still dowing nothing when I moove a task ..

**Comment by gregoirelemoulant** [comment]
![capture](https://cloud.githubusercontent.com/assets/17857554/15774080/cbf2a9de-297a-11e6-8c19-49d6b4882833.PNG)

hmm status code 101

**Comment by gregoirelemoulant** [comment]
![capture](https://cloud.githubusercontent.com/assets/17857554/15774199/65373916-297b-11e6-9723-68b6d3d1bb43.PNG)

hmm status code 101

**Comment by superalex** [comment]
101 is the expected status code, 

This is a screenshot from tree.taiga.io:

![image](https://cloud.githubusercontent.com/assets/1579633/15774821/bdb2e556-297e-11e6-8276-07a5776b10e3.png)

**Comment by superalex** [comment]
In the console you should see the result from subscribing different channels, something like:

![image](https://cloud.githubusercontent.com/assets/1579633/15774910/365dc11a-297f-11e6-8047-6b128ef617d8.png)

**Comment by gregoirelemoulant** [comment]
I am not receiving thos webSocket message, I really don't know why .. 
but many thanks for your help

**Comment by superalex** [comment]
May be your back isn't connecting properly with rabbitmq, could you show us your local.py file?, could you check your settings for EVENTS_PUSH_BACKEND and EVENTS_PUSH_BACKEND_OPTIONS?

**Comment by gregoirelemoulant** [comment]
```
from .common import *

MEDIA_URL = "/media/"
STATIC_URL = "/static/"

# This should change if you want generate urls in emails
# for external dns.
SITES["front"]["domain"] = "localhost:8000"

DEBUG = True
PUBLIC_REGISTER_ENABLED = True

DEFAULT_FROM_EMAIL = "no-reply@example.com"
SERVER_EMAIL = DEFAULT_FROM_EMAIL

EVENTS_PUSH_BACKEND = "taiga.events.backends.rabbitmq.EventsPushBackend"
EVENTS_PUSH_BACKEND_OPTIONS = {"url": "amqp://taiga:PASSWORD@localhost:5672/taiga"}

#EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
#EMAIL_USE_TLS = False
#EMAIL_HOST = "localhost"
#EMAIL_HOST_USER = ""
#EMAIL_HOST_PASSWORD = ""
#EMAIL_PORT = 25

```

**Comment by superalex** [comment]
Could you try enabling async tasks too? https://taigaio.github.io/taiga-doc/dist/setup-development.html#user-content-async-tasks-optional

**Comment by gregoirelemoulant** [comment]
of course, but now I'am facing this issue in trying to install async task 

![capture2](https://cloud.githubusercontent.com/assets/17857554/15780744/6685f046-29a3-11e6-8a16-18e19950364e.PNG)

**Comment by bameda** [comment]
Execute inside the directory `taiga-back` and not in the home dir.

```
cd taiga-back
workon taiga

celery -A taiga.....
```

**Comment by gregoirelemoulant** [comment]
Ok thanks, I have this 

![capture](https://cloud.githubusercontent.com/assets/17857554/15799047/058a3cb8-2a50-11e6-9bd5-faa54ddf4a80.PNG)

But it sems that taiga-events still not working ..

**Comment by superalex** [comment]
Hello @gregoirelemoulant did you finally make it work?, I don't know what more could we test, everything seemed to be ok in your installation.

**Comment by gregoirelemoulant** [comment]
nop, it still not working ! 

Let me know if you have some update.

Thanks for helping

**Comment by superalex** [comment]
I'm googling a little bit for "vagrant websockets" and some people have problems related to it. 

You could try configuring vagrant to forward the ports 8000 and 8888, updating your conf.json to use 127.0.0.1 instead of the ip

**Comment by gregoirelemoulant** [comment]
Hello again, I was not abble to make it work in vagrant. So I installed taiga on a server. Everything is ok but the taiga-events still doing nothing.

When I run circusctl , i have well 
```
circusd-stats: active
taiga: active
taiga-events: active
```
But when I move a task on the sprint board, nothing happend in the other account. 

(my taiga-events logs files are empty)

**Comment by herbsmn** [comment]
I just had a similar problem https://github.com/taigaio/taiga-events/issues/11

**Comment by herbsmn** [comment]
when i stop taiga-events and run coffee it hangs

**Comment by herbsmn** [comment]
@gregoirelemoulant do you need to do circusctl start taiga-celery?

**Comment by herbsmn** [comment]
what's supposed to happen after I type in /usr/lib/node_modules/coffee-script/bin/coffee index.coffee? What happened for you @gregoirelemoulant?

**Comment by herbsmn** [comment]
I am running Debian Jessie. What OS are you using?

**Comment by herbsmn** [comment]
Are you sure you don't have error logs in taigaevents.stderr.log? I do and it looks similar to what you had posted in here previously.

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
  at exports._errnoException (util.js:746:11)
  at Server._listen2 (net.js:1158:14)
  at listen (net.js:1184:10)
  at net.js:1282:9
  at dns.js:85:18
  at process._tickCallback (node.js:355:11)
  at Function.Module.runMain (module.js:503:11)
  at startup (node.js:129:16)
  at node.js:814:3

**Comment by herbsmn** [comment]
I ran lsof -i tcp:8888 

I then tried killing the node process that was already running on port 8888 (which says it is taiga) and then re-running the coffee script, but it didn't seem to be working because the process respawns. what in taiga is running on 8888 other than taiga-events? do i need to edit the taiga systemd configs so that taiga doesn't respawn back to port 8888?

**Comment by herbsmn** [comment]
when I turn off taiga-events with 'circusctl stop taiga-events' there no longer is anything running on port 8888. but then when i run /usr/lib/node_modules/coffee-script/bin/coffee index.coffee nothing happens. what is supposed to happen? the cursor moves to the next line and I have to hit ctrl C to be able to type anything again.

**Comment by herbsmn** [comment]
i just unfortunately don't know where to look in the logs or if there are any logs related to what is happening when it jams up like that. but the fact that @gregoirelemoulant said that taiga-events still didn't work after he did the same thing makes me assume that i'm in the same boat.

**Comment by herbsmn** [comment]
See anything wrong here?

![screenshot](https://cloud.githubusercontent.com/assets/8562898/16569145/54df64d4-4222-11e6-946f-b5f18aa5b878.png)

**Comment by herbsmn** [comment]
My Request URL says https is it supposed to say wss like this one from taiga.io?

![screen](https://cloud.githubusercontent.com/assets/8562898/16569397/7952e202-4225-11e6-9de5-6d1eff4367d5.png)

**Comment by herbsmn** [comment]
Here's what my browser shows for events using tree.taiga.io 

Looks very similar to what I get for my site. I'm still wondering if this is a Tor Browser issue. I'll test that soon.

![screenshot32](https://cloud.githubusercontent.com/assets/8562898/16572512/d5cce14e-4258-11e6-9696-8222930d99e1.png)

**Comment by herbsmn** [comment]
This was a Tor Browser issue. taiga-events doesn't work on with Tor Broswer https://github.com/taigaio/taiga-events/issues/11
