### ISSUE TITLE
Creating tasks collaboratively

### ISSUE THREAD

**Issue by drzraf** [taigaio/taiga-front#1041]
When designing the next sprint comes the time where story is split into tasks.

This can be done team-wide. Such case require a damn good level of reactivity but Taiga UI currently does not keep up.
- it's not reactive enough to let multiple people editing one story simultaneously because edits do not appear directly in other people browsers (description, assignment, notation, ...)
- more specifically (and more importantly), adding new tasks is not reflected in other team-mate browser
  until a page refresh

Is a etherpad/googledoc grade of interactivity/collaboration expectable on this matters?

**Comment by superalex** [comment]
Yes, it would be great supporting it in Taiga ;)
