### ISSUE TITLE
Cannot change project ownership if owner is no longer admin

### ISSUE THREAD

**Issue by Sebas3440** [taigaio/taiga-front#1044]
Hi!

We have a little issue with some of our projects where the project owner left our team, so at that time I unchecked his admin rights. This was in an older version of Taiga where the notion of project owner was less present.

But now we've updated to the latest version and I'm trying to regain ownership of those project so I sent the "Request Ownership" request but when the owner tries to accept it he's shown a "Permisssion denied" message.

Now the latest version no longer allows to change the admin settings for the owner which makes sense, but right now the owner isn't admin and I can't give him back his admin rights through the UI. Is there any other way I can fix this for the affected projects?

Thanks,
Sébastien G.

**Comment by bameda** [comment]
Yes, you can manage admin privileges in the taiga-back admin panel.

`http://<taiga-back-host>/admin/`
