### ISSUE TITLE
Cannot remove custom fields

### ISSUE THREAD

**Issue by MariusQuainted** [taigaio/taiga-front#1047]
**Steps to reproduce:**
- As admin create a custom field under attributes
- After creation attempt to delete custom field

**Expected result:**
- Custom field to be removed

**Actual Result:**
Website indefinitely loads and does not remove custom field

**Comment by mikaoelitiana** [comment]
Hi @MariusQuainted I was not able to reproduce this bug. Maybe it's a temporary error. Would it happen if you try again? If so can you please provide any error message from console?

**Comment by MariusQuainted** [comment]
I am able to replicate it.
I go to Admin -> Attributes - > Custom Fields
I create a custom field. I then create a user story and add these attributes.
I then return to Admin -> Attributes - > Custom Fields and tap on the delete message.

The screen then shows “Deleting custom attribute” and the Accept button is showing a loading indicator.
This shows the loading indicator and never clears or deletes the custom attribute.

There is no error message from the console as its simply not doing anything.
I did get the message 'Unable to delete custom field’ something about oompa loompas being sad

**Comment by mikaoelitiana** [comment]
Okay thankss. I will check that

Le lun. 13 juin 2016 17:34, MariusQuainted <notifications@github.com> a
écrit :

> I am able to replicate it.
> I go to Admin -> Attributes - > Custom Fields
> I create a custom field. I then create a user story and add these
> attributes.
> I then return to Admin -> Attributes - > Custom Fields and tap on the
> delete message.
>
> The screen then shows “Deleting custom attribute” and the Accept button is
> showing a loading indicator.
> This shows the loading indicator and never clears or deletes the custom
> attribute.
>
> There is no error message from the console as its simply not doing
> anything.
> I did get the message 'Unable to delete custom field’ something about
> oompa loompas being sad
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/taigaio/taiga-front/issues/1047#issuecomment-225599426>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AApLa8jHOLswcx4O-WjocrGF3XPy5-B_ks5qLWqAgaJpZM4I0MmQ>
> .
>
-- 

Mika Andrianarijaona
+261340722394
http://mikaoelitiana.name

**Comment by superalex** [comment]
I could reproduce it in the stable branch, we will try to fix it as soon as possible.
