### ISSUE TITLE
Unable to add a new member onto a project

### ISSUE THREAD

**Issue by AarthiVideep** [taigaio/taiga-front#1048]
Tried adding a new member onto a project using Admin -> Members -> Add New Members, but the alignment of the pop-up screen goes completely off, and I'm unable to scroll or view the form. And thus I'm unable to add a member. 
This was on Google Chrome (latest version).

**Comment by Xaviju** [comment]
Could you please add a screenshot?

**Comment by AarthiVideep** [comment]
Added a screenshot here but have hidden personal details / emails. 

We're using Taiga.io, and are not using any plugins. This happens not just for me, but for my colleague as well. 

<img width="1437" alt="screen shot 2016-06-14 at 4 53 10 pm" src="https://cloud.githubusercontent.com/assets/3622548/16041056/18968ac4-3251-11e6-95f9-621d809e29ff.png">

**Comment by Xaviju** [comment]
Sorry, this layout is not the expected when navigating to Admin > members > add members 

In fact, that should be only visible on the members screen.
Could you test if you have any problem in the console? (F12)
Or in your cache (Ctrl + Alt + R)

This is the expected layout for adding members:
![add_member](https://cloud.githubusercontent.com/assets/1343702/16043360/944e04e2-323f-11e6-81f0-e6f28f620a4c.png)

**Comment by AarthiVideep** [comment]
I'm managing 8 different projects, but this seems to occur only on one of them. The rest seem to be working fine. I tried it on Safari as well, and I saw the same issue. Just realised that that's the only project with 25 members... and that I'm on the Root plan which allows for only 25 members per private project. 

Would be good to inform the user of the same, instead.

**Comment by Xaviju** [comment]
Thanks for your feedback @AarthiVideep 
Could you please write to support@taiga.io with this project info and your taiga username so we can check out what's going on?
