### ISSUE TITLE
Tasks bulk insertion in User Story edit view

### ISSUE THREAD

**Issue by juanstiza** [taigaio/taiga-front#1051]
Hi!

It would be really useful if we could create tasks in bulk when editing an User Story. Right now the only way to do this is by putting a US on the sprint, go to the Taskboard and click on "Add some new tasks on bulk". Could that very same action be put besides the "Plus" button?

![image](https://cloud.githubusercontent.com/assets/5667982/16117697/5b0c0dc4-33a1-11e6-8171-8f29030f03b0.png)

**Comment by superalex** [comment]
Hello @juanstiza 

We had an existing enhancement request in Taiga for this one: https://tree.taiga.io/project/taiga/issue/3105

I've just copied your comments there (closing this one and leaving the other one open).

Thank you very much! ;)
