### ISSUE TITLE
Failed to load resource 400 (Bad Request) at https://tree.taiga.com

### ISSUE THREAD

**Issue by vishsid73** [taigaio/taiga-front#1053]
Hi,

While accessing the app, I am getting lots of errors. Have to click take me back to home or physically have to reload the page.

While inspecting the page, I found out there is this recurring request happening and it's not going through. Not sure if the reason to error is this but still the behaviour of such request recurring so fast seems like worth reporting.
Here is the request

> `https://sentry.kaleidos.net/api/9/store/?sentry_version=4&sentry_client=raven-js/1.1.18&sentry_key=eec0723b2e17473195226d71310010c4&sentry_data=%7B%22project%22%3A%229%22%2C%22logger%22%3A%22javascript%22%2C%22platform%22%3A%22javascript%22%2C%22request%22%3A%7B%22url%22%3A%22https%3A%2F%2Ftree.taiga.io%2Fproject%2Fvishsid73-lexstart-appv2%2F%22%2C%22headers%22%3A%7B%22User-Agent%22%3A%22Mozilla%2F5.0%20(Macintosh%3B%20Intel%20Mac%20OS%20X%2010_10_3)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F51.0.2704.84%20Safari%2F537.36%22%2C%22Referer%22%3A%22https%3A%2F%2Ftaiga.io%2F%22%7D%7D%2C%22exception%22%3A%7B%22type%22%3A%22TypeError%22%2C%22value%22%3A%22undefined%20is%20not%20a%20function%22%7D%2C%22stacktrace%22%3A%7B%22frames%22%3A%5B%7B%22filename%22%3A%22https%3A%2F%2Ftree.taiga.io%2Fv-1464347805458%2Fjs%2Flibs.js%22%2C%22lineno%22%3A23%2C%22colno%22%3A17321%2C%22function%22%3A%22o%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22https%3A%2F%2Ftree.taiga.io%2Fv-1464347805458%2Fjs%2Flibs.js%22%2C%22lineno%22%3A23%2C%22colno%22%3A18433%2C%22function%22%3A%22u%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22https%3A%2F%2Ftree.taiga.io%2Fv-1464347805458%2Fjs%2Flibs.js%22%2C%22lineno%22%3A23%2C%22colno%22%3A23422%2C%22function%22%3A%22r.inside%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22https%3A%2F%2Ftree.taiga.io%2Fv-1464347805458%2Fjs%2Flibs.js%22%2C%22lineno%22%3A23%2C%22colno%22%3A21097%2C%22function%22%3A%22i%22%2C%22in_app%22%3Atrue%7D%5D%7D%2C%22culprit%22%3A%22https%3A%2F%2Ftree.taiga.io%2Fv-1464347805458%2Fjs%2Flibs.js%22%2C%22message%22%3A%22undefined%20is%20not%20a%20function%22%2C%22extra%22%3A%7B%22session%3Aduration%22%3A21101209%7D%2C%22event_id%22%3A%226e04190270b441ad92314f3f189287f8%22%7D`

Have a look

**Comment by superalex** [comment]
Hello @vishsid73 

That call is done when an error in javascript is happening, could you please attach a screenshot from your js console to check what is happening?

**Comment by vishsid73** [comment]
Please see below for attached images:
![screen shot 2016-06-21 at 11 39 29 am](https://cloud.githubusercontent.com/assets/3729892/16219573/fae097dc-37a4-11e6-80f8-0d1d8cb5bb30.png)
![screen shot 2016-06-21 at 11 39 36 am](https://cloud.githubusercontent.com/assets/3729892/16219577/005403ca-37a5-11e6-8bd0-ca8727f3e2c7.png)
![screen shot 2016-06-21 at 11 39 42 am](https://cloud.githubusercontent.com/assets/3729892/16219587/0ce82828-37a5-11e6-9ece-43181faae666.png)

**Comment by superalex** [comment]
Hello @vishsid73 it was related to our sentry rejecting some request, it should be fixed now. Thank you very much for reporting and sorry for the inconvenience.

Regards!,
