### ISSUE TITLE
unsaved task description lost when changing status

### ISSUE THREAD

**Issue by drzraf** [taigaio/taiga-front#1055]
I'd though changing task state from "open" to "closed" wouldn't affect the description (that I was editing at the sae time)... but it did.
I lost what I was writing inside the description field of the task.
That's surprising, especially given that tasks status is a drop-down list which does not advert a page reload.

**Comment by superalex** [comment]
Thanks for reporting @drzraf we'll try to solve it as soon as possible.

Regards,
