### ISSUE TITLE
Dashboard for team members current task 

### ISSUE THREAD

**Issue by mikaoelitiana** [taigaio/taiga-front#1060]
A feature that would be really helpfull is a dashboard where one can check what each team member is doing at the moment, may it be a ticket, a task, etc...
I think of something like : 

| User  | Working on           |
|-------|----------------------|
| user1 | task #XXX issue #YYY |
| user2 |                      |
| user3 | issue #ZZZ           |

**Comment by superalex** [comment]
Thank you very much for the feedback @mikaoelitiana .

We had an existing enhancement request for this feature (https://tree.taiga.io/project/taiga/issue/3813), I've just added your comments there. Remember that you can upvote this issue in Taiga to raise its importance.

Regards!,

**Comment by mikaoelitiana** [comment]
Ok thanks. I will add my vote to it then. Thanks
