### ISSUE TITLE
Spinner shows on empty?

### ISSUE THREAD

**Issue by joeyhub** [taigaio/taiga-front#1063]
I've just started with Taiga and I have a lot of pages that just show the spinner.

Hopefully it's not just an issue with my installation but I assume that's what happens when something is empty.

It is very confusing and would be great if that could be changed to for example like a child sadly looking into an unwrapped Christmas present with nothing in it.

My project manager was sat there doing nothing for six and a half hours before I spotted it and explained the situation to him.

**Comment by superalex** [comment]
Hello @joeyhub 

It should be an issue with your installation, any empty content should have its proper placeholder.

Could you please your your javascript console and your taiga logs folder?

**Comment by Xaviju** [comment]
Closing this issue since we did not receive any response. Seems an installation error.

**Comment by joeyhub** [comment]
I went with Jira in the end.

However if you want I can give you most of the setup instructions for Centos 6.

You can use that to reproduce the bug or to help you create setup instructions for other systems.
