### ISSUE TITLE
Cannot change password

### ISSUE THREAD

**Issue by thnt** [taigaio/taiga-front#1065]
In change password form, the field 'current password' is required so if leave it empty the form cannot submit

**Comment by juanfran** [comment]
This is for safety. No one can change your password if you leave your account open.

**Comment by thnt** [comment]
Placeholder say: "Your current password (or empty if you have no password yet)"
User from github, gitlab has no "current password".
This field should be validate on backend, not frontend

**Comment by juanfran** [comment]
you're right, thanks

**Comment by paramoshkinandrew** [comment]
This issue already solved

**Comment by bameda** [comment]
Yep
