### ISSUE TITLE
Hide signup form on invitation page

### ISSUE THREAD

**Issue by thnt** [taigaio/taiga-front#1066]
The invitation page ignore config `publicRegisterEnabled: false` and keep showing the signup form

**Comment by juanfran** [comment]
Thanks for reporting @thnt we'll try to solve it as soon as possible.

**Comment by paramah** [comment]
i think its not a bug (but feature) :) 

If I invite new user i want give him some form to register, now if I set publicRegister to false I must create new user in django admin page.

**Comment by ChrisKaun** [comment]
Just run across this when trying to invite a new member to a project via email. 
Can completely agree with @paramah on this topic. 
If I send a invitation email to a client/user I want them to register if they don't have a account yet. 

Is it possible to add a second setting for the config.json like:
`publicRegisterEnabled: true/false` => for registry link in `.../discover` 
`invitationRegisterEnabled: true/false` => for a registration on the invitation page

**Comment by elebeaup** [comment]
I have the same use case than @ChrisKaun. I am trying to invite a new member to a project but I want to keep hiding the signup form (because I use the LDAP plugin)
