### ISSUE TITLE
'Invisible' dropdown when adding user story tags

### ISSUE THREAD

**Issue by nyschouten** [taigaio/taiga-front#1067]
When you searched for a tag, a dropdown shows all the tags you have used before. When you decide to erase your search term, the dropdown visibly goes away, but remains clickable. As a result, when you try to click in the Description field you easily accidentaly click on the invisible tag dropdown adding more tags to your user story.

Hopefully, this description makes sense.

Kind regards,
Natasja

**Comment by superalex** [comment]
Thanks for reporting @nyschouten 

@Xaviju I think you have been working on the new tag selector (master branch), could you please confirm if this one will be fixed?

**Comment by Xaviju** [comment]
This should be fixed in the new tags selector since we changed the tags layout. Will be in the next release.

**Comment by Xaviju** [comment]
Reference: https://tree.taiga.io/project/taiga/us/4302?kanban-status=38

**Comment by superalex** [comment]
Thanks! ;)
