### ISSUE TITLE
Filters cannot be removed when the tag you filter on does not exist anymore

### ISSUE THREAD

**Issue by nyschouten** [taigaio/taiga-front#1068]
Hi there,

I was cleaning up my tag list by filtering on tags in the backlog, opening the user stories with specific tags and removing the tag when unnecessary. However, once you close the story and go back to the filtered results, you cannot remove the tag filter anymore when there are no more user stories with that tag (because you removed the tag from all user stories with that tag). The only way to go back to the unfiltered results is to reload the page.

Thanks for your help in advance.

Kind regards,
Natasja

**Comment by superalex** [comment]
Thanks for reporting @nyschouten 

@juanfran I think this will be fixed with the reworking of the filters, could you please confirm?

**Comment by juanfran** [comment]
yes, on the new filters this doesn't happen.

thanks @nyschouten it'll be fixed in the next release
