### ISSUE TITLE
Clicking n times on "+" on task creation form, then fill title, creates n tasks with same title on submission

### ISSUE THREAD

**Issue by glefait-dbi** [taigaio/taiga-front#1069]
This issue happen on the USER STORY DETAILS page, when clicking on the related tasks "+". This is particularly annoying when integrated with slack.
![mw](https://cloud.githubusercontent.com/assets/7490317/16565419/53dfdcfe-420d-11e6-8448-9c53f3dfa7f9.png)

**Comment by juanfran** [comment]
I can't reproduce the issue, are you using tree.taiga or your own instance?

**Comment by glefait-dbi** [comment]
I'm using tree.taiga.io. However I tried it again today and could not reproduce it anymore.

**Comment by juanfran** [comment]
ok, if it happens again tell us, thanks @glefait-dbi
