### ISSUE TITLE
Pinning Sprint Board Drop Target.

### ISSUE THREAD

**Issue by lordloh** [taigaio/taiga-front#1076]
I have a long list of user stories and dragging it to the sprint board drop target needs scrolling while dragging :-(. It would be awesome if I could pin a drop target that would remain at the same position when I scroll. This way, dropping would be breeze.

Once I am done with a sprint, I can unpin it and pin another sprint and drop more user stories.

This is a variation of #255. How will the #255 solution work if there are multiple sprints?

**Comment by lordloh** [comment]
Oops. I referenced a wrong issue (225). I meant #255.

**Comment by lordloh** [comment]
I am attaching an image to clarify my request - 
![capture](https://cloud.githubusercontent.com/assets/2434923/16906968/af57a8ba-4c84-11e6-9b74-6df0702ffb47.JPG)

**Comment by superalex** [comment]
Hello @lordloh 

You could also use the checkboxes from the left column. Just check the userstories you need to move and use the action that will appear at the top: "move to current sprint"

**Comment by lordloh** [comment]
:+1: That works too... Just though this would be cooler and help with multiple sprints :)

@superalex - thank you

**Comment by superalex** [comment]
Thanks for the feedback @lordloh ;)

**Comment by Xaviju** [comment]
Hi @lordloh, remember than in a scrum backlog User Stories should be prioritized. Future sprints should get the top User stories from your list. If you need to look for a user story at the bottom you can use the feature that @superalex pointed out.
This is a good article on backlog: http://www.mountaingoatsoftware.com/agile/scrum/product-backlog

**Comment by lordloh** [comment]
Thank you. Sorry to bother with issues. Scrum seems to be a poorly
understood methodology with my coworkers. For six months, they used the
current sprint as the backlog. We never completed a sprint  (1 week) for 6
months and moved task from current sprint to the next :-D

Eventually I realized that my boss was abusing it :-D and that is not the
way it is supposed to be done :-D


Bharath Bhushan Lohray
भरत भूषण लोहरे
https://bharath.lohray.com/cv/ <https://bharath.lohray.com/cv/?ref=gmailSig>

**Comment by Xaviju** [comment]
@lordloh thank you for using Taiga!
