### ISSUE TITLE
Seems to silently fail if plugin is listed in plugins but not placed to `plugins` folder

### ISSUE THREAD

**Issue by everyonesdesign** [taigaio/taiga-front#1078]
Steps to reproduce:
- add a plugin to `conf.json`
- don't place the plugin files to `plugins` folder

It seems that plugins loading Promise ([see code](https://github.com/taigaio/taiga-front/blob/master/app-loader/app-loader.coffee#L36)) just swallows the error and fails silently.

**Comment by juanfran** [comment]
thanks @everyonesdesign 

it's fixed in master branch
