### ISSUE TITLE
Expand column width in Kanban view

### ISSUE THREAD

**Issue by everyonesdesign** [taigaio/taiga-front#1083]
It would be cool if we were able to resize the columns to contain 2, 3, etc. items in a row.

I saw this feature in TargetProcess (you can see it here https://youtu.be/-Ahzz2BNnJo?t=189) and I find it very usable.

**Comment by Xaviju** [comment]
Hi Yura,

We have been working on our cards recently and although it is not exactly the same behavior it would allow you to resize the cards based on a slider.
You can see the User Story wireframes nd design here: [New cards in Taiga](https://tree.taiga.io/project/taiga/us/2928?kanban-status=57868)

What do you think?

Thanks!

**Comment by everyonesdesign** [comment]
As for me, the mockups you provided look great, but I think that columns resizing is a bit different feature (not conflicting with item resizing slider interface in any way).

The slider allows you to scale the tasks appropriately for your screen or level of abstraction, but columns resizing allows you to maximize the screen usage avoiding scrolling.

Imagine a developer:
- having a big screen
- 4-5 statuses for user stories are used in his project,
- lots of stories have 'new' status,
- he'd like to see a title of the story in the list.

That mean that he'll have lots of empty space in the right side of the screen and he'll have to scroll the list to go to the last items.

**Comment by Xaviju** [comment]
Isn't that similar to this feature to reduce columns size in Taiga?
![image](https://cloud.githubusercontent.com/assets/1343702/17241596/e0db2492-5572-11e6-8d4b-b0979e077412.png)

**Comment by everyonesdesign** [comment]
Yes you're right, I forgot about it. But current implementation doesn't allow you to expand the column to fit 2 items in a row; you can only collapse the column.

Probably I stated the title of the issue in an inexplicit way, I'll change it to 'Expand column width in Kanban view'.
