### ISSUE TITLE
Project boxes shrink as the window become wider.

### ISSUE THREAD

**Issue by lordloh** [taigaio/taiga-front#1086]
![taiga 2k](https://cloud.githubusercontent.com/assets/2434923/17571825/60bb9ad6-5f17-11e6-971f-869ed91f0082.png)

The first image was a 1080p. The second was a 2K screen. I don't think this should happen.

**Comment by lordloh** [comment]
@Xaviju - Should I provide more info?
The screenshots are from Google Chrome, I just tried it on Firefox, it behaves the same.

**Comment by Xaviju** [comment]
No, its ok. I just don't have a large screen available and would like to test it and fix it in that screen.
Thanks for the info about the browsers @lordloh . :)

**Comment by lordloh** [comment]
You can move the left edge window beyond the edge of the screen and resize it from the right edge. It should simulate the behaviour on a large screen.

**Comment by lordloh** [comment]
Alternatively, I also discovered that if you zoom out on chrome to ~60% or less, it would show the same behaviour.

**Comment by Xaviju** [comment]
Mmmm I can reproduce it by zooming out but not by enlarging the window. I'll test it today on a large screen.

**Comment by lordloh** [comment]
This seems fixed in release 3.0.0

**Comment by Xaviju** [comment]
@lordloh thanks, I was going to test it again in production but you were faster. :)
