### ISSUE TITLE
Assign to option can be added in Add Issue modal dialog

### ISSUE THREAD

**Issue by grkkarthick90** [taigaio/taiga-front#1088]
Assign to option can be added in Add Issue modal dialog. So that when a issue is created we can directly assign to the respective person. Now whenever I create a new issue I'm going back again to issues page and open my last created card and assign to the specific person. If we have the assign to option in the Add Issues modal itself we can avoid this two step work as always usually people assign a card when they create.

**Comment by Xaviju** [comment]
Hi @grkkarthick90 
We have already that issue in our issues list. You can upvote it to raise its importance.

https://tree.taiga.io/project/taiga/issue/3167
