### ISSUE TITLE
Long US titles without spaces are not wrapped in Kanban view

### ISSUE THREAD

**Issue by everyonesdesign** [taigaio/taiga-front#1091]
Steps to reproduce:

1) Create a US with a long title without spaces (in practice I faced the issue when a long URL happened to be in title)
2) Preview it in Kanban view

Result: title is not wrapped and that causes kanban column to have horizontal scroll.

**Comment by bameda** [comment]
We know this error and will be fixed for next release. Thank you very much for using Taiga and for your feedback.

![kanban](https://cloud.githubusercontent.com/assets/877218/17779487/1a90e294-6568-11e6-82b1-624cfc786ace.png)

**Comment by everyonesdesign** [comment]
@bameda Cool, thanks!

**Comment by bameda** [comment]
you are welcome
