### ISSUE TITLE
Silently fails if 'kanban-status' get parameter is not numeric

### ISSUE THREAD

**Issue by everyonesdesign** [taigaio/taiga-front#1092]
Open url with not numeric `kanban-status` GET-parameter (e.g. https://tree.taiga.io/project/taiga/us/1674?kanban-status=abc

I expect some error to be shown (e.g. 404), but the card is empty without any signs of error.

In real life I faced that issue when my colleague sent me a url and typed a square brace accidentally after it.

**Comment by bameda** [comment]
this will be fixed for next release. 

Thank you for your feedback @everyonesdesign
