### ISSUE TITLE
Assign colors to tags

### ISSUE THREAD

**Issue by cesards** [taigaio/taiga-front#1094]
### UI enhancement

I wanted to use tags for this, but users are not allowed. First of all, very good job, keep working hard. I think your product is an awesome alternative to Trello. On the other hand, it would be awesome having the chance to choose tag colors. For instance, imagine there is an android app and I want a green "android" tag. I want the tag to be easily recognizable for the rest of the team.

Thank you!

**Comment by bameda** [comment]
This functionality is done for the next release.
https://tree.taiga.io/project/taiga/us/4302

Thanks for your words and for your feedback.

**Comment by cesards** [comment]
Awesome! Thanks! 🍻

**Comment by bameda** [comment]
you are welcome
