### ISSUE TITLE
can't create new sprint

### ISSUE THREAD

**Issue by peteratomic** [taigaio/taiga-front#1096]
Am here:
https://tree.taiga.io/project/resonatecoop-resonate-streaming-music-cooperative/backlog

Clicked on the green plus button in the top right and I get a modal window popup. Instead of being able to create a new sprint, I get a pre-populated box with last-sprint-name. If I click "create" however, then the field clears and displays a validation error. But I still can't click into the field and enter anything.

**Comment by peteratomic** [comment]
Firefox MAC.

**Comment by superalex** [comment]
Hello @peteratomic 

The sprint name box isn't prepopulated it's just a placeholder explaining what's your last sprint:

![image](https://cloud.githubusercontent.com/assets/1579633/18238230/32901c4e-733b-11e6-9451-a142931cccd2.png)

Probably your last sprint name is so long that it isn't shown correctly. If you just lest the placeholder without writing anything then the form will show you a validation error (which is correct). Just writing something in the text input with a valid dates should let you create the sprint.

Regards,

**Comment by peteratomic** [comment]
Got it. You might think about creating some kind of shortening function that truncates long titles into short ones. And no, I couldn't enter anything after the form validation error. Could only enter a new title after shortening the last sprint.
