### ISSUE TITLE
attachments are not available with IP address of the server but with the name server itself are available.

### ISSUE THREAD

**Issue by freyna** [taigaio/taiga-front#1098]
In our Taiga server, something is happening to us curious. In an issue, dragged and dropped a file to the comments and this caused the file is attached. The problem is that if the user logs in Taiga with the IP URL address of the server, to click the file, this is not available. Otherwise, when accessed with the URL server name, the file itself is downloaded.

**Comment by superalex** [comment]
I think it can be related to different things, It could be something related to the security of your browser (and content from different domains is loaded) or it could be related to your web server configuration. Could you check if you receive any errors in your javascript console?
