### ISSUE TITLE
Description 'save' button can act as comments 'save' button

### ISSUE THREAD

**Issue by everyonesdesign** [taigaio/taiga-front#1099]
Steps to reproduce:
- open a User Story/Ticket
- write a comment text _without saving it_
- write/change description and save it

Comment is saved also, but it should not be saved in that case.

**Comment by Xaviju** [comment]
Hi @everyonesdesign 

This is an known old behavior that we used to merge editions and comments. It should be fixed because now is unexpected.

**Comment by paramoshkinandrew** [comment]
Made pull request just now to fix it [#1161](https://github.com/taigaio/taiga-front/pull/1161)
