### ISSUE TITLE
[BUG] test yms

### ISSUE THREAD

**Issue by esloho** [taigaio/taiga-front#11]
🔥 

**Describe the bug**
Death and destruction

**How can we reproduce the behavior**
You can't

**Workarounds**
None

**Screenshots**
N/A

**Taiga environment**
All

**Desktop (please complete the following information):**
 - **OS:** Mac
 - **Browser:** Opera
 - **Version:** 666

**Additional context**
We're all gonna die

**Comment by Xaviju** [comment]
Opera 666 on Mac!! :tada: 

Thanks!!
