### ISSUE TITLE
New members who are invited to a project have blank profile pics

### ISSUE THREAD

**Issue by freejack** [taigaio/taiga-front#1102]
I have set the GRAVATAR_DEFAULT_AVATAR value in taiga-back/settings/local.py but it still doesn't seem to work.  I have public registration disabled (PUBLIC_REGISTER_ENABLED = False).  When I had public registration on, users created that way did have the placeholder image. 

This is the code for the blank profile pic:

`<img tg-bo-src="user.photo" tg-bo-alt="user.full_name_display" alt="user name">`

I'm using the master branch of taiga-back and stable branch of taiga-front

**Comment by superalex** [comment]
Probably the problem is using the master branch for taiga-back, please, use the stable branch there (master branches use to be unstable in the Taiga project).

**Comment by Kyslik** [comment]
@superalex same issue, brand new **working** installation, and only issue is default picture post registration (using stable branch, both front and back)

*GRAVATAR_DEFAULT_AVATAR* is set in `.../local.py` and if going to url (http://example.com/static/img/user-noimage.png) I can see the picture fine (green picture).

**Comment by superalex** [comment]
@Kyslik if you want gravatar to work your instance should be available from the outside network . Gravatar machines need to access http://taiga.oxid/static/img/user-noimage.png but that image isn't served to the outside (neither I can't access from my machine). In your case you should set gravatar to false.

**Comment by Kyslik** [comment]
I will work out some workarounds, thank you.
(Or turn gravsatars off)
