### ISSUE TITLE
Default Avatar results in invalid Image-URL after update to 3.0

### ISSUE THREAD

**Issue by nomorebugs** [taigaio/taiga-front#1109]
After updating to 3.0 following the update instructions [here](https://taigaio.github.io/taiga-doc/dist/upgrades.html), the default Avatars (the ones used, if a user isn't choosing any) are not shown any more, as they use a wrong URL of this type: https://www.gravatar.com/avatar/8da9e26cddf8253f8da3aefdda2d6cc5?d=https%3A%2F%2Fmy.taiga-installation.com%2Fv-1475257132248%2Fimages%2Fuser-avatars%2Fuser-avatar-01.png
I am not sure, if this is a frontend issue, as I haven't checked, where this URL is generated if the corresponding 'photo' -field is empty in db. This problem persists for newly generated accounts on 3.0.

**Comment by superalex** [comment]
Hello @nomorebugs 

Why is that url wrong?, did you check if https://my.taiga-installation.com/v-1475257132248/images/user-avatars/user-avatar-01.png exists? (that url should exist and should serve the file from your taiga-front-dist folder

**Comment by nomorebugs** [comment]
That url exists and works, but the gravatar url does not. Why isn't the local url used?

I think I get a clue, why this happens: We run Taiga behind a VPN. Gravatar has no access to this url.

**Comment by nomorebugs** [comment]
As this is a minor issue related to our installation, I think, it can be closed unless Taiga-team wants to fix it.

**Comment by superalex** [comment]
The local url isn't used because we don't know if the user has a valid gravatar image or not so we call gravatar with the default image fallback, if the user doesn't exist in gravatar we use the default image.

If your users update their own images they will be served directly with the local url.

**Comment by mschr** [comment]
I'd like to add to this issue; 

I can understand why it wouldnt work if some external service couldnt cache a local image while hidden behind VPN.

I can not understand why its not working with my installation - problem is that i run on an alternative port (my.domain.com**:33500**) but the avatar img.src does not reflect this.

I had one snatch on my installation when i re-migrated an empty database, the SITES["front"] missed the port under taiga-back/settings/local.py - which i later changed and everything was ok again, Is this the root of my problem? And if so, can it be patched on current database?

**Comment by superalex** [comment]
We have added an extra setting to taiga-front to disable gravatar. You can chance your conf.json and add "gravatar": false

**Comment by mschr** [comment]
Could the fault be with my initial error in sites["front"]? I'd love to find the root cause in code. 

A new user gets the <**alt**=""> shown and since positioning in the javascript popup/dropdown then gets errornous, open menu events bubbles to document.body, This closes popup immediately.

So news user cant enter the 'edit profile' area and fix themselves up with a new avatar :)
