### ISSUE TITLE
Mentions do not work

### ISSUE THREAD

**Issue by florisvanwoudenberg** [taigaio/taiga-front#1110]
Since the upgrade the mentions in the comments and the references to other issues / stories do not work anymore.

**Comment by superalex** [comment]
Thanks for reporting @florisvanwoudenberg I think it's working properly on descriptions but failing on comments and wiki, we will solve it as soon as possible. Sorry for the inconvenience

**Comment by florisvanwoudenberg** [comment]
The console give this error:
TypeError: o.project is undefined

**Comment by bameda** [comment]
it is fixed here https://github.com/taigaio/taiga-front/commit/603c81a981c1ff4f8417902585f5c3eafa78b845

taiga.io will be upgrade soon.

Thanks for report this bug
