### ISSUE TITLE
Added US to Epic crashes controllers

### ISSUE THREAD

**Issue by erparom** [taigaio/taiga-front#1112]
For my project (https://tree.taiga.io/project/erparom-rapharef) I bulk added several US to an epic, then created another one inside the epic (not bulk) and now Backlog dashboard, and epic dashboard crashes:
https://tree.taiga.io/project/erparom-rapharef/backlog

(Somehow I fixed it by forcing controller to point to new US inside epic and repeated the insertion. US name is "Cortes Caja")

**Comment by superalex** [comment]
Hello @erparom we are checcking your backlog and epic sections and they seems to be working ok. What's exactly the crash?

**Comment by erparom** [comment]
The crash is the error page with a nice Taiga landscape

**Comment by erparom** [comment]
No idea how I fixed it superalex, sorry I just created again the US same method, and no crash this time.

**Comment by superalex** [comment]
Could it be a cache browser problem?. I'm closing this issue if it happens again please reopen it.
