### ISSUE TITLE
Label for "Comment Tasks" on permissions missing

### ISSUE THREAD

**Issue by erparom** [taigaio/taiga-front#1115]
Label: COMMON.PERMISIONS_CATEGORIES.USER_STORIES.COMMENT_TASKS missing:

controller: admin/roles

**Comment by bameda** [comment]
Can you refresh your browser (CTRL + F5) and try it again?

**Comment by erparom** [comment]
Fixed!

**Comment by bameda** [comment]
:smile: 

![image](https://cloud.githubusercontent.com/assets/877218/19050380/9a1efebe-89ae-11e6-9135-2ff4c782b697.png)
