### ISSUE TITLE
Change status from issue list not working

### ISSUE THREAD

**Issue by diegogurgel** [taigaio/taiga-front#1116]
After upgrade to version 3.0.0 I can't change issue status directly from the list item.

![captura de tela 2016-10-03 as 19 17 17](https://cloud.githubusercontent.com/assets/2058439/19056409/6a1fcb94-899f-11e6-95fc-02a4b992b6ff.png)

**Comment by superalex** [comment]
Thanks for reporting @diegogurgel it should be fixed now.

Regards,
