### ISSUE TITLE
With publicRegisterEnabled set to false, invited users are not shown the registration option

### ISSUE THREAD

**Issue by freejack** [taigaio/taiga-front#1117]
<img width="1217" alt="screen shot 2016-10-03 at 9 08 59 pm" src="https://cloud.githubusercontent.com/assets/982085/19059407/bbd70c64-89ad-11e6-997b-735d81fcd2d7.png">

Only the login option is displayed.

Latest taiga-back and taiga-front-dist stable release.  Setting publicRegisterEnabled to true does display it but then the sign up links show up again also which is undesired.  Thanks!

**Comment by freejack** [comment]
Is this the expected behavior or is there something wrong?

**Comment by superalex** [comment]
@juanfran I think this was solved, isn't it?

**Comment by juanfran** [comment]
yes in the master branch
