### ISSUE TITLE
Wiki keeps crashing 

### ISSUE THREAD

**Issue by joelalm** [taigaio/taiga-front#1118]
Everytime I try to access the project wiki the app crashes. This is a new behaviour since the new release.

**Comment by superalex** [comment]
Hello @joelalm if this is happening in tree.taiga.io could you please write to support@taiga.io indicating your project url so we can check if there is something wrong?

**Comment by joelalm** [comment]
I would, if I could. Everything is now very flaky and is not working properly. You seem to have a major problem with the app…

.joel

**Comment by superalex** [comment]
Yes, right now we are having some issues with our servers, we are working to solve them as soon as possible. Sorry for the inconvenience.

**Comment by superalex** [comment]
@joelalm is this still happening?

**Comment by joelalm** [comment]
No, it’s better. The problems are not entirely gone but are no longer problem.

Best regards
Joel Almstedt

**Comment by superalex** [comment]
So could you please write to support@taiga.io indicating your project url and the steps to reproduce the issue so we can check if there is something wrong?
