### ISSUE TITLE
I can't change issue status from issues list page

### ISSUE THREAD

**Issue by mikaoelitiana** [taigaio/taiga-front#1120]
I used to be able to change a ticket status from the list of issue page but from latest update, this will not work anymore. I can display the list of status when I click the arrow but if I chose one new status, I get a console error message: 

`app.js:15320 Uncaught TypeError: Cannot read property 'length' of undefined`

**Comment by superalex** [comment]
Hello @mikaoelitiana we fixed this issue yesterday, could you check it's not a cache problem from your browser (clear the cache and reload the site).

Regards,

**Comment by mikaoelitiana** [comment]
Alright, I will check. Our update was monday so we certainly need to have last change from yesterday. Thanks!

**Comment by superalex** [comment]
You are welcome @mikaoelitiana
