### ISSUE TITLE
Document status types

### ISSUE THREAD

**Issue by fuzzy76** [taigaio/taiga-front#1122]
What does the special property "is archived" for user stories mean? What does "is closed" mean? These are not documented anywhere AFAIK.

**Comment by Xaviju** [comment]
We should add it to the docs, but the community-build taiga.pm has some info about that: http://taiga.pm/add-new-status/

Basically, all User Stories under ARCHIVED will be accesible but not visible by default on your kanban, taskboard.

**Comment by fuzzy76** [comment]
But will still clutter your backlog.

**Comment by Xaviju** [comment]
@fuzzy76 not sure how are you using the backlog, but a User Story shouldn't be archived in the backlog because it did not make it into an sprint yet.
If you are not using sprints you might want to use Kanban.

Please let us know how is your workflow to understand better your request.

**Comment by fuzzy76** [comment]
I use sprints. I just don't understand why I'd use archived at all. Sprints are archived when user stories in them are completed. If a user story is not to be completed, it does not belong in a sprint.

**Comment by bameda** [comment]
Yep, 'archive' is useful in kanban, to prevent a big kanban with a lot of cards. 

With Scrum it has no sense.

**Comment by velis74** [comment]
Well, it *could* be removed from the project graph / sum of total estimates?
