### ISSUE TITLE
Broken icon for users without avatar in local installation

### ISSUE THREAD

**Issue by rafpv** [taigaio/taiga-front#1124]
I have Taiga in my own server and the server can only be accessed from local network. 

After the update users without avatar have broken images. The source from images goes to gravatar but always show "404 page not found".

**Comment by superalex** [comment]
Hello @rafpv 

We know, right know in the case of users with no avatars those default images need to be accessed from the outside network so gravatar can show the fallback image.

**Comment by juanfran** [comment]
you can chance your `conf.json` and add ` "gravatar": false`

**Comment by rafpv** [comment]
Thanks!
