### ISSUE TITLE
Bug with tags

### ISSUE THREAD

**Issue by ichpen** [taigaio/taiga-front#1125]
Sorry if this is reported already, bug when attaching existing tags to UStories. 

Taiga.io (using latest Chrome browser) appears to create duplicate tags even though the correct colour coded tag is selected (I've used the mouse or arrow down keys to select). This means I have to merge identical tags to have the appropriate tag colour appear.

**Comment by superalex** [comment]
Hello @ichpen 

Thank you very much for reporting, could please detail the steps to reproduce the issue?.

**Comment by ASerzhant** [comment]
I have the same bug. 
Scenario:
1) I am creating new story and 
2) add tag with preferred color

Result: two tags, one with color and one without. Also if you are using different case for letters in the Tag you will have one correct option and another one not (all lowercase).

Workaround:
Create all Tags in Settings.

Chrome Version 53.0.2785.143

**Comment by superalex** [comment]
Hello @ASerzhant 

We could reproduce the case where using different case letters but not the other one (where the same tag is created with the same color and without). Is it happening on tree.taiga.io or in your own instance?, if it's our own instance could you please let the issue happen again and write to support@taiga.io indating the url of your project?.

Regards,

**Comment by ASerzhant** [comment]
@superalex we are using our own instance (3.0.0).

**Comment by superalex** [comment]
It should be working properly now in the stable branch.

Regards!

**Comment by ichpen** [comment]
Is it fixed on taiga.io?

**Comment by superalex** [comment]
Yes, it should be.
