### ISSUE TITLE
Adding Due Date

### ISSUE THREAD

**Issue by ASerzhant** [taigaio/taiga-front#1128]
Hello! 

One very useful feature of this kind of products is "Scheduling" with all required features. Like highlight when "Due Date" is coming for task or when the date is overdue. 
This is very useful and can help mange many tasks at time.
I did not find this feature, as well a feature request for this. 

Do you have it in the plan and, if have, when you plan to apply it? 

Thanks!

**Comment by bameda** [comment]
Hi @ASerzhant we already have this enhancement and you can upvote it. https://tree.taiga.io/project/taiga/issue/3069

Thanks for your feedback.
