### ISSUE TITLE
Dragging between kanban columns doesn't always work

### ISSUE THREAD

**Issue by tanc** [taigaio/taiga-front#1132]
When I drag a user story into a different kanban column the user story often (nearly always) jumps back to the column it was dragged from. The user story itself is updated, its just not reflected on the kanban board. Other users do however see the card moved into the new column if they have the kanban board open in their browsers.

This behaviour is observed in Safari (OS X) and Chrome (OS X). I haven't tested on other browsers but I suspect it would be the same. We have a self hosted instance on the latest release. We are using taiga-events.

Any ideas?

**Comment by tanc** [comment]
Ah, it looks like I might have been running an older version of taiga-events. I've just updated and the problem may have gone away. I'll re-open this if the problem is still there.

**Comment by superalex** [comment]
Great! :+1:
