### ISSUE TITLE
Taiga front does not display

### ISSUE THREAD

**Issue by robinhuy** [taigaio/taiga-front#1135]
I install taiga-front on my virtual server (debian 8) but after installation I access browser to: http://my_server_ip:9001/ and the web page does not display.
![image](https://cloud.githubusercontent.com/assets/12640832/19346454/8df24d8c-916d-11e6-9e42-3d1aef37b96b.png)

Here are errors in Console
![image](https://cloud.githubusercontent.com/assets/12640832/19346402/51cb03b2-916d-11e6-8881-a5427d003d34.png)

How to fix it?

**Comment by bameda** [comment]
Hi @robinhuy 

this PR https://github.com/taigaio/taiga-front/pull/1133/files should fix it. I will merge it in the stable branch right now.
