### ISSUE TITLE
Epics display show only first 30 related user stories

### ISSUE THREAD

**Issue by Twolewis** [taigaio/taiga-front#1139]
We have a large number of user stories assigned to a specific epic.  We found that only the first ~30 user stories display in the Epics module (expanding the dropdown list) and when viewing a specific epic in its own view.

Would like to see all the related user stories shown in the epic.

**Comment by bameda** [comment]
Fixed here https://github.com/taigaio/taiga-front/commit/3d557eaf47e51cad3d1cd810458593db2f53a849

Sorry for the inconvenience, thanks for report the bug and for using Taiga.
