### ISSUE TITLE
Taiga 3.0: import project error: 413 (Request Entity Too Large)

### ISSUE THREAD

**Issue by yungang** [taigaio/taiga-front#1141]
I used Taiga 2.x to manage my projects, last week upgraded to 3.0, so ,I want to export-import my project from old version Taiga to new.

when I export the project, its size is about 352M, when I import it to Taiga 3.0 version, chrome dev tool report error:

POST http://192.168.1.138/api/v1/importer/load_dump 413 (Request Entity Too Large)    app.js:24540

how to fix this ?

**Comment by bameda** [comment]
413 errors occur when the request body is larger than the server is configured to allow. Here’s how you can fix it, depending on your web server:

Set the client_max_body_size directive in nginx.conf (http://www.cyberciti.biz/faq/linux-unix-bsd-nginx-413-request-entity-too-large/) to allow bigger files.

But you don't have to install a new instance of Taiga after every new release, you only have to upgrade it. Remember that export and import projects between instances with different versions may not work properly. We publish information about upgrade process here http://taigaio.github.io/taiga-doc/dist/upgrades.html

Regards
