### ISSUE TITLE
Fold icons missing on Firefox

### ISSUE THREAD

**Issue by pdeffendol** [taigaio/taiga-front#1143]
We're running our own instance of Taiga, version 3.0.  When using Firefox, the fold icons on the Taskboard are not visible.  

![screen shot 2016-10-20 at 2 43 37 pm](https://cloud.githubusercontent.com/assets/8208/19577280/e20de5aa-96d3-11e6-9851-febd865839d2.png)

Both Chrome and Safari will show the icons.  

Turning off the CSS transform on the SVG element will cause them to display.  Perhaps the rotation origin needs to be adjusted?

![screen shot 2016-10-20 at 2 57 12 pm](https://cloud.githubusercontent.com/assets/8208/19577695/92566aa8-96d5-11e6-9002-eae9d248f1f7.png)

**Comment by pdeffendol** [comment]
It seems Firefox may not handle transforms on SVG elements the same way: https://css-tricks.com/transforms-on-svg-elements/

**Comment by Xaviju** [comment]
Is already fixed here https://github.com/taigaio/taiga-front/commit/d1cdcfafcb10ab0c84450e37a4153eb8ea6ae365 and will be updated in tree.taiga.io as soon as possible.
Thanks for reporting!
