### ISSUE TITLE
Taiga markdown : Line breaks after an ordered/unordered list is ignored

### ISSUE THREAD

**Issue by rifaj** [taigaio/taiga-front#1153]
When adding a list in the US description, the line breaks are ignored after the list. Please refer the screenshot attached. <Enter> after the lists are ignored. The issue happens only when using lists.

Expected behavior: Line breaks on <Enter> after a list.

This is happening in taiga.io.

Browser : Chrome - Latest version.

No console errors.

![taiga-markdown-no-line-break](https://cloud.githubusercontent.com/assets/8567491/20099274/aafbe1ca-a5dd-11e6-9a6d-efec629ef18d.png)

**Comment by bameda** [comment]
Hi @rifaj we are working in a new wygiwys editor (like the medium editor) that support markdown mode too. 

This should be fixed with the nest release.

**Comment by paulkernstock** [comment]
A little workaround would be using an empty third-level-heading:

    *    Abacus
    *    Bubbles
    *    Cunning
    ###
    Some Text
