### ISSUE TITLE
Arbitrary wiki max-width settings in css

### ISSUE THREAD

**Issue by richbl** [taigaio/taiga-front#1155]
**DOES:** On larger displays, the wiki is getting constrained to 1024px in width. Looking at the css in theme-taiga.css, I see 

```
.wiki {
   max-width:1024px
}
```

Not sure why this width constraint exists, as the rest of the UI appears to take advantage of existing screen width.

**SHOULD:** Wiki should not be constrained to 1024px, but use the full extent of the user display, as appropriate.

Note that I'm running current release of Taiga front-end (3.x, updated on 2016.11.07). This is a self-hosted install. I can confirm this issue on Chrome and Firefox running Linux/Ubuntu and Windows 10.

Rich

**Comment by Xaviju** [comment]
Hi  @richbl 
The fixed size in wiki is intended because of readability. According to multiple UX researches the wide of the text size impacts on the capacity of the users to read a text comfortably. And since wiki is all about reading, we decided to go with a not too wide page limited to around 15 words per line (wider than recommended).

More info here: http://baymard.com/blog/line-length-readability

Any thoughts?

**Comment by richbl** [comment]
Hi Xavier,

While I can understand the theory of readability (my graduate work was in Educational Psychology and HCI), I'd suggest that, given the width of a display, you would rather want to use some percentage of that display rather than limiting it n-words per line. Else, you do the user the injustice of having to scroll many more times up/down to read the same amount of information. Ironically, see how Wikipedia treats the subject of UX: https://en.wikipedia.org/wiki/User_experience. For particularly long articles/topics, as a user, I'd be unhappy if I'd have to scroll up/down to gather this information.

On the topic of line length, I'd recommend reading "How physical text layout affects reading from screen" by Mary Dyson. Link here: http://www.tandfonline.com/doi/abs/10.1080/01449290410001715714. PDF available here: http://images3.wikia.nocookie.net/__cb20060729105544/psychology/images/e/eb/Dyson,_M_C_(2004).pdf

The take-away suggests that line length is not well understood even today, and further, Ms. Dyson suggests that comprehension increases proportional to line length. More on this discussion can be found here: http://blog.fawny.org/2005/09/21/measures/

Subjectivity aside, at minimum, given the constraints currently imposed in the wiki along the left side of the display, you may want to at least increase the width of the Bookmarks column, and/or give the user the option to choose a more appropriate column width. At the moment, you have a Bookmarks column that wraps wiki titles unnecessarily, while not taking advantage of the available display width (at least use some of it). **Good design takes full advantage of the space in which it's presented.**

Gracias por todo.

Rich

**Comment by Xaviju** [comment]
Thanks @richbl i'll try to read the documents you suggested. Very interesting!
I'll reopen this issue as a question to gather more information from other users on how to keep the wiki readable and, at the same time, take advantage of the users screen to avoid too many scroll to gather information.
We'll think about this with the Taiga team (specially our UX experts) as well.

**Comment by bameda** [comment]
What WAI say about this: https://www.w3.org/WAI/tutorials/page-structure/styling/#line-length

**Comment by gillisig** [comment]
@richbl, I read the the part in the paper you linked about Comprehension of characters per line and it says in the second study, where they used more elaborate test of comprehension than in the first, that 55 characters per line produced better comprehension than 100. Here is the quote:

> However, Dyson and Haselgrove (2001) found that line length influences readers’ comprehension with documents at 55 characters per line producing better comprehension scores than the longest line length (100 characters per line).

Personally it is enough for me to count the number of times I get confused when reaching the end of one line and trying to find the beginning of the next one in a big block of text on Wikipedia.
