### ISSUE TITLE
[BUG] Issues view: when filtering on tags/status/type etc the filter can not be unselected

### ISSUE THREAD

**Issue by eklockare** [taigaio/taiga-front#1157]
**What is the current behavior?**
When viewing the issues list and selecting a tag/status/priority to filter on, I am unable to remove that filter.
**If the current behavior is a bug, please provide the steps to reproduce.**
1. Go into features list
2. Click Tags
3. Click a tag
4. Click red X next to tag
5. Tag disappears (As expected)
6. Click Tags
7. Click the same tag as in no. 3
8. Click red X next to tag
Unexpected:
Page turns white except for colored progress bar that is animating on top of page, page returns to issues view with the tag still there.
Same thing happens every time the red X is clicked from now on. 

**What is the expected behavior?**
Tag/status/type is removed when I press the X next to it
**Is it happening in taiga.io or in your own instance?**
taiga.io
**What browser/version are you using?**
Chrome Version 49.0.2623.87 (64-bit)

**Are there any console errors *(Ctrl + F12)* in red?**
For one click on the red X:
angular.js:13550 Unsubscribe from: changes.project.102289.issues
api.taiga.io/api/v1/user-storage/31e3e330e877c3afebfaaa25c7263df89a18fcab:1 GET https://api.taiga.io/api/v1/user-storage/31e3e330e877c3afebfaaa25c7263df89a18fcab 404 (Not Found)
angular.js:13550 Subscribe to: changes.project.102289.issues
api.taiga.io/api/v1/user-storage/31e3e330e877c3afebfaaa25c7263df89a18fcab:1 GET https://api.taiga.io/api/v1/user-storage/31e3e330e877c3afebfaaa25c7263df89a18fcab 404 (Not Found)

**Comment by superalex** [comment]
Hello @eklockare 

Could you please indicate what's the project where this is happening?, we are trying to reproduce the issue but we can't.

Regards,

**Comment by eklockare** [comment]
Hi @superalex 
The issue happens in this project:
https://tree.taiga.io/project/scypho-dev/issues

When I click `issues` in left hand menu, I arrive at this url:
https://tree.taiga.io/project/scypho-dev/issues?tags=next-gen&orderBy=-priority&q=&severity=510651,510650&order_by=-priority

Removing the parameters doesn't make a difference.
I'm on a different computer right now than the one where I reported from and the same issue occurs.
Using Version 52.0.2743.82 (64-bit) Google Chrome. Same thing in incognito mode.

If I try with Firefox(49.0.2 Mozilla Firefox for Linux Mint - 1.0) the issue does not occur.

**Comment by superalex** [comment]
Thanks @eklockare 

The url with params it's normal because taiga remembers your last search parameters.

I'm using chrome too but still can't reproduce the issue, is it happening only with some tags?, what extra tag are you selecting/removing?

**Comment by eklockare** [comment]
It is occurring with all severities and priorities as well:
* Wishlist
* Minor
* Normal
* Important
* Critical
--
* Low
* Normal
* High

Are all stuck.
