### ISSUE TITLE
Link in Custom Fields or Create New Branch Field

### ISSUE THREAD

**Issue by Aricha-kid** [taigaio/taiga-front#1164]
**Do you want to request a *feature* or report a *bug*?**
*feature*

**What is the current behavior?**
Currently when adding a description in the custom fields section you're only allowed to enter plain text, not hyperlinks.

**What is the expected behavior?**
The expected behavior would be the ability to add a link like so [link](https://github.com/taigaio/taiga-front/issues/new), to the custom fields description field to be able to easily create a new branch via the ticket by clicking on the link. 

Or alternatively have fields in Taiga.io that allow for creating a new branch in either Git, Gitlab, or Bitbucket and allow for generated pull/merge request links upon receiving one for the issue.

**Is it happening in taiga.io or in your own instance?**
This feature does not exist in Taiga.io at the moment, but I'd like to see it 😁 
**What browser/version are you using?**
Currently using Google Chrome

Thanks!

**Comment by superalex** [comment]
Thanks for reporting @Aricha-kid this is a duplicated one from: https://tree.taiga.io/project/taiga/issue/3741

I'm closing this one and leaving the taiga ticket open.

Regards,
