### ISSUE TITLE
Preview User story comments while editing.

### ISSUE THREAD

**Issue by lordloh** [taigaio/taiga-front#1165]
**Do you want to request a *feature* or report a *bug*?**
Feature

I would like to be able to preview while editing a comment on a user story.

**What is the current behavior?**
I get a text box to edit a comment on the user story. But I cannot preview it. I can however, preview a new comment.

**If the current behavior is a bug, please provide the steps to reproduce.**
NA

**What is the expected behavior?**
NA

**Is it happening in taiga.io or in your own instance?**
My own instance.

**What browser/version are you using?**
The latest Google Chrome.

**Are there any console errors *(Ctrl + F12)* in red?**
No.

Thanks for reporting!

**Comment by superalex** [comment]
Thanks for reporting @lordloh this one has been solved in the master branch, I hope it can be merged to stable soon.

Regards,
