### ISSUE TITLE
Feature Request: estimated_finish date for issues

### ISSUE THREAD

**Issue by ghost** [taigaio/taiga-front#1166]
When our customers create a new issue for a project, we found it convenient to specify a "required-finish-date" as to when the issue has to be resolved. Currently we are using a custom field for this. I thought this field would be a nice to have by default for issues, with an empty default value. This would require an addition to taiga-back, I created a Feature Request there: https://github.com/taigaio/taiga-back/issues/881

I thought this could show up in the issue overview (project/user-projectname/issues) as an additional field (that could optionally be empty). When viewing an issue (project/user-projectname/issues/1) the field could show up on the right side below the type, severity and priority.

**Comment by Xaviju** [comment]
The due date feature in Taiga should fix this. 
You may reopen this issue if it has been closed in error.
