### ISSUE TITLE
Add default value on task creation

### ISSUE THREAD

**Issue by alex-lairan** [taigaio/taiga-front#1167]
**Request a *feature***

**What is the current behavior?**

No default custom values for task creation.

**What is the expected behavior?**

The possibility to add a custom description for tasks.

------------------

Hello, I ask you today to request for a new feature.
It could be cool if we can set a default value for task creation (and epics? and more?) 

Exemple, I need to write each time

-------------------------------------
```
**As a** <Role>
**I must** <Task> <**if condition**>

**Acceptance tests:**
<Validation requirement>
```
-------------------------------------

Thanks for your response ! :)

**Comment by superalex** [comment]
Thanks for your feedback @alex-lairan I think it's a duplicated from this one: https://tree.taiga.io/project/taiga/issue/3683 I'm copying your comments there.

Regards,
