### ISSUE TITLE
Show filtered storypoints in backlog.

### ISSUE THREAD

**Issue by phgmhendrix** [taigaio/taiga-front#1171]
We love Taiga and use it in a Kanban way. We also estimate all stories.
I use the 'backlog' to view the total number of estimated points.

Would it be possible to show the total number of storypoints in the current filter?

**Comment by superalex** [comment]
Thanks @phgmhendrix we decided not to filter the backlog stats based on some users feedback, those users were working with Taiga in scrum mode. We will review it for future releases.

**Comment by phgmhendrix** [comment]
Great.
Both options should not be XOR... they can live together in my opinion :-)

**Comment by XXChester** [comment]
:+1:
