### ISSUE TITLE
Private Project but users outside project assigning stories to themselves?

### ISSUE THREAD

**Issue by mgeorge-asplundh** [taigaio/taiga-front#1176]
Hi, we have a private project set up with 4 internal users but on at least one occasion (thinking twice) we have had users totally outside our project and that we are not familiar with assign stories to themselves?

Project name is: asplundh-mobile-time-entry

Cases
--------

11/25/16 5:56 am (EST) - US 77 was assigned to Kestutis Kalvaitis  (NOT in our project, no clue who this is)

- other case can't recall but believe it happened previously.

Can you please let us know how this is possible.  I would think even with a public project this would not be allowed if user was not set up in our project?  But please confirm as we're worried about losing items or items edited that should not be.

**Comment by superalex** [comment]
If the project is private this can happen only if the role "external user" has enough privileges (a private project can define what parts of itself can be affected by external users), if you want we can remove that history entry. So it doesn't appear in your project timeline and in the user story activity.

Regards,

**Comment by mgeorge-asplundh** [comment]
Thanks alexandro...we adjusted our permissions. Yes, can you remove this history entry for us?  Thanks.

**Comment by superalex** [comment]
You are welcome @mgeorge-asplundh we have just removed that history entry.

Regards,
