### ISSUE TITLE
link to taigatribe.com not working 

### ISSUE THREAD

**Issue by Frazer** [taigaio/taiga-front#1178]
I have found a bug on taigo.io - 

On the KANBAN USER STORY pages, under where it says 'PUBLISH AS GIG IN TAIGA TRIBE'
there is a modal for  'More info'  which links to taigatribe.com - however clicking these nothing happens. You can open in a new tab, but just clicking the link does nothing.

![screen shot 2016-11-30 at 22 03 55](https://cloud.githubusercontent.com/assets/374464/20771232/e1057d7c-b748-11e6-97f2-64d37bd077bd.png)

![screen shot 2016-11-30 at 22 21 38](https://cloud.githubusercontent.com/assets/374464/20771858/87138824-b74b-11e6-8880-b4d53b87fa71.png)

Also, the links should not be relative urls. I have created a pull request for that: https://github.com/taigaio/taiga-front/pull/1177

I'm on Safari 10.0.1  There are no console errors.

**Comment by Xaviju** [comment]
Fixed in master
