### ISSUE TITLE
The image in the taigo tribe page is dead

### ISSUE THREAD

**Issue by Frazer** [taigaio/taiga-front#1179]
I have found a dead image on taigo.io - 

On the KANBAN USER STORY pages, under where it says 'PUBLISH AS GIG IN TAIGA TRIBE'
there is a modal for  'More info'  which has a dead image
https://tree.taiga.io/v-1479403352425/images/monster-fight.png which 404s

![screen shot 2016-11-30 at 22 21 38](https://cloud.githubusercontent.com/assets/374464/20771858/87138824-b74b-11e6-8880-b4d53b87fa71.png)

**Comment by superalex** [comment]
Thanks for reporting @Frazer it seems your browser is caching an old version of the front. That image now is at https://tree.taiga.io/v-1480331573391/images/monster-fight.png (the path is updated when we deploy). Could you please try again clearing your browser cache?

**Comment by Frazer** [comment]
Yes, that fixed it. Thank you
