### ISSUE TITLE
Sorting with some fields with filters leads to incomplete lists with duplicates on multiple pages

### ISSUE THREAD

**Issue by Thieum** [taigaio/taiga-front#1180]
**Do you want to request a *feature* or report a *bug*?**

bug report

**What is the current behavior?**

url of first page: 

issues?status=45&type=19,21&order_by=type&q=&page=1

![taigabugfirstpage](https://cloud.githubusercontent.com/assets/944894/20803957/113b0112-b7bf-11e6-8b73-97420d9f49d7.png)

url of second page:

issues?status=45&type=19,21&order_by=type&q=&page=2

![taigabugsecondpage](https://cloud.githubusercontent.com/assets/944894/20803958/113ae9ca-b7bf-11e6-982f-e5732bc3b6fa.png)

second page presents issues already listed in the first page (for example 1174). Some issues are not listed in the different. They would appear when sorted by subject.

**What is the expected behavior?**

All issues should be listed without duplicates, regardless of the sorting.

**Is it happening in taiga.io or in your own instance?**

own instance

**What browser/version are you using?**

IE 11 / Windows 7

**Are there any console errors *(Ctrl + F12)* in red?**

None

**Comment by superalex** [comment]
Thanks for reporting @Thieum we have detected where is the problem. I hope my PR solving it can be merged soon to stable and released: https://github.com/taigaio/taiga-back/pull/893

Regards!,

**Comment by Thieum** [comment]
Looks like it's been merged, thanks!
