### ISSUE TITLE
Creating tasks in some sprints do not result in a webhook being sent

### ISSUE THREAD

**Issue by khasinski** [taigaio/taiga-front#1181]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Webhook isn't being sent after creating ticket on one of my boards.

**If the current behavior is a bug, please provide the steps to reproduce.**
https://tree.taiga.io/project/khasinski-1-getbadges/taskboard/zadania-rozne // create a task on this board

**What is the expected behavior?**
webhook should be send like from any other board

**Is it happening in taiga.io or in your own instance?**
taiga.io

**What browser/version are you using?**
Chromium, Ubuntu 16.04

**Are there any console errors *(Ctrl + F12)* in red?**
N/A (and no)

**Comment by superalex** [comment]
Hello @khasinski are you creating tasks in bulk mode ("+" icon) or one by one?
