### ISSUE TITLE
Show the timestamp when a story is closed

### ISSUE THREAD

**Issue by hekevintran** [taigaio/taiga-front#1183]
**Before adding an issue**
Please ensure that your issue is not already reported in our [issues list](https://tree.taiga.io/project/taiga/issues?order_by=-created_date).
If this issue was already reported, remember that you can upvote it to raise its importance.

**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Cannot find the timestamp when a story is closed

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
I should be able to read the time when a story is closed

**Is it happening in taiga.io or in your own instance?**

**What browser/version are you using?**
Chrome 54

**Are there any console errors *(Ctrl + F12)* in red?**

Thanks for reporting!

**Comment by Xaviju** [comment]
Hi @hekevintran 

Currently the closing date is under the activity tab, at the bottom of the issue detail.

![closedissue](https://cloud.githubusercontent.com/assets/1343702/21040098/ec140f62-bde2-11e6-9646-c17c91c542e6.jpg)
