### ISSUE TITLE
Feature request: Make "Filter" side menu collapsable at issues view

### ISSUE THREAD

**Issue by matheusjardimb** [taigaio/taiga-front#1184]
The "Subject" collumn gets too thin and almost unreadable pretty easily. 
It'd be great to have the ability to collapse the "Filters" side menu, in order to expand the issues table.

Does it makes sense? Needs more details than that?

:)

**Comment by bameda** [comment]
Is a valid enhancement. You can upvote it at https://tree.taiga.io/project/taiga/issue/4826
