### ISSUE TITLE
Ordering of tags keeps changing in my user stories..way to stop from happening?

### ISSUE THREAD

**Issue by mgeorge-asplundh** [taigaio/taiga-front#1185]
Hi there.  I use the first tag of every user story to display a high/medium/low priority value and a color code (green/yellow/red).  That helps me at a glance in my backlog see all the color coded priority items together.

Problem is for some items, it seems the order of tags change.  I always have the high/medium/low tags first, but for some it seems after a few days/weeks the order of tags changes and its not displayed as I would like.  Please see attached screenshot and items #12 and #16 where the "low" tag was previously first, but keeps changing to later in the list.

It's not pressing but just annoying for what i'm trying to do and have these always display first.  Can I do something to prevent this?
![backlog](https://cloud.githubusercontent.com/assets/24278477/21114883/b609007a-c07c-11e6-8d67-f5660e08b511.jpg)

**Comment by superalex** [comment]
Thank you very much @mgeorge-asplundh I've done a PR to fix it here: https://github.com/taigaio/taiga-front/pull/1187, I hope it can be merged soon
