### ISSUE TITLE
Invite page doesn't respect LDAP auth type

### ISSUE THREAD

**Issue by mroe1234** [taigaio/taiga-front#1186]
When using the LDAP 'community module' for authentication, the sign-in page authenticates normally, however, the invite page doesn't allow LDAP users to log in.  This seems like a bug.  I have not yet upgraded to the just-announced version so I am running the one just previous, not sure where the version number is stored.

**Comment by bameda** [comment]
Hu @mroe1234 this bug should be in the ldap plugin and not in taiga-front

**Comment by mroe1234** [comment]
It's actually the invitation code that needs to be extended to support third party auth-types.  The auth type itself is working fine.

**Comment by bameda** [comment]
But the github auth plugin works properly.

**Comment by bameda** [comment]
Sorry, I don't know exactly how the plugin works, maybe a front plugin to overwrite the behavior or a PR to taiga-front will be enough.

**Comment by mroe1234** [comment]
It looks like the way the github auth plugin works is by actually creating a new button which is why it works.
