### ISSUE TITLE
Decide default assign user when creating new user story.

### ISSUE THREAD

**Issue by shigemk2** [taigaio/taiga-front#1190]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

Can't select assign user when creating new user story.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

I want to select assign user when creating new user story.

**Is it happening in taiga.io or in your own instance?**

taiga.io

**What browser/version are you using?**

Safari 10.0.1

**Are there any console errors *(Ctrl + F12)* in red?**

No

Thanks for reporting!

**Comment by superalex** [comment]
Hello @shigemk2 I think this is a duplicated one from: https://tree.taiga.io/project/taiga/issue/3167, isn't it?

**Comment by shigemk2** [comment]
Yes.

Sorry not for checking https://tree.taiga.io/project/taiga/issues. I had to check it out before creating issue.

**Comment by superalex** [comment]
Don't worry! :)

Thank you very much for the feedback

**Comment by Mereck13579** [comment]
Probably a bit of necro but that's the first result that comes up on Google when looking up how to assign a default user to "something" in Taiga. The link to the issue in Taiga's issue tracker is dead and I can't seem to find any other information about that... looked up "default" on taiga's issues but couldn't find anything remotely close to it.
