### ISSUE TITLE
Provide current sprint URL

### ISSUE THREAD

**Issue by klinki** [taigaio/taiga-front#1191]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the expected behavior?**
Please provide URL for current sprint. It could be something like `https://tree.taiga.io/project/project/taskboard/current-sprint`

This URL could be bookmarkable and user would get to current sprint all the time. I would much appreciate this feature, since I have bookmark in chrome bookmark toolbar to some old sprint and I have to always switch to current one or replace bookmark with newer one :)

**Comment by EBoisseauSierra** [comment]
Any update on this feature request?

**Comment by dxnacho** [comment]
Is there anyway to link a sprint as we do in tasks (by # and the number)?
