### ISSUE TITLE
bug: Partial footer in Firefox

### ISSUE THREAD

**Issue by alexivanou** [taigaio/taiga-front#1193]
Problem described at screenshot [screen-2016-12-25 00:55:28.png](https://postimg.org/image/4cvonfmuf/).
In Console logged error: The resource at “https://platform.twitter.com/widgets.js” was blocked because tracking protection is enabled.
Browser: Firefox 50

**Comment by superalex** [comment]
I've checked it too and in my case it only happens in "incognito mode":

![taiga](https://cloud.githubusercontent.com/assets/1579633/21494074/322710d2-cc0f-11e6-838b-fbf9a3ad53c4.png)

**Comment by alexivanou** [comment]
Sorry, problem is not error in blocking twitter. This is security configured option.
On my screenshot in the bottom menu displayed only 2 columns from 4. This is the problem - a half of links are absent.

**Comment by superalex** [comment]
Thanks for reporting @alexivanou we will try to fix it as soon as possible.

Regards,

**Comment by Xaviju** [comment]
Hi @alexivanou I cannot reproduce the issue, let me know if my configuration is the same as yours:
- Using firefox 50.1.0
- Tracking protextion enabled
- Using private window.
- OS. Archlinux (tested in ubuntu as well)

With this conf, when you navigate to taiga.io see only two columns in footer. I can see the console warnings for tracking protection but my footer looks good.

Is the conf ok? Can you ensure that this is still happening?

Thanks again!
