### ISSUE TITLE
USs, Tasks and Issues references not working for >3 digit numbers

### ISSUE THREAD

**Issue by rifaj** [taigaio/taiga-front#1194]
- Bug

- When I try to add a reference to any user story, if the Id referenced is single or two digits, the auto populate and hyper links are not coming properly. Please refer the attached screenshots. Also when I add only the reference, with #<story_number>, and no text, the link is not populated including 3 digit number Ids.

- Steps to reproduce
   - Any US/Issue/Task description, try to add a reference using #<story_number> for a project with ~ 900 Ids.
  - The reference link is not highlighted if the Id mentioned is >3 digits.

- This is happening in taiga.io.
- Browser : Chrome latest version.
- No console errors.

![taiga-reference](https://cloud.githubusercontent.com/assets/8567491/21498795/d361a764-cc55-11e6-96c7-8070c2370c02.png)
![taiga-refe](https://cloud.githubusercontent.com/assets/8567491/21498794/d3604f7c-cc55-11e6-9fa6-cd876413dda0.png)

**Comment by mikaoelitiana** [comment]
I can fix this but but I need some idea about how to generate a thousand issues and US to test it?

**Comment by superalex** [comment]
Thanks @mikaoelitiana this was solved in the master stable branch (https://tree.taiga.io/project/taiga/issue/4847) but we forgot closing the issue here in github too.

Regards,

**Comment by mikaoelitiana** [comment]
thanks @superalex. I will be looking for other issue to fix then

**Comment by superalex** [comment]
Great! :+1:
