### ISSUE TITLE
"400 Bad Request" when adding tags to issues

### ISSUE THREAD

**Issue by woistjadefox** [taigaio/taiga-front#1195]
When I try to add a tag on an issue, the the requests ends in a "400 (Bad Request)" error. 
Anyways, I get an JSON back from the server with the info:

> {tags: ["Invalid tag '['myTagName', '']'. The color is not a valid HEX color or null."]}

On the front-end I see the classic, red "Oops, something.." bar on the top and the tag is not applied. 
Weird is, that it works on some issues and on other not, can't figure out what makes the difference. 

Ah btw. this is happening on my own instance. Everything else works fine and I have no console errors on the client side except the known "user-storage 404 message". Also on the server side the logs are empty. 

I'm using Chrome 55 on Windows.

**Comment by superalex** [comment]
Hello!,

Are you sure you are using the last stable release of taiga-back and taiga-front?. If you did an upgrade from a previous version, did you try clearing your browser cache?

Regards,

**Comment by woistjadefox** [comment]
Hi @superalex !
Yup, I installed the latest stable release with the offered taiga scripts. Fixed some issues afterwards to get async tasks and events running. Everything works fine except this problem mentioned above. 

Just figured out today, that the issues who were able to add that certain tag can't be promoted to user stories. When I remove the tag, it works like a charm.

**Comment by superalex** [comment]
Hello @woistjadefox what's the error you are receiving when trying to promote those issues?.

We are still trying to reproduce the issue but we can't, could you please check the exact version of taiga-back and taiga-front you are using?. You could execute in both folders:

```
git branch
git describe  --always --tag
```

**Comment by woistjadefox** [comment]
When I promote the issue, I get this console message:

> POST http://*****.com/api/v1/userstories 400 (Bad Request)
> (anonymous) @ angular.js:11756
> m @ angular.js:11517
> c @ angular.js:11227
> a @ angular.js:15961
> (anonymous) @ angular.js:15977
> $eval @ angular.js:17229
> $digest @ angular.js:17045
> (anonymous) @ angular.js:17268
> o @ angular.js:5869
> (anonymous) @ angular.js:6145

The message I get from the server is the same as when I add the tag: 
> {tags: ["Invalid tag '['rohstreckev2', '']'. The color is not a valid HEX color or null."]}

I figured out that I can add the tag, when I write the whole tag name instead of choosing the tag from the suggestion drop down menu. But I still can't promote the issue afterwards. 

The versions: 
taiga-back: branch: stable  / version: 3.0.0-44-g16856cb
taiga-front: branch: stable / version: 3.0.0-stable-7-g195526d

**Comment by superalex** [comment]
Thanks @woistjadefox everything seems to be ok, we could check if taiga-front is doing the right request, could you please check in your browser the content of the patch to the issues API when adding the tag:

![image](https://cloud.githubusercontent.com/assets/1579633/21543250/c002ab3a-cdc4-11e6-9deb-46e04bc677fa.png)

**Comment by woistjadefox** [comment]
here we go: 

![screeshot](https://cloud.githubusercontent.com/assets/9056181/21544239/b5479800-cdcd-11e6-8311-de88a6deafa9.png)

**Comment by superalex** [comment]
That seems to be the problem your front is sending "" where it should be a null value. Could it be that your browser is caching a previous version of the javascript?

**Comment by woistjadefox** [comment]
I tried it in incognito mode and even with edge (i never used the browser before - so no cached data). same thing there
![screenshot](https://cloud.githubusercontent.com/assets/9056181/21544926/96130a72-cdd3-11e6-897c-6f926d41a253.png)

**Comment by superalex** [comment]
Could you go to the tag area of your project:
![image](https://cloud.githubusercontent.com/assets/1579633/21545224/16b2f1ae-cdd6-11e6-8643-7fdad6512991.png)

And check the response from the tags_colors API:

![taiga](https://cloud.githubusercontent.com/assets/1579633/21545264/7149a4aa-cdd6-11e6-9da5-11aa891a6ad9.png)

I'm trying to check if the tag was saved with an invalid color for some reason.

**Comment by woistjadefox** [comment]
Yes, this seems to be the issue. I tried to add another tag without any color and one with a color.
![screenshot](https://cloud.githubusercontent.com/assets/9056181/21546006/2a21950a-cddc-11e6-88f6-0db3f349be27.png)

**Comment by superalex** [comment]
Thank you very much @woistjadefox I think that is the issue, tags without color created from the admin area (it should have a null color, not an empty string), we will try to solve it as soon as possible.

As a workaround you can remove all those tags from the admin area, when assigned the first time from the issue detail they will be automatically created again with the null value.

**Comment by woistjadefox** [comment]
Thank you @superalex 
The workaround will do it for us right now.

**Comment by superalex** [comment]
Hello @woistjadefox it's now solved in both master and stable branches.

Regards,
