### ISSUE TITLE
Sub Epics

### ISSUE THREAD

**Issue by Hans-F** [taigaio/taiga-front#1202]
**Do you want to request a *feature* or report a *bug*?**

Feature

I would like to request sub epics to properly define dependencies.  If an epic has more than one sub epic, the progress bar should roll up all user stories from all sub epics to the upstream epic.  This feature is useful for project planning.

**Comment by bameda** [comment]
Hi @Hans-F your enhancement has been registered here https://tree.taiga.io/project/taiga/issue/4874 but this is a bad practice in Agile. We did a extend research that you can read here https://blog.taiga.io/whats-an-epic-our-research.html.
