### ISSUE TITLE
Comment section under user story is not working

### ISSUE THREAD

**Issue by vishalbuxani** [taigaio/taiga-front#1203]
I have a user story defined and when I try to write a comment for the same , I get the oompa loompa error and this has happened always.

**Comment by bameda** [comment]
- Is it happening in taiga.io or in your own instance?
- What browser/version are you using?
- Are there any console errors *(Ctrl + F12)* in red?
- If you are using your own instance: are there errors in the log files?

**Comment by vishalbuxani** [comment]
-it is happening in my own instance 
-Chrome Version 55.0.2883.87 m
-There are no console errors. Just the oompa loompa error that pops up 
-Do you know which log file should i be looking at?

**Comment by bameda** [comment]
gunicorn logs

**Comment by vishalbuxani** [comment]
i do not see any error in the gunicorn.stderr.log

**Comment by bameda** [comment]
It is very strange, an error in a POST call is because the call returns an HTTP 400 and it appears in the browser console (or in the network tab), or is a HTTP 500 and it returns an error in the gunicor log files (it is an HTTP 500).

Without more information I can't imagine what could be happening.

**Comment by vishalbuxani** [comment]
"GET /api/userstories/attachments?object_id=5&project=2 HTTP/1.1" 200 12 "http://<server-name>/project/<project-name>/us/4?kanban-status=8" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"


This is what i see in the nginx.access.log

**Comment by vishalbuxani** [comment]
This is what i get. i get a 403 forbidden request
![image](https://cloud.githubusercontent.com/assets/25089057/21943095/c672bd04-d99d-11e6-8cb2-e8acf64e309c.png)

**Comment by bameda** [comment]
The call from your browser can not reach the api (taiga-back), It seems a problem with your web server settings (or some proxy).

> A web server may or may not return a HTTP 403 Forbidden status in response to a request from a client for a web page or help indicate that the server can be reached and process the request, but refuses to take any further action. Status code 403 responses are the result of the web server being configured to deny access, for some reason, to the requested resource by the client.

**Comment by vishalbuxani** [comment]
The problem was that the user permissions to be able to comment were not set. 
The admin is responsible to set the same under user-> roles.
