### ISSUE TITLE
How to make my customized template as default selection when I create a new project?

### ISSUE THREAD

**Issue by woodman250** [taigaio/taiga-front#1205]
I created a new project "JHINNO" template by restful api of converting a project to template. 
Next, I deleted original templates "KANBAN" and "SCRUM".
Then I found there was no default  selected template, when I create n new project.
![create project](http://image18-c.poco.cn/mypoco/myphoto/20170116/12/17826521720170116120951063.png?759x631_130)
So many my colleagues created project with no select template, created new projects worked abnormal.
My question is how to make "JHINNO" template as default selected template when create new project.
Thanks.

**Comment by superalex** [comment]
Hello @woodman250 

Right now you can't, Taiga by default only will work with the two base templates Kanban and Scrum, you could customize taiga-front to use just your custom template.

Regards,
