### ISSUE TITLE
Problem with default user images in local taiga

### ISSUE THREAD

**Issue by omkartelee08** [taigaio/taiga-front#1212]
I am getting URL in following format for any default gravatar image.

1. I set up GRAVATAR_DEFAULT_AVATAR in local.py
2 I tried to gravatar:false in taiga-front conf.json

Still the issue persist.

https://www.gravatar.com/avatar/64e1b8d34f425d19e1ee2ea7236d3028?d=http%3A%2F%2F10.43.11.166%2Fv-1477393748631%2Fimages%2Fuser-avatars%2Fuser-avatar-02.png

you can observe 10.43.11.166 is my local server IP.

![untitled](https://cloud.githubusercontent.com/assets/14068930/22139775/4d59d756-df0e-11e6-9aea-d6e648c3254d.png)

**Comment by superalex** [comment]
Could you please show us the content of http://10.43.11.166/conf.json ?

**Comment by omkartelee08** [comment]
{
    "api": "/api/v1/",
    "eventsUrl": null,
    "debug": "true",
    "publicRegisterEnabled": true,
    "feedbackEnabled": false,
    "privacyPolicyUrl": null,
    "termsOfServiceUrl": null,
    "maxUploadFileSize": null,
    "gitHubClientId": null,
    "contribPlugins": [],
    "gravatar": false

}

**Comment by superalex** [comment]
GRAVATAR_DEFAULT_AVATAR isn't used anymore, and your conf.json file seems to be ok, did you check your browser console to see if there are any more errors?, did you try clearing your browser cache? (sometimes conf.json file is cached and the configuration isn't properly refreshed. Are you running the last stable releases for taiga-back and taiga-front?

Regards,

**Comment by omkartelee08** [comment]
yes, it was cache issue (Even in browser's incognito mode), Its working fine now.  Thanks a lot for very quick response.

**Comment by superalex** [comment]
You are welcome @omkartelee08 ;)
