### ISSUE TITLE
Realtime view lags behind one movement in Kanban view

### ISSUE THREAD

**Issue by tititestor** [taigaio/taiga-front#1214]
The realtime view lags behind one movement in Kanban view in two different windows of a Chrome browser

Hosted on ubuntu 16.04 (VM on VMWARE)
Have two PC
On both PC, have the same kanban view

Move one card ("card1") on PC1
Card1 on PC 2 don't move
Move another card ("card2") on PC1
"card1" move on PC2

Best regards

**Comment by bameda** [comment]
We fixed a bug related with this some time ago. Can you upgrade to the last version?

**Comment by tititestor** [comment]
Hi Bameda,

I'm using stable version (installed in december 2016).
Today, I follow the "Default Upgrad Process" in http://taigaio.github.io/taiga-doc/dist/upgrades.html

The result is the same.

Do you have an idea ?

BR,
Titi

**Comment by bameda** [comment]
![image](https://cloud.githubusercontent.com/assets/877218/22211434/46cdb160-e18d-11e6-812e-d1fb1444af98.png)

Can you upgrade taiga-front-dist again? I generate a new version right now. Remember to upgrade the browser cache.

**Comment by tititestor** [comment]
Thanks for your help, but the problem appears again.

Titi

**Comment by bameda** [comment]
Ok, I thought this was already in production but apparently we had not merged the commit (https://github.com/taigaio/taiga-back/commit/950c9a4987825c909a88e84bdf3f0f0bea1a0a14) in stable branch. Can you upgrade taiga-back, restart the service and try it again?

**Comment by tititestor** [comment]
Perfect !
Thanks for yours checks!

It's works fine now!

Best regards,
Titi

**Comment by bameda** [comment]
Great!!
