### ISSUE TITLE
Unable to change media URL 

### ISSUE THREAD

**Issue by omkartelee08** [taigaio/taiga-front#1216]
HI,

I want to change media location of the taiga local setup.
I have configured new file server on another machine.

did following changes in local.py

MEDIA_URL = "http://10.43.11.194/media/"
STATIC_URL = "http://10.43.11.194/static/"
SITES["front"]["domain"] = "10.43.11.193"

where 193 is my taiga server and 194 my file server.

still I can see, all uploaded images are being saved on my application server not over file server.

Is there any more setting I need to do ??

**Comment by superalex** [comment]
Uploading files is done using the API so those files will be always uploaded to your application server.
