### ISSUE TITLE
Taiga Media URLs

### ISSUE THREAD

**Issue by omkartelee08** [taigaio/taiga-front#1217]
I am trying to change location of media directory of my Local server.
my local.py is

from .common import *

MEDIA_ROOT = '/taiga-data/media'
STATIC_ROOT = '/taiga-data/static'

MEDIA_URL = "http://10.43.11.193/media/"
STATIC_URL = "http://10.43.11.193/static/"

Still I am not able to see images over UI.
the image url is like 
http://10.43.11.193/taiga-data/media/user/8/d/1/6/16b5dee28546642f59e5baa9c573a77c7e8c65be716e77a2b88aac7b494c/capture.png.80x80_q85_crop.png

Also, Image exists over new location, still nginx unable to fetch it. Is there any change I need to do ?

**Comment by superalex** [comment]
What should be the right url?, something like http://10.43.11.193/media/user/8/d/1/6/16b5dee28546642f59e5baa9c573a77c7e8c65be716e77a2b88aac7b494c/capture.png.80x80_q85_crop.png

**Comment by omkartelee08** [comment]
Still http://10.43.11.193/media/user/8/d/1/6/16b5dee28546642f59e5baa9c573a77c7e8c65be716e77a2b88aac7b494c/capture.png.80x80_q85_crop.png

provides me 404 error ..

**Comment by superalex** [comment]
You should figure what should be a valid url for your media file and then configure your settings according to it

**Comment by omkartelee08** [comment]
Hi,

we need to make change following change in /etc/nginx/sites-enabled/taiga

location /media {
        alias /home/taiga/taiga-back/media;
    }

change alias location to new alias.

**Comment by superalex** [comment]
Great! ;)
