### ISSUE TITLE
In my own instance projects are designated "public" by default.

### ISSUE THREAD

**Issue by sftd** [taigaio/taiga-front#1223]
version: taiga 3.0.0

In my own instance when creating project "public" is selected by default. I was not able to find if this can be changed in configuration file. Is this intended behavior as this is what I found in your documentation:

> By default, projects on Taiga are designated as “private“.

https://tree.taiga.io/support/frequently-asked-questions/whats-the-difference-between-public-and-private-projects/

Default project visibility ("public" / "private") value could / should be associated with `publicRegisterEnabled` as it probably would make sense in most cases.

**Comment by bameda** [comment]
Hi @sftd in the front client public is the selected option always when you create a new project so you have to change it in the form. There is no method to change this behavior 

![image](https://cloud.githubusercontent.com/assets/877218/22542955/9a025e96-e92e-11e6-992f-f34d4a70156a.png)

`publicRegisterEnabled` is about the ability to register new users.
