### ISSUE TITLE
e-mail notifications for non existing projects

### ISSUE THREAD

**Issue by sftd** [taigaio/taiga-front#1224]
own instance, version 3.0.0

After creating "New Test Project" project, in users e-mail notifications 4 "virtual" instances of project were created. After deleting project "virtual" instances are still there. As it was one time thing and I can't reproduce the problem, can you tell me if there is a way to get rid of them manually?

![taiga-screen](https://cloud.githubusercontent.com/assets/3073859/22560882/77a7b3b2-e976-11e6-9ef7-1e3398154816.PNG)
("New Test Project" doesn't exist anymore anywhere.)

**Comment by superalex** [comment]
Hello @sftd 

You could use the django admin (probably configured in the /admin/ url of your instance) and remove those membership objects manually.
