### ISSUE TITLE
Abillity to set default value/template for the "Description "-field

### ISSUE THREAD

**Issue by linde12** [taigaio/taiga-front#1226]
**Do you want to request a *feature* or report a *bug*?**
Feature.

**What is the current behavior?**
No way of specifying "Default values" for description.

**What is the expected behavior?**
I want to be able to set a default value(template) for the description field. Much like you have done here on github(default questions that must be answered)

**Comment by superalex** [comment]
Thanks for your suggestion @linde12 we had an existing enhancement request for this feature here (https://tree.taiga.io/project/taiga/issue/3683), I'm copying your comments there and closing this one.

Regards,
