### ISSUE TITLE
Promote user story to epic

### ISSUE THREAD

**Issue by napsy** [taigaio/taiga-front#1227]
We just had our first sprint planning using taiga in our team and figured out very quickly that a crucial feature was missing.

After a lengthily discussion about a user story and after adding a couple of subtasks, we saw that the user story was too big and is actually an epic. We tried to move the subtasks to user story backlog but this is impossible. I now have to add a new epic, rewrite all subtasks into user stories (luckily I can bulk-add) and remove the redundant user story.

It would be great to have a way to promote the user story and its subtasks into epic

**Comment by superalex** [comment]
Thanks for the feedback @napsy 

We had an existing user story (https://tree.taiga.io/project/taiga/us/4514) related to this topic, I hope it can be included in Taiga soon.

Regards,

**Comment by psydrohne** [comment]
@superalex Link is brocken. Is there a chance to get this?
