### ISSUE TITLE
Customized story point fields

### ISSUE THREAD

**Issue by napsy** [taigaio/taiga-front#1228]
It would be great to have customized story point fields, instead of assuming every project needs UX, Front, Back, etc.

When assingning story points, we sometimes need to improvise an set a point to a totally unrelated field. Concretely, we are currently missing fields like Testing, Marketing.

**Comment by bameda** [comment]
Roles are customizable in Taiga. You can manage roles in Admin > Permissions

![image](https://cloud.githubusercontent.com/assets/877218/22840264/19f97216-efcd-11e6-9ceb-a9db7d63cfe5.png)
