### ISSUE TITLE
*bug* Adding a tag from the suggestion list loses the uppercases

### ISSUE THREAD

**Issue by yakou32** [taigaio/taiga-front#1230]
I am adding a tag to a user story, ex : "[UTILITY] 2"
This tag already exists, and can be selected from the list.
After selecting it, a tag is added to the user story : "[utility] 2" : the case is not respected.
Also, in the main tag list (admin/project-values/tags), I now have two tags : "[UTILITY] 2" and"[utility] 2"

Our team is therefore trying not to use uppercase in tags anymore, but best would be to display the case consistently...

**Comment by bameda** [comment]
Why don't you mix the two tags in the admin panel? You can change uppercase to lowercase in all the item mixing both of them

First select the lowercase one and press merge
![image](https://cloud.githubusercontent.com/assets/877218/22935653/7d9b17b2-f2d3-11e6-9ace-4ce73b7ba62c.png)

Then select the upppercase one and click MERGE TAGS 
![image](https://cloud.githubusercontent.com/assets/877218/22935670/888a4f62-f2d3-11e6-95ad-546a233523df.png)

**Comment by yakou32** [comment]
This is what I did to remove any uppercases in the current tag list, and prevent any confusion for the moment.

But a user may still create an uppercased tag at any time, which would later be duplicated by the app in the tag list. Also, the uppercased version would not show up on the user stories...

**Comment by superalex** [comment]
Thanks @yakou32,

We had a small issue related to uppercased tags, most of the times we lowercased them but there were some exceptions. Now all the tags are allways created/edited in lowercase.

Regards,
