### ISSUE TITLE
Re-order US in the taskboard with drag and drop issue

### ISSUE THREAD

**Issue by bzhtux** [taigaio/taiga-front#1233]
Hi guys,

Some of our users encounter an issue when re ordering US with drag and drop. It appears with a large page of US with :

Mac OS X 10.11.6
Firefox 51.1.0.1
Taiga 3.0 (latest stable release)
You can see what happen in animated gif below.

Thank you for your help.

---

![taiga](https://cloud.githubusercontent.com/assets/3400292/23265088/f03085ac-f9e3-11e6-9136-0bf1485bb2e2.gif)

**Comment by juanfran** [comment]
thank you very much for the feedback, we can't reproduce the issue. Is there any error in the browser console?

**Comment by bzhtux** [comment]
Hi,

Here is the console output :

```
WebSocket message received: {"data":{"type":"change","pk":[1537,2404,2012,1538,2694,1453,2660,1054,1055,1056,1057,1570,1059,1060,1061,1062,1063,1064,3118,3119,3121,3122,3124,3125,3127,3128,3129,3130,2399,3132,3133,3135,3136,3137,1707,2630,2631,4017,2634,2636,2637,2638,2403,2649,2019,3678,2655,3680,3681,3805,3684,2664,3689,3690,3692,3693,3694,3699,2167,2168,2169,2172,3709,2686,2175,2176,2689,2178,2691,2180,2693,2183,1249,2193,3732,3733,3734,3735,3737,671,672,673,674,676,1701,1702,679,680,1705,682,683,1053,1566,1458,2555,3266,1706,1058,3279,2256,2259,3286,1522,3288,3289,1245,3295,1248,3297,3298,1251,3300,3301,1065,2858,2859,2311,3884,2861,1703,3859,2862,2840,2841,2843,2844,2010,3871,1516,3876,3877,3878,3880,2857,3882,3883,2860,3886,3887,2356,2358,2015,1250,2895,2905,2906,2908,2909,4448,2402,1891,2910,1893,1894,1895,1896,1897,1898,2923,1523,3013,896,1530,898,3307,900,901,902,903,1417,1418,1420,1421,1422,678,1426,4499,4501,918,919,920,1520,2179,1521,1454,1455,1456,500,3008,3009,3012,3525,3531,3532,3533,4502,3538,3546,2011,988,2013,2014,1892,2016,2017,2020,2021,2022,2535,1513,2026,1704,492,1517,494,496,497,498,499,1524,501,1526,681,2552,1529,507,1532,1533,2182,1535],"matches":"userstories.userstory"},"session_id":"8e33dd3f3e097d23ccd458c0137472f137496ea9","routing_key":"changes.project.19.userstories"}  libs.js:10:11849
WebSocket message received: {"data":{"type":"change","pk":3877,"matches":"userstories.userstory"},"session_id":"8e33dd3f3e097d23ccd458c0137472f137496ea9","routing_key":"changes.project.19.userstories"}  libs.js:10:11849
HeartBeat send PING  libs.js:10:11849
WebSocket message received: {"cmd":"pong"}  libs.js:10:11849
HeartBeat recived PONG  libs.js:10:11849
```
You can also see the screenshot attached.

Thanks again.

Yannick
![taiga-console](https://cloud.githubusercontent.com/assets/3400292/23761101/f8db35da-04f1-11e7-9940-34a6dfa4a89d.gif)

**Comment by juanfran** [comment]
that's very strange.. the console output is from taiga-events and you only receive it if other user has changed a userstory, are you logged in? try also to  stop taiga-events

**Comment by bzhtux** [comment]
Hi, yes the user is logged in with LDAP. I've tried to stop taiga-events but all page contents where blank. I forgot to mention that taiga is behind an Apache2 proxy.

**Comment by bzhtux** [comment]
Hi, since last stable version this bug is almost fixed.

**Comment by superalex** [comment]
Thanks @bzhtux we detected a bug in taiga-events that we solved recently
