### ISSUE TITLE
Allow non-admin to create CSV Reports

### ISSUE THREAD

**Issue by OpenNingia** [taigaio/taiga-front#1234]
I use a self-hosted version of Taiga and would like to allow some of my users to build the CSV Reports without giving them full admin capabilities. Is that possible?

**Comment by superalex** [comment]
You could generate the report link with an admin user and just share that link with them

**Comment by OpenNingia** [comment]
That's not helping. The point is that some users ( i.e. QA specialists ) should be able to generate issue reports without asking the admin ( i.e. me ) as I'm not always available and that is going to become a bottle neck on the workflow.
