### ISSUE TITLE
How to add a member , don't use a mail address on taiga?

### ISSUE THREAD

**Issue by littleyanglovegithub** [taigaio/taiga-front#1241]
Hello, superalex, I want to invite a new member to my project, don't use a mail address but could chose a existed member in my team.
Any thoughts on this as a feature?
I'm looking forword to your replay, thank you.
![image](https://cloud.githubusercontent.com/assets/26239080/23639689/0524ef22-0324-11e7-9714-f78d9286ce44.png)
@superalex

**Comment by superalex** [comment]
Hello!

This feature will be included in the next release, it will be complete and deployed to tree.taiga.io in the next days.

Regards,

**Comment by littleyanglovegithub** [comment]
Ok，thank you!
I have another question  whether I can upload files in the system？

**Comment by Xaviju** [comment]
Please @littleyanglovegithub open a different issue with your question to keep things ordered, or write to taigaio@googlegroups.com.

Thanks!

**Comment by littleyanglovegithub** [comment]
Oh,I am so so so sorry.
I must do it right now as you wish.

**Comment by Xaviju** [comment]
Thanks @littleyanglovegithub
