### ISSUE TITLE
Option: Automatically close parent-items when all child-items are closed

### ISSUE THREAD

**Issue by mauricewoelk** [taigaio/taiga-front#1242]
*feature*
It would be awesome if you could implement a setting to enable Taiga.IO to automatically close parent-items when all child-items are closed.

E.g.
When setting is set "true" automatically close a UserStory if all Tasks of the UserStory are closed (done). Also automatically close an Epic if all UserStorys of the Epic are closed (done).

That would be a pretty neat feature/setting/option. You already have the prequisites for this option in your settings:
![2017-03-07_13h05_24](https://cloud.githubusercontent.com/assets/26249558/23655934/c1671e2c-0337-11e7-8474-f152537a7ae9.png)
![2017-03-07_13h05_08](https://cloud.githubusercontent.com/assets/26249558/23655935/c1683622-0337-11e7-8bc5-ae557ecbd207.png)
![2017-03-07_13h05_17](https://cloud.githubusercontent.com/assets/26249558/23655936/c16a0916-0337-11e7-8164-c3d79c5987c4.png)

Thanks in advance

**Comment by benyanke** [comment]
This seems like a backend thing, to be honest.
