### ISSUE TITLE
Can I upload files in the project on the taiga？

### ISSUE THREAD

**Issue by littleyanglovegithub** [taigaio/taiga-front#1243]
Hi,I have a requirement that I wish I could  upload documents in the project on the taiga.
I can't find this feature like that.
Thank you for your help.

**Comment by superalex** [comment]
Thanks for the feedback @littleyanglovegithub we have an enhancement request for this feature [here](https://tree.taiga.io/project/taiga/issue/2813), you can upvote it to raise its importance.

Regards,

**Comment by littleyanglovegithub** [comment]
Ok,thanks a lot!
![image](https://cloud.githubusercontent.com/assets/26239080/23693606/33fd9802-0410-11e7-969a-0b0724ba8e64.png)
I find US can add  attachments ,it also can upload documents instead of I feedback.

**Comment by Xaviju** [comment]
That's right.
You can upload attachments to Stories, tasks, issues and wiki pages. 
You cannot upload independent attachments that doesn't belong to one of the items above.
Thanks @littleyanglovegithub

**Comment by littleyanglovegithub** [comment]
Yeah, I'm looking for the next release. I really want to know when the next release will come out.
Thank you for all you do.

**Comment by bameda** [comment]
Tomorrow at the end of the day (UK timezone).

**Comment by littleyanglovegithub** [comment]
Thank you very much!
