### ISSUE TITLE
Minor visual bug see screenshot

### ISSUE THREAD

**Issue by Kyslik** [taigaio/taiga-front#1248]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
<img width="300" alt="screen shot 2017-03-13 at 12 52 09 pm" src="https://cloud.githubusercontent.com/assets/2067589/23853330/5e54e094-07ec-11e7-8daf-8de6f6b421b3.png">

**What is the expected behavior?**
Edge to be nicely rounded or be square just like Watchers (when green)

**Is it happening in taiga.io or in your own instance?**
Everywhere.

**What browser/version are you using?**
Chrome latest

**Comment by Xaviju** [comment]
😮 thanks! We will fix it ASAP

**Comment by Xaviju** [comment]
Should be fixed already. Will be fixed in production today. Thanks for reporting!

**Comment by Kyslik** [comment]
Butiful, looks nice now :) thanks.
