### ISSUE TITLE
Sign in with Gitlab fails (404)

### ISSUE THREAD

**Issue by kobaj** [taigaio/taiga-front#1250]
**Before adding an issue please ensure that your issue is not already reported**
This one is similar, but I do not see any directly related to Gitlab sign in
https://github.com/taigaio/taiga-front/issues/856

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
404 page when attempting to sign in with Gitlab

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Go here: https://tree.taiga.io/register
2. Click "Sign in with Gitlab"
3. See 404 page

**What is the expected behavior?**
Not a 404 page on step 3

**Is it happening in taiga.io or in your own instance?**
taiga.io

**What browser/version are you using?**
Tried it on Firefox 52.0 and Chrome 56.0 and Mobile with Habit Browser 1.1.75

**Are there any console errors *(Ctrl + F12)* in red?**
Not that I can see

Thanks for reporting!

**Comment by Xaviju** [comment]
Thanks for reporting

**Comment by mirai924** [comment]
Bersama [Happybet188](http://happybet188.net/), anda dapat melakukan daftar judi bola dan bermain judi bola online secara nyaman hanya dengan menggunakan smartphone anda. Happybet188 selaku agen judi bola resmi dan terpercaya di Indonesia menyediakan banyak pilihan bandar judi bola ternama untuk anda.

Happybet188 agen judi bola resmi dan agen togel terbesar di Indonesia bekerja sama dengan situs Bandar judi seperti Sbobet, Maxbet, 368Bet, Asia77, SBC168, 7Sports, Bluebet33, Cbet, dan IGKBet dalam menyediakan permainan judi bola online. Dimana kami memberikan kebebasan kepada anda untuk memilih ingin bermain dan bergabung dengan bandar judi bola yang anda inginkan.

**Comment by rvelvet993** [comment]
Thanks for reporting
Insteristing about <a href="http://35.201.145.192/">poker online</a> that make u rich.

**Comment by rvelvet993** [comment]
Thanks for reporting
Insteristing about <a href="http://35.201.145.192/">Daftar Poker</a> that make u rich.
