### ISSUE TITLE
Velocity forecasting adds the selected backlog items to current sprint

### ISSUE THREAD

**Issue by rifaj** [taigaio/taiga-front#1251]
Happening in taiga.io, browser - Chrome latest version.

I tried selecting multiple backlog items clicked on velocity forecasting, and then clicked on display backlog items. All the selected items were moved to the current sprint. Lost my backlog priorities and backlog items got mixed up with current sprint backlog items.

**Comment by Xaviju** [comment]
Hi @rifaj 

When you have an open sprint in progress, the text says 'click here to add to current sprint'. If you do not have any sprints, it will create a new one. 
Adding the velocity forecasting to a sprint is a expected behavior warned on the create button. 

Is that the case?
