### ISSUE TITLE
Leaving editing a wiki page shall switch to HTML mode automatically

### ISSUE THREAD

**Issue by vlcinsky** [taigaio/taiga-front#1252]
**Do you want to request a *feature* or report a *bug*?**
Before last update it was fine, after latest update introduced HTML and Markdown modes it is more difficult to use. Hard to say a feature or a bug?

**What is the current behavior?**
Edit a wiki page.

Use Markdown mode (lower left corner of edit box).

Save or quit editing.

As a result, the page is shown in Markdown mode and there is no "HTML Mode" button to press.

**What is the expected behavior?**
Whenever I leave a wiki page editing, it shall always use HTML mode for representing the content.

I think, the "HTML or Markdown mode" feature shall apply exclusively to editing, not to representation as wiki shall always represent in such a form that it has clickable links etc.

**Is it happening in taiga.io or in your own instance?**
taiga.io

**What browser/version are you using?**
Firefox: http://whatsmybrowser.org/b/Z8WJN5N

**Comment by superalex** [comment]
Thanks for reporting @vlcinsky we solved this issue some hours ago, it's deployed in tree.taiga.io and backported to the stable branch.

Regards,

**Comment by vlcinsky** [comment]
I confirm, it works well now on tree.taiga.io (tested on wiki page as well as on task description).

thanks
