### ISSUE TITLE
User Stories complete list

### ISSUE THREAD

**Issue by claudio-b** [taigaio/taiga-front#1255]
Hello,

I have a problem with the REST API. Basically in my project I have 127 user stories, so I expect to receive all of them without filtering the list or something like that. However, when I do receive the JSON response, there are only 30 out of 127. My question is why?

This is the URL I use to obtain it: https://api.taiga.io/api/v1/userstories?project=$id

**Comment by superalex** [comment]
That's the url but should add an extra header to disable the default pagination: https://taigaio.github.io/taiga-doc/dist/api.html#_pagination

**Comment by claudio-b** [comment]
Thanks for the fast reply. Kudos to you. However, I recommend to write a notice or something where results are paginated or at least to have something like "Default limited to 30 items", mainly because people who never worked with Taiga API before might go straight to the point needed and skip Pagination and other vital parts which I should have searched for but I didn't.
