### ISSUE TITLE
Wiki revision history should be hidden by default

### ISSUE THREAD

**Issue by terrycloth** [taigaio/taiga-front#1256]
Feature request:

Being able to look through a page's revision history is useful. But I doubt that it's used so often that users typically need to have it display at all times.

I bring this up because always displaying the page's history makes it a little inconvenient to navigate the page's *current contents*. If you want to read or edit something at the bottom of a long wiki page, you might normally expect that you could hit the End key, so the browser scrolls directly to the bottom of the page. This doesn't work, however, for wiki pages with a long revision *history*, because instead you go to the bottom of the wiki's "Activity" instead of the bottom of its main content.

Another drawback: In desktop web browsers, at least, you can estimate how long a page is by looking at its window scroll bar. When page activity always displays, the scroll bar maybe instead suggests how many times the page has been edited, rather than how much stuff is in it.

I'm using a Taiga.io account in Firefox Beta 53.0b4, on Linux, Fedora 25 Workstation x86_64.

**Comment by j88per** [comment]
I second this, just adding a display: none; to class wiki-history with an icon to control, esp in angular is super easy.  It's annoying and confusing seeing the history, thinking I'm looking at the wiki page.

**Comment by eclipsenet** [comment]
I concur, this is annoying. Even better if the activity were loaded later, on demand but just hiding it be default at first will be great.

**Comment by w1ck3dg0ph3r** [comment]
I totally agree that activity should be loaded on-demand. Currently the load time of a wiki page with more than 100 editions could be tens of seconds.
