### ISSUE TITLE
Why no stop/start sprint options?

### ISSUE THREAD

**Issue by Leo-G** [taigaio/taiga-front#1257]
Jira has a stop/start sprint option, also when you close a sprint all active stories should automatically go to the next sprint,  In taiga's case you need to manually move stories, is there any reason for this particular Flow?

Another feature would like to see is instead of adding the dates, I add a time period and it automatically selects the dates.

**Comment by Shivaprasad2452** [comment]
I also have the same question, can you add this tasks  as soon

**Comment by stelcheck** [comment]
In JIRA, if I close a sprint where there are still unfinished tickets, it will ask me if I want to move them to the backlog or next sprint. I think that would be quite a nice feature to have here.

**Comment by stefano-cherchi** [comment]
Hi, I see that the feature is still missing in v6. Any chance it will be implemented any time soon? TBH I find pretty odd that such an obvious feature for a Scrum Team is not considered high priority.
