### ISSUE TITLE
Link from task to wiki page leads to task

### ISSUE THREAD

**Issue by vlcinsky** [taigaio/taiga-front#1260]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Created wiki page and wanted to link to it from task comment. Resulting link was broken (leading to task and not wiki).

**If the current behavior is a bug, please provide the steps to reproduce.**
Create a wiki page

In a task, add a comment trying to link to the wiki page. Tried ```[[performance]]```, ```[[performance|performance]]``` and ```[performance](performance)```

**What is the expected behavior?**
Links to wiki page shall work from anywhere, if they follow defined syntax.

**Is it happening in taiga.io or in your own instance?**
taiga.io

**What browser/version are you using?**
Firefox 51.0 on Ubuntu

**NB**
Taiga has totally changed our working style and productivity (in positive way). However, wiki is the weakest part of it as we have to deal with syntax, broken features and cannot focus on progressing to other tasks.

**Comment by jespino** [comment]
Now must work

**Comment by vlcinsky** [comment]
I can confirm it works now.
Thanks for the fix.
