### ISSUE TITLE
Custom fields according to Tags

### ISSUE THREAD

**Issue by Kels** [taigaio/taiga-front#1264]
Hello,

The tags feature is great and helps me to quickly filter my user stories and tasks.
When I add a new task custom field, this one is available for all my tasks. After editing them, I noticed that the custom field was updated only for somes tags.

Is it possible to configure custom fields per tags ?

Kelson

**Comment by jespino** [comment]
Actually no, custom fields are linked to tasks, user stories, epics and issues (in the database). Add a relation with tags (which are simply a list of strings) is complicated.
