### ISSUE TITLE
Broken templates on delete account modal

### ISSUE THREAD

**Issue by dhettler** [taigaio/taiga-front#1267]
**Before adding an issue**
Please ensure that your issue is not already reported in our [issues list](https://tree.taiga.io/project/taiga/issues?order_by=-created_date).
If this issue was already reported, remember that you can upvote it to raise its importance.

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
`LIGHTBOX.DELETE_ACCOUNT.SUBTITLE` and `LIGHTBOX.DELETE_ACCOUNT.NEWSLETTER_LABEL_TEXT` are displayed.

**If the current behavior is a bug, please provide the steps to reproduce.**
Click "Delete Taiga account" in user settings

**What is the expected behavior?**
Display the real text

**Is it happening in taiga.io or in your own instance?**
taiga.io

**What browser/version are you using?**
Chrome 56

**Are there any console errors *(Ctrl + F12)* in red?**
Probably unrelated:
```
X-Frame-Options may only be set via an HTTP header sent along with a document. It may not be set inside <meta>.
```

Thanks for reporting!

**Comment by Xaviju** [comment]
Thanks for reporting
