### ISSUE TITLE
Failed to create a private project after deleting one. On Seed Plan

### ISSUE THREAD

**Issue by andre-mota** [taigaio/taiga-front#1268]
After deleting a private project, I tried to create a new one, but it says I have reached the maximum number of private projects,

When I click on `Change your current plan` it says "You currently have no private projects so we believe that the Seed plan might work great for you.".

**Comment by Xaviju** [comment]
Could you try to log out and log in again. I think this is a known bug.
Please let me know if it keeps failing.

**Comment by andre-mota** [comment]
@Xaviju It worked. Forgot to test that before submitting the issue. Thanks!

**Comment by Xaviju** [comment]
@andre-mota no problem. Thanks for reporting
