### ISSUE TITLE
Some words missing on 'too many private projects' alert.

### ISSUE THREAD

**Issue by andre-mota** [taigaio/taiga-front#1269]
I believe some words and punctuation are missing on the alert after the word "private".

![selection_175](https://cloud.githubusercontent.com/assets/2658097/24364718/8e6c0292-130b-11e7-85c4-59454590beb9.png)

**Comment by Xaviju** [comment]
Hi @andre-mota could you please let us know where is this happening to reproduce the error?

**Comment by andre-mota** [comment]
@Xaviju After deleting a private project, I tried to create a new one, and I got that error. Just like [this issue](https://github.com/taigaio/taiga-front/issues/1268)

**Comment by Xaviju** [comment]
So, 
1. you deleted a private project
2. You tried to create a new one (kanban or scrum)
Result: You saw that error on the creation page

Is the above correct? Otherwise, please let me know how to reproduce

**Comment by andre-mota** [comment]
Yes, exactly that. If it matters, it was scrum and on Seed plan.
