### ISSUE TITLE
Timeline just shows spinning dial - never completes

### ISSUE THREAD

**Issue by enly1** [taigaio/taiga-front#1270]
**Before adding an issue**
Please ensure that your issue is not already reported in our [issues list](https://tree.taiga.io/project/taiga/issues?order_by=-created_date).
If this issue was already reported, remember that you can upvote it to raise its importance.

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
Viewing timeline on a new project simply shows a multi-colour spinner and never completes.
Firefox console sees errors about fonts 
downloadable font: kern: Too large subtable, table discarded (font-family: "OpenSans-Light" style:normal weight:normal stretch:normal src index:0) source: https://tree.taiga.io/v-1490604436010/fonts/OpenSans-Light.ttf

Also, other errors reported:

Firefox can’t establish a connection to the server at wss://api.taiga.io/events.  app.js:3:3864
The connection to wss://api.taiga.io/events was interrupted while the page was loading.

**If the current behavior is a bug, please provide the steps to reproduce.**
Simply create a new kenban project (private) and view timeline (with or without creating any tasks)

**What is the expected behavior?**
See a timeline :-)

**Is it happening in taiga.io or in your own instance?**
taiga.io 

**What browser/version are you using?**
Firefox 52.0.1 (32-bit) and Chrome Version 56.0.2924.87 (64-bit)

**Are there any console errors *(Ctrl + F12)* in red?**
See above comments

Thanks for reporting!

**Comment by theriverman** [comment]
+1

I happen to experience the same issue on my own, self-hosted instance.
According to the upgrade guide, I updated both the front- and back-end, rebooted the OS, but still no luck.
In the afternoon it did the same on the kanban module too, but that seems to be alright for now.
Timeline, however, is still stuck at loading and I'm getting the same font-related error just as OP.

/riverman

**Comment by Xaviju** [comment]
@enly1 is it still happening? Did you try to refresh you cache?

**Comment by enly1** [comment]
I put  comment on the Taiga timeline saying all was well as the link from the email notification took me there.   I then checked my timeline and it was working, so reporting that.

However, after refreshing the page, it looks to be broken again.  (although eventually it did eventually stop spinning after maybe a minute) 

As I type this i'm still waiting for my project timeline to do anything other than spin the spinner.

So looks a bit broken and doesn't look cache related ( well not obviously )

Firefox can’t establish a connection to the server at wss://api.taiga.io/events.  app.js:3:3864
The connection to wss://api.taiga.io/events was interrupted while the page was loading.  app.js:3:3864
Firefox can’t establish a connection to the server at wss://api.taiga.io/events.  app.js:3:3864
WebSocket error: [object Event]

Not sure if closing and re-opening websockets is part of the problem but the above is being reported over and over about 5 times at one point.

**Comment by enly1** [comment]
FYI - leaving the site and then coming back in on this link and then swapping to the taiga timeline and then my project timeline both show the timelines without a spinner.

https://tree.taiga.io/project/taiga/issue/5059

Maybe cached, maybe just working with new clean websockets.

**Comment by Xaviju** [comment]
Thanks @enly1 we cannot reproduce it but we will test it further to see if there is any problem with the timeline.
We are working on the Taiga infrastructure so it might be related to it. Let us know if it stops happening.

**Comment by iwkse** [comment]
That's something I'm also experiencing. When I check the XHR calls, I see the timeline api returns an empty JSON or not authenticated error.
Any hints?

**Comment by barnacker** [comment]
Same issue: https://myserver.domain/api/v1/timeline/project/1?only_relevant=true&page=1
This url only returns [] in the body.
Looks like an empty JSON list

**Comment by iwkse** [comment]
@barnacker I fixed it forcing the broker_url in settings/celery.py 

 It seems EVENTS_PUSH_BACKEND_OPTIONS in settings/local.py is basically ignored.

if I set broker_url in settings/celery.py to be different from the default amqp://guest:guest@localhost:5672//  but equal to EVENTS_PUSH_BACKEND_OPTIONS everything works.

Wonder why though.
