### ISSUE TITLE
Missing wysiwyg bar

### ISSUE THREAD

**Issue by tititestor** [taigaio/taiga-front#1271]
Sorry, I'm not sure about the problem
After upgrade back and front, I cannot see my "wysiwyg" bar with buttons

![capture](https://cloud.githubusercontent.com/assets/20988933/24413357/795d07b8-13db-11e7-934c-f3d199fdb135.JPG)

Taiga turn on Ubuntu server 16.04

Thanks for your help

**Comment by Xaviju** [comment]
Check our latest release to see how it works: https://blog.taiga.io/taiga-perovskia-atriplicifolia-release-310.html

**Comment by tititestor** [comment]
Oops, thanks and sorry!

**Comment by Xaviju** [comment]
No problem, thanks for reporting
