### ISSUE TITLE
Mentions not working property if username has a dot in 3.1

### ISSUE THREAD

**Issue by magalhas** [taigaio/taiga-front#1272]
After updating do Taiga 3.1 mentions to users that contain a dot (.) in their username is not working. Check the attached screenshot for an example.

![screen shot 2017-03-29 at 11 30 19](https://cloud.githubusercontent.com/assets/1500063/24450554/38d326da-1473-11e7-86e8-8fcce75624a6.png)

**Comment by superalex** [comment]
Hello @magalhas when did you udpate your instance?, we fixed this issue some days ago in stable branch.

**Comment by magalhas** [comment]
Hi @superalex . I've updated it a couple of days ago (27th March).

**Comment by superalex** [comment]
Could you try updating taiga-front again?

**Comment by magalhas** [comment]
I will and I'll let you know how it goes in the incoming days.

**Comment by superalex** [comment]
Great! :+1:
