### ISSUE TITLE
Include version number in frontend for non-admins

### ISSUE THREAD

**Issue by lofidevops** [taigaio/taiga-front#1278]
**Do you want to request a *feature* or report a *bug*?**
Feature.

**What is the current behavior?**
Version number is not visible from the frontend / browser / for non-admins. See #1276

**What is the expected behavior?**
While browsing a Taiga instance as an anonymous or regular logged in user I can see what version of Taiga is running. This is helpful, for example, when reporting issues.

As an arbitrary example, the footer of https://try.gogs.io/gogs includes the version of the Gogs instance that generated that page.

**Is it happening in taiga.io or in your own instance?**
Both.

**What browser/version are you using?**
* Firefox 52
* Taiga version unknown

**Are there any console errors *(Ctrl + F12)* in red?**
N/A

**Comment by ajay2507** [comment]
Is it still open?. Can I make this enhancement?.

**Comment by superalex** [comment]
Hello @ajay2507 

That would be great, just consider our contributing guidelines: https://tree.taiga.io/support/frequently-asked-questions/how-can-i-contribute-to-taiga/#propose-some-feature-or-enhancement before starting to work.

Regards,

**Comment by ajay2507** [comment]
@superalex As I am new to this project. I need some info.  Currently I can see the footer like this
<img width="942" alt="img" src="https://cloud.githubusercontent.com/assets/21375014/26603608/69a636ea-4555-11e7-9e7d-8e0e2dd0dd8b.png">

Where I need to include the Version number?. 
From where I can get version number.?

**Comment by superalex** [comment]
Hello @ajay2507 I think that page is https://taiga.io and not https://tree.taiga.io, if you want to include the version number in the https://tree.taiga.io footer I think it could be probably related to the execution of the npm run/build commands. I think doing it manually on every release will be very prone to errors. 

About where to include the version exactly, part of your proposal should include the user experience and design about it: https://tree.taiga.io/support/frequently-asked-questions/how-can-i-contribute-to-taiga/#propose-some-feature-or-enhancement

Regards,
