### ISSUE TITLE
X-Frame-Options may only be set via an HTTP header sent along with a document. It may not be set inside <meta>.

### ISSUE THREAD

**Issue by mrjester888** [taigaio/taiga-front#1283]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
Browser Console Warning:  X-Frame-Options may only be set via an HTTP header sent along with a document. It may not be set inside <meta>.

**If the current behavior is a bug, please provide the steps to reproduce.**
Open browser dev tools console.  Load taiga.  See warning.

**What is the expected behavior?**
No warning message.

**Is it happening in taiga.io or in your own instance?**
https://tree.taiga.io
and local instance

**What browser/version are you using?**
Chrome 56.0.2924.87

**Are there any console errors *(Ctrl + F12)* in red?**
 X-Frame-Options may only be set via an HTTP header sent along with a document. It may not be set inside <meta>.

Thanks for reporting!

**Comment by LeGiangAnh** [comment]
Got the same issue for hosted version

**Comment by theriverman** [comment]
+1
same issue here on hosted version

**Comment by octopusx** [comment]
+1
Can reproduce the issue reliably on a local instance.

**Comment by dohlin** [comment]
Can also replicate the issue on local instance; I also get it on https://tree.taiga.io too.  Both using latest version of Chrome.

**Comment by yonas** [comment]
+1

**Comment by sekkinsan** [comment]
+1
Issue is faced on hosted version as well.

**Comment by thejockel** [comment]
+1

**Comment by pypetey** [comment]
+1
