### ISSUE TITLE
Feature Request: Mattermost plugin / Mattermost Webhook interaction

### ISSUE THREAD

**Issue by theriverman** [taigaio/taiga-front#1284]
**Do you want to request a *feature* or report a *bug*?**
request a feature

**What is the current behavior?**
Could not find an easy way to connect Taiga with Mattermost.

**If the current behavior is a bug, please provide the steps to reproduce.**
N/A
**What is the expected behavior?**

When a user gets assigned to a task/user story/epic/whatever in Taiga, send him (@-mention him?) a message in a specified channel on Mattermost, like:
> @John assigned task `Request input for GUI` to @Brad in Board `Video Game UI.`

This is one scenario, however, a Mattermost BOT could inform the user about every change, such as about a task/US status change, deletion of task/us, etc..etc..
The Mattermost desktop client would pop in the corner and let the user know about the change and could also help a team organize its tasks.

I believe that webhooks might be able to handle this request, but I lack of knowledge to do this.
Opinions?

[BTW: Mattermost is a free, open-source alternative to Slack. It can be hosted and managed locally. Brilliant app for team communications.]

**Is it happening in taiga.io or in your own instance?**
N/A 
**What browser/version are you using?**
N/A
**Are there any console errors *(Ctrl + F12)* in red?**
N/A
Thanks for reporting!

**Comment by bameda** [comment]
@theriverman try to use the slack integration with mattermost, it should works.

**Comment by theriverman** [comment]
Thank you for the tip, @bameda !
I set it up and seems to work without a flaw, very nice job @jespino !!

You rock, lads!
