### ISSUE TITLE
Can't browse 127.0.0.1:9001/register

### ISSUE THREAD

**Issue by sonnyESP24** [taigaio/taiga-front#1285]
Always redirects me to /login. Other stuff works. Only problem is the register.
Did someone have the same issue?

**Comment by superalex** [comment]
Hello @sonnyESP24 

Is this happening in your own instance or in tree.taiga.io?

**Comment by sonnyESP24** [comment]
I created a new database and do some migrations.
I fixed it 
thanks

**Comment by superalex** [comment]
You are welcome! ;)
