### ISSUE TITLE
Feature requedt - CalDAV task integration

### ISSUE THREAD

**Issue by zeigerpuppy** [taigaio/taiga-front#1286]
**Before adding an issue**
Please ensure that your issue is not already reported in our [issues list](https://tree.taiga.io/project/taiga/issues?order_by=-created_date)

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Is it happening in taiga.io or in your own instance?**

**What browser/version are you using?**

**Are there any console errors *(Ctrl + F12)* in red?**

Thanks for reporting!

**Comment by makayabou** [comment]
Hello,
+1 for this feature request.
I would also find fantastic to have caldav integration in taiga.
We could connect to a caldav task list, for example on Nextcloud, and create kanban cards for each task.
Thanks for re-opening, or please point me to some other issue or doc, I couldn't find by myself.

**Comment by majidasgari** [comment]
+1
