### ISSUE TITLE
Related Task URLs are not being generated properly in a user story view

### ISSUE THREAD

**Issue by juliovalcarcel** [taigaio/taiga-front#1287]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The urls generated when viewing a user story for its related tasks are incorrect. No matter how many related tasks all but the last one's href's arent being set properly. (The href's for them are just `href="#"`)
**If the current behavior is a bug, please provide the steps to reproduce.**
Go to any user story with related tasks and try to open any of them and they will all just stay on the current page
**What is the expected behavior?**
Should open a new page
**Is it happening in taiga.io or in your own instance?**
Own instance
**What browser/version are you using?**
Chrome, taiga 3.1.0
**Are there any console errors *(Ctrl + F12)* in red?**
No
Thanks for reporting!

**Comment by superalex** [comment]
Hello @juliovalcarcel 

We solved this issue some days ago, could you try updating your taiga-front copy?

Regards,

**Comment by juliovalcarcel** [comment]
I was using the 3.1-stable tag. I didn't see any tags for 3.1.1 or any bug fix versions so I used master and that worked

**Comment by superalex** [comment]
Master can be unstable so I don't recommend you to use that branch. With hotfixes we don't use to add new tags.

**Comment by juliovalcarcel** [comment]
Which branch do you suggest then (I am using taiga-front-dist)

**Comment by superalex** [comment]
taiga-front-dist in the stable branch with a `git pull`

**Comment by juliovalcarcel** [comment]
Okay thank you

**Comment by superalex** [comment]
You are welcome ;)
