### ISSUE TITLE
[Q] Update jQuery in docker version of taiga-front

### ISSUE THREAD

**Issue by cc-cmarher** [taigaio/taiga-front#129]
I would like to know if there is a way to update jQuery to 3.5.0+ in the docker version of taiga-front.

Thanks!

**Comment by yamila-moreno** [comment]
Hi there!

Do you know that we have [Taiga Community](https://community.taiga.io/) for questions? Please, check there; maybe another user has already ask something similar. If not, create your own. There are people there willing to help, members of the Taiga team members and other users.

To simplify  the process, we will systematically close all issues that are general support questions and redirect people to Taiga Community.

Taiga Team
