### ISSUE TITLE
2 watchers on a private project with me as the only member?

### ISSUE THREAD

**Issue by jvnn** [taigaio/taiga-front#1290]
I'm currently testing taiga using the cloud service and my private project shows 2 watchers although I'm the only user that has never had anything to do with the project. This is hopefully a bug of somekind (e.g. me being counted twice or some notification bot being included in the count) because the other alternative, someone else being able to watch my private project, would be somewhat undesirable... :)

The same count is showing both on the timeline view of the project as well as the "watched" section of my user profile.

**Comment by superalex** [comment]
Hello @jvnn it sounds like you added a watcher in some elements (issue, task, user story, epic) it can be achieved using the @username syntax (but if that user has no privileges to see that element it won't be notified at all). Please write to support@taiga.io indicating the project where this is happening so we can check it.

**Comment by jvnn** [comment]
Ah, ok, I think I know what's going on. I've been adding comments with text "@@" in them (because I use two at-signs as a tag for a templating engine). I guess there's now a user "@" (or whatever text I happened to add after the second @-sign) being marked as a watcher for the project... The editor could maybe be a bit clearer on this, I've seen some weird things happen when I use the @@ signs but I've always been busy typing and whatever popups the editor might have shown me disappeared immediately.

**Comment by superalex** [comment]
I think you are right, we could make that part much more clear, I hope we can improve it soon ;)
