### ISSUE TITLE
"This User Story belongs to" is not ready to translate

### ISSUE THREAD

**Issue by fcojgodoy** [taigaio/taiga-front#1292]
In the user story screen (when it belongs to an epic), the text "This User Story belongs to" is no translate from English to Spanish (in my case) and it does not appear in taiga-front Transifex project.

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
That text is no ready to translate.

**If the current behavior is a bug, please provide the steps to reproduce.**
In Spanish language, in the user story screen, when it belongs to an epic. The text "This User Story belongs to" is no translate.

**What is the expected behavior?**
The text is translate to Spanish or is available to translate in taiga-front project in Transifex.

**Is it happening in taiga.io or in your own instance?**
taiga.io

**What browser/version are you using?**
Firefox 53

**Are there any console errors *(Ctrl + F12)* in red?**
No

**Comment by superalex** [comment]
Thank you very much for reporting, it should be fixed in the stable branch now.

Regards,
