### ISSUE TITLE
Avatar shown as 80x80 instead of 300x300

### ISSUE THREAD

**Issue by jguitar** [taigaio/taiga-front#1293]
**Do you want to request a *feature* or report a *bug*?**

It's a bug

**What is the current behavior?**

The avatar is showing pixelated. Because the image shown is 80x80.

**If the current behavior is a bug, please provide the steps to reproduce.**

After logged in, add a new avatar, or change the photo, or using the default one at https://tree.taiga.io/user-settings/user-profile

**What is the expected behavior?**

In previous versions the image shown was 300x300.

**Is it happening in taiga.io or in your own instance?**

At both

**What browser/version are you using?**

Firefox.

**Are there any console errors *(Ctrl + F12)* in red?**

Nope

**Comment by superalex** [comment]
Thanks for reporting @jguitar we had solved this issue some days ago but we deployed it on tree.taiga.io some minutes ago.

Regards.

**Comment by jguitar** [comment]
So nice, and so fast.
I saw it here at 2e055608f3a14436ed1e9d833df6db1b1682eab3
Do you know when it will be available at `stable` branch?

Thanks @superalex

**Comment by superalex** [comment]
It should be in stable branch too
