### ISSUE TITLE
typo in 'another person has made changes' warning message

### ISSUE THREAD

**Issue by tobyjohnston38** [taigaio/taiga-front#1294]
**Do you want to request a *feature* or report a *bug*?**

Bug / minor/ typo

**If the current behavior is a bug, please provide the steps to reproduce.**

![taigatypo](https://cloud.githubusercontent.com/assets/15662887/25468641/51698ad6-2b6b-11e7-86e6-29baff46a109.png)

**What is the expected behavior?**

'Activiy' should be 'Activity'

**Is it happening in taiga.io or in your own instance?**

taiga

**What browser/version are you using?**

Firefox - probably not browser specific

**Are there any console errors *(Ctrl + F12)* in red?**

Cant remember, probably not as its a typo

**Comment by superalex** [comment]
Thanks for reporting and for the pull request. It should be fixed now on the stable branch.

Regards,
