### ISSUE TITLE
Markdown has no spaces after lists and block quotes

### ISSUE THREAD

**Issue by jerickbixly** [taigaio/taiga-front#1295]
We're running an instance of taiga 3.0 and we found the following error. Below is a sample of the text inserted in the markdown comment box for testing

<pre>
My list

* One
* Two
* Three

A new paragraph - Donec blandit varius mollis. Nullam elit nibh, tempor commodo accumsan vel, interdum quis tortor. Sed ipsum arcu, facilisis nec erat at, dictum venenatis est. Curabitur tempor nisi et quam malesuada, at convallis nunc congue. Mauris sagittis imperdiet enim vitae egestas. Donec id sollicitudin metus. Phasellus at scelerisque lorem, pretium feugiat nulla. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse vel accumsan metus, vitae ullamcorper elit.

Nullam in efficitur felis. Morbi vitae ex eu odio tincidunt laoreet eget at lorem. Donec at turpis vitae eros feugiat faucibus. Phasellus non nunc sem. Suspendisse sed velit mattis, dignissim ligula in, rutrum turpis. Duis id risus vel est fringilla dapibus eget id ipsum. In a consectetur est. Mauris at iaculis sem. Suspendisse potenti.

> Sorry, received this Thursday when I was off. All good. 
>
>
</pre>

Here is the rendered comment. as you can see, there is no line break after the list and inside the block quote, there are no spaces after the line " Sorry, received this Thursday when I was off. All good." when there should be

![rendered_md_edit](https://cloud.githubusercontent.com/assets/2738535/25524402/020297a8-2c3d-11e7-8ba2-816eb6de5a2d.png)

I installed a vanilla version of taiga 3.0 from the repository and tested it and i found the same problem. 

I did some digging though and, at least for the list, i found this work around
https://github.com/taigaio/taiga-front/issues/1153

place an empty H3 header after the list

I couldn't find one for the block quote unfortunately. Is there a fix for both issues we could use or at the very least, a workaround we could use?

Thanks

**Comment by bameda** [comment]
Hi, this was fixed with the last release of Taiga

![image](https://cloud.githubusercontent.com/assets/877218/26691403/42cab8ee-46fd-11e7-9c0f-f3db909bd3b5.png)
