### ISSUE TITLE
Cannot add multiple UserStories to a Sprint.

### ISSUE THREAD

**Issue by theriverman** [taigaio/taiga-front#1302]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
When I try moving multiple(2 or more) user stories into a sprint [either by drag and drop or "Move to current sprint" button], it fails. When I open the sprint board, it's empty and when I go back to the backlog, the UserStories are still there

**If the current behavior is a bug, please provide the steps to reproduce.**
Tick the tickbox next to atleast two user stories then drag and drop them into a sprint.

**What is the expected behavior?**
Get the user stories moved into the desired sprint.

**Is it happening in taiga.io or in your own instance?**
own instance. I could not reproduce the issue on taiga.io

**What browser/version are you using?**
Mozilla Firefox 53.0 (32-bit)

**Are there any console errors *(Ctrl + F12)* in red?**
[I cannot tell if this is related. In FireFox my log was empty. In Chrome I got the following:]

backlog:11 X-Frame-Options may only be set via an HTTP header sent along with a document. It may not be set inside <meta>.
angular.js:13550 Initialize navigation urls
angular.js:13550 Initialize api urls
angular.js:13550 Using the default logging exception handler.
angular.js:13550 Initialize resources
angular.js:13550 Initialize application
angular.js:13550 Analytics: no acount id provided. Disabling.
angular.js:13550 HeartBeat enabled
angular.js:13550 WebSocket connection opened
angular.js:13550 Subscribe to: notifications
angular.js:13550 Subscribe to: changes.project.9.userstories
angular.js:13550 Subscribe to: changes.project.9.milestones
/api/v1/user-storage/e69e4d22b66cbead4040ce4c65a7553d86086f8e Failed to load resource: the server responded with a status of 404 (Not Found)
/api/v1/userstories/bulk_update_milestone Failed to load resource: the server responded with a status of 400 (Bad Request)
angular.js:13550 HeartBeat send PING
angular.js:13550 WebSocket message received: {"cmd":"pong"}
angular.js:13550 HeartBeat recived PONG

Thanks for reporting!

**Comment by superalex** [comment]
Hello,

> /api/v1/userstories/bulk_update_milestone Failed to load resource: the server responded with a status of 400 (Bad Request)

You could check your taiga-back logs to see why this API call is failing exactly. Those logs should probably exist in the logs folder of the taiga user.

Regards,

**Comment by theriverman** [comment]
Hi,

Thanks for the suggestion!
Might be a dumb question, but where can I find the logs specifically for taiga-back?
I have set `DEBUG = True` in ` settings/local.py` but in the `~/logs/` I only have the following files:

> celery.stderr.log  gunicorn.stderr.log  gunicorn.stdout.log.1  nginx.access.log  taigaevents.stderr.log
> celery.stdout.log  gunicorn.stdout.log  gunicorn.stdout.log.2  nginx.error.log   taigaevents.stdout.log

I did restart the server too but still no logs created, however the issue still persists.

Thanks,

**Comment by superalex** [comment]
API logs should be in gunicorn.stderr.log or gunicorn.stdout.log

As you have DEBUG = True you can also use the javascript console of your browser to see the content of the response when the API call fails.

**Comment by superalex** [comment]
Thanks for reporting @theriverman 

This one should be solved in the stable branch now (and deployed in tree.taiga.io)
