### ISSUE TITLE
Wiki broken on stable branch

### ISSUE THREAD

**Issue by joeystandrew** [taigaio/taiga-front#1304]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Wiki pages do not allow adding or editing text.

**If the current behavior is a bug, please provide the steps to reproduce.**
Browse the wiki page on any project while on the stable branch

**What is the expected behavior?**
For the text editing functionality to work.

**Is it happening in taiga.io or in your own instance?**
Own instance.

**What browser/version are you using?**
Chrome and Safari

**Are there any console errors *(Ctrl + F12)* in red?**
angular.js:13550 Error: [$injector:unpr] Unknown provider: tgWikiHistoryServiceProvider <- tgWikiHistoryService <- tgWikiWysiwygDirective

**Comment by joeystandrew** [comment]
When running on the master branch the wiki seems to work fine btw.

**Comment by superalex** [comment]
Thank you very much for reporting @joeystandrew 

I've just rebuilt taiga-front-dist and it should be working now. Sorry for the inconvenience.

Regards,

**Comment by joeystandrew** [comment]
Just wanted to say you rock and thanks for such a speedy fix. I am setting up Taiga as my office's new project management software and quick fixes, etc like this make me feel good about using this project.

Sorry if posting here was the wrong place to do this, just wanted to give some kudos and a shout out!

**Comment by superalex** [comment]
Thank you very much @joeystandrew and don't worry, you can report that kind of thins using github issues ;)
