### ISSUE TITLE
Missing kanban headers

### ISSUE THREAD

**Issue by joeystandrew** [taigaio/taiga-front#1305]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Some kanban headers are hidden for statuses

**If the current behavior is a bug, please provide the steps to reproduce.**
Checkout the stable branch and view the kanban board of any project

**What is the expected behavior?**
I should be able to see all headers to edit, add, etc tasks

**Is it happening in taiga.io or in your own instance?**
Both

**What browser/version are you using?**
Webkit

**Are there any console errors *(Ctrl + F12)* in red?**
No

**Possible Fixes?**
Apply the following CSS rules:

.kanban-table-header .kanban-table-inner {
    overflow: visible !important;
}

**Comment by lvlts** [comment]
I can confirm this is happening on Firefox and Webkit based browsers. An example of the bug (whenever scrolling horizontally in the Kanban board):

![Kanban headers](https://user-images.githubusercontent.com/32608130/61688438-4f756680-ad25-11e9-9d1f-414fa67d29cb.png)

The suggested fix is working (tested using browser developer tools). Shall I submit a pull request?

**Comment by alexhermida** [comment]
@lvlts yes of course! You can contribute to Taiga in many different ways, check it https://tree.taiga.io/support/frequently-asked-questions/how-can-i-contribute-to-taiga/
