### ISSUE TITLE
Timeline View Empty after upgrade to 3.1

### ISSUE THREAD

**Issue by cmthomps** [taigaio/taiga-front#1306]
**Do you want to request a *feature* or report a *bug*?**
Potential BUG

**What is the current behavior?**
Upon upgrading from 3.0 to 3.1, the timeline view on our server no longer displays data.
Screenshot attached.   I went through the standard upgrade process and have rebooted the machine.  The odd thing that I just noticed is that it may be intermittent.  For a minute, the activity was appearing but I went to test on other machines and it stopped working...  Very strange.

**If the current behavior is a bug, please provide the steps to reproduce.**
NA

**What is the expected behavior?**
Display Timeline view.

**Is it happening in taiga.io or in your own instance?**
Our own instance.

**What browser/version are you using?**
Chrome 57

**Are there any console errors *(Ctrl + F12)* in red?**
No

![2017-05-08_16-04-22](https://cloud.githubusercontent.com/assets/1678345/25822934/5d0ee6a6-3408-11e7-9f09-0d62a22c8417.png)

**Comment by superalex** [comment]
Could you please check if there are any errors on the javascript console?

**Comment by saikirubamj** [comment]
Any solutions for this problem?

I have no error on java script console in browser

**Comment by alexhermida** [comment]
@saikirubamj did you update to 3.1 or the last release? 
3.1 has three years old. If you use it, you must make sure you also use the same backend version.
Nevertheless, you would have some console error if not also make sure you receive the request in the backend, and it comes with data.
