### ISSUE TITLE
Ordering backlog items does not store the order correctly

### ISSUE THREAD

**Issue by rmaijers** [taigaio/taiga-front#1308]
**Before adding an issue**
Please ensure that your issue is not already reported in our [issues list](https://tree.taiga.io/project/taiga/issues?order_by=-created_date).
If this issue was already reported, remember that you can upvote it to raise its importance.

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Ordering backlog items does not preserve order, i.e. moving two items (not at once, but in two actions) does not give the expected order. I work around this by reloading after every move, which is quite tedious (scroll/autoload/scroll/autoload after every reload). This has been an issue for half a year now (ever since we use Taiga).

**If the current behavior is a bug, please provide the steps to reproduce.**
Look at 4 backlog items:
1
2
3
4

Move nr 4 up:
1
4
2
3

Move nr 1 down:
4
2
1
3

Reload, the order is different:
4
1
2
3

**What is the expected behavior?**
Correctly store order the user made:
4
2
1
3

**Is it happening in taiga.io or in your own instance?**
Own instance, up-to-date.

**What browser/version are you using?**
Firefox (recent), but it appears in other browsers too.

**Are there any console errors *(Ctrl + F12)* in red?**
Nope

Thanks for reporting!

**Comment by boris-arkenaar** [comment]
+1

**Comment by christianlupus** [comment]
Can you check if this is still an issue? This might be no longer open.

**Comment by rmaijers** [comment]
I can't, because we decided to stop using Taiga. Because of this and other issues that made it hard to work with. And we didn't get the impression that great improvements would come soon.
