### ISSUE TITLE
Assign to User after bulk task create

### ISSUE THREAD

**Issue by eliocapelati** [taigaio/taiga-front#1310]
After create a sprint, add a US, and bulk create task, I'm getting an error in assign a user to these tasks.

Step 1: Empty sprint with some US:

![1](https://cloud.githubusercontent.com/assets/550933/25969580/d27d364e-366b-11e7-81dc-307fafe4c49a.png)

Step 2: Bulk create Task:

![2](https://cloud.githubusercontent.com/assets/550933/25969631/fc913a70-366b-11e7-9c42-ea9545fe08ab.png)

Step 3: Bulk create Task with success:

![3](https://cloud.githubusercontent.com/assets/550933/25969643/098a05d6-366c-11e7-994d-a5f07a11de3a.png)

Step 4: Assign a User to a brand new task:

![4](https://cloud.githubusercontent.com/assets/550933/25969680/3e39e7f6-366c-11e7-8da0-0e48ace84cfb.png)

Step 5: Fail to assign user to task, (and no error feedback on UI):

![5](https://cloud.githubusercontent.com/assets/550933/25969742/757e3578-366c-11e7-813d-f9046f3837de.png)

Step 6: Reload page, and the user is not assigned:

![6](https://cloud.githubusercontent.com/assets/550933/25969768/864780b2-366c-11e7-8689-dd0207906840.png)

**Comment by superalex** [comment]
I've just tested this in https://tree.taiga.io (running the last stable release) and I can't reproduce. What taiga version are you using?.
