### ISSUE TITLE
Select many user stories from the backlog and move them into a sprint does not actually move the user stories

### ISSUE THREAD

**Issue by jean553** [taigaio/taiga-front#1311]
Hello,

When I select many user stories from the backlog (using the user story check box), and I move them into a sprint on the right, the selected US appear into the sprint US list and then suddenly disappear (one second later). The selected US are not into the backlog either, the only way to get them back there is to refresh the page. This problem doesn't occure when I select only one US.

Steps to reproduce :
1. Select more than one US from the backlog with the checkboxes
2. Move them into a sprint on right
The US are appended to the sprint US list during one second, then they disappear. The US are neither into the sprint US list, nor in the backlog.

The moved US should stay into the sprint US list.
It happens on Taiga.io.
I am using Firefox 53.0.2 64bits, Linux (Arch).
There is no error into the Firefox console.

Thanks.

**Comment by theriverman** [comment]
Hi,

I already opened a ticket for this issue a couple of days ago here: [Cannot add multiple UserStories to a Sprint. #1302](https://github.com/taigaio/taiga-front/issues/1302)

Please merge these two issues!

/riverman

**Comment by jean553** [comment]
Alright, thanks. Duplicate of https://github.com/taigaio/taiga-front/issues/1302.
