### ISSUE TITLE
Unresponsive Script https://tree.taiga.io/v-1493894420511/js/libs.js:22

### ISSUE THREAD

**Issue by jmaibach** [taigaio/taiga-front#1312]
**Do you want to request a *feature* or report a *bug*?**

Report  a bug.

**What is the current behavior?**

Sometimes i get the following error message in arbitrary situtations and Firefox freezes. This often happens when, for example, clicking on an issue:

> A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.
> 
> Script: https://tree.taiga.io/v-1493894420511/js/libs.js:22

**If the current behavior is a bug, please provide the steps to reproduce.**

As i said, this happens from time to time, often when clicking on an issue.

**What is the expected behavior?**

This shouldn't occur.

**Is it happening in taiga.io or in your own instance?**

It is happening in taiga.io.

**What browser/version are you using?**

Firefox 53.0.2 (64-bit) on Ubuntu 16.04.

**Are there any console errors *(Ctrl + F12)* in red?**

When i click on "Debug Script" I get to the following point:

![](http://i.imgur.com/ktOiBR7.png)

Thanks for reporting!

**Comment by Gnafu** [comment]
Same here, it is happening on a on-premise installation.
Both /v-1494222008101/js/libs.js and /v-1494222008101/js/templates.js files fails to load.

Firefox 57.0.1
I noticed it happens if I don't use taiga for a long time (days)
