### ISSUE TITLE
Code snippet on wiki hides http:// prefix when rendered

### ISSUE THREAD

**Issue by vlcinsky** [taigaio/taiga-front#1314]
Consider following code snippet:
```
location /ws {
    auth_basic off;
    proxy_pass http://localhost:15675/ws;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
}
```

If put into Taiga wiki, the "http://" from "http://localhost:15675/ws" is gone when the page is rendered (the source is correct, only the rendered result is without the protocol prefix).

This shall not happen.

**Comment by superalex** [comment]
Hi @vlcinsky 

If you want it to be rendered as source code you should use the "code" format, that way url's wont generate a <a>  tag and everything will be rendered under the same code block.

Regards,

**Comment by vlcinsky** [comment]
@superalex 
I used three backtics according to https://tree.taiga.io/support/misc/taiga-markdown-syntax/#auto-highlight-code-block

Sorry, I had better tell it directly (I am using three backticks all the time and consider it natural default, what was wrong assumption).

Please, review the issue for code enclosed in pair of three backticks.

**Comment by superalex** [comment]
Hello @vlcinsky the three backticks should work if writing in markdown mode. Were you writing does backticks in html mode?.

If this is happening in tree.taiga.io, could you write to support@taiga.io including the url where this is happening?

**Comment by vlcinsky** [comment]
I write the text in markdown mode.

When I put following (enclosed within pair of three backticks) into wiki, the "http://" is not rendered:

```
location /ws {
    auth_basic off;
    proxy_pass http://localhost:15675/ws;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
}
```
I will send the url of my wiki page to support@taiga.io (and will include link to this issue).

**Comment by vlcinsky** [comment]
@superalex Would you be so kind to reopen this issue? So far I have provided you with requested information and the issue seems to be still present.

**Comment by sshnaidm** [comment]
This breaks scripts which makes using "code" snippets in taiga completely useless. Is there a chance to increase priority for this bug?
I wonder why you remove "http" and "https" at all, what is it for? It doens't make URL prettier in any way, but only hides from user an important information - whether it's secure HTTPS or insecure HTTP.
