### ISSUE TITLE
Singing in with GitLab causes an Error. And what is an Oompa Loompa?

### ISSUE THREAD

**Issue by hcdangan** [taigaio/taiga-front#1316]
**Do you want to request a *feature* or report a *bug*?** Reporting a BUG

**What is the current behavior?** Signing on GitLab fails. There is an error that says "Oops, something happened... Our Oompa Loompas have not been able to get you credentials from GitLab."

**If the current behavior is a bug, please provide the steps to reproduce.** On the login page, click SIGN IN WITH GITLAB

**What is the expected behavior?** It will sign me in

**Is it happening in taiga.io or in your own instance?** It is happening on taiga.io

**What browser/version are you using?** Google Chrome 58.0.3029.110

**Are there any console errors *(Ctrl + F12)* in red?** None

Thanks for reporting!

**Comment by iGormilhit** [comment]
[Wikipedia](https://en.wikipedia.org/wiki/List_of_Charlie_and_the_Chocolate_Factory_characters#Oompa-Loompas) knows some about this mysterious Oompa Loompa. 😃

**Comment by jespino** [comment]
I can't reproduce it :disappointed:

**Comment by ilu123** [comment]
I got this error too.

**Comment by Gredys** [comment]
Where is a fix for this issue!?

**Comment by svenseeberg** [comment]
I tried to use the Gitlab integration for Gitea/Forgejo. WHen using the browser console, I can see a request to taiga.example.com/auth that returns a response `unsupported_grant_type`. I suggest to have a look into your browser tools to get the specific error that helps debugging the problem. Sadly, it seems that there is no solution to my problem AFAICT.
