### ISSUE TITLE
Feature Request: Linked Numbers

### ISSUE THREAD

**Issue by marbetschar** [taigaio/taiga-front#1318]
It would be cool to have linked user stories in case of blocking issues. That said, it's the same behaviour for typing #... in the block reason as in the content.

So another user can click the block message and directly jump to the cause of the block. See screenshot for further infos.

![bildschirmfoto 2017-05-31 um 21 32 32](https://cloud.githubusercontent.com/assets/392542/26650335/5de671ae-4649-11e7-9e28-337e09728099.png)

**Comment by marbetschar** [comment]
Is there any ETA if and when this will be landing?

**Comment by superalex** [comment]
No sorry, we don't have any elapsed time for this
