### ISSUE TITLE
Feature Request: Auto Link URLs in Text

### ISSUE THREAD

**Issue by marbetschar** [taigaio/taiga-front#1319]
URLs in Text should be linked automatically without the need of editing and inserting the link manually.

![bildschirmfoto 2017-05-31 um 21 39 07](https://cloud.githubusercontent.com/assets/392542/26650490/da53b77e-4649-11e7-8ec0-a65c53ed309c.png)

**Comment by superalex** [comment]
They are linked automatically:

![image](https://cloud.githubusercontent.com/assets/1579633/26664548/be7741c6-4692-11e7-954c-bb5174f60473.png)


Are you sure you edited that text field in html mode and not directly in markdown mode?

**Comment by superalex** [comment]
I've just checked again in https://tree.taiga.io (running the last stable release) and it's properly rendered

**Comment by marbetschar** [comment]
@superalex you're right, this has obviously been done. Why are there hardly any releases...?

https://groups.google.com/forum/#!msg/taigaio/niR1_RVuPzU/D5IS0mg7AAAJ

**Comment by superalex** [comment]
Yes, I agree we could improve the release process but for us it's just faster to add those small issues directly in the current stable branches.

**Comment by marbetschar** [comment]
what do you mean by `add small issues directly in the current stable branches` ...? The thing for us is, we are relying on changes in the release version - and obviously there nothing has changed.

So how to get the latest stable release actually?

**Comment by superalex** [comment]
You could check the the last commits in the stable branches:
- https://github.com/taigaio/taiga-front/commits/stable
- https://github.com/taigaio/taiga-back/commits/stable

**Comment by marbetschar** [comment]
@superalex so is it save to assume these two branches always contain the latest stable release and fully ignore any release numbers then?

**Comment by superalex** [comment]
Yes, those branches always contain the last stable release (also deployed in https://tree.taiga.io).

**Comment by marbetschar** [comment]
@superalex thank you so much for clearing things up!!

**Comment by superalex** [comment]
You are welcome @marbetschar ;)
