### ISSUE TITLE
Search and Add Issue

### ISSUE THREAD

**Issue by marbetschar** [taigaio/taiga-front#1322]
I was just struggling adding an issue because of some design decisions made in the UI: I tried to enter the query term in the grey bar on top, instead of the search field on the left because it felt similar like the knowledgebase search fields.

That's the reason why I came up with the following improvements to the UI:

<img width="1198" alt="bildschirmfoto 2017-06-02 um 09 34 21" src="https://cloud.githubusercontent.com/assets/392542/26715784/404b2e8a-4777-11e7-8b47-9963fd07b3d8.png">

What do you think?

**Comment by Xaviju** [comment]
Hi @marbetschar your suggestion is interesting but Taiga is using that filter sidebar component in other areas so if we remove the search box from there but keep it in other pages there will be some UI inconsistency.
The gray area might be misleading, I agree

**Comment by marbetschar** [comment]
@Xaviju i see that keeping a consistent UI is more important than making this change only on one screen. However, as far as I can tell the other areas can be adjusted fairly easily too - but maybe I'm missing something here.

On the other hand, if the gray would not been there - I would haven ever created this issue ;)
