### ISSUE TITLE
Project Export does not work in Safari

### ISSUE THREAD

**Issue by marbetschar** [taigaio/taiga-front#1323]
For some reason the project export does not work in Safari on macOS. But it does without any problem in Chrome. Here's what I'm encountering in Safari:

#### First, I hit the export button
<img width="1268" alt="bildschirmfoto 2017-06-02 um 11 53 46" src="https://cloud.githubusercontent.com/assets/392542/26720957/52dccc08-478a-11e7-9404-851415083bc0.png">

#### Then nothing more happens for a while and I decide to click on "click here" link. This takes me then to the following 404 page - no file is downloaded at all:
<img width="1255" alt="bildschirmfoto 2017-06-02 um 11 53 54" src="https://cloud.githubusercontent.com/assets/392542/26720979/69d84ef0-478a-11e7-9f9b-3217b0b3e422.png">

FWIW There is no error or anything outputted to the JavaScript console.

**Comment by marbetschar** [comment]
Any news on this export issue?

**Comment by superalex** [comment]
Hello @marbetschar what's the url generating the 404 error page?. Is this happening on https://tree.taiga.io or in your own instance?

**Comment by marbetschar** [comment]
@superalex it's on my own instance. I'm running the latest taiga from as far as I can tell; but if you say how I can verify that I'd happily do so :)

**Comment by superalex** [comment]
What's the url generating the 404 error?

Could you also please check if it's happening on tree.taiga.io?

**Comment by marbetschar** [comment]
The URL generating the error is the "if the download does not start automatically, please click here" link, which points to the following url: https://project.mandelkind.pizza/media/exports/1/mandelkind-cloudron-875819fe7f3e496b9e73299d7c7b7b8d.json

<img width="1227" alt="bildschirmfoto 2017-07-18 um 12 31 34" src="https://user-images.githubusercontent.com/392542/28312921-254ad452-6bb5-11e7-9aa1-77f38c106e4a.png">

Can't test this on tree.taiga.io since there it's saying "We'll send you an email after the export is finished".

**Comment by superalex** [comment]
I've checked that url and it exists (no 404 received), are you still receiving the error?, could it be a cache browser problem?, could you check your javascript console to see if there is any error?

**Comment by marbetschar** [comment]
Can you reproduce the error? And/or can we find another way to debug the issue? From my end it seems simple; it's on every self hosted instance and appears alle the time - only in Safari.

**Comment by marbetschar** [comment]
I now clicked on the link pasted here on GitHub and it worked. Do we have some sort of timing issue here? For example, Taiga generates the download link but is not finished yet with generating the export and therefore the link itself generates a 404 when clicked.

**Comment by superalex** [comment]
Taiga generates the file but it's served directly by the web server (nginx in the standard installation). I assume your instance is working in synchronous mode (you don't receive an email to download the file) and Taiga should generate that link only when the file is generated.

Did you check if that file exists on the filesystem on the momento you get the 404?, you could also check your browser console to see if there is any error.

**Comment by jszsj** [comment]
I have the same problem, but if u refresh the 404 page the json file can be shown
