### ISSUE TITLE
Nginx configuration error

### ISSUE THREAD

**Issue by kaisbe** [taigaio/taiga-front#1324]
After following all the installation steps from https://taigaio.github.io/taiga-doc/dist/setup-production.html and opening localhost on the web browser, I get problems with the frontend content display, along with Nginx throwing those errors within /var/log/nginxs/error.log:

> 2017/06/12 01:22:14 [error] 8512#8512: *1 open() "/usr/share/nginx/html/v-1495549531419/svg/spinner-circle.svg" failed (2: No such file or directory), client: 127.0.0.1, server: , request: "GET /v-1495549531419/svg/spinner-circle.svg HTTP/1.1", host: "localhost", referrer: "http://localhost/"
> 2017/06/12 01:22:19 [error] 8512#8512: *1 open() "/usr/share/nginx/html/api/v1/stats/discover" failed (2: No such file or directory), client: 127.0.0.1, server: , request: "GET /api/v1/stats/discover HTTP/1.1", host: "localhost", referrer: "http://localhost/discover"
> 2017/06/12 01:22:19 [error] 8512#8512: *1 open() "/usr/share/nginx/html/api/v1/projects" failed (2: No such file or directory), client: 127.0.0.1, server: , request: "GET /api/v1/projects?discover_mode=true&order_by=-total_fans_last_week HTTP/1.1", host: "localhost", referrer: "http://localhost/discover"
> 2017/06/12 01:22:19 [error] 8512#8512: *1 open() "/usr/share/nginx/html/api/v1/projects" failed (2: No such file or directory), client: 127.0.0.1, server: , request: "GET /api/v1/projects?discover_mode=true&order_by=-total_activity_last_week HTTP/1.1", host: "localhost", referrer: "http://localhost/discover"
> 2017/06/12 01:22:19 [error] 8512#8512: *1 open() "/usr/share/nginx/html/api/v1/projects" failed (2: No such file or directory), client: 127.0.0.1, server: , request: "GET /api/v1/projects?discover_mode=true&is_featured=true HTTP/1.1", host: "localhost", referrer: "http://localhost/discover"
> 2017/06/12 01:22:27 [error] 8512#8512: *7 open() "/usr/share/nginx/html/events" failed (2: No such file or directory), client: 127.0.0.1, server: , request: "GET /events HTTP/1.1", host: "localhost"
> 2017/06/12 01:23:27 [error] 8512#8512: *8 open() "/usr/share/nginx/html/events" failed (2: No such file or directory), client: 127.0.0.1, server: , request: "GET /events HTTP/1.1", host: "localhost"
> 2017/06/12 01:24:27 [error] 8512#8512: *9 open() "/usr/share/nginx/html/events" failed (2: No such file or directory), client: 127.0.0.1, server: , request: "GET /events HTTP/1.1", host: "localhost"

This is the nginx configuration file used for taiga: 
[taiga.txt](https://github.com/taigaio/taiga-front/files/1066820/taiga.txt)

This is the circus configuration file: 
[taiga.ini.txt](https://github.com/taigaio/taiga-front/files/1066821/taiga.ini.txt)

**Comment by superalex** [comment]
It seems nginx isn't using your config file. For example there is an errors saying:

> open() "/usr/share/nginx/html/api/v1/projects" failed 

but /api/v1/projects should be using 
```
# Backend
location /api {
....
```
It sounds like you have some kind of configuration in your nginx that is trying to serve everything from /usr/share/nginx/html/

Regards,
