### ISSUE TITLE
Not able to login to my self hosted Taiga

### ISSUE THREAD

**Issue by adutta14** [taigaio/taiga-front#1326]
**Before adding an issue**
Please ensure that your issue is not already reported in our [issues list](https://tree.taiga.io/project/taiga/issues?order_by=-created_date).
If this issue was already reported, remember that you can upvote it to raise its importance.

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I  am trying to migrate my self hosted Taiga from one server to another. I have used the automated scripts to set up my environment. I did the configuration changes. Now i am able to see the Taiga login page but not able to login to it. Neither Sign up option helps as it doesn't do anything on filling the details and clicking it.

**Is it happening in taiga.io or in your own instance?**
Own instance

**Comment by superalex** [comment]
You could start checking two different things:
- The logs folder from your server (by default it will be in the logs folder, that folder should be under the home of the user you used for the taiga installation)
- The browser console logs

**Comment by adutta14** [comment]
I am seeing the below error in the nginx error logs:-

2017/06/26 08:11:56 [error] 16637#16637: *260586 connect() failed (111: Connection refused) while connecting to upstream, client: 68.231.147.19, server: taigapro.isdatatower.com, request: "GET /events HTTP/1.1", upstream: "http://127.0.0.1:8888/events", host: "taigapro.isdatatower.com"

Is it like taiga-back is refusing to connect with taiga-front?
How can i troubleshoot and fix it?

**Comment by superalex** [comment]
taiga-events is independent from taiga-back, you could try your instance disabling the taiga-events component

**Comment by adutta14** [comment]
We are not using taiga-events and hence i have not configured it.

**Comment by superalex** [comment]
Probably you front conf.json file have taiga-events configured

**Comment by adutta14** [comment]
There was with " "eventsUrl": ............... " .
So,i just now removed it,  reloaded the nginx config and restarted nginx.
What should be the default user to login to taiga?

**Comment by superalex** [comment]
If you migrated your data from one instance to the other you should use the same user/password

**Comment by adutta14** [comment]
i just copied the media folder under taiga-back and took a dump of the DB using pqsl and transferred them to the new server.
Is there anything else i need to do as a part of data migration?

**Comment by superalex** [comment]
No, that should be enough.

**Comment by adutta14** [comment]
So, its not working for me... is there a way i can check the users that are present in the DB as because it always throws me an error with :
"Oops, something happened...
According to our Oompa Loompas, your username/email or password are incorrect."

Also, why would "signup" functionality wont work?

**Comment by superalex** [comment]
You could check if the users table from your database is filled correctly.

If signup isn't working it could be also related to an error on email sending

**Comment by adutta14** [comment]
Well, the same email settings are working for our current working Taiga server. So, i doubt that.

**Comment by adutta14** [comment]
I could figure out that my taiga-backend is not running that is why i might be getting 502 error.

I tried restarting it by configuring circus. So, when i run "circusctl status" or "circusctl reloadconfig", i get the below error:-
Timed out.
A time out usually happens in one of those cases:

#1 The Circus daemon could not be reached.
#2 The Circus daemon took too long to perform the operation

For #1, make sure you are hitting the right place
by checking your --endpoint option.

For #2, if you are not expecting a result to
come back, increase your timeout option value
(particularly with waiting switches)

Please tell me  on what all information you need from my end to troubleshoot this issue.

**Comment by manvirsorout** [comment]
i have migrated postgres db of taiga from one instance to another instance but i am unable to login in migrated taiga while link is running

**Comment by manvirsorout** [comment]
i have to migrate taiga docker one instance to 2nd instance but in taiga installed by source code in 2nd instance 
kindly tell how to migrate one instance to 2nd instance.
