### ISSUE TITLE
Cannot see Backlog stories 

### ISSUE THREAD

**Issue by sallyrutherford** [taigaio/taiga-front#1335]
When I look at the Backlog and filter on a tag, there are no stories in the list
I expect to see the stories in the list that have the specified tag.
This is happening in taiga.io

I am using  Chrome

**Comment by superalex** [comment]
Hello @sallyrutherford 

Could you please indicate the full url you are using to see your backlog?

**Comment by sallyrutherford** [comment]
https://tree.taiga.io/project/bretman-cashmanager-rural-2/backlog?milestone=140665&q=&tags=sprint%204-3

**Comment by superalex** [comment]
It seems you are filtering your backing by sprint, just try accessing to: https://tree.taiga.io/project/bretman-cashmanager-rural-2/backlog?q=

**Comment by jwir3** [comment]
@kaplanke Did you ever solve this? I am also seeing this issue and can't seem to clear the milestone.

**Comment by kaplanke** [comment]
Hi, just clear your local storage. But there may be a better solution of course...
