### ISSUE TITLE
Not able to import.

### ISSUE THREAD

**Issue by Cyr3con** [taigaio/taiga-front#1336]
**Before adding an issue**
Please ensure that your issue is not already reported in our [issues list](https://tree.taiga.io/project/taiga/issues?order_by=-created_date).
If this issue was already reported, remember that you can upvote it to raise its importance.

**Do you want to request a *feature* or report a *bug*?**
bug

**Is it happening in taiga.io or in your own instance?**
own instance

Hello, I am not able to import an existing  project from the backup. Is it because of the size of the backup file? As, i was able to import another small project.

Attached are the screenshots.
<img width="659" alt="2" src="https://user-images.githubusercontent.com/25628910/27878562-80db82b8-6173-11e7-9db0-38ce3bfc0667.PNG">
<img width="663" alt="1" src="https://user-images.githubusercontent.com/25628910/27878561-80d69aa0-6173-11e7-8bbe-bc9c2fd9d956.PNG">

Please advice.

Thanks for reporting!

**Comment by superalex** [comment]
Hello!,

It's probably because of themax attachment file for your web server

**Comment by Cyr3con** [comment]
What is that? Can you please elaborate and provide me the solution please.

**Comment by Cyr3con** [comment]
Waiting for your response sir.

**Comment by Cyr3con** [comment]
I checked my gunicorn.stderr.log file and i am seeing the below error:-

[2017-07-10 02:28:17 +0000] [1530] [CRITICAL] WORKER TIMEOUT (pid:1552)
Trying import local.py settings...
[2017-07-10 02:28:17 +0000] [2225] [INFO] Booting worker with pid: 2225

Please advice.

**Comment by superalex** [comment]
You could check your nginx error file to see if there is any error related to the file upload. You could check the value of client_max_body_size on nginx and check it's bigger than the file you want to upload.
