### ISSUE TITLE
Wrong numbers with story

### ISSUE THREAD

**Issue by Varunram** [taigaio/taiga-front#1339]
Expected Number: 38 (instead of 37190)
<img width="1231" alt="screen shot 2017-07-11 at 8 34 03 pm" src="https://user-images.githubusercontent.com/18598959/28075319-c36195f0-6678-11e7-85a9-2a6bd03156d0.png">
I don't know why this occurred, but most probably this is a bug

**Comment by superalex** [comment]
Hello @Varunram ,

Is this happening in your own instance or in tree.taiga.io?

**Comment by Varunram** [comment]
@superalex Not my own instance,  it happens on tree.taiga.io. <a href="https://tree.taiga.io/project/musicoin-musicoin/us/39">This </a>is the link if it helps. Thanks!

**Comment by superalex** [comment]
oh, I think the error is we are showing the id instead of the ref, we will try to solve it as soon as possible.

Regards,

**Comment by iGormilhit** [comment]
Same issue [here](https://tree.taiga.io/project/mmo-rero-test-project/us/1?milestone=152473)

**Comment by jespino** [comment]
I'm working on it
