### ISSUE TITLE
Show current sprints in Working On

### ISSUE THREAD

**Issue by treuherz** [taigaio/taiga-front#1341]
As it is, the Working On section, in the projects dashboard, shows stories and tasks assigned to a user, but accessing any information on sprints requires clicking through to the project, then going via. It would be extremely helpful to have a display in the Working On secition of the current Sprint, linking to the Sprint Taskboard. This would make the Projects Dashboard far more useful as a one-stop-shop for what's going on in the Taiga instance.

**Comment by zenovalle** [comment]
I quote this.

**Comment by zenovalle** [comment]
+1
