### ISSUE TITLE
Change "Related tasks" to "Subtasks" - Enhancement

### ISSUE THREAD

**Issue by davidflast** [taigaio/taiga-front#1343]
In my process of trying out taiga I thought "related tasks" meant you could attach one task card to another, so I thought taiga did not have subtasks, was dissapointed an went to other sites. I decided to give taiga another try 2 weeks later and realized that they were simply subtasks and chose to continue using it. I think changing the name would help new users see that taiga has "Subtasks" since that is the lingo that every other agile site uses, and would prevent some confusion.

**Comment by superalex** [comment]
Thank you very much for your suggestion @davidflast we will consider it on future taiga releases.

**Comment by theriverman** [comment]
+1
