### ISSUE TITLE
UX: Cannot reorder tasks within User Story view

### ISSUE THREAD

**Issue by methadata** [taigaio/taiga-front#1347]
Currently it is not possible to reorder a list of tasks inside a user story. However, reordering user  stories under the Epic view is possible. 
The UX should be consistent in this case, right?

**Comment by jerem-ie** [comment]
Yes, and it will be very helpfull !

**Comment by hdave** [comment]
This would be very helpful as our team likes to stage the tasks long before they are assigned to a sprint and would have to be pointed.  When tasks are ordered in roughly the time ordering of work it really helps to identify if anything is missing.

**Comment by Doctor-Who** [comment]
It will make sense as user can already reorder epic, user story. Many thanks for take in consideration our request.

**Comment by benyanke** [comment]
I agree - this is something which is really needed.
