### ISSUE TITLE
Unable to sign in with GitHub on iOS TaigaApp

### ISSUE THREAD

**Issue by jsinclair1991** [taigaio/taiga-front#1348]
This appears to be a bug, but I suppose could be an issue with my phone or configuration, or something.

When logging into the iOS app "TaigaApp", I attempt to sign in with GitHub. I enter my GitHub credentials, and it returns to the TaigaApp with a loading icon that never finishes. See screenshot. I can login with GitHub successfully on a browser (both on PC and on mobile), so it does not appear to be a problem with my credentials. I have not been able to test on a second device at this time.

Steps to recreate:
1. Open TaigaApp on iPhone
2. Tap "Sign In with GitHub"
3. Enter credentials. Click sign in.
4. Loading screen shots, never logs in (see screenshot) - I've waited approximately 5 minutes before giving up, on my longest attempt.

After this displays, the app is not responsive. I cannot click the "x" for the cookies notice. I also cannot click the "Cancel" text in the top right. I seem to only be left to force close the app, that I've been able to tell.

Environment: iOS 10.3.2 (14F89), iPhone 6s Plus, TaigaApp 1.2.2 (released July 26, 2017)

![image](https://user-images.githubusercontent.com/10506856/28673481-a0a843c6-72b0-11e7-9e01-8a847658f114.png)

**Comment by superalex** [comment]
Hello @jsinclair1991 

I'm sorry but that app isn't developed by us, could you please contact their staff to notify this issue?

**Comment by jsinclair1991** [comment]
@superalex 

I'm sorry, I was not aware this was not an official app. I only just recently started using Taiga a few days ago. Thank you for letting me know.
