### ISSUE TITLE
Odd epic ID on kanban board

### ISSUE THREAD

**Issue by rimmington** [taigaio/taiga-front#1355]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
When hovering over an epic colour on the kanban board, the tooltip contains some unknown number instead of the epic ID. The epic name is correct.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Enable Kanban, Epics modules
2. Create a user story
3. Create an epic, add the user story to the epic
4. Go to the Kanban view
5. Hover mouse over coloured circle next to the name of the user story

**What is the expected behavior?**
The number in the tooltip is the epic ID as listed in the Epics module.

**Is it happening in taiga.io or in your own instance?**
Taiga.io.

**What browser/version are you using?**
Firefox 55.0.1 on Ubuntu.

**Are there any console errors *(Ctrl + F12)* in red?**
Nope.

**Comment by bameda** [comment]
Fixed https://github.com/taigaio/taiga-front/pull/1356

Thanks for report this.
