### ISSUE TITLE
BUG: epics progress broken

### ISSUE THREAD

**Issue by sopitz** [taigaio/taiga-front#1357]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Even though 75% of an epic are close, the epic progress remains at 33%. 

**If the current behavior is a bug, please provide the steps to reproduce.**
Create new epic, create 4 stories within it. Close 3 of them. Check Epics overview page for the progress of the epic.

**What is the expected behavior?**
Progress should update according to accumulated progress of the stories within.

**Is it happening in taiga.io or in your own instance?**
own instance

**What browser/version are you using?**
MacOS, Chrome 59.0.3071.115

**Are there any console errors *(Ctrl + F12)* in red?**
no
![2017-08-23-13-17-taiga silicon dev espp eon com](https://user-images.githubusercontent.com/1926344/29613253-7c06fd22-8805-11e7-8310-d7981160f01b.png)

First line is the epic progress bar.

EDIT: fix screenshot. now it shows the right content.

**Comment by ambrt** [comment]
Same here

**Comment by sopitz** [comment]
Interesting @superalex. I could now again reproduce the desired behaviour on taiga.io. On our self-hosted system it is still behaving as described in the issue report.

**Comment by sopitz** [comment]
Is there a way to find a version number on self hosted systems? Just to make sure that it's up to date?!

**Comment by superalex** [comment]
It sounds like you aren't using the last stable version. You could execute something like "git show-ref --head" to check if the last commit of your installation matches the last one from the stable branch of the repo

**Comment by sopitz** [comment]
I cloned [taiga-front-disk](https://github.com/taigaio/taiga-front-dist) at [93bbd82a983d3f7f694bfe3d460221d6ae6701ba](https://github.com/taigaio/taiga-front-dist/commit/93bbd82a983d3f7f694bfe3d460221d6ae6701ba) which is even more up to date than 3.1.0-stable as far as I could see.

**Comment by superalex** [comment]
And taiga-back?

**Comment by sopitz** [comment]
taiga-back at [d1dd3631f98ad43aef37607b6d698faad861eef5](https://github.com/taigaio/taiga-back/commit/d1dd3631f98ad43aef37607b6d698faad861eef5)

**Comment by superalex** [comment]
It seems you have the commit solving that issue in your instance (https://github.com/taigaio/taiga-back/commits/stable). Did you reload taiga back after the last upgrade?

**Comment by sopitz** [comment]
I think I did, I will try tonight, currently our developers are working with it, therefore I can't try it right now. Sorry! And thanks for your help @superalex!

**Comment by ss-abramchuk** [comment]
Hi @superalex , I also have a similar problem with epic progress bar. I have installed latest stable commit of `taiga-backend` and latest `taiga-front-dist`. But I noticed that `taiga-front-dist` hasn't been updated since 23rd May and `taiga-front` has this commit [Improving epics progress](https://github.com/taigaio/taiga-front/commit/3492879160df6b08221d2b7fcfc9bf14659d5bc9) made on 22nd June. Probably that is the cause of the issue. Could you update `taiga-front-dist` to the latest stable version?

**Comment by bameda** [comment]
I've just regenerated taiga-front-dist with the last fixed. Could you upgrade your server and test it

**Comment by ss-abramchuk** [comment]
That fixed the issue for me, thanks

**Comment by bameda** [comment]
Great, you are welcome

**Comment by sopitz** [comment]
same here. that fixed it for us, too! Thanks @superalex and @bameda for the quick help. Much appreciated.
