### ISSUE TITLE
Cannot attach pictures

### ISSUE THREAD

**Issue by Musya21** [taigaio/taiga-front#1359]
![taiga bug](https://user-images.githubusercontent.com/31408832/29774434-d6ebd35c-8c1a-11e7-886f-c8a0290d8f31.jpg)

**Comment by bameda** [comment]
**Please provide the steps to reproduce this.**
**What is the expected behavior?**
**Is it happening in taiga.io or in your own instance?**
**What browser/version are you using?**
**Are there any console errors *(Ctrl + F12)* in red?**
Thanks for reporting!
