### ISSUE TITLE
[BUG] Task textbox too short

### ISSUE THREAD

**Issue by danieldownes** [taigaio/taiga-front#136]
Have looked over the issues, but did not spot anything related.

**Task textbox too short**

<img width="644" alt="image" src="https://user-images.githubusercontent.com/1720388/150112679-9fa9149a-cf2e-4e4f-9612-4757f65814fd.png">

I would like to be more verbose on the subject. Ideally the team knows what the tasks is from its title, but we find it takes a little bit more text than what is provisioned in this textbox.

**How can we reproduce the behaviour**
From a user-story, add tasks using the teal plus button.

**Workarounds**
We may draft the tasks in the story description first, and then paste them in. It would be more fluid to just type directly in the task textbox.

**Taiga environment**
Using Taiga.io, Chromium based browsers.

**Comment by ChriFo** [comment]
No problem with Firefox.
![Task input](https://user-images.githubusercontent.com/7130686/195262939-60e4c262-ed58-4f6c-98af-420384d27bba.png)
