### ISSUE TITLE
Subscription to a Paid Plan not working !

### ISSUE THREAD

**Issue by benjoz** [taigaio/taiga-front#1364]
**Issue** : users are not able to subscribe to a PAID PLAN when logged
**How to reproduce** : on Chrome 61 & on Safari, go to "Paid Plan", select Root, Monthly and Continue 
**Console** : Javascript error, see bellow

<img width="1672" alt="screen shot 2017-09-13 at 11 17 17 1" src="https://user-images.githubusercontent.com/1252868/30369710-b7d6674a-9875-11e7-975e-a2a63280525e.png">

**Comment by bameda** [comment]
Hi @benjoz we are working on it right now

**Comment by bameda** [comment]
we will tell you something as soon as possible.

sorry for the inconvenience

**Comment by jespino** [comment]
Fixed! Sorry for the inconvenience :disappointed:
