### ISSUE TITLE
Throws 500/504 when creating new users

### ISSUE THREAD

**Issue by sokoow** [taigaio/taiga-front#1368]
**Before adding an issue**
Please ensure that your issue is not already reported in our [issues list](https://tree.taiga.io/project/taiga/issues?order_by=-created_date).
If this issue was already reported, remember that you can upvote it to raise its importance.

**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
When trying to create a new user, system throws me 500 or 504. Please help me out with debugging, as the system doesn't give any useful details.

**If the current behavior is a bug, please provide the steps to reproduce.**
Install taiga yourself, try to create a new user

**What is the expected behavior?**
I'd like users to be created without any issue

**Is it happening in taiga.io or in your own instance?**
On my own instance

**What browser/version are you using?**
Firefox currenty

**Are there any console errors *(Ctrl + F12)* in red?**
Yes, I get 500/504, without much explanation

Thanks for reporting!

**Comment by bameda** [comment]
Please, review the log files of taiga to see the error.

**Comment by sokoow** [comment]
on frontend I see: 

```
2017/09/17 18:12:05 [error] 11#0: *363 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 10.36.0.0, server: localhost, request: "POST /api/v1/auth/register HTTP/1.1", upstream: "http://10.102.79.39:8000/api/v1/auth/register", host: "taiga.devopsknowledge.club", referrer: "https://taiga.devopsknowledge.club/register"
```

on backend:

```
Trying import local.py settings...
[2017-09-17 18:12:06 +0000] [233] [INFO] Booting worker with pid: 233
[2017-09-17 18:12:18 +0000] [44] [CRITICAL] WORKER TIMEOUT (pid:182)
```

nothing much to tell me what's wrong, and ideas?

**Comment by bameda** [comment]
It seems a problem with your email settings in taiga-back, your server return a 504 error (gateway timeout) because it spend a lot of time processing the response with every action that try to send an email.

**Comment by sokoow** [comment]
that was it, more debugging info would be needed
