### ISSUE TITLE
Feature request: Avoid registration when auth backend is set to LDAP

### ISSUE THREAD

**Issue by bzhtux** [taigaio/taiga-front#1373]
Hi guys,

With LDAP auth enabled within taiga-back, users can register locally from login page. We would like:

 - When LDAP auth is enabled, users should not be able to register locally, only LDAP users can log in.
 - Register button should disappear from login page.

Informations:

- taiga version: 3.1.0
- Browser: safari
- No errors reported

Thanks

**Comment by sokoow** [comment]
How can one enable the LDAP backend ?

**Comment by theriverman** [comment]
LDAP backend is not officially supported, however, it can be found under the following name online:
`taiga_contrib_ldap_auth`
It's quiet easy to setup and works pretty stable.

**Comment by sokoow** [comment]
It's not a feature request, it's a bug. Seems like  "publicRegisterEnabled": false," flag in conf.json doesn't work properly when ldap is used.

**Comment by bameda** [comment]
You should report this bug in the ldap contrib plugin repositorry.
