### ISSUE TITLE
Bug: Comment for User story is not saved

### ISSUE THREAD

**Issue by apekelnik** [taigaio/taiga-front#1376]
**Do you want to request a *feature* or report a *bug*?**
Bug

**Steps to reproduce.**
1. Set permissions as on the screen.
2. Login as User with this role
3. Go to any User story, create a comment
4. Save comment
5. Comment is not saved.

**What is the expected behavior?**
5. Comment is saved.

**Is it happening in taiga.io or in your own instance?**
taiga.io

**What browser/version are you using?**
Chrome, Version 60.0.3112.113

**Are there any console errors *(Ctrl + F12)* in red?**
no

**Screenshot with permissions**

![permissions](https://user-images.githubusercontent.com/24312310/31270838-a0eeb1e2-aa8e-11e7-93fd-bd6ee0b2ffa5.jpg)

**Comment by jespino** [comment]
In which role are you changing the permissions?

**Comment by apekelnik** [comment]
I am admin with full rights.

**Comment by apekelnik** [comment]
Admin

Sincerely yours,
Alex Pekelnik | Project manager | Skype: Alex Pekelnik
9065 Jollyville Rd, Suite 203C | Austin, TX 78759
Syberry Corporation | www.syberry.com<http://www.syberry.com/>

**Comment by jespino** [comment]
I mean, which role permissions are you editing?

**Comment by apekelnik** [comment]
It is called Stakeholder.

**Comment by jespino** [comment]
I can't reproduce the error with my own accounts and project, can you give me extra information, for example, which users can't comment and in which project? If you prefer, you can send me this data to support@taiga.io

**Comment by apekelnik** [comment]
@jespino I sent info to this e-mail.

**Comment by apekelnik** [comment]
@jespino I can comment if user story is not connected to Epic. Please, try.

**Comment by jespino** [comment]
Thank you, now I can reproduce it :)

**Comment by apekelnik** [comment]
It works after your changes! Thanks :)

**Comment by jespino** [comment]
You are welcome :)

**Comment by phoenixsboys** [comment]
Thanks, it work

Regard
<a href="http://termiteinsect.info/">Termite Insect</a><br>
