### ISSUE TITLE
Timeline cache(?) tries to load old URLs

### ISSUE THREAD

**Issue by theriverman** [taigaio/taiga-front#1377]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I migrated my own Taiga instance from one URL to an other.
Taiga itself works flawlessly, however, when moving to a project page, the Timeline tries to load contents (such as attachment image thumbnails) fromt the old address.
It looks like the timeline parses the url from some cache or static location. I did obviously restart Taiga in circus and restarted nginx (/var/cache/nginx is empty) but no help.

This behavior results in weakened security though, because the browser believes that I'm trying to load contents on a secure site from an insecure one.
(The previous address was HTTP, but the new on is HTTPS).

**If the current behavior is a bug, please provide the steps to reproduce.**
- Set up Taiga on HTTP
- Add an image attachment to a US
- Migrate the Taiga instance from an HTTP address to an HTTPS one
- Open the Timeline of your project
- Taiga will try to load the Timeline thumbnail from the old URL

**What is the expected behavior?**
Load the thumbnails from the new location.

**Is it happening in taiga.io or in your own instance?**
Own instance.

**What browser/version are you using?**
Firefox 57.0b5 (64-bit)

**Are there any console errors *(Ctrl + F12)* in red?**
Loading mixed (insecure) display content “http://taiga.xxxxx.yyyyyy/media/attachments/6/f/6/1/9f641f91b2f30aaeadasdasdasdasdasdasasdasd1e9fa93c3e/amazon.jpg.640x0_q85_crop.jpg” on a secure page

Thanks for reporting!

**Comment by jespino** [comment]
Yes, this is the current behavior because in timeline entries we store the full url. I have to study the implications of change this to store a relative path. If you want to fix it locally you probably have to update the data field inside the timeline_timeline table. It is a json field, so you have to modify the "attachments" field inside the json.

**Comment by theriverman** [comment]
I forgot to comment a feedback on this issue, sorry @jespino 
Though it may be not recommended, I modified the database and changed the urls in the timeline_timeline table -- it works fine now! :) 
Thanks!
