### ISSUE TITLE
Creating Interfaces, Customize User Interfaces

### ISSUE THREAD

**Issue by Mayr98** [taigaio/taiga-front#1378]
Hey, 
is there a way to create interfaces on taiga? I'm not able to find something about it. Also, I want to know how to customize the user interfaces, for example kanban. I know I'm probably in the wrong place for this, but I would really appreciate any help you could provide.

**Comment by Xaviju** [comment]
Hi @Mayr98 the answer is yes.

You can edit the UI (CSS) creating themes: https://taigaio.github.io/taiga-doc/dist/#themes
You can also create plugins editing the whole UI (structure and behavior) using taiga-contrib plugins. You'll find some in the taiga repo: https://github.com/taigaio/taiga-contrib-slack

Hope it helped
