### ISSUE TITLE
How do I view Tasks assigned to me or a Team Member?

### ISSUE THREAD

**Issue by SoupPlate** [taigaio/taiga-front#1379]
Hi, 

I wish to view all _Tasks_ assigned to an individual team member (_I'm using Kanban view_). I can see  this feature for _User Stories_ and for _Issues_, **but** not for _Tasks_? 

Current behaviour is to view Kanban _User Stories_ and/or _Issues_ via Filters on those pages.

Expected behaviour is for me as Product Owner to see exactly who is doing what. And for any Team Members to see all _Tasks_ assigned to themselves in one view. 

We are using the projects [here](http://taiga.reutersr53.net): **[http://taiga.reutersr53.net](http://taiga.reutersr53.net)**

I'm using Chrome Version 61.0.3163.100 (Official Build) (64-bit).

**Comment by jespino** [comment]
Hi @SoupPlate,

Using the Kanban, the normal behavior is to use each Card as a Task assigned to one person. The tasks inside the User stories of the kanban normally are used to organize inside the User story, but not for split the work in one User Story (This, of course, depends on the usage of the tool).

If you use Scrum, then, the sprints are organized in User Stories + Tasks. In this case, you can see the tasks inside the user stories of the current sprint.

About in what are the user working, you can see the Dashboard (home page of the logged user) of the user the section "Working On".

Other option to see who is working on what is use the Taiga support of exporting all its content in csv format: https://taiga.io/support/csv-reports/ (you can use this feature to download Taiga data and open it in any spreadsheet editor)

**Comment by SoupPlate** [comment]
Thanks @jespino . 

So I've now realised that to achieve what I require I need to promote my _User-Stories_ to _Epics_, and in turn their _Tasks_ into _User-Stories_ belonging to those new _Epics_!

Is there a way to do it without having to delete all the entries and starting again please?

**Comment by jespino** [comment]
Not an easy way. You can automatize it by a script using the API. can be relatively easy with python-taiga library for example.

Other option is export the project, and modify the dump file in json format to move things from one place to another. And finally, import again.

Anyway, both options requires a bit of effort. (Maybe it is a good opportunity to know the Taiga API to future interesting automation)

**Comment by SoupPlate** [comment]
Thanks @jespino . 

However when I try to Export the project I get a 404: **[https://i.imgur.com/1YjkVuJ.jpg](https://i.imgur.com/1YjkVuJ.jpg)**

**Comment by jespino** [comment]
This is a problem related to your nginx configuration, you have to configure correctly the "media" directory to be shared through nginx directly.

Here (https://taigaio.github.io/taiga-doc/dist/setup-production.html#nginx) you have an example of the nginx configuration, you need to define the "location /media" block.

**Comment by cmprmsd** [comment]
While using tasks to split work between workers is not the primary goal I think including us a lot of people use this as a way to organize. 

E.g. I'd like to have an onboarding process where the person is a user story. In that user story there are different tasks for account creation and so on which get assigned to the people administrating each system. 

It would be great if there was a view to see open tasks for oneself. 

I'm not sure if I can move this to epic and user stories instead as it was discussed above.
