### ISSUE TITLE
Adding a new language

### ISSUE THREAD

**Issue by canercandan** [taigaio/taiga-front#138]
How should we proceed to add a new spoken language ? If I am not wrong we only need to deal with the frontend.

**Comment by milovanderlinden** [comment]
I'm ready to translate Dutch, great project!

**Comment by nsdont** [comment]
I'm ready to translate Chinese! :smile:

**Comment by bameda** [comment]
Now you can help us get taiga translated into your language. fast, easy & Fun!x

https://www.transifex.com/connect/projects/?sort=undefined&search=Taiga

Thanks!!
