### ISSUE TITLE
Sprint Taskboard crashes when I move User Story Tasks from New to In Progress

### ISSUE THREAD

**Issue by AjitKamath** [taigaio/taiga-front#1387]
Hello,

I am trying to move a task from New to In Progress and the webpage just crashes and redirects me to the error page(the Taiga landscape). This has been happening since yesterday. I first suspected it to be a cache issue but it wasn't the case as it continues to happen even after clearing my cache. I tried it in different browsers too. No luck so far !

**Comment by jespino** [comment]
Hi @AjitKamath,

Do it happens in your own instance or in ours? In which project?
