### ISSUE TITLE
Sorting user stories based on story points fails

### ISSUE THREAD

**Issue by updiversity** [taigaio/taiga-front#1388]
**Before adding an issue**
Please ensure that your issue is not already reported in our [issues list](https://tree.taiga.io/project/taiga/issues?order_by=-created_date).
If this issue was already reported, remember that you can upvote it to raise its importance.

**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

I can't sort the user stories based on story points

**If the current behavior is a bug, please provide the steps to reproduce.**

Well, i added user stories and story points, then trying to sort them it gave me this error message...

**What is the expected behavior?**

To sort the user stories with the story points

**Is it happening in taiga.io or in your own instance?**

My instance

**What browser/version are you using?**

Chrome Version 62.0.3202.89 (Official Build) (64-bit)

**Are there any console errors *(Ctrl + F12)* in red?**

2app.js:8246 Uncaught TypeError: Cannot read property 'top' of undefined
    at app.js:8246
    at Object.open (app.js:8282)
    at HTMLDivElement.<anonymous> (app.js:9835)
    at HTMLDivElement.dispatch (jquery.js:4737)
    at HTMLDivElement.g.handle (jquery.js:4549)
(anonymous) @ app.js:8246
(anonymous) @ app.js:8282
(anonymous) @ app.js:9835
dispatch @ jquery.js:4737
g.handle @ jquery.js:4549

Thanks for reporting!

**Comment by jespino** [comment]
Yes, is very weird, in my own instance works correctly. I have to investigate it.

**Comment by leepfrog-ger** [comment]
Still running into this with the most recent version and chrome 81. Tested FF 76 which also throws the error.

```
app.js:8566 Uncaught TypeError: Cannot read property 'top' of undefined
    at app.js:8566
    at Object.open (app.js:8602)
    at HTMLDivElement.<anonymous> (app.js:10372)
    at HTMLDivElement.dispatch (jquery.js:4737)
    at HTMLDivElement.g.handle (jquery.js:4549)
(anonymous) @ app.js:7702
(anonymous) @ app.js:7702
(anonymous) @ app.js:9721
dispatch @ jquery.js:4103
g.handle @ jquery.js:4103
```

**Comment by yamila-moreno** [comment]
We have been doing some housekeeping work prior to Taiga6 upcoming release and we are reviewing old issues that we didn't correctly attend back then.
Regarding this issue, user stories are ordered only by priority (what you see is the priority) and you cannot reorder them in the backlog list. As this is the expected behaviour, I'm closing the issue.

Thanks for you participation on behalf the Taiga Team!
