### ISSUE TITLE
Can not add member to project

### ISSUE THREAD

**Issue by DblK** [taigaio/taiga-front#1400]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
Impossible to add user to project

**If the current behavior is a bug, please provide the steps to reproduce.**
Just fresh install, create project, go to admin member and hit add member button.
The display is not good and impossible to add member.

Here what the screen looks like.
<img width="737" alt="screen shot 2017-12-23 at 10 09 43 pm" src="https://user-images.githubusercontent.com/832617/34324004-09135548-e82e-11e7-92be-52aa8149bd2c.png">

**What is the expected behavior?**
Be able to add members.

**Is it happening in taiga.io or in your own instance?**
Own instance.

**What browser/version are you using?**
Chrome latest

**Are there any console errors *(Ctrl + F12)* in red?**
<img width="845" alt="screen shot 2017-12-23 at 10 07 29 pm" src="https://user-images.githubusercontent.com/832617/34323998-f46459da-e82d-11e7-8ddc-0668b441a233.png">

Thanks for reporting!

**Comment by DblK** [comment]
Seems to be because of https://github.com/m00re/taiga-docker/issues/1

**Comment by ava-dylang** [comment]
Just incase you guys need a second user to report the issue to confirm the bug, I ran into this as well.

**Comment by natsimhan** [comment]
I have the same bug;)
I'm using Taiga 3.1.0 (latest version) on the clean docker installation, everything works fine but I have exactly the same screen and the error in the console to add a member ...
I am under updated Waterfox (the fork of Firefox).
Any help is welcome;)
![bug_taiga_3 1 0_add_member](https://user-images.githubusercontent.com/5631475/36413790-2b2aaf80-1620-11e8-9a8e-a9beab7a5970.jpg)

**Comment by ava-dylang** [comment]
Eh it wsan't clean for me (i deleted 3.1.0's database and installed from scratch) but a revert worked for me for now.
