### ISSUE TITLE
Can't add member in Taiga 3.1.0

### ISSUE THREAD

**Issue by Hummel-Mors** [taigaio/taiga-front#1401]
I following the guide in any detail (https://taigaio.github.io/taiga-doc/dist/setup-production.html).
But after some hours of hard work (installing taiga a few times...) I can't get any further.

`
from .common import *

MEDIA_URL = "http://.....com/media/"
STATIC_URL = "http://.....com/static/"
ADMIN_MEDIA_PREFIX = "http://.....com/static/admin/"
SITES["front"]["scheme"] = "http"
SITES["front"]["domain"] = ".....com"

SECRET_KEY = "theveryultratopsecretkey"

DEBUG = False
PUBLIC_REGISTER_ENABLED = True

DEFAULT_FROM_EMAIL = "no-reply@.....com"
SERVER_EMAIL = DEFAULT_FROM_EMAIL

CELERY_ENABLED = True

EVENTS_PUSH_BACKEND = "taiga.events.backends.rabbitmq.EventsPushBackend"
EVENTS_PUSH_BACKEND_OPTIONS = {"url": "amqp:/guest:guest@localhost:5672/taiga"}

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_USE_TLS = True
EMAIL_HOST = "....-server.de"
EMAIL_HOST_USER = "us..."
EMAIL_HOST_PASSWORD = "pa...
EMAIL_PORT = 25
`

![bildschirmfoto 2017-12-29 um 02 48 31](https://user-images.githubusercontent.com/21189842/34427477-f3df99a2-ec42-11e7-98d2-e7df883eaea4.png)

![bildschirmfoto 2017-12-29 um 02 58 26](https://user-images.githubusercontent.com/21189842/34427580-312a1098-ec44-11e7-9888-51fc38e8404f.png)

`
{"_error_type": "taiga.base.exceptions.MethodNotAllowed", "_error_message": "Methode 'GET' ist nicht erlaubt."}
`

It's sooo frustrating!

Carsten

**Comment by WillyReyno** [comment]
I have the same problem, difficult to work as a team...
