### ISSUE TITLE
Can't access user menu with Firefox and Chromium

### ISSUE THREAD

**Issue by baby-gnu** [taigaio/taiga-front#1406]
**What is the current behavior?**

When I want to access the user menu, like to disconnect, the menu appears and disappears before I can move on it. 

I can't provide a short screen cast since GitHub does not accept theses formats

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Open a session
2. Put the mouse over the user name
3. Try to reach the disconnect action

**What is the expected behavior?**

The menu stay displayed when I switch from the user name to the menu entries, it's actually working only on gnome-web.

**Is it happening in taiga.io or in your own instance?**

I installed the stable version on an Ubuntu 16.04 like described in http://taigaio.github.io/taiga-doc/dist/#_setup_production_environment

**What browser/version are you using?**

* working
  * gnome-web 3.26.5.1
* no working
  * Firefox 58.0.1
  * Chromium 63.0.3239.108

**Are there any console errors *(Ctrl + F12)* in red?**

No errors

Thanks for reporting!

**Comment by diegocortassa** [comment]
This happened to me because the default administrator user image was broken causing the menu to move down a bit, try to update the user profile with a new image and the menu should work again.

**Comment by baby-gnu** [comment]
It was a fresh default installation to test the software and gravatar was disabled by default IIRC.

I do not have the software installed, so I can't test anymore.

I just wanted to point the fact that the behaviour was not the same with gnome-web 3.26.5.1 from Debian unstable.

Feel free to close this issue if you think it's not relevant any more as I stopped my tests, I just made the report to help.

Regards.

**Comment by ZamanOof** [comment]
![mouse-over](https://user-images.githubusercontent.com/9051946/72977639-cff84b00-3dcc-11ea-85e3-b6439eddde0d.gif)


> This happened to me because the default administrator user image was broken causing the menu to move down a bit, try to update the user profile with a new image and the menu should work again.
> 
> check if you hae "gravatar": True in your conf.json and have a firewall cutting your connection to the gravatar site
@diegocortassa 
But still need a solution.
Best Regards
