### ISSUE TITLE
Can't resize images in markdown editor

### ISSUE THREAD

**Issue by edward-nunez** [taigaio/taiga-front#1408]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

When resizing an image in Markdown editor, image retains it's original size and not the downsized one.

**If the current behavior is a bug, please provide the steps to reproduce.**

Attach an image using the markdown tag and try to resize the image and save.

**What is the expected behavior?**

Image should reduce to the size adjusted.

**Is it happening in taiga.io or in your own instance?**

Both

**What browser/version are you using?**

Firefox 58.0.2 (64-bit)

**Are there any console errors *(Ctrl + F12)* in red?**

No

**Comment by gfdesign** [comment]
I want to resize attached images in Taiga, specifically on descriptions or comments fields. 
Very frustrating not be able to do it :(
