### ISSUE TITLE
Forbidden downloading an attachment

### ISSUE THREAD

**Issue by antonizer** [taigaio/taiga-front#1411]
**Bug report**
Forbidden downloading an .apk attachment file. Please fix it. Thanks

**Comment by alexhermida** [comment]
Hi @antonizer we will look into the issue.

Please, if you would like to give us more details don't hesitate in contact with support@taiga.io.

Thank you!

**Comment by antonizer** [comment]
okay, sent

**Comment by alexhermida** [comment]
Hello @antonizer as we commented, we detected and fixed the problem. The updated to Django 1.11  wasn't setting properly the file permissions when uploading attachments bigger than 2.5MB. 

Thank you for the warning!
