### ISSUE TITLE
taiga-front-dist update

### ISSUE THREAD

**Issue by douglasmiranda** [taigaio/taiga-front#1419]
Please update [taiga-front-dist](https://github.com/taigaio/taiga-front-dist) to 3.1.3.

---

I don't know if you guys considered this before, but I think it would be better to show a .tar.gz link with the dist code of taiga-front on the release description, it seems better than using other GitHub repo.

**Comment by douglasmiranda** [comment]
taigaio/taiga-front-dist#16

**Comment by alexhermida** [comment]
Hi @douglasmiranda 

We just updated the last release https://github.com/taigaio/taiga-front-dist/releases/tag/3.1.3-stable
and we'll take into account your comments, thank you! :-)
