### ISSUE TITLE
Coffee-Script compiles broken code

### ISSUE THREAD

**Issue by theriverman** [taigaio/taiga-front#1426]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
The code compiles without any error (atleast nothing's in the console), but the results are completely broken. (see attachments for error log)

**If the current behavior is a bug, please provide the steps to reproduce.**

1. cd ~/
2. git clone -b stable https://github.com/taigaio/taiga-front.git
3. cd taiga-front
4. npm install && gulp

Open browser pointing to frontend and click `Login`.

**What is the expected behavior?**
Do not throw such warning and allow me to Log in

**Is it happening in taiga.io or in your own instance?**
Own instance

**What browser/version are you using?**
Firefox 58.0.2

**Are there any console errors *(Ctrl + F12)* in red?**
A lot! See attached file for detailed and organized logs.
The `conf.json` is not missing. I'm using the same as on the production server except the URLs.

If I get taiga-front-dist and expose it with the same conf.json, there are no warnings and I can log in.
I can't tell if the code itself or the compiler is broken, but something's gone bad recently.

[taiga-front_issue.txt](https://github.com/taigaio/taiga-front/files/1803567/taiga-front_issue.txt)

**Comment by natrist** [comment]
Are you sure npm and gulp ran correctly? I have built and installed from the latest master and it works just fine. Maybe try that instead of the stable branch and write back the results?

**Comment by theriverman** [comment]
I'm sure npm and gulp ran correctly. Well, more accurately: I'm sure there's no visible error. No error message, no warning. However, I fired up a VM, and on that I can compile the code without any issues.
I have no idea where did it go wrong but thanks for confirming that it works for you!
