### ISSUE TITLE
Blank Page after fresh installation

### ISSUE THREAD

**Issue by vahid07** [taigaio/taiga-front#1430]
Hi,

i install taiga according this wiki page on ubuntu 16.04 
http://taigaio.github.io/taiga-doc/dist/setup-production.html

but i see i white blank page
https://studio724.net/

**Comment by migonzalvar** [comment]
It seems everything is working for you now. We hope you enjoy taiga!

**Comment by vahid07** [comment]
Yes. we have a problem on https version and with debug process its solved.
