### ISSUE TITLE
[Wiki] Text formatting is lost when copy paste

### ISSUE THREAD

**Issue by iwkse** [taigaio/taiga-front#1431]
In the Wiki module, if HTML mode is set, copy & paste some text doesn't maintain formatting.
I works fine in Markdown mode.

**Comment by foliovision** [comment]
This is a near duplicate of [1280](https://github.com/taigaio/taiga-front/issues/1280).

Quick switch between HTML/Markdown solves the issue. Should be easy to at least keep line breaks though and not strip linebreaks from the incoming text, creating mush.
