### ISSUE TITLE
Serious bug feedback!!!

### ISSUE THREAD

**Issue by tr654992156** [taigaio/taiga-front#1432]
**Before adding an issue**
Please ensure that your issue is not already reported in our [issues list](https://tree.taiga.io/project/taiga/issues?order_by=-created_date).
If this issue was already reported, remember that you can upvote it to raise its importance.

**Do you want to request a *feature* or report a *bug*?**
I want to report a bug.
**What is the current behavior?**
When I create a new rope in the scene of crane which is the sample scene of rope 3.3, the unity editor will break down, even the system! However, the rope 3.2 does not has this problem
**If the current behavior is a bug, please provide the steps to reproduce.**
In the scene of crane:
(1) create a new rope (include: obirope, obisolver, obiBezier)
(2) click the "play" button, the unity editor will break down!
**What is the expected behavior?**
It will display a normal and simple rope.
**Is it happening in taiga.io or in your own instance?**
In my own instance.
**What browser/version are you using?**
Unity 5.6.4
**Are there any console errors *(Ctrl + F12)* in red?**
No
Thanks for reporting!

**Comment by bameda** [comment]
Sorry @tr654992156 but what is a rope in Taiga?, this is the repository of taiga (https://taiga.io) a project management software. 

I think you made a mistake reporting this error in the wrong way.
