### ISSUE TITLE
program crashed

### ISSUE THREAD

**Issue by LeoHqLi** [taigaio/taiga-front#1448]
Hello, when I used ObiFluid, the program crashed in my own instance.Version of the Obi that i used is 3.2.

Faulting application name: water.exe, version: 5.6.1.24755, time stamp: 0x5910657a
Faulting module name: libOni.dll, version: 0.0.0.0, time stamp: 0x59a32a1d
Exception code: 0xc0000409
Fault offset: 0x0006b926
Faulting process id: 0x41e8
Faulting application start time: 0x01d3e1bd5ddb1cfe
Faulting application path: C:\Users\Administrator\Desktop\water1645\water.exe
Faulting module path: C:\Users\Administrator\Desktop\water1645\water_Data\Plugins\libOni.dll
Report Id: 35857696-b35c-4a2c-b6b5-b6bfacf2aad0
Faulting package full name: 
Faulting package-relative application ID:

**Comment by bameda** [comment]
I'm sorry @LeoHqLi but I think you reported the error in the wrong repository. This is for issues related to Taiga, the freen open source project management software.

Regards
