### ISSUE TITLE
Profile and Privacy

### ISSUE THREAD

**Issue by herrold** [taigaio/taiga-front#1454]
**Before adding an issue**

I searched the GH index under the terms on the Subject line, and no relevant hits appear

**Do you want to request a *feature* or report a *bug*?**

missing 'feature'

**What is the current behavior?**

There is no way to limit the visibility of a Profile, nor of 'everything you do and what you are working on'

The profile 'Edit' page states by default:

> Your profile
> 
> People can see everything you do and what you are working on. 
> Add a nice bio to give an enhanced version of your information.

With the concern about personal information 'cross-linking' which the recent Facebook / Cambridge Analyticia 'harvesting' and the relentless scouring of the 'public' and non-ACL'd web, there needs to be a way to be less than 'wide open; as to:

 - the existence of an account
 - the contents the profile
 - any offered 'bio' (although this is seemingly at least partially under the end user's control, if one choses not to submit a meaningful one'
 - 'everything you [the user]do[es]'
 - what you [the user is]  are working on

Clearly ACL mechanisms exist in parts of the project (viz., 'private vs. public' projects)

The same design work needs to be applied here, in advance of the European GDPR

**If the current behavior is a bug, please provide the steps to reproduce.**

NA

**What is the expected behavior?**

fine grained end user control of visibility to the information types listed above under the control of the user

**Is it happening in taiga.io or in your own instance?**

present in all instances as of 2018 May

**What browser/version are you using?**

Firefox 52 ESR

**Are there any console errors *(Ctrl + F12)* in red?**

?? this key sequence does nothing in my particular browser

There are however 34 HTML tidy errors on this page [  https://github.com/taigaio/taiga-front/issues/new ]:

> Info: 34 errors / 0 warnings
> available at:  http://users.skynet.be/mgueury/mozilla/

Thanks for reporting!

**Comment by alexhermida** [comment]
@herrold thanks for the feedback. We included this feature in the backlog to take into account towards next releases.
