### ISSUE TITLE
Feature request: paste images direct into description fields / as attachments

### ISSUE THREAD

**Issue by sc0ttc0** [taigaio/taiga-front#1458]
Feature

**What is the current behavior?**
You cannot easily paste an image into the description or comments or attachments box direct from the clipboard.  I have seen this 

**What is the expected behavior?**
Copy an image to the clip board and  then on the task / story description field be able to paste the image directly.

And/or be able to paste the image direct such that it becomes an attachment.

This avoids the usual hassle of capturing an image (often a screenshot or part screenshot), saving it to the file system, finding it on the file system and uploading to the browser window.

I believe this might only work in newer browsers than can capture the pasted image as base64 data then upload it to the server .

**Comment by marcus-davies** [comment]
This would be a really useful feature and would save me sending messages on slack or creating, cropping files and uploading them to a ticket which is very time consuming

**Comment by petrofm** [comment]
> Does anyone know of a good open source project we could use as a reference in order to implement this change? I'd be happy to commit some time to it if we had an example
here https://github.com/peclik/clipboard_image_paste

**Comment by theriverman** [comment]
In HTML editing mode, you can simply drag&drop images into both the description and the comments field. It gets uploaded as an attachment and it’s automatically referenced in the field you’re currently editing. 
This feature is already there but not entirely trivial.

**Comment by deAtog** [comment]
@petrofm There's an pretty good write-up here of how to obtain images pasted to the browser: https://web.archive.org/web/20120502162434/http://joelb.me/blog/2011/code-snippet-accessing-clipboard-images-with-javascript/ and an MIT licensed open source project here written in coffeescript, which you can decaffinate using https://decaffeinate-project.org/, that demonstrates its use: https://github.com/JoelBesada/pasteboard

**Comment by Adonts** [comment]
A very useful feature  !

**Comment by sc0ttc0** [comment]
> 
> 
> In HTML editing mode, you can simply drag&drop images into both the description and the comments field. It gets uploaded as an attachment and it’s automatically referenced in the field you’re currently editing.
> This feature is already there but not entirely trivial.

I've not keep an eye on this .. so not tried the suggestion, but will do.  I think though you'd still need the image saved on the file system ... if like me you have a quick key combo for using a tool to snap a portion of the screen marking it up, then copy back to clipboard - I still want to go straight from clipboard in as a pasted image.  Makes capturing changes so much easier..

**Comment by lumotroph** [comment]
Check this out.
http://jsfiddle.net/6yocdszm/

**Comment by cenggel** [comment]
A very useful feature !

**Comment by NatachaMenjibar** [comment]
We have been doing some housekeeping work prior to Taiga6 upcoming release and we are reviewing old issues that we didn't correctly attend back then. 
Since Taiga6 brings a significant UX/UI rework, we encourage you to wait and see if Taiga6 satisfies this need and open a new issue if that's not the case. This time we will make sure to review it when it comes through. 

Thank you very much on behalf of the Taiga Team!

**Comment by pixtur** [comment]
After creating a bunch of issues with Taiga, I believe this feature is essential. I got used to working heavily with screenshots both on Windows and Mac and pasting them everywhere, from Trello, Slack, Teams, Dropbox Paper, Figma, Discord, etc. 

IMHO, this is not feature. Not implementing it, feels like a bug.

The issue should be reopened or another feature request should be created.

**Comment by theriverman** [comment]
Hey @sc0ttc0 & @pixtur ,
Could you try switching from **Markdown** edit mode to **HTML** and try pasting an image from your clipboard?

I clearly remember using this feature back in 2017/2018 for my company.
I have just tested this feature and it works quite well on the latest deployed Taiga version (hosted on tree.taiga.io) and also works for our internal version which is roughly 1,5 years old.

The screenshot gets automatically added as an attachment and referenced inline the text.

**Comment by pixtur** [comment]
Thanks! I will try this.

**Comment by pixtur** [comment]
Works like a charm!
