### ISSUE TITLE
Slow rendering Kanban view

### ISSUE THREAD

**Issue by jadelaop** [taigaio/taiga-front#1460]
Hello,

In my project, i have thousands of User Stories and my Kanban view load very slow...

I checked CPU and RAM usage and it is Ok, RAM over 400MB and CPU over 10% for every request of Kanban view.

Then, I believe that I have a problem with Kanban view rendering when a I have a lot of User Stories in the project.

Something to do with in my config files or my server?

Thank you.

**Comment by theriverman** [comment]
The US rendering is done on the client side.
What you can do is hiding the Done/Finished column (suppose you have one or more).
That can reduce the loading time (I suppose).
