### ISSUE TITLE
"Assign to me" bug

### ISSUE THREAD

**Issue by subpardaemon** [taigaio/taiga-front#1472]
private hosted taiga instance, LDAP users, in private project, members already added to the project.

when clicking on "Assign to me" a user story's screen, the following error shows up on the console (i included a heartbeat msg before and after for the sake of completeness):

HeartBeat send PING
angular.js:13550 WebSocket message received: {"cmd":"pong"}
angular.js:13550 HeartBeat recived PONG
--- here comes the important part ---
angular.js:13550 TypeError: Cannot read property 'push' of undefined
    at p.u [as assignToMe] (app.js:5563)
    at fn (eval at compile (angular.js:14432), <anonymous>:4:221)
    at e (angular.js:15485)
    at i (angular.js:25018)
    at p.$eval (angular.js:17229)
    at p.$apply (angular.js:17329)
    at HTMLAnchorElement.<anonymous> (angular.js:25023)
    at HTMLAnchorElement.dispatch (jquery.js:4737)
    at HTMLAnchorElement.g.handle (jquery.js:4549)
(anonymous) @ angular.js:13550
(anonymous) @ app.js:9032
$apply @ angular.js:17334
(anonymous) @ angular.js:25023
dispatch @ jquery.js:4737
g.handle @ jquery.js:4549
--- that's it, folks! ---
angular.js:13550 HeartBeat send PING
angular.js:13550 WebSocket message received: {"cmd":"pong"}
angular.js:13550 HeartBeat recived PONG*

**Comment by bameda** [comment]
#1472 and #1473 seems to be related. Have you try to clean the cache of your browser? What version of taiga-front-dist and taiga-back are you using? (`git describe --tags` to show the version)
