### ISSUE TITLE
Bulk Entry for US Tasks

### ISSUE THREAD

**Issue by benyanke** [taigaio/taiga-front#1483]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
The bulk input method available for user stories is not available on tasks.

**What is the expected behavior?**
It would be very helpful to be able to bulk-add tasks, especially for some user stories which have a large amount of tasks

**Comment by alexhermida** [comment]
@benyanke could you elaborate a little bit more? Currently you can add tasks in bulk from the Taskboard (https://taiga.pm/adding-tasks-in-bulk-from-the-taskboard/).

Thank you!

**Comment by benyanke** [comment]
I was thinking of adding them in the User Story view - our team doesn't end up using the taskboard extensively. Exactly the interface I had in mind, but just on a different screen than I expected.

I wonder if that could be added here?

![image](https://user-images.githubusercontent.com/4274911/42459001-96b0c52a-8360-11e8-8ec3-bc4afe57fd00.png)

**Comment by LosaMatova** [comment]
Hello, I second this. I would very much like to be able to Bulk-add Tasks on KanBan boards.

**Comment by LosaMatova** [comment]
I would also like this. My boss is breathing down my neck about it not being here.
