### ISSUE TITLE
Feature request - Matrix/Riot integration

### ISSUE THREAD

**Issue by rudynz** [taigaio/taiga-front#1486]
It is already possible to integrate a chat with Slack and Hipchat. But both of those are  proprietary chat services where the data ends up in some U.S. Cloud. 
One of the main reasons for choosing Taiga is that it can be self hosted and therefor allows to keep that control over your own data.
It would be great to integrate a chat with Matrix / Riot (https://matrix.org/blog/home/).
I think this is one of the most promising open source chat services that are currently developed.
Thank you for your great work
Rudy

**Comment by theriverman** [comment]
Hi,
Use Mattermost for chat. It can be hosted on your on premises and it does integrate well with Taiga, because Mattermost is using the same APIs as Slack --> you can use the Slack plugin for Taiga.
We're having this setup and works quite reliably.

**Comment by rudynz** [comment]
Hi,
I also locked at Mattermost and it is not 100% open source in my opinion. If you want all the features (like search all massages and video/voice to many) you need to buy the Enterprise version.
But being able to integrate it with Taiga is another plus on the list for mattermost

**Comment by rudynz** [comment]
I kind of got it to work using the matrix-appservice-webhooks
https://matrix.org/docs/projects/as/matrix-appservice-webhooks.html
But unfortunately the links don't work.
See https://github.com/turt2live/matrix-appservice-webhooks/issues/14

**Comment by rudynz** [comment]
The same wish also exists on the Matrix side
https://github.com/turt2live/matrix-wishlist/issues/26
If you like it, please give it a thumbs up!
