### ISSUE TITLE
Bug: Issue not promoted to user story

### ISSUE THREAD

**Issue by LizeMonametsi** [taigaio/taiga-front#1488]
**Before adding an issue**
Please ensure that your issue is not already reported in our [issues list](https://tree.taiga.io/project/taiga/issues?order_by=-created_date).
If this issue was already reported, remember that you can upvote it to raise its importance.

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
An issue is not promoted to a user story

**If the current behavior is a bug, please provide the steps to reproduce.**
Go to Issues
Choose an issue and promote is to a user story
Go to the Backlog
The story is not there

**What is the expected behavior?**
The issue is available as a user story on the backlog once it has been promoted to a user story

**Is it happening in taiga.io or in your own instance?**
taiga.io

**What browser/version are you using?**
Chrome Version 67.0.3396.99 (Official Build) (64-bit)

**Are there any console errors *(Ctrl + F12)* in red?**
No

Thanks for reporting!

**Comment by t0mgerman** [comment]
Have you ruled out caching issues in the browser? This is working for me on a self-hosted instance, latest taiga-front, but I found my nginx setup was caching the user-story call so the promoted story didn't immediately appear
