### ISSUE TITLE
Unable to turn on public registration(sign up).

### ISSUE THREAD

**Issue by sibil** [taigaio/taiga-front#1512]
In my taiga instance, "publicRegisterEnabled": false. was set and working. 

I upgraded to Taiga 3.3. Now "publicRegisterEnabled": true is not enabling public registration. "SIGN UP" button is greyed out in the registration form.

Steps to reproduce:
1. Set "publicRegisterEnabled": false.  restart the services and public registration is now disabled.
2. "publicRegisterEnabled": true, 
Expected public registration to re-appear. Please note that "sign up" is disabled even on invitaion links.
Enabled in the backend as well.
PUBLIC_REGISTER_ENABLED = True

Tried in the latest version of  Google chrome and Mozilla Firefox, Windows 10

No browser console errors.

**Comment by basilrabi** [comment]
I also thought this was a bug in taiga. It happened to me just now. Initially both of my settings were set to false then I tried to change it to true then restarted the service then restarted the server. However, there were still no visible changes in the browser after I went to my taiga instance in the browser. What I did was press `Reload current page` in Firefox and then I saw the `Sign-up Button`. I think this is just a caching issue in the browser and not an issue in taiga.
