### ISSUE TITLE
Stories dragged and dropped on a sprint can end up in any position

### ISSUE THREAD

**Issue by vdemario** [taigaio/taiga-front#1517]
**Do you want to request a *feature* or report a *bug*?**

Report a bug.

**What is the current behavior?**

In the backlog page, when I drag a story that is inside a sprint to a new position in that sprint it sometimes ends up in a random position.

**If the current behavior is a bug, please provide the steps to reproduce.**

Drag a story down (or up) and see it moving to the wrong place after it is dropped.

Here is a GIF showing a part of the screen where this happens.

![taigabug](https://user-images.githubusercontent.com/6087424/43662740-43627148-973d-11e8-9332-4407f0b7d687.gif)

As you can see, it is a little bit random, not every drag and drop ends up in the wrong place.

**What is the expected behavior?**

The story stays in the spot it is dropped. For instance, when I drag story 249 in the GIF it should end up in the third line not the fourth.

**Is it happening in taiga.io or in your own instance?**

It's on tree.taiga.io.

**What browser/version are you using?**

Chrome 67.0.3396.99

**Are there any console errors *(Ctrl + F12)* in red?**

No, the console is clean.

edit: This is extremely common for me. Let me know how I can help you reproduce this because it is so prevalent in my experience that reordering stories on a sprint is very painful.

**Comment by alexhermida** [comment]
Hello @vdemario thank your for you feedback!. It's fixed in the current release https://github.com/taigaio/taiga-front/releases/tag/3.3.15
