### ISSUE TITLE
Bug Report: Still have permissions after logout (Google Chrome)

### ISSUE THREAD

**Issue by justengel** [taigaio/taiga-front#1541]
*bug*

**What is the current behavior?**
I logged into my self-hosted taiga server. I logged out of taiga. Everything displayed properly. The screen asked me to login at the top right corner. Taiga shows that I am logged out.

I click on my public project. I still have access to the admin panel. I can change any value in the admin panel. I can go into the wiki and change wiki pages. I can still do anything.

Taiga shows I am an anonymous user. The permission settings in my project does not give any permissions to anonymous users. I think the back-end still registered that I was logged in.

I was using Chrome. I opened firefox and went to my taiga server. I went to the same project as an anonymous user. I did not have access to the admin panel, and I could not change anything like the wiki pages.

**If the current behavior is a bug, please provide the steps to reproduce.**
(Google Chrome) Login > Create a public project > Logout > Go to the same public project > You still have admin access.

**What is the expected behavior?**
It shows that I am logged out, but I still have my permissions. I should not have permissions or admin access to my public projects.

**Is it happening in taiga.io or in your own instance?**
My own instance.

**What browser/version are you using?**

Google Chrome | 68.0.3440.106 (Official Build) (64-bit) (cohort: Stable)
-- | --
Revision | 1c32c539ce0065a41cb79da7bfcd2c71af1afe62-refs/branch-heads/3440@{#794}
OS | Windows
JavaScript | V8 6.8.275.26

I also reloaded the page and cleared the cache and still had admin access.

Firefox - No Issue
Microsoft Edge - No Issue

**Are there any console errors *(Ctrl + F12)* in red?**
```
angular.js:13550 TypeError: Cannot read property 'auth_token' of null
    at app.js:1830
    at a (angular.js:15961)
    at angular.js:15977
    at p.$eval (angular.js:17229)
    at p.$digest (angular.js:17045)
    at p.$apply (angular.js:17337)
    at app.js:923
    at lodash.js:2762
(anonymous) @ angular.js:13550
angular.js:13550 TypeError: Cannot read property 'auth_token' of null
    at app.js:1830
    at a (angular.js:15961)
    at angular.js:15977
    at p.$eval (angular.js:17229)
    at p.$digest (angular.js:17045)
    at p.$apply (angular.js:17337)
    at angular.js:17633
    at o (angular.js:5869)
    at angular.js:6145
```

**Comment by alexhermida** [comment]
@justengel I tried to reproduce the issue but I didn't find the way to do it, neither in tree.taiga.io nor in a custom instance. 

Please, could you give us more detailed information? Even a tiny screencast would be helpful.

**Comment by justengel** [comment]
It could be from signing in with GitHub. The only thing I did was setup a production environment and sign in with GitHub. After signing in with GitHub I changed my password and started using a username and password to sign in.

I just created a project, logged out, navigated back to the project and saw that I had admin access. I tried replicating this on Firefox and Microsoft Edge. This only happens on Google chrome.

Is there a javascript command I can run in the console to help debug?

Below is an image showing that I am not logged in and still have access to the admin panel of a project I own.

![taiga_login_issue](https://user-images.githubusercontent.com/5590556/44264804-f38b8f00-a1f1-11e8-9be9-d3f272ee9358.PNG)

**Comment by roque86** [comment]
I am facing the same issue with Firefox 65.0 (64-bit) or Chrome 70.0.3538.77, and a clean install of Taiga 4.1.0.
I have full access even when logged off. A new private section, however, sends me to the login page instead, and I only have an "External User" access.   
Differently from @justengel, I do not have a GitHub module, nor am I using any other integrations.
My project is a private one, so the issue should not be restricted to public projects. 
My Taiga instance is behind a proxy, but I do not think that should affect this workflow.

**Comment by rushfly** [comment]
I have the same bug. But it **fully** logout when I clean browsed data ( I use Chinese UI, so I don't know what English to say.) include cookies through the function of Chrome menu. So, it's might be cookie's life time problem.
