### ISSUE TITLE
Any way to force-add users to a project?

### ISSUE THREAD

**Issue by JohnDorien1** [taigaio/taiga-front#1542]
**Before adding an issue**
Please ensure that your issue is not already reported in our [issues list](https://tree.taiga.io/project/taiga/issues?order_by=-created_date).
If this issue was already reported, remember that you can upvote it to raise its importance.

**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
It seems I am not able to force-add users into a project. Right now it seems I can only invite.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
I need to be able to force users into a project, no matter if already on the (private) taiga instance or not, for I can instantly assign tasks or US to them. In my setup taiga is connected to the ldap and co-workers need to be assigned even if e.g. on holidays. So i need to override somehow if they "accept the invitation" or not.

**Is it happening in taiga.io or in your own instance?**
Own instance, taiga.io not tested

**What browser/version are you using?**
tried all of them

**Are there any console errors *(Ctrl + F12)* in red?**
nope

Thanks for reporting!

PS: Either there is already a way to achieve this, then please guide me, else please drop me a hint where i need to look at in the sources, I am not a good coder but willing to try and create commit in case of success.

**Comment by benyanke** [comment]
We would also like this - ability to add users to a project as an IT admin or a user's manager is a needed feature.
