### ISSUE TITLE
Sprint Issues: View progress/status on Sprint Taskboard

### ISSUE THREAD

**Issue by LizeMonametsi** [taigaio/taiga-front#1543]
**Before adding an issue**
Please ensure that your issue is not already reported in our [issues list](https://tree.taiga.io/project/taiga/issues?order_by=-created_date).
If this issue was already reported, remember that you can upvote it to raise its importance.

**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
The status of a Sprint Issue on the Sprint Taskboard isn't visible in the same way as the Tasks are.

**If the current behavior is a bug, please provide the steps to reproduce.**
Currently one has to navigate to Issues to see the status of a Sprint Issue (or am I missing something?)

**What is the expected behavior?**
View status of the Sprint Issue on the Sprint Taskboard so that the status of all work in the sprint is visible. (Note: Really loving the fact that one can now view Issues on the Sprint Taskboard so that all work in the Sprint is visible in the same place - thanks for the feature!)

**Is it happening in taiga.io or in your own instance?**
taiga.io

**What browser/version are you using?**
Chrome Version 68.0.3440.106 (Official Build) (64-bit)

**Are there any console errors *(Ctrl + F12)* in red?**
No

Thanks for reporting!

**Comment by alexhermida** [comment]
@LizeMonametsi currently you should view the issue status inside the card at the bottom left. 

![sprint_issues](https://user-images.githubusercontent.com/4062867/44449338-181aa900-a5ee-11e8-84d6-79abb9c61654.png)

Is that correct?

**Comment by alexhermida** [comment]
We're going to close this since it seems works ok.

**Comment by AndreSteenbergen** [comment]
Shouldn't it be better to have the swimming lane match the status in the bottom left corner?
