### ISSUE TITLE
Sprint taskboard top summary alignement in Firefox

### ISSUE THREAD

**Issue by ajira86** [taigaio/taiga-front#1547]
**What is the current behavior?**

This is a little UX issue on vertical alignment on summary div in context of "Sprint taskboard".

This issue doesn't affect the summary div in the "Backlog" view

**If the current behavior is a bug, please provide the steps to reproduce.**

To see this issue, simply load a sprint taskboard page with Firefox. The issue doesn't affect Chromium nor Gnome Browser

**What is the expected behavior?**

It should be correctly aligned like in other browser.

**Is it happening in taiga.io or in your own instance?**

Yes, this problem occurs in all versions that I tried (from 3.1.1 to 3.4)

**What browser/version are you using?**

Firefox Nightly

**Are there any console errors *(Ctrl + F12)* in red?**

No error.

**Comment by alexhermida** [comment]
@ajira86 we just fixed this issue in this PR https://github.com/taigaio/taiga-front/pull/1535 
It's already included in the last 3.4.1 version we just published yesterday also in taiga.io. Could you try to force a refresh and confirm if it's the same error?

**Comment by ajira86** [comment]
Hi @alexhermida, I took a quick look on the fix from my container and I can confirm the fix. Thanks !
