### ISSUE TITLE
Can't move the cursor to the left with the keyboard

### ISSUE THREAD

**Issue by vdemario** [taigaio/taiga-front#1560]
**Do you want to request a *feature* or report a *bug*?**

Report a bug.

**What is the current behavior?**

Moving the cursor to the left with the arrows on the keyboard does not move the cursor. This doesn't happen as soon as I open taiga but after I leave the tab open for a while and come back it starts happening. I don't know if it's tied to being left in the background, if it's tied to a certain amount of time, I just know that if I leave taiga open eventually I can't move the cursor to the left with the keyboard.

It seems to affect every textarea and every text input. I've seen it happen with the description of a new user story, editing the title of an existing story, commenting on a task, it seems to happen everywhere.

**If the current behavior is a bug, please provide the steps to reproduce.**

I don't have exact steps since I don't know exactly what triggers this behavior. What I can say is: open Taiga, work as normal, leave the tab open and go do something else. Come back later and try to edit some text somewhere.

**What is the expected behavior?**

Normal text navigation.

**Is it happening in taiga.io or in your own instance?**

tree.taiga.io

**What browser/version are you using?**

I was on Chrome 68.0.3440.106 when I started seeing this behavior. I'm now on Firefox Developer Edition 62.0b19. It happens on both browsers.

**Are there any console errors *(Ctrl + F12)* in red?**

No. There are lots of logs about a websocket heartbeat but no errors.

**Comment by alexhermida** [comment]
@vdemario thanks for reporting. We'll deploy a new patch version next monday with this fix. Thanks!

**Comment by vdemario** [comment]
Thanks @alexhermida. I really appreciate how fast you guys fix things.

**Comment by alexhermida** [comment]
Thank you @vdemario We just fixed the issue also in https://tree.taiga.io/
