### ISSUE TITLE
[Bug] Wiki page's content are not displayed

### ISSUE THREAD

**Issue by carmelocatalfamo** [taigaio/taiga-front#1563]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
Entering on wiki page: pages are not displayed

**If the current behavior is a bug, please provide the steps to reproduce.**
1) Login taiga app
2) Open any Project
3) Go to "WIKI" section
4) Open any wiki page

**What is the expected behavior?**
Entering on wiki page: pages are correctly displayed

**Is it happening in taiga.io or in your own instance?**
My own instance, on Ubuntu 18.04.
Taiga (backend and frontend) it's updated to latest commits.

**What browser/version are you using?**
Chrome v68.0.3440.106

**Are there any console errors *(Ctrl + F12)* in red?**
```
Error: [$injector:unpr] Unknown provider: tgWikiHistoryServiceProvider <- tgWikiHistoryService <- tgWikiWysiwygDirective
```

**Comment by pauloxnet** [comment]
Same issue for me. I've just updated taiga-front-dist and taiga-back as defined here
https://taigaio.github.io/taiga-doc/dist/upgrades.html#_3_3_0_3_4_x

With taiga 3.3.16 I was able to view and edit the wiki pages, after the upgrade to the latest version of taiga 3.4 I can't see or edit my wiki page ( I can see only the title, meta info box and attachment section but not the page content)

**Comment by alexhermida** [comment]
@carmelocatalfamo @pauloxnet we can't reproduce it neither local or production environment. Maybe it is a cache problem. Could you try to do a hard refresh (Ctrl+F5 or Cmd+Shift+R) in the browser?

If the problem persists try to compile again the frontend if you aren't using https://github.com/taigaio/taiga-front-dist.

**Comment by carmelocatalfamo** [comment]
going back to commit **62d4f10** (for frontend dist) works.
Error is [here](https://github.com/taigaio/taiga-front-dist/commit/0d1cf7c92a4de6bbcd724fff2586cc009c546307) on latest commit.

**Comment by pauloxnet** [comment]
Rolling back taiga-front-dist to 62d4f10 have worked here too.

**Comment by filippo-20tab** [comment]
thanks @carmelocatalfamo for your solution. Works for me as well.

**Comment by alexhermida** [comment]
Seems to be some kind of problem during the compilation, the code it's ok. Please, could you try the last [3827101c](https://github.com/taigaio/taiga-front-dist/commit/3827101c213639c87aeceda957a5e3bea6772f92) commit? 

Thanks for reporting.

**Comment by pauloxnet** [comment]
@alexhermida your last commit have fixed the bug , thanks!

**Comment by alexhermida** [comment]
thank you @pauloxnet !
