### ISSUE TITLE
Problem with translation because of combination of words and missing translation points.

### ISSUE THREAD

**Issue by oderwat** [taigaio/taiga-front#1570]
We are going to use taiga for project management for a German client. 

We also did a lot of the German translation in the past (rera1, oderwat, nkpyck). Currently we have a hard time to translate the headers in the light box. 

For example "new issue" should get "Neues Ticket". We managed to translate "new" to "neu". So now it shows "neu issue". Thats not acceptable. We also can't just say "neues" as translation vor "new" as this is just another form of the same word). 

In addition the next word also is dynamical (object afair). First of, we did not yet manage to find where wo translate these words (issue, task... aso). 

Second: Even if we could translate this, it would not be correct for the German language. What we need would be that those headers are not "joined" from basic words but the terms need to be fixed. Something like "lightbox_header_new_issue" gets "new issue" and "Neues Ticket". 

So besides having "singular" and "plural", there are also the "virtual" genders of words and a diversity of flexing which needs to be considered. 

I personally think the translation should not use combined words but only simple and clearly targeted strings.

**Comment by alexhermida** [comment]
@oderwat we tried to improve some _translations_ with your comments it this PR #1574 already merged and in the stable branch. Anyway, we'll take into account this for new and old translations. Thank you!

**Comment by oderwat** [comment]
Thank you!
