### ISSUE TITLE
Issues > Filter column becomes unusable if multiple filters selected on small screen 

### ISSUE THREAD

**Issue by MaartenW** [taigaio/taiga-front#1582]
*bug*

When on small screen (13" laptop), in _issues_, with multiple filters selected, 

<img width="421" alt="lots of filters" src="https://user-images.githubusercontent.com/1092133/45685604-1e973480-bb4a-11e8-9657-97581bd48b1f.png">

selecting an extra filter becomes very cumbersome and almost impossible.

<img width="359" alt="filter unreahable" src="https://user-images.githubusercontent.com/1092133/45685627-366eb880-bb4a-11e8-8638-6001747581df.png">

Reproduce:
- go to issues
- make your browser screen not higher than 900px (72dpi)
- select as many filters as needed to have a small stack of issues (lower than the filter column)
- expand any of the filter types
- the filters are only visible in a very low DIV with overflow:auto

The filter types should expand fully and make the screen scrollable so they can be easily selected.

This happens in taiga.io

The happens in Chrome 69 & Safari 12 on MacOS

No console errors. This is purely a visual bug.

**Comment by alexhermida** [comment]
@MaartenW we just fixed this in Taiga version 4.1.1. Thank you for your feedback 😄
