### ISSUE TITLE
Stable (Front) as of today not working for me.

### ISSUE THREAD

**Issue by oderwat** [taigaio/taiga-front#1599]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Taiga page stays blank

**If the current behavior is a bug, please provide the steps to reproduce.**
Update frontent to stable (8fa24a2791432fa348d18d9f565c4ab878592580)

**What is the expected behavior?**
Taiga just works :)

**Is it happening in taiga.io or in your own instance?**
My instance

**What browser/version are you using?**
chrome 69.0.3497.100 (but same in Firefox / Safari)

**Are there any console errors *(Ctrl + F12)* in red?**
Yes, see below

```
Uncaught Error: [$injector:unpr] Unknown provider: tgErrorHandlingServiceProvider <- tgErrorHandlingService <- authHttpIntercept <- $http <- $tgModel <- $tgRepo <- $tgProjectsResourcesProvider
http://errors.angularjs.org/1.5.5/$injector/unpr?p0=tgErrorHandlingServiceProvider%20%3C-%20tgErrorHandlingService%20%3C-%20authHttpIntercept%20%3C-%20%24http%20%3C-%20%24tgModel%20%3C-%20%24tgRepo%20%3C-%20%24tgProjectsResourcesProvider
    at libs.js:10
    at libs.js:10
    at Object.r [as get] (libs.js:10)
    at libs.js:10
    at r (libs.js:10)
    at i (libs.js:10)
    at Object.a [as invoke] (libs.js:10)
    at Object.$get (libs.js:10)
    at Object.a [as invoke] (libs.js:10)
    at libs.js:10
```

**Comment by alexhermida** [comment]
@oderwat seems to be a compilation problem. If you are using this repo for taiga-front could you try to compile it again with `npm install && gulp deploy`?

**Comment by oderwat** [comment]
I use `taiga-front-dist` but there are no issues at all, so I reported it here. The change you did some minutes ago made it work again for me.
