### ISSUE TITLE
Github Webhook is wrongly rejected as invalid JSON

### ISSUE THREAD

**Issue by AncientSwordRage** [taigaio/taiga-front#1606]
**Before adding an issue**
_Please ensure that your issue is not already reported in our [issues list](https://tree.taiga.io/project/taiga/issues?order_by=-created_date).
If this issue was already reported, remember that you can upvote it to raise its importance._
Searched for 'webhook'

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Error message is returned when setting up a github webhook
{"_error_message": "The payload is not a valid json", "_error_type": "taiga.base.exceptions.BadRequest"}

**If the current behavior is a bug, please provide the steps to reproduce.**
Steps followed here: **https://tree.taiga.io/support/integrations/github-integration/**

**What is the expected behavior?**
Payload is considered valid

**Is it happening in taiga.io or in your own instance?**
taiga.io

**What browser/version are you using?**
Modern Chrome 

**Are there any console errors *(Ctrl + F12)* in red?**
N/A // Unknown

Payload details below:
https://stackoverflow.com/questions/53015780/invalid-json-returned-by-taiga-webhook-in-github-but-it-seems-valid

Thanks for reporting!

**Comment by eesprit** [comment]
Same problem here with our self-hosted Taiga instance.

**Comment by eesprit** [comment]
As sayed on stackoverflow, I found that in our case, the hook was misconfigured : the content-type was set to form instead of application/json.

**Comment by Guisardo** [comment]
Hi all, this is happening to me now. Tiaga server is responding:
`{"_error_message": "The payload is not valid json", "_error_type": "taiga.base.exceptions.BadRequest"}`
