### ISSUE TITLE
Emoji support breaks Microsoft Sharepoint URLs

### ISSUE THREAD

**Issue by theriverman** [taigaio/taiga-front#1608]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Emoji strings, such as, `:x:` are replaced in linked URLs too.

This is rendered faulty by the frontend:
```
[My linked URL](https://mycompanyurl.sharepoint.com/:x:/r/sites/123456789)
```

If I manually escape the emoji string with a backslash, it works correctly, but this is not user-friendly at any level:
This is rendered correctly after some hacky-hacky:
```
[My linked URL](https://mycompanyurl.sharepoint.com/\:x\:/r/sites/123456789)
```

**If the current behavior is a bug, please provide the steps to reproduce.**
See above.

**What is the expected behavior?**
Don't render URLs with references to emojis.

**Is it happening in taiga.io or in your own instance?**
both

**What browser/version are you using?**
Firefox 63.0 -> issue is browser independent

**Are there any console errors *(Ctrl + F12)* in red?**
nope

**Comment by qwertyllo** [comment]
Subscribing to this issue. We have the exact same problem in our organization.
Thanks.

**Comment by robinz1987** [comment]
We have the same problem in our organization with this issue.
Would be very helpful if you analyze and improve the code here.

**Comment by migonzalvar** [comment]
Merged #1920 but I'm afraid that fix didn't work as expected. We need to look into it further.

**Comment by theriverman** [comment]
What did you experience, @migonzalvar ? Any way I could help to fix it?

**Comment by migonzalvar** [comment]
I can reproduce the bug in current `master`.

When I type on o textarea this text (markdown or HTML mode)

```
https://example.com/:x:/1
```

and save, then I see:

![image](https://user-images.githubusercontent.com/928566/92407773-d6f58300-f13b-11ea-93c0-c87a77f701dc.png)

We need to prevent detecting emoji inside an URL.

---

As a workaround, if I type:

```
https://example.com/\:x\:/1
```

and save, then I see the correct link

![image](https://user-images.githubusercontent.com/928566/92407848-1cb24b80-f13c-11ea-9c3f-2f170a29e419.png)

---

We are trying to solve this issue in taiga-back.

**Comment by theriverman** [comment]
Are you 100% sure you were testing on the right branch?
I've just pulled master, hit `gulp` and I couldn't reproduce the bug anymore now that you've merged my fix.

My just cloned repo's details:
```bash
pi@raspberrypi:~/proj/taiga/taiga-front $ git branch
* master
pi@raspberrypi:~/proj/taiga/taiga-front $ git log --format="%H" -n 1
6e51097473ccc46bc568fdd41bf5350a2ac76298
pi@raspberrypi:~/proj/taiga/taiga-front $ git describe
3.4.0-441-g6e5109747
pi@raspberrypi:~/proj/taiga/taiga-front $
```
I'm testing on Firefox 80.0.1 and Edge 85.0.564.44 (Chromium)


**Here's my render in Firefox:**

![image](https://user-images.githubusercontent.com/22156894/92530261-58c4d980-f22c-11ea-8d40-407e14d9c597.png)

Seemingly it does work just as expected.

**Comment by migonzalvar** [comment]
You are right, my fault. I think we can close this issue.
