### ISSUE TITLE
Unable to watch a wiki page for changes or an entire wiki

### ISSUE THREAD

**Issue by ssbarnea** [taigaio/taiga-front#1611]
At this moment it seems impossible to get notifications about wiki pages being updated, making this feature bareley usable for knowledge dissemination and collaboration.

**Comment by foliovision** [comment]
Great request. It would make sense to add the standard Watcher/Watch interface here (of course without the Assignement and Point sections).

![Taiga-watchers-interface](https://user-images.githubusercontent.com/1180948/65373880-8d3e2f00-dc83-11e9-8189-4196d5f656fa.png)

It's also a frustration that there's **no way to rename **the Wiki page! Workaround is to create new one and copy over but that loses changes and is awkward. There probably shouldn't be a Main Wiki page either: whichever one is dragged to the top should be the hero/first page.
