### ISSUE TITLE
Taiga.io Hangs at "loading"

### ISSUE THREAD

**Issue by Arkano** [taigaio/taiga-front#1616]
**Do you want to request a *feature* or report a *bug*?**
I think this is a bug.
**What is the current behavior?**
Taiga.io hangs on load.
**If the current behavior is a bug, please provide the steps to reproduce.**
Try to purchase the Premium plan, then a "loading" message overlay appears and gets stuck there forever. the Safari browser error console shows this error:
"Error: null is not an object (evaluating 'this.myPlan.current_plan.amount_month')"
**What is the expected behavior?**
The loading message goes away and progresses to whatever lies after it.
**Is it happening in taiga.io or in your own instance?**
In Taiga.io.
**What browser/version are you using?**
Safari 10.0.3 or Chrome 70.0.3538.102, happens in both.
**Are there any console errors *(Ctrl + F12)* in red?**
"Error: null is not an object (evaluating 'this.myPlan.current_plan.amount_month')"

**Comment by alexhermida** [comment]
@Arkano probably it's because of a temporary problem connecting with 3rd party services. Anyway, Taiga.io service issues it's better to let it know throughout support email. Thank you!
