### ISSUE TITLE
Feature Request: Drop-Down Combo Custom Fields

### ISSUE THREAD

**Issue by jfuller-ezenics** [taigaio/taiga-front#1622]
Our company relies on the custom fields for attributing timecard and other categorical information to tickets. Re-entering values manually for each and every ticket means that it's difficult for everyone to remember all of the possible options and greatly increases the likelihood of spelling errors and incorrectly entered information.

Please add drop-down combo selectors as custom field types. It would be greatly appreciated. Thank you!

**Comment by alexhermida** [comment]
@jfuller-ezenics I suppose you are suggesting the same as https://tree.taiga.io/project/taiga/issue/3725
 It's included in the next Taiga release and It's already in the [4.0rc](https://github.com/taigaio/taiga-front/tree/4.0rc) branch and will be available in a few days. Thanks!
