### ISSUE TITLE
Feature Request: Configurable Columns for Backlog Table

### ISSUE THREAD

**Issue by jfuller-ezenics** [taigaio/taiga-front#1623]
Our team relies heavily on several fields that are not displayed in the Backlog table, meaning that we have to export from Taiga, prioritize tickets offline, and then go bak to make changes on Taiga. This is a cumbersome process and the filters only partially help.

Please make the Backlog table's columns configurable so that we can choose which columns to show and prioritize by. It could be done in a config file or via the UI, whichever is easiest and fastest. Thank you!

**Comment by smidt** [comment]
+1
We would also be very happy about the feature.

**Comment by ngulden** [comment]
I give another +1 in a comment, because reactions are not synced to the taigo project page here: 
https://tree.taiga.io/project/taiga/issue/5610

**Comment by stygmate** [comment]
+1
