### ISSUE TITLE
Can't embed attached images in wiki

### ISSUE THREAD

**Issue by ThenIAwoke** [taigaio/taiga-front#1627]
Hi,

I open a new wiki page. 

I upload an svg image called circle1.svg as an attachment.

I try to embed it in the article.

`![alt text](circle1.svg "Title") `
does not work.

`![alt text][id]`
`[id]: /static/images/circle1.svg "Title"`
does not work.

From: https://tree.taiga.io/support/misc/taiga-markdown-syntax/#images

also this doesn't work:

`[[img src=circle1.svg alt=foobar]]`

From: https://sourceforge.net/p/taigaio/wiki/markdown_syntax/#md_ex_img

The only thing working is getting the public image url (Something like https://media-protected.taiga.io/attachments/...) containing a token, which is probably/hopefully not valid forever and doing this: 

`![tiny arrow](https://media-protected.taiga.io/attachments/... "tiny arrow")`

Is there no other way to embed attached images?

**Comment by cadjou** [comment]
Hello, I have the same question. ;)
For the moment, i use ![](/media/attachments/...so long token....... "Image")

**Comment by koromkorom** [comment]
> 
> 
> Hello, I have the same question. ;)
> For the moment, i use ![](/media/attachments/...so long token....... "Image")

The token is only valid for a few days.... so we would have to change the URLs every now and then, which seems not practical.

**Comment by DanMMX** [comment]
Any news on this ?

**Comment by ThenIAwoke** [comment]
Not that I know of ... 
There are 290 open issues and I don't imagine the taiga team to be that big. 
The only thing we can do is seeking attention, by using the thumbs up reaction on the bottom left of the original post.

**Comment by foliovision** [comment]
Thanks for the tip about the expiring token. Images uploaded and shown internally should not expire.
