### ISSUE TITLE
Order Backlog 502 Bad Gad Gateway on Estimation

### ISSUE THREAD

**Issue by Sirhexalot** [taigaio/taiga-front#1664]
When we order the Backlog US and then try to estamate a User Story we always get a 502 Bad Gateway

**Comment by alexhermida** [comment]
@Sirhexalot currently there are no reported bugs regarding this. Could you detail it more? If it's a custom instance configuration issue you can ask for advice on the mailing list https://groups.google.com/d/forum/taigaio.
