### ISSUE TITLE
Autocomplete tags with relevant order

### ISSUE THREAD

**Issue by 4n70w4** [taigaio/taiga-front#1677]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

Not user friendly autocomplete order for tags. Example i type ma. Autocomplete suggest me auto**ma**tion and **ma**rketing.

![image](https://user-images.githubusercontent.com/38257723/50378673-cbe97f00-0648-11e9-9d70-4b448a59ccc4.png)

**What is the expected behavior?**

marketing tag in current case most relevanted because ma is first letters of word.

**Is it happening in taiga.io or in your own instance?**

My own instance

**What browser/version are you using?**

Chrome latest.

**Comment by diacritica** [comment]
Also, tag popularity could be used as a tiebreaker or even as a relevant weight
