### ISSUE TITLE
Opportunity to change project home page from timeline to another page

### ISSUE THREAD

**Issue by 4n70w4** [taigaio/taiga-front#1678]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

Currently on open project user see timeline page.

**What is the expected behavior?**

I want open backlog page (or another page, setted in settings) by click on project title.

**Is it happening in taiga.io or in your own instance?**

My own instance.

**Comment by alexhermida** [comment]
@4n70w4 since las 4.0 release you can customize your project home section. Check https://blog.taiga.io/taiga-larix-cajanderi-release-400.html
