### ISSUE TITLE
opportunity to filter US / tasks for "due date"

### ISSUE THREAD

**Issue by fabianfritz1994** [taigaio/taiga-front#1679]
**Before adding an issue**
Please ensure that your issue is not already reported in our [issues list](https://tree.taiga.io/project/taiga/issues?order_by=-created_date).
If this issue was already reported, remember that you can upvote it to raise its importance.

**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
No opportunity to filter US / tasks for "due date"
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
opportunity to filter for due date states "past due, soon due,..."
**Is it happening in taiga.io or in your own instance?**
own instance

Thanks for reporting!

**Comment by Amasit** [comment]
+1. I could very much use this useful feature.
