### ISSUE TITLE
subscription api

### ISSUE THREAD

**Issue by rmros** [taigaio/taiga-front#1681]
Hi
I want use subscripe module
I saw subscription frontend inside taiga repositories
But I can't find backend api subscription

I need that,

Best regard

**Comment by alexhermida** [comment]
@rmros please check https://github.com/taigaio/taiga-contrib-subscriptions/

**Comment by rmros** [comment]
@alexhermida  there is no any thing subscription backend in https://github.com/taigaio/taiga-contrib-subscriptions/
