### ISSUE TITLE
Date selector displayed outside the screen when creating new US

### ISSUE THREAD

**Issue by PeaceRebel** [taigaio/taiga-front#1689]
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
Part the date selector for adding due date when creating a new US is displayed outside the screen
**If the current behavior is a bug, please provide the steps to reproduce.**
Create a new US and add new due date
**What is the expected behavior?**
Date selector should we within the screen
**Is it happening in taiga.io or in your own instance?**
https://board.disroot.org instance
**What browser/version are you using?**
Google Chrome v70.0.3538.110 on MacBook Pro 15" and Chromium v72.0.3626.7 on debian/sid 15.6"
**Are there any console errors *(Ctrl + F12)* in red?**
NO
<img width="1280" alt="screen shot 2019-01-11 at 5 15 55 pm" src="https://user-images.githubusercontent.com/22352237/51121283-1374bc80-183d-11e9-8743-32576067292e.png">

**Comment by alexhermida** [comment]
@PeaceRebel thanks for your feedback. We just fixed this in Taiga 4.1.1 release.
