### ISSUE TITLE
Gitlab integration messages shows up multiple times if commit was merged and then pushed with merge

### ISSUE THREAD

**Issue by szucior** [taigaio/taiga-front#1691]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Duplicated mentioned comments from gitlab.
If commit had #ready-for-test tag but issue was already closed, then it will be changed to ready-for-test again. (happend for us)
There could be worse problem where rejected could be changed back to closed.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Create commit with TG-XXX mention
2. Push it to branch X on gitlab driven repo with enabled taiga intergration via webhook
3. Merge branch X into another branch
4. Push merge commit
5. Mention comment shows up again.

**What is the expected behavior?**
Comments shows only one time for one commit.

**Is it happening in taiga.io or in your own instance?**
Own Instance

**What browser/version are you using?**
Taiga 4.0
GitLab 11.6.3-ee (76c33c6)
Chrome  71.0.3578.98  Official x64

**Are there any console errors *(Ctrl + F12)* in red?**
No

**Comment by Gim6626** [comment]
Submitted feature request https://github.com/taigaio/taiga-back/issues/1385. It may fix this.
