### ISSUE TITLE
wrong date format after migrating to Taiga 4

### ISSUE THREAD

**Issue by tcharlss** [taigaio/taiga-front#1693]
Hi,

We use our own instance of Taiga.
After migrating from v3.x to v4, following exactly the documentation, the dates are displayed like this on  issues, user stories, etc. :
```
JJ janv. AMAMAMAM 11:00
```

Our interface is set in french.
Maybe it's related to issue #805 ?

**Comment by alexhermida** [comment]
@tcharlss you are right. We fixed it and updated the string some days ago in transifex. We will update stable version in next release. Thank you!

**Comment by tcharlss** [comment]
Great, thanks a lot!
