### ISSUE TITLE
User Story Mapping Module

### ISSUE THREAD

**Issue by ddamasceno** [taigaio/taiga-front#1703]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Our team is working on complex projects and we are having trouble keeping a "big picture" of the project from a *priority* (release) and an *activity* (epic/story) points of view.
Sprints and Epics Modules are not sufficient to get an larger understanding on what is going on and how it will go ahead.

**What is the expected behavior?**
Having a new "User Story Map" module would help us keeping control on bigger picture on both release and UX timelines : 

| Epics(=activities) | Epic 1 | Epic 2 | Epic 3 |
|------|-------|-------|-------|
| Release 1 | US 1 : US 2 | US 5 : US6 | US 9 |
|        (continued)          | US 3            | US 12         |           |
| Release 2 | US 11  | US 4 : US 7 | US 10 |

References :  
> Story mapping consists of ordering user stories along two independent dimensions. The "map" arranges user activities along the horizontal axis in rough order of priority (or "the order in which you would describe activities to explain the behaviour of the system"). Down the vertical axis, it represents increasing sophistication of the implementation. ( https://www.agilealliance.org/glossary/storymap )

> User Story Mapping is a dead simple idea. Talk about the user’s journey through your product by building a simple model that tells your user’s story as you do. It turns out this simple idea makes working with user stories in agile development a lot easier. (https://www.jpattonassociates.com/user-story-mapping

Does that makes sense to any other users ? Any better suggestions of solutions ?

**Comment by rupeshk** [comment]
User story maps are valuable for large projects. It seems a Kanban view of the [current Epics list ](![image](https://user-images.githubusercontent.com/512407/119226679-fe547a80-bb27-11eb-9aa3-63a4f6ef8116.png)) with swimlanes from chosen tags could create a story map.
