### ISSUE TITLE
responsive design *feature*

### ISSUE THREAD

**Issue by TheGamin93** [taigaio/taiga-front#1716]
Hello, I use a taiga at home with my family and we **love the application**.

The problem is that we use the application from a mobile browser (because the App that is not official is very expensive and is not intuitive at all) and we have problems managing the cards from the mobile version.

I would like to request if you can adjust the design to be responsive and compatible with mobile devices.

Thank you.

**Comment by christianlupus** [comment]
I would see much use in this as well.

**Comment by Sandvich** [comment]
I'm seeing demand for this from within my organisation too - TaigaApp is unfortunately too limited.

**Comment by stylergergely** [comment]
Yeah, let me chip in. This would be a huge productivity boost for us too.

**Comment by c64bob** [comment]
This would be awesome!
