### ISSUE TITLE
Remove ruby dependency by using LibSass?

### ISSUE THREAD

**Issue by stevenhaddox** [taigaio/taiga-front#172]
It looks like your documentation suggests installing Ruby just to get the sass gem. Perhaps consider implementing a port of [LibSass](http://libsass.org/) for a language you already require rather than installing another dependency just to compile some CSS files?

I'm hoping one of these will make it an easier install for everyone:
[Python](https://pypi.python.org/pypi/libsass/0.5.1)
[Grunt](https://www.npmjs.org/package/grunt-libsass)
[Node](https://www.npmjs.org/package/node-sass)

Sorry I don't know the exact one to recommend. I haven't had a chance to walk through this fully yet. I just know that Ruby is overkill just for sass compiling >.<

**Comment by Zorlin** [comment]
The Ruby dependency is a PITA for sysadmins. I can live with it, but FWIW.

**Comment by superalex** [comment]
@Zorlin we are currently working on it, the idea is that Taiga also includes the front compiled, this way if you are doing a standard installation you won't have so many dependencies (only if you need to rebuild the front).

**Comment by Zorlin** [comment]
Ah, nice.

Sorry, I am still getting my installation automated (Debian 7) with Ansible
and haven't gotten it finished yet.

**Comment by Xaviju** [comment]
We just moved to libSass, is currently under testing and will be released soon.
The bad thing about this is that it is not at the same sass version as rub- sass and some Sass features are not yet implemented.
