### ISSUE TITLE
Way to get the randomly generated animal picture for each user

### ISSUE THREAD

**Issue by annabeenana11** [taigaio/taiga-front#1721]
**Before adding an issue**
Please ensure that your issue is not already reported in our [issues list](https://tree.taiga.io/project/taiga/issues?order_by=-created_date).
If this issue was already reported, remember that you can upvote it to raise its importance.

**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Unless I am missing something, I see no way to get the random animal avatar that was generated for a user that hasn't set their user picture.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
It would be nice if it was in the user table in the database.
**Is it happening in taiga.io or in your own instance?**

**What browser/version are you using?**

**Are there any console errors *(Ctrl + F12)* in red?**

Thanks for reporting!

**Comment by Zelphy** [comment]
Images are located here:
```
ls -l ./taiga-front-dist/dist/images/user-avatars/user-avatar-0*
-rw-rw-r-- 1 taiga taiga 1088 Feb  5  2019 ./taiga-front-dist/dist/images/user-avatars/user-avatar-01.png
-rw-rw-r-- 1 taiga taiga 1005 Feb  5  2019 ./taiga-front-dist/dist/images/user-avatars/user-avatar-02.png
-rw-rw-r-- 1 taiga taiga 1335 Feb  5  2019 ./taiga-front-dist/dist/images/user-avatars/user-avatar-03.png
-rw-rw-r-- 1 taiga taiga 1170 Feb  5  2019 ./taiga-front-dist/dist/images/user-avatars/user-avatar-04.png
-rw-rw-r-- 1 taiga taiga 1093 Feb  5  2019 ./taiga-front-dist/dist/images/user-avatars/user-avatar-05.png
```

I'm not sure to understand this issue, what are you trying to achieve?
