### ISSUE TITLE
taiga-events not running

### ISSUE THREAD

**Issue by tocloco** [taigaio/taiga-front#1723]
**Before adding an issue**
Please ensure that your issue is not already reported in our [issues list](https://tree.taiga.io/project/taiga/issues?order_by=-created_date).
If this issue was already reported, remember that you can upvote it to raise its importance.

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
Kanban events not updating the front end.
Logged in to Taiga and using the Kanban screen as different users in different browsers. Changes made to a story in one browser - such as changing the assigned user or changing the status are not being updated in the second browser.

I see some errors related to taiga-events when I run systemctl status 'taiga*':

md[1]: Started taiga_events.
Mar 09 07:53:22 mobility bash[1469]: Unhandled rejection Error: connect ECONNREFUSED 127.0.0.1:5672
Mar 09 07:53:22 mobility bash[1469]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
Mar 09 07:53:22 mobility bash[1469]: Unhandled rejection Error: connect ECONNREFUSED 127.0.0.1:5672
Mar 09 07:53:22 mobility bash[1469]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
Mar 09 07:53:25 mobility bash[1469]: Unhandled rejection Error: connect ECONNREFUSED 127.0.0.1:5672
Mar 09 07:53:25 mobility bash[1469]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
Mar 09 07:53:37 mobility bash[1469]: Unhandled rejection Error: read ECONNRESET
Mar 09 07:53:37 mobility bash[1469]:     at TCP.onread (net.js:622:25)

● taiga.service - taiga_back
   Loaded: loaded (/etc/systemd/system/taiga.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2019-03-09 07:53:17 UTC; 41s ago
 Main PID: 1353 (gunicorn)
    Tasks: 5
   Memory: 270.1M
      CPU: 9.897s
   CGroup: /system.slice/taiga.service
           ├─1353 /home/taiga/.virtualenvs/taiga/bin/python3 /home/taiga/.virtualenvs/taiga/bin/gunicorn --workers 4 --timeout 60 -b 127.0.0.1:8001 taiga.wsgi
           ├─1727 /home/taiga/.virtualenvs/taiga/bin/python3 /home/taiga/.virtualenvs/taiga/bin/gunicorn --workers 4 --timeout 60 -b 127.0.0.1:8001 taiga.wsgi
           ├─1728 /home/taiga/.virtualenvs/taiga/bin/python3 /home/taiga/.virtualenvs/taiga/bin/gunicorn --workers 4 --timeout 60 -b 127.0.0.1:8001 taiga.wsgi
           ├─1729 /home/taiga/.virtualenvs/taiga/bin/python3 /home/taiga/.virtualenvs/taiga/bin/gunicorn --workers 4 --timeout 60 -b 127.0.0.1:8001 taiga.wsgi
           └─1732 /home/taiga/.virtualenvs/taiga/bin/python3 /home/taiga/.virtualenvs/taiga/bin/gunicorn --workers 4 --timeout 60 -b 127.0.0.1:8001 taiga.wsgi

Mar 09 07:53:19 mobility gunicorn[1353]: [2019-03-09 07:53:19 +0000] [1353] [INFO] Listening at: http://127.0.0.1:8001 (1353)
Mar 09 07:53:19 mobility gunicorn[1353]: [2019-03-09 07:53:19 +0000] [1353] [INFO] Using worker: sync
Mar 09 07:53:19 mobility gunicorn[1353]: [2019-03-09 07:53:19 +0000] [1727] [INFO] Booting worker with pid: 1727
Mar 09 07:53:19 mobility gunicorn[1353]: [2019-03-09 07:53:19 +0000] [1728] [INFO] Booting worker with pid: 1728
Mar 09 07:53:19 mobility gunicorn[1353]: [2019-03-09 07:53:19 +0000] [1729] [INFO] Booting worker with pid: 1729
Mar 09 07:53:19 mobility gunicorn[1353]: [2019-03-09 07:53:19 +0000] [1732] [INFO] Booting worker with pid: 1732
Mar 09 07:53:20 mobility gunicorn[1353]: Trying import local.py settings...
Mar 09 07:53:21 mobility gunicorn[1353]: Trying import local.py settings...
Mar 09 07:53:21 mobility gunicorn[1353]: Trying import local.py settings...
Mar 09 07:53:23 mobility gunicorn[1353]: Trying import local.py settings...

● taiga_celery.service - taiga_celery
   Loaded: loaded (/etc/systemd/system/taiga_celery.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2019-03-09 07:53:17 UTC; 41s ago
 Main PID: 1467 (celery)
    Tasks: 5
   Memory: 238.6M
      CPU: 4.737s
   CGroup: /system.slice/taiga_celery.service
           ├─1467 /home/taiga/.virtualenvs/taiga/bin/python3 /home/taiga/.virtualenvs/taiga/bin/celery -A taiga worker --concurrency 4 -l INFO
           ├─2016 /home/taiga/.virtualenvs/taiga/bin/python3 /home/taiga/.virtualenvs/taiga/bin/celery -A taiga worker --concurrency 4 -l INFO
           ├─2026 /home/taiga/.virtualenvs/taiga/bin/python3 /home/taiga/.virtualenvs/taiga/bin/celery -A taiga worker --concurrency 4 -l INFO
           ├─2030 /home/taiga/.virtualenvs/taiga/bin/python3 /home/taiga/.virtualenvs/taiga/bin/celery -A taiga worker --concurrency 4 -l INFO
           └─2048 /home/taiga/.virtualenvs/taiga/bin/python3 /home/taiga/.virtualenvs/taiga/bin/celery -A taiga worker --concurrency 4 -l INFO

Mar 09 07:53:27 mobility celery[1467]:   . taiga.webhooks.tasks.change_webhook
Mar 09 07:53:27 mobility celery[1467]:   . taiga.webhooks.tasks.create_webhook
Mar 09 07:53:27 mobility celery[1467]:   . taiga.webhooks.tasks.delete_webhook
Mar 09 07:53:27 mobility celery[1467]:   . taiga.webhooks.tasks.resend_webhook
Mar 09 07:53:27 mobility celery[1467]:   . taiga.webhooks.tasks.test_webhook
Mar 09 07:53:29 mobility celery[1467]: [2019-03-09 07:53:29,038: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
Mar 09 07:53:29 mobility celery[1467]: [2019-03-09 07:53:29,054: INFO/MainProcess] mingle: searching for neighbors
Mar 09 07:53:30 mobility celery[1467]: [2019-03-09 07:53:30,078: INFO/MainProcess] mingle: all alone
Mar 09 07:53:36 mobility celery[1467]: [2019-03-09 07:53:36,805: INFO/MainProcess] Received task: taiga.timeline.service.push_to_timelines[dfa0b394-dcfd-4807-8bf2-47c7d519e973]
Mar 09 07:53:36 mobility celery[1467]: [2019-03-09 07:53:36,809: INFO/MainProcess] Received task: taiga.webhooks.tasks.change_webhook[24a98ead-6bea-4f56-bd97-dda0dadd0183]
```


**What is the expected behavior?**
The second browser should update to reflect the story status.

**Is it happening in taiga.io or in your own instance?**
Own instance

**What browser/version are you using?**
Chrome 72.0.3626.121 & Safari 12.1 on Mac OS

**Are there any console errors *(Ctrl + F12)* in red?**
TypeError: Cannot read property '0' of null
    at a (inject.bundle.js:1)
    at t.r.isButtonDisabled (inject.bundle.js:1)
    at t.r.getButtonStyles (inject.bundle.js:1)
    at t.r.renderNavigation (inject.bundle.js:1)
    at t.value (inject.bundle.js:1)
    at Cn (inject.bundle.js:1)
    at Nn (inject.bundle.js:1)
    at Kn (inject.bundle.js:1)
    at Yn (inject.bundle.js:1)
    at fr (inject.bundle.js:1)

**Comment by tocloco** [comment]
Doing some more digging into the "Unhandled rejection Error: read ECONNRESET" error....

I installed rabbitmq_management and used it to verify the taiga credentials and they work as configured.

**Comment by alexhermida** [comment]
@tocloco The issue, as you said, is related to the connection to RabbitMQ. Make sure that RabbitMQ is listening in the IP address 127.0.0.1 and port 5672. With the command `rabbitmqctl status` check the configuration looking for "listeners" key and "amqp" value.
