### ISSUE TITLE
taskboard view doesn't load until refresh

### ISSUE THREAD

**Issue by adrigen** [taigaio/taiga-front#173]
![blank](https://cloud.githubusercontent.com/assets/1256365/5176041/2cc155b6-7497-11e4-9b1f-9aa8ebac3fc3.png)

Clicking on the taskboard only shows the headers until the page is refreshed. Firefox 30, Ubuntu.

**Comment by superalex** [comment]
@adrigen could you check if is this still happening?

**Comment by adrigen** [comment]
All sorted :)

**Comment by superalex** [comment]
ok! :+1:
