### ISSUE TITLE
After Latest Update, Tasks on Task Board Show as "New" and "Not Estimated", Which is Wrong

### ISSUE THREAD

**Issue by souch3** [taigaio/taiga-front#1730]
Also created https://tree.taiga.io/project/taiga/issue/5703

**Do you want to request a *feature* or report a *bug*?**
Report a bug
**What is the current behavior?**
Looking at tasks on the task board show their status as New and Not Estimated when they all have user points and some are already closed

**If the current behavior is a bug, please provide the steps to reproduce.**
Look at task board

**What is the expected behavior?**
Proper state and points are shown

**Is it happening in taiga.io or in your own instance?**
taiga.io

**What browser/version are you using?**
Safari 12.0.3
**Are there any console errors *(Ctrl + F12)* in red?**
Yep!
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (91c8fff1a28e809b53b350bd892ff2e60f8085f6, line 0) 

Trying to get 
https://api.taiga.io/api/v1/user-storage/91c8fff1a28e809b53b350bd892ff2e60f8085f6

<img width="310" alt="Screen Shot 2019-03-20 at Mar 20 6 05 33 PM" src="https://user-images.githubusercontent.com/4501695/54728520-8cdda380-4b3b-11e9-81fa-cc319ce9cb30.png">
<img width="1518" alt="Screen Shot 2019-03-20 at Mar 20 6 05 40 PM" src="https://user-images.githubusercontent.com/4501695/54728521-8cdda380-4b3b-11e9-9951-3ffcb5145f05.png">

**Comment by alexhermida** [comment]
@souch3 thank you for your feedback. It's because a bug introduced in taiga-back 4.2.1. It was a temporary revert in 4.2.2. Currently must be working without issues.
