### ISSUE TITLE
No loading of remaining epics in filtered epic view when scolling is not possible (Firefox)

### ISSUE THREAD

**Issue by wf-r** [taigaio/taiga-front#1733]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

We have ~48 epics, many of which are closed. When opening the epic view, only some of these are loaded. When scrolling down, the remaining are loaded. This behaviour is expected.

If one reloads the epic view such that only the initial batch of epics is loaded and displayed, and then applies the filter to hide closed epics, only open epics within the first loaded batch are displayed. The remaining open epics are never loaded (scrolling down is not possible, as the open epics are easily shown within the page).

The same happens if one applies the filter to hide open epics, and then reloads the epics page.

The same behaviour can be reproduced in the backlog, if, e.g., the browser window is moved to a different screen with higher resolution so that all user stories are (due to different resolution) shown on one page with scrolling disabled, or if you change the zoom level of the browser.

**If the current behavior is a bug, please provide the steps to reproduce.**

see above

**What is the expected behavior?**

When applying a filter that reduces the amount of displayed entities, you should check whether there remain some to be loaded and displayed.

When I change the browser size so that all currently loaded entities fit on one page, loading of further entities should be triggered (or: if I do a scroll/page down on a list that fits in the window, loading of further items should happen).

**Is it happening in taiga.io or in your own instance?**

Both

**What browser/version are you using?**

Firefox 66.0.2 (64-Bit)

It does work on Edge for the epic view, where a scroll down event can be triggered.

**Are there any console errors *(Ctrl + F12)* in red?**

No

Thanks for reporting!

**Comment by eesprit** [comment]
Having the same problem with Firefox (68.3.0esr) and Chrome (79.0.3945.79) and Chromium (78.0.3904.108) and even with Edge 44.18362.449.0.
All my co-workers have the same problem (using differents kinds of browser)
We are on the stable branch for taiga-front-dist and taiga-back (updated today, not sure how to find out the exact release number tough...).

The only fix is to allow to display closed epics, scroll from top to bottom until last epics, and then filtering out closed epics.
But having to do this every time we come on the eipcs dashboard is a time killer action :(
