### ISSUE TITLE
Request: "create and another" option on new story/issue dialogs

### ISSUE THREAD

**Issue by lullis** [taigaio/taiga-front#1735]
**Do you want to request a *feature* or report a *bug*?**
Request

**What is the current behavior?**
The "New User Story"/"New Issue" dialogs contain a series of different options and a button to submit the data. After the user presses "create", the user is redirect to the screen showing the list of backlog/issues

**What is the expected behavior?**
It would be nice to have another button with the option to "Create and add another", which would **not** leave the form, only clear the title field in the form. This would be a huge usability improvement for everyone who is adding a series of stories and issues, and would not depend on any changes on the API.

**Comment by diacritica** [comment]
Proposed UX UI from Taiga's core team

![5712_create_and_add_new_3](https://user-images.githubusercontent.com/1606348/66582075-7b182800-eb81-11e9-9f89-5f33b7e05dab.png)
![5712_create_and_add_new_2](https://user-images.githubusercontent.com/1606348/66582076-7b182800-eb81-11e9-8f9f-3d462661fe05.png)
![5712_create_and_add_new_4](https://user-images.githubusercontent.com/1606348/66582078-7bb0be80-eb81-11e9-9b24-1bcc22c91a67.png)
![5712_create_and_add_new_1](https://user-images.githubusercontent.com/1606348/66582079-7bb0be80-eb81-11e9-9432-c22d109d71f6.png)

**Comment by jespino** [comment]
I would like to pick this one

**Comment by diacritica** [comment]
All yours! :)
