### ISSUE TITLE
Your Interpolation is Showing {{ SECTION_NAME | TRANSLATE }}

### ISSUE THREAD

**Issue by JTorr** [taigaio/taiga-front#1738]
**Before adding an issue**
Please ensure that your issue is not already reported in our [issues list](https://tree.taiga.io/project/taiga/issues?order_by=-created_date).
If this issue was already reported, remember that you can upvote it to raise its importance.

**Do you want to request a *feature* or report a *bug*?**
*bug*
**What is the current behavior?**

Jade syntax is showing on production site at the following url:
https://tree.taiga.io/project/chicknator-w8-loss/backlog

**If the current behavior is a bug, please provide the steps to reproduce.**
Logged in and was redirected to backlog. 404 from the user storage API.
Was logging in from a new computer, so could be a cacheing issue?

**What is the expected behavior?**
Translated text would appear
**Is it happening in taiga.io or in your own instance?**
taiga.io
**What browser/version are you using?**
Chrome latest
**Are there any console errors *(Ctrl + F12)* in red?**
Yes, attached
Thanks for reporting!
![image](https://user-images.githubusercontent.com/7951702/56328723-e38fca80-6145-11e9-94d6-cd55a09564df.png)
![image](https://user-images.githubusercontent.com/7951702/56328877-92340b00-6146-11e9-87e7-d185ac4fc188.png)
![image](https://user-images.githubusercontent.com/7951702/56328892-a24bea80-6146-11e9-8cd6-270a0b7c0311.png)
![image](https://user-images.githubusercontent.com/7951702/56328911-c14a7c80-6146-11e9-879b-f17780ce8c5f.png)

**Comment by alexhermida** [comment]
@JTorr the 404 from user-storage it's normal behavior if you don't have any filters. 
But seems you have some other errors related to the API connection. Since I can access without issue to that public project, as you said could be a cache issue with your browser. Try to reset it.
The lang interpolation it's failing due to the page isn't loading correctly.
