### ISSUE TITLE
Filters that exclude an Epic do nothing in Kanban View

### ISSUE THREAD

**Issue by gmalmquist** [taigaio/taiga-front#1740]
**Do you want to request a *feature* or report a *bug*?**
*Bug*

**What is the current behavior?**
In the Kanban view, creating a filter with an Epic excluded, doesn't actually exclude stories in that epic.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Create a few stories.
2. Assign some of them to an Epic.
3. Attempt to filter out the epic in the Kanban view, by going to Advanced > Exclude, then selecting the Epic.

**What is the expected behavior?**
Stories with the excluded epic don't show up in the filtered view.

**Is it happening in taiga.io or in your own instance?**
taiga.io

**What browser/version are you using?**
```
Google Chrome | 73.0.3683.75 (Official Build) (64-bit) (cohort: 73_75_Win)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17763.379
JavaScript | V8 7.3.492.22
Flash | 32.0.0.171 C:\Users\Garrett\AppData\Local\Google\Chrome\User Data\PepperFlash\32.0.0.171\pepflashplayer.dll
```

**Are there any console errors *(Ctrl + F12)* in red?**
```
GET https://api.taiga.io/api/v1/user-storage/a83e8ad0896bd1aae15814f073c2fbc1965ba97a 404 (Not Found)
```
Thanks for reporting!

**Comment by alexhermida** [comment]
@gmalmquist the bug is fixed with the last [4.2.5)(https://github.com/taigaio/taiga-back/releases/tag/4.2.5) release. Thanks!
