### ISSUE TITLE
Changes made on Kanban Board get overwritten when not refreshed

### ISSUE THREAD

**Issue by kathaneu** [taigaio/taiga-front#1742]
**Before adding an issue**
Please ensure that your issue is not already reported in our [issues list](https://tree.taiga.io/project/taiga/issues?order_by=-created_date).
If this issue was already reported, remember that you can upvote it to raise its importance.

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
When I make some priority changes on the Kanban Board, drag and drop User Stories inside a row, the changes get overwritten, if another user makes changes in the meanwhile and I forgot to refresh.  So the events regardign changes on the Kanban Board are submitted on load/refresh?

**If the current behavior is a bug, please provide the steps to reproduce.**
Make a priority change on the Kanban Board without browser refresh. Then another user makes a change on the Kanban Board.  then do a refresh and the first changes are lost.

**What is the expected behavior?**

**Is it happening in taiga.io or in your own instance?**
It is happening on my own instance

**What browser/version are you using?**
Chrome / Firefox

**Are there any console errors *(Ctrl + F12)* in red?**

Thanks for reporting!

**Comment by alexhermida** [comment]
@kathaneu, since Taiga has an *Optimistic concurrency control* any of you, should get an error message when you try to save the US (https://taigaio.github.io/taiga-doc/dist/api.html#_occ_optimistic_concurrency_control).
