### ISSUE TITLE
Missing tag colors in sprint US list

### ISSUE THREAD

**Issue by hormiai76** [taigaio/taiga-front#1744]
**Before adding an issue**
Please ensure that your issue is not already reported in our [issues list](https://tree.taiga.io/project/taiga/issues?order_by=-created_date).
If this issue was already reported, remember that you can upvote it to raise its importance.

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Is it happening in taiga.io or in your own instance?**

**What browser/version are you using?**

**Are there any console errors *(Ctrl + F12)* in red?**

Thanks for reporting!

**Comment by hormiai76** [comment]
Hi,
I just installed the version 4.2 and a user said to me that tag colors are missing in the sprint US list.
I'm not sure they were there before but he said to me that it could be useful.
The user's project use EPIC but even with a normal User Story the color is not shown in the Sprint list
Regards,
Alberto Nardella

**Comment by alexhermida** [comment]
@hormiai76 what do you mean with "sprint US list"? The TaskBoard? If you give us more detailed information about the issue, we can investigate it. Thank you!

**Comment by hormiai76** [comment]
@alexhermida 
Sprint US (user stories) list is the right sidebar with the current sprint.  In the image you have in the taiga.io web page (https://taiga.io/img/scrum-screen.6640bfbd.jpg) you see that the tagged user stories have one or more colored circles. Did you removed this feature?
My current updated taiga installation doesn't show the circles for the tagged user stories in the Sprint user stories list
Regards,
Alberto

**Comment by alexhermida** [comment]
It is fixed in master and stable branch. Thank you @hormiai76 !
