### ISSUE TITLE
CSV Report Error 500

### ISSUE THREAD

**Issue by igorsop** [taigaio/taiga-front#1747]
https://api.taiga.io/api/v1/issues/csv?uuid=29e1dfb1f7ce4bab975ac9ace23eec1b

This report returns 500 error. (There is about 700 issues listed on this report)
![error](https://user-images.githubusercontent.com/18582282/57297729-c72ce100-70a6-11e9-9b93-ebaa5bc7d41f.PNG)

**Comment by alexhermida** [comment]
@igorsop issues regarding the tree.taiga.io instance you have to contact through support@taiga.io contact email 😄
