### ISSUE TITLE
conf.json doesn't seem to be read

### ISSUE THREAD

**Issue by Sandvich** [taigaio/taiga-front#1752]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
The API seems to behave as expected, but the taiga frontend isn't connecting to the backend. Since registration is also showing as enabled despite the fact that I disabled it, I'm concluding that the conf.json file isn't being read.

**If the current behavior is a bug, please provide the steps to reproduce.**
Fresh install of Taiga in a docker container (all components inside said container). conf.json is as below:
```js
{
    "api": "http://127.0.0.1:8000/api/v1/",
    "eventsUrl": null,
    "eventsMaxMissedHeartbeats": 5,
    "eventsHeartbeatIntervalTime": 60000,
    "eventsReconnectTryInterval": 10000,
    "debug": false,
    "debugInfo": false,
    "defaultLanguage": "en",
    "themes": ["taiga"],
    "defaultTheme": "taiga",
    "publicRegisterEnabled": false,
    "feedbackEnabled": true,
    "supportUrl": "https://tree.taiga.io/support",
    "privacyPolicyUrl": null,
    "termsOfServiceUrl": null,
    "GDPRUrl": null,
    "maxUploadFileSize": null,
    "contribPlugins": [],
    "tribeHost": null,
    "importers": [],
    "gravatar": true,
    "rtlLanguages": ["fa"]
}
```

In case it's relevant, taiga.conf (for nginx) is:
```
server {
	listen 8001 default_server;
	server_name _;

	large_client_header_buffers 4 32k;
	client_max_body_size 50M;
	charset utf-8;

	access_log /home/taiga/logs/nginx.access.log;
	error_log /home/taiga/logs/nginx.error.log;

	# Frontend
	location / {
		root /home/taiga/taiga-front-dist/dist/;
		try_files $uri $uri/ /index.html;
	}

	# Backend
	location /api {
		proxy_set_header Host $http_host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Scheme $scheme;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_pass http://127.0.0.1:8000/api;
		proxy_redirect off;
	}

	# Admin access (/admin/)
	location /admin {
		proxy_set_header Host $http_host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Scheme $scheme;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_pass http://127.0.0.1:8001$request_uri;
		proxy_redirect off;
	}

	# Static files
	location /static {
		alias /home/taiga/taiga-back/static;
	}

	# Media files
	location /media {
		alias /home/taiga/taiga-back/media;
	}
}
```

**Is it happening in taiga.io or in your own instance?**
My own instance

**What browser/version are you using?**
Chrome/latest

**Are there any console errors *(Ctrl + F12)* in red?**
Attempting to log in gives an error. Accessing /login does not.

**Comment by alexhermida** [comment]
@Sandvich As long as you have your Nginx backend configuration at `/api` and listening in the 8001 port, you must configure the frontend following those specs with the appropriate port in the conf.json. Like `"api": "http://127.0.0.1:8001/api/v1/"`. 
You must look for network errors getting the `conf.json` in the browser inspector.

**Comment by Sandvich** [comment]
@alexhermida This is not the issue. Inside the container I can access the backend at 8000, the /api bit on the nginx config just allows me to access it from outside the container (albeit on 8001, as that's what I'm sharing to the host).
However, I tried that anyway, and it still doesn't work. I see the GET for conf.json and it appears to be fine, but still there are no requests being logged on the backend and the login fails.

**Comment by Sandvich** [comment]
It occurs to me that the container I've made doesn't contain any proprietary information, so I've shared it on github [here](https://github.com/Sandvich/taiga-docker). Maybe this will make it easier to find the source of the problem.

**Comment by alexhermida** [comment]
Ok, I understand. And what error message do you get when you try to log in?

**Comment by Sandvich** [comment]
It just complains that the username or password is wrong - but I don't see any logs in the backend so it can't be actually hitting the backend.

**Comment by Sandvich** [comment]
@alexhermida Never mind, I'm being dumb! It was just that I'd copied the file to taiga-front-dist/conf.json instead of taiga-front-dist/dist/conf.json!

**Comment by Sandvich** [comment]
(thank you, btw!)
