### ISSUE TITLE
Sorting US in the Sprint box in the backlog section is broken

### ISSUE THREAD

**Issue by gabbork** [taigaio/taiga-front#1759]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
When sorting the US inside the Sprint 'box' in backlog section, after drag&dropping the item, it moves in an apparently random position

**If the current behavior is a bug, please provide the steps to reproduce.**
Given the backlog section
And an open sprint
And at least 2 or more User Stories already inside the Sprint box on the right
And at least an other still not assigned US in the backlog list
When drag&drop the US in a particular position in the Sprint box (both within the Sprint box or from the backlog item list)
Then it didn't stay in the desired position, but moves in another one (not every time, but often)

**What is the expected behavior?**
The US staying in the desired position. This is a new bug, never found in previous Taiga versions

**Is it happening in taiga.io or in your own instance?**
Both

**What browser/version are you using?**
Google Chrome 73.0.3683.103 on macOS Mojave 10.14.4

**Are there any console errors *(Ctrl + F12)* in red?**
Just opening Taiga:
api.taiga.io/api/v1/user-storage/52643ec3c7cf2bfae6c43337330ec92ab1675713:1 Failed to load resource: the server responded with a status of 404 (Not Found)
2api.taiga.io/api/v1/user-storage/5b36fa240b0843ad41a646bf31d706707c85bc05:1 Failed to load resource: the server responded with a status of 404 (Not Found)

Thanks for reporting!

**Comment by alexhermida** [comment]
Duplicated. Issue #1748
