### ISSUE TITLE
Cannot open links to tasks from the sprint board in a new tab

### ISSUE THREAD

**Issue by brettp** [taigaio/taiga-front#1773]
Using cmd / ctrl + click does not open links in a new tab from the sprint board. This looks like a regression of #532 

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Links do not open when cmd / ctrl + clicking.

**If the current behavior is a bug, please provide the steps to reproduce.**
Open a sprint board. Cmd / ctrl + click on a task. 

**What is the expected behavior?**
The task should open in a new tab.

**Is it happening in taiga.io or in your own instance?**
Both

**What browser/version are you using?**
Chrome / FF / Safari latest

**Are there any console errors *(Ctrl + F12)* in red?**
No

Thanks for reporting!

**Comment by brettp** [comment]
@Xaviju @juanfran @bameda 

This is still an issue and is starting to severely impact our sprint planning meetings because we keep losing our place since we can't open new tabs. Is this considered expected behavior now? If so, please at least let me know so we can consider alternatives or forking.

**Comment by juanfran** [comment]
sorry @brettp but right now I'm not involved in developing Taiga so I'm not 100% sure but it seems to come from allowing multi drag&drop in macOS https://github.com/taigaio/taiga-front/pull/1424

**Comment by migonzalvar** [comment]
Hi @brettp. Please, take a look at pull request #1908. Could you try it and check if will work for you?

**Comment by brettp** [comment]
Sorry, @migonzalvar -- This notification slipped through the cracks. We have migrated away from Taiga, so unfortunately I cannot test this.

**Comment by NatachaMenjibar** [comment]
We have been doing some housekeeping work prior to Taiga6 upcoming release and we are reviewing old issues that we didn't correctly attend back then. Since Taiga6 brings a significant UX/UI rework, we encourage you to wait and see if Taiga6 satisfies this need and open a new issue if that's not the case. This time we will make sure to review it when it comes through. 

Thank you very much on behalf of the Taiga Team!
