### ISSUE TITLE
Ability to unset complex custom filters in one click

### ISSUE THREAD

**Issue by affanshahid** [taigaio/taiga-front#1787]
**Feature Request**

If I apply a complex custom filter (i.e one with multiple conditions) I need to manually unselect all the applied conditions to clear it. There should be a one-click method of unapplying the filter.

For example clicking again on the custom filter should unset all the conditions that were part of that filter

**Comment by diacritica** [comment]
UX UI proposed by Taiga's core team

![5778_clear_custom_filter_1](https://user-images.githubusercontent.com/1606348/66584634-cc2a1b00-eb85-11e9-9746-f676dd957ee0.png)
![5778_clear_custom_filter_2](https://user-images.githubusercontent.com/1606348/66584635-ccc2b180-eb85-11e9-8dcf-02385687607f.png)
![5778_clear_custom_filter_3](https://user-images.githubusercontent.com/1606348/66584636-ccc2b180-eb85-11e9-9e40-6b8a8b5242d4.png)
