### ISSUE TITLE
Taiga behind basic auth

### ISSUE THREAD

**Issue by c64bob** [taigaio/taiga-front#1789]
Is it possible to run Taiga behind a reverse proxy (e.g. nginx) with basic auth? I've tried, but the Authorization header gets overwritten by nginx or taiga. Any tricks to make this work?

**Comment by zentavr** [comment]
My colleagues report the same issue. Personally I did not caught the problem.
I'm on Firefox ESR on Mac.

**Comment by c64bob** [comment]
I have managed to "solve" this using client certificates.
