### ISSUE TITLE
Display Error on Registration Page

### ISSUE THREAD

**Issue by DPRIYATHAM** [taigaio/taiga-front#179]
**Describe the bug**

This is **a small bug** yet a **special kind of bug**, which any developer or user will face only once.
Because it is in the [Registration Page](https://tree.taiga.io/register)
Due to that reason it might have been un-noticed yet.
I found this bug when I am signing up for taiga this week.
The form in the Registration Page is having a issue in displaying the **Form_Errors** Messages, when we enter the details in wrong format we are supposed to display a error message, describing what is wrong with their entered credentials.
Though it's giving the correct error message for each case, there is a error in displaying them, there is a CSS error in displaying those error messages.
The error messages are in the same color (#ffffff) as the background-color. which are supposed to be in red color.

**How can we reproduce the behavior**

Change the css of the form's error-displaying class, by adding color to the text as red

**Workarounds**

I am still interested to work with Taiga, which is a good open source platform, 
I am also interested in solving this bug, 
I would be glad if you assign this issue to me as I am interested in making open source contributions,
I will be happy if I can contribute to Taiga.

**Screenshots**

How it is behaving:
![image](https://user-images.githubusercontent.com/94455615/232043599-115bf2ee-35d9-4700-a26b-62494dffba1d.png)
How it is expected to behave:
![image](https://user-images.githubusercontent.com/94455615/232043724-8b0c43bb-ca54-4984-963f-88af58778e1f.png)
These lines, which I highlighted should be visible in red, for instructing the user.

**Taiga environment**

I am using [Taiga.io](https://www.taiga.io/) 

**Desktop (please complete the following information):**
 - **OS:** Windows
 - **Browser:** Chrome, Firefox

**Comment by DPRIYATHAM** [comment]
I am interested to work on this issue please, assign to me.

**Comment by NatachaMenjibar** [comment]
Hi @DPRIYATHAM 
Thanks for reporting this bug and for offering you to fix it! We really appreciate it.
 I'm assigning this bug to you. Once you are ready with your pull request, our team will review it.
 
 Thanks again for your support!

**Comment by DPRIYATHAM** [comment]
Hey, @NatachaMenjibar 
Thanks for assigning me on this bug, on the way of fixing I went through contributors guidelines and procedure,
1. Forked repo `taiga-front`, cloned into my local machine.
2. Installed nvm, node version 16.19.1
3. `npm start` and I ended upon a blank white page, in the localhost:9001 
4. The tab name is displaying as taiga and I am getting logo there.
5. The body and everything is simply white.

I am not getting what is the issue. 🥲 
Could you please help me out, to host the webpage properly, so I can fix the bug.
Please let me know if I missed any steps or do I need `taiga-back` too on my machine.

-Thank you.

**Comment by juanfran** [comment]
@DPRIYATHAM, you need `taiga-back`, but it's easier to use the production environment for this.

To do so, you just need to edit your `dist/config.json` and use the following configuration:

```json
{
    "api": "https://api.taiga.io/api/v1/",
    "eventsUrl": "wss://api.taiga.io/events",
    "isSaas": true,
    "debug": false,
    "eventsHeartbeatIntervalTime": 30000,
    "publicRegisterEnabled": true,
    "feedbackEnabled": true,
    "supportUrl": "https://community.taiga.io/",
    "privacyPolicyUrl": "https://taiga.io/privacy-policy",
    "termsOfServiceUrl": "https://taiga.io/terms-and-conditions",
    "maxUploadFileSize": 104857600,
    "enableGithubImporter": true,
    "enableJiraImporter": true,
    "enableTrelloImporter": true,
    "enableAsanaImporter": true,
    "themes": ["taiga"],
    "contribPlugins": [

    ]
}
```

**Comment by DPRIYATHAM** [comment]
There is actually no `config.json` file in `dist`folder, I can only find `conf.example.json` file there.
And also are there any commands to start or host the backend too?
`"api": "http://localhost:8000/api/v1/",` I found this there, does it mean there should be running something in localhost:8000?

**Comment by juanfran** [comment]
You can create the `conf.json` in the dist folder using the JSON from my previous message. Alternatively, you can copy and paste the `conf.example.json` file, setting up the back-end may require more time: https://community.taiga.io/t/taiga-30min-setup/170

**Comment by DPRIYATHAM** [comment]
So if I go with the above steps, I don't need a backend right sir?
As I will be using production environment.

**Comment by juanfran** [comment]
yes, you don't need it a local backend for this.

**Comment by DPRIYATHAM** [comment]
I am actually using the code you shared sir, 

![image](https://github.com/kaleidos-ventures/taiga-front/assets/94455615/48f503c0-faf1-4eeb-8b40-4e47eb227d2b)
Output was better than before, it's showing me `Loading...`, colored loading line on the top, of the page, and giving this pop-up, which before was only a white page.
But still I couldn't host the application properly.🥲 
Could you please suggest me how to overcome this issue.
Am I missing something more?

**Comment by juanfran** [comment]
I'm not sure, it should be fine. Could you open Chrome devTools to see if there are any errors?

**Comment by DPRIYATHAM** [comment]
![image](https://github.com/kaleidos-ventures/taiga-front/assets/94455615/b703cb88-cd2a-4f6e-a4cc-f2b490420a01)
` "eventsUrl": "wss://api.taiga.io/events",`
This is not working in the conf.json file, is this the issue which is making the page unresponsive?
can you please check this issue sir?

**Comment by juanfran** [comment]
that's what is expected, you can't access wss that way.

I have recorded a video in linux with the whole process. Check that you followed the same steps.

[front.webm](https://github.com/kaleidos-ventures/taiga-front/assets/905195/8761c01a-c98c-4cec-a24e-9973c2eb161f)

**Comment by DPRIYATHAM** [comment]
Hey, thanks for your efforts, I done everything again from the beginning by following the above video, but I am still getting the same error 😢 
I'll try to debug.

**Comment by DPRIYATHAM** [comment]
Hey,
I wanted to try fixing the bug again today but I found out that, it's already resolved.
I couldn't fix the bug, but I just want to thank and appreciate you for the support and opportunity @juanfran .
Thank you.
