### ISSUE TITLE
Feature Request: Scroll kanban view using mouse click-drag

### ISSUE THREAD

**Issue by lonix1** [taigaio/taiga-front#1790]
In the kanban view, to scroll left/right we need to use the scrollbars, or use middle-click scrolling.

It would be nice to have click-drag scrolling. That's when you click, hold and move the mouse. On some platforms the cursor changes to a small hand icon. And then you can drag left/right to scroll left/right.

Would be much more convenient.

**Comment by theriverman** [comment]
Hold down the shift key and scroll like you usually do. Should be scrolling horizontally now.

**Comment by lonix1** [comment]
Nice trick, thanks!

Not the same as grab-scrolling though.
