### ISSUE TITLE
Feature Request: Global KANBAN view with filtering by user

### ISSUE THREAD

**Issue by curtisnehring** [taigaio/taiga-front#1793]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
From what I can see in the UI and via the docs KANBAN view is only usable by Project. I.E. you select a Project and then KANBAN view.

What I would like is a way to view KANBAN globally for all current projects and then be able to filter by User.

For example I would like a Global KANBAN view where I can see all of the US for all of the Projects I am currently working on. Right now I have to switch from Project to Project to see everything that I have going on.

It would also be great if as an admin I could switch from User to User to see the Global KANBAN for each user.

I realize that different project can have different statuses resulting in different column headings in KANBAN view. A potential solution would be to display statuses that don't exist in one project before or after the statuses in common as ordered by the altered project.

For example the current default statuses are: 
  new/ready/in-progress/ready for test/done/archived

Perhaps customized project 1 has: 
  new/in-review/ready/in-progress/ready for test/client-review/done/archived

Perhaps customized project 2 has: 
  new/ready/out for scheduling/in-progress/done/archived

Some of these are in common so perhaps a merged KANBAN might look like:
  new/in-review/ready/out-for-scheduling/in-progress/ready for test/client-review/done/archived

Thanks for all the great work you've done so far!

**Comment by senner** [comment]
We built our own angular app that does just this. It's a global Kanban view, and you can filter by user or project or all projects.  We serve it at https://servername/kanban/ and it uses all Rest api calls. We built for our own internal use but if of interest to you i can see if they can wrap it up and release on github.
