### ISSUE TITLE
Broken "Help" link in Taiga.io

### ISSUE THREAD

**Issue by mstratman** [taigaio/taiga-front#1795]
Clicking "Help" from within my project (e.g. `https://tree.taiga.io/project/MY-PROJECT/kanban?q=`) goes to `https://tree.taiga.io/support`, which is 404.

Link probably should be `https://tree.taiga.io/support/`

**Comment by alexhermida** [comment]
Thank you @mstratman!. It's frontend configuration, we already fixed in production.
