### ISSUE TITLE
Make pageSize configurable

### ISSUE THREAD

**Issue by chrisfromredfin** [taigaio/taiga-front#1798]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
When scrolling through the backlog, there is a lazy-load pager that happens when you get to the bottom. 

**What is the expected behavior?**
I would like to be able to configure the pageSize to a number more comfortable in my instance (for me, higher - or disabling the pager altogether).

**Is it happening in taiga.io or in your own instance?**
Both

**Comment by pcorbett** [comment]
I may not be using Taiga correctly, but this is an issue for me as well where when we are planning a sprint with a client and looking at the project backlog together. If a story is at the bottom of the backlog, and using advanced filters still leaves the list rather long (>100 stories), a lot of time is wasted scrolling down the list and waiting for the lazy loader to reach the end. Once a story close to the end of the list is identified, you then either need to drag it way back up to the top where the Sprint drop area is or check the box next to the stories you wish to assign to the current sprint by scrolling back up to the top and clicking the appropriate button.

It would be nice, at least in this instance to either turn off lazy loading or specify the number of items to load at once.

**Comment by LosaMatova** [comment]
I second this for Epics as well, currently only 33 epics can be shown at a time and there is no lazy loading.

**Comment by joostcoelingh** [comment]
I would like to see this implemented
