### ISSUE TITLE
Visual bug ponts in backlog

### ISSUE THREAD

**Issue by yamila-moreno** [taigaio/taiga-front#1799]
**Do you want to request a *feature* or report a *bug*?**

BUG

**What is the current behavior?**

In the backlog > points column > select "?" > "ux" (to select points for a US). The layer has only the first row of points. (see image)
![bugtaiga](https://user-images.githubusercontent.com/3340793/64697607-7d636580-d4a1-11e9-9027-e961f86a0982.png)

If you enter the detail of the US you can choose between all the possible points.

**What is the expected behavior?**

Instead of the partial layer, a complete set of points should appear

**Is it happening in taiga.io or in your own instance?**

tree.taiga.io

**What browser/version are you using?**

Firefox

**Are there any console errors *(Ctrl + F12)* in red?**

nope

**Comment by dangarbar** [comment]
Fixed in 7a826857f693756eb3bf57d2e251181d286183f7
