### ISSUE TITLE
Epics lack Lazy-Loading or Pagination, therefore not all epics are shown.

### ISSUE THREAD

**Issue by LosaMatova** [taigaio/taiga-front#1803]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Only 33 epics can be shown at a time, no lazy loading or pagination is available to see more, thus making them hard to manage and update.
**If the current behavior is a bug, please provide the steps to reproduce.**
Make a few dozen epics, 
Go to /project/<project>/epics (The epics module)
**What is the expected behavior?**
Every epic is shown on the epics module, or at least accessible. 
**Is it happening in taiga.io or in your own instance?**
Own Instance
**What browser/version are you using?**
Test on Chrome (Latest as of Sept/19) and Firefox (Ditto)
**Are there any console errors *(Ctrl + F12)* in red?**
No

**Comment by eesprit** [comment]
Related to #1733 ?
