### ISSUE TITLE
Wiki page titles should be editable

### ISSUE THREAD

**Issue by diacritica** [taigaio/taiga-front#1816]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

Once you create a wiki page, you enter a title and that stays forever. You can delete the page but that's all, no option to change it.

**What is the expected behavior?**

This is a tricky one. Changing the page title should be available and immediately applied to any link used in the project that pointed to that. Otherwise, it will result in broken links within the wiki and from project content.

An initial approach could be that the page title is changed but its slug is not, so no need to rewrite existing links but it might lead to confusing for future references. Example: I create a wiki page titled "Monday" and then reference it back from 10 pages and comments. I change it to "Tuesday" but slug remains monday, which is what matters to links and future wiki references. It will lead to confusion. This initial approach might be counterproductive.

**Comment by wrapper** [comment]
I think changing the slugs everywhere might be the solution? Normally a unique identifier would be used and not just a slug which would prevent this issue (then slugs can be redirected easily)

You can actually change the slug in /admin/ and then add a new bookmark to the new slug, it's a bit messy but it does seem to work.
