### ISSUE TITLE
Notifications doesn't work on 4.2.14

### ISSUE THREAD

**Issue by mmazzocchetti** [taigaio/taiga-front#1821]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Notifications doesn't work in the latest 4.2.14 version, on 4.2.12 works well

**If the current behavior is a bug, please provide the steps to reproduce.**
Login with an account from with browser cache cleaned

**What is the expected behavior?**
Browser asks notifications permission 

**Is it happening in taiga.io or in your own instance?**
Own instance

**What browser/version are you using?**
Chrome latest, Edge latest, Firefox latest on Windows and Linux
**Are there any console errors *(Ctrl + F12)* in red?**
Only console log message "This browser does not support desktop notification"

I think  [this](https://github.com/taigaio/taiga-front/commit/5d6bba1ffb78067dff1cad48334d5f436a7eb73d?diff=unified#diff-98e6872af27b656cd27b55a3de9eff19) change in app/coffee/modules/events.coffee broke something.

**Comment by leepfrog-ger** [comment]
any updates on this? seeing the same with the most recent version on my local instance

**Comment by djgreg13** [comment]
It is the same with 5.0.15

**Comment by NatachaMenjibar** [comment]
We have been doing some housekeeping work prior to Taiga6 upcoming release and we are reviewing old issues that we didn't correctly attend back then. Taiga6 brings a significant UX/UI rework, and after the launch, we’ll come back to this issue as it’s part of our roadmap. This time we will make sure to review it properly. 

Thank you very much on behalf of the Taiga Team!

**Comment by olegy89** [comment]
taiga 6.0.2 same issue, Firefox, Chrome, Safari all the same.

**Comment by juanfran** [comment]
Fixed in https://github.com/taigaio/taiga-front/commit/9f488bc809312ce6557c51fb011e805d60f817bb and it will be in production in the next release

Thanks for reporting!
