### ISSUE TITLE
WIP limit setting not showing in UI

### ISSUE THREAD

**Issue by moreshiny** [taigaio/taiga-front#1838]
On taiga.io when the window is maximised the WIP limit setting is not shown for User Stories in the status settings, and I cannot set a value for this. There is no horizontal scrollbar, the setting is simply not shown at all even though there is plenty of screen space.

![Fullscreen-no-WIP](https://user-images.githubusercontent.com/58051424/69377632-facf0180-0cac-11ea-8088-d128fff9f2f9.png)

When I reduce the window to half, the setting appears and can be set, but the UI is quite distorted, still cropped, and there is still no vertical scrollbar.

![Halfscreen-WIP](https://user-images.githubusercontent.com/58051424/69377630-fa366b00-0cac-11ea-9b47-f88327b98672.png)

To reproduce (on Firefox 70.0.1 on Ubuntu) navigate to Attributes -> Statuses the WIP column and try to set the WIP limit for User Stories while the browser is at fullscreen (1920x1080).

I would expect the UI to scale more cleanly and a scrollbar to appear when part of the UI is hidden.

**Comment by migonzalvar** [comment]
Thank you @moreshiny
