### ISSUE TITLE
Wrong folding state for sprint in backlog view

### ISSUE THREAD

**Issue by hardion** [taigaio/taiga-front#185]
Thanks guys for this refreshing tool. I am giving a try now and found one UI issue.

Taiga did not accept when I tried to drag a user story from the backlog to one sprint because the sprint was fold.
I did not understand first as the symbol ">" was in the unfold position. My brain mistakes me as the symbol of another sprint was in the same position but really unfold (there was a user story in).
To be able to drag again, I had to "fold" the sprint.
![image](https://cloud.githubusercontent.com/assets/305207/5239071/fd694432-78d2-11e4-9efc-c6728fba2175.png)

**Comment by Xaviju** [comment]
This should be fixed! :+1:
