### ISSUE TITLE
Bug : Can't change the task name in the userstory tasks list 

### ISSUE THREAD

**Issue by jerem-ie** [taigaio/taiga-front#1862]
**Do you want to request a *feature* or report a *bug*?**
Bug 

**What is the current behavior?**
I want to update the name of one task in the US page, on the tasks list. Usually, i'm doing that with the help of the pen icon, appearing when you fly over the task. 
In the last stable version of the taiga-front-dist, it threw an this.childScope is undefined error.

**What is the expected behavior?**
Changing the name of a task by using the pen icon on the userstory tasks list.

**Is it happening in taiga.io or in your own instance?**
Own Instnace, 

**What browser/version are you using?**
Firefox 72.0.1 and Chromium Version 79.0.3945.79

**Are there any console errors *(Ctrl + F12)* in red?**
```
TypeError: this.childScope is undefined app.js:3810:8
    f app.js:3810
    g app.js:3849
    jQuery 2
        dispatch
        handle
```

**Comment by dangarbar** [comment]
Fixed in https://github.com/taigaio/taiga-front/commit/80407d91591a90d4134c782e1c4cc32ad0a33276
