### ISSUE TITLE
Contributing to taiga: setting up the development environment

### ISSUE THREAD

**Issue by AnthonyLenglet** [taigaio/taiga-front#1863]
> note: not sure wether to post this here or in the mailing list, though I felt an issue would give this more visibility for anyone who has tried contributing and gotten in the same issue

Since this isn't an usual issue, I'll be removing the issue template for this one

As it stands, the project is running under angularJS with coffeescript and jade, and with this stack becoming a bit dated over the years, it seems like the IDEs are having trouble giving a correct experience with it

An exemple in our case:
- under VSCode: there's a complete lack of intellisense and autocomplete for anything in the files, installing the [Coffeescript-support extension](https://marketplace.visualstudio.com/items?itemName=yorkxin.coffeescript-support) does not help more than this

![image](https://user-images.githubusercontent.com/36004334/72739711-81686800-3ba4-11ea-893c-bd7913edde36.png)

I've also tried other IDEs and editors:
- sublime text 2 and 3
- text mate
- Intellij IDEA

IDEA seems to work best, however I'm not sure if this is the one that is being used internally or if there's another alternative (having to switch to an IDE specifically for this is kind of alienating, especially for a paid one)

having multiple possibilities for this would be amazing, especially with VSCode, with it being the most commonly used one in this field

I think it would be great if a wiki page or a part of the readme would give info about a possible development environment in order to make it easier to contribute to the project, because having intellisense and autocomplete can definitely help navigating a big unknown project such as this one

**Comment by blurp1478963** [comment]
Same experience... any better ideas?

**Comment by jcrben** [comment]
Might be time to consider switching from coffeescript? https://github.com/decaffeinate/decaffeinate

**Comment by yamila-moreno** [comment]
We have been doing some housekeeping work prior to Taiga6 upcoming release and we are reviewing old issues that we didn't correctly address back then. Taiga6 brings a significant UX/UI rework, and after the launch, we’ll come back to this issue to check it again. This time we will make sure to review it properly. More specifically, updating the technology is in the near roadmap.
Thank you very much on behalf of the Taiga Team!

**Comment by thda** [comment]
Hi,

thanks for the great software.

Can we find this roadmap somewhere ? The company I work for could contribute, however the learning curve is too steep as it is.

Cheers

**Comment by yamila-moreno** [comment]
Hi @thda thanks for your interest. We have documentation about setting a development environment but it's not properly updated as it should be. It's in our next to-do list however, cause we understand its importance.

You'll find the development documentation here: https://taigaio.github.io/taiga-doc/dist/#development

**Comment by thda** [comment]
Thanks,

However I was refering to this:

> updating the technology is in the near roadmap.

When we review our contribution policy we are also checking the applicative stack.
Shall I open a separate issue ?

**Comment by yamila-moreno** [comment]
@thda 
- a public roadmap is also in the roadmap, we understand its importance
- although we plan to make importants update, right now it's unlikely that we'll change the stack python/angular based

**Comment by thda** [comment]
Thanks for taking the time to answer. I will check the announcements.
We have django & angular experts, the issue was more coffeescript  to be honest.
Btw we can contribute kubernetes kustomize configurations, ldap & kerberos plugins.
