### ISSUE TITLE
Filter sidebar partially shown when closed under certain circumstances

### ISSUE THREAD

**Issue by thejavascriptman** [taigaio/taiga-front#1885]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Filter sidebar is partially shown in the Kanban view when resolutions higher than 1920x1080 are used

**If the current behavior is a bug, please provide the steps to reproduce.**
Visit the Kanban view using a resolution higher than 1920x1080 (or use `Ctrl` + `-` to zoom out which will trigger the same behavior)

**What is the expected behavior?**
The filter sidebar should not be shown when closed

**Is it happening in taiga.io or in your own instance?**
Both

**What browser/version are you using?**
Chromium 80

**Are there any console errors *(Ctrl + F12)* in red?**
No

**Comment by migonzalvar** [comment]
Fixed in 3bf7fc44a3bd11d80d44c5256e737829d6476f08.

Thank you for reporting
