### ISSUE TITLE
Can I promote a Task/Issue to a User-Story via API?

### ISSUE THREAD

**Issue by ylapshin** [taigaio/taiga-front#1891]
How? Please, help!

**Comment by yamila-moreno** [comment]
Hi @ylapshin; to promote a issue to a US, you have to do a POST request:

```
https://api.taiga.io/api/v1/issues/{issue_id}/promote_to_user_story
```

with the body:
```
{'project_id': 'XXXX' }
```
Besides, as this is a lack in the documentation, I'm creating a new issue to address it. Thanks for your participation!
