### ISSUE TITLE
Angular 2+

### ISSUE THREAD

**Issue by jayvdb** [taigaio/taiga-front#1897]
I see Taiga is still using Angular JS.

There was a branch for Angular 2+, but it appears to have died.

I know having a Angular 2+ UI would be a significant consideration of the decision making process for the PM tool used by the OSS company I work for, and I expect it would be others.  We are a Django+Angular 2+ shop, using a commercial closed source SaaS product which is good enough for our needs, and has a better feature match than most OSS tools we have evaluated.  But having a basic, 'incomplete' even, Angular 2+ interface would make Taiga a serious replacement, as we could build any core bits which we need, and add extensions we needed.  But we're not going to invest into a Angular 1.x tool - to begin with it would drive our devs balmy.

Can a serious plan for Angular 2+ be developed, so interested parties can help bring it to reality.

**Comment by juanfran** [comment]
Totally agree, we'll probably talk about this in 1 or 2 weeks and we will star working on an upgrade of the frontend stack.

**Comment by juanfran** [comment]
We've started working in Taiga with Angular 9 :smiley:, no repo/branch yet

**Comment by jayvdb** [comment]
Hmm.  Closed again without anything tangible/visible.
Still open at https://tree.taiga.io/project/taiga/issue/5884 ;-)

**Comment by juanfran** [comment]
Thanks!

We are going to start from scratch probably in a new Taiga project and new repo. It's a lot of work so we are discussing how to do it.
