### ISSUE TITLE
Feature request: Automatic tag or issue id numbering

### ISSUE THREAD

**Issue by remus-selea** [taigaio/taiga-front#1918]
**What is the current behavior?**
Currently you have to manually enter the tag into each individual story.
![image](https://user-images.githubusercontent.com/58348422/82750150-dc120a80-9db6-11ea-9e9f-c34b78beb0a1.png)

**What is the expected behavior?**
Automatically assign to all issues the same tag with an incremented number.
GE-1, GE-2, GE-3... 
This would make it easier to identify the issue when making commits on github, for example:
[GE-37] Add new feature X

**Comment by NatachaMenjibar** [comment]
We have been doing some housekeeping work prior to Taiga6 upcoming release and we are rejecting old issues that we didn't correctly attend back then. Taiga6 brings a significant UX/UI rework, and we are certain it improves overall experience. However, this feature does not have fit in the 6.x roadmap, so we’re closing it.

Thank you very much on behalf of the Taiga Team!
