### ISSUE TITLE
Feature Request - Project "Templates" (Customized Admin Setup)

### ISSUE THREAD

**Issue by linkerx** [taigaio/taiga-front#1924]
**What is the expected behavior?**
Create my own project templates with my personal configurations, column names, colors, etc. Every time i setup a new project, have to do a buch of configurations.

**Alternative**
I have an instance of taiga running in docker containers on my own server, can i edit default values on Django Admin? or directly in the database?

**Comment by zazy** [comment]
Have you tried the **duplicate project** feature? Doesn't it do what you ask?

**Comment by linkerx** [comment]
Yes sorry
