### ISSUE TITLE
[FEATURE] LaTeX support in Taiga

### ISSUE THREAD

**Issue by madmath03** [taigaio/taiga-front#1929]
**Do you want to request a *feature* or report a *bug*?**

Feature Request.

**What is the current behavior?**

Currently, if we want to include a formula in the description of a Taiga object, we need to generate and export it as an image and add it as attachment.

**What is the expected behavior?**

It would be nice if LaTeX syntax like `$\frac{1}{2} = 0.5$`, probably using [KaTeX](https://katex.org/),  could be integrated to the Markdown component.

**Is it happening in taiga.io or in your own instance?**

All.

**What browser/version are you using?**

All.

**Are there any console errors *(Ctrl + F12)* in red?**

None, not a bug.

**Comment by NatachaMenjibar** [comment]
We have been doing some housekeeping work prior to Taiga6 upcoming release and we are rejecting old issues that we didn't correctly attend back then. Taiga6 brings a significant UX/UI rework, and we are certain it improves overall experience. However, this feature does not have fit in the 6.x roadmap, so we’re closing it. 

Thank you very much on behalf of the Taiga Team!
