### ISSUE TITLE
Allow bulk editing of stories.

### ISSUE THREAD

**Issue by SpacyRicochet** [taigaio/taiga-front#193]
Very useful when trying to tagging multiple stories with the same tag, or assign a group of stories to one person.

**Comment by leftclickben** [comment]
:+1: This would be great, also assigning user story points in bulk.

**Comment by rmpato** [comment]
I see that this is from year 2014. Is there any feature like this already? I need to move 174 US to archived, and I would love to do this in bulk.

**Comment by superalex** [comment]
Hello @rmpato we still couldn't work on this so right now there is now way to do it in bulk.

**Comment by ichpen** [comment]
@superalex As a fresh new user of taiga this is by far the most frustrating feature.

1. Bulk tagging
2. Bulk edits
3. Some sort of quick view at the very least so that you can do this without opening each story individually
4. Bulk delete

**Comment by alexxmde** [comment]
@superalex, couldnt agree more with @ichpen.
I need to bulk-tag and book-points my bulk-inserts. I have now inserted some 20 user stories that I'll have to edit each, one by one. I'm a lazy guy, you know... That would be an amazing feature to prioritize!

**Comment by IwishIcanFLighT** [comment]
Bump on that issue. I have a ton of tasks to tag with the same value but clicking on one-by-one is very frustrating and time consuming. Thanks

**Comment by KDWorsley** [comment]
We need to move a few hundred task from finished to archived. How about a "Select All" and perform an action?

**Comment by phosphre** [comment]
@KDWorsley agreed - click-shift-click would be amazeballs.

**Comment by RichardPflaum** [comment]
is this already reopened or possible in Taiga 6? I'm just getting started with Taiga and completely agree this would facilitate things a lot! I saw that click + shift click already works which is great! I could not find a bulk-tagging functionality yet though.
