### ISSUE TITLE
FR: Points & Votes should be optional

### ISSUE THREAD

**Issue by blaggacao** [taigaio/taiga-front#1944]
I have no decent use for points and votes metadata in most circumstances, please make them configurable on kanban projects. They are just clutter. I'd rather prefer #1941 (better tags visibility)

**Comment by yamila-moreno** [comment]
We have been doing some housekeeping work prior to Taiga6 upcoming release and we are rejecting old issues that we didn't correctly attend back then. Taiga6 brings a significant UX/UI rework, and we are certain it improves overall experience.
Regarding these two topics: 
- Votes will have important changes. 
- However, Points does not have fit in the 6.x roadmap, so we’re closing it.

Thank you very much on behalf of the Taiga Team!
