### ISSUE TITLE
Add an option to mae Make a project "Protected"

### ISSUE THREAD

**Issue by njsubedi** [taigaio/taiga-front#1960]
I am suggesting a new feature. The current behavior is that the Taiga instance is publicly visible, even to the public. In a team, most projects need to be shared among only the members of the team. 

But Taiga only allows sharing the project with individual members, one by one, or make it public.

There could be an option to set the project's privacy "protected" or "all members".

**Comment by diacritica** [comment]
Hi @njsubedi Have you tried setting the Taiga project private and then giving some permissions to External User role? External User allows Taiga users not belonging to the project to do some work (what you say there in those permissions). That could do the trick, wouldn't it?

**Comment by Xaviju** [comment]
This issue has been closed because it seems inactive.  You may reopen this issue if it has been closed in error.
