### ISSUE TITLE
Bug in scrum sprint taskboard display when user story is folded

### ISSUE THREAD

**Issue by antonc42** [taigaio/taiga-front#1994]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
In a scrum taskboard, when a user story is folded, the icons representing the tasks are displayed one per line rather than many per line as previously. As a result, the folded size of the story is unnecessarily large. See image below:

![taiga-taskboard-actual](https://user-images.githubusercontent.com/13502058/95900711-eb8af380-0d57-11eb-8d1b-9b2f0f0e680d.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Go to a sprint taskboard that has a user story with multiple sub-tasks.
2. Fold the user story using the fold button to the left of the story name.
3. Observe the icons representing tasks are displayed one per line.

**What is the expected behavior?**
When a user story is folded, the task icons should display multiple per line and wrap to the width of the status column. See image below:

![taiga-taskboard-desired](https://user-images.githubusercontent.com/13502058/95900709-eaf25d00-0d57-11eb-896d-02466ac6806d.png)

**Is it happening in taiga.io or in your own instance?**
Our own instance.

**What browser/version are you using?**
Firefox 81.0
Google Chrome 86.0.4240.75

**Are there any console errors *(Ctrl + F12)* in red?**
No, there are no errors in the browser console.

**Additional Notes**
This issue appears to be caused by this line: https://github.com/taigaio/taiga-front/blob/94221d9b01fc099dba1294c4e14a4cfe276822b5/app/styles/modules/backlog/taskboard-table.scss#L36
This line was changed in commit 94221d9b01fc099dba1294c4e14a4cfe276822b5
Changing the property to `flex-direction: row;` or removing the line entirely reverts to the desired behavior.

**Comment by antonc42** [comment]
I was able to create a workaround by implementing my own copy of the Taiga theme and modifying it. This is just a temporary solution until the issue is fixed.

I followed the directions here to create a copy of the Taiga theme: https://taigaio.github.io/taiga-doc/dist/#themes

I put the following in the `custom.scss` file:
```
.taskboard-table-body .row-fold .taskboard-column,
.taskboard-table-body .row-fold.taskboard-column {
    flex-direction: row;
}
.taskboard-table-body .column-fold .taskboard-column,
.taskboard-table-body .column-fold.taskboard-column {
    flex-direction: row;
}
```

I then compiled with `gulp deploy` and copied the generated `dist/` directory to my production location.

**Comment by NatachaMenjibar** [comment]
We have been doing some housekeeping work prior to Taiga6 upcoming release and we are reviewing old issues that we didn't correctly address back then. Taiga6 brings a significant UX/UI rework, and after the launch, we’ll come back to this issue to check it again. This time we will make sure to review it properly. 

Thank you very much on behalf of the Taiga Team!

**Comment by Xaviju** [comment]
Closing. This was fixed in the recent Taiga6 release
