### ISSUE TITLE
Caddy Webserver support

### ISSUE THREAD

**Issue by LecrisUT** [taigaio/taiga-front#2008]
**Before adding an issue**
Please ensure that your issue is not already reported in our [issues list](https://tree.taiga.io/project/taiga/issues?order_by=-created_date).
If this issue was already reported, remember that you can upvote it to raise its importance.

**Do you want to request a *feature* or report a *bug*?**
*feature* and clarification

**What is the current behavior?**
Currently I am able to start taiga using `caddy` as a webserver. However I have problems whenever I get redirected to the taiga url. Even directly accessing `taiga/discover` yields a 404 error.
All of the other functionalities seem to work, except I cannot manually add users to projects via the `/admin` page.

**If the current behavior is a bug, please provide the steps to reproduce.**
Use the following `Caddyserver` file to handle all of the redirects:
```
##Caddyfile
taiga {
   root * /var/www/taiga/dist
   encode gzip zstd
   file_server
   route /api/* {
      reverse_proxy localhost:8001
   }
   route /admin/* {
      reverse_proxy localhost:8001
   }
   route /static/* {
      root * /opt/taiga-back
      file_server
   }
   route /media/* {
      root * /opt/taiga-back
      file_server
   }
   route /events/* {
      reverse_proxy localhost:8888
   }
}
```

**What is the expected behavior?**
I suspect there are missing rewrite directives so I wish to ask what are all of the rewrite directives needed for taiga to work with redirects.

**Is it happening in taiga.io or in your own instance?**
Selfhosted

**What browser/version are you using?**
Irrelevant

**Are there any console errors *(Ctrl + F12)* in red?**
404

Thanks for reporting!

**Comment by yamila-moreno** [comment]
We have been doing some housekeeping work prior to Taiga6 upcoming release and we are rejecting old issues that we didn't correctly attend back then. Taiga6 brings a significant UX/UI rework, and we are certain it improves overall experience.

Regarding this specific issue, there are different points:

1. how to configure Caddy. Maybe [this](https://caddy.community/t/caddyfile-for-django-api-and-spa/10196/2?u=yami) solution is helpful for you as it was for me. (TLDR: The order in the Caddyfile is not necessarily the order that caddy uses to resolve)

2. creating users through the `/admin` page is not currently supported

Thank you very much on behalf of the Taiga Team!

**Comment by LecrisUT** [comment]
I have since got a working configuration, and I can share it for future documentation:
However I haven't thoroughly checked if all the Nginx/Apache configurations are ported, and if it will still be compatible with 6.
```
taiga.example.com {
   root * /var/www/taiga/dist
   encode gzip zstd
   @try_files {
      not path /api/* /admin/* /static/* /media/* /events*
      file {
         try_files {path} {path}/ /index.html
      }
   }
   rewrite @try_files {http.matchers.file.relative}
   file_server
   reverse_proxy /api/* localhost:8001
   reverse_proxy /admin/* localhost:8001
   file_server /static/* {
      root /opt/taiga-back
   }
   file_server /media/* {
      root /opt/taiga-back
   }
   reverse_proxy /events* localhost:8888
}

```

**Comment by yamila-moreno** [comment]
Thanks for sharing! as you said, for an SPA, `try_files` is needed. Closing this issue.
