### ISSUE TITLE
Each lane can list more cards in horizontal

### ISSUE THREAD

**Issue by jeffery9** [taigaio/taiga-front#2036]
as a scrum team, i want to display more than one card horizontal in oen lane, eg. display 3 card horizontal is very useful in 4K display.

comments;

1.  this feature should be a options can be set in config.json
2.  the number of card that can be display horizontally is a configuration option.

**Comment by NatachaMenjibar** [comment]
We have been doing some housekeeping work prior to Taiga6 upcoming release and we are reviewing old issues that we didn't correctly address back then. Taiga6 brings a significant UX/UI rework, and after the launch, we’ll come back to this issue to check it again. This time we will make sure to review it properly. 

Thank you very much on behalf of the Taiga Team!

**Comment by Xaviju** [comment]
This has been improved in the recent Taiga 6 release
