### ISSUE TITLE
FR: Federation or sync with project with tree.taiga.io

### ISSUE THREAD

**Issue by LecrisUT** [taigaio/taiga-front#2040]
**Before adding an issue**
Please ensure that your issue is not already reported in our [issues list](https://tree.taiga.io/project/taiga/issues?order_by=-created_date).
If this issue was already reported, remember that you can upvote it to raise its importance.

**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Currently there is no way of syncing or publishing a project from a self-hosted taiga.io to a more open project page.

**What is the expected behavior?**
Such an implementations would help with local private projects which are not on secured public network. Either implementations would be appreciated. Some discussion points I have:
- Federation would help with more data conscious people who want to know exactly where and what data is going out to public or private entities. This feels in spirit with half of taiga's spirit of open source self-hosting.
- This is already partly present with the current webhooks and it would be great to see it expanded to other taiga repositories as well.
- Implementing Github Actions or any other similar option for a 2-way sync would lessen the need for such an implementation.
- If the project hierarchy, organization and other gate-keeping features are implemented, this feature will make more sense, e.g. having a overall management project running on local network and syncing ready for public sub-projects with the world when ready.

**Comment by NatachaMenjibar** [comment]
We have been doing some housekeeping work prior to Taiga6 upcoming release and we are rejecting old issues that we didn't correctly attend back then. Taiga6 brings a significant UX/UI rework, and we are certain it improves overall experience. However, this feature does not have fit in the 6.x roadmap, so we’re closing it. 

Thank you very much on behalf of the Taiga Team!

**Comment by LecrisUT** [comment]
May i reopen this issue here and in the Taiga project once 6.0 is out?

**Comment by yamila-moreno** [comment]
Hi! You may open a new issue, however, for the time being, this is not being implemented as it does not fit in the Taiga 6.x roadmap.

Thank you very much on behalf of the Taiga Team!

**Comment by LecrisUT** [comment]
Ok, I will reopen it after 6.0 is out, and the future roadmap is published.

**Comment by LecrisUT** [comment]
@yamila-moreno I would like to reopen this issue to discuss this feature for future taiga versions.
