### ISSUE TITLE
404 on privacy policy link on cookie message

### ISSUE THREAD

**Issue by xMicky24GIT** [taigaio/taiga-front#2066]
**Before adding an issue**
Please ensure that your issue is not already reported in our [issues list](https://tree.taiga.io/project/taiga/issues?order_by=-created_date).
If this issue was already reported, remember that you can upvote it to raise its importance.

**Do you want to request a *feature* or report a *bug*?**

A bug

**What is the current behavior?**

When I click "clicking here" on the cookie message when I try to register it redirect me to https://www.taiga.io/privacy-policy.html but the page doesn't exists

**If the current behavior is a bug, please provide the steps to reproduce.**

Click "TRY FOR FREE" (or go to https://tree.taiga.io/register) and then click "clicking here" link

**What is the expected behavior?**

I think it should redirect you to https://www.taiga.io/privacy-policy

**Is it happening in taiga.io or in your own instance?**

On taiga.io

**What browser/version are you using?**

Firefox/83.0

**Are there any console errors *(Ctrl + F12)* in red?**

There's a failed CORS request on https://tree.taiga.io/register

Thanks for reporting!

**Comment by bameda** [comment]
Links now works properly, thanks for reporting.

Best regards
