### ISSUE TITLE
Bug: verbatim and links display raw text in the comments

### ISSUE THREAD

**Issue by shinhermit** [taigaio/taiga-front#2078]
Since a few weeks, the verbatim (using ```) and the links (using \[](url)) are not working in the comments. When editing and we set _htm mode_, the verbatim and links dispaly correctly, but when we save, they just display plain text.

We work with recent versions of with Chrome.

**Comment by migonzalvar** [comment]
Hi @shinhermit. Yes, we identified the bug. We missed a class in the comments, so the content is not formatted well. We are working on a fix.

**Comment by migonzalvar** [comment]
Fixed in 0f4a63d0bad9f9c07357c0f2fccfdb4733adb9a3
