### ISSUE TITLE
[enhancement] To be able to filter issues by negating a filter

### ISSUE THREAD

**Issue by fleebzz** [taigaio/taiga-front#210]
I'd like, like on Github, to be able to see all issues which are not closed.

But I don't want to to select all other status like I do today. Just by reverting the filter or something else I don't know...

On screenshot attached I have too much closed issues I don't want to see.

![capture d ecran 2014-12-12 a 11 02 14](https://cloud.githubusercontent.com/assets/507108/5409843/d7a16df4-81ee-11e4-8ac5-68a9bb09b89a.png)

**Comment by ti-mo** [comment]
Hello, any word on this? Would be a nice time saver, we use Taiga's Issues heavily. Cheers!

**Comment by rdesmet** [comment]
+1

**Comment by superalex** [comment]
Hello @ti-mo no news, it's in our list of pending enhancements with moderate priority, I hope we can work on it soon.

Regards!,

**Comment by siliconalchemy** [comment]
+1 this is a major ux defect!

**Comment by wuxxin** [comment]
is it possible to workaround (not having "not filters") using a url in the browser, like adding something to a search url ?

**Comment by superalex** [comment]
Sorry @wuxxin but not right now

**Comment by siliconalchemy** [comment]
Just to follow up, i've found that as a project grows this really becomes a problem.  Once you get over 50-100 issues, the inability to filter out closed issues makes this not an enhancement but a major ux bug.
Ideally it should behave like github - automatically filter out closed issues.

**Comment by wuxxin** [comment]
another idea: is it possible with the API to filter with "not", eg. "all tickets not having tag xxx" .

To do this now, i usually export the tickets to excel,  filter them there, and then go back to taiga to work on the filtered tickets one by one.

i agree with @siliconalchemy that once you have more than 100 (we currently have >300) issues the workflow handling then becomes cumbersome.
