### ISSUE TITLE
Can't select Project in My Projects Tab after Update to 4.2

### ISSUE THREAD

**Issue by tiehscher** [taigaio/taiga-front#2124]
After update to 4.2.6 I can't select a Project (neither new created nor old ones). Doesn't matter if its on the left side of the active projects on the My Projects" or on the right sidebar or even on the top drop down folder icon menu.

The link ist always ending with a "#" (https://example.com/projects/#), no matter which project I choose or hover over.

I'm using Ubuntu Server 18.06 with the user "taiga" and it was working on 3.3.11 without any issues.
If I select a user story from the Dashboard it works and jumps to the Project.

Thanks for your help,
Tiehscher

**Comment by Xaviju** [comment]
Hi @tiehscher Taiga is in version 6. Is this error already fixed?

**Comment by Xaviju** [comment]
Closed because inactiva
