### ISSUE TITLE
repetitive user assignment becomes unresponsive after ~5 assignments

### ISSUE THREAD

**Issue by sviluppatore** [taigaio/taiga-front#213]
I'm not sure if I am in the correct place for this, so please advise and I will resubmit the issue elsewhere.

***Background***
I have an instance running on a local box. I have used the vagrant resource so that I can evaluate the application. Currently, I am the only one using the system and I am populating the projects with data. I have 20 user stories within one project. I am using the Kanban interface, but I have both enabled for the project.

***Problem Description*** 
I will be completing them each user story and was assigning them to reflect that. After about 4 or 5 assignments, one right after another, selecting my name from the list stops working. 

***Workaround*** - or what works for me...
In order for it to work again I either must exit from the selection screen and reselect the user story or perform a search for my name. Once I complete either of those actions the selection works again.

I hope this helps. I have only been using this for a few days, but I think it is pretty slick so far.

**Comment by juanfran** [comment]
fixed in the master branch

thanks @sviluppatore
