### ISSUE TITLE
Different design proposal for US points

### ISSUE THREAD

**Issue by spleenteo** [taigaio/taiga-front#214]
I cannot contribute with real code right now
It is very difficult to visualize and read ponts labels. this is an easy alternative:

original
![original](https://cloud.githubusercontent.com/assets/434724/5478942/e4af72fe-8638-11e4-93e0-e8fd31380146.png)

alternative
![schermata 2014-12-17 alle 21 51 24](https://cloud.githubusercontent.com/assets/434724/5478975/24d6582a-8639-11e4-99af-dd283b8ebfdc.png)

hover
![mouseover](https://cloud.githubusercontent.com/assets/434724/5478968/1e218478-8639-11e4-8e0e-9d9363562594.png)

**Comment by Xaviju** [comment]
This has been recently redesigned with a new approach much more responsive and readable. :+1:
