### ISSUE TITLE
Subtasks can be hard to find.

### ISSUE THREAD

**Issue by jonastreub** [taigaio/taiga-front#216]
Might be nice to have the option to view subtasks without opening a parent.

**Comment by zeigerpuppy** [comment]
excuse my ignorance but how does one create a subtask?

**Comment by superalex** [comment]
@zeigerpuppy I assumed @jonastreub was talking about tasks inside a user story (some people use the work task for what we call user stories in Taiga)

**Comment by zeigerpuppy** [comment]
I see, that makes sense.  
subtasks are an interesting idea but the last meeting my group had came to the conclusion that we just need to be more realistic about what a task is and if it needs subtasks then those should be the items that are in the kanban.  It's all a bit new to us but we're loving being able to explore and modify our flow with taiga, bravo for making it so inviting and forgiving to change.

**Comment by superalex** [comment]
Well, I think that decision depends on your concrete workflow, for Taiga development we are using Taiga with tasks inside user stories and it's working for us. If you can keep it only working with "us" level it's much more comfortable :)

We are really happy that you are enjoying Taiga!

**Comment by metasean** [comment]
> Might be nice to have the option to view subtasks without opening a parent.
Agreed.
> if it needs subtasks then those should be the items that are in the kanban
Agreed.

I'd really like to be able to treat and see sub-tasks exactly like tasks. Specifically, I'd like to be able to:
- From a 'parent task', import an existing task as a "Related Task"
- See *all* tasks on the Kanban board.
  - Ideally, see sub-task cards under their parent tasks.  There may be visualization challenges if:
    - a single sub-task is included in multiple parent tasks.
    - there is a deep thread of sub-tasks.
    - all related tasks can't be completed within a sprint. 
  - It may be easier to simply show a list of sub-tasks (as hyper-links to the actual sub-task) listed on their parent task cards, with an indication of the sub-tasks' status (e.g. a simple icon, lined out when completed, etc.)
- Roll-up estimates from sub-tasks to their parent tasks.

**Comment by metasean** [comment]
I think #398 is related to this enhancement.

**Comment by metasean** [comment]
And in the Backlog list view it would also be nice to see *all* tasks, to include sub-tasks.  Again, potentially with some indication of sub-tasks' relation to parent tasks.  But at this point, **I'd be really happy with any way to indicate (a) prerequisite tasks while also (b) being able to see *all* tasks in a single view.**

**Comment by superalex** [comment]
Thanks for your comments @metasean

**Comment by geoah** [comment]
I've just started working with taiga and I'm very interested in this.
Expanding a story and viewing/adding tasks on the backlog page would be awesome.
(Buld addition of tasks would also be awesome)

Is this planned or should we give it a shot?

**Comment by bameda** [comment]
No, isn't planned yet, but I've taken note. 

Thanks @geoah 

https://tree.taiga.io/project/taiga/issue/1821

**Comment by heyalbert** [comment]
Subtasks can be really hard to find. Is there any progress for this feature request?

**Comment by superalex** [comment]
Hello @heyalbert, still no progress on this one. 

Regards!

**Comment by gabeio** [comment]
I really like @metasean's idea about making all (sub-tasks also) tasks visible on either the kanban board or the task board so that you can move/complete the subtask...

**Comment by zeigerpuppy** [comment]
I agree, revealing subtasks when clicking on a user story in the Kanban view would be logical and easy to navigate.  Then they could be reordered from there.

**Comment by johannesjo** [comment]
+1

**Comment by mkaito** [comment]
:+1:

Tasks need more visibility. They need to be visible outside of their parent US page. Notably, I'd like for them to be visible in an expanded card view in the kanban, and in the backlog under their parent US.

**Comment by aabril** [comment]
:+1:

**Comment by JordyLangen** [comment]
:+1:

**Comment by LC43** [comment]
+1

**Comment by anrue** [comment]
+1

**Comment by diabolo** [comment]
+1 Personally sub tasks really aren't usable without this

**Comment by johnbellone** [comment]
:+1:

**Comment by tgoodlet** [comment]
As a slight jab, this is one of the few things Atllassian's Jira does somewhat right in their Kanban ui
![1456278545](https://cloud.githubusercontent.com/assets/291685/13273101/00cbff9e-da6f-11e5-8193-eb5aac22fb3a.png)

It's pretty simple:
- indent and show subtasks slightly indented *below* their parents if in the same progress column
- show a small greyed out banner referencing the parent US/task if the subtask is in a different KB column

I do think their current solution isn't complete and is one of those things you could [beat Jira on](https://answers.atlassian.com/questions/291555/show-subtasks-on-jira-agile-planning-boards).

For personal TODO / life management projects in particular I think categorization of subtasks is a must!

**Comment by rashtao** [comment]
+1

**Comment by mageddo** [comment]
:+1:  please, taiga is awesome, for me this is the unique thing that is missing:

Explaining on my way:

> Offer subtasks for the kanban story like jira? This way I can move the subtasks and when all subtasks done, the story is done

**Comment by mathieu-b** [comment]
👍 
@bameda / @superalex : has there been any progress on that front?

Maybe as an easier start: having a list of tasks, as for the "Issues", eventually grouped / sortable by user-story?

Thanks for Taiga.

**Comment by Xaviju** [comment]
On the next release, tasks inside a Story will be visible in the kanban/taskboard cards on-demand. 
![kanbantasks](https://cloud.githubusercontent.com/assets/1343702/17472088/0da14ba4-5d49-11e6-820c-30b651f33254.jpg)

**Comment by tgoodlet** [comment]
@Xaviju when's the release due?

**Comment by superalex** [comment]
@tgoodlet probably in september ;)

**Comment by Xaviju** [comment]
This was already released long ago. Closing it.
