### ISSUE TITLE
Caddy webserver support

### ISSUE THREAD

**Issue by LecrisUT** [taigaio/taiga-front#2165]
Firstly, great work on the taiga 6 release. Just from the work needed to migrate it looks like there have been a lot of restructuring.

There are still some configuration issues which might be related to caddy, e.g. ~~taigaio/taiga-events#51~~ (fixed it is a problem in the documentation), but here's a starting caddy configuration:
```
taiga {
   root * /path/to/taiga-front
   # try_files needed to properly redirect on refresh or other common redirects
   @try_files {
      not path /api/* /admin/* /static/* /media/* /events* /_protected/*
      file {
         try_files {path} {path}/ /index.html
      }
   }
   rewrite @try_files {http.matchers.file.relative}
   file_server
   encode gzip zstd
   reverse_proxy /api/* localhost:8001
   reverse_proxy /admin/* localhost:8001
   file_server /static/* {
      root /path/to/taiga-back
   }
   route /_protected/* {
      uri strip_prefix /_protected
      header +Content-disposition "attachment"
      file_server {
         root /path/to/taiga-back/media
      }
   }
   route /media/exports/* {
      header +Content-disposition "attachment"
      file_server {
         root /path/to/taiga-back
      }
   }
   route /media/* {
      uri strip_prefix /media
      reverse_proxy localhost:8003

   }
   reverse_proxy /events* localhost:8888
}
```
Comparing with the nginx configuration there are a few paths missing: `/_protected` and `/media/exports` for which I don't know what `add_header Content-disposition "attachment";` refers to and how to make an equivalent configuration. I suspect that in caddy the header can be added using `route` and `header`, but I don't know what `attachment` header is there. I have added my attempt there, but I am still unable to access attachments.

~~After fixing that and the `taiga-events` issue referenced above,~~ we can refine the `Caddyfile` to be equivalent with the nginx one, e.g. whether `proxy_redirect off;` is needed and what equivalent is there.

**Comment by tanc** [comment]
I've just installed Taiga 6 using the the official Docker method but with Caddy (v2) in front to reverse proxy requests back to the containers. Everything seems to work fine with a very simple caddy file:

```
mycustomdomain.net {
  reverse_proxy 127.0.0.1:9000
}
````

As Caddy is just a reverse proxy to the nginx container I think the more complex set up is already taken care of in nginx. I've only just started using it so I'll report back if there are any problems.

**Comment by LecrisUT** [comment]
Yes, if it's used as a reverse proxy, these issues aren't applicable. However, I would like the installation guide to have alternative web servers, and since Caddy is the easiest to setup and understand the configuration file of, I want to find the proper configuration for everyone to use.

I've updated the title of this issue to better reflect this.

**Comment by LecrisUT** [comment]
@yamila-moreno In the end have you managed to get the caddy path to work?
When I try to access an attachment the page does not redirect. Here's the console log for the fetch request (slightly edited for anonymity):
HTTP request:
```
await fetch("https://taiga.example.com/media/attachments/d/f/6/8/7cc95ba71f8dafc1fed51b2d26b2c927aff486fd29c1970211bc2e0fe24c/screen-shot-2021-02-12-at-152053.png?token=YCoRJQ%3APdRr0R29XeqUf-Pu-gXWWKXmPEHxqXItQTGZsCVJcr_cXaQttriTXhAbFJWAui0wOAfOp0AXPGKFyxy6RVmDNg#_taiga-refresh=issue:5", {
    "credentials": "omit",
    "headers": {
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:85.0) Gecko/20100101 Firefox/85.0",
        "Accept": "image/webp,*/*",
        "Accept-Language": "en,en-US;q=0.5",
        "Pragma": "no-cache",
        "Cache-Control": "no-cache"
    },
    "referrer": "https://taiga.example.com/project/test-test/issue/1",
    "method": "GET",
    "mode": "cors"
});
```
Request Header:
```
GET /media/attachments/d/f/6/8/7cc95ba71f8dafc1fed51b2d26b2c927aff486fd29c1970211bc2e0fe24c/screen-shot-2021-02-12-at-152053.png?token=YCoRJQ%3APdRr0R29XeqUf-Pu-gXWWKXmPEHxqXItQTGZsCVJcr_cXaQttriTXhAbFJWAui0wOAfOp0AXPGKFyxy6RVmDNg HTTP/1.1
Host: taiga.example.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:85.0) Gecko/20100101 Firefox/85.0
Accept: image/webp,*/*
Accept-Language: en,en-US;q=0.5
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Referer: https://taiga.example.com/project/test-test/issue/1
Pragma: no-cache
Cache-Control: no-cache
```
Response Header:
```
HTTP/2 200 OK
date: Mon, 15 Feb 2021 06:14:14 GMT
server: Caddy, gunicorn/19.9.0
x-accel-redirect: /_protected/attachments/d/f/6/8/7cc95ba71f8dafc1fed51b2d26b2c927aff486fd29c1970211bc2e0fe24c/screen-shot-2021-02-12-at-152053.png
content-length: 0
X-Firefox-Spdy: h2
```
Response: (empty)
Image as data URI: `data:image/png;base64,`

A few notes:
- If I access `taiga.example.com/_protected/attachments/d/f/6/8/7cc95ba71f8dafc1fed51b2d26b2c927aff486fd29c1970211bc2e0fe24c/screen-shot-2021-02-12-at-152053.png` directly with no header I am able to get the file. Probably this is not intended and this is what `internal` is supposed to solve.
- `X-Accel-Redirect` is set and received from `taiga-protected`
- I suspect that we need to add a `handle_response` in the `/media/*` block until these are implemented by default. As soon as caddyserver/caddy#3712 is merged I will try to fiddle around and see what can be done there.
- The `content-disposition` is set correctly with `header +Content-disposition "attachment"`

Could you show me how the web-console would look like when a proper nginx configuration is setup? Particularly, what is the next request look like after this fetch command, and is it possible to manually `GET` the attachment from the `/_protected/...` path?

**Comment by yamila-moreno** [comment]
Hi @LecrisUT ! I didn't as you can see in the caddy forum. I opened the issue, and get as far as I could but there are some directives that are not directly implemented and I didn't get to the solution.

As a workaround, you could use your Caddy as the proxy server and TSL manager, and redirect to a nignx with the working configuration.

**Comment by LecrisUT** [comment]
Ok. Francis over at caddy provided a very elegant solution which should be possible in an upcoming version.
```
reverse_proxy localhost:8003 {
	handle_response header X-Accel-Redirect {
		root * /path/to/back/media
		header Content-Disposition "attachment"
		rewrite {http.response.header.X-Accel-Redirect}
		file_server
	}
}
```
Once it is available, I will test and update the configuration in this issue and ping you for revision if it's ok. In the meantime I believe a version without `_protected` can be published. Maybe the documentation can be improved to have the different implementations in the comment and then provide both Nginx and Caddy there. Here's my draft for now and I leave it to you guys to reformat the documentation accordingly
```
taiga.example.com {
	# General configurations
	encode gzip zstd

	# Forward all basic paths to taiga-back
	@taiga-back path /admin/* /api/*
	handle @taiga-back {
		reverse_proxy 127.0.0.1:8001
	}

	# Serve public attachments directly with appropriate header 
	handle /media/exports/* {
		header +Content-disposition "attachment"
		root * /path/to/taiga-back
		file_server
	}

	# Serve all other media files through taiga-protect or directly
	# If taiga-protected is used switch the following directive with the commented one
	# Temporary note: taiga-protected integration is not yet possible in Caddyfile. Wait for caddyserver/caddy#3712
	handle /media/* {
		root * /path/to/taiga-back
		file_server
	}
#	handle_path /media/* {
#		reverse_proxy localhost:8003 {
#			# Nginx's X-Accel-Redirect has to be manually implemented here
#			handle_response header X-Accel-Redirect {
#				root * /path/to/taiga-back/media
#				header Content-Disposition "attachment"
#				rewrite {http.response.header.X-Accel-Redirect}
#				file_server
#			}
#		}
#	}

	# If taiga-events is installed uncomment this next section
#	reverse_proxy /events* localhost:8888

	# All other paths
	handle {
		@backend path /static/*
		root @backend /path/to/taiga-back
		root * /path/to/taiga-front/dist
		try_files {path} {path}/ /index.html
		file_server
	}

	# Optional: Write the logs to file
	log {
 		output file /path/to/caddy.log
	}
}
```

**Comment by yamila-moreno** [comment]
Hi @LecrisUT ! I agree that we could add the caddy implementation when it's ready, so it can be fully compilant with nginx and the current needs of Taiga. 

I'm closing the issue by now, and we'll be happy to review when the upcoming version is available and we can offer a complete configuration.

Thanks for your contribution!
