### ISSUE TITLE
taiga.io: WYSIWYG markdown editor can get too wide

### ISSUE THREAD

**Issue by jktjkt** [taigaio/taiga-front#2172]
**Describe the bug**
The new markdown editor *and* the markdown renderer can become too wide for (some) old issues

**To Reproduce**
1. Go to https://tree.taiga.io/project/jktjkt-czechlight/issue/989
2. See that the main column is too wide, and therefore one cannot close that issue.
3. When adding comment, the "Save" icon is not visible.

Fell free to add yourself whatever access you need to reproduce this; unfortunately it is not a public project.

**Taiga environment**
Taiga.io

**Screenshots**
![image](https://user-images.githubusercontent.com/2631925/107025644-04596200-67aa-11eb-9be1-9abbcbef86b3.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 81.0

**Comment by juanfran** [comment]
Thanks @jktjkt!

This bug is fixed in tree.taiga.io
