### ISSUE TITLE
Save vertical pixels (endangered species, especially on laptops)

### ISSUE THREAD

**Issue by swiss-knight** [taigaio/taiga-front#2175]
Generally speaking, vertical pixels are a scarce commodity on web browser, especially on laptop computers.

Hence,

As a laptop user, 

I'd like the Kanban to be reorganized from:    
![image](https://user-images.githubusercontent.com/19967599/107124594-2257bd00-68a5-11eb-8e3c-3f88647eb725.png)

to:    
![image](https://user-images.githubusercontent.com/19967599/107124559-e58bc600-68a4-11eb-894c-c9b059e18737.png)

in order to fully enjoy some more vertical space on the screen.

**Comment by miryamgduque** [comment]
Hi!
We also cared about the endangered species :) In fact, we thought about it, but we have plans for additional functionality that will use this second row so, we'll check it then.
Thanks for the feedback!
