### ISSUE TITLE
Garbled preformatted text: newlines are not always preserved

### ISSUE THREAD

**Issue by jktjkt** [taigaio/taiga-front#2187]
**Describe the bug**
I'm trying to use the ````` ``` `````-delimited code block (that's three backticks if it renders wrong for you). Sometimes it gets rendered correctly, sometimes the newlines are not preserved.

**To Reproduce**
1. Go to https://tree.taiga.io/project/jktjkt-netconf-cli/issue/215
2. See the wrong rendering of the second example

**Taiga environment**
This is on Taiga.io.

**Screenshots**
![image](https://user-images.githubusercontent.com/2631925/107369617-4bb15c80-6ae2-11eb-9c60-0cdd74de5c32.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 81.0

**Comment by juanfran** [comment]
Did you fixed the example? I'm seeing something different from the screenshot.

**Comment by jktjkt** [comment]
Nope, must have been fixed upstream.
