### ISSUE TITLE
Integrate keyboard navigation

### ISSUE THREAD

**Issue by saelfaer** [taigaio/taiga-front#219]
many tools we use integrate keyboard navigation to some degree.

the new google drive layout has full keyboard navigation

code repository sites like github / bitbucket have it in a way you can navigate to the specific pages, like the following shortcuts from bitbucket:
- `r` + `i` takes you to the issues page
- `x` + `p` takes you to the create pull request page
- `f` allows you to search
- ...

tools like trello which is very similar to Taiga, offers a vast range of keyboard shortcuts, many of which should be very useful in taiga too, to shorten time spent doing repetitive tasks.
- `space` while hovering over a US, assign yourselve to the ticket
- `arrowkeys` to navigate a kanban board
- `return` open an issue
- ...

I'm sure a few basic commands could get a keyboard key assigned to them. but I'm also aware that full keyboard navigation is not done overnight. and requires both UX, a little Design, a bit more coding and lots of analysis to get it right.

but I would be happy with a few commands to start with, and some more thorough implementation later on the roadmap.

**Comment by saelfaer** [comment]
to go further, i just implemented angular hotkeys in a project of mine.
and it's a breeze to work with. you can bind hotkeys to scope, controllers, routes, ...
very interesting but still a task to first define which hotkeys you want to support of course.

http://chieffancypants.github.io/angular-hotkeys/

for the reference if you ever pick up this ticket, i bet this will be the library that will help you on your way.

**Comment by superalex** [comment]
It looks great!, thank you very much :+1:

**Comment by ernestoalejo** [comment]
I am constantly trying to use `Ctrl + Enter` to save descriptions or create new items (issues, stories, etc.). Also pressing `Enter` in the autocomplete field of tags sends the whole form instead of adding the tag, and that's not intuitive at all.

**Comment by sftd** [comment]
Still extremely missing `ctrl + enter` feature.

#683 could probably be closed in favour of this one.

**Comment by cfrancois7** [comment]
Yes, it should be very nice to provide the first basic `ctrl + enter` and be patient for the other.
