### ISSUE TITLE
Ability to move US out of Sprint back into Backlog

### ISSUE THREAD

**Issue by hirusi** [taigaio/taiga-front#2195]
**Is your feature request related to a problem? Please describe.**
I accidentally clicked a button that moved all my backlog user stories into the current sprint. I cannot find any way to move those US back to the backlog.

**Any alternatives you've considered**
I've moved all US into a new Sprint called `Dummy Backlog/Sprint`, from which I drag US into current Sprint. This is not desirable.

**Describe the solution you'd like**
Just like I am able to drag and drop and assign US to a sprint, I want to be able to do the opposite, where dragging a US into the backlog should remove it from the sprint.

**Comment by miryamgduque** [comment]
Hi!
Thanks for reporting! We already have an open issue about it. You can follow it in our public project, here https://tree.taiga.io/project/taiga/issue/2640
