### ISSUE TITLE
config.json resets to defaults

### ISSUE THREAD

**Issue by unbranched** [taigaio/taiga-front#2199]
I'm using Taiga docker on Ubuntu 20.04, mapped a config.json file to /usr/share/nginx/html/conf.json and changed some values like defaultLanguage.
Since the last docker pull I did today, the config keeps resetting to defaults every time I restart the containers.
I also tried editing the file directly inside the container, but I have the same behaviour. This wasn't happening before.

**Comment by yamila-moreno** [comment]
Hi @unbranched you're totally right; it's a bug we recently introduced. We're fixing asap.

Thanks for reporting!

**Comment by yamila-moreno** [comment]
Hi @unbranched we just pushed a new taigaio/taiga-front:latest with the fix. Please, pull it again and try. It should be working as before.

**Comment by unbranched** [comment]
Yes it's fixed now, muchas gracias Yamila!
