### ISSUE TITLE
Username with specific char

### ISSUE THREAD

**Issue by Spidlace** [taigaio/taiga-front#2200]
**Describe the bug**
When a user have specific char in his username (e.g : _ ), when we tag this user and save the comment, mention is overwritten without specific char

**To Reproduce**
1. Mention user with specific char (e.g : @User_Name_Test)
2. Write comment
3. Hit save

**Taiga environment**
On Taiga.io

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser : Brave

**Comment by juanfran** [comment]
thanks @Spidlace It's already fixed in the master branch, should be fixed with next release
