### ISSUE TITLE
Rename features User Stories etc

### ISSUE THREAD

**Issue by Revenger** [taigaio/taiga-front#2204]
I'm going to be using Taiga for my home projects as out of most I looked at this is really simple and easy to use for what I want without complexity to track my home hobbies and projects.

One thing that doesn't make sence to me is the naming conventiones, User Stories, Sprints etc I worked ouit what each area does but it would be nicer if we could raname them like we can with the Kanban colums.

For me this is what my mindset is,
A epic is a collection of those areas that make up a feature.
3D printer Enclosure Complete

User stories are areas of a feature / Epic to work on.
To me this is just a feature title i'm not writing a story  description and title for every personal idea and project I have.
eg, 3D Printer Enclosure Leg work, 3d printer upgrading etc

Tasks are subs of stories this one makes the most sence as well as issues.
eg: Cut metal, drill holes etc

Sprints to me are features that are active and being worked on, im not sprinting rushing, crunching or whatever to do any task for example.

You can see from my workflow the default naming makes no sence for me.
I'm not writing a story / novel for feature headings for example, way I see user stories is users write a story, 'one day I was in the woods'.

I am thinking of editing the language and renaming everything but I hope that this can be considered for the super user admin area to be able to set custom language names for these things,

I know and read this was requested back in 2017
https://github.com/taigaio/taiga-front/issues/1211
But the request may have been turned down due to sticking with Agile naming conventions.
audreytoskin mentioned in that thread things should be more generic which I agree.

**Comment by yamila-moreno** [comment]
Hi @Revenger if you're using a self-hosted Taiga, you could create your own "Language"/translation where you can translate "User Story" for your own concept.
You need to add the new language to "LANGUAGES" in `settings/common.py` and create the corresponding locales.

Cheers!
