### ISSUE TITLE
Deploy using a path other than `/`

### ISSUE THREAD

**Issue by carneirofc** [taigaio/taiga-front#2209]
**Is your feature request related to a problem? Please describe.**

I am having issues trying to deploy the frontend with an URL other than `/` e.g. "https://localhost:9000/taiga". For my specific use case this is important, as I am using a reverse proxy on ports `443` and `80`, redirecting requests based on the url to backends of different applications.

The jade templates are using absolute paths and it seems that there is no easy way to modify it.
e.g. 
https://github.com/taigaio/taiga-front/blob/master/app/index.jade#L14

If we had something like this, the issue could be solved.
```javascript
link(rel="stylesheet", href="#{baseUrl}/#{v}/styles/theme-taiga.css")
```
Is there another way I could implement this behaviour?

**Comment by juanfran** [comment]
Duplicate https://github.com/taigaio/taiga-front/issues/492 (there is workaround here)

Right now we can't do it because some problems related to angularjs, I'll keep this issue open to keep it in mind while we a upgrading the taiga tech.

Thanks

**Comment by teotikalki** [comment]
AngularJS is EOL, so is this particular upgrade a priority (ie. currently ongoing)? Anywhere that I could look at the progress/test/etc? I've been wanting to use Taiga for a few years now and this is my blocker.

**Comment by juanfran** [comment]
> AngularJS is EOL, so is this particular upgrade a priority (ie. currently ongoing)? Anywhere that I could look at the progress/test/etc? I've been wanting to use Taiga for a few years now and this is my blocker.

Yes it's a priority and its ongoing, we're currently working on it but it's a lot of work so it will to take a while. You can see some of the work here https://github.com/taigaio/taiga-front-next but right now most of the progress is private.

**Comment by juanfran** [comment]
Finally we've found a way to do it in Taiga 6.3.1, so you can change de `baseHref` in your `config.json` and in the index.html also if your using docker you have to change the TAIGA_SUBPATH variable.
