### ISSUE TITLE
Link to contribution guide under contributing guidelines page is 404

### ISSUE THREAD

**Issue by SimplifyAndAddCoffee** [taigaio/taiga-front#2217]
https://github.com/taigaio/taiga-front/blob/608cce11dc9d9f4fb15c56e8130fff8c67f0e79f/CONTRIBUTING.md

links to: https://resources.taiga.io/how-can-i-contribute

which gives me a 404

**Comment by Xaviju** [comment]
This is the correct URL: https://resources.taiga.io/extend/how-can-i-contribute/

**Comment by Xaviju** [comment]
Fixed [in this commit](https://github.com/taigaio/taiga-front/commit/7af9c0aa6310a418ce82d56f8b1755702d55d3ec)
