### ISSUE TITLE
UI layout in Safari is slightly broken

### ISSUE THREAD

**Issue by ss-abramchuk** [taigaio/taiga-front#2220]
**Describe the bug**
Some UI elements in Safari are too close to each other. For example, on the Project Timeline tags and buttons (like, watching, contact) don't have spaces between them. The same true for icons in the project list on the Projects Dashboard screen and tags on User Story screen.

Also "Number of US" on Kanban screen located incorrectly (under user pic), settings icon on left side menu is cut off, and on the "New Project Details" screen icon and title (Kanban, Scrum) are not aligned correctly.

**To Reproduce**
Steps to reproduce the behavior (should be performed in Safari):

1. Create new project.
2. Select "Kanban" or "Scrum" and check alignment of the title and icon.
3. Go to the Timeline and check arrangement of buttons (like, watching, contact).
4. Go to "Kanban" and check location of "Number of US".
5. Create new User Story.
6. Add a few tags and check their arrangement.
7. Take a look at the lower left corner where settings menu item located and check size of the icon.

**Expected behavior**
Layout arranged correctly and everything is on its place.

**Taiga environment**
Checked on Taiga.io and a self-hosted Taiga (installed using docker images).

**Screenshots**
![slice](https://user-images.githubusercontent.com/7886854/110314206-9efec800-8018-11eb-9fde-48a02ef910b2.png)

**Desktop (please complete the following information):**
 - OS: macOS 11.2.2
 - Browser: Safari 14.0.3
 - Taiga Version: 6.0.6

**Comment by Xaviju** [comment]
This is fixed and ready for deployment (will be available next week).
https://github.com/taigaio/taiga-front/pull/2234

**Comment by ss-abramchuk** [comment]
Hi @Xaviju,

I'm afraid there is one issue left, US counters still located under the user icon instead of kanban columns.

<img width="486" alt="us-counter" src="https://user-images.githubusercontent.com/7886854/119217731-d263d580-bae4-11eb-8d07-d94e69da889a.png">

**Comment by Xaviju** [comment]
Hi @ss-abramchuk this is already reported and being tracked here https://tree.taiga.io/project/taiga/issue/4523
