### ISSUE TITLE
UI Layout for the Epics view slightly broken under 1140px width

### ISSUE THREAD

**Issue by msouabni** [taigaio/taiga-front#2222]
**Describe the bug**
The "view options" below the table overlay the table header.

**To Reproduce**
1. Activate Epic Module for the project
2. Go to 'Epics'

**Expected behavior**
The position of "view options" need to be modified to avoid overlaying the table header.

**Taiga environment**
Are you using Taiga.io or a self-hosted Taiga? Taiga.io

**Screenshots**
![image](https://user-images.githubusercontent.com/8258515/110486457-f40c0e00-80ec-11eb-85bb-44b0eb4a5b60.png)

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 20
 - Browser Chrome & Firefox

**Comment by Xaviju** [comment]
Thanks for reporting, we are reviewing it.

**Comment by NatachaMenjibar** [comment]
Hello!

This has been fixed an it will be in production in the next patch release.

Thanks!
