### ISSUE TITLE
Responsive for Mobile browser 

### ISSUE THREAD

**Issue by krswin** [taigaio/taiga-front#2227]
**Is your feature request related to a problem? Please describe.**
Sometimes wants to use Taiga on mobile its not possible due to not being responsive according to device size. 

**Describe the solution you'd like**
Support for small devices/Mobile phone browsers. 

Thank you very much.

**Comment by miryamgduque** [comment]
Hi!
We plan to get into it, but it's part of our long-term roadmap.
However, can I ask you what info you would like to consult from your mobile phone?

**Comment by krswin** [comment]
@miryamgduque  Thanks for consideration. 
From mobile phone Its good to have below features:

1. To see the board (it can be horizontal and vertical scroll.)
2. To create new tickets

it would be good if you can plan for this year this things.
Thank you.

**Comment by miryamgduque** [comment]
Thank you! Maybe I try to contact you in the future to ask you some questions about it.
