### ISSUE TITLE
Missing Gherkin code formatter in the last Taiga release

### ISSUE THREAD

**Issue by gabbork** [taigaio/taiga-front#2229]
**Describe the bug**
In the description editor, the Gherkin formatter is missing after the update to the last version of Taiga

**To Reproduce**
1. Go to US editor
2. In the html mode, click on "Insert code block"
3. In the select, you can't see "Gherkin" option
4. Even if you insert it in markdown mode: \` \` \` Gherkin   .... \` \` \` it will not work

**Expected behavior**
Find the Gherkin code formatter, as in the previous version of Taiga

**Taiga environment**
Taiga self-hosted, with docker

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser firefox
 - Version 83.0

**Additional context**
No additional context

**Comment by juanfran** [comment]
thanks @gabbork It's already fixed in the master branch, should be fixed with next release
