### ISSUE TITLE
Assign To List

### ISSUE THREAD

**Issue by teamcoltra** [taigaio/taiga-front#223]
It looks like you can view all your assigned issues but not userstories and related tasks, is there any way to see just what you are tagged in?

**Comment by superalex** [comment]
Not actually but we plan rebuilding the user home and probably that info about your assigned "things" should appear there.

Regards

**Comment by teamcoltra** [comment]
Is there a bounty program? I would probably be willing to contribute to the bounty if there was. For now what I do is create an issue for each team member which links to all the tasks they are responsible for.

**Comment by superalex** [comment]
Thanks @teamcoltra it seems like a good workaround while we develop the noe home. About the bounty program what we have now is documented here: https://taiga.io/support/making-donations-to-taiga/

Thank you very much! :+1:

**Comment by Xaviju** [comment]
There is already a WORKING ON dashboard showing all your Stories, tasks and issues you are assigned to.
