### ISSUE TITLE
Moving user story on kanban does not update state to open or closed

### ISSUE THREAD

**Issue by alsace68347** [taigaio/taiga-front#2235]
Hello,

**Describe the bug**
I don't know if it's a bug or if I missed something,  but user story  "Open" or "Closed" state are not update when moving card on Kaban, but are update when i change status  with dropdown list in the user story.

**To Reproduce**
1. create an project with two user story. 
2. move one to "Done" on the kanban. Status is done but state is Open
3. Edit the second user story. Change status to done using the dropdown list. Status is done and state is Closed. 

It's the same when moving user story from "Done" to another status. State stay to "Closed" if you move on Kanban. State change to "Open" with the dropdown list. 

**Expected behavior**
Moving user story on kanban must update  "Open" and "Closed" state as if if  status is change with the dropdown list. 

**Taiga environment**
I am using your latest docker version. 

**Desktop:**
Same issue with firefox (87) and chrome( 89) 
    
Thanks

**Comment by yamila-moreno** [comment]
Hi @alsace68347 If I'm correct, this is the same bug as [this one](https://tree.taiga.io/project/taiga/issue/4414). It's already in master and will be released next week.

If it's a different one, please, feel free to reopen it. Cheers!
