### ISSUE TITLE
[enhancement] Create a realtime view in the taskboard

### ISSUE THREAD

**Issue by FlorianBezagu** [taigaio/taiga-front#224]
We are 10 developers working on the same project on Taiga and frequently we have conflicts when we want to update some tasks because there is no realtime in the taskboard.

It would be so great if it exists. It's a real problem for us everyday.

**Comment by jespino** [comment]
Already exist a websockets based realtime updates system. Are you using your own instance or the tree.taiga.io service?

**Comment by FlorianBezagu** [comment]
We use our own server.

Yes it's realtime when we create a task, if refreshes all the taskboard (Saw a TODO in your code saying it's maybe too much too reload all the taskboard each time)

But when creating or updating on my computer, it does not update or create on my colleagues computer until they create or update at least one task.

**Comment by jespino** [comment]
You have to configure taiga-events (Isn't documented yet).

You have to clone the taiga-events repository, copy the example.conf.py to config.py, edit it with your configuration (you must edit the dbname in repo_conf and queue_conf, and the secret to the same of the taiga-back settings/local.py).

Then, you have to run it with python run.py -f config.py.

Done this, you have to configure the taiga-front to use the taiga-events server changing the config file of taiga-front, the variable eventsUrl to ws://taiga-events-server-name-or-ip:port

The default settings of the taiga-events use postgresql pub/sub system (NOTIFY). But can be configured to use RabbitMQ.

You can try this working on the tree.taiga.io instance.

**Comment by FlorianBezagu** [comment]
Very interesting ! I'm going to try it asap !
Thanks

**Comment by gaikwad411** [comment]
Hi,
   I also have same requirement. 

  I have tried the solution given by @jespino, but notifications are not working.

   I have installed the required dependencies including tornado and after starting taiga events 
gave me message "Now listening on: http://127.0.0.1:8888", according to this I changed the "eventUrl" to "ws://127.0.0.1:8888".
 
  Please let me know if I am missing something. 
Thanks

**Comment by jespino** [comment]
Hi,

Have you recompiled the taiga-front? (any change in the configuration
require a new compilation).

Regards.

**Comment by gaikwad411** [comment]
Yes did that, But changing "eventsUrl" from "ws://127.0.0.1:8888" to "ws://127.0.0.1:8888/events" solved the problem. Now notifications are working.. 
Thanks

**Comment by FlorianBezagu** [comment]
When running :

```bash
python2 run.py -f config.py
```

I have this error :

```bash
Traceback (most recent call last):
  File "run.py", line 2, in <module>
    from taiga_events.main import main
  File "/home/taiga/taiga-events/taiga_events/main.py", line 23
    def make_app(config:dict) -> Application:
                       ^
SyntaxError: invalid syntax
```

@jespino : I did exactly what you said.

**Comment by FlorianBezagu** [comment]
Hi @jespino,

When I run `python run.py -f config.py`, the event server is running in my terminal.

What can I do to launch it at boot as a daemon ?

**Comment by jespino** [comment]
Hi @FlorianBezagu,

You can configure it in your circus configuration like the taiga-back service.

**Comment by RobertoGongora** [comment]
You gave detailed instructions to run this on a self hosted environment, but what if I'm using the tree.taiga.io service? Is there a way to enable it?

**Comment by superalex** [comment]
We were having problems with the configuration in tree.taiga.io so it's not on right now, we will enable it soon.

Regards!,

**Comment by dpipkin** [comment]
Is there still a timeline on implementing it in tree.taiga.io? My coworker and I were just talking about this.

**Comment by superalex** [comment]
Hello @dpipkin 

Realtime view is working from a long time ago :), it's actually working on backlog, kanban, taskboard and issues views

Regards!

**Comment by hwinkel** [comment]
hhm. just tried at tree.taig.io but the realtime view lags behind one movement in Kanban view in two different windows of a Chrome browser

**Comment by tititestor** [comment]
Same as hwinkel,
the realtime view lags behind one movement in Kanban view in two different windows of a Chrome browser

Best regards

**Comment by bameda** [comment]
We fixed a bug related with this some time ago. Can you upgrade to the last version?
