### ISSUE TITLE
Taiga isn't displaying screenshots or code blocks for users who are not logged in

### ISSUE THREAD

**Issue by K1D77A** [taigaio/taiga-front#2240]
Hi,

I have created a wiki page for my project and I have set it so that anonymous users can view it, however when I use a private browsing window to view my page none of the screenshots or the code blocks are loading. 

What it looks like logged in.
![image](https://user-images.githubusercontent.com/10334164/113791262-2a17ce80-973b-11eb-9baf-8c0bfb075528.png)

Now using private browsing
![image](https://user-images.githubusercontent.com/10334164/113791308-4156bc00-973b-11eb-986a-778bb3d5b0f2.png)

A screenshot of my wiki permissions:
![image](https://user-images.githubusercontent.com/10334164/113791374-61867b00-973b-11eb-93e9-0ee587f1b31e.png)

Any help would be greatly appreciated.
Thanks.

**Comment by Xaviju** [comment]
Hi @K1D77A 

Are you using Taiga.io or a self-hosted Taiga?
If self-hosted, is it installed with docker or from source code?

**Comment by K1D77A** [comment]
Hi, 
Thanks for the response.
This is a self hosted instance that has been installed through docker.

**Comment by K1D77A** [comment]
Fixed it. Sorry for the inconvenience. Sys admin performed an update.

**Comment by Xaviju** [comment]
Thanks @K1D77A
