### ISSUE TITLE
Has voting been removed?

### ISSUE THREAD

**Issue by mgmorcos** [taigaio/taiga-front#2242]
In Taiga 6 on-prem via the docker deployment scripts, I do not see upvoting/downvoting functionality for Issues. Has voting been removed?

**Comment by miryamgduque** [comment]
Hi!
Indeed, we have removed the votes because our data indicated that practically no one used them. However, the idea that users can participate showing their interest is still interesting, so we are rethinking a better way to do it, that offers the best experience.

Thanks for your feedback!
