### ISSUE TITLE
Estimate time field needed for completing a story and a task 

### ISSUE THREAD

**Issue by travelg** [taigaio/taiga-front#2244]
**Is your feature request related to a problem? Please describe.**
Field to write estimate the time to complete a Story or a task is missing.

**Describe the solution you'd like**
When try to estimate Story and a Task there should be one field to estimate the time needed to finish Story or a Task. 
Example Like 5 Hours/10 Hours

**Describe alternatives you've considered**
Should be one field in Story and a Task where we can define how much time will be needed to complete the task.

**Comment by Xaviju** [comment]
Hi @travelg,

Does [user story estimation](https://resources.taiga.io/features/introscrum/#scrum-backlog) not work for you? What's the problem? 
What about custom fields? https://resources.taiga.io/faqs/settings-customfields/

**Comment by travelg** [comment]
@Xaviju Thanks for reply. i can not find it for kanban mode. i just want to estimate the stories in kanban mode with time in hours. thanks.

**Comment by Xaviju** [comment]
Hi @travelg 

You should be able to estimate user stories on kanban. By default, all user stories have `points` which is a generic name for anything, it could be hours. To edit its possible values you should go to `settings > Attributes > points`

In the kanban view, using the `detailed` or `expanded` zoom level you can view the selected estimation in the card and in the user story detail.

If it does not work for you, you can also use the `due date` option. Set a due date in the user story detail, and it will appear on the card.

Do this work for you?

**Comment by Xaviju** [comment]
Closing this story due to its inactivity, please reopen if needed
