### ISSUE TITLE
Double-quoting of task "title" 

### ISSUE THREAD

**Issue by micw** [taigaio/taiga-front#2247]
**Describe the bug**

When creating a task that contains special characters like < and >, the page title contains &gt; &lt;

**To Reproduce**

1. Create a story with a task containing <> in title
2. Open the task detail view
3. Look at the browser title

**Expected behavior**
Title should contain <>

**Taiga environment**
Cloud at tree.taiga.io

**Screenshots**
![image](https://user-images.githubusercontent.com/186753/114674673-c592db80-9d07-11eb-8fa9-2fb8091b3117.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version latest stable

**Comment by Xaviju** [comment]
Thanks for reporting, we'll look into it and as soon as we can, we will get back to you.

**Comment by Xaviju** [comment]
This is fixes and will be released soon in version `6.0.11`
