### ISSUE TITLE
webhooks don't work 

### ISSUE THREAD

**Issue by flover97** [taigaio/taiga-front#2248]
I configured the webhook to integrate with zulip and it passes the test button, also in the zulip I see a test message. When I try to create a task in Kanban or assign a user to it, the system does not use the webhook (there is nothing in the history) and, accordingly, nothing comes to the zulip. 

Taiga 6.0.9 self-hosted

 in config.py:
```
WEBHOOKS_ENABLED = True
```
the logs are no errors.

![изображение](https://user-images.githubusercontent.com/17098761/114872866-62866f00-9e03-11eb-8efd-cb9c358416d6.png)

**Comment by erikmyrsell** [comment]
I had the same issue. Try setting in config.py:

`CELERY_ENABLED = False`

If you use docker to set it up try setting in docker-compose.yml:

`CELERY_ENABLED: "False"`

After some ugly custom logging I concluded that CELERY_ENABLED defaults to True if it is not set which it was not in my case. Therefore the _execute_task function in the /taiga-back/taiga/webhooks/signal_handlers.py tries to execute the task change_webhook in  /taiga-back/taiga/webhooks/tasks.py with a delay:

`task.delay(*webhook_args)`

But the task change_webhook never executes.

**Comment by talheim-it** [comment]
@flover97 you need to check the async part as @erikmyrsell wrote. If that service is not running, it won't work.

**Comment by flover97** [comment]
> @flover97 you need to check the async part as @erikmyrsell wrote. If that service is not running, it won't work.

Thank you, I fixed it a long time ago and was so happy that I forgot to unsubscribe :)) the problem was in the celery
