### ISSUE TITLE
[Bug] Can't load user stories with Firefox

### ISSUE THREAD

**Issue by Chaostheorie** [taigaio/taiga-front#2256]
## Problem

When opening a user story with Firefox, the view won't load any content beyond the title. After some digging, this seems to be due to the UI not including the ref when fetching the user story details on page load. Specifically, the GET `ref` param is missing.

## Mitigation

The frontend will include the ref when using Chromium, or a Chromium-based browser, for some reason. I couldn't trace it back, but it just does it.

## MRE

- You need a Mozilla Firefox browser / and a user story 

- Open the user story in a Mozilla Firefox browser and see an empty description, status and attachment
- Using dev tools, you will find that a request to `https://<instance>/api/v1/userstories/by_ref?order_by=kanban_order&project=<project id>&status=1` will have been made and handled with a 400 Error by the API

## Environment

- New, clean Taiga Instance from docker:latest. No other functions are degraded
- Found to be a problem on both Mozilla Firefox ESR and at least Mozilla Firefox 94.0.2
- OS: EndeavourOS / Linux 5.10.82-1-lts x86_64 /

**Comment by Chaostheorie** [comment]
Has resolved itself in Firefox 95.0

**Comment by thelazyoxymoron** [comment]
I'm still seeing this on Firefox 104.0.2. Working fine in Chrome.

**Comment by Chaostheorie** [comment]
I'm not using taiga anymore personally and don't self-host an instance anymore. However user stories worked for me (see below for client, has changed from before) on the official taiga instance. My test user story was https://tree.taiga.io/project/c0balt-test-project/us/1.

---
Client:
- Firefox 104.0.2 (64-bit) (Firefox for openSUSE)
- openSUSE Tumbleweed (date: 21-09-22) / 5.19.8-1-default

**Comment by thelazyoxymoron** [comment]
Thanks. The attached test user story seems to work for me as well. This seems to be an issue with self-hosted version only.
