### ISSUE TITLE
Taskboard is re-painting itself continuously

### ISSUE THREAD

**Issue by EtienneRd** [taigaio/taiga-front#229]
Using chrome 39.0

If you leave a taskboard opened in Chrome, you'll notice that chrome is taking some unexpected load of CPU.

If you open the Developer Tools and inspect the Timeline of events, you'll notice that the Taskboard is continuously re-calculating the layout and re-painting itself.

Temp fix is to open a new tab, and return to the taskboard tab only when you need to.

![screen shot 2015-01-09 at 11 26 35](https://cloud.githubusercontent.com/assets/1311726/5678441/cb27ae16-97f2-11e4-80af-488839abf9d9.png)

**Comment by juanfran** [comment]
We found the problem and it should be fixed, thanks!!
