### ISSUE TITLE
https://tree.taiga.io/register, it works under Opera, but not firefox with noscript.

### ISSUE THREAD

**Issue by timoc** [taigaio/taiga-front#231]
I'd like to try it out, but https://tree.taiga.io/register, it works under Opera, but not firefox. I use noscript on one but not the other.

I assumed noscript was the problem and tried adding a filter to the cross site scripting manager:
```
^https?://([a-z]*)\.?taiga.io/[^"'<>\?%]+$
```
Still no luck. 

When i look at the source, i see that some Django templates have not been processed.

```
  <div tg-lb-create-project class="wizard-create-project">
      <form>
        <section data-step="step1" class="wizard-step create-step1">
          <div class="title">
            <h1>Choose a template</h1>
            <p>Which template would fit better in your project?</p>
          </div>
          <div class="template-wrapper">
            <div class="template-inner">
              <fieldset ng-repeat="template in templates">
                <input type="radio" name="template" id="template-{{ template.id }}" ng-value="template.id" ng-model="data.creation_template" data-required="true">
                <label for="template-{{ template.id }}" class="backlog"><span class="icon icon-backlog"></span>
                  <h2>{{ template.name }}</h2>
                </label>
                <p>{{ template.description }}</p>
              </fieldset>
            </div>
          </div>
          <fieldset><a href="" title="Next" class="button-next button button-green">Next</a></fieldset>
        </section>
```

**Comment by niwibe** [comment]
Hi @timoc 

You can not use taiga with noscript, because taiga frontend application is build interelly in javascript.

The snippet of html that are you show, is not django template, is angularjs template, and is processes  on client side with javascript.

**Comment by timoc** [comment]
Noscript allows me to 'turn on' javascript permissions for domains. I did a quick census of angular sites, from  https://builtwith.angularjs.org/, (it also works with noscript) and when i enable scripting on these  other AngulaJS built sites they seem to work.

Maybe there are some off site resources i need to whitelist?

**Comment by superalex** [comment]
Hi @timoc  your filter seems to be right (^https?://([a-z]*)\.?taiga.io/[^"'<>\?%]+$), I don't know if noscript logs the resources it's blocking, it could be an idea.

Regards,

**Comment by timoc** [comment]
I've been looking into it and it seems to be related to local storage
```
Error: TypeError: localStorage is null
Source File: https://tree.taiga.io/js/app.js?v=1430849908242
Line: 15
```

In firefox, if you select the lock symbol beside the url (tree.taiga.io), you can change the default security permissions for a site. In this case setting  'set cookie' and 'maintain offline storage' from the default to 'allow' would normally fix the issue of not being able to create client side permanent html5 storage.

**Comment by superalex** [comment]
Thanks @timoc
