### ISSUE TITLE
Contrast is too small in some parts of the app

### ISSUE THREAD

**Issue by dimaursu** [taigaio/taiga-front#232]
http://i.imgur.com/kEPVzJw.png
http://i.imgur.com/jH3Ugl7.png
Some box-shadows, or different colors would definitely help.

**Comment by Xaviju** [comment]
HI @dimaursu
**I will recheck both colors to improve contrast a bit** but compared to my screen (i just callibrated it to be sure) it looks that your screen is too bright and you are loosing some contrast between background and text.

Thanks for your feedback!

**Comment by Xaviju** [comment]
We improved contrast in those areas for next release. If still happening please reopen the issue. :cool:
