### ISSUE TITLE
Better names for kanban columns

### ISSUE THREAD

**Issue by dimaursu** [taigaio/taiga-front#233]
"New" I guess it's okay, but the second one, "Ready" is quite confusing.

**Comment by jeremykossen** [comment]
Taiga's default process is fairly streamlined process. "Ready" is a pretty typical Kanban stage in Kanban development, which I find pretty useful. "Ready" simply means "ready for development". 

Great thing about Kanban is that the method does not overload team members. So we start by putting everything in our cue under New, which by itself would look VERY overwhelming. The PM then drags the tasks over to "Ready" when she assigns the tasks to the developers. The developers drag it over to "In Progress" as they're working on it. Then into "Ready for Test" when it's ready for us to make sure it works, and once it's been tested, the PM drags it over to "Done". It works very well!

Another pretty common work flow, which breaks down the workflow much further is as follows:

New -> Specification -> Ready For Development -> Development -> Code Review -> Test Locally -> Test in Pre-Production Environment -> Ready for Deployment -> Deployed

Alternately, if you want to create a very simple workflow...for example, maybe for personal tasks, it could be as simple as:

To-Do -> Doing -> Done

Keep in mind, in Taiga you can customize the workflow anyway you want. 

In our company, we're now using Taiga across departments. i.e. PR, marketing, venture/angel fundraising, etc.

For example, our workflow for VC/Angel funding is below -- we add all prospective investors into Taiga as a "story" and they go through the workflow like a "sales funnel":

New -> Outreach -> Pitch -> Due Diligence -> Committed -> Funded

Cheers,
Jeremy

**Comment by superalex** [comment]
@jeremykossen thank you very much for your answer and for sharing your workflows implementation with us :+1: 

@dimaursu you can customize the kanban column names through Admin -> Custom attributes -> US statuses
