### ISSUE TITLE
Workflow Templates [Enhancement]

### ISSUE THREAD

**Issue by jeremykossen** [taigaio/taiga-front#234]
It would be really nice to be able to create Workflow templates. We use the default Kanban workflow for most stuff we do, but we are also using Taiga across departments and functional areas (i.e. development, marketing, sales, etc.), so I find myself customizing the workflow on anything that doesn't fit neatly into the default kanban workflow.

**Comment by jeremykossen** [comment]
Alternately, another (simpler) idea is to create the ability to clone/copy a project.

**Comment by superalex** [comment]
Hello @jeremykossen 

Actually the API is supporting this feature (http://taigaio.github.io/taiga-doc/dist/api.html). It's still pending adding it to the web app. 

In case you want to use now with a bit of curl magic you could do it. From base project (one you have customized) you can do: 
- http://taigaio.github.io/taiga-doc/dist/api.html#projects-create-template to create the template from a project
- http://taigaio.github.io/taiga-doc/dist/api.html#projects-create to create the project sending creation_template with the value you received in the previous call

**Comment by jeremykossen** [comment]
Awesome! Thanks Alex.

**Comment by superalex** [comment]
You are welcome! @jeremykossen :)

**Comment by meshane** [comment]
I cloned an existing project just by exporting it and reimporting it, as a pretty simple alternative.

**Comment by Xaviju** [comment]
Nice alternative @meshane :sunglasses:
