### ISSUE TITLE
All Projects Backlog [Enhancement]

### ISSUE THREAD

**Issue by jeremykossen** [taigaio/taiga-front#235]
We're now managing multiple projects on Taiga. One shortcoming is that you have to go into each individual project to view the backlog for that project. It would be great if on the User Homepage / Dashboard, there was a way to view your backlog for All Projects.

**Comment by superalex** [comment]
Thanks @jeremykossen  we are currently rethinking the user homepage so your feedback is really usefull ;)

**Comment by leftbrasil** [comment]
We have the same problem. Up voting :)

**Comment by cm-cita** [comment]
+1
