### ISSUE TITLE
Counter-agent to "Iocaine"; Maybe "Panacea"

### ISSUE THREAD

**Issue by mackaltman** [taigaio/taiga-front#239]
While I believe the iocaine to be a rather cute, and original, touch, which makes the end-user feel like their dealing with someone more human. As an IT professional, I know sometimes I would get really happy about clicking this. In reality, those submitting issues may interpret high usage of this feature to be insulting. They may ask their coworkers, "Does Mack ever click the poison when you submit an issue? I think he doesn't like me, because he always does it when I submit an issue."

As childish as it may seem, I feel another great addition would be a "positive" sign. For example, I may start to notice the user is learning from my feedback and starts to improve in the way they submit an issue. By clicking something "positive", this could let them know I'm aware they are trying to do better. "panacea" would be a great counter-agent.

**Comment by superalex** [comment]
Thank you very much for your suggestion @mackaltman.

Our idea after iocaine concept wasn't exactly  to mean a "bad thing". Our idea is that the team mark some items as "iocaione" when it means they are reaching beyond their comfort zone by taking a dose or two of this potion. No pain, no gain. It's related to the concept of going out of your control zone but not in a crazy way (you can monitor how many doses are you taking). 

The team member who is taking care of the poisoned item should be the one deciding if it's iocaine or not, for you a task could be trivial (not iocaine) and really difficult for me (a lot of iocaine). 

Regards!,
