### ISSUE TITLE
Question: How to add User Stories (or Related Tasks) to Sprints?

### ISSUE THREAD

**Issue by SpacyRicochet** [taigaio/taiga-front#241]
This might be because I'm too unfamiliar with the SCRUM method, but I don't get how we are supposed to add User Stories to the sprint we're currently working on.

User stories that we created in the Backlog screen (and assigned points to) don't show up in the Sprint Taskboard of the Sprints that we created in the Backlog screen. Since the Sprint Taskboard does mention Task, we tried creating a couple of Related Tasks in a User Story, but those do not show up either.

I'm either confused on how SCRUM is supposed to work, or how Taiga implements SCRUM. Or this is a bug, but I'm pretty sure I would've seen an open issue about it then. Any help?

**Comment by superalex** [comment]
Hi @SpacyRicochet ,

The way you assign user stories to a sprint is from the backlog view using drag&drop. Then in the sprint taskboard you can create their associated tasks.

Regards,

**Comment by SpacyRicochet** [comment]
Thanks! Improvement suggestion on its way :)

**Comment by Xaviju** [comment]
@SpacyRicochet just to complete the answer from @superalex, you can also select the checkbox on the left side of the US in backglo and click on 'Move to current Sprint' button. :smile:

**Comment by daao87** [comment]
Hi @superalex,

Related with this issue, I've been trying to keep user stories in the backlog, even if they have been moved to a sprint. I think this feature is useful when the product owner or any member of the team wants to see ALL the user stories (no matter their status) in ONE place. Is this feature available or has to be implemented?

Thanks.

**Comment by superalex** [comment]
Hello @daao87,

It's not implemented but you could have a possible workaround. Using the csv-reports feature (https://taiga.io/support/csv-reports/) you could create any custom report you need about your project user stories. You can find an example video here -> https://www.youtube.com/watch?v=tdt7nqXVf_E

Regards!,
