### ISSUE TITLE
Improvement: When dragging a User Story to a Sprint, use the entire Sprint box to accept drag.

### ISSUE THREAD

**Issue by SpacyRicochet** [taigaio/taiga-front#242]
Currently, you can only drag User Stories to a very small area when there are no assigned user stories yet. This hurts discoverability of the feature and is confusing, because you *do* end changing the order of the user story if you let the story go at the wrong point.

Using the entire box of the Sprint to accept dragged User Story would improve this. To account for dragging the User Story in-between other Stories, you can always add Stories to the end or front of the queue when they're not dragged directly in the queue of stories.

**Comment by superalex** [comment]
Thanks for your suggestion @SpacyRicochet

**Comment by zeigerpuppy** [comment]
+1 for this, it's logical to try to just drag the US to the right and difficult to do with a long list at the moment

**Comment by superalex** [comment]
Pull request on https://github.com/taigaio/taiga-front/pull/255
