### ISSUE TITLE
When collapsing statuses in a Sprint Taskboard, statuses more to the right disappear.

### ISSUE THREAD

**Issue by SpacyRicochet** [taigaio/taiga-front#244]
When collapsing statuses in the Sprint Taskboard (for example, because I want to drag something to 'Needs info', but needs info is very far away) 'Needs Info' actually disappears. 

Using latest Safari on updated OS X.

**Comment by superalex** [comment]
Thank you very much @SpacyRicochet,

Could you pleass add and screenshot and the result link of visiting http://www.whatsmybrowser.org/ please?

Regards

**Comment by SpacyRicochet** [comment]
Ah, the other Statuses disappear on the left. Collapsing more of them makes it quickly become very interesting ;)

whatsmybrowser.org/b/RAI5ZQE

![screen shot 2015-01-13 at 17 43 03](https://cloud.githubusercontent.com/assets/904596/5724423/caf44538-9b4b-11e4-99d2-e3ba71c237f3.png)
![screen shot 2015-01-13 at 17 43 12](https://cloud.githubusercontent.com/assets/904596/5724425/cb0fec02-9b4b-11e4-9aa6-825669eff6ba.png)
![screen shot 2015-01-13 at 17 43 24](https://cloud.githubusercontent.com/assets/904596/5724426/cb110074-9b4b-11e4-8e4e-539aabd58e5d.png)
![screen shot 2015-01-13 at 17 43 33](https://cloud.githubusercontent.com/assets/904596/5724424/cb0f9efa-9b4b-11e4-8fe9-e0faea5f58a3.png)

**Comment by superalex** [comment]
Thanks! :+1: 

You are right, it becomes really interesting, we'll solve it as soon as possible.

Regards

**Comment by Xaviju** [comment]
This is happening on Safari 8 and IE11 as well. 
We already have an issue for IE11 so I will add Safari 8 in the same issue, we are reviewing it right now. 
:)

**Comment by Xaviju** [comment]
This bug is fixed in repo and should be available in taiga.io in the upcoming release this week.

Thanks @SpacyRicochet!
