### ISSUE TITLE
Frontend Translation

### ISSUE THREAD

**Issue by ovnicraft** [taigaio/taiga-front#245]
Its possible translate taiga to others languages ?
I search project at transifex, nothing found.

**Comment by jespino** [comment]
Not yet, we have it in our backlog.

**Comment by ovnicraft** [comment]
:+1:

**Comment by Belibaste** [comment]
I would love to contribute to french translation. Feel free to ask :-)

**Comment by superalex** [comment]
Thanks @Belibaste!

**Comment by rydersaint** [comment]
I would like to contribute to the Japanese translation. Your software is wonderful great work!

**Comment by superalex** [comment]
Thanks @rydersaint

**Comment by eu81273** [comment]
I also would love to contribute to Korean translation!!

**Comment by RubenKelevra** [comment]
I would like to add and maintain a german translation, just ping.

**Comment by Nepeus** [comment]
I would like to add the Spanish translation.

**Comment by plesatejvlk** [comment]
I can provide the Czech strings.;)

**Comment by Xaviju** [comment]
It is already possible to help translate Taiga using transifex: https://www.transifex.com/taiga-agile-llc/
:tada:
