### ISSUE TITLE
502 (Bad Gateway)

### ISSUE THREAD

**Issue by mixxit** [taigaio/taiga-front#246]
GET http://10.1.0.19/api/v1/projects 502 (Bad Gateway) 

This is with latest install from step 1 
http://taigaio.github.io/taiga-doc/dist/setup-alternatives.html

Install looked ok apart from this

remote: Total 13713 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (13713/13713), 4.07 MiB | 1.06 MiB/s, done.
Resolving deltas: 100% (8869/8869), done.
Checking connectivity... done.
~/taiga-back ~ ~/taiga-scripts
Branch stable set up to track remote branch stable from origin.
Switched to a new branch 'stable'
Running virtualenv with interpreter /usr/bin/python3.4
Using base prefix '/usr'
New python executable in taiga/bin/python3.4
Also creating executable in taiga/bin/python
Installing setuptools, pip...done.
Downloading/unpacking djangorestframework==2.3.13 (from -r requirements.txt (line 1))
  Downloading djangorestframework-2.3.13-py2.py3-none-any.whl (294kB): 294kB downloaded
Downloading/unpacking Django==1.7 (from -r requirements.txt (line 2))
  Downloading Django-1.7-py2.py3-none-any.whl (7.4MB):  64%  4.8MBTraceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named 'django'
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named 'django'
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named 'django'
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named 'django'
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named 'django'
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named 'django'
~ ~/taiga-scripts
~/taiga-scripts
Downloading/unpacking circus

**Comment by superalex** [comment]
It sounds like the python requirements were not installed properly, did yo try to remove ~/taiga-back, ~/taiga-scripts and ~/taiga-web and start again with the installation?

Regards,

**Comment by mixxit** [comment]
Hi Super,

No i literally installed a blank copy of ubuntu and followed the guide

My error seems the same as this https://github.com/taigaio/taiga-scripts/issues/10

**Comment by superalex** [comment]
I think something failed while you were doing the installation...the easiest would be to retry from the beginning  ramoving ~/taiga-back, ~/taiga-scripts and ~/taiga-web and starting again with the installation

**Comment by mixxit** [comment]
I just tried that and it failed, can you fire it up in a fresh virtual machine so you can see the problem too?

**Comment by superalex** [comment]
Sure, I'm trying right now

**Comment by mixxit** [comment]
I just wiped out .setup and .npm and then the other folders you mentioned and then rebooted then reran setup and it's working now

I am not sure if you can see in the logs the cause of that problem?

**Comment by superalex** [comment]
I finished the installation in a clean ubuntu 14.04 and worked. It could be any network problem installation problems are not logged right now.

**Comment by mixxit** [comment]
ok thanks well it's working now!

**Comment by superalex** [comment]
You are welcome!
