### ISSUE TITLE
Search by recent modifications

### ISSUE THREAD

**Issue by zeigerpuppy** [taigaio/taiga-front#252]
We are starting to use taiga in our non-profit project team and people are really enjoying the interface.
One question I had from a user the other day was: "How do I find what items have changed recently?"

I was sure there would be a way to filter or search recent activity but cannot find how to do this.
If it's not available it would be a really useful feature for users to be able to catch up on changes and improve workflow.

The search function also could benefit from syntax (or filters) like: 
**Search** priority: high, user: Joe
If carefully implemented I don't think it would add too much complexity and would help users find items flexibly

**Comment by superalex** [comment]
Hello @zeigerpuppy,

Actually there is now way of making such query through the web app. We are currently rethinking a lo of things and one of them is the main screen in a project and the user home. Probably timelines will be added so you would be able to find easily that kind of changes.

Thank you very much for using Taiga and for your feedback! :+1:

**Comment by Xaviju** [comment]
There are timelines and the dashboard displays the recent items that are assigned to you srted by the most recently modificated. I thing thi enhancement coud be closed :)
