### ISSUE TITLE
editing of tag colours

### ISSUE THREAD

**Issue by zeigerpuppy** [taigaio/taiga-front#253]
tags work well but it would be nice to be able to change the colours of the tags so that they can be a bit more intuitive

**Comment by superalex** [comment]
Actually it's supported in the API but not in the web app. You can find examples about to update them here -> https://groups.google.com/forum/#!msg/taigaio/gRoO-RVeKo8/XxBS5DUcmpAJ

**Comment by Xaviju** [comment]
This will be available in the next Taiga release!
https://github.com/taigaio/taiga-front/blob/master/CHANGELOG.md
