### ISSUE TITLE
The cookie popup covers the 'Sign Up' and 'Login' buttons.

### ISSUE THREAD

**Issue by SpacyRicochet** [taigaio/taiga-front#254]
As a call to action for new visitors, this functions poorly.

**Comment by superalex** [comment]
Thanks for reporting @SpacyRicochet could please include a screenshot and the link you can get at http://www.whatsmybrowser.org/

Regards!,

**Comment by SpacyRicochet** [comment]
Chrome: http://whatsmybrowser.org/b/78YTPYA
![screen shot 2015-01-15 at 13 50 45](https://cloud.githubusercontent.com/assets/904596/5757627/abc23b70-9cbd-11e4-91b7-7a4653450e60.png)

Safari: whatsmybrowser.org/b/R8LUTED
![screen shot 2015-01-15 at 13 51 00](https://cloud.githubusercontent.com/assets/904596/5757628/c012afa6-9cbd-11e4-8e81-1a9e44bb8b58.png)

**Comment by superalex** [comment]
Not in the last days...

**Comment by SpacyRicochet** [comment]
Strange. Did see it happen, but it was on a darker login screen than the current one. Ah well. Carry on the good work :)

**Comment by SpacyRicochet** [comment]
Found it. whatsmybrowser.org/b/PA7O89F

![screen shot 2015-01-19 at 12 34 23](https://cloud.githubusercontent.com/assets/904596/5799868/a9547fca-9fd7-11e4-8f89-588a868302c4.png)

**Comment by superalex** [comment]
I see @SpacyRicochet, thanks for reporting.

I'm closing again because it's not a taiga-front bug, it's a comercial site one that we keep in another repo.

Thanks! :+1:
