### ISSUE TITLE
Please add feature to prioritize & set complexity to user stories

### ISSUE THREAD

**Issue by Chris2011** [taigaio/taiga-front#258]
For our daily work, we use jira and at the weekend I had a look at taiga and I created my first user story (yeah), but I missed the part where I can set the priority like minor, major, critical, blocker and to set the complexity low, medium, high.
I know there are the story points for this and I already use it but when I create a bug ticket, inside the issues I have those options, but why not for user stories?

Maybe we don't need the complexity because we have the story points, but for my perspective, the priority is missing and this is a must have, but only my opinion.

In Jira (Don't know whether we have activated it or not) we can set the priority for user stories as well.

Cheers

Chris

**Comment by superalex** [comment]
Hello @Chris2011,

Thanks for trying Taiga. If you are using a backlog the complexity for user stories should be reflected by the story points. Under a scrum point of view the priority should be reflected by the order, the top in the backlog are the most priority ones.

Anyway we are adding custom fields to Taiga objects (issues, tasks and user stories) so you could track any extra info you want to this items.

Regards,

**Comment by Chris2011** [comment]
Thx for the feedback :) :+1:
