### ISSUE TITLE
Dynamic domain name for dynamic environments

### ISSUE THREAD

**Issue by opnoack** [taigaio/taiga-front#264]
Hi there,

I'm trying to create a dynamic installation of taiga.io. The installation advises to use a static domain name which is okay for manual installations. We're planning to provide taiga.io as WebApp on twoub.io. The problem is that we would have to follow the point 7.2 "How can I change the domain name?" on http://taigaio.github.io/taiga-doc/dist/setup-production.html which leads to "gulp deploy" and that costs about a minute on my test machine for each build (which is far too long).

Isn't it possible to run the ajax calls against paths instead of static domain names so that the browser automatically takes the same domain and protocol?

Thanks in advance!

**Comment by superalex** [comment]
Hello @opnoack,

You could configure taiga-front for making the API requests to a PATH, I've tested in our PRE server to set the "api" entry from conf/main.json to:

> "api": "/api/v1/",

But you would have to do gulp deploy at least once. 

You would also have to configure your web server for proxy passing that "/api" location to taiga-back

**Comment by opnoack** [comment]
Hello @superalex,

thanks for your reply. I changed the line in the .json file and it works now. Is there also a similar solution for the websocket url? Can I just leave the example.com out of it?

**Comment by superalex** [comment]
Yes @opnoack it should work in the same way.

From the  taiga-front source code:

```
        url = @config.get("eventsUrl")

        # This allows disable events in case
        # url is not found on the configuration.
        return if not url

        # This allows relative urls in configuration.
        if not startswith(url, "ws:") and not startswith(url, "wss:")
            loc = @win.location
            scheme = if loc.protocol == "https:" then "wss:" else "ws:"
            path = _.str.ltrim(url, "/")
            url = "#{scheme}//#{loc.host}/#{path}"
```
