### ISSUE TITLE
kanban sprints

### ISSUE THREAD

**Issue by natearn** [taigaio/taiga-front#265]
It'd be nice if I could optionally organise the user stories for my sprints with a kanban board instead of a task board. I don't plan on using subtasks, but I would still like the burn-down chart and US overview.

**Comment by superalex** [comment]
It's something we planned to add in the future.

Thanks for your suggestion!

**Comment by F-3r** [comment]
This would be a huge improvement. I think is the only feature that keeps our team from using taiga

**Comment by jimutt** [comment]
It's a pity this has been untouched for the past two years. I think it would be a great addition! :)
