### ISSUE TITLE
Change the Payload URL in admin/third-parties/* to $http_host

### ISSUE THREAD

**Issue by opnoack** [taigaio/taiga-front#268]
Hi there,

at the moment the Payload URL is deposited in local.py. Which line(s) of code do I need to edit to get a dynamic Payload URL under all admin/third-parties sites and do you think it would be useful to make it dynamic by default?

Thanks in advance!

**Comment by jespino** [comment]
Hi @opnoack, I'm understand your proposal, and can have sense in some cases, but the Payload URL is an API URL, then this may be different from the frontend url. We can try to search a way to define the Payload URL based on front host url, but IMHO this mustn't be the default behavior.

**Comment by opnoack** [comment]
Hi @jespino, that sounds good. If SITES["front"]["domain"] in local.py isn't set it will display localhost, right? So weed would just need to get the http_host for that case and update the Payload URL. I'll try to find the lines but if someone knows where to search I'd appreciate any help!

**Comment by jespino** [comment]
Hi @opnoack you can found it on taigaio/taiga-back repository in the taiga/hooks/*/services.py path.

The get_or_generate_config define the webhooks url for your github/gitlab/bitbucket integration, you can send us a pull request of any of the service with your idea of how must it works.

**Comment by opnoack** [comment]
Hi @jespino, thanks for the hint! I have been digging around in the sources to find the exact place where to start. Then I came across the taiga-front/app/partials/admin-third-parties-gitlab.jade file which mentions ng_model="gitlab.webhooks_url". Is this url generated by the app.js? How can I change it to take the http_host instead of the "localhost:8000" for this dynamic environment?

**Comment by jespino** [comment]
Hi @opnoack,

the gitlab model is obtained from the api, the api generate the data here based on the stored data in the database and the get_or_generate_config placed in taiga-back taiga/hooks/github/services.py file.

**Comment by marnovdm** [comment]
@jespino I'm not sure I follow, I think I have the same issue. taiga-front only shows http://localhost:8000/api/v1/github-hook?project=5 instead of the https://tracker.realdomain.tld/api/v1/ etc I'd expect.

I did setup local.py with correct SITES["front"]["domain"] and SITES["front"]["scheme"] and restarted the workers, but it still shows http://localhost urls here. URLs in invitation emails are correct though. 
Can this be configured somewhere or is this just the way it is for now? I wasn't sure what to make of this issue and the comments.

**Comment by bameda** [comment]
@marnovdm  payload url is a api url, not front, so in taiga-back/settings/local.py add

```
SITES[api]["scheme"] = "https"
SITES[api]["domain"] = "tracker.realdomain.tld"
```

**Comment by marnovdm** [comment]
@bameda Thanks, working great now!

**Comment by bameda** [comment]
:dancer: :dancer: :dancer: 

You are welcome :smiley_cat:

**Comment by jwir3** [comment]
In the comment above, it should be:
```
SITES["api"]["scheme"] = "https"
SITES["api"]["domain"] = "tracker.realdomain.tld"
```

(Notice the quotes around `api`)
