### ISSUE TITLE
Tasks should retain all history in their full view

### ISSUE THREAD

**Issue by peiriannydd** [taigaio/taiga-front#270]
Currently, when blocking or unblocking a task, the record of the block is not retained in the history of the task. This makes it difficult to do retrospectives regarding blockers that have arrived over time.

A search that identifies blockers would be great to have as well.

**Comment by superalex** [comment]
Thanks for reporting @peiriannydd we will solve it as soon as possible!

**Comment by superalex** [comment]
Should be solved by:
https://github.com/taigaio/taiga-back/pull/233 and https://github.com/taigaio/taiga-front/pull/307
