### ISSUE TITLE
The ESC key should not be used to exit a text dialog

### ISSUE THREAD

**Issue by trevor-vaughan** [taigaio/taiga-front#271]
For those of us that are routine VIM users, this causes us to lose a LOT of work!

A 'cancel' button would be better since it cannot accidentally be pressed.

**Comment by superalex** [comment]
We implemented the ESC key from users feedback, I think we could add a setting for the key that cancel a field edition.

I think the cancel button could be a bit overkill, in issue/task/user-story details you can edit each field in an independent way, if we add a cancel button for each field I think it could be a bit heavy, we will have to check it with UX&design people.

**Comment by peiriannydd** [comment]
Being able to change the key would be good. Having to hit Ctrl+Something
would be best.

On Fri, Jan 23, 2015 at 1:33 AM, Alejandro <notifications@github.com> wrote:

> We implemented the ESC key from users feedback, I think we could add a
> setting for the key that cancel a field edition.
>
> I think the cancel button could be a bit overkill, in
> issue/task/user-story details you can edit each field in an independent
> way, if we add a cancel button for each field I think it could be a bit
> heavy, we will have to check it with UX&design people.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/taigaio/taiga-front/issues/271#issuecomment-71153385>.
>



-- 
Trevor Vaughan
Vice President, Onyx Point, Inc
(410) 541-6699
tvaughan@onyxpoint.com

-- This account not approved for unencrypted proprietary information --

**Comment by Mr-Snailman** [comment]
+1. 

Just ran into this when switching from terminal to Taiga to update/create an issue... Very frustrating when I finish a ticket and then immediately close it.

**Comment by Xaviju** [comment]
This is already fixed since there is an alert message
