### ISSUE TITLE
backlog width inconsistency

### ISSUE THREAD

**Issue by iknite** [taigaio/taiga-front#275]
Hi guys, 

In Firefox (both 35 and 37 developer edition) it doesn't keep the table width consistent.

![screenshot from 2015-01-23 13 49 16](https://cloud.githubusercontent.com/assets/745710/5874902/16610c28-a307-11e4-939e-5c8dbc145c8d.png)
`window size = 1005x1056px`

Kudos!

**Comment by superalex** [comment]
Thanks for reporting @iknite!

**Comment by Xaviju** [comment]
Hi @iknite I'm testing it on Firefox developer version 37.0a2 (2015-01-25) on production and everything seems to work well.
Could you please send us your browser version ans OS from here? http://www.whatsmybrowser.org/

Thanks!

**Comment by iknite** [comment]
That's the dump of that page (besides the IP address... :imp:)
```

Operating system     Linux x86_64
Javascript enabled   Yes
Cookies enabled      Yes
Flash version        11.2.202
Java version         Not installed
Websockets supported Yes
Browser size         954 x 1008
Screen size          1920 x 1080 (Retina)
Color depth          24 bit

Your full user agent string is:
Mozilla/5.0 (X11; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0
```

Also last version in both versions. 
```
iknite ~ ❯ yaourt -Q | grep firefox
extra/firefox 35.0-1
local/firefox-developer 37.0a2-1
```

I begin to suspect is the High dpi that I had in the laptop, because of that I had to change the `layout.css.devPixelsPerPx` to 2 (defaults: -1) inside the `about:config` page.  

Disabling it and zoom it to >= 150% gets the same results.

:beers:

**Comment by Xaviju** [comment]
This is fixed and will be available in the next version that will be online this week. Closing issue.

Thanks @iknite :)

**Comment by iknite** [comment]
great news, thanks!!

**Comment by Xaviju** [comment]
:smiley:
