### ISSUE TITLE
Please add feature to mark user stories, tasks, issues as duplicate.

### ISSUE THREAD

**Issue by Chris2011** [taigaio/taiga-front#276]
I would like to close a task which is a duplicate, but I can't find those option. Is it already implemented?

**Comment by jespino** [comment]
Hi @Chris2011,

You can do this in various different ways in taiga, depending on your workflow. You can create a new status called "Duplicated" which can be a closed status. You can use a tag for mark duplications. You can create an "severity" or "priority" called "Duplicated" and use it.

We normally use a comment with a reference to the duplicated issue, and change the status to "Rejected".

**Comment by Chris2011** [comment]
Ok, I will have a look later, thx.

**Comment by benhutchins** [comment]
It might be useful to have this in the [taiga-doc](https://github.com/taigaio/taiga-doc), creating a section of the docs of how to configure/use Taiga from an end-user, non-technical perspective. Currently there is limited documentation on how to actually use Taiga.

**Comment by superalex** [comment]
You are right @benhutchins we are working with our usability people to improve the new users experience when they start working with Taiga, it's not only a problem for non-technical users, we had assumed that Taiga was easier to use than it really is :)

**Comment by knocte** [comment]
> You can create a new status called "Duplicated"

IMHO the Duplicated status should come out of the box.

**Comment by hackedbellini** [comment]
@jespino There's a problem with your approach, it doesn't automatically track duplicates.

I mean, take bugzilla as an example: I'll mark an issue `foo` and issue `bar` as duplicated of `baz`. When checking `baz` page I can see that those bugs were duplicated of it, giving me statistics, access to their discussion history and so on.

In taiga to do that I would have to comment on both issues, and still it would take a lot of reading depending on the issue to find the duplicates in the comments.
