### ISSUE TITLE
Please add a view like the taskboard for user stories (Storyboard)

### ISSUE THREAD

**Issue by Chris2011** [taigaio/taiga-front#277]
I really like the taskboard but I would like to drag & drop user stories on the same way I can do it with the tasks. Is it possible to add a storyboard? Maybe with a combination of the taskboard and options to show tasks or not? That would be great.

Regards

Chris

**Comment by jespino** [comment]
Hi @Chris2011 

I'm don't understand it correctly. You want a "Taskboard" for only one User Story? and move the tasks of the user story? or you want a taskboard of user stories to move the user stories from one status to another?

If you want the second option. You have the kanban. You can enable kanban and backlog at the same time then, you can have the sprint taskboard for manage tasks, and the kanban for manage user stories.

Regards

**Comment by Chris2011** [comment]
Thx, works like a charm :)

**Comment by Chris2011** [comment]
I meant the second one ;)

**Comment by jespino** [comment]
You are welcome :smile:
