### ISSUE TITLE
Please add feature for auto suggestion when I type #

### ISSUE THREAD

**Issue by Chris2011** [taigaio/taiga-front#278]
I would be nice, if we can have an auto suggestion of tasks when I type: "#" then I would like to see: "#2 - This is my task" as in github. This is helpful, when I want to link to an other ticket.

**Comment by jespino** [comment]
Sure, is in our backlog with other improvements for comments/descriptions/wiki autocompletions :smiley:

**Comment by Chris2011** [comment]
Thx, nice to hear :)

**Comment by leftclickben** [comment]
:+1:

**Comment by Xaviju** [comment]
This is already in production!
