### ISSUE TITLE
Missing npm modules

### ISSUE THREAD

**Issue by masterkorp** [taigaio/taiga-front#280]
Hello,

While setting up a working environment, I had to install the following packages by hand because the ``gulp`` task was failing.

- htmlparser2
- utile
- lodash
- node-notifier
- lodash.template
- node.extend
- sax
- xmlbuilder

Please add them to your ``package.json``

**Comment by jespino** [comment]
Hi @masterkorp, thanks for your feedback.

I have downloaded the master branch and run npm install and gulp and everything is working. In which environment (Operating system, version) happens this error? Can you try to clone and run npm install again (sometimes npm doesn't works properly).

**Comment by bameda** [comment]
Hi @masterkorp, you need to execute ```bower install```
