### ISSUE TITLE
Roles

### ISSUE THREAD

**Issue by joelabair** [taigaio/taiga-front#293]
Love the ability to control permissions of a role; but, perhaps I'm not understanding the implementation of roles here.  The roles "UX, DESIGN, FRONT, BACK, PRODUCT OWNER, STAKEHOLDER" are an excellent starting point.  However, I'm apparently only able to assign one role to a member, which is fine in the use case of a "PRODUCT OWNER" or "STAKEHOLDER".  But for my team, many members cover both "FRONT" and "BACK" roles, and sometimes also "DESIGN" and "UX".   Do I simply need to create a "MONKEY" role for these cases?  Or is there something else I'm missing?

**Comment by jespino** [comment]
Hi @joelabair,

The answer is yes, one project member only have one role, if you have members with "multiple roles" you can define "full-stack" or other new role. The roles are for 3 different things:

1. Inform the user type (this user is Front or Back, or my new group FullStack)
2. Define the type of estimations (If you want estimate the Back and Front effort in different estimations, you need 2 different roles).
3. Define permissions. Two roles can have different permissions.

We can think about more complex roles/permissions system, but this is the current implementation.

:smile:

**Comment by joelabair** [comment]
Thanks @jespino !

**Comment by pinkra** [comment]
Hi, this is useful also for the role of ScrumMaster that can be also a developer in some cases. So, when i define the new ScrumMaster role i cannot take this role in addition to the developer role!
