### ISSUE TITLE
Search should be able to search filenames and extensions

### ISSUE THREAD

**Issue by trevor-vaughan** [taigaio/taiga-front#298]
Currently, users cannot type a search like 'pdf' and have search results returned on attachments.

This makes it difficult to find items in the Wiki or attached to tasks.

Also, filenames should be searched.

Something like 'filetype:pdf myawesomefilename' would be great.

**Comment by superalex** [comment]
Thanks @peiriannydd searching is something we have to improve in Taiga, thank you very much for your suggestions

**Comment by invernizzie** [comment]
Same goes for tags.
