### ISSUE TITLE
Limit the roles rows. 

### ISSUE THREAD

**Issue by iknite** [taigaio/taiga-front#299]
![screenshot from 2015-01-29 18 19 10](https://cloud.githubusercontent.com/assets/745710/5962366/b30ed4d4-a7e3-11e4-86e0-25237094b477.png)

Can you guess who's the Design Leader?
Maybe limit the maximum number of roles to 4-5 can help. 

:beers:

**Comment by Xaviju** [comment]
This is a bug, it is supposed to have a minimum space for each role, and, if required, fall down to next line.
Thanks for reporting @iknite 

:beers:

**Comment by Xaviju** [comment]
This should be fixed here: https://github.com/taigaio/taiga-front/commit/b631aef22d8c93e4a52ebb82646a0dbd0e6d710a
