### ISSUE TITLE
Back log order does not persist

### ISSUE THREAD

**Issue by t9hill** [taigaio/taiga-front#301]
I use drag-and-drop to order my User Story backlog in priority order (highest priority at the top).  However, as I make changes (add User Stories, update status, etc.), the order of the User Stories in the list seems to randomly change.

**Comment by superalex** [comment]
Hello @t9hill, what browser and version are you using?, I've been checking tree.taiga.io right now and I can't reproduce the problem. Yesterday we deployed a new release, could you have problems with your browser cache?

Regards,

**Comment by FlorianBezagu** [comment]
Hi @t9hill 

I have same problem. See this issue : https://github.com/taigaio/taiga-front/issues/261#issuecomment-70612301

**Comment by superalex** [comment]
@t9hill is it still happening?
