### ISSUE TITLE
coffee-script version 1.9.0 gives error for taiga front

### ISSUE THREAD

**Issue by gaikwad411** [taigaio/taiga-front#317]
Hello there , 
  I have just install my npm dependencies again, I think new coffe-script version does not generate correct js code. 
  Error I have,
      ReferenceError: config is not defined app.js:20139
  Error is blocking, it does not let project start.
 
   Earlier version 1.8.0 is working fine. 
   As a quick fix I am chaning package.json to strictly include 1.8.0. 

   Thanks

**Comment by gaikwad411** [comment]
Error was with gulp-coffee not the "coffe-script" package.

I have changed 
"gulp-coffee": "^2.2.0", 
to 
"gulp-coffee": "2.2.0"

Now it is working.

**Comment by juanfran** [comment]
that should be fixed, are you on the master branch?
