### ISSUE TITLE
Inviting users to a project: error message provided by backend is not displayed on frontend

### ISSUE THREAD

**Issue by leftclickben** [taigaio/taiga-front#318]
I want to invite users to a project, but I am getting an error that gives me no information.

## Steps to reproduce

1. Enter a project and go to Admin > Manage Members
2. Hit the "New Member" button
3. Fill in details as displayed in the first screen shot below
4. Hit the "Create" button

## Expected

An error message that tells me what went wrong and how to fix the problem.

## Actual

An error message as shown in the second screen shot.  This says nothing, only that something went wrong, and that somebody is a fan of Roald Dahl.

## More info

The third screen shot shows the relevant output in the Firebug network tab, including a descriptive error message ("Ensure this value has at most 255 characters (it has 951).").

## Suggested fix

Display the error message from the JSON response in the notification in the UI.

It doesn't seem too much of a stretch that there would be other errors that are affected by this issue as well.

## Screenshots

First screenshot (ready to send invitation):
![1-ready-to-send-invitation](https://cloud.githubusercontent.com/assets/94266/6037567/07d6f1f8-ac90-11e4-88b3-0429dcff8f42.png)

Second screenshot (after pressing "Create"):
![2-after-pressing-create](https://cloud.githubusercontent.com/assets/94266/6037568/07faa8fa-ac90-11e4-9282-99a6a210e37d.png)

Third screenshot (Firebug network tab):
![3-firebug](https://cloud.githubusercontent.com/assets/94266/6037569/0806204a-ac90-11e4-8fe2-12ba993f3ffc.png)

**Comment by superalex** [comment]
Thank you very much @leftclickben 

It was solved here -> taigaio/taiga-front@8934861 but still not in stable branch

**Comment by leftclickben** [comment]
Thanks @superalex , at first I thought this wasn't an appropriate fix, but I suppose prevention is better than cure :-)
