### ISSUE TITLE
Editable length restriction for personal message in invitation

### ISSUE THREAD

**Issue by leftclickben** [taigaio/taiga-front#319]
As mentioned in #318 there is a length restriction on personal messages in user invitations.

I don't see any reason for this limitation, can it be removed?

**Comment by superalex** [comment]
The reason was that we didn't want to allow users to spam another users in invitations, if text has unlimited size this could be achieved easily.

**Comment by leftclickben** [comment]
Thanks for the response @superalex .  That certainly makes sense for the hosted version because the spam would be coming from Taiga's servers.  But if I'm running the software locally, it would come from my server, and therefore is no different to me just writing a very simple script to do the same job.  Installing an agile project management tool does seem like an obscure path to sending spam :-)

Perhaps the enhancement could be to make the maximum length configurable?  That way on your servers it can be a low limit but if I install it locally, I can set the limit to what I need.

**Comment by superalex** [comment]
I think the maximum length configurable would be the right way to go. By default it could have th 255 limit but you could customize it in your own instance for disabling/extending the limit :+1:
