### ISSUE TITLE
Long names for sprint point options breaks UI

### ISSUE THREAD

**Issue by leftclickben** [taigaio/taiga-front#321]
Using long names for sprint point options breaks the UI, which uses a fixed width to display these elements.

![broken-sprint-points](https://cloud.githubusercontent.com/assets/94266/6039136/9bc17128-ac9e-11e4-8998-b5aa61b64aee.png)

This applies when assigning sprint points from the list in the backlog, or from the "Edit User Story" dialog, or from the full-screen editor for the user story (URL of `/project/project-name/us/123`).

I have used the names of notes in musical notation because the project is music-related.

A simple vertical list would probably solve the problem, or better, a (per-project) option to switch between the grid layout and the simple list.

**Comment by superalex** [comment]
Thanks for reporting @leftclickben

**Comment by Xaviju** [comment]
We are working on this issue and it will be fixed on the upcoming release. :tada:
