### ISSUE TITLE
Ability to edit comments

### ISSUE THREAD

**Issue by moaazsidat** [taigaio/taiga-front#323]
It would be really useful if comments on user stories/issues could be edited, along with the indication of when the last change was made and an edit history to track the changes.

**Comment by superalex** [comment]
Thanks for your suggestions @moaazsidat

**Comment by zwarag** [comment]
Any Information if/when this will get added?

**Comment by superalex** [comment]
Hello @zwarag, it's something that we still have to decide if finally will be included in the taiga core so no aprox dates for it.

Regards!,

**Comment by shrbrkmak** [comment]
+1  My team members are very used to workflows of GitHub/GitLab where comments are easily edited. Thanks for your consideration!

**Comment by omichde** [comment]
+1 our teams uses Taiga a lot and comments are used extensively - editing comments are probably the most severely missed feature.

**Comment by red-hood** [comment]
:+1: We also need this feature, i don't think it should be hard to implement. Btw, is there a taigo project for taiga, or will all issues be tracked here?

**Comment by bameda** [comment]
@red-hood is not as easy as you think (because right now one comment depends on a change to an object (https://github.com/taigaio/taiga-back/blob/master/taiga/projects/history/models.py#L62), we need to maintain a history of changes of every comment,...), but we have a US in our kanban to implement this.

https://tree.taiga.io/project/taiga/us/2929

**Comment by KOGI** [comment]
Another upvote for this feature :)

**Comment by AdrianSchurz** [comment]
Feature would be much appreciated. Cheers.

**Comment by Morkalork** [comment]
Yeah, this is a bit of a bummer, upvote! :P

**Comment by AlexzAK** [comment]
It's a must have feature. With out it I'am feeling a lot of pain, due to inability to change typo in prev comment.

**Comment by mlenderink** [comment]
+1

**Comment by siliconalchemy** [comment]
+1 - I curse the interface several times a day due to this :)

**Comment by mageddo** [comment]
:+1:  please

**Comment by KOGI** [comment]
Over a year later, looks pretty clear this isn't going to get done. :(

**Comment by bameda** [comment]
@KOGI It's not true we'll do it. This enhancement has a lot of upvotes but right now we are working to get subscriptions for the next month.

We have to evaluate how we can rewrite the historical system  (and migrate current data to the new one) to maintain a history of changes of every comment too so this change is not so trivial as you think.

**Comment by philippebarbosa** [comment]
Can't understand why this feature isn't available, and still not. This is a must have feature :(

**Comment by shoeper** [comment]
Please add this. It would be very very helpfull.

**Comment by bameda** [comment]
in progress, I hope it could be for next release 

https://tree.taiga.io/project/taiga/us/2929

**Comment by mathieu-b** [comment]
+1
@bameda : great!

**Comment by Mr-Snailman** [comment]
+1. I also screw up the formatting on my comments and forget to 'Preview' before I submit.

**Comment by bameda** [comment]
This feature will be for the next release.

https://github.com/taigaio/taiga-front/blob/master/CHANGELOG.md#300--unreleased
