### ISSUE TITLE
In the Backlog view, the user point selector should not be a drag handle for a user story

### ISSUE THREAD

**Issue by leftclickben** [taigaio/taiga-front#324]
In the backlog, each user story shows the current user story point total, with an arrow that opens a list of user types, then clicking one of the user types brings up the configured user story point options.

Currently, dragging on the user type list or the user story point options list drags the user story.  

This is unintuitive: if I have opened the list, I am interacting with that list now, not the parent item in its parent list.

**Comment by superalex** [comment]
Thanks @leftclickben, yesterday we received more feedback about the same topic, we will have to review this part :+1:

**Comment by juanfran** [comment]
Hi @leftclickben this is fixed in master branch and it will be in production in the next release
