### ISSUE TITLE
502 bad request error when adding a new member

### ISSUE THREAD

**Issue by elsenben** [taigaio/taiga-front#326]
Hello, 

I have a taiga running on an EC2 instance, everything installed like explained in the documentation and everything works except adding members to a project. 
When I try so, I get the oompa loompas error and in firebug, I see: 
![schermafbeelding 2015-02-05 om 10 51 45](https://cloud.githubusercontent.com/assets/10460196/6058253/de94269e-ad25-11e4-8dcc-1bd880017375.png)
 
Does somebody have a clue what the problem can be?

Thanks,
Ben

**Comment by superalex** [comment]
Hello @elsenben 

Could you check the response for the bulk create?, are you sending an extra text longer that 255?. If yes it's a bug we solved here (https://github.com/taigaio/taiga-front/commit/8934861cc7df76d8cc22888836c173921557c4e9) but still not merged into stable

**Comment by elsenben** [comment]
Yes I noticed the error regarding the length.. I send just a random 'ff' as test. 
This is what I send: 
{"project_id":7,"bulk_memberships":[{"email":"bert@heymans.org","role_id":"42"}],"invitation_extra_text":""}

**Comment by elsenben** [comment]
![schermafbeelding 2015-02-05 om 11 13 30 2](https://cloud.githubusercontent.com/assets/10460196/6058488/1431c836-ad28-11e4-9b7a-5e0ecddb0a1c.png)

**Comment by superalex** [comment]
Thanks @elsenben, in your screenshot I can see the parameters sent, could you also include another one from the server response, please?

Regards!,

**Comment by elsenben** [comment]
![schermafbeelding 2015-02-05 om 12 12 10 2](https://cloud.githubusercontent.com/assets/10460196/6059310/43111e56-ad30-11e4-8e3a-c7d6bb32d455.png)

**Comment by elsenben** [comment]
I switched the debug mode on and then I see this error as a response of the bulk request: 

gaierror at /api/v1/memberships/bulk_create

[Errno -2] Name or service not known

Request Method: 	POST
Request URL: 	http://taiga.joobizz.be/api/v1/memberships/bulk_create
Django Version: 	1.7
Exception Type: 	gaierror
Exception Value: 	

[Errno -2] Name or service not known

Exception Location: 	/usr/lib/python3.4/socket.py in getaddrinfo, line 530
Python Executable: 	/home/taiga/.virtualenvs/taiga/bin/python3.4
Python Version: 	3.4.0
Python Path: 	

['/home/taiga/taiga-back',
 '/home/taiga/taiga-back',
 '/home/taiga/.virtualenvs/taiga/bin',
 '/home/taiga/.local/lib/python3.4/site-packages',
 '/home/taiga/.virtualenvs/taiga/lib/python3.4',
 '/home/taiga/.virtualenvs/taiga/lib/python3.4/plat-x86_64-linux-gnu',
 '/home/taiga/.virtualenvs/taiga/lib/python3.4/lib-dynload',
 '/usr/lib/python3.4',
 '/usr/lib/python3.4/plat-x86_64-linux-gnu',
 '/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages',
 '/home/taiga/taiga-back']

Server time: 	Thu, 5 Feb 2015 11:08:31 +0000

**Comment by superalex** [comment]
It sounds like yout system is trying to send an email to a domain it can't resolve...could you try with another email?

**Comment by elsenben** [comment]
I just tried with another email but I get the same error..

**Comment by superalex** [comment]
How is your taiga-back email configuration?, are you using a local server?

**Comment by elsenben** [comment]
Yes I installed it on a amazon EC2 instance but I think I located the problem. When I comment all the lines regarding mails in the local.py, it works. So their should be something wrong there.. 
Do you have by any chance some example config data to send mails from a google (business) mail adress? 

This is what I use now:
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_USE_TLS = True
EMAIL_HOST = "smpt.gmail.com"
EMAIL_HOST_USER = "***"
EMAIL_HOST_PASSWORD = "***"
EMAIL_PORT = 587

With the given user en password, I can login through gmail..

**Comment by elsenben** [comment]
Ok I made the stupiest mistake :) 'smPT' should be 'smTP' ;) Sorry for the trouble! Thanks a lot for directing me to the email settings!

**Comment by superalex** [comment]
I think I found your problem smpt.gmail.com is not the same as smtp.gmail.com that could be the problem why you can't resolve the hostname :)

**Comment by superalex** [comment]
Hahaha!, I think we found the solution at the same time! :+1:

**Comment by elsenben** [comment]
Haha indeed :)
