### ISSUE TITLE
Chart: Business Value vs Development Cost

### ISSUE THREAD

**Issue by emanuelvianna** [taigaio/taiga-front#330]
Hi fellows,

I would like to suggest a new feature for the Taiga IO product.

It's a chart that crosses the business value of a User Story (US) made by the 
Product Owner (y-axis) with the development cost estimated by the Team (x-axis). 

We normally do this by hand, as shown below:

![chart](https://cloud.githubusercontent.com/assets/3580848/6107678/06c3e13c-b054-11e4-9fb1-10a9fa0dacaa.png)

This chart help us to prioritize our user stories.

You already have a feature to input these values (P.O. and Team estimates), which
data could be used for plotting.

Very best regards,
Emanuel

**Comment by superalex** [comment]
Hello @emanuelvianna, it sounds very interesting, I think it could be one of the graphs we could add when we improve the reporting system inside Taiga.

What we are currently implementing are the custom fields and csv export features. With this you could use your favourite spreadsheet app with the csv urls as remote data sources and create all the graphs/reports you need for your working workflow.

Regards,

**Comment by joshhopkins** [comment]
This would be really great.
