### ISSUE TITLE
Restarting nginx nginx [fail]

### ISSUE THREAD

**Issue by psgganesh** [taigaio/taiga-front#336]
Hi all!

When i do " sudo service nginx restart " , terminal says me: * Restarting nginx nginx [fail]

What can i do?

Below are my conf settings

[circus]
check_delay = 5
endpoint = tcp://taiga.ellipsonic.com:5555
pubsub_endpoint = tcp://taiga.ellipsonic.com:5556
statsd = true

[watcher:taiga]
working_dir = ~/taiga-back
cmd = gunicorn
args = -w 3 -t 60 --pythonpath=. -b taiga.ellipsonic.com:8001 taiga.wsgi
uid = taiga
numprocesses = 1
autostart = true
send_hup = true
stdout_stream.class = FileStream
stdout_stream.filename = ~/logs/gunicorn.stdout.log
stdout_stream.max_bytes = 10485760
stdout_stream.backup_count = 4
stderr_stream.class = FileStream
stderr_stream.filename = ~/logs/gunicorn.stderr.log
stderr_stream.max_bytes = 10485760
stderr_stream.backup_count = 4

[env:taiga]
PATH = $PATH:~/.virtualenvs/taiga/bin
TERM=rxvt-256color
SHELL=~/../bin/bash
USER=taiga
LANG=en_US.UTF-8
HOME=~/
PYTHONPATH=~/.local/lib/python3.4/site-packages

[watcher:taiga-celery]
working_dir = ~/taiga-back
cmd = celery
args = -A taiga worker -c 4
uid = taiga
numprocesses = 1
autostart = true
send_hup = true
stdout_stream.class = FileStream
stdout_stream.filename = ~/logs/celery.stdout.log
stdout_stream.max_bytes = 10485760
stdout_stream.backup_count = 4
stderr_stream.class = FileStream
stderr_stream.filename = ~/logs/celery.stderr.log
stderr_stream.max_bytes = 10485760
stderr_stream.backup_count = 4

[env:taiga-celery]
PATH = $PATH:~/.virtualenvs/taiga/bin
TERM=rxvt-256color
SHELL=/bin/bash
USER=taiga
LANG=en_US.UTF-8
HOME=~/taiga
PYTHONPATH=~/.local/lib/python3.4/site-packages

Unable to do the following too
circusctl reloadconfig
circusctl restart taiga
circusctl start taiga-celery

~/taiga-front-dist/dist/js/conf.json
{
    "api": "http://taiga.ellipsonic.com/api/v1/",
    "eventsUrl": "ws://taiga.ellipsonic.com/events",
    "debug": "true",
    "publicRegisterEnabled": true,
    "feedbackEnabled": true,
    "privacyPolicyUrl": null,
    "termsOfServiceUrl": null,
    "maxUploadFileSize": null,
    "gitHubClientId": null,
    "contribPlugins": []
}

**Comment by bameda** [comment]
Hi @psgganesh, this is not a bug in taiga-front code, rather it's a configuration error in your nginx service.

So, Can you write to the taiga mailing list (at https://groups.google.com/forum/#!forum/taigaio) and explain us your problem with more details, please? For example you can paste your ngingx log file (```/var/log/nginx/nginx_error.log```, ```/var/log/nginx/error.log``` or something similar) and/or your nginx configuration. 

Thanks.
