### ISSUE TITLE
Links within issues and comments should open in a new tab

### ISSUE THREAD

**Issue by jamesdoc** [taigaio/taiga-front#338]
Really small tweak that would be wonderful: when the markdown links are converted to HTML it would be helpful to add `target="_blank"` to links that direct outside of Taiga.

**Comment by fuzzy76** [comment]
Why would you override the users decision? Please don't.

https://css-tricks.com/use-target_blank/

**Comment by bameda** [comment]
Because are external links, internal links open in the same tab/windows by default and external links open in other one. Wikipedia, for example, do the same.
