### ISSUE TITLE
Blank page after fresh installation of version 1.5.0

### ISSUE THREAD

**Issue by opnoack** [taigaio/taiga-front#342]
Hey there,

after having installed version 1.4.0 successfully I tried to cleanly install version 1.5.0 in a completely new environment. I followed the exact same steps as before (http://taigaio.github.io/taiga-doc/dist/setup-production.html) but when I access the website I only get a blank page.

These are the entries in the firefox console:
ReferenceError: config is not defined - app.js:14
"Initialize navigation urls" - libs.js:10

What has changed from 1.4.0 to 1.5.0 that could cause this problem? Did I forget anything?

**Comment by superalex** [comment]
Hello @opnoack,

Could you try to checkout your taiga-front-dist to stable branch, make a pull and check if the error is still happening please?

**Comment by zhanif3** [comment]
I'm having the same issue in 1.4.0. Using chrome and firefox. Oddly, it seems to work in Safari.

**Comment by superalex** [comment]
If you are using 1.4.0 it sounds like you are using taiga-front and not taiga-front-dist, could you checkout to the last version from stable and try again please?

**Comment by opnoack** [comment]
Hi there, thanks for your replies. Indeed it was a problem with taiga-front / taiga-front-dist. I used the old setup guide from your website and since it has changed it didn't work anymore. Now I've updated my installation to use taiga-front-dist and its working again. Thanks!

**Comment by superalex** [comment]
You are welcome @opnoack ! :+1:
