### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by louim** [taigaio/taiga-front#345]
Hi guys,

Is there plans to add unit / integration tests on the front-end part? I think that it is really important to have good tests in such app. What do you guys think?

**Comment by juanfran** [comment]
HI @louim 

I totally agree, but add them in an Angular app already developed could be a nightmare. We don't have any specific plan about this but we would like to add them.

**Comment by juanfran** [comment]
we are adding test in the new functionality :smiley:
