### ISSUE TITLE
No place to put planned hours or actual hours spent on a task

### ISSUE THREAD

**Issue by adityaSplendornet** [taigaio/taiga-front#346]
I don't see any option to add planned hours & actual hours worked for a particular task. I can make use of story points as planned hours, but how do I track how much is the time spent for each task? This information might be useful when we are doing a retrospection of a particular sprint.

**Comment by superalex** [comment]
Hello @adityaSplendornet ,

We are currently implementing custom fields (for user stories, tasks and issues) and csv export features. With this you could add those new fields to your tasks and use your favourite spreadsheet app with the csv urls as remote data sources for creating all the graphs/reports you need for your working workflow.

Regards,
