### ISSUE TITLE
Can not add Sub-Task

### ISSUE THREAD

**Issue by adityaSplendornet** [taigaio/taiga-front#347]
I can see facility to put task, but no facility to put sub-task under it and no facility to define story points for each task/sub-task. Is this something which can be added?

**Comment by superalex** [comment]
By default Taiga allows you to define user stories (with estimated points) and children tasks, this tasks hasn't subtasks. I've answered about the definition of story points for tasks in your other issue -> https://github.com/taigaio/taiga-front/issues/346

Thank you very much for using Taiga! ;)

**Comment by adityaSplendornet** [comment]
Thanks for the reply, is there any chance of seeing this facility of creating sub-task in taiga?

Kudos to you and your team for developing such as wonderful system. My team thanks each one of you :-)

**Comment by superalex** [comment]
We are very happy if you are enjoying it! :)

Could you describe a situation where you need subtasks?, we found that with two levels (us and task) we covered all the "normal" situations.

**Comment by adityaSplendornet** [comment]
Well I could very well manage with user stories and task as you have said, but then in that case there would be too many user stories.

Generally what we do it, we take a feature what product owner has specified and consider it as user story/requirement, and then split it into Tasks. So the task can be considered as an user story in itself. So I think we need to change our methodology and create smaller user stories.

If I encounter any specific case where the sub-task is absolute necessity I will let you know.

Thanks for the support.

**Comment by superalex** [comment]
Thanks @adityaSplendornet!

Just a question, are you using backlog or kanban?, if you have too many user stories in Kanban you could keep them in a collapsed status or in an archived one.

**Comment by adityaSplendornet** [comment]
We mostly use backlog.

**Comment by bameda** [comment]
I Hi @adityaSplendornet , I think you're using user stories as epics. We have spoken about this feature in our blog (https://blog.taiga.io/epic-stories.html) and would like to include it in Taiga in the future.

**Comment by adityaSplendornet** [comment]
Yes you are right, I forgot the word "epic" :-). Hope to see this feature soon.

**Comment by Cephlin** [comment]
So no epics as of yet?

**Comment by bameda** [comment]
Not yet

**Comment by shifa-icare** [comment]
Eagerly awaiting Epics!
