### ISSUE TITLE
Add lets-chat integration.

### ISSUE THREAD

**Issue by SL-RU** [taigaio/taiga-front#359]
There are already integration of proprietary chat services, but selfhosted opensource chat will be much better. 
Here it is: http://sdelements.github.io/lets-chat/

Or other, if you know other opensouce selfhosted alternatives of slack or hall, or hipchat.

**Comment by geoffwhittington** [comment]
I'm affiliated with Lets Chat and unfortunately I'm unfamiliar with Taiga w/ Slack/HipChat - what level of integration is this?

We have API documentation on our wiki https://github.com/sdelements/lets-chat/wiki/API Basically, we support posting messages to a room similar to how Slack supports posting text to a channel. What is different is that we use the `Authorization: Bearer` header for authentication. Also, we don't support certain additional fields like attachment.

I can help a Taiga developer work with our API if there is any interest in this integration.

**Comment by astagi** [comment]
Lets chat looks interesting...  These integrations work on events, whenever something happens, e.g. a task description changes, user creates a new user story  or delete something, then send a message to the chat using its own api.. Auth header is not a problem, it's just an additional information to store and send when events happen.. attachments are just urls to the attached files.. 

I can get this task if the other guys are interested..

**Comment by geoffwhittington** [comment]
Ok great @astagi It sounds like the integration should be straight-forward then. Please let me know if I can be of service!

**Comment by astagi** [comment]
ok @geoffwhittington thanks :) we're now testing lets chat within my company today and we're really enthusiast :) I also tried the API but it seems that I can't send html text, I tried

    http -f POST http://192.168.93.194:5000/rooms/dev/messages text="Hello <b>from</b> <br>API" Authorization:"Bearer MYBEARER"

and the result is plain text. Am I missing anything or is it just not implemented? in the latter case I think that it would be really useful allowing users to send html text (with a limited set of tags e.g. bold, italic, line break) and get a nice output.

**Comment by astagi** [comment]
https://github.com/sdelements/lets-chat/pull/303

this filter should be enabled only on api calls

**Comment by hhaidar** [comment]
@astagi +1, thanks for doing this :D 

One small thing: `message.format` should be blank by default imo

**Comment by astagi** [comment]
Lets chat team added markdown support, I can start working on Taiga integration. Could anyone open a new dedicated repo to work on, please? thanks! :smile:

**Comment by bameda** [comment]
@astagi done https://github.com/taigaio/taiga-contrib-letschat

**Comment by astagi** [comment]
@bameda thank you :smile:

**Comment by 8cells** [comment]
:+1:

**Comment by astagi** [comment]
@bameda sorry but it looks like I don't have write permissions in the letschat plugin repo :) could you please allow me to push directly? thanks!

**Comment by superalex** [comment]
Hello @astagi,

You are a member of taiga-hipchat team and you should have write permissions, could you confirm if it's working please?

**Comment by astagi** [comment]
First alpha version ready for test! :tada: :tada: 

https://github.com/taigaio/taiga-contrib-letschat

**Comment by bameda** [comment]
Great!

**Comment by SL-RU** [comment]
@astagi, this is awesome!

Thank you! :3
