### ISSUE TITLE
Allow for wiki-page label creation and linking and possibly TOC generation

### ISSUE THREAD

**Issue by shidorama** [taigaio/taiga-front#363]
Git flavored markdown allows for link to a headers inside current page like this:

```markdown
# TOC
* [First] (#first)
* [Second] (#second)

## First
sample text

## Second
sample text
```

which can be used to produce a Table of contents.
Same syntax doesn't work inside taiga wikia and it's quite inconvinient.
I propose this feature to be added to taiga markdown wiki alongside with autogenerator fo TOC. There are many implementations of auto TOC generators for markdown and auto TOC is basically a must for any decent wiki.

**Comment by jespino** [comment]
Hi @shidorama,

A possible solution is to enable the TOC extensions of your markdown library which is this (https://pythonhosted.org/Markdown/extensions/toc.html).

This is enough for you?

**Comment by shidorama** [comment]
I guess so.

**Comment by superalex** [comment]
Added here -> https://github.com/taigaio/taiga-back/pull/271
