### ISSUE TITLE
Default username and password

### ISSUE THREAD

**Issue by Ryahn** [taigaio/taiga-front#368]
I have it up and running but I do not have a username and password to login with. I used the setup-server.sh on ubuntu 14.04

Here is the install log https://pastebin.com/kp5QZ5Gt

**Comment by superalex** [comment]
The default username and password taiga creates is admin with password 123123, isn't it working?

**Comment by superalex** [comment]
I'm closing this one and keeping opened https://github.com/taigaio/taiga-scripts/issues/24
