### ISSUE TITLE
Manually Approve Members

### ISSUE THREAD

**Issue by Ryahn** [taigaio/taiga-front#372]
In the case of my server, my mail server is not working or the IP of my VPS is not whitelisted with all the major email providers. Is there a way to manually approve a member?

**Comment by superalex** [comment]
You could access to the django admin interface, go to the memberships section and check the invitation token for the user. 

With this token you could generate manually a url like: TAIGA_URL/invitation/TOKEN that the user could use for joining Taiga.

**Comment by Kyslik** [comment]
I have tried the same and I added manual token (like one char just to test it out) and token seems to not work (red notification bar pops out, invalid token (or token not found).
