### ISSUE TITLE
[BUG] HTML Table formatting not properly rendering to Markdown with embedded images

### ISSUE THREAD

**Issue by cerealkella** [taigaio/taiga-front#38]
**Describe the bug**
When dropping images into tables and attempting to save via the html editor, the markdown conversion or whatever it is that happens in the background goes wonky, and does not save it properly formatted. It can be fixed in Markdown, but any changes that subsequently get made via HTML will break the formatting.

**How can we reproduce the behavior**
See GIF > when making a table and adding images to it, then attempting to save in HTML mode, the formatting is not at all how it should be.

**Workarounds**
Only use markdown editing mode.

**Screenshots**
![GIF](https://i.imgur.com/hzIC8iR.gif)

**Taiga environment**
Self-hosted, built from source

**Desktop (please complete the following information):**
 - **OS:** Manjaro
 - **Browser:** Can reproduce in Firefox and Chrome
 - **Version:** 88.01 (Firefox) 91.0 (Chrome)

**Additional context**
Using wiki editing as example.

**Comment by rsanchezbalo** [comment]
Hello. 
This change is available on our latest release (6.2.1). 
Thank you very much @kellerjustin

**Comment by cerealkella** [comment]
> Hello.
> This change is available on our latest release (6.2.1).
> Thank you very much @kellerjustin

upgraded, and it worked properly after I cleared my browser cache. Thanks!
