### ISSUE TITLE
Can't manage or close account without any project

### ISSUE THREAD

**Issue by RubenKelevra** [taigaio/taiga-front#385]
If you register a fresh account, you cant click on your account-icon and change info, change your password or close your account.

You have to create a project first, to do this, since in the project-view, your account-picture is clickable.

**Comment by superalex** [comment]
You are right, we are working on new homes for user, projects and profile pages and it will be restructured so you don't need any project for doing it.

Regards!,

**Comment by RubenKelevra** [comment]
Thats great! Thanks for your fast response! :)

**Comment by Xaviju** [comment]
Should be fixed with the latest release (1.8.0)

**Comment by RubenKelevra** [comment]
Thanks!
