### ISSUE TITLE
Add severity-ratings with categorys to US

### ISSUE THREAD

**Issue by RubenKelevra** [taigaio/taiga-front#386]
We start to use kanban, because its simple and intuitive for most users.

Now we got some rows:

inbox, read, need more info, prioritization done, next, active, review, testing, next release,  rolled out

In our case we need to prioritize our US, as you can see. To implement this, we raped "user roles" for this, we got an "Security", "User Experiance" and "Backend"-User-Role for this, and redefined the US-Points to reflect the severity of a US, like on a ticket system.

Since we use the user-roles for this, we cant use them to reflect the difficulty on each team for a user-story - which is sad.

So it would be nice if you could implement the possibility to rate a US on different category's for it's severity, and allow to sort a kanban-row automatically on this calculated points ('prioritization done' and 'next' on our example).

Thanks in advance! :)

**Comment by adebayo-dealdey** [comment]
Is it possible to add a ticketing system on taiga?

**Comment by superalex** [comment]
@adebayo-dealdey actually Taiga has an issues area that can be used that way.

**Comment by adebayo-dealdey** [comment]
Can you be more precise please, I just deployed taiga on my local machine (development) and i found out that the plugin section wasn't included and I will love to add a ticketing system to taiga if it's not included already. Thanks.

**Comment by superalex** [comment]
@adebayo-dealdey I wasn't speaking about an extra plugin for a ticketing system, just the issues section from a project, you can access to it from the left bar.

For example, the taiga issues section -> https://tree.taiga.io/project/taiga/issues

**Comment by adebayo-dealdey** [comment]
@superalex Ooo.. thanks. I was thinking of a more native ticketing system but I will get into that as recommended. How about the other plugin section that was excluded from my development installation?

**Comment by superalex** [comment]
What plugin section was excluded from your installation?

**Comment by adebayo-dealdey** [comment]
@superalex How to relicate issue:
> Clicking the project you are working on
> Navigate to the admin section
> You will see links like: Project, Attribute, Members etc but not Plugin which exist on the taiga.io

The plugin section allows me to add HipChat, Gog and Slack which i dont have access to on my development version, want to know if its just a bug, overlooked process or something else. Thanks.

**Comment by superalex** [comment]
Oh!, now I understand what you mean, you should enable them one by one:
- https://github.com/taigaio/taiga-contrib-hipchat
- https://github.com/taigaio/taiga-contrib-gogs
- https://github.com/taigaio/taiga-contrib-slack

**Comment by adebayo-dealdey** [comment]
Thanks.. you just saved me stress...

**Comment by superalex** [comment]
You are welcome! ;)

**Comment by adebayo-dealdey** [comment]
@superalex  I guess there is an error in the documentation of the plugins, the front-end section where the plugin directory has to be added to the conf.json: it said the conf.json is located in the dist/ directory instead of the dist/js/ directory.. please confirm if I right. Thanks.

**Comment by bameda** [comment]
Is because you are using the documentation of the dev version. Use this:

https://github.com/taigaio/taiga-contrib-slack/tree/stable
https://github.com/taigaio/taiga-contrib-gogs/tree/stable
https://github.com/taigaio/taiga-contrib-hipchat/tree/stable

**Comment by adebayo-dealdey** [comment]
Okay, thanks. I didn't think of that. Thanks once again.

**Comment by bameda** [comment]
You are welcome.

**Comment by adebayo-dealdey** [comment]
Do you have any documentation on taiga system build? What each of the terms
you decided to use mean.

**Comment by superalex** [comment]
Hello @adebayo-dealdey we have a blog and a support platform:
 - https://taiga.io/support/
 - https://blog.taiga.io/

Regards!,

**Comment by adebayo-dealdey** [comment]
@superalex Thanks. Checked them yesterday.. Got a lot of information.

**Comment by superalex** [comment]
Great! :+1:

**Comment by adebayo-dealdey** [comment]
@superalex I must confess, I don't know what breaks the connection between the plugins and taiga production version this time, I was able to solve adding plugins to the development server but following the same step for the production server doesn't work.
Below is my development server installation with a broken template engine filling the project name where required.
![image](https://cloud.githubusercontent.com/assets/16304032/12164774/8f71a04a-b518-11e5-8a27-cdb92ead5b3c.png)
 
Below is my production server installation not displaying my plugin tab at all even after adding plugins into the application

![image](https://cloud.githubusercontent.com/assets/16304032/12164875/408b269e-b519-11e5-9105-93257179bed0.png)

Can you kindly tell me what I might be doing wrongly?
Thanks for your usual help.

**Comment by superalex** [comment]
Hello @adebayo-dealdey,

Did you follow the instructions to install the plugins?, updating both back and front applications, updating local.py and conf.json files, reloading your back...

**Comment by adebayo-dealdey** [comment]
Yes, I did, If reloading the back simply means restarting circus.

**Comment by superalex** [comment]
If the plugins section isn't shown it means your conf.json file isn't valid or isn't found...

**Comment by adebayo-dealdey** [comment]
My Conf.json file is in the taiga-front/dist/js directory

**Comment by superalex** [comment]
Is it possible you updated from 1.9.0 to 1.9.1? -> http://taigaio.github.io/taiga-doc/dist/upgrades.html the conf.json file location has changed slightly

**Comment by adebayo-dealdey** [comment]
How do i check my taiga version?

**Comment by bameda** [comment]
With `git describe --tags`

```
$ git describe --tags
1.9.0-stable-2-gfbe6fa9
```

**Comment by adebayo-dealdey** [comment]
I keep getting this error whenever I want to install requirements
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall
-Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat
-Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/libxml2
-Isrc/lxml/includes -I/usr/include/python3.4m
-I/home/ubuntu/.virtualenvs/taiga/include/python3.4m -c
src/lxml/lxml.etree.c -o build/temp.linux-x86_64-3.4/src/lxml/lxml.etree.o
-w

virtual memory exhausted: Cannot allocate memory

Compile failed: command 'x86_64-linux-gnu-gcc' failed with exit status 1

creating tmp

cc -I/usr/include/libxml2 -I/usr/include/libxml2 -c
/tmp/xmlXPathInit1zlrzhc2.c -o tmp/xmlXPathInit1zlrzhc2.o

cc tmp/xmlXPathInit1zlrzhc2.o -lxml2 -o a.out

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
  Rolling back uninstall of lxml
Cleaning up...
Command /home/ubuntu/.virtualenvs/taiga/bin/python3.4 -c "import
setuptools,
tokenize;__file__='/home/ubuntu/.virtualenvs/taiga/build/lxml/setup.py';exec(compile(getattr(tokenize,
'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))"
install --record /tmp/pip-s5ua704k-record/install-record.txt
--single-version-externally-managed --compile --install-headers
/home/ubuntu/.virtualenvs/taiga/include/site/python3.4 failed with error
code 1 in /home/ubuntu/.virtualenvs/taiga/build/lxml
Storing debug log for failure in /home/ubuntu/.pip/pip.log

**Comment by superalex** [comment]
Probably you don't have enough RAM -> https://taigaio.github.io/taiga-doc/dist/#requirements

>The main Taiga hardware restriction is having at least 0.75 GB of RAM. When installing the python >requirements, the package lxml will use gcc for building itself and fail if there is not enough memory.

**Comment by adebayo-dealdey** [comment]
I am using a AWS EC2 server and it has more than enough RAM to use. My
taiga-front is still showing 1.9.0-stable-2-gfbe6fa9. Is that the current
stable version for taiga-front?

**Comment by superalex** [comment]
It seems that it hasn't got enough free memory...

The current tag should be:

```
$ git describe --always --tag                                                                                                                                                                              
1.9.1-stable
```

**Comment by adebayo-dealdey** [comment]
Can I have your skype ID so we talk from there?

**Comment by superalex** [comment]
No sorry, we don't have a private support system but we can keep the conversation public using this github issue or the public mailing list ;)

**Comment by adebayo-dealdey** [comment]
Okay, do I have to replace every occurrences of localhost and 127.0.0.1 in
production server installation with the domain url?

**Comment by adebayo-dealdey** [comment]
@bameda  
Is because you are using the documentation of the dev version. Use this:

https://github.com/taigaio/taiga-contrib-slack/tree/stable
https://github.com/taigaio/taiga-contrib-gogs/tree/stable
https://github.com/taigaio/taiga-contrib-hipchat/tree/stable

The documentation has changed.

**Comment by bameda** [comment]
¿?

**Comment by adebayo-dealdey** [comment]
@bameda I fixed that already, thanks.

my new question is pertaining to the invitation emails been sent incase the user do not exist on the platform: 

The invitation email on my production server returned an error page if its been clicked
![image](https://cloud.githubusercontent.com/assets/16304032/12190479/6442a71e-b5c9-11e5-9834-2eda14ed4867.png)

while the default taiga.io returns
![image](https://cloud.githubusercontent.com/assets/16304032/12190503/7cdb5ac8-b5c9-11e5-8cb7-d5dee759985d.png)

when clicked

why?

**Comment by superalex** [comment]
Hello!, that error page seems to be shown by your web server, could you show us an invitation link sent by your platform?. I assume you configured Taiga with nginx, isn't it?

**Comment by adebayo-dealdey** [comment]
@superalex @bameda Yes, I configured it with nginx, the link is in this form: http://http//<domain>//invitation/aeed36a8-b5bf-11e5-b26a-02e777bc3367

**Comment by adebayo-dealdey** [comment]
I fixed it already, the problem is from the local.py SITE["front"]["domain"] should not contain http:// and trailing / . It shouln't be http://<domain>/ but <domain>

**Comment by superalex** [comment]
Great! ;)

**Comment by adebayo-dealdey** [comment]
I think that should be taken care of in the documentation... I also have few adjustments to make concerning some lines of documentation (installation procedure) can I be a collaborator?

**Comment by superalex** [comment]
Sure, you can make pull requests to the taiga-doc repo -> https://github.com/taigaio/taiga-doc

Regards!,

**Comment by adebayo-dealdey** [comment]
Okay, thanks. When I navigate to the http://[domain]/events it tells me `Update Required`, whats that suppose to mean? I checked all available repo i pulled, it has the latest git tags.

**Comment by superalex** [comment]
Why should you browse to http://[domain]/events?, taiga-events is the websockets gateway to show real time changes on Taiga.

Regards!,

**Comment by adebayo-dealdey** [comment]
Was just checking if it has a UI display for those changes, thanks.  Is there a documentation to use slack with taiga? not integration but how to use it, i assume I have to put #channel before conversations to be able to pass info through the channel

**Comment by superalex** [comment]
Yes!, we have this support page explaining it -> https://taiga.io/support/slack-integration/

**Comment by adebayo-dealdey** [comment]
@superalex @bameda What is the Authorization callback URL for github by default in taiga?

**Comment by superalex** [comment]
Hello @adebayo-dealdey you can find the full instructions about how to configure the github plugin here -> https://taiga.io/support/github-integration/

**Comment by adebayo-dealdey** [comment]
@superalex I am talking about github auth integration, it didn't include the callback URL for taiga

**Comment by superalex** [comment]
Sorry, I didn't understand your question, just the base url for your instance. For example for taiga.io we use: https://tree.taiga.io

**Comment by adebayo-dealdey** [comment]
@superalex @bameda Thanks.

**Comment by dennisroy-glofleet** [comment]
@superalex @bameda https://github.com/login/oauth/authorize?client_id=null&redirect_uri=http://[domain]/login&state=github&scope=user:email

Thats the URL that is been redirected to when I want to login to GitHub, the client_id is null and it's been supplied in my local.py file.

**Comment by superalex** [comment]
@dennisroy-glofleet did you update the gitHubClientId in your conf.json file too? (https://github.com/taigaio/taiga-contrib-github-auth#taiga-front)

**Comment by dennisroy-glofleet** [comment]
@superalex thanks so much, you just saved me enough time (y)

**Comment by superalex** [comment]
you are welcome! ;)

**Comment by adebayo-dealdey** [comment]
@superalex @bameda How do I integrate toggl with my version of taiga?

**Comment by bameda** [comment]
@adebayo-dealdey https://support.toggl.com/toggl-button-chrome-extension/

**Comment by bameda** [comment]
And @adebayo-dealdey your questions have nothing to do with this issue so please, use our mailing list https://groups.google.com/forum/#!forum/taigaio to talk about setup and configuration problems or whatever you want.

Thank you very much.
