### ISSUE TITLE
Sorting tasks in sprint tasksboard doesn't reflect inside the user stories views.

### ISSUE THREAD

**Issue by iknite** [taigaio/taiga-front#398]
Hi!

So having an US with N tasks, then inside the Sprint TaskBoard it can be sorted, but inside his own US View it doesn't. 
I think it should keep the defined sorting and gain the ability to be sorted inside the User Story view. 

It makes sense? 
kudos

**Comment by superalex** [comment]
Hello @iknite,

I think it makes sense, I'm adding it as possible enhancement for Taiga and the team will review it.

Thanks for your feedback and suggestions!

**Comment by Noogic** [comment]
+1 to this

**Comment by mathieu-b** [comment]
+1
