### ISSUE TITLE
permit user to upload picture directly fom wiki

### ISSUE THREAD

**Issue by allan-simon** [taigaio/taiga-front#40]
Hello though this feature is "trivial" to say, it's reason why our company has discarded some wiki in the past, as we have "non computer people"  that needs to write documentation etc.,  being able to upload directly image improve greatly the workflow rather to need to stop, upload the image somewhere, copy the link etc.

**Comment by shishi** [comment]
:+1:

**Comment by hgfischer** [comment]
:+1: :+1: :+1: :+1: :+1:

**Comment by chiarabroggi** [comment]
:+1:

**Comment by gabbork** [comment]
:+1:

**Comment by allan-simon** [comment]
I would like to add that in a wiki I used to implement a long time ago , what i did was that in the  "link image" button of the wysiwyg,  i added a upload file option , that use the same api than the normal "upload file" and directly put the uploaded file link in the  markdown link

**Comment by bameda** [comment]
This and more features over attachments will be in the next release

https://github.com/taigaio/taiga-front/commit/50af4483050087e3fb9bf1007dfac59f2f87a793
