### ISSUE TITLE
Move the close button in kanban edit and assign screens more close to the center 

### ISSUE THREAD

**Issue by bitnukl** [taigaio/taiga-front#403]
I like using the kanban view on a large 4k monitor. (And it is beautiful btw)
In my scaling the close button on the edit and assign overlay is really far away. Like really, really far. :-)

Any chance to move it more close to the center where all the other content is? Even on normal resolution it looks misplaced to me.

**Comment by superalex** [comment]
Thanks @bitnukl we will study it with the UX and design people! :+1:

**Comment by bameda** [comment]
And remenber that you can press ESC key to close them
