### ISSUE TITLE
Not filtering by new.

### ISSUE THREAD

**Issue by CMLL** [taigaio/taiga-front#404]
After the last update, 1.6.0, the front end is not appending the status param to the request url when using the new status type, resulting in no filter when selecting the new status. It worked for every other filter selected but no with new.

We checked the log  and confirmed that when setting the closed and rejected filter the status was appended, but not with the new.

Closed:
[18/Mar/2015 19:50:08] "GET /api/v1/issues?page=1&project=9&status=60
HTTP/1.1" 200 25100

New:
[18/Mar/2015 19:50:14] "GET /api/v1/issues?page=1&project=9 HTTP/1.1"
200 23698

![screenshottaiga](https://cloud.githubusercontent.com/assets/3720126/6717943/60393f2e-cd86-11e4-87b2-df06c77f0fdb.png)

With @jventuravs

**Comment by superalex** [comment]
Hello @CMLL could your browser be caching the content?, I can see you have different icons in the "Subject or reference", "Filters > status". Is it happening in different browsers and different machines?

How did you update the front app?

**Comment by jventuravs** [comment]
Hi @superalex, I was the one doing the upgrade. We were using taiga-front and changed to taiga-front-dist. Also, we migrated from 1.4 to 1.6 (back and front).

We'll let you know tomorrow if there's a problem with the browser/caching.

**Comment by superalex** [comment]
Ok @jventuravs, 

Just a fast question, if you moved from taiga-front to taiga-front-dist, did you update the nginx configuration?

**Comment by CMLL** [comment]
Hi @superalex you were right, it was the cache, I cleaned it and is working correctly. Thanks for your help.

**Comment by superalex** [comment]
You are welcome! :+1:
