### ISSUE TITLE
Changing slug name in public project points to 404

### ISSUE THREAD

**Issue by cnicodeme** [taigaio/taiga-front#405]
Hi,

I created a public project on Taiga.io and it was available when not connected (I tried it with private browsing). I decided to change the name to something better and now the project redirects to a 404 for non connected users (https://tree.taiga.io/project/2leadin/).

The project is marked as public so it should be available to everyone right ? even non connected users ?

Thanks for the reply.

**Comment by jespino** [comment]
Hi @cnicodeme, sorry about this, we have "removed" the public view of public projects, because some people has view public projects on his project lists (because they are using the previous front version from the browser cache). We'll re-enable the public projects visualization soon.

**Comment by cnicodeme** [comment]
Hi Jespino, thank you for the feedback. Do you have an ETA for that?

I find Taiga very useful to showcase to my customers what is planned (Kanban) and the current issues they can view/open without having to share with them the repo from Github/Bitbucket/etc. 

It's a great project and I can't wait to put the Taiga link to my project ... in my project ! :)

**Comment by superalex** [comment]
Hello @cnicodeme,

We would like to include it in the following release (1.7.0) or in the worst case scenario in (1.8.0). We would like it to release it as soon as possible to make Taiga project public! :)

**Comment by cnicodeme** [comment]
Awesome! Thank you very much! :)
