### ISSUE TITLE
Custom Fields label misplacement in firefox

### ISSUE THREAD

**Issue by iknite** [taigaio/taiga-front#406]
Hi guys!

Check the Name / Description labels in the screenshot below. 

![screenshot from 2015-03-19 10 18 34](https://cloud.githubusercontent.com/assets/745710/6727345/7d929fac-ce21-11e4-8704-61a911691008.png)
```
USER_AGENT = Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0
```

**Comment by iknite** [comment]
Nevermind, I see it properly now. Something load realated?

**Comment by superalex** [comment]
Probably css's were cached :(
