### ISSUE TITLE
permit admin to put the company logo/project logo

### ISSUE THREAD

**Issue by allan-simon** [taigaio/taiga-front#41]
trivial things but in some companies, management people first remark when you try to push a new tool is "can you change the logo by ours",  and as its the same management people that will agree or not for the company to use that tool ....

**Comment by Xaviju** [comment]
This should be already working

**Comment by omkartelee08** [comment]
does it works ? or any new way appeared by now?

**Comment by shubhpy** [comment]
@Xaviju @jespino 
How is it working?
What is the new process of doing that?
Thanks

**Comment by lifenautjoe** [comment]
Hello? Where can this setting be changed?

**Comment by spazdic1787** [comment]
Yes and new info this is important changing the login page to match self hosted company logo and tagline is definitely needed.
