### ISSUE TITLE
Email Images

### ISSUE THREAD

**Issue by tomchavakis** [taigaio/taiga-front#410]
Images at email  doesn't appear  when the taiga front installation is not connected to the internet.

**Comment by superalex** [comment]
Hello @tomchavakis,

The problem is that embedding the images wouldn't work here neither (https://www.campaignmonitor.com/blog/post/3927/embedded-images-in-html-email)

Do you have any idea about what should we do in this situation?

**Comment by tomchavakis** [comment]
I suppose that if the image is in a local directory  or in the database as binary you can include it in the mail template.

**Comment by superalex** [comment]
I think you can only send a link to the image, in my previous link you can see that embedding them in the email won't work in a lot of scenarios. If the image is in a local url it could work in some scenarios, it would depend on your email client, gmail tries to proxy every image (this one won't work).

I think there is no good solution if your instance isn't connected to the internet except disabling images.

By the way, could you check the url of the images associated to the emails?.

Regards,

**Comment by Trefex** [comment]
Is it possible to de-activate images in the emails sent?

**Comment by superalex** [comment]
It could be possible @Trefex but it would require some work to be done in the core. I'm thinking at least adding a setting for including images or not and considering it in the email templates.

**Comment by Trefex** [comment]
@superalex i think is still an issue then. Private installations that are not visible on the internet will have no images shown. The option to remove them would increase the UX.

**Comment by superalex** [comment]
I know @Trefex :)
