### ISSUE TITLE
Support for task dragging on touch screens

### ISSUE THREAD

**Issue by eddie-dunn** [taigaio/taiga-front#411]
At my company we are running Taiga on a projector with touch functionality. In Chrome/ium, which supports touch scrolling, it is not possible to use touch for dragging tasks to different categories. In Firefox, where touch scrolling is not enabled, this is possible.

Is it possible to modify the java script in the front end so that tasks can be dragged even when touch scrolling is enabled in the browser?

**Comment by superalex** [comment]
Hello @eddie-dunn 

Sorry buy actually Taiga hasn't been properly tested  in touch screens.

**Comment by zach-capalbo** [comment]
This seems pretty easy to do using [JQuery Touch Punch](https://github.com/furf/jquery-ui-touch-punch). I've done it in a fork here, to test it: https://github.com/zach-capalbo/taiga-front/commit/4d6164915e7d7e064165849814073b5ee121c885

**Comment by superalex** [comment]
Thank you @zach-capalbo 

Could you make a pull request to taiga-front so we can check/test it with our front people?

Regards,

**Comment by Xaviju** [comment]
Fixed here thanks to @zach-capalbo https://github.com/taigaio/taiga-front/commit/1d1152577313189452df64592c5c07720a0b0047
