### ISSUE TITLE
Can connect to taiga-front from host machine only

### ISSUE THREAD

**Issue by rpatni** [taigaio/taiga-front#415]
Hi..

I am facing the same issue as #367. I completed the installation on Ubuntu 14.04 VM as per http://taigaio.github.io/taiga-doc/dist/setup-production.html

1. I am using a VM on Azure and have created TCP end points for port 80, 8000 & 8001.

2. When I try to connect from an external system, I get the oompa loompas error message with the Js console showing:
http://localhost:8000/api/v1/projects Failed to load resource: net::ERR_CONNECTION_REFUSED

3. When I try to connect from the server using lynx localhost, I get a proper response with no errors

4. When I try to connect from the server using lynx locahost:8000/api/v1/, I get the following error:
    Looking up  'localhost' first
    Looking up localhost first
    Looking up localhost:8000
    Making HTTP connection to localhost:8000
    Alert!: Unable to connect to remote host.
    lynx: Can't access startfile http://localhost:8000/api/v1/

5. When I try to connect from the server using lynx locahost:8000/api/v1/, I get the following error:
     502 Bad Gateway
     nginx/1.4.6 (Ubuntu)

6. My conf.json for front end follows:
    {
    "api": "http://xxxxx.cloudapp.net/api/v1/",
    "eventsUrl": "ws://xxxxx.cloudapp.net/events,
    "debug": true,
    "publicRegisterEnabled": true,
    "feedbackEnabled": true,
    "privacyPolicyUrl": null,
    "termsOfServiceUrl": null,
    "maxUploadFileSize": null,
    "contribPlugins": [],
    "debugInfo": false
    } 

7. app-loader.js shows:

    (function() {
    var promise, version;
    version = 1426845020297;

     window.taigaConfig = {
     "api": "http://localhost:8000/api/v1/",
     "eventsUrl": null,
     "debug": true,
     "publicRegisterEnabled": true,
     "feedbackEnabled": true,
     "privacyPolicyUrl": null,
     "termsOfServiceUrl": null,
     "maxUploadFileSize": null,
     "contribPlugins": []
      };

      promise = $.getJSON("/js/conf.json");

      promise.done(function(data) {
      return window.taigaConfig = _.extend({}, window.taigaConfig, data);
      });

     promise.always(function() {
     var plugins;
      if (window.taigaConfig.contribPlugins.length > 0) {
      plugins = _.map(window.taigaConfig.contribPlugins, function(plugin) {
        return plugin + "?v=" + version;
      });
      return ljs.load(plugins, function() {
        return ljs.load("/js/app.js?v=" + version, function() {
          return angular.bootstrap(document, ['taiga']);
        });
      });
      } else {
       return ljs.load("/js/app.js?v=" + version, function() {
        return angular.bootstrap(document, ['taiga']);
        });
      }
    });

    }).call(this);

8. local.py for taiga-back has all url's changed to xxxxx.cloudapp.net

9. nginx settings follow:

    server {
      listen 80 default_server;
      server_name _;

    large_client_header_buffers 4 32k;
    client_max_body_size 50M;
    charset utf-8;

    access_log /home/xenon/logs/nginx.access.log;
    error_log /home/xenon/logs/nginx.error.log;

    \# Frontend
    location / {
        root /home/xenon/taiga-front-dist/dist/;
        try_files $uri $uri/ /index.html;
      }

    \# Backend
    location /api {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://127.0.0.1:8001/api;
        proxy_redirect off;
    }

    \# Django admin access (/admin/)
    location /admin {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://127.0.0.1:8001$request_uri;
        proxy_redirect off;
    }

    \# Static files
    location /static {
        alias /home/xenon/taiga-back/static;
    }

    \# Media files
    location /media {
        alias /home/xenon/taiga-back/media;
    }
    }

Please let me know how to fix the error!?

**Comment by bameda** [comment]
Hi @rpatni, would you please send your question to the mailing list?  https://groups.google.com/forum/#!forum/taigaio

We are trying to use github only for bugs and the mailing list for support and questions.

We have a support page with some useful information too at https://taiga.io/support/

Thank you very mutch.

**Comment by rtorino** [comment]
I'm getting the same error. I tried to debug and found out that the default config was not overridden by the the conf.json even though ```_.extend({}, window.taigaConfig, data);``` was returned on the ```promise.done``` callback. This callback is never executed when I tried to put break points on it, that's why the value ```window.taigaConfig``` is still the same.

**Comment by juanfran** [comment]
@rtorino thanks for the info, that's usually because the config.json is in a wrong place or the config.json has a syntax problem

**Comment by sivasai519** [comment]
Hello @bameda 
after restarting the nginx server 
i am connecting with http://192.168.1.248/api/v1/ 
i am getting this error 
The page isn’t redirecting properly in the browser.
thank you
