### ISSUE TITLE
Creating links to other wiki pages

### ISSUE THREAD

**Issue by blt909** [taigaio/taiga-front#416]
Hi,

I've completed the installation of Taiga on my own server and I'm now testing the wiki.
I tried to generate a link between my home wiki page and an other one with this syntax : 
```markdown
[[my-slug|My Slug]]
```
Once saved, the wiki page has a link with this url : 
```
http://localhost:8000/project/<my project>/wiki/my-slug
```
Where can I find the parameter to rewrite the url with my host?

**Comment by bameda** [comment]
Hi @blt909 , would you please send your question to the mailing list?  https://groups.google.com/forum/#!forum/taigaio

We are trying to use github only for bugs and the mailing list for support and questions.

We have a support page with some useful information too at https://taiga.io/support/

Thank you very mutch.
