### ISSUE TITLE
Go back to page 1 by Issues

### ISSUE THREAD

**Issue by mgoebel-tgm** [taigaio/taiga-front#419]
Our project is getting large and we have lots of issues and ToDO's, so we need page 2.
The problem is: We can't go back to page 1 because the button don't handle anything.
Our solution: We go back to Backlog, wait a sec, go back to Issues.

**Comment by superalex** [comment]
Hello @mgoebel-tgm,

Is your project in our Taiga instance (tree.taiga.io) or in a private one. It it's int tree.taiga.io, could you please write to support@taiga.ia with the name of the project so we can check what's happening please?

Regards

**Comment by mgoebel-tgm** [comment]
Thank you I will write a email.
Regards

**Comment by superalex** [comment]
Hello @mgoebel-tgm, could you write that email?

Regards,

**Comment by mgoebel-tgm** [comment]
Sorry I tried it several times but got a mail-delivery-failed-email.

**Comment by superalex** [comment]
Thanks!, we just received your email, it seems there is a bug if there are only two pages, we'll try to solve it as soon as possible
