### ISSUE TITLE
Unnecessary cookie usage

### ISSUE THREAD

**Issue by Crawleyprint** [taigaio/taiga-front#421]
I've inspected cookie on taiga.io and, unless I'm wrong, I don't see why the info there needs to be stored in a cookie as opposed to localStorage. The only relevant key in cookie is `i18next` which could be moved to localStorage by setting `useCookie` to `false` and `useLocalStorage` to `true` in `$i18nextProvider.options`.

**Comment by superalex** [comment]
You are right, they should be moved to localStorage.

Thanks!

**Comment by Crawleyprint** [comment]
You're welcome. I'd gladly write a PR, but I'm not friends with coffeescript...

**Comment by superalex** [comment]
Well, if you are good at javascript coffeescript will be really easy for you, there are also some tools for translating js to coffee like -> http://js2.coffee/

Regards,
