### ISSUE TITLE
Taskboard "view my tasks only"

### ISSUE THREAD

**Issue by realbazso** [taigaio/taiga-front#422]
Hi,

Enhancement:
I have many user stories with many tasks in each. This makes the taskboard really big. My team members would like to have a filter or a separated "My tasks" view somehow to let them focus on their own tasks.
Thank you.

**Comment by realbazso** [comment]
I've tried to remove the right to view the tasks, but it made hidden their own tasks as well.

**Comment by superalex** [comment]
Hello @realbazso, adding a "My tasks" section in the user home is something we are working on just now, and filtering the taskboard is another feature we would like to work on.

Regards!,

**Comment by realbazso** [comment]
Great, thank you :)
I was hoping that I'm not the only one missing this, as I'm not the main target customer of taiga. Instead of development I'm managing an architect team with it.

Best wishes for this great product.

**Comment by superalex** [comment]
Thank you very much for your feedback @realbazso :+1:

**Comment by NickvdMeij** [comment]
I +1 this

**Comment by me-snail** [comment]
much needed feature

**Comment by superalex** [comment]
Working on it! :)

**Comment by andrewtennison** [comment]
is there a task/issue were I can track when this feature will be complete?

**Comment by bameda** [comment]
https://tree.taiga.io/project/taiga/us/1775
https://tree.taiga.io/project/taiga/us/2256

Regards

**Comment by DrozdovNik** [comment]
Hi bameda, Hi everybody, 
I've tried to open the links from the last message, but both of them are outdated. 
Could you please advice - is there a such function like "show my tasks" in Taiga?

> https://tree.taiga.io/project/taiga/us/1775 https://tree.taiga.io/project/taiga/us/2256
> 
> Regards
