### ISSUE TITLE
Bug: Adding a nonexistent user to a project

### ISSUE THREAD

**Issue by realbazso** [taigaio/taiga-front#423]
Hi,

After adding a nonexistent user to the project one gets an email, but after registration one is not assigned with the project. After successfull registration I have to delete the user invitation from the project and create a new one - this way the user joins nicely.
(The user needs to be registered first)
Thank you.

**Comment by superalex** [comment]
Hello @realbazso,

Is it working in tree.taiga.io or in your own instance?

**Comment by realbazso** [comment]
Hi,

own instance based on this docker image:
https://registry.hub.docker.com/u/htdvisser/taiga-back/
and its frontend.

**Comment by superalex** [comment]
Could you check what branches for taiga-back and taiga-front repos are deployed in your instance?.

Could you also paste here the value of PUBLIC_REGISTER_ENABLED in taiga-back (settings/local.py) and the publicRegisterEnabled from taiga-front (dist/js/conf.json) ?

**Comment by realbazso** [comment]
This is the whole content of local.py:

```
from .common import *

from .dockerenv import *

# THROTTLING
#REST_FRAMEWORK["DEFAULT_THROTTLE_RATES"] = {
#    "anon": "20/min",
#    "user": "200/min",
#    "import-mode": "20/sec"
#}
```

And the conf.json:

```

{
  "api": "/api/v1/",
  "eventsUrl": null,
  "debug": false,
  "publicRegisterEnabled": true,
  "feedbackEnabled": true,
  "privacyPolicyUrl": null,
  "termsOfServiceUrl": null,
  "maxUploadFileSize": null,
  "gitHubClientId": null,
  "contribPlugins": [ ]
}

```

**Comment by realbazso** [comment]
Both front and back are from the master branch

**Comment by superalex** [comment]
Could you try adding PUBLIC_REGISTER_ENABLED = True to your local.py and restarting circus:
```
circusctl restart taiga
```

**Comment by realbazso** [comment]
Same state.

**Comment by superalex** [comment]
Could you please trying moving both apps to the stable branches?. We are trying to reproduce your issue but we can't :(
