### ISSUE TITLE
Bug: Issue list page switch doesn't work

### ISSUE THREAD

**Issue by realbazso** [taigaio/taiga-front#424]
Hi,

After having a long issue list there are page switcher numbers at the bottom of the page. Clicking on the numbers doesn't refresh the page.
Thank you.

**Comment by superalex** [comment]
Hello @realbazso,

Is it working in tree.taiga.io or in your own instance?, if it's a tree.taiga.io instance, could you write us an email indicating what's your project slug?

Regards,

**Comment by realbazso** [comment]
Hi,

Own instance based on this docker image:
https://registry.hub.docker.com/u/htdvisser/taiga-back/
and its frontend.

**Comment by superalex** [comment]
Could you move taiga-back and taiga-front to stable branches and rebuild taiga-front (gulp deploy) ?
