### ISSUE TITLE
Colour picker disappears off the bottom of the screen

### ISSUE THREAD

**Issue by umacher** [taigaio/taiga-front#425]
When editing the colours for the Status attributes, editing the last status colour (Issue Status' - "Postponed") will scroll the colour picker off the bottom of the screen

https://tree.taiga.io/project/.../admin/project-values/status
- scroll down to the bottom of the page, edit the last status and change the colour

**Comment by Xaviju** [comment]
Hi @umacher 
What browser are you using?
Currently tested on Chrome and firefox and (even if has an issue) is not unusable, just adds some scroll pixels at the bottom.

**Comment by Xaviju** [comment]
Since its not generating any more bugs and wee addedsome more space to fit the color picker, I close this issue
