### ISSUE TITLE
Stakeholder can "edit" assigned tasks

### ISSUE THREAD

**Issue by Jokipii** [taigaio/taiga-front#431]
As a stakeholder a person can see and edit the people the tasks are assigned to. The information however does not save and will remain as original when visited the task/ page again.

Issue: Stakeholder can "edit" assigned tasks for a brief moment (without making actual changes to the original task)

**Comment by superalex** [comment]
Hello @Jokipii ,

By default Stakeholder role has only view permissions for tasks, the web app should let you to modify the assigned user, where are you updating them?, in the task detail?
