### ISSUE TITLE
Taiga crashes while on Admin>Plugins page

### ISSUE THREAD

**Issue by pksh** [taigaio/taiga-front#432]
When an user clicks on to get to the Plugins menu, the page appears to load in a continous loop and eventually crashing the browser. 
Branch: taigaio/taiga-front [stable] with github-auth plugin
Tested on Mac OSX (Yosemite): 
Mozilla Firefox v37.0.1
Chrome v41.0.2272.118 
Opera v27.0.1689.69

Screenshot
![taigaio](https://cloud.githubusercontent.com/assets/3693303/7113663/05c72504-e1ce-11e4-8860-6c16fb2f7fdd.png)

**Comment by superalex** [comment]
Hello @pksh, 

You have your own instance, isn't it?, could you us the contribPlugins line from your conf.json please?

**Comment by pksh** [comment]
certainly.. it goes like:
"contribPlugins": ["/js/github_auth.js"]

**Comment by bameda** [comment]
Yep, I have the same problems with the same plugin in master branch

**Comment by superalex** [comment]
I have the same problem when enabling multiple plugins and githubauth is the last one, we'll solve it as soon as possible!

**Comment by superalex** [comment]
@bameda I think this PR solves the problem https://github.com/taigaio/taiga-front/pull/435, could you check it please?. When merged to master we will backport it to stable :+1:

**Comment by astagi** [comment]
@superalex your PR fixes the problem here!

**Comment by superalex** [comment]
Thanks @astagi ! :)

**Comment by superalex** [comment]
Great!, backported to sable :)
