### ISSUE TITLE
Clickable links in 'Issues' should always be visible, even on smaller resolutions

### ISSUE THREAD

**Issue by SpacyRicochet** [taigaio/taiga-front#437]
I currently have my browser screen with Taiga open at 75% of my screen width and the issues aren't clickable anymore. 

![screen shot 2015-04-15 at 11 16 16](https://cloud.githubusercontent.com/assets/904596/7155745/55d7f228-e361-11e4-899d-5cd503646435.png)

The links should always be visible (and clickable), since they're the most important information to read at a glance and the only method of going to the issue detail.

**Comment by superalex** [comment]
Thanks @SpacyRicochet, the minimum supported resolution in Taiga should be 1024x768 and it's not working on issues listing, we'll fix it as soon as possible

**Comment by Xaviju** [comment]
Fixed in this PR https://github.com/taigaio/taiga-front/pull/458
