### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by amiraliakbari** [taigaio/taiga-front#443]
My taiga installation (self hosted) is used by users speaking Farsi (fa) which is a right-to-left language. I know supporting RTL is a big task, but there are some parts of the UI that adding a simple `direction: rtl` to it will improve the usability for RTL users a lot (e.g. US details: `section.us-content`).
My current solution is to patch the files locally and add a few CSS classes. Is there a planned approach for including a set of CSS files and classes if the active language is RTL?

**Comment by superalex** [comment]
Hello @amiraliakbari,

We actually had no plans for adding RTL support but if you want to work on that feature and make a pull request for Taiga it could be great! :+1: 

Regards,

**Comment by jespino** [comment]
I think this can be done through the new feature (not yet finished #504) of themes, which allow you to redefine all the css of the page. An RTL based template maybe a first aproach :smiley:

**Comment by Xaviju** [comment]
We could use this postcss plugin to create a simple RTL theme: https://github.com/MohammadYounes/rtlcss

**Comment by dorad007** [comment]
Is there any progress?

**Comment by superalex** [comment]
Still not, sorry!

**Comment by Xaviju** [comment]
Hi @dorad007 Taiga now supports themes. The community could create a nice RTL theme.
After being tested by some users, we could pack it into the official Taiga themes.

Anybody up for helping with this?

**Comment by dorad007** [comment]
Tell me what to do and i will try to make time performing it.

**Comment by Xaviju** [comment]
There is info on the docs on how to create custom themes: http://taigaio.github.io/taiga-doc/dist/#themes

Thanks @dorad007

**Comment by sepehr** [comment]
This is not about themes! 

We use a LTR taiga theme, but we need markdown RTL support for wiki pages.

**Comment by Xaviju** [comment]
Hi @sepehr I think the issue of @amiraliakbari was related to the whole theme. If you are already using a RTL theme it would be nice to share it with other RTL users. Would you?

**Comment by sepehr** [comment]
Hey @Xaviju,

I see now; yes it's about themes, my issue was related to markdown RTL support.

We don't have a RTL theme for Taiga; will share for sure if we develop one in the future.

**Comment by Xaviju** [comment]
Thanks @sepehr it would be very useful :smiley:

**Comment by alexhermida** [comment]
We close this issue since Taiga currently supports RTL (since version 3.3.9). We'll continue to improve some RTL styles but it's generally implemented.

**Comment by vaheeds** [comment]
recently I host taiga on my ubuntu machine, but when I change th language to Farsi, nothing happen to style of the page but labels text change to Farsi. I see the rtl is working great on the hosted version at https://tree.taiga.io.  what do I miss?

**Comment by AnasGhrab** [comment]
@vaheeds I also have to same problem. The RTL in Markdown is not working.. maybe I've missed something... Did you find any solution ?
