### ISSUE TITLE
Custom theme settings

### ISSUE THREAD

**Issue by astagi** [taigaio/taiga-front#444]
Hi,

I'd like to add a configuration option to override the main theme (e.g. in Nephila we experimented a new theme https://github.com/nephila/taiga-front/commit/097d5838bbee97ed4179ef01f4abd2c8350ad4c9). I'll work on this little feature, is it ok for you?

**Comment by superalex** [comment]
Allowing custom themes in Taiga would be a cool feature, we think it's great if you work on it :)

**Comment by Xaviju** [comment]
How is this supposed to work? 
Only overriding Taiga theme is not going to satisfy most of the users and its not good for CSS performance. I don't know how crazy is this, but I like the Wordpress model here (not all the features, but the concept).

What do you think?

**Comment by astagi** [comment]
Hi @Xaviju I think that people would like to override main colors, logos, things like these, building their own theme and instead of modifying the code they just use settings specifying an additional css to use. I am not a css expert, why is it a problem for performances? What do you mean with wordpress model, any examples?

**Comment by Xaviju** [comment]
Not sure, I am asking myself what would be the model.
- Will users only override some colors, logos, etc?
- Will users want to create their own themes?

In the first case, your approach is correct, there is no big deal adding a new stylesheet.
In the second case, just adding a stylesheet could be a pain to develop.

The wordpress model means that they have a basic theme to work with and developers can duplicate it and edit it or add a new one (mantaining the default one) and a theme selector in the admin area.

I am not sure what will be the best option for the long-term. What do you think? And @superalex?

**Comment by astagi** [comment]
Users should be able to override only colors, logos, background, etc adding their own stylesheet. I like the Wordpress model, we could provide a basic scss to the developers where there are colors, logos and they can start from it to create their own theme, then they can put it in a themes/ folder and then select theme from admin (or in a configuration field).

**Comment by Xaviju** [comment]
That sounds nice! A blank theme.scss file where users can add their own styles and select it from an admin.  :smiley:  
In the future that theme creation could be directly in the UI.
Lets see what @superalex thinks about this but I like how it sounds so far.

Grazie!

**Comment by astagi** [comment]
Non c'è di che ;)

@Xaviju just a clarification: with blank theme.scss do you mean a single theme.scss file or one scss file per theme? something like:

    themes/
        theme.scss
        my-theme-1.scss
        company-x-theme.scss

I think that we should provide a theme.scss as a base, then developers can extend it.

**Comment by superalex** [comment]
+100000 "A blank theme.scss file where users can add their own styles and select it from an admin."

**Comment by Xaviju** [comment]
Yes, I was thinking in a single file with some variables that override Taiga's default variables and settings. Users can override that file or create a new one so they can create multiple themes and, of course, extend it as much as they want.
I'm not sure how hard it could be, so I'm just I'm just fantasizing:

1. We provide a default file ```blank-theme.scss``` with a minimum list of empty variables.
``` scss
// $green: Write here the main green color
// $hovergreen: Write here the hover green color
....
````
2. People could use it or create ```my-theme.scss``` duplicating this one and create their own theme as you wrote in your last comment (I guess every file is a different theme and they are not combined).
3. Then they should be able to choose one from a dropdown in the settings (_remember: I'm just fantasizing, it could be from a settings file_)
4. The file overrides default taiga settings and compiles the ```css``` with the new variables.

Is it too hard to do? Were you thinking in something else?

**Comment by astagi** [comment]
yes @Xaviju that's exactly what I had in mind :) I'll start working on it!

**Comment by Xaviju** [comment]
I think this could be an amazing feature for self-hosted Taiga's and for example, high contrast themes and so on... looking forward to it! :)

:+1:

**Comment by astagi** [comment]
thanks :)

**Comment by astagi** [comment]
Hi @Xaviju @superalex ,

I started looking at some solutions to implement themes, I wrote some code to compile and set custom themes using gulp (I included base theme and a fake nephila theme just to show an example): 

https://github.com/astagi/taiga-front/tree/feature/themes 

As you can see there's a themes/ folder with a folder per theme:

    themes/
        base/
            colors.scss
            items.scss
        nephila/
            colors.scss
            items.scss

This is not what we discussed in the previous conversation, this is another way to implement custom themes. It should be easy for developers to create their custom themes, the most common use case I can imagine is changing colors: with our previous solution it's not possible to change colors without redefining every single component, with my current solution they just have to rewrite colors.scss and if they want to change single components they just need to put them in items.scss. Anyway you can apply this solution only using gulp and not from an admin panel. To make it working from an admin panel the css generated should be put in a new file in 

    dist/styles/name_of_theme.css

e.g. 

    dist/styles/nephila.css

And load it on start instead of main.css.

There's a global variable 'current_theme', it won't be used in the final version, there will be e gulp task 'apply_theme' to set the current theme (maybe another task 'new_theme' to create a skeleton for a new custom theme would be nice).

What do you think?

**Comment by Xaviju** [comment]
To me its fine having a folder per theme. Default theme could be Taiga!
If I am not wrong you are saying that users will not be able to select the theme from the admin panel, instead there will be a gulp task were users will have to change the theme name and afterwards regenerate it so the theme is applied? (New Theme task is nice!)
I'm not completely happy with this behavior because that means that Taiga.io won't be able to provide a high contrast version or a funny pink-unicorns taiga but its nice for self-hosted platforms.

The code seems to be fine to me, not sure what @superalex or @bameda think about this. :+1:

**Comment by superalex** [comment]
I agree with @Xaviju, I was thinking about a solution that allows the user choosing between different themes but this would be great for self-hosted platforms (a lot of users with custom instances want to modify a little bit the css's).

**Comment by astagi** [comment]
Hi @Xaviju @superalex ,

they will be able to choose between different themes from the admin panel, no problem! I ended up with another solution: reuse the current code I wrote to compile all the themes in themes/ folder, generating a css file per theme, then it's easy to create a select to allow users to choose their favourite theme :) what about?

**Comment by Xaviju** [comment]
That sounds nice, looking forward to see it working!!

**Comment by superalex** [comment]
Great! :+1:  :+1:  :+1:  :+1:

**Comment by astagi** [comment]
Hi @Xaviju @superalex ,

thank you for your feedback :) I added some code to that branch, now users can select their favourite theme from admin! here's the backend support for themes: https://github.com/astagi/taiga-back/tree/feature/themes . The script is also able to auto detect themes in app/themes folder.
Available themes need to be registered in conf.json:

    {
        "api": "http://localhost:8000/api/v1/",
        /* ..... */
        "themes": ["main", "nephila", "unicorn"]
    }

I don't know gulp.js so much, do you know if there's a cleaner method to launch the same task for each folder? At the moment I just call task for each theme inside the existing task, for example:

    function style_theme(current_theme) {
        var _paths = [
            paths.tmp + "vendor.css",
            paths.tmp + "/themes/" + current_theme + "/app.css"
        ];
        return gulp.src(_paths)
            .pipe(concat(current_theme + ".css"))
            .pipe(gulpif(isDeploy, minifyCSS({noAdvanced: true})))
            .pipe(gulp.dest(paths.dist + "styles/"))
    }

    gulp.task("styles", ["css-app", "css-vendor"], function() {
        availableThemes.forEach(function(theme) {
            style_theme(theme);
        });
        var _paths = [
            paths.tmp + "vendor.css",
            paths.tmp + "app.css"
        ];
        return gulp.src(_paths)
            .pipe(concat("main.css"))
            .pipe(gulpif(isDeploy, minifyCSS({noAdvanced: true})))
            .pipe(gulp.dest(paths.dist + "styles/"))
    });

**Comment by juanfran** [comment]
thank you @astagi we have been talking about this and we have some ideas about how the gulpfile should work, we will try to do it this week and show it to you

**Comment by astagi** [comment]
thank you @juanfran ;)

**Comment by astagi** [comment]
Any updates there? :)

**Comment by juanfran** [comment]
no sorry, we have been very busy with some tasks. I hope to have time this week

**Comment by astagi** [comment]
no problem! :smile:

**Comment by juanfran** [comment]
i've done the changes in the gulpfile for custom themes https://github.com/taigaio/taiga-front/tree/custom-themes
```
gulp //work with the default taiga theme
gulp --theme theme_name //work with a custom theme name
gulp compile-themes //compile all themes
```
we will wait some feedback before making the profile theme selection.

What do you think?

**Comment by astagi** [comment]
Hi @juanfran your grunt file works very well! I just integrated it with my profile theme selection work (it was already in my branch :P) .

**Comment by bameda** [comment]
It's done

**Comment by dottorblaster** [comment]
Hi guys, when will this functionality be merged in stable?

**Comment by bameda** [comment]
@dottorblaster  It will be for next release, I hope in a couple of weeks.

**Comment by dottorblaster** [comment]
@bameda thank you very much :+1:

**Comment by bameda** [comment]
@dottorblaster you are welcome :smiley_cat:
