### ISSUE TITLE
User Profile image description - image not getting "cropped"

### ISSUE THREAD

**Issue by LinuCC** [taigaio/taiga-front#445]
Hi, this is a small one: 
Below the avatar in the user profile it is mentioned that "The image will be cropped to 80x80px.".
It should say scaled instead of cropped, because it does just that :)

**Comment by superalex** [comment]
Thank you very much @LinuCC, solved here -> https://github.com/taigaio/taiga-front/commit/a87805caf78ca46c86a474dff24baecd472bfe3c

Regards!

**Comment by LinuCC** [comment]
Yeop, that is correct. Its not on your service yet, but I guess it will be soon :)

**Comment by superalex** [comment]
Yes!, it will be soon released there too! ;)
