### ISSUE TITLE
Filter in backlog behaviour : only one filter possible (or as many as you can select in 1s.)

### ISSUE THREAD

**Issue by alopezg** [taigaio/taiga-front#447]
When you try to select a filter with the status or tags criteria, you can only select one from the list( the list is collapsed and no other choice is possible until removing filters). You could anyway select more than one if you do it quickly (< 1-2 seg.) it's for this reason I think this is an unexpected behavior (as the feature of allowing multiple selection is working well ... if you're fast enough ;) )
Tested on Chrome (Version 41.0.2272.89 (64-bit)) and Firefox (36.0.4) on Ubuntu 14.04

**Comment by bameda** [comment]
You are right, this is a critical bug. We try to fix up tomorrow (tomorrow in Spain ;-))

**Comment by mikaoelitiana** [comment]
Hello guys!! Have you fixed this? I want to work on this otherwise.

**Comment by mikaoelitiana** [comment]
I think this is fixed as I can't reproduce this bug anymore. The issue should be closed then.

**Comment by bameda** [comment]
yes

**Comment by bameda** [comment]
Yes is fixed, sorry but we use Taiga to manage issues and sometimes the issue can be open here but closed in Taiga

**Comment by mikaoelitiana** [comment]
Alright!! So if I want to contribute it's better to browse the taiga project, right?

**Comment by bameda** [comment]
yep
