### ISSUE TITLE
User Story buttons, no difference between hover and selected.

### ISSUE THREAD

**Issue by rodrigograca31** [taigaio/taiga-front#449]
When creating a new "User Story" there is no color difference between a selected hovered element button/option...

![as seen here](http://i.imgur.com/h5GVoD5.png)

The first one is selected and the second one is being hovered...

The "Blocked" option has two colors... This may be a design/preference problem but is also a UX problem...

**Comment by Xaviju** [comment]
Should be fixed here, https://github.com/taigaio/taiga-front/commit/0d4bee68a997bd0c70ac9a798dc52e7e5a4c0529

**Comment by rodrigograca31** [comment]
Nice! Thanks!
