### ISSUE TITLE
Formatted/multi-line custom fields

### ISSUE THREAD

**Issue by artlepool** [taigaio/taiga-front#451]
Hi

Thanks for adding the custom fields in to Taiga - they're great, just what we needed!

Something that would make them even better (from our point of view) would be providing multi-line and markdown support on a custom field. 

Essentially, enabling them to be used in the same way as the main Description field/textbox.

I appreciate the fact that you maybe don't want to overcrowd the User Story screen with lots of big multi-line text boxes, but before we moved across to using Taiga, we had two formattable (HTML and/or Markdown) multi-line text boxes to describe our user stories, ie.  a Description box and a separate Acceptance Criteria box.

We can combine these all in to the Description box in Taiga but would be nice to physically separate these two fields if possible. 

Thoughts?

**Comment by superalex** [comment]
This was our first approach to custom fields. We were thinking about defining types on them, if they are mandatory or not, different visualizations...But we prefered releasing a simple approach receive some feedback and see how it's used.

Thank you very much for your comments, we will consider them when working again in this part of Taiga! :+1:

**Comment by artlepool** [comment]
Thanks @superalex!

Wondering whether you'd accept a merge request for this?

All we'd really like is the simple ability to set a custom field to be single-line or multi-line.  Not too bothered about it being markdown-enabled etc.

I've made changes to my version of the code to render the input box for a custom field on a user story as a HTML Textarea tag instead of an Input tag, which is relatively simple change.

In the Admin panel where you create the custom field, you could have a checkbox where you say whether you want the field to be multi-line or not, as follows (note that the UI is not great, its just for illustrating!):

![screen shot 2015-05-05 at 16 10 06](https://cloud.githubusercontent.com/assets/8647257/7475797/ae2b7d60-f341-11e4-88ab-80f7847b5013.png)

When the input box for the custom field on a User Story/Task/Issue is rendered, you could check the Multi-line option and render as either Input or Textarea tag.

What do you think?

**Comment by Xaviju** [comment]
Sounds good to me! I suppose the only change that is made in the custom fields section is to change the input[text] for:
```
<textarea id="custom-field-description" name="description" ></textarea>
```
I am testing it in my local and looks good to me. Could you please make the pull request so we can test it?

**Comment by artlepool** [comment]
Great!

Do you think it is worth implementing the "Multi-line" configuration option?  As you say, the change is quite easy in taiga-front to swap input[text] for textarea.

But if we go with the Multi-line config, then thats a change to the custom_attributes model and requires a database migration, etc.  to store the flag value.

I'm happy to do this, I'm just confirming the scope of the enhancement..

**Comment by Xaviju** [comment]
This is a question for @superalex

**Comment by bameda** [comment]
Personally, I prefer a selector instead of a checkbox. In the future we
could easily add more types .

What do you think?


Regards


---


   *David Barragán Merino*
* Engineer *
<david.barragan@kaleidos.net>
 david.barragan@kaleidos.net  | Tel: (+34) 913562995
www.kaleidos.net/FFF8E7

**Comment by artlepool** [comment]
Yes good idea @bameda. Agreed, it makes sense for the future.

**Comment by superalex** [comment]
I agree too, a selector allows more fields in the future (something we would like to have for sure :D)

About the custom_attributes model I think there is no problem with updating the model if the necessary migrations are added.

Thank you very much @artlepool we will wait for your pull request! :dancer:

**Comment by artlepool** [comment]
Hi guys, looking for a bit of advice...

What are your thoughts on how to store the list of different custom field types?  I know that all the other lookup selector values (eg for issue types, user roles, etc) are customisable by the user in that they can add new types, roles.   
But the types of custom fields shouldn't really be changed by the user because each different field type needs to have the appropriate code to render it correctly in the user interface.

So would there need to be list of custom field types that the user is not able add/edit/remove types themselves? And if so, has this been done in Taiga before?

**Comment by bameda** [comment]
The list of types can not be editable. Some example:

- text (default).
- text area.
- markdown text area.

in the future we can add, for example:
- checklist
- select
- multiselect
- ... and so on

The api returns the custom field info (name and type) and the frontend
knows how to render it correctly by its type.

And no, there is nothing like this made in Taiga.

Regards.


---


   *David Barragán Merino*
* Engineer *
<david.barragan@kaleidos.net>
 david.barragan@kaleidos.net  | Tel: (+34) 913562995
www.kaleidos.net/FFF8E7

**Comment by jbingman** [comment]
It sounds like some of these options might be somewhere down the road but, it seems that it would also be useful to have support for dates, and attribute/Boolean values. We are evaluating Taiga for our organization and these are some of the things that our current solution does not support.

**Comment by superalex** [comment]
Thanks for sharing with us @jbingman :+1:

**Comment by artlepool** [comment]
Hi guys

See pull request #533 
and also taiga-back pull request 355

**Comment by artlepool** [comment]
Any feedback on this @superalex?  In a few days time I'll be disappearing and won't be in a position to contribute for a month, so would be interested in what you guys think..

cheers :-)

**Comment by superalex** [comment]
Sorry @artlepool 

Last week was a bit crazy with the last release, we'll try to tell you something today!, sorry!

**Comment by artlepool** [comment]
Thought that might be the case 😊 no problem @superalex!

**Comment by superalex** [comment]
Hello @artlepool , I've merged both pull requests, it's working great :)

Thank you very much!

**Comment by artlepool** [comment]
Great, thanks @superalex!

I've just pulled down taiga-back and taiga-front master branches to do a check myself, when I go to the Custom Fields admin screen, and try to add a new custom field, I see "undefined" in the Type dropdown (see image below)

Do you see this on your Taiga instance?

![screen shot 2015-06-23 at 09 17 12](https://cloud.githubusercontent.com/assets/8647257/8301765/f54bd420-1988-11e5-9aaf-ed0206b8fe2a.png)

**Comment by superalex** [comment]
Yes!, it fails for the new fields but not when editing an existing one...could you check what's happening please?.

Regards!,

**Comment by artlepool** [comment]
Found it!

Line 58 of `app/partials/includes/modules/admin/admin-custom-attributes.jade` needs to be:

```
ng-options="e.id as e.name | translate for e in [{'id':'TEXT', 'name': 'ADMIN.CUSTOM_FIELDS.FIELD_TYPE_TEXT'},{'id':'MULTI', 'name': 'ADMIN.CUSTOM_FIELDS.FIELD_TYPE_MULTI'}]")
```

Do you want me to create pull request or you happy to change in master?

**Comment by superalex** [comment]
Thank you very much @artlepool I've just changed it in master -> https://github.com/taigaio/taiga-front/commit/4d17ebdc33ccbde521930ff309185c9bb58576b1

**Comment by artlepool** [comment]
Cool :+1:  thanks!

**Comment by fboxwala** [comment]
Hi! I was wondering if there has been any more thought to having markdown-formattable custom fields?

This would really help our team - and might help to ameliorate many people's struggles with not being able to create dependency chains between stories, tasks, and issues ([taiga-back#154](https://github.com/taigaio/taiga-back/issues/154)).

If we could create a custom field, and call it "is blocked by" or "depends on" and have the field be markdown formatted, we could link to other stories automatically by their # (like we can do in the description box).
