### ISSUE TITLE
absolute paths vs relative paths

### ISSUE THREAD

**Issue by sitstde** [taigaio/taiga-front#453]
if  you put the frontend in an subdirectory on the server like http://myserver.org/taiga/
nothing works because taiga assumes every file it needs is located in the root directory like http://myserver.org/js/.... same with all other files and folders

**Comment by bameda** [comment]
Hi @sitstde , would you please send your question to the mailing list?  https://groups.google.com/forum/#!forum/taigaio

We are trying to use github only for bugs and the mailing list for support and questions.

We have a support page with some useful information too at https://taiga.io/support/

Thank you very much.

**Comment by sitstde** [comment]
i have no question its a bug.
example in index.html:
    <script src="/js/libs.js?v=1426844703197"></script>
    <script src="/js/app-loader.js?v=1426844703197"></script>
    <script src="/js/templates.js?v=1426844703197"></script>

should be
    <script src="js/libs.js?v=1426844703197"></script>
    <script src="js/app-loader.js?v=1426844703197"></script>
    <script src="js/templates.js?v=1426844703197"></script>

i changed this and other paths, now it works.

**Comment by bameda** [comment]
Sorry, but I don't understand

**Comment by Xaviju** [comment]
@sitstde you pasted the same code in both examples

**Comment by sitstde** [comment]
no see the src=" there is a backslash  on the top one making it a absolute path. on the bottom one its a relative path because the backslash is not there

**Comment by superalex** [comment]
Hello @sitstde,

We where studying the possibility of making taiga work in a non-root url and we found it was not possible. 

Are you sure your Taiga instance is working properly just with that change?, can you login, list your projects, etc?. If so, could you show us your custom settings for taiga-front and taiga-back

The discussion we had in the list about this issue -> https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/taigaio/bov9je7lfNQ/fyJtflnQ7WUJ

Regards,

**Comment by schmitzhermes** [comment]
any updates on this?

**Comment by superalex** [comment]
Nop...

**Comment by jachstet-sea** [comment]
Well, maybe the official documentation at https://github.com/taigaio/taiga-front-dist#installation should state that the frontend must be accessible the at the root of the static web server. I just fell into this one as well ...
