### ISSUE TITLE
Colorblind alternative (issues table)

### ISSUE THREAD

**Issue by slvn** [taigaio/taiga-front#454]
Hello,

As a colorblind, using color in the issues table to indicate type, severity and priority is inconvenient. Having an alternative using shape, numbers, words, letter, emoticons, gif or whatever could be nice.
If you have any question, i'll be happy to help. I'll try to dig in the code how do that properly.

Cheers.

**Comment by superalex** [comment]
Thank you very much for your suggestion @slvn :+1:

**Comment by cmnstmntmn** [comment]
:+1:

**Comment by micaelbergeron** [comment]
As soon as I installed Taiga, I found myself searching for a colorblind mode.
You could add some glyphs (1..5, ABCDE, Icons) in the state flags and it would solve the problem fairly easily.

**Comment by MrKahuna** [comment]
Here are a couple examples of what it looks like to colorblind users.  As you can see it's inconvenient at best and unusable in many respects.  Where in the code are the colors/icons assigned to the various categories/severities?

![taiga_noredcones](https://cloud.githubusercontent.com/assets/52570/16357215/db82e496-3abd-11e6-8c3d-f05decc65058.png)
![taiga_monochromacy](https://cloud.githubusercontent.com/assets/52570/16357217/e16f2874-3abd-11e6-9623-28e215f4f354.png)

**Comment by superalex** [comment]
Thank you very much @MrKahuna we will review this with our UX people

**Comment by slvn** [comment]
Fair :)
