### ISSUE TITLE
Email disclosure issue

### ISSUE THREAD

**Issue by tasn** [taigaio/taiga-front#459]
Hey,

It's actually the backend that's disclosing this information, but here felt like the right place to report it. Please let me know if I'm wrong. Anyhow, when asking for a password reset, I can put my username or email. The issue is when I put my username. When the username is detected I get a message that goes something like: "An email has been sent to youremail@address.com". This means I can just find the email of anyone using taigo.

**Comment by superalex** [comment]
Thank you very much @tasn, this one or the taiga-back repo are good places for reporting but please, if you find more information disclosure bugs report them first to support@taiga.io. 

We are yet working on this and it will be solved as soon as possible.

Regards!,

**Comment by tasn** [comment]
You are right. This was a bit irresponsible...
I can edit the ticket to remove the report if you prefer to keep this private and already have a copy of the reproduction case. I suspect private details may leak to unauthorized users in other places too so better check those.

Thanks for your prompt reply.

**Comment by superalex** [comment]
The bug is yet solved in master and stable branches and deployed in our servers but I think it would be better to hide the details for protecting another not updated instances.

Thank you very much again for reporting this, if you find anything more let us know please :+1:

**Comment by tasn** [comment]
Edited out the details. Thanks for solving it.
