### ISSUE TITLE
Continuous integration support for projects

### ISSUE THREAD

**Issue by NickvdMeij** [taigaio/taiga-front#462]
I've started to work with Taiga and i really love it. It's finally a scrum tool that's well designed and easy to use.
However, I do have some suggestions that would make it perfect for my business:

At the moment (and perhaps its already implemented, but i couldn't find it anywhere), you must specify the number of sprints and maximum story points as administrator. However, some businesses use Continuous integration for certain projects. It would be awesome to have an infinite number of sprints and infinite number of story points that can be used, and a have a backlog for each sprint. That way, you can use this tool perfectly with continuous intergration.

Thanks in advance,
Nick van der Meij

**Comment by superalex** [comment]
Hello @NickvdMeij,

Actually you can't set that number to infinite but we could add that enhancement.

What I don't fully understand is the utility of having a backlog for each sprint, could you please expand it a bit more?

Regards,

**Comment by NickvdMeij** [comment]
On the backlog page, there is a burndown chart for all the sprint. However at the moment its a chart that has all the sprint in them. It would be nice to be able to select a sprint and only view the burndown chart for that sprint (or maybe a range of sprints) depending on how much story points there were in the sprints

So say sprint 1 has 20 story points, sprint 2 also 20 story points and sprint 3 30 story points, and each sprint lasts 2 weeks, you could show a graph of sprint 1 and 2 and have the graph reflect the days as x-axis instead of the sprints.

**Comment by bameda** [comment]
Go to the taskboard of some sprint and press the graph icon to see a burndown graph per sprint

![image](https://cloud.githubusercontent.com/assets/877218/7538141/49697d0a-f59e-11e4-8a16-5de2ca39510a.png)

**Comment by NickvdMeij** [comment]
@bameda Nice, thats exactly what i was looking for! Ty man!

**Comment by bameda** [comment]
:dancer: :dancer:  you're welcome :smile_cat:
