### ISSUE TITLE
Configuration for Hipchat notification

### ISSUE THREAD

**Issue by florisvanwoudenberg** [taigaio/taiga-front#466]
Would be nice to have an option to configure what notifications are send to hipchat
(wiki created, wiki updated, issue created, issue updated, etc.)

**Comment by superalex** [comment]
Thank you very much @florisvanwoudenberg, we have separate repos for plugins, could you please create this issue here: https://github.com/taigaio/taiga-contrib-hipchat?

Regards!,

**Comment by florisvanwoudenberg** [comment]
My apologies. I just created this issue in the right repo.

**Comment by superalex** [comment]
Thanks @florisvanwoudenberg :+1:
