### ISSUE TITLE
Seeing the user assigned to a user story directly on the taskboard 

### ISSUE THREAD

**Issue by tdbs** [taigaio/taiga-front#468]
This would help give some context, i know the taskboard is designed for seeing tasks, but we see the user stories on the left, there's space, it might as well do something useful, like seeing the person assigned to the user story.

**Comment by superalex** [comment]
Hello @tdbs,

We have received some more feedback about this so I'm adding it to our enhancements list for Taiga core.

Regards!

**Comment by tdbs** [comment]
Thank you
