### ISSUE TITLE
Disable user story addition in sprint using drag and drop for user who did not have edit sprint rights

### ISSUE THREAD

**Issue by me-snail** [taigaio/taiga-front#469]
Steps to reproduce - 
1. Disable access rights to edit sprint ,  from admin permission settings.
2. Try to add user stories in created sprint by dragging it from backlog to sprint.

Issue : User with no access rights to edit sprint can still be able to add user story in sprint

**Comment by superalex** [comment]
Hello @me-snail,

I think it's the same issue reported here: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/taigaio/gdZITIrxtms/xTtfNcXEWo8J

For Taiga the sprint associated to a user story is an attribute from the user story. The edition sprint permission affects only to the sprint attributes (dates, name...). If you want your users not to be able of adding user stories to sprint you should remove the edit user story permission from that role.

Regards!,
