### ISSUE TITLE
View to show all assigned User Stories, Tasks and Issues

### ISSUE THREAD

**Issue by paultag** [taigaio/taiga-front#472]
It'd be great if there were a view to show all the Tasks, User Stories and Issues assigned to me across all of my projects; not unlike GitHub's [/issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+user%3Apaultag) view

**Comment by superalex** [comment]
Thanks for the idea @paultag 

We are currently working on it and it will be released very soon. I'm closing this one because it's a duplicated from https://github.com/taigaio/taiga-front/issues/422

Regards!

**Comment by paultag** [comment]
Thanks!
