### ISSUE TITLE
Missing the button for enabling assign US to a role.

### ISSUE THREAD

**Issue by Jensig** [taigaio/taiga-front#474]
Missing the on/off switch and i'm using https://tree.taiga.io/

![screen shot 2015-05-22 at 13 49 57](https://cloud.githubusercontent.com/assets/733933/7769989/aa0ce980-0089-11e5-9090-6f7c70f3d938.png)

**Comment by Jensig** [comment]
I't has been fixed.

**Comment by superalex** [comment]
Thanks! :+1:
