### ISSUE TITLE
Option for pdf generation of wikepages

### ISSUE THREAD

**Issue by florisvanwoudenberg** [taigaio/taiga-front#475]
Would be nice to generate pdf's with a general / custom stylesheet.
Is this on the roadmap or is there an alternative solution?

**Comment by superalex** [comment]
Hello @florisvanwoudenberg,

It isn't in our roadmap but I'm adding it as a possible one, we will review it and study if can be included in Taiga core. As a workaround when I needed to generate a pdf from the Taiga wiki pages I've used this chrome extension -> https://chrome.google.com/webstore/detail/print-friendly-pdf/ohlencieiipommannpdfcmfdpjjmeolj/related?hl=en

Regards!,

**Comment by florisvanwoudenberg** [comment]
Thanks for the suggestion. It is a workaround indeed. I still prefer to have a native sollution, but for now it works for me.

**Comment by superalex** [comment]
Great! :)

**Comment by jgomo3** [comment]
I would add, maybe in another ticket if it is a worth idea, to allow share a public link of an specific version of a wiki page of a private project.
