### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by florisvanwoudenberg** [taigaio/taiga-front#476]
Beside the burndown chart that is already in Taiga, are there any other metrics on the roadmap?

**Comment by superalex** [comment]
Hello @florisvanwoudenberg,

Actually we have charts in the backlog and in the taskboard. In the long term we would like to have a full and customizable reporting system inside of Taiga (so it's in our roadmap). Our first approach for this was the CSV reports feature, it allows you to create your custom reports with real time data from your projects, you can see an example about how it works here -> https://www.youtube.com/watch?v=tdt7nqXVf_E

Regards!,

**Comment by florisvanwoudenberg** [comment]
Thanks @superalex
