### ISSUE TITLE
Project configuration screen gives the option to set number of spints for Kanban

### ISSUE THREAD

**Issue by florisvanwoudenberg** [taigaio/taiga-front#477]
Even if the Scrum module is not enabled, there is an option to set the number of sprints. Maybe the config screen should be dependent to the enabled modules?

**Comment by superalex** [comment]
Hello @florisvanwoudenberg, 

I think you are right, this area could be hidden if the project hasn't the backlog module enabled.

Thank you very much for your suggestions!
