### ISSUE TITLE
Taiga over ssl configuration documentation not correct

### ISSUE THREAD

**Issue by florisvanwoudenberg** [taigaio/taiga-front#478]
Not sure where to leave this issue:
In de the documentation http://taigaio.github.io/taiga-doc/dist/setup-production.html there is one thing missing in the file ~/taiga-front-dist/dist/js/conf.json
The eventsUrl should be changed to  
   "eventsUrl": "wss://example.com/events" 
(secure websocket)

Correct configuration in ~/taiga-front-dist/dist/js/conf.json:
{
    "api": "https://example.com/api/v1/",
    "eventsUrl": "wss://example.com/events",
    "debug": "true",
    "publicRegisterEnabled": true,
    "feedbackEnabled": true,
    "privacyPolicyUrl": null,
    "termsOfServiceUrl": null,
    "maxUploadFileSize": null
}

**Comment by superalex** [comment]
Hello @florisvanwoudenberg,

If you find more bugs related to the documentation I think it would be better to have them in the taiga-doc repo (https://github.com/taigaio/taiga-doc).

I've corrected this one some minutes ago -> https://github.com/taigaio/taiga-doc/commit/5e78fa8eb29d07fe69c449f1535fe42bd92bfa43 and updated http://taigaio.github.io/taiga-doc/dist/setup-production.html

Thank you very much! :+1:

**Comment by florisvanwoudenberg** [comment]
Ok, thank you!

**Comment by superalex** [comment]
You are welcome! :)
