### ISSUE TITLE
Jitsi Gives a 404 Error when the URL Contains a Hyphen

### ISSUE THREAD

**Issue by 19kestier** [taigaio/taiga-front#479]
When the Taiga project name contains a space, the generated URL replaces the space with a hyphen.
This is a problem though, because Jitsi gives a 404 error when the meet.jit.si URL contains a hyphen. The URL generated for the "Meet Up" feature should probably either remove the hyphen, or use camelCase.

**Comment by 19kestier** [comment]
It looks like the only time Jitsi doesn't give a 404 error is when all characters past the last '/' are either a number or a letter.

**Comment by 19kestier** [comment]
It appears that the person who implemented Jitsi knew of this problem because it looks like they tried to remove the hyphens in the Jitsi URLs.

    videoConferenceUrl = (project) ->
            urlSeparator = "-"
            if project.videoconferences == "appear-in"
                baseUrl = "https://appear.in/"
            else if project.videoconferences == "talky"
                baseUrl = "https://talky.io/"
            else if project.videoconferences == "jitsi"
                urlSeparator = ""
                baseUrl = "https://meet.jit.si/"
            else
                return ""

**Comment by superalex** [comment]
Hello @19kestier,

I implemented this part but I didn't consider all the possible situations, it's a bug and we will solve it as soon as possible. 

Thank you very much for reporting and sorry for the inconveniences!

**Comment by superalex** [comment]
It should be fixed here -> https://github.com/taigaio/taiga-front/commit/82de0addc738e462af4d224791dfcece620f927c

Regards!,
