### ISSUE TITLE
access to other projects

### ISSUE THREAD

**Issue by yisahn** [taigaio/taiga-front#482]
(Google Translate)
launch the browser (FF), I opened my taiga (https://tree.taiga.io/project/xxx/backlog) without going through the connection page.
User icon was hidden, and I had access to several projects and team that were not mine !! (none of my projects)
I have cleared my cache (ineffective) and go to the login page.
demo or bug (?)

**Comment by superalex** [comment]
Hello @yisahn,

If it's a public project you should be able of accessing it if you know the url, could you write to support@taiga.io with the url of that project?

Regards!,

**Comment by yisahn** [comment]
projects I had access were not mine, but the (private) url was. sure !
i'm writing to support
thanks

**Comment by superalex** [comment]
We received your email, it was a problem with the customized project permissions.

Thank you very much @yisahn ! :+1:
