### ISSUE TITLE
Backlog story point pull down menu shows incorrect amount of story points when using customized story point values

### ISSUE THREAD

**Issue by Tohnmeister** [taigaio/taiga-front#483]
- Create a project
- Instead of the default list of story point values, choose another one (for example the 0, 1/2, 2, 3, 5, 8, 13, 20, 40, 100).
- In the Backlog screen, add a user story.
- Now in the list of backlog items, click on the pull down for adding story points.
- Choose 13
![0914294a00944476be6a8b05046e3ad8](https://cloud.githubusercontent.com/assets/1702409/7838830/6ab68bf6-048f-11e5-9a21-803b2963a4de.png)
- Note that the list shows 15 as the amount of story points, while I would have expected 13
![e34b0dc855299ae61d76c977058c76dd](https://cloud.githubusercontent.com/assets/1702409/7838852/7cb627c6-048f-11e5-9995-01e604b4ff9e.png)

**Comment by bameda** [comment]
In _Admin > Attributes > Points_ panel US Points have two attributes: name and value.
 - Name is a string of chars, ex.: "13", "1/2", "S", "L", "A few"...
 - Value is a decimal number ex.: 13, 0,5, 2, 4, 1....

I think you've changed the name to " 13" but the value is still 15.

**Comment by Tohnmeister** [comment]
Thanks. You are indeed right. Silly mistake.

**Comment by bameda** [comment]
Thanks to you for using Taiga. :smiley_cat: 

Regards
