### ISSUE TITLE
Go to parent button

### ISSUE THREAD

**Issue by alexproca** [taigaio/taiga-front#485]
After a related task is clicked and it's page is loaded provide a button to go back to parent story

**Comment by bameda** [comment]
Hi @alexproca 

You have a link under the subject of the task to go to user story

![image](https://cloud.githubusercontent.com/assets/877218/7866129/a1a8df22-056d-11e5-8571-92d44e123235.png)

Regards

**Comment by alexproca** [comment]
Hello @bameda ! Thanks for explanation. I was searching for something like a button or an arrow pointing upwards and I missed the feature right under my eyes.

**Comment by bameda** [comment]
Don't worry, is easy to miss this link, you are not the first. :smile:
