### ISSUE TITLE
Promote to task

### ISSUE THREAD

**Issue by SpacyRicochet** [taigaio/taiga-front#486]
We're still figuring out a proper workflow between Slack, Taiga and Gitlab. The current lack of Taiga -> Gitlab integration makes it more useful to add issues and tasks in Gitlab and have them be ported over to Taiga as issues as well.

However, it would be very useful if Taiga offered a 'Promote to Task' in addition to the 'Promote to User Story' option for issues. That way, you can quickly create multiple issues in Gitlab and then assign those issues as a task to certain User Stories.

**Comment by superalex** [comment]
Thank you very much for your suggestion @SpacyRicochet we will review it to see if it feets on Taiga core :+1: 

Regards!

**Comment by martinrebane** [comment]
+1 Scope of a problem often changes and it is very useful to move and convert stuff around, including converting issue to task. I was just looking for the feature to convert issue to task.

**Comment by walljm** [comment]
Can I add that it would be super useful to aslo be able to Promote a Task to a User Story

**Comment by Xaviju** [comment]
I guess we could mix all the transformations into a 'Promote' feature that will allow users to Promote their US, issue o task to something else.
Not sure if the naming "Promote" will be useful anymore. Could 'downgrade' a user story to an issue or a task as well? 
Or we only want to promote to a higher level? issue -> task (or US) -> US

**Comment by walljm** [comment]
Yes!

**Comment by cmmata** [comment]
I have one more suggestion: Could you add an option to close / delete ported issue? When I add a Gitlab issue and promote it to user story in Taiga, that issue still appears in Taiga and I need to manually select each one and change the status. It can be useful to change status or delete that issue automatically when you promote to user story or task. Or is there any login in ported issues I don't see?

**Comment by superalex** [comment]
We decided not to take any action by default because some teams have workflows that leave the issue open (and manually close/remove them when needed). We had the idea of adding customizable actions when promoting :)

**Comment by cmmata** [comment]
I was talking more about an option you could check / uncheck to change status or something. Maybe in the issue page next to promote button. Actions by default are dangerous :) there are a lot of different workflows.

**Comment by superalex** [comment]
Sure!, making it customizable should be the right way :+1:

**Comment by lfarkas** [comment]
I'd also useful to use milestone as sprint and gitlab milestones automatically appear as sprint while issue as task.

**Comment by terrycloth** [comment]
I don't know if I would call it a "promotion," but certainly being able to convert a user story to a task or an epic, and vice versa, would be easier than having to delete the epic/story/task and recreating it as the other type.

**Comment by techlogix** [comment]
Is it possible to change a story to an epic and vice versa yet? Is there an enhancement being worked? thanks!

**Comment by Xaviju** [comment]
@techlogix No, we haven't worked on it yet. If we do, we'll keep this issue informed.

**Comment by zicklag** [comment]
It would be very useful to me and my team if we could make a user story from an Issue, but have the ability to make the new story in a different project than the one the issue was in.

@superalex said:
> We had the idea of adding customizable actions when promoting :)

Having customizeable "promote" actions would be perfect. Then you could make a "push to US on project foo" action.

It would also be nice if the issue that the story was created from would have some kind of link to the story or stories that were spawned by it, and vice versa.

**Comment by zicklag** [comment]
It would also be nice if I could specify a title for the story that is spawned from an issue, just in case I want to spawn more than one story from an issue. That way, if I have a feature request that makes sense to split up into multiple stories, I can spawn more than one story, each with different titles, from the same issue, and have links to them all from the original issue. Maybe like the bulk entry buttons that already exist in different parts of the UI.

**Comment by zicklag** [comment]
I just realized that what I want is essentially the same UX as adding related stories to epics. I created a new issue for that: #1342

**Comment by abdallahYashir** [comment]
+1 for being able to promote a **Task** directly to a **User Story**.

At the time of breaking User Stories into small tasks, most of the times we do not think of the complexity of each individual ones.

Then when working on a task in particular, we often realise that it's more complex than first estimated.

**Comment by kenjiru** [comment]
I also happen to underestimate from time to time the complexity of a task. And would like to have an option to promote a task to a user story very helpful. And to make the things complete, it would also help to have the reverse option, to convert a task to a story.

**Comment by msdisme** [comment]
+1

**Comment by theriverman** [comment]
+1

**Comment by artemkovalyov** [comment]
+1, It was my first blocker after starting to use the tool

**Comment by tpopela** [comment]
Hi, is there any update on this? In https://tree.taiga.io/project/taiga/issue/2773 @diacritica says, that it might be ready Q1, 2019. We would like to use this in Fedora's Teams Taiga, instead of removing the current tasks and create new US and copy the information there.
