### ISSUE TITLE
Allow install under a subdirectory

### ISSUE THREAD

**Issue by paultag** [taigaio/taiga-front#492]
It'd be great if there was some way to tell the front-end that the code was under `/somewhere` not `/`

I know most of this is static HTML and hardcoded, but it'd be great to find some magic way :)

**Comment by superalex** [comment]
Hello @paultag,

We were studying the possibility of making taiga work in a non-root url and we found it was not possible with the actual structure although it's something we would love Taiga to support.

The discussion we had in the list about this issue -> https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/taigaio/bov9je7lfNQ/fyJtflnQ7WUJ

Regards,

**Comment by paultag** [comment]
Is there an open issue to track that feature?

Thanks!

**Comment by superalex** [comment]
Nop!

**Comment by paultag** [comment]
Mind reopening this ticket and using this?


On Wed, Jun 3, 2015 at 9:37 AM, Alejandro <notifications@github.com> wrote:

> Nop!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/taigaio/taiga-front/issues/492#issuecomment-108416584>
> .
>



-- 
:wq

**Comment by superalex** [comment]
ok :+1:

**Comment by herbsmn** [comment]
has there been any movement on this?

**Comment by superalex** [comment]
Hello @herbsmn, sorry but not

**Comment by wonson** [comment]
What I guess, subdirectory problem is not your problem, it's a common problem of RoR apps, is it true?

Technically it's difficult to solve the problem because RoR sucks. 

However, is it possible for u guy to figure out the rewrite rules for Apache and Nginx, and write it in the installation guide? This would help, and solve the problem technically.

**Comment by wonson** [comment]
What I guess, subdirectory problem is not your problem, it's a common problem of RoR apps, is it true?

Technically it's difficult to solve the problem because RoR sucks. 

However, is it possible for u guy to figure out the rewrite rules for Apache and Nginx, and write it in the installation guide? This would help, and solve the problem practically.

**Comment by Kyslik** [comment]
Has there been any movement on this?

**Comment by notfood** [comment]
For anyone else who happens to hit this issue...

It's quite easy to make Taiga run under a subdirectory with the html5 directive `<base href="/taiga/"/>`

I'll detail the general changes required. 

---
To begin with I'm using stable `taiga-front-dist` in the `/home/taiga/frontend` path. You must change the #Frontend to whatever subdirectory you are aiming for, for my case I use `taiga`, conf.json and the compiled directory must be available in the root for certain static links to work, they could be changed to relative in the code but we won't bother...

### nginx.conf
Move the Frontend URIs under `/taiga`, change `root` to `alias`, don't forget to change `index.html` location.
```nginx
        # Frontend
        location /taiga {
                alias /home/taiga/frontend/dist;
                try_files $uri $uri/ /taiga/index.html;
        }
        location /conf.json {
                alias /home/taiga/frontend/dist;
                try_files /conf.json =404;
        }
        location /v-1569907893851 {
                alias /home/taiga/frontend/dist/v-1569907893851;
        }
```


### index.html
Edit `/home/taiga/frontend/dist/index.html` and add `<base href="/taiga/"/>` to anywhere in the `<head>` element.
```patch
diff --git a/dist/index.html b/dist/index.html
index ef8f5e0..28403e0 100644
--- a/dist/index.html
+++ b/dist/index.html
@@ -6,6 +6,7 @@
     <meta name="fragment" content="!">
     <!-- Main meta-->
     <title>Taiga</title>
+    <base href="/taiga/"/>
     <meta name="description" content="Taiga is a project management platform for startups and agile developers &amp; designers who want a simple, beautiful tool that makes work truly enjoyable.">
     <meta name="keywords" content="agile, scrum, taiga, management, project, developer, designer, user experience">
     <link rel="stylesheet" href="/v-1569907893851/styles/theme-taiga.css">
```


And done.

Everything should work. Switching `/admin` is harder but it should be removed after you are done installing it, the landing page is hardcoded...

For `/api`, `/static`, `/media` and `/events` they all can be changed already in the `/home/taiga/frontend/dist/conf.json` (api, eventsUrl) and `/home/taiga/backend/settings/local.py` (SITES, MEDIA_URL, STATIC_URL) to whatever url, just change it in nginx as well.
