### ISSUE TITLE
preview an image attachment in kanban

### ISSUE THREAD

**Issue by wisemyth** [taigaio/taiga-front#494]
When i upload an image attachment in a task , it's complicated to preview it.  Click the task link in kanban which will redirct to the task detail page, and then i must download the image for previewing.

It will be amazing if taiga can provide a thumbnail image at the task in kanban and click it for previewing conveniently.

the picture is a kanban task from trello,which provide this function:
![9dd42486-34fa-4c61-bc3f-27ce754b9d71](https://cloud.githubusercontent.com/assets/10470250/7953486/298da0f6-09f8-11e5-8f77-f355d3c9d105.png)

**Comment by superalex** [comment]
Thank you very much for your ideas @wisemyth 

This is something we have received more feedback about and it was already in our TODO enhancements list for Taiga.

Regards!,

**Comment by Xaviju** [comment]
@wisemyth Attachment images will be available in Kanban and taskboard under demand in the upcoming release
