### ISSUE TITLE
Support for Burnup chart

### ISSUE THREAD

**Issue by kentoj** [taigaio/taiga-front#496]
This is a question for both front and back ends of taiga. 
Does taiga have a module for burn up charts? I am using a burn up chart in excel for all of my projects and want to use one in taiga. If one doesn't exist I'll probably have to create it myself.

Also, does the taiga-back have support for showing changing scope over time as would be needed for a burn up chart?

**Comment by superalex** [comment]
Hello @kentoj 

I've answered you also in the public group (https://groups.google.com/forum/#!topic/taigaio/hqo1sC_5ciE) so I'm closing this one ;)

Regards!,
