### ISSUE TITLE
Confusing placeholder text for tag in New user story

### ISSUE THREAD

**Issue by brycefisher** [taigaio/taiga-front#498]
![screen shot 2015-06-07 at 12 08 46 pm](https://cloud.githubusercontent.com/assets/220106/8025537/09b67a32-0d0e-11e5-8879-cabae7fddd00.png)

I think it's really cute and funny to have "Tag me! I'm it" as the placeholder text for the tag creation. However, I didn't understand the purpose of this box at first. Could we use some slightly more informative text here?

Ex: "Create new tag" or "Enter tag" or even "Tag" or "Tag this story"

**Comment by Xaviju** [comment]
Thanks @brycefisher we would like to maintain an informative approach while not being to serious or 'robotic'. We will talk with our UX team and see if we can find a better sentence to ensure that every user will understand the meaning and the action proposed.
Any other ideas are welcome :)

Thanks!

**Comment by brycefisher** [comment]
Woot! You guys rock. Thanks @Xaviju.

**Comment by Xaviju** [comment]
Finally changed to "Enter Tag" as @brycefisher proposed. Will be released in the upcoming release in October.
