### ISSUE TITLE
QUESTION: Possible to only use tasks?

### ISSUE THREAD

**Issue by brycefisher** [taigaio/taiga-front#499]
I'm trying to use this software for my personal life and sharing an organized todo list with my wife (who is not a developer). I realize this is not the main use case for Taigia, so this question is probably not a high priority.

For my personal life use case though, I'd like to shut off the User Stories and Issues, and I'd like to simply make everything a task in at least one project. Is that currently possible?

In a related vein, could I disable severities entirely?

**Comment by superalex** [comment]
Hello @brycefisher,

I think Taiga could fit in your scenario if you use the kanban module and disable the backlog one. This way you will only see tasks (they really are user stories) in a board. You could customize the project status to simplify them, something like having only: todo, in progress, done.

Actually you can't disable severities, they will keep showing in the detail view but you can customize their possible values to use them in some other way...

Regards!,

**Comment by brycefisher** [comment]
Thank @superalex !!

**Comment by superalex** [comment]
You are welcome! ;)
