### ISSUE TITLE
Cannot assign task to a given user

### ISSUE THREAD

**Issue by dolohow** [taigaio/taiga-front#506]
How to reproduce in our project
1. Create task with no person assigned to it.
2. In assign pop up there are no specific user.
3. Assign to task to other person.
4. In assign pop up there is a specific user.

Before assigned:
![1](https://cloud.githubusercontent.com/assets/1408564/8077458/4507d690-0f56-11e5-8d22-a1cd2805e7c2.png)

After assigned to different person:
![2](https://cloud.githubusercontent.com/assets/1408564/8077499/a01a760a-0f56-11e5-89f2-037ba73a680e.png)

**Comment by Xaviju** [comment]
Did you try to filtering in the search field before assigning the task in step 1?
We cannot show all the users on the assign lightbox so we provided the filter field.
If even filtering you cannot find the person, that is a bug.

**Comment by dolohow** [comment]
> Did you try to filtering in the search field before assigning the task in step 1?

I didn't, but it works :)

This is kind
 of a weird, cause there is a plenty of space down there and it's hard to figure this out.
![3](https://cloud.githubusercontent.com/assets/1408564/8077754/b84b4af4-0f58-11e5-9a8a-6d59cc05c280.png)

**Comment by Xaviju** [comment]
The space down depends on which screen size do you have, we have to show a limited height or add a scroll, and our decision was to add a filtering input.
The bug, in this case, is related to the hint text in that lightbox, it should be there.

Thanks for reporting, we will fix that bug to avoid confussion.

**Comment by dolohow** [comment]
Thank you for your cooperation.

**Comment by Xaviju** [comment]
:D yw
