### ISSUE TITLE
Add filter on watched issues

### ISSUE THREAD

**Issue by bengibollen** [taigaio/taiga-front#507]
I haven't found a way to see all issues I'm (or someone else) currently watching. An addition to the filter section would be great. So far we have added tags with user names in addition to adding a watch, but that's a workaround and it's, if done in the wrong order, adding extra status change mail reports wich is already a bit too chatty for some (but that's another issue)

**Comment by superalex** [comment]
Hello @bengibollen,

We have rebuilt the user home (with a lot of other things), this new home includes a "working on" and a "watching" section so probably next week (when we will release the new version) it will be deployed to tree.taiga.io.

Regards!,
