### ISSUE TITLE
Feature: Redirect Login to First Project if only 1 Project

### ISSUE THREAD

**Issue by brycefisher** [taigaio/taiga-front#509]
Possibly my use case is very strange, please don't bend over backwards for this. In my use case, I have only 1 project. When I login, I go to the project listing view. This makes a lot of sense for multiple projects, but when there is only 1 project, it feels like wasted effort. Could the login flow check for project count = 1 and redirect to that project?

**Comment by brycefisher** [comment]
Also, I'd be willing to open a PR if there's interest in adding this feature :boom:

**Comment by superalex** [comment]
Hello @brycefisher we have rebuilt the user home and we will release it probably the next week. In this new home you see your "working on" and "watching" stuff so it makes sense even if you have only one project. The original home was a "temporary" one that survived too much :)

Thank you very much for your PR offering but I think it won't be necessary with the new home.

**Comment by brycefisher** [comment]
Yay! That's so awesome. Thanks for being super @superalex
