### ISSUE TITLE
Issue while setting up development environment for Taiga..In Taiga Frontend

### ISSUE THREAD

**Issue by developer-sachidanand** [taigaio/taiga-front#52]
** I followed the guidelines present in the taiga docs to setup the development environment using the source code  but after ** ** ** doing setup when I run 
** taiga on port 9001, I am getting this error

* the conf.example.json file is available in dist folder , so just renamed it as conf.json file

![Screenshot from 2021-06-12 09-30-06](https://user-images.githubusercontent.com/74866315/121764343-cb1e6d80-cb60-11eb-8c27-5ee4a15941e2.png)

** but when I click on the button that are showing in body part of google chrome
I**  just hit by another error
![Screenshot from 2021-06-12 09-31-36](https://user-images.githubusercontent.com/74866315/121764379-00c35680-cb61-11eb-9c57-d12eefd60d49.png)

**Comment by bameda** [comment]
@developer-sachidanand It seems to be an error in the json file conf.json 

Can you paste the cont of the file??? 
Is there any other error trace in the gulp execution logs?

**Comment by yamila-moreno** [comment]
Hi there!

Do you know that we have [Taiga Community](https://community.taiga.io/) for questions? Please, check there; maybe another user has already ask something similar. If not, create your own. There are people there willing to help, members of the Taiga team members and other users.

To simplify  the process, we will systematically close all issues that are general support questions and redirect people to Taiga Community.

Taiga Team

**Comment by freya0608** [comment]
how to do?

**Comment by freya0608** [comment]
how to do? @yamila-moreno
