### ISSUE TITLE
Cmd / Cntl + click does not open links in new tab

### ISSUE THREAD

**Issue by brettp** [taigaio/taiga-front#532]
Cmd / Cntl + click is a standard way to open links in new tabs, but does not work in Taiga. Right clicking, then selecting "Open in new tab" does, though.

**Comment by bameda** [comment]
Hi @brettp, could you tell where it's happening exactly? What button? What link?

**Comment by juanfran** [comment]
@bameda @brettp It will be fixed in the next release

**Comment by brettp** [comment]
@juanfran :+1: Sounds great!
@bameda For reference, as far as I can tell it's everywhere -- any link.

**Comment by Xaviju** [comment]
It should be fixed now, can you test it?

**Comment by brettp** [comment]
This works perfectly now!

**Comment by brettp** [comment]
This has regressed as of (but maybe before) Taiga 4.2.4 for at least the links to tasks from the sprint board. Do you prefer a new ticket to track this?
