### ISSUE TITLE
Strings are missing for English

### ISSUE THREAD

**Issue by florisvanwoudenberg** [taigaio/taiga-front#537]
After updating our self taiga installation, there are some strings missing.
I checked it in the hosted instance at taiga.io, but there is everything ok.

When I switch to dutch, all strings are translated and available.

See screenshot
![screen shot 2015-06-18 at 20 28 22](https://cloud.githubusercontent.com/assets/1166612/8238934/033ebb1c-15f9-11e5-8725-9ae75b30e526.png)

**Comment by florisvanwoudenberg** [comment]
Hmm, it seems I had to clear my browser-cache (Chrome) and now everything is working fine

**Comment by bameda** [comment]
You are right. Sorry for the inconvenience.

**Comment by superalex** [comment]
We were having some problems with chrome cache not clearing properly (the have some issues opened about it). What it works for me is:
 - Press F12
 - Richt click on the reload site button
 - Empty cache and hard reload
