### ISSUE TITLE
Usability issue timeline

### ISSUE THREAD

**Issue by florisvanwoudenberg** [taigaio/taiga-front#540]
On the timeline it says something like:
has updated the attribute "Status" of the task #132 which belongs to the US #22 ...

But no information is given wat the new status is. This makes the information on the timeline much less usefull. 
The same for all other changes that are shown in the timeline exept for the wiki-pages

Better option:
... has update the status for the task ... to 'ready for test'

**Comment by superalex** [comment]
Hello @florisvanwoudenberg,

Just this morning we were having a discussion about this one and @Xaviju is of the same opinion, next week we'll talk about it with the usability people to decide the final message :)

Regards!,
