### ISSUE TITLE
Dashboard not updating

### ISSUE THREAD

**Issue by ibandominguez** [taigaio/taiga-front#541]
Hi there!

First at all I have to say that I have been using Taiga for a while now and it is amazing, from my point of view the best pm tool out there.

I have noticed there is a little bug on the new release and I wanted to let you guys know in case you have not find out yet.

When updating the project desc ''https://tree.taiga.io/project/{project-slug}/admin/project-profile/details/" and going back to the dashboard "https://tree.taiga.io/" the changes are not updated on the projects boxes located at the right of the screen.

It is definitely not a big issue and it does not interfere with the main use of the app but just so you know.

congrats, great app
Ibán Domínguez

**Comment by superalex** [comment]
Hello @ibandominguez 

Thank you very much for reporting, we will try to solve it  as soon as possible :)

Regards!,
