### ISSUE TITLE
Missing tooltip on project upload

### ISSUE THREAD

**Issue by lhole** [taigaio/taiga-front#552]
This appears to be a new (minor) issue on Taiga 1.8. My locale is "en".

Steps to reproduce:
1) After having logged in and accessed a project
2) Hover the cursor over the folder icon in the toolbar at the top of the page
3) After the pop-up appears, hover over the upload icon

Expected outcome:
A tooltip is displayed indicating what the button does

Actual outcome:
A tooltip is displayed with the text "PROJECT.NAVIGATION.TITLE_ACTION_IMPORT"

**Comment by superalex** [comment]
Thank you very much @lhole 

You are right, it's a bug. I've just solved it here -> https://github.com/taigaio/taiga-front/commit/3c8e3e85a4d42b6fb58c26de142130cdd49a40aa

Regards!,
