### ISSUE TITLE
Removing a sprint deletes all tasks contained therein

### ISSUE THREAD

**Issue by wrl** [taigaio/taiga-front#554]
1. Create a user story
2. Add a task to the user story
3. Add user story to a sprint
4. Delete sprint

The user story moves back to the backlog, but the tasks turn up missing. Noticed this on tree.taiga.io.

**Comment by jespino** [comment]
Thanks for your feedback! :heart_eyes:

It's fixed on the taiga-back PR#381.

We will try to upload it to production as soon as possible.

**Comment by jespino** [comment]
Now working in production! :smile: 

Thanks again!
