### ISSUE TITLE
Release 1.8.0 - Project search option not provided / not accessible, project list is also not accessible after 30 projects

### ISSUE THREAD

**Issue by gaikwad411** [taigaio/taiga-front#556]
Hi There, 
   I have recently updated the my taiga instance to 1.8.0., but I have following concern with this release

1. Project search option not provided / not accessible
    At frontend no search box for searching project is given. I can not search projects now, earlier it
was possible.
   Is that search functionality removed intentionally ? 

2. Project list is also not accessible after 30 projects
   At frontend, "see more projects" page, projects after 30 are not visible, no pagination is there. 

Please help, I think this is blocking issue.

**Comment by bameda** [comment]
1. Search functionality is not removed. The search icon is still in the same place.
   ![image](https://cloud.githubusercontent.com/assets/877218/8406887/875378c8-1e61-11e5-8d5b-5f69f1c793ab.png)

2. This is a bug, we try to solve it ASAP. https://tree.taiga.io/project/taiga/issue/2977

Thank you very much.

**Comment by gaikwad411** [comment]
Hi ,
Thank you for replying..
I was talking about the "search projects filter"  for searching existing projects, not the "search in project".

This feature was available on lickc of top left "taiga" icon. 
[search project]
project 1
project 2 
...

**Comment by bameda** [comment]
OK, the bug (2) is fixed, Try it and tell me If you can see all your projects now.

We've moved the projects menu from the logo icon to the new icon "open folder". This menu now show only the 10 most important project for you (you can reorder your projects list in "My projects" page) so the search input in the menu is no longer necessary.

**Comment by gaikwad411** [comment]
Thanks for replying and fixing the bug. I ll pull the changes from master branch.
