### ISSUE TITLE
Cross-project overview.

### ISSUE THREAD

**Issue by JulienPalard** [taigaio/taiga-front#56]
o/

There is no cross-project overview, it may be a usefull one as in our team we may run some project in parallel.

bests,

**Comment by steinm6** [comment]
Any news on this one? 

It would be cool, if you could create a custom kanban/scrum board containing tickets of all the projects you work on.

**Comment by silsha** [comment]
+1 It would also be nice to see all tasks in a per member overview.

**Comment by seandmack** [comment]
+1 
Ummm, it was on the "short-term plans" almost three years ago. Any update here? 

We are just getting started with Taiga but we have multiple projects some of which have inter-dependencies. Really need to be able to view all stories on a single board regardless of project.

**Comment by cm-cita** [comment]
+1

**Comment by ddamasceno** [comment]
+1
