### ISSUE TITLE
Frontend Caching problem

### ISSUE THREAD

**Issue by smarek** [taigaio/taiga-front#567]
Hello,

I'm running into API caching problem, to be able to use the Taiga frontend, I have to have developer console open and "Disable Cache" checked.

Problem is with "/api/v1/" calls, which show "Status Code: 200 OK (from cache)" in network console, which effectively gives me outdated results in views.

Currently using Google Chrome (OSX 64-bit 45.0.2447.0 Canary channel)

What debug/config info can I provide you with? Just ask

**Comment by bameda** [comment]
Are you using your own instance of Taiga or our service tree.taiga.io?

If you are using your private instance, are you using nginx or apache?

**Comment by smarek** [comment]
Private Apache2.4.10 instance (see the config here: https://github.com/taigaio/taiga-back/issues/390 )

**Comment by bameda** [comment]
Could you try in other browser? Or maybe the problem is with Apache....

**Comment by smarek** [comment]
Well I'm sorry, that was problem with my Apache configuration, I've updated section in referenced taiga-back documentation issue, and for reference including here. Sorry for disturbance.

**Problem was with already configured mod_headers and mod_expires apache modules, which automatically and agressively cached /api calls**

```apache
<Location /api>
        ProxyPass http://127.0.0.1:8001/api
        ProxyPassReverse http://127.0.0.1:8001/api

        <IfModule mod_expires.c>
                ExpiresActive On
                ExpiresDefault "now"
        </IfModule>
        <IfModule mod_headers.c>
                Header set Cache-Control "no-cache, must-revalidate"    env=no-cache-headers
                Header set Pragma        "no-cache"                     env=no-cache-headers
                Header set Expires       "Sat, 1 Jan 2000 00:00:00 GMT" env=no-cache-headers
        </IfModule>
</Location>
```

**Comment by bameda** [comment]
Don't worry. I'm glad now works :-)
