### ISSUE TITLE
Very slow, and occasionally broken, update on Issues page

### ISSUE THREAD

**Issue by BraveSirAndrew** [taigaio/taiga-front#568]
Hi there

Really loving Taiga, and it's been super stable for the most part, but recently a particular log file was uploaded as part of a bug report, and everything to do with issues has more or less exploded since then. The issue was, for some reason, automatically duplicated a bunch of times and now can't be deleted. The larger problem though is that the issues page shows the No issues text for a long time then either updates to show the bug list, or goes to the error page. 

The project is at https://tree.taiga.io/project/onikira/, and the problematic issue is 832 through 836. We are ironically at exactly the point in our project where we need the issues list the most, so it would be great if this could be fixed quickly, or alternatively, if there was some way for us to export the issues.

Thanks
Andrew

**Comment by bameda** [comment]
Hi @BraveSirAndrew, please send an email to support@taiga.io and we'll try to solve your problems.

**Comment by Xaviju** [comment]
Closing because it seems fixed.
