### ISSUE TITLE
private/public project button doesn't react

### ISSUE THREAD

**Issue by JulienPalard** [taigaio/taiga-front#57]
o/

In the project configuration view, the "Public" and the "Private" button does nothing. It's probably known but I open a ticket to track this one.

Bests.

**Comment by segler-alex** [comment]
This is still not working, why are there buttons that do nothing ? ;)
It would be really nice for my teammates to see our core project without adding every single one.
They should by default all be able to see the project and add issues.

**Comment by Xaviju** [comment]
This is already working, if you set your project as public, your project will be visible for anyone with the project URL.
We have set an example public project: https://tree.taiga.io/project/the-princess-bride/
