### ISSUE TITLE
Be able to add other attributes (built in and custom) to the list of sortable and viewable attributes on the backlog

### ISSUE THREAD

**Issue by walljm** [taigaio/taiga-front#571]

**Comment by bameda** [comment]
Thank you @walljm for your feedback.

**Comment by ChristianHenkeEMnify** [comment]
This is the feature that i am looking for and none of the trillions of agile tools have it. Still trying to find the one that has it.  This would make us change to taiga.io

**Comment by SamuelYaron** [comment]
We are currently in the process of evaluating taiga for our toolchain as well. It is a great tool already, but this is a feature we would love to see as well!

**Comment by ngulden** [comment]
I'm also looking forward to this. Would very much help with the priority decision making process.
