### ISSUE TITLE
Stories should support validation/acceptance criteria

### ISSUE THREAD

**Issue by lincolnthree** [taigaio/taiga-front#573]
Scrum related: User stories are often broken down into:

Story, Acceptance Criteria, Tasks, and Impediments.

There is currently no way in Taiga to track acceptance criteria outside of tasks, or typing them into the story description itself.

Acceptance criteria should have their own set of permissions, typically owned by stakeholders.

Acceptance criteria should have two states: "Accepted" "Not-accepted"

Once a story's validation criteria are accepted, it can be moved from "awaiting test/validation" to "done" - though this should not be be enforced programmatically.

**Comment by ktallon** [comment]
Agree with this 100%

**Comment by lanphan** [comment]
Hello,
Is there any plan for this feature, Taiga team?

**Comment by nathanprins** [comment]
Would like to see this feature being added as well.

**Comment by lonix1** [comment]
:+1: 
User stories without acceptance criteria != scrum
Also I would argue that != kanban

Without ACs it's just a wishlist. We need ACs to provide the definition of done.
