### ISSUE TITLE
Sorting of wiki links

### ISSUE THREAD

**Issue by florisvanwoudenberg** [taigaio/taiga-front#574]
Would be nice to have the ability to sort the wikilinks.
Now it is very static and sometimes a page is plitted in two pages as it grows.

**Comment by Xaviju** [comment]
Hi @florisvanwoudenberg 
We already have an enhancement in our list for this issue, I'll ad your feedback!
https://tree.taiga.io/project/taiga/issue/1464

**Comment by Xaviju** [comment]
This will be added in the upcoming release. In a couple weeks.
