### ISSUE TITLE
"https: / <domain name> / media / " directory structure getting created under 'taiga-backend'

### ISSUE THREAD

**Issue by reeteshranjan** [taigaio/taiga-front#575]
I have used 1.7 versions of taiga-back and taiga-front-dist and setup my own taiga server.

When I tried to create an attachment first time, and also tried to change my gravatar, I saw that the URLs corresponding to them that read like following:

https://{domain name}/media/attachments/..
https://{domain name}/media/user/..

are not loading in the frontend and I get an Nginx 404 page if I take the URL and paste directly in my browser.

I looked into my server installation and found that there is a directory structure created inside my taiga-back directory which goes like:

https: / {domain name} / media / user
https: / {domain name} / media / attachments

I tried to merge the 'user' and 'attachments' directories found here into my taiga-back/media/ directory and few issues got resolved e.g. my gravatar started showing up at bottom left; however, I still do not see that on the tasks in sprint dashboard. When I inspect the image shown on left of task name, it shows the following:

img ng-src=""

So merging this spurious directory myself did not help completely.

**Comment by bameda** [comment]
Sorry I don't understand why you talk about directories and you write urls

Can you paste your local.py file?

**Comment by reeteshranjan** [comment]
Here is a description to help you understand better.

Following is my home directory where I have setup taiga-back and taiga-front-dist

```
ubuntu@ip-172-31-16-221:~$ ls
archana  buildyourweb  circus.ini  kiggles  logs  ssl  taiga-back  taiga-front-dist
```

When I upload a gravatar image I see that a strange directory called **https:** is created in `taiga-back`.

```
ubuntu@ip-172-31-16-221:~$ cd taiga-back/
ubuntu@ip-172-31-16-221:~/taiga-back$ ls
AUTHORS.rst      LICENSE    doc     manage.py   regenerate.sh           scripts   taiga
CHANGELOG.md     NOTICE     https:  media       requirements-devel.txt  settings  tests
CONTRIBUTING.md  README.md  locale  pytest.ini  requirements.txt        static
```

The domain I am using to host my own installation of Taiga is `taiga.buildyourweb.in`. Please see what is inside this https: directory:

```
ubuntu@ip-172-31-16-221:~/taiga-back$ cd https\:/
ubuntu@ip-172-31-16-221:~/taiga-back/https:$ ls
taiga.buildyourweb.in
ubuntu@ip-172-31-16-221:~/taiga-back/https:$ ls taiga.buildyourweb.in/
media
ubuntu@ip-172-31-16-221:~/taiga-back/https:$ ls taiga.buildyourweb.in/media/
user
ubuntu@ip-172-31-16-221:~/taiga-back/https:$ ls taiga.buildyourweb.in/media/user/
3
```

So for some reason rather than creating my image under `taiga-back/media/user/..`, the upload is creating one whole set of directories matching my eventual photo URL (something like `https://taiga.buildyourweb.in/media/user/..`).

What do you think is causing this? Is it something to do with one's own domain name not being acceptable to the upload code?

Please note that everything else works. I have created several projects which are currently active, and I am able to daily Scrum management, Kanban, modify settings, add new roles etc. so basically everything that is present by default to manage user stories, tasks, sprints etc. plus the settings modifications etc. are all working fine.

I am also providing the users_user table row pertaining to my user. You can see the relative photo URL here.

```
 | reeteshranjan   | reeteshranjan@buildyourweb.in   | t  | Reetesh Ranjan  | #223af8 |   | user/3/a/6/4/92859b4dc57d7268cb211333dc6b443440d892b82ec4814a3242543e2fed/reetesh.jpg  | 20
```

**Comment by bameda** [comment]
Can you paste your local.py file?

**Comment by reeteshranjan** [comment]
I just tried your hint and looked into my local.py file. I had put the absolute path like in common.py including the domain name, and that's what was causing the issue. I changed it to relative path as follows and it works fine now. My photo upload works.

```
MEDIA_ROOT = 'media'
STATIC_ROOT = 'static'
#MEDIA_ROOT = 'https://taiga.buildyourweb.in/media'
#STATIC_ROOT = 'https://taiga.buildyourweb.in/static'
```
Thanks!

**Comment by bameda** [comment]
Great! :dancer:
