### ISSUE TITLE
Issue with backlink to User story from an issue

### ISSUE THREAD

**Issue by captnbp** [taigaio/taiga-front#576]
Hi,

I'm using Taiga on not standard port 8443. 

When I display an issue which was promoted to a user story, there are 2 links to go to the user story : 
- One under the title : 
![capture2](https://cloud.githubusercontent.com/assets/7904693/8616740/f5101db8-26fd-11e5-85cb-a74aecf21117.PNG)
- One in the comments :
![capture](https://cloud.githubusercontent.com/assets/7904693/8616670/8079dd9a-26fd-11e5-8e3c-0f1b40121cf3.PNG)

The first one contains my custom port, but the second one doesn't contain it, so the link points to port 80 which is wrong.

**Comment by bameda** [comment]
Edit taiga-back/settings/local.py and add:
```
SITES["front"] = {
    "domain": "localhost:9001", 
    "scheme": "http", 
    "name": "front"
}
```
with your custom settings


Regards

**Comment by captnbp** [comment]
Thanks !
