### ISSUE TITLE
Image attachments should be opened in browser instead of downloaded

### ISSUE THREAD

**Issue by brettp** [taigaio/taiga-front#577]
In order to view images attached to tickets, you first have to download them. Images should be displayed directly in the browser.

**Comment by brianmontanaweb** [comment]
Maybe a thumbnail/preview if it's an image asset.

**Comment by superalex** [comment]
Thanks for the feedback!,

We had en existing enhancement for Taiga, I've just copied your comments there -> https://tree.taiga.io/project/taiga/issue/1619

Regards!,
