### ISSUE TITLE
Sprint Calendar View

### ISSUE THREAD

**Issue by walljm** [taigaio/taiga-front#580]
I'm thinking of something similar to a gantt chart where you can see your sprints spanning a timeline.

This is especially useful if you're managing multiple projects in a single project.  In my case, i have several applications that share a common code base, and may run sprints in parallel.  Being able to see how the sprints graph out on a calendar would help.

As an added benefit, you could then display the user stories that belong to a selected sprint below the chart similarly to the way you display the backlog, allowing the user to filter/sort remove/reorder items in the list

**Comment by Lotbert** [comment]
+1
Something like a ganttchart would be really nice

**Comment by heyakyra** [comment]
@walljm why did you close this ticket? 

It looks like this is synced with https://tree.taiga.io/project/taiga/issue/3051

But there are some duplicates: 
* https://tree.taiga.io/project/taiga/issue/2972
* #1126 (synced with https://tree.taiga.io/project/taiga/issue/4628)
