### ISSUE TITLE
Attachment URL pointing to localhost

### ISSUE THREAD

**Issue by mastayoda** [taigaio/taiga-front#581]
I installed taiga using the Script as the web page instructions says(1.4. Setup server-like environment). I have a virtual machine in Amazon EC2 with Ubuntu 14.04 LTS, everything works well so far but for some reason all attachments are pointing to localhost and not to the virtual machine URL, see the image below:

![screen shot 2015-07-11 at 1 44 12 pm](https://cloud.githubusercontent.com/assets/1596707/8634744/588744a4-27d3-11e5-9ea3-bc5eef9e9d0c.png)

**Comment by bameda** [comment]
Add (or edit) in ```taiga-back/settings/local.py```:

```
MEDIA_URL = "http://<your_host>/media/"
```

**Comment by bameda** [comment]
And please, for support questions about custom installation please send an email to the Taiga mailing list

http://groups.google.com/d/forum/taigaio.

Thanks

**Comment by mastayoda** [comment]
I didn't realize it was a configuration problem. Thanks so much.

**Comment by bameda** [comment]
you are welcome :smile_cat:
