### ISSUE TITLE
delete attribute cause duplicate data append on setting>attribute

### ISSUE THREAD

**Issue by LightZam** [taigaio/taiga-front#582]
i do it as a admin role 

it will be reproduce by delete any attribute, like status, point, priority, servertis, type, custom field

every delete will occur duplicate data append to view

**Comment by superalex** [comment]
Thanks @LightZam, it was a reported one, we will solve it as soon as possible. It's only a visual effect, if you refresh the page the entries won't be duplicated.

Regards!,
