### ISSUE TITLE
User Stories without Sub-tasks

### ISSUE THREAD

**Issue by mario595** [taigaio/taiga-front#583]
Hi,
first of all, thank you for developing this awesome app. I've been using it for a couple of weeks and I love it simplicity. Although, there is one think I haven't been able to do yet.

I am used to other tools for Agile project management where you can move your US across the columns in the agile board. I don't normally use tasks for the stories, so I would like to be able to drag & drop a story from one column to another.

As a workaround, I create a task for each US with the same name, and use it for that purpose, but I was wondering wether  what I need is possible or not.

thank you!

**Comment by bameda** [comment]
Hi Mario, what board are you using: Kanban or Backlog (with Sprint Taskboards)?

- In Sprint Taskboards you move taks. https://tree.taiga.io/project/the-princess-bride/taskboard/first-act
- In Kanban you move user stories. https://tree.taiga.io/project/the-princess-bride/kanban

**Comment by wdullaer** [comment]
I've been trying taiga on and off and this is something which bugged me.
I don't really use scrum for my projects, more a kanban flow. Unfortunately the kanban view only gives an overview of user stories which are too high level in most cases.
Grouping things in sprints just to get a different kanban feels weird.

It would be nice if you could select what you'd like to see on the kanban view: user stories, tasks or issues, potentially even a mix.
It would help to get an overview of where the project is right now, irregardless of sprints.

**Comment by superalex** [comment]
Thank you very much for your suggestion @wdullaer

**Comment by velis74** [comment]
@wdullaer really has a good point here: right now my team must first review open issues, then promote each of "ready" issues to US (and close it), THEN finally be able to include it in a sprint. The process could be more streamlined if there could be a general overview and adding an issue to sprint would automatically promote it to US (if that's necessary).

**Comment by Xaviju** [comment]
Great workflow suggestion, @velis74

**Comment by fabue** [comment]
+1 for a simple kanban task board

**Comment by Xaviju** [comment]
This issue reminds me a lot of #486 
Both are demanding the possibility of promoting tasks to US and add it to sprints or kanban. Could we merge both to a simple 'Promote from everything to everything to use it in the kanban or taskboard'?

**Comment by flesser** [comment]
Look like this issue is still valid in Taiga6 (and probably Taiga Next?), so why not reopen?

**Comment by diacritica** [comment]
You're absolutely right, but we don't need to reopen it, we'll just make sure it's addressed in Taiga Next. Thanks!
