### ISSUE TITLE
Master board

### ISSUE THREAD

**Issue by florisvanwoudenberg** [taigaio/taiga-front#584]
We have around 40 projects in Taiga right now (and more will be added). Clients can add issues in their projects. But it's hard to have an overview right now, I have to go in all the projects to see what issues are added.
My suggestion is to have a master board where all issues from the project the user has access to are shown, grouped by project. So on this board the issues can be assigned to users.

**Comment by superalex** [comment]
Hello @florisvanwoudenberg 

If you use your profile link (top right icon) you could check your timeline where info about created issues should appear. I think if this info is too much we could add filter for this part.

Regards!,

**Comment by florisvanwoudenberg** [comment]
Hello @superalex 
I know this feature. But what about clients adding issues? 
Maybe a better idea is to have a custom dashboard with configurable widgets (assignee, creation date, type of issue, status, due date etc.) that can be added or removed from the dashboard.
For project managers this would give a good status overview, something I'm missing right now.
A user could also have multiple dashboards, so one is for planning ahead and one for the retrospective (we have on at the end of the week where we evaluate the work and progress of the week)

**Comment by superalex** [comment]
Hmmmmm, I like the idea about having a custom dashboard configurable with widgets. 

I'm closing this one and creating: https://tree.taiga.io/project/taiga/issue/3071

Regards!,
