### ISSUE TITLE
Page history for wiki pages

### ISSUE THREAD

**Issue by cheptil** [taigaio/taiga-front#585]
Really important functionality when you need to see what kind of changes you have done for the last few weeks
--
Real'no podgoraet - posony zapility pliz

**Comment by bameda** [comment]
Sorry @cheptil but I don't understand

**Comment by Xaviju** [comment]
Do you mean a wiki changelog? Something like this? https://en.wikipedia.org/wiki/Help:Page_history

**Comment by cheptil** [comment]
@Xaviju @bameda Yes, I mean this(page history)

**Comment by bameda** [comment]
Ok, this feature is in our roadmap https://tree.taiga.io/project/taiga/us/1621

**Comment by superalex** [comment]
As it was already existing as a user story in our roadmap I'm closing this one. Thanks for your ideas @cheptil
