### ISSUE TITLE
Incorrect alt-text on Backlog page

### ISSUE THREAD

**Issue by lhole** [taigaio/taiga-front#589]
On the sprint backlog page within a project, hovering over the percentage bar section shows the following tooltips:
`{{'BACKLOG.EXCESS_OF_POINTS' | translate}}`
`{{'BACKLOG.PENDING_POINTS' | translate}}`
`{{'BACKLOG.CLOSED_POINTS' | translate}}`

I'm using en_GB locale.

**Comment by bameda** [comment]
Thanks, it's a bug. We have added your bugs to our projects:
- https://tree.taiga.io/project/taiga/issue/3090
- https://tree.taiga.io/project/taiga/issue/3091
- https://tree.taiga.io/project/taiga/issue/3093

**Comment by superalex** [comment]
Fixed here! -> https://github.com/taigaio/taiga-front/commit/f614c3eb196680d81a512743ef9ee8bdba1bb225

Thank you very much @lhole
