### ISSUE TITLE
Unexpected alt-text in US blocked modal

### ISSUE THREAD

**Issue by lhole** [taigaio/taiga-front#590]
Steps to reproduce:
1) Go onto the Kanban within a project
2) Select a US
3) Click the "Block" button
4) Hover over the white background

Expected outcome:
Probably no tooltip shown

Actual outcome:
Tooltip with content `US.LIGHTBOX_TITLE_BLOKING_US` shown

I'm in the en_GB locale.

**Comment by bameda** [comment]
Thanks for reporting.

**Comment by superalex** [comment]
Fixed here! -> https://github.com/taigaio/taiga-front/commit/f614c3eb196680d81a512743ef9ee8bdba1bb225

Thank you very much @lhole
