### ISSUE TITLE
Unexpected translation of text in comments (Limited XSS)

### ISSUE THREAD

**Issue by lhole** [taigaio/taiga-front#592]
Steps to reproduce:
1) Go onto the Issue list within a project
2) Click on an existing issue
3) Add a comment with the text `{{'foo' | uppercase}}`
4) Click the "Comment" button
5) Review the text in the newly added comment

Expected outcome:
Text should be `{{'foo' | uppercase}}`

Actual outcome:
The text has been evaluated, and now reads `FOO`

Note that this appears to apply to US comments too.
Also note that any Angular filter appears to be applicable, which I'd consider a cross-site-scripting security issue, although the scope is very limited.
Finally, an example of this can be seen in the US https://tree.taiga.io/project/taiga/issue/3090, where the comment and the US text should be the same.

**Comment by bameda** [comment]
o_O this is a big one. Thank you very much, we try to solver it ASAP

**Comment by juanfran** [comment]
fixed! 

thanks!
