### ISSUE TITLE
user assignment not showing up

### ISSUE THREAD

**Issue by wolfencode** [taigaio/taiga-front#595]
Hi we have a taiga server built on our own servers. The installation followed the steps in the instructions for the production installation. We have the program up and running fine so far except when we try and assign something(task, story, watchers) to a user the user selection is missing. We see the search field and the "x" for the lightbox but we don't see the list of users. We are able to add users, members, task, etc. So the communication to the DB seems to be fine. There are no errors showing in the console in the browser and the server shows no errors. Any ideas?

**Comment by superalex** [comment]
If you can add users and members the connection should be working ok. That list of users should come with the project info (project detail API) but it's very strange the popup is empty. Could you create a dummy/temporary user for the taiga development team and send the credentials to support@taiga.io?

Regards!,
