### ISSUE TITLE
Use a default profile image when user hasn't chosen one

### ISSUE THREAD

**Issue by tasn** [taigaio/taiga-front#596]
Taiga looks really bad when a user doesn't have a profile image. Solution: add a default profile image.
Way to reproduce:
1. Create a user without a profile image.
2. Assign a kanban task to the user (or really, anywhere else, even in the top right of the window when the user is logged in).
3. See how odd it looks.

**Comment by Xaviju** [comment]
Hi @tasn,
Taiga has a default image (the taiga logo). Are you using your own instance or the Taiga service?
Could you attach a screen capture? 

Thanks!

**Comment by tasn** [comment]
![taiga](https://cloud.githubusercontent.com/assets/108670/9021873/205d5178-3853-11e5-9508-a3c0dab5df61.png)
Look at the "Tal Hacohen" user.
I'm using the hosted taiga service.
The users were created a while back, maybe that's the issue?

**Comment by Xaviju** [comment]
If the user has no image, there should be a Taiga default image. I'll try to reproduce it and see what happens...
Please ensure that it is not a cache problem by hard-reloading or private session.

Thanks!

**Comment by tasn** [comment]
I just checked, not a cache problem. Is there a way for me to give you a user id so you can maybe investigate the specific user object on the server?

**Comment by tasn** [comment]
In case this help, this is the <img> tag from the kanban task assign popup for the "broken" user:
<img src="//www.gravatar.com/avatar/6de55b086e539bf034314d65657570c8?size=80&amp;default=https%3A%2F%2Fstatic.taiga.io%2Fimg%2Fuser-noimage.png">

**Comment by superalex** [comment]
Hello @tasn 

I'm checking your project and your image is correctly shown:

![image](https://cloud.githubusercontent.com/assets/1579633/9032116/98f87536-39bb-11e5-861f-3e087cec4625.png)

**Comment by tasn** [comment]
Hey,

It seems like he changed his profile picture now because the visual bugs were so annoying. That's the same reason why I put a stub github image for mine, just so the interface doesn't look bad. So I guess you can't really debug with my account anymore, but maybe try to reproduce with a new project? As I said, maybe it's only for users created a while back, (and I showed you the value I got in the image tag, that was wrong) so maybe it's no longer a real issue. We fixed it for us by setting a profile image.

**Comment by superalex** [comment]
Hello @tasn ,

I've been checking another "old" users and couldn't reproduce the issue...Actually if the user didn't set an avatar image but he has an existing one in gravatar that's the one we are using it, is it possible that we were showing your gravatar image?.

**Comment by tasn** [comment]
I pasted the img tag here. As you can see you were trying to show the gravatar. The problem was that the user doesn't have a gravatar and there was no default set (it seems).
Try creating a user without a gravatar and without an image set, maybe that would do it?

**Comment by bameda** [comment]
It is very strange. For example users without image and gravatar looks like this https://tree.taiga.io/profile/rubiales

**Comment by tasn** [comment]
I can't see it here, I'm not logged in on this box. I believe you it works for some people, and as I said, the workaround is easy (just add a picture). However I did show the img tag I was getting with that specific user (maybe use a backup of the db to see the broken user?) that was returning nothing (though now when I checked on this box, it's returning the default gravatar image, which is something, but still wrong). I guess doing a hard refresh didn't update cached images because those were loaded later on with injected image tags (no idea how that browser mechanism actually decides what to invalidate and what not), and I had a cached broken image for that user. Not sure.

Anyhow, let's consider this close until we get other reports.

Thanks.

**Comment by bameda** [comment]
So... you don't use tree.taiga.io. You are using other instance/server of Taiga, correct?

**Comment by tasn** [comment]
Already mentioned that, I'm using the hosted service.

**Comment by bameda** [comment]
okis. we'll be alert if this happens again.

**Comment by tasn** [comment]
Great, thanks.

**Comment by rriemann** [comment]
I have the same issue!

**Comment by rriemann** [comment]
![moodle1](https://cloud.githubusercontent.com/assets/111932/10715998/b8638eba-7b29-11e5-9e3c-71b133718d54.jpg)

**Comment by rriemann** [comment]
The issue is related to the browser. It's working on chromium, but not with Firefox.

**Comment by tasn** [comment]
Ahh, I was also using Ghostery. That makes sense.
