### ISSUE TITLE
Add a way to "peek" at story descriptions from the taskboard

### ISSUE THREAD

**Issue by skaulana** [taigaio/taiga-front#598]
My team and I love running our sprint acceptance reviews from the taskboard view, but in order to review acceptance criteria we write in each story's description, there's a lot of back and forth navigation between the taskboard and each US (or a profileration of new tabs).

Would be great to see a "peek" of some sort added to the taskboard view to simplify this workflow - some ideas that come to mind are hovering over the US title for a bit, having a separate icon to tap/hover over for more story details, or adding a project setting to always list story descriptions in the taskboard under title. Thanks for considering!

**Comment by superalex** [comment]
Hello @skaulana,

Thanks for your feedback. This enhancement now exists in Taiga too -> https://tree.taiga.io/project/taiga/issue/3135 and it's assigned to our UX expert, we will study it! :+1:
