### ISSUE TITLE
Search page's UI filter resets when more results are being fetched

### ISSUE THREAD

**Issue by skaulana** [taigaio/taiga-front#599]
Noticed this UI glitch on Chrome 44, Windows 8.1:

1. Go to https://tree.taiga.io/project/taiga/search, type 'story' for your search query
2. After pressing Enter click the Issues tab and wait for the query to complete _(sidenote: no indication that results are being fetched... a spinner might be nice?)_

Result: filter switches back to User Stories
Expect: stays filtered to Issues

Seems to repro easiest for broad queries, like 'project', and you can sometimes see a partial fetch happen (the filter #s refresh with a subset of results) that may or may not render when you visit that filter, but once the full fetch is done you'll get dropped back to User Stories again.

**Comment by superalex** [comment]
Thank you very much for reporting @skaulana 

You found a bug (https://tree.taiga.io/project/taiga/issue/3136), we will try to solve it as soon as possible. Sorry for the inconvenience.

Regards!,
