### ISSUE TITLE
Support for velocity forecasting

### ISSUE THREAD

**Issue by skaulana** [taigaio/taiga-front#600]
For Scrum projects using the backlog module, would be **super handy** to see a visual forecast line (similar to the doomline) applied to the top of the backlog, based on the historical velocity of that project. For example:

![image](https://cloud.githubusercontent.com/assets/1870844/9063706/5894b9a2-3ab8-11e5-9c5a-61c104590fc2.png)

This is similar to a feature of [Team Foundation Server](https://msdn.microsoft.com/en-us/magazine/dn189203.aspx) (see figures 11, 12).

**Comment by superalex** [comment]
Thank you very much @skaulana 

It sounds like a really useful idea and not difficult to implement, I hope we can work on it soon (by the way, pull requests are welcome ;D)

Regards!,

**Comment by Xaviju** [comment]
Love the idea! Great @skaulana

**Comment by golov** [comment]
This is the missing feature for our team to start using taiga. Any idea if this will be implemented?
