### ISSUE TITLE
[enhancement] Add possibility to add specific Attributes on the right panel, redesign the user story view

### ISSUE THREAD

**Issue by elharraa** [taigaio/taiga-front#601]
For example, i want to add new status on my project user stories.
Actually, we have to enter a value in input text, and it will be very good to edit the design manually, and give the possibility to change the position of elements

**Comment by superalex** [comment]
Hello @elharraa 

Actually all the attributes shown in the right column are fully customizable. If you want to customize your status values you can do it via: admin -> attributes -> status

Regards!,

**Comment by elharraa** [comment]
Hello,
My goal is to add a new attributes to exisiting attributes..

actually we can only to add a 'Custom Fields'. wich it's not shown in 
the right panel.

Regards!
And your product rocks!
  GL Guys
Le 05/08/2015 09:46, Alejandro a écrit :
>
> Hello @elharraa <https://github.com/elharraa>
>
> Actually all the attributes shown in the right column are fully 
> customizable. If you want to customize your status values you can do 
> it via: admin -> attributes -> status
>
> Regards!,
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/taigaio/taiga-front/issues/601#issuecomment-127903179>.
>

-- 
​--
Adil EL HARRAS.
Mobile : 0 6 52 38 53 15

**Comment by superalex** [comment]
Thanks @elharraa 

This was our first approach to custom fields, we plan extending that feature a lot with required fields, different types of attributes (dates, numbers, ranges...), validator, showing it in the popup or not, showing it in the listings or not...I hope we can extend that feature soon! ;)
