### ISSUE TITLE
icon-drag-v iconography looks like menu

### ISSUE THREAD

**Issue by brianmontanaweb** [taigaio/taiga-front#604]
icon-drag-v looks like a menu selection when compared to other applications/sites. Maybe a pan arrow icon to make it easier to recognize it's purpose?

http://www2.psd100.com/ppp/2013/11/2701/Cross-arrow-cursor-1127205232.png

**Comment by Xaviju** [comment]
@brianmontanaweb Yes you are right. When we started the Taiga project this icon was not that extended as it is now and it was not widely used as a menu icon as it is now. We should find an alternative, like the icon you proposed.

![](http://www2.psd100.com/ppp/2013/11/2701/Cross-arrow-cursor-1127205232.png)

We are open to hear another proposals on the drag and drop icon.

Thanks!

**Comment by brianmontanaweb** [comment]
I'm a fan of these two for moving elements around, at least in the visual layout you're using.

http://fortawesome.github.io/Font-Awesome/icon/arrows/
http://fortawesome.github.io/Font-Awesome/icon/arrows-v/

**Comment by Xaviju** [comment]
I like that icon, but it could be too big, and take too much space. Id like to find a thinner alternative to test as well. 
What about something like this?

![](http://i.imgur.com/JafgrlP.png)

**Comment by brianmontanaweb** [comment]
Ohhh. I like easy for to make in CSS for modern browsers.

**Comment by Xaviju** [comment]
I guess we will use SVG. We are moving all icon fonts to SVG. But yes, it could be an option.

**Comment by brianmontanaweb** [comment]
Awesome thanks! Keeping it consistent sounds solid to me SVG makes sense then.
