### ISSUE TITLE
Freestanding tasks

### ISSUE THREAD

**Issue by maparent** [taigaio/taiga-front#605]
We are migrating from a task-based workflow to a user-story-based workflow. It would have been useful for us to redefine our old tasks in Taiga, to assign them to stories progressively. This would require at least #467, but it is currently impossible to even define a task that lives outside a story, hence this issue.
We would have also appreciated a task list view in this context.

**Comment by superalex** [comment]
Hello @maparent ,

Actually there is a workaround for this one. Tasks can be detached from user-stories in Taiga but the only way of creating them is if they are associated to a sprint (the last row of the sprint taskboard is for tasks with no user story associated), you could have a "dummy" sprint where you have all those tasks but  #467 would still be needed...

Thank you very much for the feedback!
