### ISSUE TITLE
Delete member screen does not show email.

### ISSUE THREAD

**Issue by Pablohn26** [taigaio/taiga-front#606]
Hi,

when you want to delete a member invitation, the email is not showed. 
See the next screenshot: 
![selection_318](https://cloud.githubusercontent.com/assets/1228418/9150669/fdd8d7b0-3de5-11e5-894a-a1ec63beecfd.png)

**Comment by superalex** [comment]
Thank you very much @Pablohn26 we will try to solve it as soon as possible.

Regards!,

**Comment by juanfran** [comment]
Solved in the master branch. It will be in the next release.
