### ISSUE TITLE
Add custom fields to the "New Userstory" screen

### ISSUE THREAD

**Issue by Hopiu** [taigaio/taiga-front#608]
Hi,
as we tried to move our current project workflow to taiga, we added some custom fields to User Stories. Unfortunately I find it quite annoying to fill these fields with content. Did you consider adding the custom fields form to the "New Userstory" screen? To us this would be a great improvement in usability as it would first help our users to find the fields and second save some clicks.

**Comment by superalex** [comment]
Hello @Hopiu,

Yes, it's something we would like to add, we would like to make it customizable so you can choose what custom fields appear on the lightbox (not only for issues, also for user stories and tasks).

Regards!,

**Comment by at-huydq** [comment]
hi @superalex any milestone or plan for this?

**Comment by superalex** [comment]
Hello @at-huydq we still have no estimation about it, sorry

**Comment by jgeorgeson** [comment]
A year with no updates so I'm assuming still no plans for this? It's pretty annoying to have to ask reporters to go back and cut/paste everything from the description and into the fields. What about pre-populating the description field in the lightbox to have some instructions?

**Comment by leonidas-o** [comment]
Bump... 
I'm also very interested to see the "New User Story" Lightbox either disappear or get the full functionality/fields like an already created one. It's a really bad design that way, where you have to create your story, then save it, open it again just to be able to enter more information like the acceptance criteria (custom field). Really not usable that way.

**Comment by douglaslassance** [comment]
Taiga 6 does not address this issue. Custom fields are not displayed on creation forms.
I think this issue should be re-opened.
