### ISSUE TITLE
[BUG] Still broken on mobile even after Taiga 6 release

### ISSUE THREAD

**Issue by antgel** [taigaio/taiga-front#61]
[Reopening as requested](https://github.com/taigaio/taiga-front/issues/249#issuecomment-737205781) because obviously this wasn't fixed in Taiga 6. 

It's 2021 and mobile first is a thing, but Taiga is still borderline-unusable on mobile. In fact, when checking it before opening this report, I managed to inadvertently drag user stories between columns then couldn't drag them back. (Firefox Android.)

**Comment by rsanchezbalo** [comment]
Hello.
We have a FR for this on https://github.com/kaleidos-ventures/taiga-front/issues/16

Im closing this one to prevent duplicates. Thanks.

**Comment by antgel** [comment]
@rsanchezbalo Um, #61 is this issue, recursive duplicate? :)

**Comment by rsanchezbalo** [comment]
@antgel oh my bad, let me fix that

https://github.com/kaleidos-ventures/taiga-front/issues/16
