### ISSUE TITLE
Hovering over backlog points bar shows code to be run as title, not the actual output of the code.

### ISSUE THREAD

**Issue by usandfriends** [taigaio/taiga-front#611]
Hovering over backlog points bar shows code to be run as the title, not the actual output of the code. Examples:

+ Hovering over green sub-bar displays the title: `'{{ 'BACKLOG.CLOSED_POINTS' | translate}}`.
+ Hovering over red sub-bar displays the title: `'{{ 'BACKLOG.EXCESS_OF_POINTS' | translate}}`.
+ Hovering over white sub-bar displays the title: `'{{ 'BACKLOG.PENDING_POINTS' | translate}}`.

The template code should be running and displaying the proper value.

**Comment by superalex** [comment]
Thanks @usandfriends 

This one was solved in master branch some days ago (https://github.com/taigaio/taiga-front/commit/f614c3eb196680d81a512743ef9ee8bdba1bb225) we will merge it to stable soon.

Regards!,

**Comment by usandfriends** [comment]
Oops, my apologies. Thanks.
