### ISSUE TITLE
As a user, I would like to have a clear understanding of how to add a card when I first go to the kanban board.

### ISSUE THREAD

**Issue by ashumz** [taigaio/taiga-front#614]
Sorry for all of the enhancement requests -- this is my last one. Hope it's helpful. 

I clicked the card icon on the first column, thinking I could add a card that way -- but it opened the prompt for bulk adding (not what I wanted to do.) 

I just want to know how to add a single card for my first experience, before I try the tool out with a team. I clicked the card, and it launched me into a user story template that did not resonate with me. I can't add total points but I can add points by role? That's new to me and I've worked with agile tools of all kinds for years. 

In fact, I'd prefer a way to add a lightweight, single card for each work item that would be assigned to each role, in chunks that are assignable to a single human. 

My idea of kanban stories/cards are small, broken down chunks of work that are relatively the same size -- not potentially 13 points or more because you lump every part of the work into one card and size it by role. Feels like an anti-pattern without obvious story-splitting capabilities. (Might be a cool way to initially estimate feature work before breaking it down into chunks, though.) 

Lastly, I looked around and couldn't find WIP limits. Everything seems to be around sizing. If you plan to continue in this direction, I'd rebrand your kanban board to be a scrumban board (not a bad thing, but more accurate.)

Sorry if this is the wrong forum! GitHub Issues is easier than a mailing list for me, and I wanted to share this feedback in case it can be helpful in the future. 

Nice work overall.

**Comment by superalex** [comment]
Hello @ashumz 

It's great that you are doing so many enhancement requests, users feedback and ideas affects a lot in our decisions about Taiga so they are really really useful for us :)

I think you are right, some parts of Taiga are not so clear as we thought and we should rethink them. 

About WIP limits, you can set them in the admin area -> attributes -> status

Regards!,

**Comment by Xaviju** [comment]
This should be fixed with the new joyrides and placeholders.
