### ISSUE TITLE
As a user I want to switch easily between projects

### ISSUE THREAD

**Issue by florisvanwoudenberg** [taigaio/taiga-front#618]
This could be done by implementing an autocomplete on top of the 10 projects that are listed
![project-list](https://cloud.githubusercontent.com/assets/1166612/9292606/fbf2e85e-4403-11e5-9869-fdcae9ce2956.jpg)
This search should be fuzzy, in case you do not know the exact name of the project

Right now it takes a multiple steps to go to a project, first click on 'see more projects' and than look in the list to find you project. This is not user-friendly

**Comment by heyalbert** [comment]
I wish it could be direct in the sidebar, so you do not have many click steps to switch into another project.
![projects-sidebar](https://cloud.githubusercontent.com/assets/7317458/9573592/7a320608-4fbe-11e5-9c26-64af92b29804.png)

**Comment by Xaviju** [comment]
Its a great idea @florisvanwoudenberg 
Just a small tip: Do you know you can reorder your projects in the "See more projects" page to choose the 10 projects listed in your dropdown? It might help with the current implementation.

**Comment by florisvanwoudenberg** [comment]
Yes, I know, but with all the active projects I always have to go the the 'see all projects' page and then with cmnd-F find the project.
