### ISSUE TITLE
Master configuration

### ISSUE THREAD

**Issue by florisvanwoudenberg** [taigaio/taiga-front#620]
We use our own hosted instance of taiga. Sometimes there are configurations that are global and should apply to all projects. I know there is an option to export and import 'templates', but what about configurations that should apply to all projects that are already existing?
Currently we have to go through all the projects if we want to change some values.
It would be helpfull to have a cascading configuration structure.
This would also solve the problem of added features in new releases. One screen and maybe a role of super-user where these options can be changes.
cascading:
default -> super-user config -> config per project
The lower always overrides the higher level.

**Comment by superalex** [comment]
It sounds good, could you please show an example of that kind of configurations you would change from the super-user config?

**Comment by adityaSplendornet** [comment]
I too agree with florisvanwoudenberg, global settings could be

1) Custom fields, like for example we use, "Allocated Hours" and "Actual Hours" to monitor the amount of time allocated for task or user story and spent time
2) We have custom roles for example "Project Manager", which we have to add every time along with the permissions

Regards
Aditya
Splendornet Technologies Pvt. Ltd.

**Comment by superalex** [comment]
Thanks @adityaSplendornet now I understand much better what kind of workflow you follow when creating new projects! :+1:
