### ISSUE TITLE
Optional 'Oopma Loompa' References

### ISSUE THREAD

**Issue by AndreiUlmeyda** [taigaio/taiga-front#621]
As summed up in https://tree.taiga.io/project/taiga/issue/3040, these references reduced to hard-to-ignore noise in a matter of seconds for me as well. I would be nice to have them optional or eradicate for good the proud folk that is the oompa loompa.

**Comment by superalex** [comment]
Thank you very much for the feedback @AdrianSchurz 

I'm adding your comment to -> https://tree.taiga.io/project/taiga/issue/3040 and closing this one.

Regards!,
