### ISSUE TITLE
Add & Delete Member - Pagination Issue

### ISSUE THREAD

**Issue by Rohit291520** [taigaio/taiga-front#623]
Hello,

While browsing through Memberships menu. I sent invitations to more than 30 Members. When I was sending invitation to 31st Member. After invitation sent pagination not get enabled automatically & then after I refresh the page , I got the pagination correctly.

Suppose now I have pagination. There are two pages. On first page there are 30 Records & on second page there is 1 record. Now I am on second page & if I delete the invitation on second page then success message comes properly but on the page it still showing that record & in URL last parameter is still page=2. Now I got empty page with no records. So what should exactly happen that I should get redirected to first page without pagination now.

Pagination thing is not working after single record add after 30 or single record deleted from any page greater than one.

**Comment by superalex** [comment]
Thank you very much @Rohit291520. We will try to solve it as soon as possible, sorry for the inconvenience! ;)

**Comment by juanfran** [comment]
Solved in the master branch. It'll be in the next release, thanks!
