### ISSUE TITLE
Cannot mention users with capitalized user names

### ISSUE THREAD

**Issue by nidico** [taigaio/taiga-front#628]
User names in taiga are case sensitive (e.g. there is a `daniel` and a `Daniel`). However mentioning users with capitalized (e.g. by using `@Daniel`) does not properly highlight / link to the mentioned users. I haven't checked whether the notification itself actually works.

**Comment by superalex** [comment]
Hello @nidico 

As you say names (and emails) in taiga are case sensitive and it's a deliberate decision so mentions with capitalized won't work (we can have two users with the same username if they are not capitalized in the same way).

**Comment by nidico** [comment]
Why couldn't you make capitalized mentions work?

**Comment by superalex** [comment]
Because mentions refer to usernames and usernames are different if they are capitalized.

**Comment by nidico** [comment]
I know. But why can't you distinguish between `@Foo` and `@foo`?

**Comment by superalex** [comment]
Sorry, I wasn't understanding you, I thought you said that @Foo should mention user foo not that user Foo existed but wasn't highlighted. It's a bug, we'll try to solve it as soon as possible. Sorry for the inconvenience! :+1:

**Comment by nidico** [comment]
Great!

**Comment by topalavlad** [comment]
This looks like it's closed on taiga: https://tree.taiga.io/project/taiga/issue/3221.
Might be worth updating here also.

**Comment by bameda** [comment]
Upps yes, I hope we can disable issues in github and enable creation/edition in taiga soon to prevent duplicate information
