### ISSUE TITLE
[Solved]"assign user in Kanban module" is a blank page, and I can't comment any story.

### ISSUE THREAD

**Issue by ryanemax** [taigaio/taiga-front#629]
assign user in ISSUE module is OK,
but assign user for a Task  in Kanban module is Blank.

And I can't comment any story.

need help, thx

**Comment by ryanemax** [comment]
assigned user for a ISSUE is OK,
assigned user for a Task in Kanban is Blank.

**Comment by bameda** [comment]
this errors happen in taiga.io or in your own Taiga instance? Could you see the browser console to find errors?

PS.: Kanban has user stories, no task. User stories contain tasks.

**Comment by ryanemax** [comment]
My own Taiga instance, Maybe something wrong when deploying( Ubuntu 14.10, 64bit, Python3.4 ).
I'm Checking for this mistake.

It's OK when I assign an issue *In The List View* to an user.
URL:http://a.anasit.com/project/ryanemax-zhang-shang-lu-20/issues?page=1

It's Blank when I do it *In the Details View*.
URL:http://a.anasit.com/project/ryanemax-zhang-shang-lu-20/issue/20

**Comment by bameda** [comment]
Could you send me an invitation to your project at bameda at gmail dot com?

**Comment by bameda** [comment]
Ok, it seems that your apache is not working properly because I can access to the invitation, the url return a 404.  Try to check the apache configuration.

Why you have not used nginx like the documentation recomends?

**Comment by ryanemax** [comment]
Well that's make sence, there are some mistakes with wrong apache configuration:

* 1.Some Blank Page, such as comments & assign user
* 2.Wrong HashTag When invite someone
* 3.malposition div, <div class="navbar-dropdown dropdown-user">
I'll Figure out how to configure apache corretly, and then Switch to Nginx. :)

:+1: 

Thx for your help.

**Comment by bameda** [comment]
You are wellcome. 

Thanks to you for using Taiga
