### ISSUE TITLE
Clicking "new task" when a new task is already open clears the text

### ISSUE THREAD

**Issue by davidfraser** [taigaio/taiga-front#630]
If, in a user story, I

* click on the `+` by *Related Tasks*, a new task entry line appears.
* enter a task subject, but don't yet press *Enter* or click *Save*
* click on the `+` again to add a new task

Then, the task subject I've been typing disappears - the new task replaces it

This is on Chrome 44 on Ubuntu

**Comment by superalex** [comment]
Thanks for reporting @davidfraser, we will review it and try to solve as soon as possible. Sorry for the inconvenience.

**Comment by davidfraser** [comment]
This was fixed by commit e8ea2a558d4e58c6 and is on the current https://tree.taiga.io ... thanks!
