### ISSUE TITLE
Does taiga have the user management part?

### ISSUE THREAD

**Issue by magixyu** [taigaio/taiga-front#640]
Hi,

It is really a wonderful tool. Thanks!

Does this tool have the user management function? I would like to manage the users registered to the system or add the user manually.

Thanks,
Tristan

**Comment by superalex** [comment]
Thank you very much @magixyu  !

You can manage users per project in the web app and if you have your own Taiga instance you can access directly to the django admin and manage all the platform users from there.

Regards!,
