### ISSUE TITLE
contrib-hipchat $loading is not a function

### ISSUE THREAD

**Issue by r1se** [taigaio/taiga-front#641]
Hello. When i'm try save hipchat plugin, front say me:
Uncaught TypeError: $loading is not a function
hipchat.js Line:102

I'm read this issue https://github.com/taigaio/taiga-back/issues/437

After, git pull taiga-front-dist, i got message Already up-to-date.
But bug, still exist.
What me to do? Do pull for backend to?

**Comment by astagi** [comment]
Hi @r1se did you update your hipchat.js file in dist/ ? Try using this https://github.com/taigaio/taiga-contrib-hipchat/blob/f0a678d87c8fb4d01ea85ba0240d1e008f90c1a9/front/dist/hipchat.js

**Comment by r1se** [comment]
@astagi thank you, it's works.

**Comment by astagi** [comment]
:+1:

**Comment by jespino** [comment]
Thanks @astagi

**Comment by astagi** [comment]
np @jespino
