### ISSUE TITLE
Re-order module / function icons on the sidebar

### ISSUE THREAD

**Issue by Tocath** [taigaio/taiga-front#642]
Great tool!  

Would love to be able to reorder the modules on the side bar on a per-project basis.  

![image](https://cloud.githubusercontent.com/assets/14301154/9921760/89b91066-5c9e-11e5-902d-51f3088bad78.png)

For example, I'd like to use Taiga to project manage an upcoming training development and release, and I'd like the wiki page to be the team's first stop, followed by the kanban board, and so on.  It would be great to have a setting to indicate which order they should appear in!  

Thanks!

**Comment by foliovision** [comment]
This would be great for client (project sidebar re-ordered to suite their project) but bad for main development team as user interface consistency and muscle memory is very important to productivity.
