### ISSUE TITLE
Moving a User Story between projects is not possible

### ISSUE THREAD

**Issue by l-mb** [taigaio/taiga-front#644]
Evaluating taiga.io for using it to develop projects, I noticed that it doesn't support moving US between them. That, alas, can be a quite common problem when developing multiple versions of a product/project - imagine starting out with v1, doing 8 sprints, and then realizing that not all features made the schedule-driven release. They need to be pushed to v2 (whereas v1 might only see some additional "maintenance sprints").

I can see problems - e.g., if users/statuses/attributes etc differ between the two projects. A best-effort match could be done? (A larger solution might be to have a master configuration ("organization") encompassing multiple projects so they can't diverge, but that seems more tricky.)

**Comment by superalex** [comment]
Hello @l-mb 

We have received some more feedback about this feature so it was already added to our list of enhancements with high priority. I've just added your comment there (https://tree.taiga.io/project/taiga/issue/2776)

Regards!,

**Comment by l-mb** [comment]
@superalex Thank you! Another way I thought of addressing this was to have a "never-ending" project (which happens to release to customers ever so often). But then the assignment of static points to a project doesn't really make sense.

BTW, awesome work.

**Comment by superalex** [comment]
You are welcome!,

We are also working in supporting projects with "a priori" undefined number of points and sprints, it will be probably ready for the next release ;)

**Comment by benyanke** [comment]
Did this ever get completed? I'm needing to do this as well.

**Comment by 4n70w4** [comment]
[2] Did this ever get completed? I'm needing to do this as well.

**Comment by thomai** [comment]
Are there any news about this feature?
