### ISSUE TITLE
[UX] Accept Button Usability - Color + Verb

### ISSUE THREAD

**Issue by ClashTheBunny** [taigaio/taiga-front#646]
I would like to request a common usability option for the "Accept" button in Taiga's frontend.

Usually, instead of generic verbs like "OK" and "Accept" a specific verb would be better to help people understand what the action will be.  For example, when I delete an issue, I'm given "Accept" instead of somethings like "Delete (cannot be undone)".
https://www.google.com/design/spec/components/dialogs.html#dialogs-full-screen-dialogs
https://msdn.microsoft.com/en-us/library/windows/desktop/ff728831(v=vs.85).aspx#HOW_TO_HANDLE_CRITICAL_ACTIONS
https://msdn.microsoft.com/en-us/library/ms997506.aspx (under "Labels for command buttons")
https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/Controls.html
https://developer.apple.com/library/mac/documentation/UserExperience/Conceptual/OSXHIGuidelines/ControlsButtons.html

There is also a common practice of coloring dangerous actions red, like in bootstrap's "btn-danger" option.  It would be nice if the delete action were a different color because it's going to permently and destructively alter the item.

Right now, I feel like I just have to accept that this action is going to happen and that it's a good action.  Both of these feelings are contrary to reality.

**Comment by superalex** [comment]
Thank you very much for your suggestions @ClashTheBunny !, we will review it! ;)

**Comment by Xaviju** [comment]
Hi @ClashTheBunny its a great idea and ill be happy to fix it, can you give us some examples on how would you improve this actions? We also use red for some dangerous actions like deleting things, can you explain where are you expecting red buttons instead of green ones?

Thanks
