### ISSUE TITLE
[UI] Projects Import Hover-over text missing

### ISSUE THREAD

**Issue by tkirchner-clickboarding** [taigaio/taiga-front#648]
When hovering over the import icon next to "create project" on the projects page you see the text "PROJECT.NAVIGATION.TITLE_ACTION_IMPORT".

**Comment by superalex** [comment]
Thank you very much @tkirchner-clickboarding it was solved in master branch with this commit some time ago (https://github.com/taigaio/taiga-front/commit/3c8e3e85a4d42b6fb58c26de142130cdd49a40aa) we will merge it to branch with the next release.

Regards!,
