### ISSUE TITLE
No gulpfile found -- always

### ISSUE THREAD

**Issue by Davidx7** [taigaio/taiga-front#650]
No matter what I did ::
-- Installed dependencies manually 
-- copied from git the gulpfile
-- reinstalled server
-- installed from scripts/ the components

I never get error in the install, taiga-back works, but front is always out of the gulpfile and does nothing

**Comment by bameda** [comment]
why you need a gulp file? what method are you using to install taiga?

**Comment by Davidx7** [comment]
I don't care about gulpfile but taiga-front doesn't start and that's the only error message I get.

```taiga-scripts/setup-server.sh``` -- all is good with it, but taiga-front get's this error and does not work. ```taiga-back``` works

**Comment by bameda** [comment]
Try to remove ```gulp``` in ```~/.tmux-conf.sh``` and in ```taiga-scripts/scripts/setup-config.sh``` I think is a bug and this command is not necessary right now.

**Comment by Davidx7** [comment]
Same error. 
Remove ```gulp``` from ```function taiga-runserver-front() {}``` it's the only place where it is and I get same error

**Comment by bameda** [comment]
yes, you don't need to do anything to run taiga-front

**Comment by Davidx7** [comment]
Well, actually you do, I just can't figure out what. 
I erased the whole thing and installed it in ```vagrant``` and works fine. Couldn't get passed that bug or find out more info about error.

**Comment by superalex** [comment]
I've updated taiga-script to remove that unnecessary command :https://github.com/taigaio/taiga-scripts/commit/70216ff5f7d15ab33ee98bfbe74ac0caab0663c9

Thank you very much @Davidx7
