### ISSUE TITLE
Allow custom project url

### ISSUE THREAD

**Issue by tanc** [taigaio/taiga-front#651]
Currently when I create a project it creates a url like /project/[username]-[projectname]/

It would be great to be able to provide a custom url (path, slug etc) for that project as it looks a little unprofessional to customers seeing a username before their project name.

**Comment by superalex** [comment]
Hello @tanc,

Allowing the slug update without control had a lot of side effects so we deliberately decided not to allow that feature, if you want to update the slug of any of your projects you can write to tree.taiga.io and we can make the necesary updates for you.

Regards!,

**Comment by tanc** [comment]
Hi @superalex, thanks for the quick reply. Unfortunately this is on a self hosted instance of Taiga. Is there any way to do it for ourselves? What about when creating a new project, is there a method of creating it without adding the username at the beginning of the project slug?

**Comment by superalex** [comment]
Sure!, you can access to the django admin (probably configured in /admin url) and update the project slug there. You should also rebuild the timeline with something like: "python manage.py rebuild_timeline --project PROJECT_ID". 

Sorry but actually there is no way of creating the project without the username appended.

**Comment by tanc** [comment]
Thanks for the instructions, I'll give that a try. Is it possible to create a feature request to remove the username part of the slug? What is the reasoning behind having that?

**Comment by superalex** [comment]
We were thinking about something unique in Taiga that we could append to the project name to avoid duplicates and we thought that using the username made sense. Of course, it's possible to create a feature request for it. 

Regards!,

**Comment by stickyhands** [comment]
@superalex what do you think about organizing users into company/organization and use the slug of the company name to prefix the project name instead of the username of the creator of the project ?

**Comment by superalex** [comment]
Hello @stickyhands 

It could work, organizations is something we will include in Taiga in future releases.

Regards,

**Comment by remus-selea** [comment]
I also noticed that the taiga project i created has my username in the url and I looked for a way to change that. I changed my username but unfortunately the url stayed the same.

Is there a timeline for the company/organization feature or some other way to make avoid project name duplicates?
