### ISSUE TITLE
No Pictures, Team List Messed Up

### ISSUE THREAD

**Issue by ryanleesipes** [taigaio/taiga-front#654]
See screenshot, without user profile picture the names of users bleeds over to cover others.
![taiga_team_no_pic](https://cloud.githubusercontent.com/assets/2141621/10146487/be08ab16-65ee-11e5-8381-06c76e4a6fcb.png)

**Comment by Xaviju** [comment]
Users have a default user profile in Taiga in case they did not upload their own picture. Are you using your own instance or the Taiga servers?

**Comment by ryanleesipes** [comment]
@Xaviju - Taiga servers, this is what is assigned to the users without pictures.

**Comment by bameda** [comment]
Edit taiga-back/settings/local.py and set the default user image:

```
GRAVATAR_DEFAULT_AVATAR =  "http://YOURTAIGABACKURL/static/img/user-noimage.png"
```

Then restart taiga-back.

**Comment by superalex** [comment]
Hello @ryanleesipes ,

If you are using a tree.taiga.io instance, could you please write to support@taiga.io indicating your project url so we can check if everything is working properly?

Regards!,
