### ISSUE TITLE
Task work effort

### ISSUE THREAD

**Issue by pinkra** [taigaio/taiga-front#661]
As a member of the development team i want to estimate tasks by setting working hours to each one. The sum of the total working hours must appears on the sprint summary. This is useful to better estimate the sprint effort during sprint planning.

**Comment by bameda** [comment]
Hi @pinkra, thank you for using Taiga.

Currently Taiga does not support time tracking and this is our motivation: https://taiga.io/support/why-is-there-no-time-tracking/

You can use custom fields + csv repost to generate graph with sprint effor in hours or use [Toggl](https://toggl.com/).

**Comment by adityaSplendornet** [comment]
I agree, it will be highly useful addition and very important to monitor time spent on activities.

**Comment by adityaSplendornet** [comment]
But we can use the custom fields surely to achieve this only problem being the summation has to be done manually for each task to arrive at user story time.

**Comment by bameda** [comment]
No, you can use csv reports and list all task in a spreadsheet.
