### ISSUE TITLE
Taiga fails on Firefox 40.0.3

### ISSUE THREAD

**Issue by nomorebugs** [taigaio/taiga-front#663]
Neither the stable nor the master branch work on Firefox 40.0.3. It cannot be any problem of the installation, cause everything works fine in Chrome/Chromium.

1. It is impossible to change any entry in the profile. Error: "No user matches the given query"
2. It doesn't display any projects on dashboard or in the menu. "You don't have any projects yet"
3. It is impossible to create a new project. The page freezes after entering name and description. 

The installation on taiga.io works fine on Firefox though.

Debug:
Changing the profile requests "http://(xxx)/api/v1/users/5" (url1), method PATCH and returns a 404 Error. Entering the named url (url1) manually into the address-bar returns a Taiga rest api page with code 200 (Firefox). Same request in Chrome returns 200 as well. Here everything works fine.

I use an IP-Address and not any proper domain name yet. May the problem be connected to this?

**Comment by superalex** [comment]
Hello @nomorebugs 

So, everything is working ok under tree.taiga.io (with firefox 40.0.3) but the problem is in your own instance, isn't it?

Are you having any more errors on your javascript console?, what kind of urls did you configure for your app?, something like http://IP for the front and http://IP/api/ for the API or you have different domains/ports for them?

Regards,

**Comment by nomorebugs** [comment]
Hello superalex,

The problem is at my own instance, but i don't know if tree.taiga.io uses the same code version. The problem occurs only in Firefox not Chrome/chromium.
The paths to the api are correct. Further research shows, that the problem is related to authentication at the backend/api. Requesting user information at the api works w/o authentication (which imho is a security flaw), but changing fields (PATCH or DELETE Method) throws a 404 Error with the json-object "_error_message": "No User matches the given query.". Querying projects is forbitten as well. (See pic: request info firefox vs chromium)
There is an error within the app.js: SyntaxError: unreachable code after return statement1 app.js:2118:10 . Chromium prints no errors.
The problem is not related to using a plain ip address as domain name. I made some local domain configuration through /etc/hosts and reconfigured the server. Problem remains. 

Thx a lot for your support
Regards,
 
![request](https://cloud.githubusercontent.com/assets/6703930/10450964/faaa1eac-718c-11e5-86b9-95f5113854c8.png)

![request-chromium](https://cloud.githubusercontent.com/assets/6703930/10451186/2c699192-718e-11e5-90c6-3d2639d3322d.png)

**Comment by nomorebugs** [comment]
As we can also see in the requests, a cookie is not set in firefox during login (cookies are allowed). csrftoken=... is missing in the request. Listing cookies in Firefox shows no cookie of taiga host, while it exists in chromium.

**Comment by superalex** [comment]
Hello @nomorebugs 

- I can confirm tree.taiga.io uses exactly the actual code from stable branch.
- Cookies are not used for authentication, we use selfcontained signed tokens for it (added to the request headers).
- Some API calls are allowed without being authenticated so it shouldn't be a security flaw, Taiga allows public projects and anonymous user so the API needs those resources (but doesn't show any private items).

Your issue related to the user authentication sounds very strange, could you try with an incognito session in your browser?, could it be any browser plugin doing something strange?, did you try to log in and log out again?. Another test I think you could do is using another machine with firefox to access to your own instance and check if it's still happening.

Regards,

**Comment by nomorebugs** [comment]
I tried access from a vm running xp and a new firefox installation w/o any addons. Problems remain.

**Comment by superalex** [comment]
I've just deployed a clean taiga instance served by ip and with firefox 41.0.1 everything works ok, it seems something related to your installation/infrastructure but I can't figure what...could it be any firewall?, did you check the Taiga logs to see if there is something wrong? (you can find them on the ~/logs folder).

Another test could be installing a clean Taiga instance in another virtual machine (it should be minutes if using taiga-scripts) and check if it works correctly on that one.

**Comment by superalex** [comment]
Hello @nomorebugs 

Any update about this?

Regards!,

**Comment by nomorebugs** [comment]
Hello @superalex 

There is no progress jet. Our team will use Taiga with any other browser than Firefox. 
The server seems to behave correctly. At authentication a bearer token is returned by the server, but Firefox stays with using basic auth. If i tamper the http-requests and manually send the returned bearer token, everything works perfect in Firefox. I am running out of ideas for debugging...

Regards,

**Comment by nomorebugs** [comment]
I finally managed to find the reason for this buggy behaviour. The service runs in an area, which needs http-auth provided by nginx. While browsers other than firefox replace the authentication-field for xhr-posts with the taiga bearer-token, firefox stays with nginx-auth token. Thats why api-auth is impossible. If i turn out nginx-auth everything runs fine in Firefox. 
Is this a Firefox bug or could it be avoided by different request construction within the taiga js-code?

**Comment by superalex** [comment]
Hello @nomorebugs 

It sounds like a Firefox bug (or at least something they haven't implemented). Did you try with the last firefox release?, I'm not sure but may be you could use any firefox plugin to use correctly the auth API.

Regards,
