### ISSUE TITLE
cant find follow/bookmark button

### ISSUE THREAD

**Issue by muzirian** [taigaio/taiga-front#664]
The dashboard welcomes with text "Follow the projects, User Stories, Tasks, Issues" but cant figure out how to follow/bookmark or add project to watchlist

**Comment by Xaviju** [comment]
Currently the way to follow User Stories, tasks and issues is by **adding yourself as a watcher in its detail**. This Stories, tasks and issues will appear in your dashboard so you can watch how it evolves. Projects will have a watch button soon!

**Comment by muzirian** [comment]
Thanx
