### ISSUE TITLE
Comment is edited if you cancel add link

### ISSUE THREAD

**Issue by topalavlad** [taigaio/taiga-front#672]
Start adding a comment for a story, for example - We're going to -
Press 'Link', URL dialog appears, press cancel.

Expected result: The text remains unchanged and no link is added.
Actual result: The text becomes - re going to -

Same for abcdef which will be transformed into def. It looks like the first 3 letters are always removed on cancel action.

**Comment by superalex** [comment]
Thanks for reporting @topalavlad

**Comment by topalavlad** [comment]
No problem, hopefully I'll have time to also start fixing issues. 
On a different note, would you guys  consider adding a "Starter" tag to easy tasks or something similar? I think it's encouraging for new people to see these.

**Comment by superalex** [comment]
Thank you very much, pull requests are welcome! :+1: 

It's a good idea @topalavlad as you say that way it could be easier for new people to know where to contribute :)

**Comment by topalavlad** [comment]
Mini pull request :) - https://github.com/taigaio/taiga-front/pull/689

**Comment by superalex** [comment]
Merged!, Thank you very much! ;)
