### ISSUE TITLE
More granular burndown calculation

### ISSUE THREAD

**Issue by fuzzy76** [taigaio/taiga-front#676]
It can be very demotivating when you have completed 9 out of 10 tasks in a user story, and the last one is left on "needs info" or something like that and your burndown chart hasn't moved at all.

Could we get credits in the burndown chart for tasks? So that if we have completed 60% of tasks in a user story, we would get 60% of the points?

We are a small team, so often a single developer works on a user story for many days. And we would like to see _some_ movement on the chart from day to day. :)

**Comment by superalex** [comment]
Hello @fuzzy76 we had an existing enhancement request for this one (https://tree.taiga.io/project/taiga/issue/3307) I'm adding your comments there and closing this one.

Thank you very much for the feedback! :)

**Comment by OpenNingia** [comment]
Why is the issue closed? ( I'm refering to this one https://tree.taiga.io/project/taiga/issue/3307 )
was this feature implemented?

**Comment by superalex** [comment]
@OpenNingia actually the calculation is done in a more granular way than before. Now every closed task from a user story affects to the burndown sprint graph :)

**Comment by OpenNingia** [comment]
@superalex 
I tried today with my installation to no avail.

I'm using taiga version ( from the stable branch )
## 1.9.1 Taiga Tribe (2016-01-05)

**Comment by superalex** [comment]
You could check the PR here -> https://github.com/taigaio/taiga-back/pull/557

If your US is 5 points and one task was closed the chart should go down by 2.5 story points.

Regards!,

**Comment by msdisme** [comment]
is this released in the current taiga.io cloud based version?
