### ISSUE TITLE
No default profile photo/icon is set for new users who don't upload their own

### ISSUE THREAD

**Issue by adriennetacke** [taigaio/taiga-front#679]
As the title states, a user's photo does not fall back to a default if they do not upload their own. I've attached some screenshots to show what occurs:

[Chrome Version 46.0.2490.71 m]
Team Page:
![image](https://cloud.githubusercontent.com/assets/8050265/10646101/292d594c-77e6-11e5-9041-5f4ebddfd88b.png)

Team Sidebar on Timeline Page: 
![image](https://cloud.githubusercontent.com/assets/8050265/10646127/4cb01710-77e6-11e5-8194-1fe98f0e149e.png)

New User entry on Timeline Page:
![image](https://cloud.githubusercontent.com/assets/8050265/10646138/633965f4-77e6-11e5-8d45-dad5e7132ba6.png)

It's a little better on Firefox (Version 43.0a2), but still noticeable:

Team Page (Not as bad):
![image](https://cloud.githubusercontent.com/assets/8050265/10646255/2081fdf6-77e7-11e5-89a8-61610d8d551d.png)

Team Sidebar on Timeline Page:
![image](https://cloud.githubusercontent.com/assets/8050265/10646270/30a9b87c-77e7-11e5-899e-4a30e423f1bf.png)

New User entry on Timeline Page:
![image](https://cloud.githubusercontent.com/assets/8050265/10646294/40de4c26-77e7-11e5-8c92-ef7b957100d3.png)

We're using the hosted service. Any help or suggestions (other than forcing a user to upload a photo!) would be appreciated. 

Thanks!

**Comment by bameda** [comment]
Sorry @adriennetacke but I do not understand what it means. 

If tou are using https://tree.taiga.io could be a temporary problem with gravatar. This is the default photo:
![image](https://cloud.githubusercontent.com/assets/877218/10646583/1b5ef93a-7834-11e5-9bab-9bf019f856c8.png). 

If you are using your own instance of taiga you have to configure the default user photo to use.
> Edit ```taiga-back/settings/local.py``` and set the default user image:
> ```
> GRAVATAR_DEFAULT_AVATAR =  "http://YOURTAIGABACKURL/static/img/user-noimage.png"
> ```
> Then restart taiga-back.

**Comment by adriennetacke** [comment]
Hi! 

We are using https://tree.taiga.io and it has been this way for a while. Should we attribute this to gravatar then?

Thanks for the quick reply btw.

**Comment by bameda** [comment]
Ok, I need to see the project, can you invite me like a temporary member to your project? Send me an invitation to david.barragan @ kaleidos.net

**Comment by adriennetacke** [comment]
You know what? I just figured out the problem. Something silly.

Our company's firewall is preventing the image from being downloaded. That's why the default image doesn't show. >:(

Thanks for your time though. I appreciate it!

**Comment by bameda** [comment]
Yep, I can see the default avatar

![taiga-no-avatars](https://cloud.githubusercontent.com/assets/877218/10650864/41751d12-784c-11e5-93f8-ba303ce99152.png)

Don't worry, we love receive feedback and enhancements from our users and resolve bugs. :smiley_cat: 

Regards.
