### ISSUE TITLE
Ctrl + Enter as shortcut for "commiting" currently edited description/comment/...

### ISSUE THREAD

**Issue by sftd** [taigaio/taiga-front#683]

**Comment by bameda** [comment]
Add comment where? How? Can explain your enhancement with a description?


Thanks

**Comment by bameda** [comment]
Your request can be very obvious to you, but I have no idea what should be done

**Comment by sftd** [comment]
Sorry for not being clear enough.

When adding / editing comments or as a matter of fact anything else I expect modern UI to have mapped ctrl+enter shortcut for "commiting" message (for example clicking "Comment").

**Comment by bameda** [comment]
ok, thank you very mutch for the clarification.

**Comment by almereyda** [comment]
Similar discussions for @discourse happened back then at

* https://meta.discourse.org/t/keyshort-press-ctrl-enter-to-post/4456
* https://meta.discourse.org/t/cmd-enter-support/12093

if you long for more descriptions of this use case.

**Comment by m-messiah** [comment]
Any news here?

Abandoned?

**Comment by bameda** [comment]
Nop. we have an enhancement to create keyboard shortcuts but we have not yet started with it
