### ISSUE TITLE
Ghostery plugin enabled: missing gravatar icon break menu and ui

### ISSUE THREAD

**Issue by rriemann** [taigaio/taiga-front#684]
Related to #596 .

It seems to be the Ghostery plugin of Firefox that blocks Gravatar Widgets. There must be a working fall-back! when the avatar in the top right corner cannot be displayed and the name is too long, the pull-down menu shows up about 50 px further down and cannot be accessed as it is closed when the cursor the navbar leaves.

**Comment by superalex** [comment]
As Ghostery is just running in the user browser I don't know if there is a way of detecting that the request to gravar is blocked, @rriemann do you know if it's possible?

**Comment by rriemann** [comment]
Probably not. I think the alt-text of the gravatar-image should be changed or the gravatar-image should be loaded as a background-image overlaying a default image. In your design, you should just assume that the gravatar-image cannot be loaded and the ui should be work either way.

![recorded](https://cloud.githubusercontent.com/assets/111932/10726154/3cb4bb92-7bd1-11e5-8b47-c6c248761fa8.gif)

**Comment by Xaviju** [comment]
This is a _bug_ related to *Ghostery* (there are no white-list options?). 
If the images don't load is a problem of the network or the plugins the users are using in their browsers. Taiga cannot detect if the images are not loading for an external reason or if someone is blocking content from their network and could not fix it for every case.
Your proposal for the image is a (somehow dirty) workaround for a non Taiga issue.

*To me this is not a bug.*

**Comment by rriemann** [comment]
I disagree vehemently. Consider a short disruption of the Gravatar Avatar Service (server offline). All users with gravatar icons cannot access the main menu anymore. No logout, etc. It's even not possible to change quickly the avatar to a non-gravator one, because you would need to edit the profile and - here is the problem - you need to access the menu in order to do this.

A fix of this issue would of course also help people like me that opted for a self-determined protection of privacy.

**Comment by Xaviju** [comment]
A easy fix is to add to the image a width html attribute: Images are 48px x 40px and it would work for use cases where there is no image.

**Comment by Xaviju** [comment]
Fixed here: https://github.com/taigaio/taiga-front/commit/a757618d97b668a78b1ce3a8069f90f5f537ba30

**Comment by bameda** [comment]
@rriemann one question, what app are you using to make gif screenshots?

Thanks

**Comment by rriemann** [comment]
@bameda I used Byzanz (https://www.maketecheasier.com/record-screen-as-animated-gif-ubuntu/)
with this custom script: https://gist.github.com/lucy/3042755

However, you have to know in advance how many seconds you want to record, which is not really handy. There is vokoscreen which does a better job, but doesn't record to gif. However, you can create gifs from videos with various tools (ffmpeg, imagemagick convert).

**Comment by Xaviju** [comment]
@rriemann 
There is any way to improve the default GIF quality?
I tested **byzanz** but the generated gifs are not very high quality.

**Comment by bameda** [comment]
@rriemann thank you, I'll try Byzanz. I want to avoid to convert videos to gif

**Comment by rriemann** [comment]
@Xaviju I don't know. convert has some options to optimise the filesize, but therefore, you already need a source with a high quality. Let me know if you have found a solution.
