### ISSUE TITLE
System messages should not talk about oompa-loompas

### ISSUE THREAD

**Issue by fisx** [taigaio/taiga-front#685]
This is a matter of taste, but I have talked to a few people now about this and there is a wide consensus, so I'll post it here anyway: The system messages do not help your users think that you take them seriously.  It is arguably cute, and I think I miss a reference that I have missed on Futurama before, but it is also distracting and, I sometimes feel, demeaning.

I am not saying you want to demean me, though.  Taiga is nice.  Thanks!  (-:

**Comment by superalex** [comment]
Thank you very much for the feedback @fisx 

We had an existing enhancement request (https://tree.taiga.io/project/taiga/issue/3040) and I've added your comments there. I'm closing this one but keeping the taiga one open.

Regards!,
