### ISSUE TITLE
Usability: unnecessarily truncated attament file names.

### ISSUE THREAD

**Issue by fisx** [taigaio/taiga-front#686]
attachment file names are truncated, even if there is plenty of space:

![taiga-attachment-lists](https://cloud.githubusercontent.com/assets/10210727/10728294/d5c2eee4-7be0-11e5-8b74-671c6b8dfddc.png)

**Comment by bameda** [comment]
![image](https://cloud.githubusercontent.com/assets/877218/10728499/b9b32ec4-7be2-11e5-9621-e51891a426ad.png)


There is no space in a laptop screen

**Comment by bameda** [comment]
I think we can adjust a bit more.
https://tree.taiga.io/project/taiga/issue/3382

**Comment by Xaviju** [comment]
This should be fixed in next Taiga release with new attachment modules: https://github.com/taigaio/taiga-front/pull/73
