### ISSUE TITLE
Expand report output

### ISSUE THREAD

**Issue by mgilroy** [taigaio/taiga-front#694]
Is there any way to include additional fields in the generated reports? The issues report doesn't include a created date modified date or finished date. These fields are available for user stories but not issues. The created date is available in the normal web view. Being able to plot the issues over time and time to resolve can be very very helpful.

**Comment by superalex** [comment]
Hello @mgilroy 

I think you are right, it could be very helpful it makes our report system more consistent and it's also really easy to fix. I've just submitted a PR with this feature (https://github.com/taigaio/taiga-back/pull/506), I hope it can be included in master branch soon ;)

Regards!,
