### ISSUE TITLE
I lose ability to assign team members US when changing point names (kanban)

### ISSUE THREAD

**Issue by turbochris** [taigaio/taiga-front#698]
I decided to change the points in Kanban to mimic our organization. I specifically changed it to

"15 minutes or less"
"1 hour or less"
etc.
I left the values of point as-is.

Further more i Deleted the one with ZERO in value. I reinserted later when I realized all data was lost.

This causes all my assignments to be lost (in ALL of my projects - not just the one that I changed the names of the points)

To replicate:
1) Have a project with team-members of type Kanban
2) Create 1 user story
3) Assign it to a user, give it some points
4) Go to admin -> attributtes -> points
5) Delete the one with "0" in value.
6) Change name of the points

I am now unable to assign or do anything with my team members? I cannot even see them in view?

**Comment by turbochris** [comment]
Hmm it seems that it was a temporary glitch. It comes on/off now

**Comment by turbochris** [comment]
And now It's back fully. So not really sure why this is happening.

**Comment by superalex** [comment]
Hello @turbochris,

Are you using tree.taiga.io instance?, we updated the system with the new release while this issue happened so I think it could be related to the backend reload and your browser caché. Could you please clear your browser caché and confirm it's working properly now?

Regards!,

**Comment by turbochris** [comment]
Yeah. That is very likely what happened. Thanks for quick reply, you can close the ticket again. I have no issues any more.

Thanks for some awesome gui :). Only thing i really miss is that my team members can filter by "assigned to them"... I am assuming it will be available in the paid version at some point?

B.R

Chris

**Comment by superalex** [comment]
Thank you very much @turbochris 

We have to improve all the search/filter interfaces, I hope we can work on it soon

Regards!,
