### ISSUE TITLE
Enhancement suggestion: Don't lock sprints when achieving more than 100 points.

### ISSUE THREAD

**Issue by turbochris** [taigaio/taiga-front#699]
I really like that you can add a Scrum backlog with burndown, even though i'm using KanBan.

But it's a not preferable that a Sprint automatically closes once you insert enough Points to fullfill a sprint. I would like to add more assignments to a sprint - it's only good if you can overachieve.. then you know that you need to become better at assigning points to a US. 

It is fine to "overachieve" a sprint I think.

**Comment by bameda** [comment]
> I really like that you can add a Scrum backlog with burndown, even though i'm using KanBan.

You can enable kanban and backlog at the same time.

> But it's a not preferable that a Sprint automatically closes once you insert enough Points to fullfill a sprint. I would like to add more assignments to a sprint - it's only good if you can overachieve.. then you know that you need to become better at assigning points to a US.
>
> It is fine to "overachieve" a sprint I think.

I don't understand this, There is no limits in sprints, you can add all stories that you want.

**Comment by bameda** [comment]
Have you seen the admin panel???

![image](https://cloud.githubusercontent.com/assets/877218/10892741/7cf110c8-81a5-11e5-8a6a-183f434b7212.png)

![image](https://cloud.githubusercontent.com/assets/877218/10892675/17560476-81a5-11e5-8cbb-51d9078bf706.png)

```Total points``` and ```Total sprints``` are only used to draw the burndown graph and you can create more sprints and estimate more points.

**Comment by turbochris** [comment]
oh man..*blush* gotta just find the setting. Sry

Thanks for your help :)

**Comment by bameda** [comment]
You are welcome and don't worry, we need a better document to these things.
