### ISSUE TITLE
[enhancement] Quick auto assign task

### ISSUE THREAD

**Issue by yamila-moreno** [taigaio/taiga-front#70]
In kanban, when creating a task, it could be useful a button like "It's me" to assign to current user.

**Comment by Xaviju** [comment]
Assign to me button already in production! :D

**Comment by yamila-moreno** [comment]
<3<3<3<3<3 Thank you so much!

On 22 February 2016 at 07:50, Xaviju <notifications@github.com> wrote:

> Assign to me button already in production! :D
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/taigaio/taiga-front/issues/70#issuecomment-187040275>.
>



-- 
Yamila  Moreno Suárez
http://dendarii.es
http://moduslaborandi.net
