### ISSUE TITLE
Issue with visible identifiers on tree.taiga.io 1.9

### ISSUE THREAD

**Issue by GlennV** [taigaio/taiga-front#700]
I'm getting these long identifiers everywhere since this afternoon. 
Seems like they're not rendered for some reason.
We're using the hosted tree.taiga.io version with a private project.

<img width="323" alt="schermafbeelding 2015-11-02 om 16 19 29" src="https://cloud.githubusercontent.com/assets/1556321/10885471/a4f199bc-817d-11e5-92d4-d15f4778e7de.png">
<img width="357" alt="schermafbeelding 2015-11-02 om 16 19 24" src="https://cloud.githubusercontent.com/assets/1556321/10885470/a4f14bce-817d-11e5-9363-f2a619fcb9c4.png">
<img width="748" alt="schermafbeelding 2015-11-02 om 16 19 16" src="https://cloud.githubusercontent.com/assets/1556321/10885473/a4f6aa24-817d-11e5-9f05-4fbf992c2336.png">
<img width="728" alt="schermafbeelding 2015-11-02 om 16 19 14" src="https://cloud.githubusercontent.com/assets/1556321/10885472/a4f32728-817d-11e5-9aa9-d35415331965.png">

**Comment by bameda** [comment]
Is a cache problem, you have to clean the cache of your browser.
