### ISSUE TITLE
(enhancement) As a user I want to be able to make releases. 

### ISSUE THREAD

**Issue by florisvanwoudenberg** [taigaio/taiga-front#705]
This may be a big one:
As a user I want to be able to make releases. 
In Jira this works as follows: 
In the Kanban collumn done / closed, I can klik on release on top of the collumn. All issues in the collumn are bundled in a release, I can give a version and release-date and the releases are shown on a release history page.
This way it is easy to see in what release an specific user-story or issue is done.

**Comment by superalex** [comment]
Hello @florisvanwoudenberg 

We had an existing enhancement request for this one (https://tree.taiga.io/project/taiga/issue/1960), I've just added your comments there. I'm closing this one and leaving the taiga one open.

Thank you very much for the feedback!
