### ISSUE TITLE
Login from anywhere in top bar

### ISSUE THREAD

**Issue by Achifaifa** [taigaio/taiga-front#706]
I have my project on taiga bookmarked, so when I click on the bookmark it loads the kanban page. 

The problem is that in that page there is no login button (As far as I've seen), so I have to go to the main page, login and then go back.

Would it be possible to add something (Maybe just a door or other simple icon where the avatar usually is) to log in from any page that is not the main page?

**Comment by superalex** [comment]
Thank you very much @Achifaifa we will review it with our UX and design people!

**Comment by Achifaifa** [comment]
Cool, thanks :)

**Comment by bameda** [comment]
https://tree.taiga.io/project/taiga/issue/3453

**Comment by Xaviju** [comment]
Should be release in latest 1.10 release
