### ISSUE TITLE
As a user I want to be able to create a project from a gist file (template)

### ISSUE THREAD

**Issue by florisvanwoudenberg** [taigaio/taiga-front#713]
This is how it should work:

On my profile I have the option to enter one or more url's to gist-files.
When creating a new project, I can choose to upload a template or choose one of the gist-files.
This way it is easy to sync the templates (with adjustments) through the organisation

**Comment by superalex** [comment]
Hello @florisvanwoudenberg we had an existing enhancement request in Taiga related to project templates here (https://tree.taiga.io/project/taiga/issue/3034), I've added your comments. I'll close this one and keep the taiga one open.

Regards!,
