### ISSUE TITLE
Some unit tests broken in Firefox

### ISSUE THREAD

**Issue by matachi** [taigaio/taiga-front#714]
Hi, running the unit tests with an up-to-date master branch in Chromium 45 on Ubuntu 14.04 yields the following output:

    daniel@daniel-VirtualBox:~/taiga-front$ npm test

    > TaigaIO@0.0.1 test /home/daniel/taiga-front
    > ./node_modules/karma/bin/karma start

    09 11 2015 18:53:32.873:WARN [karma]: No captured browser, open http://localhost:9876/
    09 11 2015 18:53:32.886:INFO [karma]: Karma v0.13.15 server started at http://localhost:9876/
    09 11 2015 18:53:32.892:INFO [launcher]: Starting browser Chrome
    09 11 2015 18:53:37.955:INFO [Chromium 45.0.2454 (Ubuntu 0.0.0)]: Connected on socket 4WpEJNQAo_euEWtEAAAA with id 89231786
    Chromium 45.0.2454 (Ubuntu 0.0.0): Executed 22 of 166 SUCCESS (0 secs / 0.212 secs)
    Chromium 45.0.2454 (Ubuntu 0.0.0): Executed 23 of 166 SUCCESS (0 secs / 0.213 secs)
    Chromium 45.0.2454 (Ubuntu 0.0.0): Executed 24 of 166 SUCCESS (0 secs / 0.243 secs)
    Chromium 45.0.2454 (Ubuntu 0.0.0): Executed 25 of 166 SUCCESS (0 secs / 0.244 secs)
    Chromium 45.0.2454 (Ubuntu 0.0.0): Executed 26 of 166 SUCCESS (0 secs / 0.369 secs)
    Chromium 45.0.2454 (Ubuntu 0.0.0): Executed 27 of 166 SUCCESS (0 secs / 0.485 secs)
    09 11 2015 18:53:42.309:WARN [proxy]: failed to proxy /images/unnamed.png (connect ECONNREFUSED 127.0.0.1:9001)
    Chromium 45.0.2454 (Ubuntu 0.0.0): Executed 129 of 166 SUCCESS (0 secs / 1.619 secs)
    Chromium 45.0.2454 (Ubuntu 0.0.0): Executed 166 of 166 SUCCESS (4.596 secs / 2.052 secs)

While Firefox 42 on the same machine yields the following:

    daniel@daniel-VirtualBox:~/taiga-front$ npm test

    > TaigaIO@0.0.1 test /home/daniel/taiga-front
    > ./node_modules/karma/bin/karma start

    09 11 2015 18:51:14.293:WARN [karma]: No captured browser, open http://localhost:9876/
    09 11 2015 18:51:14.306:INFO [karma]: Karma v0.13.15 server started at http://localhost:9876/
    09 11 2015 18:51:14.326:INFO [launcher]: Starting browser Firefox
    09 11 2015 18:51:17.925:INFO [Firefox 42.0.0 (Ubuntu 0.0.0)]: Connected on socket gg8uinoCbWYRyvUdAAAA with id 35461835
    Firefox 42.0.0 (Ubuntu 0.0.0): Executed 24 of 166 SUCCESS (0 secs / 0.132 secs)
    Firefox 42.0.0 (Ubuntu 0.0.0): Executed 25 of 166 SUCCESS (0 secs / 0.132 secs)
    Firefox 42.0.0 (Ubuntu 0.0.0): Executed 26 of 166 SUCCESS (0 secs / 0.239 secs)
    Firefox 42.0.0 (Ubuntu 0.0.0): Executed 27 of 166 SUCCESS (0 secs / 0.264 secs)
    09 11 2015 18:51:20.178:WARN [proxy]: failed to proxy /images/unnamed.png (connect ECONNREFUSED 127.0.0.1:9001)
    09 11 2015 18:51:20.190:WARN [proxy]: failed to proxy /images/unnamed.png (connect ECONNREFUSED 127.0.0.1:9001)
    09 11 2015 18:51:20.198:WARN [proxy]: failed to proxy /images/unnamed.png (connect ECONNREFUSED 127.0.0.1:9001)
    Firefox 42.0.0 (Ubuntu 0.0.0): Executed 128 of 166 SUCCESS (0 secs / 1.001 secs)
    Firefox 42.0.0 (Ubuntu 0.0.0) tgUserTimelineItemTitle title with username FAILED
      expected undefined to equal 'title_ok'
      AssertionError@/home/daniel/taiga-front/node_modules/chai/chai.js:5285:18
      [3]</module.exports/Assertion.prototype.assert@/home/daniel/taiga-front/node_modules/chai/chai.js:206:1
      assertEqual@/home/daniel/taiga-front/node_modules/chai/chai.js:759:1
      [10]</module.exports/ctx[name]@/home/daniel/taiga-front/node_modules/chai/chai.js:3946:18
      doAsserterAsyncAndAddThen@/home/daniel/taiga-front/node_modules/chai-as-promised/lib/chai-as-promised.js:292:1
      chaiAsPromised/</</<@/home/daniel/taiga-front/node_modules/chai-as-promised/lib/chai-as-promised.js:251:21
      [26]</module.exports/ctx[name]@/home/daniel/taiga-front/node_modules/chai/chai.js:5077:18
      @/home/daniel/taiga-front/app/modules/user-timeline/user-timeline-item/user-timeline-item-title.service.spec.js:79:12 <- user-timeline-item-title.service.spec.coffee:85:8
      
    Firefox 42.0.0 (Ubuntu 0.0.0) tgUserTimelineItemTitle title with project name FAILED
      expected undefined to equal 'title_ok'
      AssertionError@/home/daniel/taiga-front/node_modules/chai/chai.js:5285:18
      [3]</module.exports/Assertion.prototype.assert@/home/daniel/taiga-front/node_modules/chai/chai.js:206:1
      assertEqual@/home/daniel/taiga-front/node_modules/chai/chai.js:759:1
      [10]</module.exports/ctx[name]@/home/daniel/taiga-front/node_modules/chai/chai.js:3946:18
      doAsserterAsyncAndAddThen@/home/daniel/taiga-front/node_modules/chai-as-promised/lib/chai-as-promised.js:292:1
      chaiAsPromised/</</<@/home/daniel/taiga-front/node_modules/chai-as-promised/lib/chai-as-promised.js:251:21
      [26]</module.exports/ctx[name]@/home/daniel/taiga-front/node_modules/chai/chai.js:5077:18
      @/home/daniel/taiga-front/app/modules/user-timeline/user-timeline-item/user-timeline-item-title.service.spec.js:169:12 <- user-timeline-item-title.service.spec.coffee:204:8
      
    Firefox 42.0.0 (Ubuntu 0.0.0) tgUserTimelineItemTitle title with sprint name FAILED
      expected undefined to equal 'title_ok'
      AssertionError@/home/daniel/taiga-front/node_modules/chai/chai.js:5285:18
      [3]</module.exports/Assertion.prototype.assert@/home/daniel/taiga-front/node_modules/chai/chai.js:206:1
      assertEqual@/home/daniel/taiga-front/node_modules/chai/chai.js:759:1
      [10]</module.exports/ctx[name]@/home/daniel/taiga-front/node_modules/chai/chai.js:3946:18
      doAsserterAsyncAndAddThen@/home/daniel/taiga-front/node_modules/chai-as-promised/lib/chai-as-promised.js:292:1
      chaiAsPromised/</</<@/home/daniel/taiga-front/node_modules/chai-as-promised/lib/chai-as-promised.js:251:21
      [26]</module.exports/ctx[name]@/home/daniel/taiga-front/node_modules/chai/chai.js:5077:18
      @/home/daniel/taiga-front/app/modules/user-timeline/user-timeline-item/user-timeline-item-title.service.spec.js:190:12 <- user-timeline-item-title.service.spec.coffee:232:8
      
    Firefox 42.0.0 (Ubuntu 0.0.0) tgUserTimelineItemTitle title with object FAILED
      expected undefined to equal 'title_ok'
      AssertionError@/home/daniel/taiga-front/node_modules/chai/chai.js:5285:18
      [3]</module.exports/Assertion.prototype.assert@/home/daniel/taiga-front/node_modules/chai/chai.js:206:1
      assertEqual@/home/daniel/taiga-front/node_modules/chai/chai.js:759:1
      [10]</module.exports/ctx[name]@/home/daniel/taiga-front/node_modules/chai/chai.js:3946:18
      doAsserterAsyncAndAddThen@/home/daniel/taiga-front/node_modules/chai-as-promised/lib/chai-as-promised.js:292:1
      chaiAsPromised/</</<@/home/daniel/taiga-front/node_modules/chai-as-promised/lib/chai-as-promised.js:251:21
      [26]</module.exports/ctx[name]@/home/daniel/taiga-front/node_modules/chai/chai.js:5077:18
      @/home/daniel/taiga-front/app/modules/user-timeline/user-timeline-item/user-timeline-item-title.service.spec.js:214:12 <- user-timeline-item-title.service.spec.coffee:263:8
      
    Firefox 42.0.0 (Ubuntu 0.0.0) tgUserTimelineItemTitle title obj wiki FAILED
      expected undefined to equal 'title_ok'
      AssertionError@/home/daniel/taiga-front/node_modules/chai/chai.js:5285:18
      [3]</module.exports/Assertion.prototype.assert@/home/daniel/taiga-front/node_modules/chai/chai.js:206:1
      assertEqual@/home/daniel/taiga-front/node_modules/chai/chai.js:759:1
      [10]</module.exports/ctx[name]@/home/daniel/taiga-front/node_modules/chai/chai.js:3946:18
      doAsserterAsyncAndAddThen@/home/daniel/taiga-front/node_modules/chai-as-promised/lib/chai-as-promised.js:292:1
      chaiAsPromised/</</<@/home/daniel/taiga-front/node_modules/chai-as-promised/lib/chai-as-promised.js:251:21
      [26]</module.exports/ctx[name]@/home/daniel/taiga-front/node_modules/chai/chai.js:5077:18
      @/home/daniel/taiga-front/app/modules/user-timeline/user-timeline-item/user-timeline-item-title.service.spec.js:237:12 <- user-timeline-item-title.service.spec.coffee:293:8
      
    Firefox 42.0.0 (Ubuntu 0.0.0) tgUserTimelineItemTitle title obj milestone FAILED
      expected undefined to equal 'title_ok'
      AssertionError@/home/daniel/taiga-front/node_modules/chai/chai.js:5285:18
      [3]</module.exports/Assertion.prototype.assert@/home/daniel/taiga-front/node_modules/chai/chai.js:206:1
      assertEqual@/home/daniel/taiga-front/node_modules/chai/chai.js:759:1
      [10]</module.exports/ctx[name]@/home/daniel/taiga-front/node_modules/chai/chai.js:3946:18
      doAsserterAsyncAndAddThen@/home/daniel/taiga-front/node_modules/chai-as-promised/lib/chai-as-promised.js:292:1
      chaiAsPromised/</</<@/home/daniel/taiga-front/node_modules/chai-as-promised/lib/chai-as-promised.js:251:21
      [26]</module.exports/ctx[name]@/home/daniel/taiga-front/node_modules/chai/chai.js:5077:18
      @/home/daniel/taiga-front/app/modules/user-timeline/user-timeline-item/user-timeline-item-title.service.spec.js:260:12 <- user-timeline-item-title.service.spec.coffee:323:8
      
    Firefox 42.0.0 (Ubuntu 0.0.0) tgUserTimelineItemTitle task title with us_name FAILED
      expected undefined to equal 'title_ok'
      AssertionError@/home/daniel/taiga-front/node_modules/chai/chai.js:5285:18
      [3]</module.exports/Assertion.prototype.assert@/home/daniel/taiga-front/node_modules/chai/chai.js:206:1
      assertEqual@/home/daniel/taiga-front/node_modules/chai/chai.js:759:1
      [10]</module.exports/ctx[name]@/home/daniel/taiga-front/node_modules/chai/chai.js:3946:18
      doAsserterAsyncAndAddThen@/home/daniel/taiga-front/node_modules/chai-as-promised/lib/chai-as-promised.js:292:1
      chaiAsPromised/</</<@/home/daniel/taiga-front/node_modules/chai-as-promised/lib/chai-as-promised.js:251:21
      [26]</module.exports/ctx[name]@/home/daniel/taiga-front/node_modules/chai/chai.js:5077:18
      @/home/daniel/taiga-front/app/modules/user-timeline/user-timeline-item/user-timeline-item-title.service.spec.js:287:12 <- user-timeline-item-title.service.spec.coffee:357:8
      
    Firefox 42.0.0 (Ubuntu 0.0.0): Executed 166 of 166 (7 FAILED) (3.63 secs / 1.317 secs)

So there are some tests that work under Chromium but not under Firefox. I haven't looked into it, so I don't know if it's a problem that manifests into something that the user experience.

**Comment by juanfran** [comment]
Thank you @matachi we only run the unit test in chrome but we will try to fix it.
