### ISSUE TITLE
Rendering errors in Midori

### ISSUE THREAD

**Issue by matachi** [taigaio/taiga-front#717]
I tried to browse the site with the web browser Midori and I encountered some rendering errors:

![screenshot from 2015-11-09 23-20-19](https://cloud.githubusercontent.com/assets/980838/11048681/a4c7811a-8739-11e5-83db-c43779f2545d.png)
![screenshot from 2015-11-09 23-27-54](https://cloud.githubusercontent.com/assets/980838/11048809/3f99f308-873a-11e5-942e-bf1d424460df.png)

I guess this might not even be a concern, but I thought that I should at least let you know.

The following is the information I found in `about:version` about my Midori installation:

    Version numbers in brackets show the version used at runtime.

    Command line midori
    Midori 0.5.11 ((null)) Midori
    GTK+ 2.24.28 (2.24.28)	Glib 2.44.1 (2.44.1)
    WebKitGTK+ 2.4.9 (2.4.9)	libSoup 2.50.0
    cairo 1.14.2 (1.14.2)	libnotify No
    gcr 3.16.0	granite No
    Platform X11; Linux x86_64
    Identification Mozilla/5.0 (X11; Linux) AppleWebKit/538.15 (KHTML, like Gecko) Chrome/18.0.1025.133 Safari/538.15 Midori/0.5
    Video Formats H264 [x]   Ogg Theora [x]   WebM [x]

**Comment by Xaviju** [comment]
Hi @matachi I've just tested Taiga in midori and seeems that MIdori does not support very well some features of CSS3 like flexbox or SVG. Looks like it is an old implementation of Webkit (those bug happen in Safari 6 as well). Taiga does not currently supports this old versions.
I fixed the login error here: https://github.com/taigaio/taiga-front/commit/d0207ed71a4e7d11b5fb24d3759a1456edb46ca5 but you will probably find more in the UI that I'm not sure we will be able to fix so easily.
