### ISSUE TITLE
Unable to delete attachment file named with Korean letters.

### ISSUE THREAD

**Issue by sungheele** [taigaio/taiga-front#718]
I can't delete files named with Korean letters in the attachment by somehow.

Here is the screenshot of the error message.

![delete_message_error](https://cloud.githubusercontent.com/assets/14971626/11055820/3386d1b0-87be-11e5-94a0-f6b1e506ac56.png)

**Comment by superalex** [comment]
Thank you very much @sungheele we will try to fix it as soon as possible

**Comment by bameda** [comment]
Hi @sungheele can you try it again

**Comment by sungheele** [comment]
I have tried to reproduce the error message, and it doesn't trigger the error message anymore.

Thank you.

**Comment by superalex** [comment]
Great! :+1:
