### ISSUE TITLE
[Q] Compiled Taiga Front - Changing Logos in Template.js and App.js causes failure

### ISSUE THREAD

**Issue by MarlNox** [taigaio/taiga-front#72]
Hi there Taiga Team, 
I'm trying to implement a local version of Taiga which features a new logo, and some new colors. 
In doing so im using docker, and pulling a modified Taiga Front image, taken from the compiled Taiga Front. 
Changing all the SVG and PNG/JPG files in the folder - changes a few instances (icons etc) of the logo but not all. 
Specifically login page remains unchanged and the upper left corner logo. 
I noticed these were SVG code in the template.js and app.js files. 
To change these I went and modified the template.js and app.js files. But when i upload this new modded version, Taiga does not load the front page at all - but rather shows blank. 

Checking the console it provides an error of this type: 

```
Uncaught SyntaxError: '' string literal contains an unescaped line break templates.js:1:292
Uncaught Error: [$injector:modulerr] Failed to instantiate module taiga due to:
[$injector:modulerr] Failed to instantiate module templates due to:
[$injector:nomod] Module 'templates' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.10/$injector/nomod?p0=templates
k/<@http://10.10.10.233/v-1623248848298/js/libs.js:1:207063

```
Any ideas how to easily change the logo of the login page and upper left corner?
or
Any ideas how to fix this error, when I do modify the files?

**Comment by DanInSpace104** [comment]
> Uncaught SyntaxError: '' string literal contains an unescaped line break templates.js:1:292

@MarlNox Looks like you messed up some syntax in your svg or js code. Try to check it with some online validators.

**Comment by yamila-moreno** [comment]
Hi there!

Do you know that we have [Taiga Community](https://community.taiga.io/) for questions? Please, check there; maybe another user has already ask something similar. If not, create your own. There are people there willing to help, members of the Taiga team members and other users.

To simplify  the process, we will systematically close all issues that are general support questions and redirect people to Taiga Community.

Taiga Team
