### ISSUE TITLE
Module where I can see all the files in the project.

### ISSUE THREAD

**Issue by hazafantasy** [taigaio/taiga-front#720]
I would like a module where I can see all the files ever attached to any User Story, and if possible a button to download all of them as .zip / .tar file.

BTW, you are awesome :)

**Comment by superalex** [comment]
Thank you very much @hazafantasy :D

We had an existing enhancement request for this one in Taiga (https://tree.taiga.io/project/taiga/issue/2813), I've just added your comments there, closing this one and leaving the Taiga one open.

Regards!;
