### ISSUE TITLE
Missing translation (custom fields)

### ISSUE THREAD

**Issue by silsha** [taigaio/taiga-front#729]
The strings for the custom field types are missing or not loaded.
Tested on current stable with German and English language settings.

![screen shot 2015-11-13 at 19 35 42](https://cloud.githubusercontent.com/assets/31850/11154173/00ff168a-8a3e-11e5-85ed-56fccda99066.png)

**Comment by bameda** [comment]
Hi @silsha, are you using tree.taiga.io or your own Taiga instance?

**Comment by silsha** [comment]
I'm using my own instance.

**Comment by bameda** [comment]
Please, update your repositories. We've fixed this and other bugs in stable branches since we released Taiga 1.9.

For example this is the commit that fix this https://github.com/taigaio/taiga-front/commit/e7f344d274a52fe488deab23f2c1c440072f2af5

And there are more commits after that https://github.com/taigaio/taiga-front/commits/stable

**Comment by silsha** [comment]
I am on the current stable release (66f3d124b5badee93df14d358ccea963b8b962fb).

**Comment by bameda** [comment]
And you still have this problem?

**Comment by bameda** [comment]
I see this in English

![image](https://cloud.githubusercontent.com/assets/877218/11155411/9a407fda-8a45-11e5-934a-7e5bddf35719.png)

and in Deutsch

![image](https://cloud.githubusercontent.com/assets/877218/11155427/b183aaaa-8a45-11e5-8c53-719f1646b14a.png)

**Comment by silsha** [comment]
I'm still having that problem. Will try to investigate.

**Comment by superalex** [comment]
This kind of failures can be related to cache browser problems. Please check your taiga-front repo is updated to the last stable version and try to clear your browser cache.

**Comment by silsha** [comment]
My mistake. It's fixed in the current stable.

**Comment by superalex** [comment]
Great!
