### ISSUE TITLE
Plugins with type 'decorator' initialized twice

### ISSUE THREAD

**Issue by msiniy** [taigaio/taiga-front#733]
I've found that my plugin with 'decorator' type initialized twice. As you can see at Line 519 in the app.coffee file it's really initialized two times:
https://github.com/taigaio/taiga-front/blob/master/app/coffee/app.coffee#L519

The same in stable branch:
https://github.com/taigaio/taiga-front/blob/stable/app/coffee/app.coffee#L519

**Comment by juanfran** [comment]
thank you!, fixed in master
