### ISSUE TITLE
Setting custom field value over REST api

### ISSUE THREAD

**Issue by kuntaldaftary** [taigaio/taiga-front#737]
Would like to set custom field value by REST api while creating a new issue or at least after creating, while patching an issue.

**Comment by superalex** [comment]
Hello @kuntaldaftary,

Actually you can set the custom attributes for any Taiga item via API but you have to use the "custom attributes" specific API's. For issues: https://taigaio.github.io/taiga-doc/dist/api.html#_issue_custom_attribute

**Comment by bameda** [comment]
And
https://taigaio.github.io/taiga-doc/dist/api.html#_issue_custom_attributes_values
to manage values for a concrete issue.


On Mon, Nov 23, 2015 at 7:50 AM, Alejandro <notifications@github.com> wrote:

> Hello @kuntaldaftary <https://github.com/kuntaldaftary>,
>
> Actually you can set the custom attributes for any Taiga item via API but
> you have to use the "custom attributes" specific API's. For issues:
> https://taigaio.github.io/taiga-doc/dist/api.html#_issue_custom_attribute
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/taigaio/taiga-front/issues/737#issuecomment-158863446>
> .
>



-- 

---


*David Barragán Merino*
* Engineer *
<david.barragan@kaleidos.net>
david.barragan@kaleidos.net  | Tel: (+34) 913562995
www.kaleidos.net/FFF8E7
