### ISSUE TITLE
Make certain custom fields mandatory during issue creation

### ISSUE THREAD

**Issue by kuntaldaftary** [taigaio/taiga-front#738]
Would like to make certain fields mandatory during issue creation - which component does the issue belong to - so that it can be routed to the correct team member automatically.

**Comment by kfuglsang** [comment]
Just giving my upvote as well. This would be a great improvement.

**Comment by nonameolsson** [comment]
This would be very good! I've tried Pipefy for a while, and that is something really good they have. It would be a big improvement to have that in Taiga.

<img width="526" alt="pipefy" src="https://cloud.githubusercontent.com/assets/1493018/19984886/8c5be272-a210-11e6-9628-af7ea376a5e3.png">
