### ISSUE TITLE
Closed tasks need a visual cue

### ISSUE THREAD

**Issue by mkaito** [taigaio/taiga-front#740]
When a task is closed, I suggest there be a visual cue to differentiate from tasks that still require action. Right now, the only difference is the word "closed" on the right.

**Comment by cmmata** [comment]
:+1: I agree. Maybe a check or a <strike> in the title.

**Comment by Xaviju** [comment]
I guess this visual cue should only be visible in the Story detail, right?

**Comment by Xaviju** [comment]
All closed sub tasks will be colore in a light gray color with a gray visual indicator. Its task name will be striked to ensure that closed tasks are visible at first sight. Status color will keep its color to avoid confusion.

 https://github.com/taigaio/taiga-front/commit/04efa2eca428b12fa869c92ff1ddbfdd455c673d
