### ISSUE TITLE
Block story completion if it contains open tasks

### ISSUE THREAD

**Issue by mkaito** [taigaio/taiga-front#741]
Story should not allow itself to be market as complete if it still contains open tasks.

**Comment by superalex** [comment]
Hello @mkaito 

It depends on the workflow of the team, we have a lot of different teams working in Taiga from a lot of different areas and some of them prefer to be able of working this way. 

We like the idea that Taiga allows you to do "more things that you can" but focusing on making the users responsible of their actions and keeping the traceability of what happened.

Thanks for the feedback! ;)
