### ISSUE TITLE
Tag entry needs autocompletion

### ISSUE THREAD

**Issue by mkaito** [taigaio/taiga-front#742]
When typing a tag into an input box, I should be able to choose from a list of tags that match what I have already typed.

**Comment by Xaviju** [comment]
This is already working on Taiga
![bug103](https://cloud.githubusercontent.com/assets/1343702/11360684/0a46e3e8-9287-11e5-8ebc-2e62cae21e2a.png)

**Comment by mkaito** [comment]
Is this your cloud version? Because it doesn't do that for the version we've deployed on our servers.

**Comment by superalex** [comment]
Yes, it's our cloud version, are you using the last stable release?

**Comment by mkaito** [comment]
I'll see if we can update our installation.
