### ISSUE TITLE
The wiki keeps losing my changes

### ISSUE THREAD

**Issue by mkaito** [taigaio/taiga-front#745]
I will edit a page, hit save, the oompa loompas will say they saved it... and it'll be gone. Just like that. I'll have to reload the page, and then the first edit will work. If I save and edit again, it gets stuck.

**Comment by superalex** [comment]
Hello @mkaito 

If reloading shows your previous changes it sounds like a cache problem. Are you after some kind of proxy/firewall?, what browser are you using?, could you try using a different one?

Regards!

**Comment by mkaito** [comment]
No proxy or firewall. firefox 42.0-2 on archlinux. A little testing in chromium suggests it works fine there.

I also noticed that taiga performs *significantly* faster in chromium than firefox.

**Comment by superalex** [comment]
Thanks for reporting @mkaito we will check what's happening with firefox and try to solve it as soon as possible. Sorry for the inconvenience ;)

**Comment by juanfran** [comment]
Tested in firefox 42 on linux mint and works well.

Could you check on firefox page inspector if there is an error? thanks!
