### ISSUE TITLE
Make it easy to upload and refer to an attachment

### ISSUE THREAD

**Issue by mkaito** [taigaio/taiga-front#746]
For example, when writing in the wiki. You can upload files, including images. But there's no convenient way to do this *while editing* a page, nor is there an easy way to refer to the upload to link to it from the page (perhaps to give context to the file).

**Comment by Xaviju** [comment]
We are currently working on it right now because we are improving the attachments module.
https://tree.taiga.io/project/taiga/issue/3561
Thanks!
