### ISSUE TITLE
The timeline is not very useful

### ISSUE THREAD

**Issue by mkaito** [taigaio/taiga-front#748]
Every entry is just a single line of text. If you use long-ish, descriptive issue/story names, the timeline becomes very hard to read, especially when dealing with tasks inside stories.

Have a look at your github dashboard for a better example. It uses short entries for simple events, but more interesting events get multiple lines, icons, images, etc. to keep things easy to "parse".

Repeated events are... well, repeated. Say for example I'll edit a wiki page multiple times as I work on something. Each and every edit will show up in the timeline. This is needlessly verbose, and repeated events should be collapsed.

The prose could probably use some work. "<name> has updated the attribute "Status" of the US <whatever> to <new status>" is needlessly verbose and rather hard to read. Some events, such as changing points for a story, really don't need their own entry in the timeline, or should be severely shortened.

When doing anything with a task, the timeline will contain the full title of the task, the story it belongs to, along with a very verbose description of what happened. All on a single line of light grey mixed with light green.

This module needs love!

**Comment by Xaviju** [comment]
Hi @mkaito 
We have been talking about this and reduced drastically the amount of information displayed in the timeline. We agree that it could be improved.
Could you please give us an example on how would you improve those verbose timeline entries?
And which would you make more important?

Thanks!

**Comment by mkaito** [comment]
Well, you can always click into a story/task detail page to get more info. So just show the essentials in the timeline. And use multiple lines, icons and colours to make things easier to parse at a glance.

**Comment by Xaviju** [comment]
Thanks for the feedback, I agree, 
The design team will review this idea to see if we can make it easier to parse.

**Comment by stevenroose** [comment]
Is there an option to change the default landing page of a project so that it opens the Kanban/Scrum view instead of the timeline?

**Comment by Xaviju** [comment]
@stevenroose no, the timeline is the default page.

**Comment by stevenroose** [comment]
Is there an opened issue already to make it possible to change that?
