### ISSUE TITLE
Add and render header anchors in rendered markdown passages

### ISSUE THREAD

**Issue by mkaito** [taigaio/taiga-front#749]
So you can easily link to specific passages.

**Comment by superalex** [comment]
Hello @mkaito 

Actually those anchors (id's) are generated for the different h1, h2, h3, aren't they working ok?

**Comment by mkaito** [comment]
At least not in the wiki.

**Comment by bameda** [comment]
In wiki pages too

![image](https://cloud.githubusercontent.com/assets/877218/11368201/a9e12eaa-92b8-11e5-9b22-f7253e78fbcc.png)

![image](https://cloud.githubusercontent.com/assets/877218/11368143/5279c7c6-92b8-11e5-8d85-298da58f5f93.png)

**Comment by mkaito** [comment]
![2015-11-24-133912_1920x1080_scrot](https://cloud.githubusercontent.com/assets/20434/11368280/d2b70910-92b0-11e5-9b6b-694e0998682b.png)

**Comment by bameda** [comment]
So "wikipageurl#stuf" and "wikipageurl#more-stuff" works.

**Comment by mkaito** [comment]
Oh, that's right, you could link to ids. Completely forgot that, and was looking for `<a>` tags.

But have you noticed the little anchor icon you get on github when you hover a header? That's pretty useful.

**Comment by bameda** [comment]
Ummmm yes, we have to make a refactor of this section (add all the history of changes, improve the editor, improve link section....) and anchor icon is a good idea.

I've created this enhancement https://tree.taiga.io/project/taiga/issue/3569

**Comment by mkaito** [comment]
Thanks
