### ISSUE TITLE
How can one follow public projects on taiga.io?

### ISSUE THREAD

**Issue by farmazon3000** [taigaio/taiga-front#751]
The https://taiga.io/ says:
```
Follow public projects
Watch them grow and evolve
```
How can one follow public projects? Where can one browse public projects?

**Comment by farmazon3000** [comment]
Relates to #664.

**Comment by Xaviju** [comment]
Hi @farmazon3000,
- To follow projects, you can go to its URL and click on _watch_ button, and select your notifications level. See https://tree.taiga.io/project/taiga/
- Same for Stories, tasks and issues  you can go into the detail and add yourself as watcher. Example https://tree.taiga.io/project/taiga/us/2127?kanban-status=38

In the next release, we will release a Discover public projects page.
You can also view the roadmap from our website taiga.io

**Comment by farmazon3000** [comment]
I see that https://tree.taiga.io/project/taiga/us/2127 is now DONE, when can we expect the relase?

**Comment by bameda** [comment]
@farmazon3000 this saturday
