### ISSUE TITLE
Readabilty of text-areas in edit mode

### ISSUE THREAD

**Issue by florisvanwoudenberg** [taigaio/taiga-front#755]
I would like the font in the text areas one or two point bigger
(and maybe another monospaced font?)

**Comment by Xaviju** [comment]
@florisvanwoudenberg Hi! I think you are right, we will make editable textarea fonts a bit larger. About the monospaced font, its the default monospaced font of your system (to avoid adding a new font). We could also change it to the default Sans, i should do some testing.
I would like to avoid adding a new font if its not a big big deal.

**Comment by florisvanwoudenberg** [comment]
Ok, another font is just 'nice to have', but the font-size is for me as a 40+-er necessary. The difference in size with the default text is too big now.

**Comment by Xaviju** [comment]
Sure, I've edited the enhancement in Taiga: https://tree.taiga.io/project/taiga/issue/3579

**Comment by Xaviju** [comment]
Fixed in master, font increased to .9rem and moved from Courier New to default monospace font (so it will probably be 'Courier New' but its customizable)
It will be shipped in next release!
Thanks
