### ISSUE TITLE
Option to disable issue & task count

### ISSUE THREAD

**Issue by RasheedAZ** [taigaio/taiga-front#76]
Is there a way to have the number followed by the # symbol not show up on US cards and tasks?

**Comment by miryamgduque** [comment]
Hi! No, there is not. Does it create some kind of conflict with something?

**Comment by RasheedAZ** [comment]
No I just didn't understand why the numbering is continues across user story cards and tasks - why each card's tasks do not begin with number 1...

**Comment by miryamgduque** [comment]
Right, sure! Each entity has this unique number so that you can refer to it at any time. Whenever you have a text field, you can type the number symbol followed by a number, and you'll get a nice link to it.

**Comment by RasheedAZ** [comment]
OK thanks.
