### ISSUE TITLE
cant login from mobile

### ISSUE THREAD

**Issue by lupa18** [taigaio/taiga-front#761]
From my phone I get a big cookie anounce that I cant close so cant log in :(

Screenshot: https://seacloud.cc/f/533f562d97/

**Comment by Xaviju** [comment]
Hi @lupa18, Taiga has no mobile version yet but you should see this login page correctly.
- Please let us know what mobile are you using and its screen resolution. 
- Ensure that there is no zoom activated.
- Confirm that the page is tree.taiga.io/login.

Ill try to make some tests and fix it if possible.

Thanks!

**Comment by lupa18** [comment]
Hi @Xaviju !! thanks !
I reviewed all options and found Firefox has "big text" set. So I changed to normal and now y can see the "x" on top right of advice and could close it.
