### ISSUE TITLE
Issues bulk editing / deleting

### ISSUE THREAD

**Issue by cmmata** [taigaio/taiga-front#762]
Hi!

I think it could be useful to have a bulk editing or deleting option in issues view. Sometimes I want to assign some issues to the same user, or change status of some ported issues or delete them. Could it be possible?

**Comment by superalex** [comment]
Hello @cmmata,

It could be possible, I'm tagging this one as an enhancement request so we can consider it when adding new features to Taiga :+1: 

Regards!,

**Comment by nkvname** [comment]
We need this feature. It's been over 3 years. Are you going to implement it? It takes a lot of time to remove all closed issues.
