### ISSUE TITLE
Team requirement mislabeled

### ISSUE THREAD

**Issue by nisckis** [taigaio/taiga-front#767]
If you create a team requirement in a Scrum project with no client requirement, the team requirement line nodes are labeled as "Incremented points by client requirements for sprint &lt;sprint_name&gt; is &lt;points&gt;".

In the very moment you create a client requirement too, the team requirement line nodes are labeled correctly.

**Comment by Xaviju** [comment]
Thanks @nisckis we will review this issue as soon as possible

**Comment by superalex** [comment]
It should be fixed right now, thank you very much for reporting @nisckis
