### ISSUE TITLE
Add to points checkbox [enhancement]

### ISSUE THREAD

**Issue by velis74** [taigaio/taiga-front#768]
Especially in the upper ranges, point ranges become quite coarse, e.g. default settings offer 10, 15, 20 and 40 points. But what often happens is someone saying "oh, and I forgot that I need an extra 2 hours to do this & that".

Would it be possible to add a checkbox or something to points assignment drop-down saying "Add to existing nn" which would perform an addition to already assigned points. This checkbox could be made to only appear when points were already assigned to avoid any confusion as to what it means.

**Comment by Xaviju** [comment]
@velis74 sorry Velis, Taiga follows an agile good practice: points are estimations, not hours. If you are setting 20 pints for a User Story it only means that is more complex than others below 20 points. If you need 2 more hours for a User Story, your estimation is almost perfect.
You can also customize points in User Story. Go to: admin > project > points
If you need time reporting, you can use integrations like toggl: https://taiga.io/support/why-is-there-no-time-tracking/

**Comment by velis74** [comment]
I aggree that points are estimations, but in the undelying database they are stored as floats. Perhaps my example wasn't the best, but points corrections are a frequent occurrence, especially in the project design phase. Adding clutter with unnecessary point stop suggestions is less helpful than being able to progressively add points to estimation.

**Comment by Xaviju** [comment]
I understand your workflow, but seems to me that we are discussing a feature related to a very personal workflow that is opposed to good practices for estimations. Lets see what others think about this.
