### ISSUE TITLE
"Points" type of custom field [enhancement]

### ISSUE THREAD

**Issue by velis74** [taigaio/taiga-front#769]
Linked to #569 and #756 and to FAQ: "why don't you allow time tracking?".

Adding a custom field of this type would support such use cases and not mess with core design of Taiga at the same time.

**Comment by Xaviju** [comment]
Since it is a custom field it depends on your workflow so you can add this field in the admin > custom fields

**Comment by velis74** [comment]
Currently supported types are "text", "multiline" and "date".
This is not about adding another custom field of an existing type. This is about adding one additional type into the "Type" select control.

**Comment by Xaviju** [comment]
Sorry if I did not understand the request correctly. Why would you need a Points Type custom field instead of just a text field (or numeric field?) If you want to track hours points will not be useful since they don't have all the values.

**Comment by velis74** [comment]
This is not to track hours. It's to add possibility to assign points to objects that are currently not supported (issues, tasks) as well as to add ability to assign points according to different models: when multiple such fields were available on one object, one could represent estimate, the other risk factor, yet another priority, etc.

**Comment by Xaviju** [comment]
Understood.
Thanks!
