### ISSUE TITLE
new tag doesn't "register" in US creation [bug]

### ISSUE THREAD

**Issue by velis74** [taigaio/taiga-front#771]
Just created a project. Started creating stories. Assigned one tag to the first story. Assigned the same tag to second story. 

Auto-suggestion did not work.

It only started working when I added a second tag.

**Comment by Xaviju** [comment]
We will review this behavior as soon as possible.

**Comment by juanfran** [comment]
This is because the tags load at startup, anyway it's rare, we'll try to fix it
