### ISSUE TITLE
filter in US is unapplied as soon as filter pane is closed [bug]

### ISSUE THREAD

**Issue by velis74** [taigaio/taiga-front#772]
As the title says. 
Go to dashboard. 
Open filter pane. 
Choose a tag (stories are filtered). 
Close filter pane (stories are not filtered any more)
Open filter pane (still shows tag as selected, but it doesn't reapply)
Select tag again (stories are filtered again), but bug no 2: now the same tag is listed twice

**Comment by Xaviju** [comment]
@velis74 wow, thats a good catch! We will try to solve this bug as soon as possible.

**Comment by juanfran** [comment]
thanks @velis74 

fixed in the next release https://github.com/taigaio/taiga-front/pull/775
