### ISSUE TITLE
After Import Project at Issue Page ( Comments Generating the user story error link)  

### ISSUE THREAD

**Issue by tomchavakis** [taigaio/taiga-front#777]
After import the project with previous taiga version i faced the following problem.
At the Issue page in the area of comments, if an issue had promoted to user story then you have a comment Generating the user story ... 
The link is not valid link page and the result produce an error page.

Solution :

Connect to the postgres and set the following query :

UPDATE history_historyentry set comment_html = replace(comment_html,'http://192.168.100.21/static/img/emojis/us.png','');

and 

UPDATE history_historyentry set comment_html = replace(comment_html,'![us]','../us/');

**Comment by bameda** [comment]
Yes, this is and old bug... the importer works find between instance with the same taiga versions.
