### ISSUE TITLE
pascalprecht.translate.$translateSanitization: No sanitization strategy has been configured. This can have serious security implications. 

### ISSUE THREAD

**Issue by marnovdm** [taigaio/taiga-front#778]
Security warning? Getting this in javascript console:

pascalprecht.translate.$translateSanitization: No sanitization strategy has been configured. This can have serious security implications. See http://angular-translate.github.io/docs/#/guide/19_security for details.

I can't determine if this has any security impact on our Taiga instance but I'd like to know for sure :)

**Comment by juanfran** [comment]
thanks @marnovdm 

we've already fixed on the master branch, it will be in the next release

**Comment by marnovdm** [comment]
awesome, thanks!

**Comment by joshgarwood** [comment]
Has this been resolved?  I am getting the same error with a recent release.

Thanks!

**Comment by juanfran** [comment]
@joshgarwood yes it's solved. Are you using https://github.com/taigaio/taiga-front-dist ?
