### ISSUE TITLE
Taiga web-ui loses title after opening project & going back to overview

### ISSUE THREAD

**Issue by marnovdm** [taigaio/taiga-front#779]
When I access our local Taiga instance the title is 'Home - Taiga' like you'd expect. When I open one of the projects we have created the title becomes 'Projectname', also like you'd expect. However when I then click on the top-left icon to go back to Taiga overview page, the title becomes the URL of the Taiga instance.

**Comment by Xaviju** [comment]
You are right, we are experiencing same behavior in both local and production Taiga's.
Thanks for reporting.

**Comment by juanfran** [comment]
thanks @marnovdm 

we've fixed on the master branch, it will be in the next release
