### ISSUE TITLE
Projects on project overview sorted by creation date instead of alphabetically/by modification

### ISSUE THREAD

**Issue by marnovdm** [taigaio/taiga-front#780]
alphabetically or by last modification date would make more sense to me. Minor feedback obviously :)

EDIT: I just figured out that I can sort the projects manually after clicking on the 'See more projects' button. I can see all the projects we have on the main overview so I never bothered to look at that page, perhaps it could be renamed to be a bit more clear that you can sort your projects there? Or perhaps the 'Project cards' could also be draggable on the main overview directly instead of only on the 'See more projects' page?

**Comment by Xaviju** [comment]
What do you think of:
- Projects are ordered by by default by *last modification date*
- Rename the button to _'manage all projects'_ or similar (there are only 10 in this view)
- If user reorder the projects, then this becomes the default order.

**Comment by marnovdm** [comment]
@Xaviju do you mean last modification date of project level properties (like title / team members) or last modification date of any story within that project? Either could make sense, I'm not sure which I'd prefer...

'Manage all projects' still doesn't really imply that you can go there to sort projects - perhaps it could be mentioned on the initial wizard (which I thought was a really nice touch!).

Thanks!

**Comment by Xaviju** [comment]
@marnovdm Im not sure either, will review with the team, but I was thinking on the last modification date of any item within a project made by the user.
Great suggestion for the projects reorder hint in the joyride, thanks!

**Comment by velne** [comment]
@Xaviju wouldn't it make sense to sort it by last updated (could be user story, tasks or issues) being at top. Or the other I could think of is most updated being at top. I guess the 2nd one would have performance impact though.

-Thanks

**Comment by Xaviju** [comment]
Yes, that's the idea!
> Or the other I could think of is most updated being at top. I guess the 2nd one would have performance impact though.

Not sure, will review with the team, but sounds like a great idea.

**Comment by velne** [comment]
great... would be happy see how this turns into reality...

**Comment by Xaviju** [comment]
The issue is open on Taiga with everybody comments to be reviewed by the team, but it could take some time. https://tree.taiga.io/project/taiga/issue/3638 
Remember that users can upvote it to gain awareness and we accept PRs as well.

**Comment by danpawlik** [comment]
Is it continued?

**Comment by yamila-moreno** [comment]
We have been doing some housekeeping work prior to Taiga6 upcoming release and we are reviewing old issues that we didn't correctly attend back then.
Regarding this issue, currently the projects are reverse ordered by creation date, and you can add custom reorder (with drag&drop) to put it according with your needs. For the time being, we're not implementing changes on this order.

Thanks for you participation on behalf the Taiga Team!
