### ISSUE TITLE
don't blank the field on submission, and allow retries

### ISSUE THREAD

**Issue by elephantjim** [taigaio/taiga-front#781]
If I'm adding a comment to a task, or editing the description, I lose my work whenever there's an error with Taiga.  This is especially frustrating if I've made a large edit.

I've noticed that when submitting a comment, the text field gets blanked after clicking the "comment" button.  If the submission fails, I lose my comment entirely.  I can't even cut and paste to a local text editor to try again later.

With the intermittent outages at Taiga over the past few weeks, this has become a critical problem.

**Comment by superalex** [comment]
Thank you very much for reporting @elephantjim

**Comment by juanfran** [comment]
hi @elephantjim 

this should be fixed, do you still have problems?

thanks

**Comment by Xaviju** [comment]
Should we close this?
