### ISSUE TITLE
Typo/glitch when deleting custom field

### ISSUE THREAD

**Issue by csfeathers** [taigaio/taiga-front#784]
In Admin -> Attributes -> Custom Fields there are two small issues in the confirmation dialog for deleting custom fields. `Remeber` is misspelled and the `</br>` tag shouldn't be displayed at all.

![delete_custom_attr](https://cloud.githubusercontent.com/assets/14216995/11743641/6a578802-a009-11e5-9c46-7bad364601ee.PNG)

**Comment by juanfran** [comment]
thanks @csfeathers 

it is fixed, it will be in the next release
