### ISSUE TITLE
Custom fields for tasks  does not appear in "new" form 

### ISSUE THREAD

**Issue by allan-simon** [taigaio/taiga-front#786]
Step to reproduce:

1.  login
2.  select a project
3. go in admin
4. attributes 
5 custom fields
6.  for task choose custom field 
7. create a custom field "complexity" 

8. now go on sprint taskboard
9. click on create task
=> a new task form is displayed

Expected Result:

we should see the custom field among the other fields

Observed Result:

We only see the default fields

**Comment by bameda** [comment]
Yes, right now custom fields are only in the detail page because the lightbox is small to put them in it. We have planned a refactor to change lightboxes for something more flexible to add more fields.

Thanks for your feedback

**Comment by varisvitols** [comment]
Why cannot lightboxes contain inner scroll?

**Comment by bameda** [comment]
Is a very bad UX practice have more than one scroll in a page.
