### ISSUE TITLE
Wiki Save&Cancel Icon locations

### ISSUE THREAD

**Issue by Sauermann** [taigaio/taiga-front#788]
The locations of the save and cancel icons are very closely next to each other.
This makes it very simple to accidentially cancel the edits while actually wanting to save them and vice versa.
I want to suggest to add additional horizontal space between the two icons just like between Preview and Save icons.

**Comment by superalex** [comment]
Hello @Sauermann,

We had an existing reported bug for this one (https://tree.taiga.io/project/taiga/issue/2369), I'm closing this one and copying your comments into the taiga issue.

Regards!,

**Comment by Sauermann** [comment]
Thanks! Was not aware of that other issue tracker.
