### ISSUE TITLE
Issues creating Hebrew tags

### ISSUE THREAD

**Issue by tmr232** [taigaio/taiga-front#791]
When trying to create a tag in Hebrew, the characters seem to be handled as their English counterparts on the keyboard, so some letters translate to symbols, splitting words.

I encountered the issue using the Hebrew letter `ת`. On an English keyboard, it is located at the same location as the comma (`,`). Using it in a tag name caused the same effect as using a comma. Other letters corresponding to English letter on the keyboard seem to work just fine.

**Comment by Xaviju** [comment]
Hi @tmr232 
We are using Open Sans font (https://www.google.com/fonts#QuickUsePlace:quickUse/Family:Open+Sans)
Could you try on google site to ensure that you can write there properly? We might need to update it.

**Comment by tmr232** [comment]
The problem is not the fonts, guess I was unclear.
When I try to create a tag in Hebrew, say: "בדיקות תוכנה" (translates to "software tests"), I get the following result:
![image](https://cloud.githubusercontent.com/assets/1386239/11925730/2720c01a-a7c7-11e5-8f8f-f5796975fb0f.png)

On the other hand, if instead of typing it, I paste the full text, everything seems to work ok (just discovered that now):
![image](https://cloud.githubusercontent.com/assets/1386239/11925746/4e19bad2-a7c7-11e5-92b2-0745df04c780.png)

Since `ת` and `,` are the same key on the keyboard, I suspect the javascript code listening on keyboard events is handling the keypress incorrectly, creating a new tag when I press `ת`.

Additionally, it seems that it does not recognize it when I press `,` on a Hebrew keyboard:
![image](https://cloud.githubusercontent.com/assets/1386239/11925864/3ab4fbf4-a7c8-11e5-826e-2f87cf278efe.png)


I hope this helps clarify the issue.

**Comment by juanfran** [comment]
thanks @tmr232 

it's already fixed
