### ISSUE TITLE
Issues Permission(Commenting)

### ISSUE THREAD

**Issue by endercrest** [taigaio/taiga-front#793]
Not sure if this is a bug or not. In a public project, only members of the project are able to add comments to issues. I think either a new permission should be added to allow for guests to add comments or make it default to allow all users to add comments. 

Currently, once a user submits and issue there is not way for them to respond to anything in the comment.

**Comment by Klapsa2503** [comment]
It should work just like here on github

**Comment by superalex** [comment]
We had an existing enhancement request to include this permission -> https://tree.taiga.io/project/taiga/issue/3003

I've copied your comments there, closing this github issue and leaving the Taiga one open.

Regards!,
