### ISSUE TITLE
Timeline and Kanban board full. Wiki, US Details, Issues, TeamBoard blank

### ISSUE THREAD

**Issue by Schwoebel** [taigaio/taiga-front#798]
I upgraded to 1.9 yesterday and started experiencing the issue described in the title.
On each page that is having the problem, this error occurs in the chrome console:
```
TypeError: Cannot read property 'length' of undefined
    at groupBy (utils.coffee:82)
    at detail.coffee:115
    at processQueue (angular.js:14454)
    at angular.js:14470
    at Scope.$eval (angular.js:15719)
    at Scope.$digest (angular.js:15530)
    at Scope.$apply (angular.js:15824)
    at angular.js:16119
    at completeOutstandingRequest (angular.js:5370)
    at angular.js:5642
```
and this in the firefox console:
```
Error: coll is undefined
groupBy@http://taiga.iusinnovation.se/js/app.js?v=1444379800383:700:17
UserStoryDetailController.prototype.loadProject/</<@http://taiga.iusinnovation.se/js/app.js?v=1444379800383:14299:37
processQueue@http://taiga.iusinnovation.se/js/libs.js?v=1444379800364:14:19572
scheduleProcessQueue/<@http://taiga.iusinnovation.se/js/libs.js?v=1444379800364:14:19839
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://taiga.iusinnovation.se/js/libs.js?v=1444379800364:15:875
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://taiga.iusinnovation.se/js/libs.js?v=1444379800364:14:30628
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://taiga.iusinnovation.se/js/libs.js?v=1444379800364:15:1281
scheduleApplyAsync/applyAsyncId<@http://taiga.iusinnovation.se/js/libs.js?v=1444379800364:14:26125
completeOutstandingRequest@http://taiga.iusinnovation.se/js/libs.js?v=1444379800364:12:1197
Browser/self.defer/timeoutId<@http://taiga.iusinnovation.se/js/libs.js?v=1444379800364:12:4214
```
I've tried deleting all cache from both browsers and restarting taiga and reseting my nginx server.
I have also crawled through the production env. setup guide to make sure everything is how it should be.  With no success.

One key thing I would like to mention is that Angular requests to the backend are coming through fine as Json.  For example my UserStories request: http://taiga.iusinnovation.se/api/v1/userstories?project=12&status__is_archived=false comes back with a hefty json string:
![image](https://cloud.githubusercontent.com/assets/1336569/12065710/4b481a7a-afdc-11e5-82c4-43b115deba1f.png)

 that includes the the information for all of the US in the system, but none of that information makes it into the page HTML.

Screenshot of a Kanban UserStory page:
![image](https://cloud.githubusercontent.com/assets/1336569/12065636/2b5a7448-afdb-11e5-8d3c-fd8c1005b795.png)

Now, I will say, that I do have an ongoing issue with Taiga-events where WS connection never completes.  But I have had that issue for a few months now and I never had a problem like this one.

Another thing that might help.  When the browser prints back what I have written in my conf.json file for the front end, it shows the right information for api, eventsURl, and contribplugins, but, it ignores when I change debug and debuginfo.

I hate to bring this up on new years eve...but I really hope to get some additional guidance before people come back to work Monday and blow up my inbox/slack channel because their Taiga isn't working properly.

p.s.  I love the system outside of this issue, I've convinced the entire company to move over to this from another system and they love it too.

**Comment by Schwoebel** [comment]
Digging further.  When holding up the coffee script detail.coffee that the browser is using vs the detail.coffee on my nginx server.  They are different.  So this must be a caching issue.

**Comment by superalex** [comment]
Hello @Schwoebel ,

Did you solve the issue?, it was finally related to the cache?

**Comment by Schwoebel** [comment]
Hi @superalex , 
I did get this solved just minutes ago.  It was a caching issue.  I just had to remove the taiga-front directory and re-clone.  That got it done.

**Comment by superalex** [comment]
Great! :+1:
