### ISSUE TITLE
Wiki Page heading can be wrapped if the heading exceeds the page width. 

### ISSUE THREAD

**Issue by PaviJas** [taigaio/taiga-front#799]
If the wiki page heading length is more than the page width, then heading can be wrapped. But now its enabling the scroll bar and heading exceeds the page width (heading is displayed beyond the page width) which is not looking good.

**Comment by Xaviju** [comment]
This should be fixed since the [1.9.1 release](https://github.com/taigaio/taiga-front/releases/tag/1.9.1).
