### ISSUE TITLE
Search fails for non-English languages

### ISSUE THREAD

**Issue by tmr232** [taigaio/taiga-front#800]
Added a task with a Hebrew title and description. Search does not find any results.

If I add any English text to the description or title, I can use it to find the task.

**Comment by superalex** [comment]
Thanks for reporting @tmr232, I think it can be related to the full text search system we are using (from postgresql), we will take a look on it!.
Regards!,

**Comment by m-messiah** [comment]
I have solve it by re-creating postgresql cluster/database with UTF-8 encoding, add custom FTS with dictionaries for language (Russian) and use them  in taiga-back/taiga/searches/services.py 

IMHO, this issue is not related to taiga-front, but needs improvements in FTS system in taiga-back.

**Comment by bameda** [comment]
You are right, but is difficult to know what language should be used in each situation. For example if I select frecnh as my language in my user profile but the project is writte in Russian.... maybe the project admin could set the default project language in the projects settings panel.

**Comment by m-messiah** [comment]
Simple way: it could be done by using utf8 without any dictionaries and search by full equality, I think.
Harder: create FTS for main supported languages and add documentation about adding new languages.

Maybe, change FTS to another system.

**Comment by bameda** [comment]
Yes, It worked in that way before, bu many users complain about and asked for more intelligent searches
