### ISSUE TITLE
"Saved!" popup when adding related tasks

### ISSUE THREAD

**Issue by tmr232** [taigaio/taiga-front#801]
When adding "related tasks", every time I press return (or click the 'save' icon) to save a new task, I get the popup saying that it was saved and everything is OK.

Seems to make more sense to only notify me on failure, when the expected result is that the task is saved.

**Comment by superalex** [comment]
Thanks for reporting @tmr232 

We will review this one with our usability people.

Regards!,

**Comment by bameda** [comment]
Fixed in https://github.com/taigaio/taiga-front/commit/60e86656eef031f56b75428f7c68432286ba962f
