### ISSUE TITLE
Use proper dialog boxes and not `prompt`.

### ISSUE THREAD

**Issue by tmr232** [taigaio/taiga-front#802]
In the editor, both the `Add Image` and `Add Link` options show a popup using `Window.prompt`. This is problematic for two reasons:

1. For the user, it is annoying to have to pass through several popups instead of just one with all relevant info. Also, the modal nature of those popups prevents the user from copying text from the editor itself.
2. From the second prompt on, Chrome shows a checkbox that allows the user to disable popups for the page. This is very problematic.

It could be replaced with javascript+html generated dialogs to eliminate the issue.

**Comment by superalex** [comment]
Thanks for reporting @tmr232 

There is a user story to fully rebuild the wiki editor (https://tree.taiga.io/project/taiga/us/2114), I'm copying your comments there and closing this one.

Regards!,
