### ISSUE TITLE
On Issue author name, appears PMPMPMPM

### ISSUE THREAD

**Issue by michelwilhelm** [taigaio/taiga-front#805]
![taiga_pmpmpmpm](https://cloud.githubusercontent.com/assets/440280/12091882/fa1d51bc-b2e0-11e5-98b5-560d855518be.PNG)
Using Portuguese translation, custom on self hosted and taiga stable

**Comment by superalex** [comment]
Hello @michelwilhelm 

We use transifex to keep Taiga translations, it seems that one of the collaborators from the portuguese team updated the date format with an invalid value, it should be fixed right now. If you are interested you can update Taiga translations using https://www.transifex.com/taiga-agile-llc/public/

Regards!,

**Comment by michelwilhelm** [comment]
Thanks @superalex :) I can help with translate to Brazilian Portuguese too ;)

**Comment by bameda** [comment]
@michelwilhelm  Cool!! :dancer: :dancer:

**Comment by superalex** [comment]
Great! :+1:
