### ISSUE TITLE
Autocompletion for email in "add members"

### ISSUE THREAD

**Issue by allan-simon** [taigaio/taiga-front#806]
it would be great to be have an autocompletion on it

a least  a simple list of email , with autocompletion on the email
the dream being to have autocompletion on username / full name/ email  with a list showing the avatar etc.  but it's optionnal i think

**Comment by superalex** [comment]
Thanks for your suggestion @allan-simon 

Just a doubt, where do you think that autocompletion list should come from?, it shouldn't be a list of all Taiga users because it could allow you spamming users.

Regards!,

**Comment by allan-simon** [comment]
hmm true, i only thought about the "private instance installed for 1 company usage" case for which it makes sense,  but as you said it becomes spammy if we have that on a public instance.

**Comment by allan-simon** [comment]
actually i think it opens a wider discussion about the fact that a lot of things that would be practical for managing a "one company instance"  which are in conflict with using taiga as a SaaS

  * autocompletion of email/account as you said
  * one dashboard for admin to see all the projects (the django admin is a good workaround but it feels like a hack (but i understand that with limited developer resource, it's better than nothing) and it requires a local account)
  *  consolidated view of several projects 
  
I'm going to open a ticket about that

**Comment by superalex** [comment]
Great!, so I'm closing this one.

Regards!,
