### ISSUE TITLE
Sign Up page should mention alternate login options such as GitHub

### ISSUE THREAD

**Issue by pdurbin** [taigaio/taiga-front#807]
I clicked "Sign Up" which took me to https://tree.taiga.io/register and made me think, "I wish Taiga supported login via GitHub. I don't want to create yet another password":

![screen shot 2016-01-06 at 9 14 52 am](https://cloud.githubusercontent.com/assets/21006/12144548/7563f36e-b456-11e5-8ca8-353f9920975a.png)

It turns out you **can** log in via GitHub if you click "Log In":

![screen shot 2016-01-06 at 9 15 53 am](https://cloud.githubusercontent.com/assets/21006/12144563/95ffc350-b456-11e5-94b7-33bdbaa29cbf.png)

I think the Sign Up page should mention alternate login options such as GitHub. It was super easy to log in with GitHub. No need to create yet another password!

**Comment by superalex** [comment]
I think you are right @pdurbin, thank you very much for reporting! ;)

Regards,

**Comment by superalex** [comment]
Should be fixed here: https://github.com/taigaio/taiga-front/pull/808 I hope it can be merged to stable soon.

Regards!,
