### ISSUE TITLE
Can't add Sprints

### ISSUE THREAD

**Issue by valentinbud** [taigaio/taiga-front#809]
Hello Taiga,

I have installed Taiga latest stable in Docker Containers using [ipedrazas/taiga-docker](https://github.com/ipedrazas/taiga-docker). 

I can access the Taiga installation just fine with default user admin. I have also created
two projects selecting Scrum template. 

I have configured the Project using ADMIN button on the left side of the screen as follows:
Number of Sprints 4 and Number of US 0.

I have also added a couple of user stories in BACKLOG. Now I want to create a sprint 
but there is no button on the right of the page under SPRINTS. A screenshot can be found [here](http://i.imgur.com/eTThjIy.png).

I have looked over the logs of taiga-backend and taiga-frontend containers and everything seems
fine, no trace dumps or any other errors.

What can I do to solve this issue or at least debug it further? Thank you.

**Comment by superalex** [comment]
It sounds really strange, if deployed properly you should see something like: 
![image](https://cloud.githubusercontent.com/assets/1579633/12167840/d7159256-b52e-11e5-971a-b331ad79fffb.png)

Did you check your javascript console to see if there is any error?, you could also check if your taiga-front copy is really updated to the last stable release -> https://taigaio.github.io/taiga-doc/dist/upgrades.html

**Comment by valentinbud** [comment]
Thank you @superalex for the prompt response. I have rebuilt the taiga-frontend container following 
the [upgrades documentation](https://taigaio.github.io/taiga-doc/dist/upgrades.html) but I see the same behaviour.

I have also enabled the javascript console and some errors pop up there. I don't think they are related to the situation I have encountered though.

<img width="1440" alt="screen shot 2016-01-07 at 12 23 58" src="https://cloud.githubusercontent.com/assets/3338528/12168269/c042a770-b539-11e5-9dba-67b6bf2e83d9.png">

What to do further in this matter? Thank you.

**Comment by superalex** [comment]
Those warnings doesn't affect (they also appear in tree.taiga.io). 

Could you execute:

```
git branch
git describe --always --tag
```

In your taiga-front folder?

**Comment by valentinbud** [comment]
I am using the [taigaio/taiga-front-dist](https://github.com/taigaio/taiga-front-dist) repository for taiga-frontend. 

```bash
$ git branch
  master
* stable

$ git describe --always --tag
1.9.0-stable-2-gfbe6fa9
```

Should I use the [taigaio/taiga-front](https://github.com/taigaio/taiga-front) repository? As far as I understand the -dist repository is the minified version of the main front repository. Please correct me
if I am wrong.

Thank you @superalex for taking your time to help me.

**Comment by superalex** [comment]
You are welcome @valentinbud 

taiga-front-dist is the correct repo, could you try doing a "git pull" on that folder?

```
git describe --always --tag                                                                                                                                                                             
1.9.1-stable
```

**Comment by valentinbud** [comment]
Here it is what I have done and it what order. First I have destroyed the environment and docker images.

```
$ docker rm -f taiga-front taiga-back taiga-postgres \
&& docker rmi -f taiga-front taiga-back
```

None of the containers had volumes mounted so when I have removed them everything is gone.

In the next step I have cloned the [taigaio/taiga-back](https://github.com/taigaio/taiga-back) repository and rebuilt the docker taiga-back image.

```
$ git clone -b stable --single-branch https://github.com/taigaio/taiga-back.git
$ cd taiga-back
$ git branch
* stable
$ git describe --always --tag
1.9.1
```

Next I have cloned [taigaio/taiga-front-dist](https://github.com/taigaio/taiga-front) repository and rebuilt taiga-front image.

```
$ git clone -b stable --single-branch https://github.com/taigaio/taiga-front-dist
$ cd taiga-front-dist
$ git branch
* stable
git describe --always --tag
1.9.1-stable
```

Start the taiga-postgres container and create user and database.

```
$ docker run -d --restart always --name taiga-postgres postgres
$ docker run -it --link taiga-postgres:postgres --rm postgres sh -c "su postgres --command 'createuser -h "'$POSTGRES_PORT_5432_TCP_ADDR'" -p "'$POSTGRES_PORT_5432_TCP_PORT'" -d -r -s taiga'"
$ docker run -it --link taiga-postgres:postgres --rm postgres sh -c "su postgres --command 'createdb -h "'$POSTGRES_PORT_5432_TCP_ADDR'" -p "'$POSTGRES_PORT_5432_TCP_PORT'" -O taiga taiga'";
```

Run taiga-back regenerate.sh.

```
$ docker run -it --rm --link taiga-postgres:postgres taiga-back bash regenerate.sh
```

Start taiga-back and taiga-front.

```
$ docker run -d --name taiga-front -p 80:80 -e API_NAME=taiga.local --link taiga-back:taiga-back taiga-front
```

First thing that changed is that now I have a ton of projects when I log in as admin :). I think this is a good sign.

I can also see Sprints for an already defined project.

<img width="1440" alt="screen shot 2016-01-08 at 08 32 57" src="https://cloud.githubusercontent.com/assets/3338528/12191923/8fba9f28-b5e2-11e5-8156-7ddf4a0c7266.png">

I go ahead and create a new project with template Scrum, define a user story and change Sprints to 4 from admin.

<img width="1440" alt="screen shot 2016-01-08 at 08 38 03" src="https://cloud.githubusercontent.com/assets/3338528/12191998/69c08462-b5e3-11e5-8cbc-e01ec2cfc111.png">

And the BACKLOG for the new project looks exactly like before :(.

<img width="1440" alt="screen shot 2016-01-08 at 08 38 50" src="https://cloud.githubusercontent.com/assets/3338528/12192002/76580376-b5e3-11e5-805c-f7e65ab8d64e.png">

The javascript console output hadn't change.

I haven't posted output of commands that exited 0. If those logs are needed to debug this further please tell me. Thanks once again.

**Comment by superalex** [comment]
I don't know what can be happening, I've just regenerated my  local instance and couldn't reproduce the issue on it or in tree.taiga.io

Could you please try reproducing it on tree.taiga.io?, I would like to know if it's a bug in the code or a failure in your instance.

Regards!,

**Comment by superalex** [comment]
Hello @valentinbud could you finally reproduce the issue in tree.taiga.io?

**Comment by valentinbud** [comment]
Hello @superalex, no I couldn't reproduce it on tree.taiga.io. I gave up eventually only to start again a couple of days later (yesterday) from scratch (with custom Dockerfile following the official install documentation) and it finally worked. Thank you for your help.

**Comment by superalex** [comment]
Great!, thank you very much for using Taiga ;)
