### ISSUE TITLE
blank screen after updating from 1.9.0

### ISSUE THREAD

**Issue by aa-matthias** [taigaio/taiga-front#810]
i followed the update guide and updated to 1.9.1 but now get a white / blank page only. source code still shows valid html markup but the page is white in firefox and edge.

**Comment by superalex** [comment]
Hello @aa-matthias 

Did you follow these steps for updating from 1.9.0 to 1.9.1? -> http://taigaio.github.io/taiga-doc/dist/upgrades.html#_upgrades_notes

It sounds like your conj.json file isn't correct. Is it in the right path, could you try empty its plugins section and try again?

Regards!,

**Comment by aa-matthias** [comment]
okay, the following command in taiga-contrib-slack has not downloaded slack.json but only slack.js, this can be closed but should be investigated in taiga-contrib-slack perhaps.

svn export "https://github.com/taigaio/taiga-contrib-slack/tags/$(pip show taiga-contrib-slack | awk '/^Version: /{print $2}')/front/dist" "slack"

**Comment by superalex** [comment]
Hello @aa-matthias 

It sounds like the "pip show" command was returning an old version of taiga-contrib-slack (where slack.json didn't exist), probably when taiga-contrib-slack was updated pip show started returning the correct version and the svn export downloaded the correct files
