### ISSUE TITLE
Mixed content when serving the site over https

### ISSUE THREAD

**Issue by florisvanwoudenberg** [taigaio/taiga-front#812]
Mixed Content: The page at 'https://scrum.studiofonkel.nl/forgot-password' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://localhost:8000/api/v1/users/password_recovery'. This request has been blocked; the content must be served over HTTPS.

I'm not able to login anymore on our self-hosted instance

**Comment by florisvanwoudenberg** [comment]
It appears that I had to remove the taiga events url from the conf.json to get it working again.

**Comment by superalex** [comment]
It should work with the taiga-events url too, I see you updated your conf.json file and removed the last comma (now it's a valid json file), could you please try adding your taiga-events url again?

**Comment by florisvanwoudenberg** [comment]
I added the url again and indeed it works again. So mayby the invalid json was causing this.
The strange thing for me is that one of our clients could login and make issues (Chrome IE), while we as a team couldn't (Chrome and FF / Mac, Linux)

**Comment by superalex** [comment]
Is it possible that the browser was caching an old valid version of the json file for your client?

**Comment by florisvanwoudenberg** [comment]
Yes, that is possible. Thanks for this update again!!

**Comment by superalex** [comment]
You are welcome! ;)
