### ISSUE TITLE
Login breaks with SSH LocalForward

### ISSUE THREAD

**Issue by qnrq** [taigaio/taiga-front#822]
When accessing Taiga via LocalForward in SSH, e.g.:

```
LocalForward localhost:4443 taiga:443
```

login fails due to failed OPTIONS request sent to localhost:443 (instead of localhost:4443). This is because Taiga explicitly uses the installation port and expects it to work instead of using the requested port, which definitely works. This requires insecure root forwarding (due to 443 being a privileged port) to resolve, or moving Taiga to non privileged (non standard) installation port.

Instead, Taiga should connect to the same port as the user is actually connected to. There's a guarantee that the currently accessed port is available but there is no guarantee that the installation port is available, e.g. as the case is with the locally forwarded port above.

**Comment by superalex** [comment]
Hello @qnrq 

You can customize the url where Taiga will connect in your conf.json file,

Regards!,

**Comment by qnrq** [comment]
That would affect all users to connect to the same port and thus break functionality for users that are not tunneling as a cost to fix connections for tunneled users.

You can patch this bug by performing OPTIONS requests to the port which is actually in use.

**Comment by superalex** [comment]
But, couldn't it break another

**Comment by qnrq** [comment]
Connecting to the port which is used and guaranteed to work would not break anything.

**Comment by superalex** [comment]
But I think it could break instances using a custom port for serving the API?, for example:
- I'm serving taiba-front in XXX.XXX.XXX.XXX:9001
- I'm serving taiga-back (API) in YYY.YYY.YYY.YYY:80000

How would you redirect ports in that situation?

**Comment by qnrq** [comment]
In this particular case it's a HTTP request being sent to somewhere else than where the content is being served from. Taiga assumes that port 443 is being used when it's not.

Ports 9001 and 80000 can be tunneled safely without root requirements as they are not in the range of privileged ports, you wouldn't have this problem binding with those.

**Comment by qnrq** [comment]
Of course one could move the install from 443 to a non privileged port, but assigning a subdomain specifically for Taiga and then requiring a non-standard port makes it a tad inconvenient.

**Comment by superalex** [comment]
Thanks  @qnrq !
