### ISSUE TITLE
"Add a new user story" overlay cannot be scrolled

### ISSUE THREAD

**Issue by PAStheLoD** [taigaio/taiga-front#824]
This makes it impossible on a small enough viewport to enter the title of the story or to click on the CREATE button. (Tried it on Firefox and Chrome, both on Linux.)

**Comment by Xaviju** [comment]
@PAStheLoD Hi! I guess you mean in the add/edition lightbox. Its known enhancement in our issues list. 
Currently Taiga does not support very small viewports in this lightboxes and we are working to fix it. In the next release, probably next week, we will ship a small improvement, but it won't work for the moment in very small viewports.

https://tree.taiga.io/project/taiga/issue/3730
