### ISSUE TITLE
Slow typing in Add story overlay 

### ISSUE THREAD

**Issue by PAStheLoD** [taigaio/taiga-front#825]
Linux, Firefox, (tried it in Chrome incognito too where all extensions are disabled).

Typing a letter causes a lot of processing and finally painting it sometimes takes ~2 seconds.
![taiga-front-slow-4](https://cloud.githubusercontent.com/assets/109316/12438483/7fa766cc-bf27-11e5-9eee-7c240b205636.png)
![taiga-front-slow-3](https://cloud.githubusercontent.com/assets/109316/12438482/7fa6c078-bf27-11e5-9145-bbec3d3253cc.png)
![taiga-front-slow-2](https://cloud.githubusercontent.com/assets/109316/12438484/7fa88462-bf27-11e5-92f3-c75d27f09af5.png)
![taiga-front-slow-1](https://cloud.githubusercontent.com/assets/109316/12438485/7fadea2e-bf27-11e5-852e-7c4b78bbd194.png)

After some trial and error it seems that the slowdown depends on the numer of sprints in the project. (At least with a new project and no sprints it's not really noticeable.)

In the [profiles.zip](https://github.com/taigaio/taiga-front/files/96900/profiles.zip) you can find the JSON exports that was created via the Firefox performance tool, and you can import them to explore the call graphs.

**Comment by superalex** [comment]
Thank you very much for reporting @PAStheLoD 

Could you please indicate where is this happening exactly?, is this happening in the backlog view when clicking in the "Add new user story" button?, writing in what field?

Regards!,

**Comment by PAStheLoD** [comment]
Hello,

Yes, in the backlog view, after clicking the "add a user story" button, typing into the Subject field.

Thanks!

**Comment by superalex** [comment]
Thanks @PAStheLoD we will check it as soon as possible! ;)

**Comment by juanfran** [comment]
thanks @PAStheLoD we've found the problem and it will be in production soon
