### ISSUE TITLE
In backlog screen,  on the right, the list of sprint quickly become cluttered 

### ISSUE THREAD

**Issue by allan-simon** [taigaio/taiga-front#826]
As sprint are ordered  by "oldest" at the bottom and newest at the top,  soon you have to scroll to access to your current sprint which soon become annoying 

Several solution that me and my team thought about:

  1. a very simple to solve this would be to reverse the ordering
  2. an other would to not expand past sprint (which is compatible with 1)
  3. for very old sprint to not display them anymore but to have a page listing all sprints for people who wants to do archaeology

**Comment by bameda** [comment]
Are you sure all your sprints are closed? 

![image](https://cloud.githubusercontent.com/assets/877218/12452690/0f558ff2-bf90-11e5-8832-8346fea9d831.png)

**Comment by allan-simon** [comment]
indeed, in the list of tasks there was some that were still not closed, preventing the sprint from being closed as well

**Comment by bameda** [comment]
Great :smile_cat:
