### ISSUE TITLE
Save button is getting wrapped to the second line for the tag in Add new issues page. 

### ISSUE THREAD

**Issue by PaviJas** [taigaio/taiga-front#827]
In the add new page, if we give more than one tag and one new tag at the end then save button at the bottom. Refer the attachment. 
![add issue](https://cloud.githubusercontent.com/assets/16509954/12456491/1ef572c0-bfc6-11e5-8314-23d86bc6598f.png)

**Comment by Xaviju** [comment]
This should be already fixed in master
