### ISSUE TITLE
More than one Unassigned tag is getting displayed for Assigned to filter to view the issues. 

### ISSUE THREAD

**Issue by PaviJas** [taigaio/taiga-front#828]
More than one Unassigned tag is getting displayed for Assigned to filter to view the issues. Refer the attachment. 
![unassigned](https://cloud.githubusercontent.com/assets/16509954/12456641/ca6cc964-bfc6-11e5-80e6-fff601027b3b.png)

**Comment by superalex** [comment]
Hello @PaviJas 

Where is this happening?, in tree.taiga.io?, could you show us an url where we can see it happening?

Regards!,

**Comment by PaviJas** [comment]
Yes. https://tree.taiga.io/project/<project name>/issues?orderBy=-status&page=1 -> in this url. And if you go to the filter and select Assigned to, then it will show the list of user for that project. In that place we are getting more than one Unassigned.

**Comment by superalex** [comment]
Sorry @PaviJas but it doesn't happen in any project so we would need to know exactly your project-slug to check what's happening.

Regards,

**Comment by PaviJas** [comment]
Sorry @superalex for the late response. I will check with my Manager about sharing the project-slug and let you know as soon as possible.

**Comment by superalex** [comment]
You could also write to support@taiga.io detailing the error so you don't publish your project url in public.

Regards!,

**Comment by PaviJas** [comment]
@superalex Sorry for the very late reply :disappointed:  I found the actual issue. If the user name starts with small letter then its showing unassigned for that particular user. :smile:

**Comment by superalex** [comment]
Hello @PaviJas thank you very much but we still can't reproduce the issue, could you please write to support@taiga.io with the url of your project so we can check what's happening exactly?

**Comment by PaviJas** [comment]
Did you tried "Sign in with Github" for the new user to a project?

**Comment by bameda** [comment]
Sorry @PaviJas but I don't understand what's the relation between github sign in and unassigned issues filter

**Comment by PaviJas** [comment]
While the user sign in using github we are getting the name from github and updating name by default right? If you go to the "Team" option and see the list of user for that project we can see for user who signed in using github will have the name which starts with small letter. Let say my name in github is "PaviJas" but in the team option if I go and look at my name its displayed as "pavijas".  But for the normal sign in user we are getting the user name from user itself. That is the difference between those two cases. So in the "Assigned to option" of "Issue" page  It showing the name for the user who signed in normal and its not showing the user who signed in via github. Can you please try this and let me know whatever I have mentioned.

**Comment by PaviJas** [comment]
I am sorry for not sharing my project url BTW.

**Comment by superalex** [comment]
I'm sorry PaviJas but we need your project url from tree.taiga.io to check what's really happening, could you please just write us to support@taiga.io?

**Comment by superalex** [comment]
Hello @PaviJas we found the issue causing this happening on your projects, it should be solved right now.

Regards!,
