### ISSUE TITLE
Add "epic" level

### ISSUE THREAD

**Issue by cpineau** [taigaio/taiga-front#829]
As a user, I would like to have an "epic" level to add user-stories on it.

Epic could be define as Project (Scrum)

**Comment by superalex** [comment]
Hello @cpineau 

We have an existing user story to include epics in Taiga -> https://tree.taiga.io/project/taiga/us/1563, I've just added your comments there. Some time ago we wrote an article about how we would like to implement them on Taiga -> https://blog.taiga.io/epic-stories.html

I'm closing this one and leaving the Taiga user story open
