### ISSUE TITLE
Error 403 for Kanban Attachments

### ISSUE THREAD

**Issue by zihniates** [taigaio/taiga-front#83]
Hello, 

I am using taiga on my own vps server. I am creating a kanban project and adding the relevant content (jpg, txt, etc.) to it.

https://prnt.sc/1ohx1qj

 it is set in permissions and members added in project as you can see in the attached photos. 

https://prnt.sc/1ohxjv4
https://prnt.sc/1ohzb6a

But I can't download the files attached to the project. I am getting 403 error.

https://prnt.sc/1ohxzki

Here is log.

172.24.0.9 - - [14/Aug/2021:10:33:01 +0000] "GET //attachments/0/a/b/5/5c1af37dd796af2a68466d7b96576a9cded87a148747c8a1163ec9dfc369/capture.png?token=YReb2w%3AgcVl6sTGyQGbaNx3LDeYPCFSO7purw_ydrMRuYtLCtosvblYBxGKKc4O6natKDAYfOEE-6bt5EqkUI9xQBlQ5A HTTP/1.0" 403 234 "https://domain.ltd/project/test/us/1?kanban-status=1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0"

How can i fix? 

Thank you for your replies.

**Comment by yamila-moreno** [comment]
Hi there!

Do you know that we have [Taiga Community](https://community.taiga.io/) for questions? Please, check there; maybe another user has already ask something similar. If not, create your own. There are people there willing to help, members of the Taiga team members and other users.

To simplify  the process, we will systematically close all issues that are general support questions and redirect people to Taiga Community.

Taiga Team
