### ISSUE TITLE
Front taskboard order view

### ISSUE THREAD

**Issue by cpineau** [taigaio/taiga-front#830]
Currently older sprints appears on first (right block) so we have to scroll down in order to retrieve current sprint after each refresh actions.

It seems more simple to have at the top of the block the current sprint.

**Comment by Xaviju** [comment]
Please, ensure that the older sprints are closed (all its Stories should be closed). 
When sprints are closed, they will be hidden and put on the bottom of the list.

**Comment by cpineau** [comment]
You re right I am sorry old tasks in progress were still on old sprint.
But thank you for the reply.

Br.
