### ISSUE TITLE
Allow hiding Wiki pages from External Users

### ISSUE THREAD

**Issue by a11smiles** [taigaio/taiga-front#831]
In some public-facing projects that have private, internal development, I would prefer to use GitHub's Wiki for product documentation (like Installation guides, Knowledge Base, etc.) and Taiga's Wiki for development documentation (Business Requirements Docs, developer guides, architecture, etc.).  Being as such, I would want most of the defaults for visibility as Taiga has already configured for External Users, but would also want the ability to hide Wiki Pages and Wiki Links from External Users.

**Comment by superalex** [comment]
Hello @a11smiles 

Actually it can be achieved in Taiga, just go to your project admin area -> permission -> External user and disable "View wiki pages" and "View wiki links", this way those external users won't see anything from your Taiga wiki.

**Comment by a11smiles** [comment]
When I go there, my View pages and view links buttons are disabled and stuck in the true position

Sent from my iPhone

On Jan 21, 2016, at 12:16 AM, Alejandro <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello @a11smiles<https://github.com/a11smiles>

Actually it can be achieved in Taiga, just go to your project admin area -> permission -> External user and disable "View wiki pages" and "View wiki links", this way those external users won't see anything from your Taiga wiki.

-

**Comment by superalex** [comment]
Sorry but I think I don't fully understand your issue, could you please attach a screenshot?

**Comment by a11smiles** [comment]
Attached screenshot...  I can't flip those switches...

![taigacapture](https://cloud.githubusercontent.com/assets/11803530/12481630/74de4cdc-c018-11e5-9759-46e63bf6f6c4.JPG)

**Comment by bameda** [comment]
This is because you have defined your project as public, if you set your
project private, this checkboxes will be enabled.

So you have set your project private and allow view mode for external users
for stories, tasks and issues.

On Thu, Jan 21, 2016 at 2:25 PM, Joshua Davis <notifications@github.com>
wrote:

> Attached screenshot... I can't flip those switches...
>
> [image: taigacapture]
> <https://cloud.githubusercontent.com/assets/11803530/12481630/74de4cdc-c018-11e5-9759-46e63bf6f6c4.JPG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/taigaio/taiga-front/issues/831#issuecomment-173568829>
> .
>



-- 

---


*David Barragán Merino*
* Engineer *
<david.barragan@kaleidos.net>
david.barragan@kaleidos.net  | Tel: (+34) 913562995
www.kaleidos.net/FFF8E7

**Comment by a11smiles** [comment]
Ahh, gotcha.

Thanks.

**Comment by bameda** [comment]
You are wlcome @a11smiles  :smiley_cat:
