### ISSUE TITLE
User story accessible even without logging in.

### ISSUE THREAD

**Issue by seanocat** [taigaio/taiga-front#832]
It seems any external user has access to internal contents if specific URL is known.
I believe such an access should be redirected to login page?

For reproduction, try below in the browser without loggin in.
https://taiga.YOURCOMPANY.com/api/v1/userstories/1?format=api

If there is any user story corresponding to user story ID 1, it will show up its contents.

**Comment by superalex** [comment]
Hello @seanocat 

It depends on the permission settings for your project, you could check them in the admin area -> permissions -> external user. For example (with a real Taiga instance):

- https://api.taiga.io/api/v1/history/userstory/371243 - from a private project, the json returned includes _error_message and _error_type indicating you must be authenticated

- https://api.taiga.io/api/v1/history/userstory/184787 - from a public project, the json returned the info about the user story

I'm closing the issue but please, feel free to reopen it if you feel there is a problem with this.

By the way, if you find issues considered as security problems it would be better if you write directly to support@taiga.io.

Regards!,

**Comment by seanocat** [comment]
Great. I really appreciate your fast response.

**Comment by superalex** [comment]
You are welcome! ;)
