### ISSUE TITLE
In taskboard screen, permit the header to be  minified 

### ISSUE THREAD

**Issue by allan-simon** [taigaio/taiga-front#833]
On a normal  desktop screen,  the part 

```
Scrum - Name 

% complete    number of points etc.
```

takes a 1/5 of the screen, which quite a lot, it would be great if one could hide/minify it in order to see more tasks at a time.

**Comment by Xaviju** [comment]
The upcoming release (October) will allow multiple views, including minified cards.

**Comment by allan-simon** [comment]
awesome, thanks
