### ISSUE TITLE
While viewing the issues details Irrelevant status is also getting displayed

### ISSUE THREAD

**Issue by PaviJas** [taigaio/taiga-front#836]
Steps to reproduce the issue: 
Step 1: Select any one issue which is created by some user. 
Step 2: Change the status of the issue 
Step 3: Now view the status which is displayed right top of the issue. (Refer: Attachment) It has to display only current status only. 
![mismatch in status](https://cloud.githubusercontent.com/assets/16509954/12535968/4bea4938-c2bc-11e5-9e3b-f996056746b1.png)

In the above case, it has to display only "Ready for Test" but it displaying closed and ready for test .

**Comment by bameda** [comment]
- READY FOR TEST is the status in the workflow.
- CLOSED/OPEN It refers to if current state is considered an open one or closed.

![image](https://cloud.githubusercontent.com/assets/877218/12536065/5b4c1fe6-c299-11e5-8f49-05282b95ef1f.png)
