### ISSUE TITLE
Split View

### ISSUE THREAD

**Issue by ph-One** [taigaio/taiga-front#838]
I would like to see an option to split each column into 3 sub columns.

A use case goes as follows: Rename my columns to "Backlog", "Breakdown", "Answer", and "Validate". I would like to have three sub columns within each of those, "WIP", "Blocked", and "Done"

**Comment by superalex** [comment]
Hello @ph-One 

I'm sorry but I don't fully understand your suggestion, could you please explain us what will be the motivation of this one?, what will be the difference with customizing your user story status to Backlog-WIP, Backlog-Blocked, Backlog-Doce, Breakdown-WIP, Breakdown-Answer...?

Regards!,

**Comment by ph-One** [comment]
@superalex Good point, and that's exactly what I did do, but it didn't quite feel right that I was dragging over entire columns -- felt as if I was skipping steps because I was dragging passed the "* Blocked" column and onto the next step. This came about after looking at other Kanban boards that had each column broken up into three "swim lanes."

Example: A board on KanBanize. https://pbs.twimg.com/media/CaN6YUQWYAARlZk.jpg:large

**Comment by ph-One** [comment]
This may be a duplicate of https://github.com/taigaio/taiga-back/issues/181, now that I know they're called swim lanes.

**Comment by superalex** [comment]
Thanks @ph-One , I think it's a duplicate one, we have been talking internally about swim lanes and it's something we would like to include in Taiga. I'm closing this one and leaving https://github.com/taigaio/taiga-back/issues/181 open

Regards!,
