### ISSUE TITLE
Some icons in web fonts do not show correctly in IE11

### ISSUE THREAD

**Issue by Sebas3440** [taigaio/taiga-front#839]
After upgrading to Taiga 1.9.1, several icons in the sidebar menu and dialogs appear as regular letters:

**In IE11 (icons show properly in Edge)**
![menu-ie11](https://cloud.githubusercontent.com/assets/16899619/12582605/364c8af4-c40c-11e5-8ac4-c5b7d45f03d8.png)

**In Chrome**
![menu-chrome](https://cloud.githubusercontent.com/assets/16899619/12582608/3947d7f4-c40c-11e5-8746-73f4830f45f9.png)

The debugging console in the IE outputs the following CSS error:
> CSS3114: @font-face failed OpenType embedding permission check. Permission must be Installable.
File: taiga.ttf
> CSS3111: @font-face encountered unknown error.
File: Opensans-Regular.ttf
> CSS3114: @font-face failed OpenType embedding permission check. Permission must be Installable.
File: OpenSans-Light.ttf
> CSS3114: @font-face failed OpenType embedding permission check. Permission must be Installable.
File: OpenSans-CondLight.ttf

Clearing the browser cache did not resolve the issue.

**Comment by Xaviju** [comment]
Thanks @Sebas3440 its already fixed here https://github.com/taigaio/taiga-front/commit/1393139cf97e4c3108a4c299336adfd7bff6f691 and will be released very soon.
