### ISSUE TITLE
Use Filter in Backlog, now can't switch to Kanban

### ISSUE THREAD

**Issue by amitspuri** [taigaio/taiga-front#840]
This is to report a BUG : P3/S3 (Low).

1. I use to find a task in Backlog, and filter them down to ease my search.
2. Having found the task, I see that I need to update the status to something else in Kanban.
3. From the right menu bar, I try switching to Kanban. But, I can't.
4. Instead I click on Timeline and then I am able to come to Kanban.

**Comment by superalex** [comment]
Thanks for reporting @amitspuri 

I'm trying to reproduce the issue but I can't, you have both kanban and backlog enabled for your project?, could you please generate a video/gif-animation showing how did you reproduce the issue?

Regards!,

**Comment by amitspuri** [comment]
@superalex / I have been able to replicate them with minimum steps, they are as follows : 
1. Yes, I have both activated, some projects (US) get addressed in Kanban, while all are listed in Backlog.
2. Goto Backlog, click 'Show Filter', the filter pane appears on the left and the 'Show Filter' option gets transformed to 'Hide Filter'.
3. So, now you click on 'Hide Filter', and now click on Kanban.
4. You can't switch to Kanban directly.

Get's replicated at your end ? I'm sorry, I can't take screen snapshot video neither do I know how to create GIFs.

**Comment by superalex** [comment]
Thanks @amitspuri I'm trying to reproduce it in tree.taiga.io but I can't, is this happening in your own instance or under tree.taiga.io?

**Comment by amitspuri** [comment]
@superalex / It's my own instance.

**Comment by superalex** [comment]
Are you using the last stable version?, could you please check what version for taiga-front are you using with the following command?

From taiga-front folder:
`git describe --always --tag `
