### ISSUE TITLE
Pressing enter when adding a tag submits the issue

### ISSUE THREAD

**Issue by ecksun** [taigaio/taiga-front#842]
When creating a new issue and adding tags, if you press enter to write another tag the issue submits.

### Steps to reproduce:

1. Go to issues
2. Press `+ NEW ISSUE`
3. Add an arbitrary subject
4. Write a tag in the tag field
5. Press enter.

### What happens:
The issue is created

### What I expect to happen:
The tag is saved and I can continue writing to add more tags.

**Comment by superalex** [comment]
Thanks for reporting @ecksun 

@juanfran I think you solved this issue in master branch, could you please check if it was backported to stable?

**Comment by juanfran** [comment]
done https://github.com/taigaio/taiga-front/commit/40cd0bd33c0588a821ada0ff786f7d56b6da345a

**Comment by ecksun** [comment]
oh my, thats awesome. This is a bit of topic but how often is fixes released to taiga.io?

**Comment by superalex** [comment]
Bugs considered critical are backported almost immediately, we have just backported this one and deployed some minutes ago so it should be fixed right now ;)

**Comment by ecksun** [comment]
Alright, nice, keep up the good work :)
