### ISSUE TITLE
Retina Display Issues

### ISSUE THREAD

**Issue by mikebronner** [taigaio/taiga-front#843]
I have attached a screenshot that illustrates some display issues in large retina screens:

<img width="1919" alt="screen shot 2016-01-27 at 08 33 51" src="https://cloud.githubusercontent.com/assets/1791050/12620406/06167fc8-c4d1-11e5-8c8d-2e324e9dad67.png">

Notice the menu icons on the left, and the text sizing and overlapping in the right side-bar, as well as the chart icon wrapping to the next line in the dark sub-menu toward the top of the page.

**Comment by bameda** [comment]
PLease, could you paste the output of the console of your browser? it seems there are more ploblems.

Clean the cache of safari and test it again, or try with other browser like Chrome

**Comment by mikebronner** [comment]
I just retested and it seems to have fixed itself. Sorry for the false alarm. :)

**Comment by bameda** [comment]
Great, thanks to you for using Taiga.
