### ISSUE TITLE
CSS not loading properly

### ISSUE THREAD

**Issue by DukeBaird** [taigaio/taiga-front#844]
When my co-workers and I go to log into taiga, as of this morning, all the CSS is completely out of whack.

In the console, its saying
```Resource interpreted as Stylesheet but transferred with MIME type text/html: "https://tree.taiga.io/v-1453901842909/styles/theme-material-design.css"```

You can scroll down and login, but the same thing is happening on the landing page

![taiga](https://cloud.githubusercontent.com/assets/7780602/12627269/ee14eb0a-c50a-11e5-9436-cc597bd56fe2.png)

**Comment by bameda** [comment]
Fixed. Thanks for report it.
