### ISSUE TITLE
Show recent changes for all projects in the overall Dashboard

### ISSUE THREAD

**Issue by Trefex** [taigaio/taiga-front#845]
Similar to a project dashboard, it could be great to see all changes that were done in all projects on the main Dashboard of taiga.

Having to go into each project can be a daunting task.

Thanks for considering this,

**Comment by leftbrasil** [comment]
Is this similar to #235 ?

**Comment by Trefex** [comment]
@leftbrasil similar, yes, but would not affect backlog, but rather an Activity Stream from all projects combined. Who did what and when and so forth?

**Comment by ffpaniago** [comment]
Is a global dashboard of all projects on the roadmap of taiga?
