### ISSUE TITLE
Backlog points filter cannot switch back to "All" properly

### ISSUE THREAD

**Issue by wsjwong** [taigaio/taiga-front#847]
Reproduce:

1. Go to backlog page.
2. Select the points filter to one of the roles (e.g. UX).
3. Select the points filter again to switch back to "All".
4. The filter label will stay in its previous state but not the "All" state.

**Comment by superalex** [comment]
Thanks for reporting @wsjwong !

**Comment by juanfran** [comment]
thanks @wsjwong It's already fixed in the master branch, It'll be in the next release
