### ISSUE TITLE
Space missing between task number and title

### ISSUE THREAD

**Issue by ecksun** [taigaio/taiga-front#848]
In the tasks list of a user story there is a space missing between the issue number and the issue title (see attached screenshot).

![taiga-task-space](https://cloud.githubusercontent.com/assets/135807/12747563/0a07dc5c-c9a5-11e5-8595-cd1a8c88b896.png)

**Comment by Xaviju** [comment]
Thanks @ecksun has been already reported https://tree.taiga.io/project/taiga/issue/3851
