### ISSUE TITLE
[Q] Can I insert a iframe into rich editor? Or how do I make it?

### ISSUE THREAD

**Issue by jianzhichun** [taigaio/taiga-front#85]

**Comment by yamila-moreno** [comment]
Hi there!

Do you know that we have [Taiga Community](https://community.taiga.io/) for questions? Please, check there; maybe another user has already ask something similar. If not, create your own. There are people there willing to help, members of the Taiga team members and other users.

To simplify  the process, we will systematically close all issues that are general support questions and redirect people to Taiga Community.

Taiga Team
