### ISSUE TITLE
US "Assign to me" link is not green

### ISSUE THREAD

**Issue by eklockare** [taigaio/taiga-front#852]
When viewing "USER STORY DETAILS" on the right side of the interface:

![taiga_assign_to_me](https://cloud.githubusercontent.com/assets/9142473/12752919/eecebcf6-c9c4-11e5-9f74-71654935689b.png)

What I expect:
That "Assign to me" is highlighted in green as links usually are.

What I see:
"Assign to me" is in black, not communicating click-ability.

**Comment by Xaviju** [comment]
Thanks for reporting @eklockare

**Comment by Xaviju** [comment]
Should be already fixed
