### ISSUE TITLE
Feature Request: Select fields to display in backlog

### ISSUE THREAD

**Issue by jpros** [taigaio/taiga-front#857]
As a former user of Atlassian JIRA, I would like to select which fields to display in backlog screen.

It should be like a selector with a combobox to select multiple fields (custom fields and default fields), and those fields are then added to the grid.

It would also be nice to have the number of tasks and attachments in that US.

Thank you for the great job! 

Regards,
João Paulo Ros

**Comment by superalex** [comment]
Thanks for the feedback @jpros

I think it's a duplicated one, we have this existing feature request  -> https://github.com/taigaio/taiga-front/issues/571

Regards!,
