### ISSUE TITLE
As a manager using Kanban I want to have a way to know how many points have been done

### ISSUE THREAD

**Issue by allan-simon** [taigaio/taiga-front#859]
we're able to set complexity point on issues, but our team members, especially managers are reporting their frustration to not be able to know how many "points' have been done during a given period of time (one week/two week, it can be arbitrary at first)

**Comment by superalex** [comment]
Hello @allan-simon 

We had an existing user story to include stats and graphs in Kanban, I've just added your comments there. As a workaround you could create the CSV reports feature to create any custom report you want, you can see a video example here -> https://www.youtube.com/watch?v=tdt7nqXVf_E
