### ISSUE TITLE
Story tasks should show votes

### ISSUE THREAD

**Issue by siliconalchemy** [taigaio/taiga-front#860]
Hi, currently in the 'Related Tasks' list of a User Story Details page:
- Each task should show votes against it.  Votes show in issues and backlog screen so to be consistent (and useful) they should also show here.  Also in the sprint taskboard - I can't see anywhere currently that you can see the votes against a task.

[edited to remove bug reference]

**Comment by Xaviju** [comment]
The bug is already closed, but your enhancement request should be reviewd first. Should I close this or you'd like to edit it?

**Comment by siliconalchemy** [comment]
Could you please reference the bug?  I tested this against master as of last night.

**Comment by Xaviju** [comment]
Sure, has been fixed here https://github.com/taigaio/taiga-front/commit/acd1f7646b8e8aada5f78dd0eb185e461db0eb23 and has been uploaded a few minutes ago and tested in production.

**Comment by siliconalchemy** [comment]
Ah, great thanks :)  I've edited the title of this issue, is that good enough or should I edit the comment as well?

**Comment by Xaviju** [comment]
It would be nice if you could remove the first list point to avoid confusion if someone else visits this.
Thanks!
