### ISSUE TITLE
US/task comments might be better ordered most recent at top

### ISSUE THREAD

**Issue by losttheplot** [taigaio/taiga-front#861]
Currently, one has to scroll down the viewport to see the most recent comment. To add a new comment, one has to scroll down again to open up the (small by default) comment window, then scroll down yet again to be able to see and click the submit button. Similarly, previous comments beyond the number threshold are hidden and not immediately obvious that they are there. Far better all round, IMHO, would be to show all comments at all times, but to list them in order of most recent at top, with a 'new comment' box above the most recent one.

...or maybe add a list ordering option.

**Comment by superalex** [comment]
Thanks @losttheplot we will review it with our UX and design people.

Regards!,

**Comment by Xaviju** [comment]
This is being developed here https://github.com/taigaio/taiga-front/pull/1020 and will be available on next release
