### ISSUE TITLE
Sprint item drag-dropbox hides after scrolling

### ISSUE THREAD

**Issue by digiajay** [taigaio/taiga-front#864]
Sprint items can be dropped at the top right corner but I have a huge list of backlog.  When I scroll down, it's hard to scroll up and put it in the dropbox

**Comment by superalex** [comment]
Hello @digiajay 

If your project use the Scrum template the priority of the story is represented according to its position in the Product Backlog

![image](https://cloud.githubusercontent.com/assets/1579633/12886935/2fecdeba-ce71-11e5-8706-d49b51da99c5.png)

So you shouldn't be moving stories drag from the bottom. 

As a workaround you could enable some checkboxes from the left column and use the option "move to current sprint"

**Comment by digiajay** [comment]
Thanks for the clarity.  I appreciate the design.  By default it indirectly forces/comply user to go according to sprint rules.. Great!

**Comment by digiajay** [comment]
Thanks for the clarity.  I appreciate the design.  By default it indirectly forces/comply user to go according to sprint rules.. Great!
