### ISSUE TITLE
Sprint backlog becomes difficult to assign backlog tasks to sprints. 

### ISSUE THREAD

**Issue by levibostian** [taigaio/taiga-front#866]
This is an annoyance that I have encountered while being a user of Taiga. (Simply here to offer an improvement to this amazing platform. I want to thank you all so very much for creating Taiga. I have completely switched all of my scrum/agile projects over to Taiga and I am planning on using it for the distant future I am in love with it! I also recommend it to dozens of others.) 

---

In the sprint backlog screen I insert a bunch of user stories. Lets say, 4 dozen user stories. After creating this long scrollable list of user stories, I want to create sprints for all of these user stories and assign each user story to a sprint. 

So I create sprints along the right hand side of the screen and then I drag user stories into each sprint. Everything technically works great. 

But from a UX standpoint, it can be a bit of a pain. Lets say a user story on the very top of my backlog list goes into sprint 12 which is far down the screen, I need to drag my user story down the screen until I see sprint 10 to drag it inside of it. 

Sure, I can collapse sprint's user stories but if I click on a user story and go back to the backlog, all of the sprints all uncollapse so I am back to square one. 

One idea that I had, have the sprint backlog become 2 separate scrollable lists. So the backlog tasks can be scrolled up and down and the sprints list can be separately scrolled up and down. This would be very helpful and solve my issue I believe.

**Comment by Xaviju** [comment]
Hi @levibostian 

Understand your use case and UX issue, we have talked about your suggestion before and we have an open enhancement to review the double scroll proposal. 
For the moment, just a recommendation: if using backlog the idea is having it properly prioritized so when creating a new sprint (ideally you should do it when closing the previous one) you should just move the top user stories in your backlog. The ideal situation should be moving top user stories to the top sprint, if that's not the situation probably you should repriorize the backlog properly.
Ideally, you should not create all sprints at one, the first time because that would lead to a static, instead of agile, development planning.

Said that, you can always select multiple Stories from the input and move all of them at once by drag and drop or clicking on the _Move to sprint_ button.

Thanks for your kind words, thanks for using Taiga!

**Comment by levibostian** [comment]
@Xaviju, thank you very much! You are so right, I am doing it wrong. 

This is my situation: I create a long list of user stories in my backlog. Then, I need to create a time estimate for how long a project will take me. This is usually pretty easy to do as I can take the total number of user story points and divide by my velocity. This is what you are saying and is correct. 

However, some of my user stories should be placed in the "icebox" and not in my actual backlog of tasks to do. So, there are some tasks that I have that I do not want to be included in the total number of user story points in the project. They are tasks that will possibly be done in the future, but not for these initial sprints. 

I don't see any sort of icebox functionality. Am I incorrect? Until I find a solution, I will probably continue to place user stories into sprint boxes as my way to differentiate between user stories in my icebox and not in my icebox.

**Comment by Xaviju** [comment]
Now I understand better.
When we start a project, we usually have more stories than points and time to do. So we have some stories in our backlog that will probably not be done in the estimated time. Lets say, they are _out of scope_
In the backlog there is a functionality that we called the _Doomline_. You can set it in your project settings (Admin > project > project details). we usually estimate the **total amount of points** we have in a project and the **total amount of sprints** we expect to do. After setting it up, if your defined backlog points are higher than your defined points in config, a red (ugly) bar will appear in the project scope you set in the Admin. All User Stories under that line will be in your icebox and are out of the project scope.
Could that help you?

**Comment by levibostian** [comment]
Thanks again. I did not know that the doomline existed. I have never set the max points and/or number sprints in the admin settings as my projects do not have a max for either of these. My projects deadlines are set when the functionality of the software is complete. I still really like having an icebox to set aside user stories as things that are simply not very important and I will use in a different iteration of development. 

I *could* satisfy my needs with your suggestion by counting the number of points that are not in my icebox and set that in my admin settings but that seems like work I should not have to do. Wouldn't it be better if Taiga did this math for me by just labeling user stories as "iceboxed". 

---

Let me explain that idea. The backlog has a section for the icebox for you to drag in user stories into it (don't know the UX for this yet but that is not important here). As I am creating user stories and assigning points to them, I can put user stories into the icebox as I go along. So in the end, I may/may not have user stories in my icebox, I have user stories in my backlog built up and I have a sprint created. Perfect now I am ready for my development iteration. 

Now, the icebox functionality is useful because it sets the maximum number sprints and/or maximum number points *for you* by summing up the points in each section (backlog and icebox) instead of having me do that math manually.

This would be great for people like me who do not have a set deadline for a project (determined by settings max number sprints/story points) but for people like you who still want to set a deadline you can still go into the admin settings and everything works as it doe already. 

What are your thoughts?

**Comment by Xaviju** [comment]
I will review this issue with the team since your use case is different to the one we expected in Taiga. Thanks for sharing this enhancement proposal!

**Comment by levibostian** [comment]
No problem, thank you so much for doing that. Love Taiga, keep up the great work.

**Comment by juanstiza** [comment]
:+1: +1 here!. What about making the sprint list sticked to the top, so when you scroll down, you'll always see it?

**Comment by Xaviju** [comment]
@juanstiza we talked abuot that here -> https://github.com/taigaio/taiga-front/issues/866#issuecomment-181739675
