### ISSUE TITLE
Layout of the "New User Story" screen is slightly broken in Safari

### ISSUE THREAD

**Issue by ss-abramchuk** [taigaio/taiga-front#868]
There is a layout problem in Safari. Total points on the "New User Story" screen is placed on the right side. Chrome shows this screen in right way.
![broken-layout](https://cloud.githubusercontent.com/assets/7886854/12917282/8ca25a94-cf49-11e5-930e-801779a291f4.jpg)

**Comment by Xaviju** [comment]
Hi @ss-abramchuk thanks for reporting.
What version of Safari are you using?

**Comment by ss-abramchuk** [comment]
Hi @Xaviju, version of Safari is 9.0.3.

**Comment by Xaviju** [comment]
Testing it right now :)

**Comment by Xaviju** [comment]
Mmm seems to be a Safari bug... https://bugs.webkit.org/show_bug.cgi?id=136041#c2

**Comment by Xaviju** [comment]
Should be fixed now here https://github.com/taigaio/taiga-front/commit/af00d7ef11f5f852bc35b118c629e0be95ca1904
