### ISSUE TITLE
Sprint->Calender typo within month "december"

### ISSUE THREAD

**Issue by dstahlmann** [taigaio/taiga-front#869]
Only a little typo or translating problem ( translate.google did not know the word diciember :D )
See screenshot for the problem.
![issue](https://cloud.githubusercontent.com/assets/16625689/12926784/473f5076-cf65-11e5-8d20-28d93d94b741.png)

**Comment by bameda** [comment]
Hi Daniel, sorry but I don't know what's the lenguage you are using, but you can fix translation typos by yourselves:

> ## Help us to translate in your language:
> 
> We are ready now to accept your help translating Taiga. It's easy (and fun!):
> 
> - Access to our team of translators with this link: [Help Taiga to trasnlate content](https://www.transifex.com/taiga-agile-llc/)
> - Set up an account in Transifex
> - Start contributing.
> 
> Join us to make sure your language is covered!

Thank you very much for using Taiga and for your feedback.

**Comment by dstahlmann** [comment]
Solved the issue by myself. Used a bit more time and translated a few more items.

**Comment by bameda** [comment]
cooolll!!! Thank you very mutch.
