### ISSUE TITLE
As a user I should not have to refresh the taskboard to view when a task is changed

### ISSUE THREAD

**Issue by allan-simon** [taigaio/taiga-front#872]
it would be great if there was a background javascript to check for update 
that would avoid the "in my taskboard i see the ticket as 'new' "   "errr, did you refresh your page?"

and it will ease to put taiga taskboard on the main LCD screen ^^

**Comment by bameda** [comment]
Hi @allan-simon are you using taiga.io or your own instance of Taiga?

**Comment by allan-simon** [comment]
my own instance (and which make found that I have no way in the interface to see the version of taiga I'm using :) )

**Comment by bameda** [comment]
Te get the backlog, kanban and sprint taksboards updated in real-time you have to use taiga-events. Have you installed taiga events?

To get the current taiga-front or taiga-back version use the command `git describe --tags` in the two directories.

**Comment by allan-simon** [comment]
I see, I didn't install taiga-events, so the problem is on my side, sorry.

**Comment by bameda** [comment]
Don't worry, I think this section in taiga-doc is confuse and we have to explain it better
