### ISSUE TITLE
Historical sprints ....

### ISSUE THREAD

**Issue by oddjobz** [taigaio/taiga-front#876]
I've just completed a sprint and it's "vanished" from my control panel .. is there a way to view historical sprints?

**Comment by superalex** [comment]
Hello @oddjobz 

You should have a button at the bottom of the sprints column to show them:

![image](https://cloud.githubusercontent.com/assets/1579633/13041508/1149a082-d3b8-11e5-9ad0-3856dbce7f6e.png)


Regards!

**Comment by oddjobz** [comment]
I Do ! many thanks ... 

I think maybe if you have quite a few sprints .. it's not too obvious ... :) 

| From: "Alejandro" <notifications@github.com>
| To: "taigaio/taiga-front" <taiga-front@noreply.github.com>
| Cc: "Gareth Bult" <oddjobz@linux.co.uk>
| Sent: Monday, 15 February, 2016 06:45:32
| Subject: Re: [taiga-front] Historical sprints .... (#876)

| Hello @oddjobz

| You should have a button at the bottom of the sprints column to show them:

| Regards!

| —
| Reply to this email directly or view it on GitHub .

**Comment by superalex** [comment]
Great!,

We will review this with our UX people :)

Regards!,
