### ISSUE TITLE
Please add a Favicon

### ISSUE THREAD

**Issue by simpsonjon** [taigaio/taiga-front#877]
It's a tiny issue, but it would be nice to have a favicon image for bookmarks. Right now it just shows as a page icon in chrome.

**Comment by bameda** [comment]
There's a favicon https://github.com/taigaio/taiga-front/blob/master/app/index.jade#L16 defined

For example, in tree.taiga.io: http://www.google.com/s2/favicons?domain=tree.taiga.io

**Comment by simpsonjon** [comment]
Ah you're right, but taiga.io still shows me the document icon. I'll just change my bookmark, thanks.

**Comment by bameda** [comment]
OK, taiga.io, our landing page, doesn't have a favicon. http://www.google.com/s2/favicons?domain=taiga.io

**Comment by Xaviju** [comment]
Should be fixed now!
