### ISSUE TITLE
Do not forward to /not-found or /error

### ISSUE THREAD

**Issue by brettp** [taigaio/taiga-front#879]
Changing the URL to /not-found or /error is frustrating because you can't solicit feedback from a user about what URL they were on when an error occurred. It's also frustrating because if you go offline and have taiga open, it will forward you to /error because it can't access the taiga server.

**Comment by superalex** [comment]
@juanfran do you think it would be possible showing the error not-found pages without redirecting the user?

**Comment by juanfran** [comment]
yes but I think there are other solutions, like a button to reload the previous page and info about the error

**Comment by superalex** [comment]
Thanks @juanfran we could talk about it with the reset of the team to make a decision about it :)

**Comment by brettp** [comment]
> yes but I think there are other solutions, like a button to reload the previous page and info about the error

I think this might be trying to duplicate features that already exist and that users are accustom to. Users already know how to reload a page and copy a URL with their browsers, so I'm concerned introduce new, non-standard ways to do this will require unnecessary user training.

**Comment by smichel17** [comment]
>yes but I think there are other solutions, like a button to reload the previous page and info about the error

@juanfran could I turn this on its head? What's the benefit of redirecting instead of just having 404s show the exact same text as /not-found?

**Comment by juanfran** [comment]
I've made a PR with with this, in the next release the url won't change

https://github.com/taigaio/taiga-front/pull/1009
