### ISSUE TITLE
Allow to choose tag from current list of tags

### ISSUE THREAD

**Issue by monsieurmax** [taigaio/taiga-front#880]
Hello,

Tags are useful, however existing values are displayed only once you start to enter a letter in the tag field. The already available tags are filtered by the letter you just entered.

If you don't know which tag to enter, choosing from existing ones, you cannot easily display all the available tags.

Use case : A new contributor on the project may not know all the tags and may not want to create new tags where existing ones are fine. He cannot easily find tags.

Best regards.

**Comment by superalex** [comment]
Hello @monsieurmax 

We were speaking about this with our UX people some months ago and it didn't sound like a good idea for the user. We were thinking about projects with 500 different tags and that kind of selector aren't very useful.

What we would like to include is an area where you can manage the tags from your project (https://tree.taiga.io/project/taiga/issue/2938), I've just copied your feedback there and closing this issue.

Regards!,

**Comment by terrycloth** [comment]
A drop-down list of all existing tags would be a little unwieldy for projects that use hundreds of tags. But for users who don't remember or don't yet know all the tags used in a project, the only alternative is to open a Taiga admin page where they can see the tags (either the dedicated tag management page @superalex alludes to, or the Backlog filters list or whatever), and either navigate back and forth, or open Taiga in multiple tabs while they look up tags to enter. This doesn't seem like great UX either.

Just a thought.
