### ISSUE TITLE
Gravizo diagrams not displayed properly

### ISSUE THREAD

**Issue by marton78** [taigaio/taiga-front#881]
The online too [gravizo](http://www.gravizo.com/) enables simple embedding of Graphviz diagrams into markdown and HTML by generating an image on the fly.

The following markdown

``` text
![Alt text](http://g.gravizo.com/g?
  digraph G {
    rankdir=LR;
    A -> B -> C;
  }
)
```

generates the image:

![A diagram](http://g.gravizo.com/g?
  digraph G {
    rankdir=LR;
    A -> B -> C;
  })

However, in Taiga, only a tiny 11x11 pixels image is displayed.

**Comment by superalex** [comment]
Thanks for reporting @marton78 

I think Taiga is filtering urls aggressively to avoid xss injections and this url is being transformed  to http://g.gravizo.com/g?digraph

If copy that url into your browser the special chars are transformed to url encoded ones and Taiga won't remove them. You could try using 

```text
![Alt text](http://g.gravizo.com/g?%20digraph%20G%20{%20rankdir=LR;%20A%20-%3E%20B%20-%3E%20C;%20}%20))

**Comment by marton78** [comment]
Thanks, that's useful to know and a nice workaround.

**Comment by marton78** [comment]
However, it makes my markdown files quite hard to maintain. I it possible to whitelist particular hosts to except them from filtering?

**Comment by superalex** [comment]
It sounds a bit dangerous to me, we should think more deeply about it...You also maintain your markdown files as usual but include a "short url" generated for that gravizo url.
