### ISSUE TITLE
moving unassigned tasks to a different sprint

### ISSUE THREAD

**Issue by holden-caulfield** [taigaio/taiga-front#884]
Seems there is no way to move unassigned tasks to another sprint. If the tasks belong to a story, I can always drag the story to a different sprint on the backlog view, but unassigned tasks do not live on a story. 

Is there a way I can do that besides deleting/re-adding the task (which is annoying)?

**Comment by bameda** [comment]
Unassigned tasks were in order to manage jobs with a short duration, necessaries to finish a sprint (ex. deploy in production, upgrade some dependencies....) right now it's not possible to move unassigned tasks between sprints.

**Comment by FreeMinded** [comment]
I would also fancy an easy way to move unassigned tasks to a different sprint. I'm using unassigned task as my personal trask list an a "personal" sprint a week to organize myself.

**Comment by drzraf** [comment]
In case of emergencies I've sometimes to transform a quick and dirty task into a full story

Having the possibility to transform an existing unassigned task into a story would give some flexibility. Otherwise I've to :
* create a story
* add to the sprint
* move the unassigned task under the story
(I know this is not very SCRUM-legal process)

**Comment by jaypeedevlin** [comment]
+1 this would be useful for our workflow.

**Comment by FreeMinded** [comment]
A bit more generic... it would be great if a task could easily (i.e. with drop down) be assigned to a different user story no matter in which sprint it is, and a user story to a different spring or to the backlog. Currently it needs a lot of going back and forth or even creating "moving-around" user story to be able to accomplish this.

**Comment by cftoselli** [comment]
+1
