### ISSUE TITLE
Customize Team Names

### ISSUE THREAD

**Issue by HeneryH** [taigaio/taiga-front#885]
I'm trying to use an Agile methodology for an effort that isn't software design.  Most of the concepts are still applicable but I would like to change the team names to something other than UX, Front, Back etc.

Can I customize these from the Admin area?

**Comment by bameda** [comment]
Yes, you can add, edit or remove roles in `Admin > Permissions` and asign users to them in `Admin > Memberships`

**Comment by HeneryH** [comment]
Thank you. Perfect.

**Comment by bameda** [comment]
You are welcome.
