### ISSUE TITLE
Always redirecting to error page if access frontend over external network.

### ISSUE THREAD

**Issue by ddonindia** [taigaio/taiga-front#896]
I am trying to selfhost taiga on my RPI 2 box. I am able to successfully install and access taiga frontend from my local network (with local and external IP ). But when I try to access it from some other network
over external IP I am always getting redirected to /error page.

First it tries to load /discover page then after few seconds it redirects to /error page.
following are the two request in nginx access logs:

> 01/Mar/2016:12:35:52 +0530] "GET /browserconfig.xml HTTP/1.1" 200 1460 "-" "Mozilla/5.0 (Windows Phone 10.0; Android 4.2.1; Microsoft; Lumia 640 Dual SIM) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Mobile Safari/537.36 Edge/13.10586"
> 01/Mar/2016:12:35:58 +0530] "GET /favicon.ico HTTP/1.1" 401 605 "-" "Mozilla/5.0 (Windows Phone 10.0; Android 4.2.1; Microsoft; Lumia 640 Dual SIM) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Mobile Safari/537.36 Edge/13.10586"

There is no load on RPI box I am only hosting Taiga on it.

Can you please help?

**Comment by ddonindia** [comment]
I think problem is even I am accessing from external IP some requests are going to internal IP.
![error](https://cloud.githubusercontent.com/assets/16450468/13420618/d0d0ad50-dfad-11e5-9b0c-37b159df7398.png)

But not sure why its happening.  I have replaces my external hostname in load.py file under settings folder of taiga-back folder.

**Comment by ddonindia** [comment]
I got it working after after fixing static directory in nginx enabled site config.
Now next problem.
I am able to login but my existing projects are not visible also I am not able to create new projects getting 401 error.


> [01/Mar/2016 08:31:58] "GET /api/v1/projects?member=16&order_by=memberships__user_order HTTP/1.0" 200 2
**> [01/Mar/2016 08:31:59] "GET /api/v1/user-storage/joyride HTTP/1.0" 404 62**
**> [01/Mar/2016 08:31:59] "POST /api/v1/user-storage HTTP/1.0" 401 124**
> [01/Mar/2016 08:32:09] "POST /api/v1/auth HTTP/1.0" 200 672
> [01/Mar/2016 08:32:10] "GET /api/v1/projects?member=16&order_by=memberships__user_order HTTP/1.0" 200 2
> [01/Mar/2016 08:32:11] "GET /api/v1/tasks?assigned_to=16&status__is_closed=false HTTP/1.0" 200 2
> [01/Mar/2016 08:32:11] "GET /api/v1/userstories?assigned_to=16&is_closed=false HTTP/1.0" 200 2
> [01/Mar/2016 08:32:11] "GET /api/v1/issues?status__is_closed=false&watchers=16 HTTP/1.0" 200 2
> [01/Mar/2016 08:32:11] "GET /api/v1/tasks?status__is_closed=false&watchers=16 HTTP/1.0" 200 2
> [01/Mar/2016 08:32:11] "GET /api/v1/issues?assigned_to=16&status__is_closed=false HTTP/1.0" 200 2
> [01/Mar/2016 08:32:11] "GET /api/v1/userstories?is_closed=false&watchers=16 HTTP/1.0" 200 2
**> [01/Mar/2016 08:32:20] "PUT /api/v1/user-storage/joyride HTTP/1.0" 401 124**
> [01/Mar/2016 08:32:46] "POST /api/v1/auth HTTP/1.0" 200 667
> [01/Mar/2016 08:32:47] "GET /api/v1/projects?member=4&order_by=memberships__user_order HTTP/1.0" 200 2
> [01/Mar/2016 08:32:48] "GET /api/v1/userstories?is_closed=false&watchers=4 HTTP/1.0" 200 2
> [01/Mar/2016 08:32:48] "GET /api/v1/tasks?assigned_to=4&status__is_closed=false HTTP/1.0" 200 2
> [01/Mar/2016 08:32:48] "GET /api/v1/userstories?assigned_to=4&is_closed=false HTTP/1.0" 200 2
> [01/Mar/2016 08:32:48] "GET /api/v1/issues?assigned_to=4&status__is_closed=false HTTP/1.0" 200 2
> [01/Mar/2016 08:32:48] "GET /api/v1/tasks?status__is_closed=false&watchers=4 HTTP/1.0" 200 2
> [01/Mar/2016 08:32:48] "GET /api/v1/issues?status__is_closed=false&watchers=4 HTTP/1.0" 200 2
> [01/Mar/2016 08:32:52] "GET /api/v1/project-templates HTTP/1.0" 200 13431
> [01/Mar/2016 08:33:13] "POST /api/v1/projects HTTP/1.0" 401 124
>

**Comment by superalex** [comment]
`But not sure why its happening. I have replaces my external hostname in load.py file under settings folder of taiga-back folder.`

You shouldn't be doing that...could you leave it in the original version and update the conf.json file for taiga-front with the right url API?

**Comment by superalex** [comment]
Could you please show us your local.py file and your conf.json one?

Regards!,

**Comment by ddonindia** [comment]
load.py:

> from .common import *
> 
> MEDIA_URL = "http://myhostname/media/"
> STATIC_URL = "http://myhostname/static/"
> ADMIN_MEDIA_PREFIX = "http://myhostname/static/admin/"
> SITES["front"]["scheme"] = "http"
> SITES["front"]["domain"] = "myhostname"
> 
> SECRET_KEY = "somekey"
> 
> DEBUG = False
> TEMPLATE_DEBUG = False
> PUBLIC_REGISTER_ENABLED = True

conf.json:

> 
> {
>     "api": "http://myhostname/api/v1/",
>         "eventsUrl": "ws://myhostname/events",
>         "debug": "true",
>         "publicRegisterEnabled": false,
>         "feedbackEnabled": true,
>         "privacyPolicyUrl": null,
>         "termsOfServiceUrl": null,
>         "maxUploadFileSize": null,
>         "contribPlugins": []
> }
> 
>

**Comment by superalex** [comment]
Everything seems to be ok, could it be some kind of proxy/plugin in your browser doing something with the authentication headers?

**Comment by ddonindia** [comment]
I am using .htaccess in nginx to have two level authentication can that cause some issue ?
I will try to disable it and check.

**Comment by superalex** [comment]
Yes, I think it could be the reason

**Comment by ddonindia** [comment]
Thanks @superalex I got it working after removing .htaccess file but I think this should be fixed in Taiga so that it can work with .htaccess
Thanks again for your help .

**Comment by superalex** [comment]
You are welcome! ;)

**Comment by ChrisNowa** [comment]
I have the same problem with the redirecting error page like @ddonindia could you send me your site enabled config? in the directory /etc/ngingx/sites-available I got only the taiga file. Do you updated that?
