### ISSUE TITLE
How to open taiga-front 

### ISSUE THREAD

**Issue by vinay90** [taigaio/taiga-front#900]
I was new with taiga. I was installed taiga by using the following steps 
http://taigaio.github.io/taiga-doc/dist/setup-production.html

what are the next steps to access and work with taiga

**Comment by superalex** [comment]
That document assumes you are using "example.com" to make all the configuration so if you can resolve that domain properly it should work. Could you show us your local.py and conf.json files?

**Comment by vinay90** [comment]
Thanks for the response this are the files local.py and conf.json
conf.json
----------
{
    "api": "http://example.com/api/v1/",
    "eventsUrl": "ws://example.com/events",
    "debug": "true",
    "publicRegisterEnabled": true,
    "feedbackEnabled": true,
    "privacyPolicyUrl": null,
    "termsOfServiceUrl": null,
    "maxUploadFileSize": null,
    "contribPlugins": []
}
-------------------------------------------------
local.py
-------------
from .common import *

MEDIA_URL = "http://example.com/media/"
STATIC_URL = "http://example.com/static/"
ADMIN_MEDIA_PREFIX = "http://example.com/static/admin/"
SITES["front"]["scheme"] = "http"
SITES["front"]["domain"] = "example.com"

SECRET_KEY = "theveryultratopsecretkey"

DEBUG = False
TEMPLATE_DEBUG = False
PUBLIC_REGISTER_ENABLED = True

DEFAULT_FROM_EMAIL = "no-reply@example.com"
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Uncomment and populate with proper connection parameters
# for enable email sending. EMAIL_HOST_USER should end by @domain.tld
#EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
#EMAIL_USE_TLS = False
#EMAIL_HOST = "localhost"
#EMAIL_HOST_USER = ""
#EMAIL_HOST_PASSWORD = ""
#EMAIL_PORT = 25

# Uncomment and populate with proper connection parameters
# for enable github login/singin.
#GITHUB_API_CLIENT_ID = "yourgithubclientid"
#GITHUB_API_CLIENT_SECRET = "yourgithubclientsecret"

**Comment by superalex** [comment]
If it's configured that way you should access example.com but you must ensure your system resolvs properly that domain to the right url (probably updating your /etc/hosts file).

Regards,

**Comment by ddonindia** [comment]
I think to test your setup you can replace example.com with your IP address and restart taiga-back and webserver.
If you are using nginx also make sure /etc/nginx/sites-available/taiga config file have correct IP/host name in proxy_pass config parameter.

**Comment by superalex** [comment]
Thanks @ddonindia that's another option too :+1:

**Comment by vinay90** [comment]
Thanks a lot for giving support. Still i have some issues related to front end display. The time line didn't show any notifications, please see the attached screenshot
![screenshot from 2016-03-03 19 23 47](https://cloud.githubusercontent.com/assets/17563558/13496447/3f89250a-e176-11e5-8553-b9e02f866639.png)

**Comment by ddonindia** [comment]
@vinay90  do you see any errors in network tab of inspect element?
Mostly this this kind of issue comes when frontend is not able to connect to backend you should see such errors in network tab.

**Comment by vinay90** [comment]
I didn't see any errors in network tab. For default projects it is showing the time line but our own created projects it is showing like that.
![screenshot from 2016-03-04 11 53 18](https://cloud.githubusercontent.com/assets/17563558/13519759/7de0a0dc-e200-11e5-8f86-98e7f784450f.png)

**Comment by vinay90** [comment]
In console it is showing error like this
WebSocket connection to 'ws://localhost/events' failed: Error during WebSocket handshake: Unexpected response code: 200

**Comment by superalex** [comment]
@vinay90 if you configured your taiga instance to work in asynchronous mode the timelines are filled in that way (not the sample data). So probably you are having some kind of problem with celery. Could you check your ~/logs/celery* files and your celery/rabbitmq configurations?

**Comment by vinay90** [comment]
Thank you issue resolved, i removed Async tasks configuration in my files.

**Comment by superalex** [comment]
Great!

**Comment by ddonindia** [comment]
:+1:
