### ISSUE TITLE
Enable and Disable Admin

### ISSUE THREAD

**Issue by adebayo-dealdey** [taigaio/taiga-front#906]
On Adding Member, you can enable and disable yourself from been an admin even when there isn't any other administrator. This feature might make admin lose itself.

**Comment by superalex** [comment]
Hello @adebayo-dealdey right now it shouldn't be happening, you only can remove yourself from been an admin only if there is at least another one. How did you reproduce it? (I'm testing the stable branch on tree.taiga.io).

**Comment by adebayo-dealdey** [comment]
I can't recreate issue because of this issue https://github.com/taigaio/taiga-front/issues/908
