### ISSUE TITLE
Adding Custom Fields as Filters for Issues

### ISSUE THREAD

**Issue by zappe-roman** [taigaio/taiga-front#907]
Option should be provided to add custom fields as filters.It will help to better filter out the issues.

**Comment by superalex** [comment]
Hello @zappe-roman ,

We had an existing enhancement request for this feature (https://tree.taiga.io/project/taiga/issue/3734), I've just added your comments there. Remember that you can upvote this issues in Taiga to raise its importance.

Regards!,
