### ISSUE TITLE
Project Setting Link Lost

### ISSUE THREAD

**Issue by adebayo-dealdey** [taigaio/taiga-front#908]
The project settings link isn't available anymore when testing with the master branch, is it an advancement or something else? I am the administrator on my localhost and it seems i have lost access to my project settings link.

**Comment by superalex** [comment]
Hello @adebayo-dealdey I'm using the master branch and I can see the admin link properly, could you attach a screenshot please?

**Comment by adebayo-dealdey** [comment]
I think it has to do with 'taigaio/refactor/is_owner_to_is_admin' it is telling me permission denied when i type the url directly. I will attach the screenshot soonest.

**Comment by superalex** [comment]
Just one comment, are you using the same branch in both taiga-front and taiga-master, isn't it?

**Comment by adebayo-dealdey** [comment]
![internet_005](https://cloud.githubusercontent.com/assets/16304032/13566831/e029332c-e457-11e5-865d-2901dbe750a6.png)

**Comment by adebayo-dealdey** [comment]
NO, I ain't using the same branch, switching my taiga-front to stable branch returns an empty page even after performing a gulp deploy. I resolved into using the master branch before sorting out the issue with the stable branch. I can do well with a head-up on where to look and peep. Thanks.

**Comment by superalex** [comment]
If not using the same branches it's not possible that it works properly :(

Regards!,
