### ISSUE TITLE
Events not working in front end

### ISSUE THREAD

**Issue by siliconalchemy** [taigaio/taiga-front#909]
I've configured the backend for asynch and events which seems to be working, in that I can see messages flowing through MQ, eg if I create a task:

2016-03-07 9:41:57: Message published
Node:         rabbit@xxx
Exchange:     events
Routing keys: [<<"changes.project.4.tasks">>]
Properties:   [{<<"content_encoding">>,longstr,<<"UTF-8">>}]
Payload: 
{"session_id": "xxx", "data": {"type": "create", "pk": 137, "matches": "tasks.task"}}

In the frontend (browser) console, I see no js errors.  If I navigate to the relevant project page (timeline by default) I see:
Subscribe to: notifications
angular.js:12477 WebSocket connection opened

I see lots of these:
angular.js:12477 HeartBeat send PING
angular.js:12477 WebSocket message received: {"cmd":"pong"}
angular.js:12477 HeartBeat recived PONG

But if I create a new task for example in another browser window, I get nothing in the original browser console.  I can't see any updates at all in any browsers, and no errors.

**Comment by superalex** [comment]
Hello @siliconalchemy 

What screen are you using in the other browser?, taiga-events should refresh changes in taskboard, kanban and backlog views.

**Comment by siliconalchemy** [comment]
I've tried the timeline, taskboard, kanban and backlog views.  I can see the subscribe to messages and don't get any errors in the browser console, but I don't see any realtime updates at all, no sign of any updates in the browser or console.

**Comment by superalex** [comment]
I'm testing on tree.taiga.io and it seems to be working ok...could you try if it also happens in our instance? (it's just running the last stable release).

**Comment by siliconalchemy** [comment]
Not sure how to test in your instance, I'll see if this comment comes through.

Messages are clearly coming through the backend into the queue but the queue seems to be empty so they must be consumed somewhere.  Is there a way of debugging or tracing in the front end to see what events are received?

**Comment by juanfran** [comment]
the source code in front is something like this

```js
var onMessage = function(event) {
        console.log("WebSocket message received: " + event.data)
        // more code
};

var ws = new WebSocket(url);
var ws.addEventListener("message", onMessage);
```
so if you see the "pong" the connection is ok but taiga-back is not sending the content

**Comment by siliconalchemy** [comment]
OK great thanks.  So taiga-back is just responsible for putting the messages into the MQ queue, is that right?  So if the messages are getting into the queue (which it looks like they are from the MQ trace) then the problem is likely with the taiga events coffee script, or how the browser talks to the socket?

**Comment by juanfran** [comment]
yes, taiga-back is the responsible for putting the messages, and taiga-events is responsible to pick them from the queue and send them to the browser. I guess you've changed the conf.json, I believe that a wrong url or secret could cause this (taiga-events has a lack of logs)

**Comment by siliconalchemy** [comment]
OK I went back over all the setup docs and redid a few configs and I now get updates in the backlog page and the corresponding 'websocket message received', which is great.  I should have made a backup of before and after, as I can't actually see what change would have made any difference.

Events are quite confusing as they only work in part of the overall interface, and don't work in others.  I'll raise issues as enhancement requests for the 'missing' pages.

Taiga-events could definitely improve logging, I have a separate issue open for that.  Thanks for your help :)

**Comment by saikirubamj** [comment]
how taiga-events works ????

**Comment by johnlund** [comment]
Thanks @jeffhoye saved me lots of time trying to debug that. Maybe someone could add that to the install doc? :)

**Comment by migonzalvar** [comment]
Now documented in https://taigaio.github.io/taiga-doc/dist/setup-production.html#_configuring_dependencies

> As the password will be used inside an URL later, please use only web safe characters: a-z, A-Z, 0-9, and - . _ ~
