### ISSUE TITLE
Small glitch on Chrome

### ISSUE THREAD

**Issue by juanstiza** [taigaio/taiga-front#910]
The tasks colouring (due to tags i guess) has a higher z-index than the menu tooltip, check the picture. Anyway, this is a really dumb bug. Keep it up, great work guys!

![image](https://cloud.githubusercontent.com/assets/5667982/13571002/a7d76a4a-e450-11e5-90dd-6bfb2e4ece08.png)

**Comment by superalex** [comment]
Thanks for reporting @juanstiza

**Comment by Xaviju** [comment]
Thanks for the catch. Should be fixed now: https://github.com/taigaio/taiga-front/commit/ba67b91beb22fe32417d89e1e538c09b68d216c7
