### ISSUE TITLE
Comment markdown preview repeating itself on multiple clicks

### ISSUE THREAD

**Issue by juanstiza** [taigaio/taiga-front#912]
Hi guys, I found another bug.

When writing a comment on a task, and previewing it, if I click the preview button many times (I can be impatient and we have a very slow connection here) it will load the preview that many times afterwards:

![screen shot 2016-03-09 at 12 07 54](https://cloud.githubusercontent.com/assets/5667982/13639543/fc606ada-e5ef-11e5-8017-d5e349c99410.png)

**Comment by juanfran** [comment]
I can't see the error in production, are you using your own instance? which browser are you using? 

thanks

**Comment by juanstiza** [comment]
We are not using our own instance. I'm using Chrome 48.0.2564.116 (64 bit) on Mac OSX 10.11.3.

**Comment by juanstiza** [comment]
Here is an ugly gif showing it. I wrote "lalala", then clicked the preview button a bunch of times, three preview boxes appeared. ![test](https://cloud.githubusercontent.com/assets/5667982/13743415/4c738466-e9c0-11e5-868c-a9013f00c188.gif)

**Comment by juanfran** [comment]
thanks @juanstiza 

we've found the bugs, it's already fixed in the master branch and it will be in production in the next release

**Comment by juanstiza** [comment]
Glad to help!
