### ISSUE TITLE
Events need adding to Issue Details page

### ISSUE THREAD

**Issue by siliconalchemy** [taigaio/taiga-front#914]
There seems to be no events/realtime updates to the Issue Details page, so no updates to these pages get broadcast to other team members. It should work as per the issues index page where all updates to the page are broadcast to other browsers through events/websockets.

**Comment by superalex** [comment]
I've included the issue details updates here -> https://github.com/taigaio/taiga-front/issues/913 I think it should be implemented at the same time ;)

Regards!,
