### ISSUE TITLE
Fix touch support on Edge for the scrum/kanban boards

### ISSUE THREAD

**Issue by phgmhendrix** [taigaio/taiga-front#916]
We are using Taiga quite heavily. On Chrome it works like a charm to move stuff around the board from a touch screen, however on the Windows 10 Edge browser it does not.

**Comment by lekoaf** [comment]
Edge uses different touch events. IIRC Instead of touchstart, touchmove and touchend they use pointerdown, pointermove and pointerup. Because why conform to the web standard?

**Comment by FreeMinded** [comment]
On Firefox Mobile it's also quite difficult to use the boards without accidentally moving around tasks or US. Would be great if it would just work. :)
