### ISSUE TITLE
Not receiving notifications 

### ISSUE THREAD

**Issue by drik** [taigaio/taiga-front#917]
A member of my team is not receiving notifications by mail about activities concerning the project allthough he choose to receive all notifications in his params.

**Comment by superalex** [comment]
Hello @drik 

Is this happening in your own instance?, if that's the point?, did you check your email server logs to see is the emails are leaving the machine?.

Regards,

**Comment by drik** [comment]
@superalex 
This is happening on the central instance http://tree.taiga.io

**Comment by superalex** [comment]
Could you write to support@taiga.io indicating the user and the project so we can check what's happening?

Regards!,
