### ISSUE TITLE
Angular Translate expression appearing in Related Task field

### ISSUE THREAD

**Issue by DevLab2425** [taigaio/taiga-front#921]
As seen in the attached screenshot, the new task field initially appears with the Angular Translate expression is appearing as the placeholder text for the field. 

<img width="974" alt="screen shot 2016-03-15 at 8 46 35 pm" src="https://cloud.githubusercontent.com/assets/8385375/13798690/429092b0-eaef-11e5-99c7-59d203a61639.png">

**Comment by superalex** [comment]
Hello @DevLab2425 

I'm checking tree.taiga.io (with the last stable release) and I can't reproduce the issue, is this happening in your own instance?

**Comment by superalex** [comment]
Hello @DevLab2425 could you check this one?

**Comment by paul-barry-kenzan** [comment]
Hi @superalex 
Sorry for the delay. I'm seeing this on the live, public-facing site. Here are the steps to reproduce:

1. Login 
1. Select a project
1. Select a US
1. Click the + button next to the Related Tasks heading

App will scroll to the inline form and display the placeholder text visible in the original screenshot.

**Comment by superalex** [comment]
Hello @paul-barry-kenzan 

I can't reproduce the issue, could it be a cache problem from your browser?. 

Just a few more questions:
 - What browser/version are you using?
 - Could you check if there are any javascript errors in your browser console?
 - What language are you using in Taiga?

Regards!,

**Comment by paul-barry-kenzan** [comment]
@superalex 

> What browser/version are you using?

Chrome 50.0.2661.86 (64-bit)

> Could you check if there are any javascript errors in your browser console?

No errors, just `.info()` statements. 

> What language are you using in Taiga?

English

Also discovered that it seems to happen more frequently with a US that contains a large number of related tasks. US without tasks don't behave the same. Additionally, when my console is open, I see a quick flicker of the incorrect placeholder, which then updates to display the appropriate text.

**Comment by superalex** [comment]
Thank you very much @paul-barry-kenzan @juanfran has detected some code that needs refactoring on that part that can be related this issue.

**Comment by juanfran** [comment]
thanks @paul-barry-kenzan 

we can't reproduce the issue but we've seen a lot of code that needs a refactor, we've done it, so I think in the next release this issue will disappear.

**Comment by paul-barry-kenzan** [comment]
@juanfran @superalex 
No problem guys! Keep up the great work over there. Great little Angular app you've got going. Sad to see the free projects disappear though.

**Comment by superalex** [comment]
Thanks!,

They don't disappear!, if you are talking about the new subscription system...free projects don't disappear, you will still can have as many public projects as you want for free ;)

Regards!,
