### ISSUE TITLE
Add a small issue filter in the kanban column

### ISSUE THREAD

**Issue by david-caro** [taigaio/taiga-front#924]
A small text box to filter user stories by will help a lot when there are many user stories, now you have to use the browser search feature or scroll and search yourself

**Comment by superalex** [comment]
Hello @david-caro 

We had a user story (in progress) to support this in Taiga -> https://tree.taiga.io/project/taiga/us/1775

I'm closing the github issue and leaving the taiga one open.

Regards!,
