### ISSUE TITLE
webhooks become deadhooks

### ISSUE THREAD

**Issue by lgrkvst** [taigaio/taiga-front#929]
Hi,

I just came across Taiga in search for a collaboration tool with community thinking. So far I'm really impressed and I can't wait to dive back in.

I did found a bug however, when trying to create a webhook towards https://actor.im/:

1. So I copy __the hook url from actor.im__
1. I go to __Taiga__, Integrations->Webhooks->__Add a new webhook__
1. I type a __name__, like "test", paste the __payload url__ and enter a dummy __key__ (actor.im doesn't require a key, but Taiga demanded one so...)
1. I click the (rather outdated) __Save__ icon
1. I get out of edit mode, however the newly created webhook turns up as static text, kinda dead, no icons, no edit options, just a black name and a grey url.

The linked support page lists three icons that should turn up at the far left side of each webhook. I don't see those.

Oh, also, upon clicking __Add a new webhook__, I'm unable to cancel it (hitting the grey cross doesn't do anything).

Anyway, thanks for a great product so far! I'm looking forward to following Taiga's road ahead.

**Comment by lgrkvst** [comment]
Just noticed in the console.

`WebSocket connection to 'wss://api.taiga.io/events' failed: Error during WebSocket handshake: Unexpected response code: 502`

**Comment by bameda** [comment]
Hi lgrkvst

> I get out of edit mode, however the newly created webhook turns up as static text, kinda dead, no icons, no edit options, just a black name and a grey url.

you see the icons if you do hover over the weebhok

![image](https://cloud.githubusercontent.com/assets/877218/13917903/202d4988-ef64-11e5-8d90-d35c07783354.png)

![image](https://cloud.githubusercontent.com/assets/877218/13917921/3a2879b6-ef64-11e5-98b0-31496f2b4f67.png)

> Oh, also, upon clicking Add a new webhook, I'm unable to cancel it (hitting the grey cross doesn't do anything).

This is a bug: thanks for report it. https://tree.taiga.io/project/taiga/issue/3997

**Comment by bameda** [comment]
Fixed at https://github.com/taigaio/taiga-front/commit/b6f3a7fe6d9a4c3669d35fa24ec9543d48cf460e
