### ISSUE TITLE
Issue creation notification does not properly escape HTML

### ISSUE THREAD

**Issue by Tagini** [taigaio/taiga-front#930]
![schermafbeelding 2016-03-21 om 10 28 36](https://cloud.githubusercontent.com/assets/3264941/13914711/7afcd590-ef50-11e5-8381-7f2fe0b8e5e2.png)

**Comment by bameda** [comment]
Thanks for report this.

https://tree.taiga.io/project/taiga/issue/3995

**Comment by bameda** [comment]
Fixed at https://github.com/taigaio/taiga-back/pull/678. Thanks @Tagini
