### ISSUE TITLE
Not able to scroll on New user story dialog

### ISSUE THREAD

**Issue by juanstiza** [taigaio/taiga-front#934]
When creating a new user story and filling the description field with a lot of data (stretching the *textarea* down), the *create* button disappears bellow the bottom of the screen. I have to shrink the *textarea* again so I can click it.
Perhaps a small detail... but detail at least.

**Comment by superalex** [comment]
Hello!,

We had an existing enhancement request for this feature (https://tree.taiga.io/project/taiga/issue/4018), I've just added your comments there. Remember that you can upvote this issue in Taiga to raise its importance. I'm closing this one (in github) and leaving the Taiga one open

Regards!,
