### ISSUE TITLE
Mixed content error when proxying over SSL

### ISSUE THREAD

**Issue by mroe1234** [taigaio/taiga-front#938]
I am using nginx to proxy over SSL here are my configs.  When trying to login I get the following error in my console:

Mixed Content: The page at 'https://kanban.foo.bar/login' was loaded over HTTPS, 
but requested an insecure XMLHttpRequest endpoint 'http://localhost:8000/api/v1/auth'. 
This request has been blocked; the content must be served over HTTPS.

====conf.json====

{
    "api": "https://kanban.foo.bar/api/v1/",
    "eventsUrl": "wss://kanban.foo.bar/events",
    "eventsMaxMissedHeartbeats": 5,
    "eventsHeartbeatIntervalTime": 60000,
    "debug": true,
    "debugInfo": false,
    "defaultLanguage": "en",
    "themes": ["taiga"],
    "defaultTheme": "taiga",
    "publicRegisterEnabled": true,
    "feedbackEnabled": true,
    "privacyPolicyUrl": null,
    "termsOfServiceUrl": null,
    "maxUploadFileSize": null,
    "contribPlugins": []
    "loginFormType": "ldap"
}

====local.py====

from .development import *
DATABASES = {
    'default': {
        'ENGINE': 'transaction_hooks.backends.postgresql_psycopg2',
        'NAME': 'taiga',
        'USER': 'taiga',
        'PASSWORD': '---------',
        'HOST': '',
        'PORT': '',
    }
}
MEDIA_URL = "https://kanban.foo.bar/media/"
STATIC_URL = "https://kanban.foo.bar/static/"
ADMIN_MEDIA_PREFIX = "https://kanban.foo.bar/static/admin/"
SITES["front"]["scheme"] = "https"
SITES["front"]["domain"] = "kanban.foo.bar"
SECRET_KEY = "---------"
DEBUG = False
TEMPLATE_DEBUG = False
PUBLIC_REGISTER_ENABLED = True
DEFAULT_FROM_EMAIL = "kanban@foo.bar"

====nginx site====

server {
    listen 443 ssl default_server;
    server_name _;
    large_client_header_buffers 4 32k;
    client_max_body_size 50M;
    charset utf-8;
    index index.html;
    # Frontend
    location / {
        root /home/taiga/taiga-front-dist/dist/;
        try_files $uri $uri/ /index.html;
    }
    # Backend
    location /api {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://localhost:8001/api;
        proxy_redirect off;
    }
    location /admin {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://localhost:8001$request_uri;
        proxy_redirect off;
    }
    # Static files
    location /static {
        alias /home/taiga/taiga-back/static;
    }
    # Media files
    location /media {
        alias /home/taiga/taiga-back/media;
    }
    ssl on;
    ssl_session_timeout 5m;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;
    ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK';
    ssl_session_cache shared:SSL:10m;
    ssl_stapling on;
    ssl_stapling_verify on;

**Comment by mroe1234** [comment]
So it seems that there was a missing comma in my conf.json which didn't log an error anywhere, but instead ignored that file entirely and was reverting to the settings in app-loader.js.  Perhaps there is a way to communicate when there is an error in the config file?

**Comment by superalex** [comment]
Hello @mroe1234 

I've done this pull request so it shows an error in the browser console if the conf.json file is invalid, I hope it can be merged to stable soon :)

Regards!,
