### ISSUE TITLE
Can't visualize more than 15 CUSTOM FIELDS

### ISSUE THREAD

**Issue by fchavarri** [taigaio/taiga-front#939]
Hi, I have installed Taiga.io on my server. I am testing it and you guys did a great great job!, I am still looking for bugs for help, and I found that, in the CUSTOM FIELDs you just can view at most 15 fields, but you can create a lot more. So if you can check it out will be awesome!

Nice nice work!!

**Comment by bameda** [comment]
Can you attach an screenshot?? I don't know where this happen
