### ISSUE TITLE
A way to group projects, or create sub project lanes in a project

### ISSUE THREAD

**Issue by elpddev** [taigaio/taiga-front#941]
Is there an existing way to group projects together ? Or to create lanes in the kanban view 
to separate stories by sub projects ?

**Comment by superalex** [comment]
Hello @elpddev 

Right now we don't support that features but we have different user stories related to this topics that will be implemented in the future:

- https://tree.taiga.io/project/taiga/us/1564 (related projects)
- https://tree.taiga.io/project/taiga/us/58 (relationships)
- https://tree.taiga.io/project/taiga/us/2129 (organizations)
- https://tree.taiga.io/project/taiga/us/1723 (swimlanes)

Regards!,

**Comment by opensas** [comment]
any update on this? has it been implemented? or at least some workaround to emulate it?

**Comment by han911976** [comment]
cascade project seems fun

It would be useful when there are several project leaders with a big boss who would like to have a kanban (eg) to monitor each projects while each project leaders could monitor their project deeply with their team members.

hope to see it soon !

**Comment by cleitonpena** [comment]
Hello!
Please!
Any update about project groups or sub projects in Taiga?

**Comment by erick-jeronimo** [comment]
Hi! Is already possible to create project groups or subprojects ?
