### ISSUE TITLE
Allow permissions to be copied to ease permissions setup

### ISSUE THREAD

**Issue by Indiefreaks** [taigaio/taiga-front#942]
I just went through the setup of a project requiring some custom permissions for some new roles and I would have loved to actually be able to setup a common default permission set and then copy it over the other ones so that I can avoid going through each module permissions...

**Comment by superalex** [comment]
Hello @Indiefreaks 

We had an existing enhancement request for this one: https://tree.taiga.io/project/taiga/issue/3034, I've just copied your comments there. 

Thank you very much for the feedback.

Regards!,
