### ISSUE TITLE
Attached images are not previwed in Issues

### ISSUE THREAD

**Issue by jgomo3** [taigaio/taiga-front#943]
An Issue lets you attach files. If it is an image, it would be nice to see a thumbnail of it. Trello and Bitbucket issues do it.

Check an example of the same issue in Taiga, Bitbucket and Trello:

## This is Taiga

![selection_011](https://cloud.githubusercontent.com/assets/1125678/14324573/25b23a2a-fbef-11e5-98be-3a23905c5e2c.png)

## This is Bitbucket:

![selection_010](https://cloud.githubusercontent.com/assets/1125678/14324574/25b30aae-fbef-11e5-885d-e30ef2e99d71.png)

## This is Trello:

![selection_009](https://cloud.githubusercontent.com/assets/1125678/14324575/25ba133a-fbef-11e5-8e77-d641215cdb01.png)

**Comment by bameda** [comment]
You can enable the thumbnail view

![image](https://cloud.githubusercontent.com/assets/877218/14324933/541aa658-fc27-11e5-8d12-7fc1e83c4cd7.png)

**Comment by jgomo3** [comment]
Wow!!! Super timing! Thank you!

**Comment by bameda** [comment]
You are welcome :-) :dancer: :dancer:
