### ISSUE TITLE
taiga's keyboard shortcut kills Mac's keybard shortcuts

### ISSUE THREAD

**Issue by natsumesou** [taigaio/taiga-front#945]
hello
I always use keyboard shortcuts when I type some texts.
And I often use Control-B to move one character backward.
But taiga's keyboard shortcut overwrite it and then it shows unknown text as below

```
**Your text here...**
```

So it's too annoying for me.
Is there any solution for this problem?
Any plans for fix this shortcut? or can I send pull request for this one?

thank you for your great project.

**Comment by Xaviju** [comment]
Ctrl + B is a standard shortcut for bold while editing text. Is it a standard Mac command?
I've seen here that its the same in mac: https://support.apple.com/en-us/HT201236

**Comment by natsumesou** [comment]
wait...plz wait.
I know that shortcuts.
But that is Command+B
It's Control+B.
and check that Control+B description. https://support.apple.com/en-us/HT201236

You can check this valid keyboard shortcuts on google documents. https://docs.google.com

please rethink this binding.

**Comment by Xaviju** [comment]
You're right @natsumesou is CMD+B, sorry for the misunderstanding, we are not Apple users.
In any case, the Ctrl + B for bold is a standard everywhere excepting Mac computers. We cannot change the general behavior or detect if you are pressing this button only in a Mac.

Do you have any suggestion?

**Comment by natsumesou** [comment]
I think keyboard shortcut script should be separated for windows and for mac.
then detect mac or windows by User-Agent, and change script tag like `<script src="shortcut_for_mac.js">` by server side code.

**Comment by Xaviju** [comment]
This seems a major change in our code for a case that (to me) seems like an Apple anti-standard bug. I'll open it to see other user opinions or PR's.  

Thanks @natsumesou

**Comment by natsumesou** [comment]
how about this issue?
I feel fear about using shortcuts on taiga pages...

**Comment by Xaviju** [comment]
Sorry @natsumesou we did not received any more feedback nor PRs for this issue, except yours. We are focused on other areas. 

- You can see our roadmap here: https://tree.taiga.io/project/taiga/kanban
- You can upvote this issue here: https://tree.taiga.io/project/taiga/issue/4067

We should receive more feedback about this to be part of our priorities.

**Comment by saulshanabrook** [comment]
I have a problem with the `CMD-<number>` keyboard shortcuts on a mac. These set heading levels, and I am used to using these to switch tabs on Chrome. 

Is it possible to disable these per user?

I have those keystrokes built into my muscle memory and the only webpage where they don't work is Taiga's text editor (that I have found).

**Comment by kwmiebach** [comment]
Many developers use a mac. It would be nice to allow different keyboard shortcuts. One for linux/windows and one for mac.

A lot of gui programs have separate shortcuts for their mac versions. I don't know about browser based solutions.

Yes they have some different keyboard standards that seem odd for linux/windows users.
