### ISSUE TITLE
Cannot delete wiki page in 2.0

### ISSUE THREAD

**Issue by krpec** [taigaio/taiga-front#947]
When I wanted to delete wiki page by clicking on the trash icon in the wiki page list, nothing happened. Clicking on the delete link in the page detail deletes only its content, the page remains in the list.

**Comment by bameda** [comment]
Yes, this is because wiki page and wiki links are different items. You can have wiki pages without wiki links and wiki links without wiki pages.

**Comment by krpec** [comment]
@bameda yes, I understand this. The thing is when I want to delete wiki link from the list by clicking on the trash icon, nothing happens.

**Comment by bameda** [comment]
for example, if yo write in a wiki page 

```markdown
[new wiki page without a wiki link](new-wiki-page) 
```

you generate a new wiki page too

**Comment by bameda** [comment]
ok, so this could be the bug. I'll try to solve right now
