### ISSUE TITLE
wiki pages cannot be opened in new window

### ISSUE THREAD

**Issue by fuzzy76** [taigaio/taiga-front#948]
The list of wiki pages are not real links. So I cannot right-click on them and copy the links or open them in new windows/tabs. ctrl/command-click does not work either.

**Comment by Xaviju** [comment]
This is a bug that we are fixing right now. Will be fixed soon.

Thanks for reporting!

**Comment by bameda** [comment]
Fixed in https://github.com/taigaio/taiga-front/pull/957
