### ISSUE TITLE
PHP Syntax Highlighting

### ISSUE THREAD

**Issue by ameenross** [taigaio/taiga-front#95]
Markdown support generally works pretty well, and I like the syntax highlighting feature. However, in the case of PHP, you generally do not want have to start with the `<?php` opening tag. Without that, however, syntax highlighting for PHP doesn't currently work. I'd like to see that fixed.

**Comment by zwarag** [comment]
Any news on this issue?

**Comment by superalex** [comment]
It's still a pending one...
