### ISSUE TITLE
RTL markdown

### ISSUE THREAD

**Issue by sepehr** [taigaio/taiga-front#954]
That would be great if Taiga had RTL support for markdown, so that we could write wikis in RTL languages. Here's an implementation of RTL markdown:  

https://github.com/dariubs/rtlmd

**Comment by superalex** [comment]
Hello @sepehr 

I think this one is a duplicated from https://github.com/taigaio/taiga-front/issues/443 isn't it?.

Regards!,

**Comment by sepehr** [comment]
Thank you @superalex.

**Comment by superalex** [comment]
Sorry, you are right, the other one speaks about themes, not about wiki support. Reopening!

**Comment by sepehr** [comment]
Thank you @superalex.

**Comment by lordloh** [comment]
I wanted to have indented lists in the US description. I does not seem to work. Is there a different issue where this is addressed? Should I start one?

**Comment by juanfran** [comment]
@lordloh is this what you need? https://tree.taiga.io/support/misc/taiga-markdown-syntax/#you-can-nest-them

**Comment by lordloh** [comment]
Right. Sorry I figured it out. I was editing my comments in Atom and markdown preview. 
- item1
  - item11
- item2
works on atom, but not in taiga. Taiga seems to be particular about 2 spaces and * instead of -. It would be great if you guys could let taiga markdown be the same as github markdown, else, I can live with it.

**Comment by vaheeds** [comment]
recently I host taiga on my ubuntu machine, but when I change th language to Farsi, nothing happen to style of the page but only labels text change to Farsi. I see the rtl is working great on the hosted version at https://tree.taiga.io. what do I miss?
