### ISSUE TITLE
Taiga Front not starting

### ISSUE THREAD

**Issue by dan13373** [taigaio/taiga-front#955]
hi @all,

I am referring to the following issue I found:
https://github.com/taigaio/taiga-front/issues/367#issuecomment-208007488

I have tried the same as the issuer in the above stated topic and followed the instructions at: http://taigaio.github.io/taiga-doc/dist/setup-production.html#_final_steps

I did not complete SSL but I did all other steps in details and checked twice. The backend at /admin is working perfect and accessible. The frontend does not load. Also ports 8000. Eschein in the other topic mentioned production ports configuration. Which ports must be changed - and where :)?

Dan

**Comment by superalex** [comment]
Hello @dan13373 

If you are having problems configuring taiga I suggest you using an automated method, for example taiga-scripts (http://taigaio.github.io/taiga-doc/dist/setup-alternatives.html) and when it's working customizing the configuration if needed.

Regards,

**Comment by dan13373** [comment]
Hi @superalex ,

thanks for the tip. I tried that yesterday but somehow this was not successful.
Well it seems to be just the ports. Is there a doc page other den "setup-production.html" to check all settings/configuration?

I guess this would also help others..who are like me ,) and want to do a clean self-installation.

Best,
dan

**Comment by superalex** [comment]
If you are doing a clean self-installation in production mode the nginx server will only expose 80/443 ports, internally it will proxypass to the different applications served by circus.

You could do that installation in another host and then check the different parts from your deploy with the working one, right now there can be a lot of failing points so it's not easy to detect what can be happening with your instance.

Regards,

**Comment by dan13373** [comment]
Well ok.
Since I want to use/test taiga I will try to do the taiga-scripts again and will test to do a clean self-installation again.
Best,
Dan

**Comment by superalex** [comment]
Great!, let us know if you are having any errors with it.

Regards!,
