### ISSUE TITLE
Customize user story categories

### ISSUE THREAD

**Issue by onekiloparsec** [taigaio/taiga-front#958]
Hi. I have a suggestion of an enhancement. In the user stories, the categories are UX, Design, Front, Back. It would just very nice to be able to change these categories: add new ones, remove unused ones. 

Taiga is amazing, and we are using here in all our teams, which comprises also some hardware development, with mechanics and electronics. Hence "front" and "back", as well as "ux" doesn't always make too much sense.

I'd love to help, since I know some front dev, and Django in the back (if someone is willing to point me in the right direction). Thanks a lot!

**Comment by bameda** [comment]
This "categories" are roles and you can manage roles in Admin > Permissions

![image](https://cloud.githubusercontent.com/assets/877218/14495428/af09f39e-018f-11e6-9774-d67fad403ef6.png)

Thanks for your feedback


Regards

**Comment by onekiloparsec** [comment]
This answers perfectly to my needs, thanks a lot for taking the time to write it down! And sorry for not having found it myself... (I was pretty sure that something close was already existing, but couldn't find the right workflow).

**Comment by bameda** [comment]
Don't worry, "Permissions" is not a good name and "Roles & permissions" is too long. We have to find a more descriptive name for this section.

Thank you for using Taiga
