### ISSUE TITLE
Simple, WTF you want money for me using your OS project?

### ISSUE THREAD

**Issue by rob-bb** [taigaio/taiga-front#959]
I tried to reply bout he email address was a no reply address.. 

I installed this for my kids high school homework project, and now you want me to pay $228 a year for it.

see gmail response bellow

New message from Mail Delivery Subsystem  Show  Ignore

Skip to content
Using Gmail with screen readers
Rob
Search

Take me to Inbox
Gmail
COMPOSE
Labels
Inbox
Sent Mail
Circles
Great Ape
Rental
Schools
St Pauls
St Peters
WLUG
Work/Income
Cook St
Estimating NZ
Foster Maintain
HA
Placemakers NEU
More 
 
 
 
  More 
3 of 1,149  
 
Expand all Print all In new window
Important subscription notice from Taiga.io
Inbox
x 

Taiga.io noreply@taiga.io via mail148.suw14.mcdlv.net 
02:53 (5 hours ago)

to me 
View this email in your browser
 
Important subscription notice from Taiga.io
Dear Taiga user,

You are receiving this email because you are the Project Owner of 2 projects on Taiga.io, your free, open source, agile project management tool.

Between now and April 30th, Project Owners with more than 1 private project will need to subscribe to one of our paid plans. 

On Taiga.io pricing tiers are determined by the number of private projects and project members associated with your account. You are considered a Project Owner if you either created a project or you accepted that a project's ownership be transferred to you. Projects to which you belong, but don't own are not counted towards your plan.

Your recommended Plan
Based on the 2 projects on your account, we recommend that you subscribe to the Sprout Plan

Sprout Plan  $19/month
Up to 5 private projects
Unlimited public projects!
Up to 25 members per private project
To subscribe, click on the link below. You will be asked to enter a credit card, but no charges will be processed until May 1st. You can continue enjoying Taiga.io's service for free until then.

SUBSCRIBE TO YOUR RECOMMENDED PLAN
Continue using Taiga without plan
If you wish to continue using Taiga.io but do not wish to pay for the service, you have the following options:

Go to admin > Project Details for each project, and designate your projects as "public". Note that Public projects are listed in Taiga.io's discover section, can be accessed (read only) by anyone with access to the URL and are indexed by search engines. You are entitled to 1 private project under Taiga.io's free price tier.
Export projects that you do not use and then delete them. Please delete with care. Once a project is deleted it cannot be recovered! You can also use this option if you wish to downgrade plan. Taiga's pricing plans can be found here.
Please contact us at support@taiga.io if you have any questions. Please note that users who have not selected a subscription plan or taken the actions detailed above will not be able to access their private projects starting May 1st. Public projects remain unaffected.

Thank you for being part of the Taiga.io community!

Enrique Posner & Pablo Ruiz
co-founders & co-CEO's
on behalf of the entire Taiga.io team
Twitter
GitHub
Website
(ɔ) 2016, Taiga Agile, LLC
This mail is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.

Want to change how you receive these emails?
You can update your preferences or unsubscribe from this list

Rob <r.brown.bayliss@gmail.com>
08:22 (0 minutes ago)

to Taiga.io 
What the fuck?  What happened  to open source? I set up our personal server for my sons school CS project, now you say I need to pay for it?   It's his school homework WTF? Like WTF?  We make no money, he is at school.  Seriously, are you guys full of shit

Mail Delivery Subsystem <mailer-daemon@googlemail.com>
08:22 (0 minutes ago)

to me 
Delivery to the following recipient failed permanently:

     noreply@taiga.io

Technical details of permanent failure:
Google tried to deliver your message, but it was rejected by the server for the recipient domain taiga.io by spool.mail.gandi.net. [2001:4b98:c:521::6].

The error that the other server returned was:
550 5.1.1 <noreply@taiga.io>: Recipient address rejected: User unknown in virtual mailbox table

----- Original message -----

DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20120113;
        h=mime-version:in-reply-to:references:date:message-id:subject:from:to;
        bh=t7WJukmlIEdKyMKrbSsjceWqWy2lqzAGLIA5sdw5vCg=;
        b=BRJZz0ZBtmE8J6nj3GvGQc81lEKmnGC9L+4wJ7th6eq+y/UJHr4qdLvHzkH5ciUjYt
         +MMItN9dYBCtP8jJ9Mx0vlpks2EDfBG/2Kh61eo8xwQkBHI3BJbnAhPWSY154/HQqPat
         +u9Jufs7yZ8UPNZCdFQCF/iowYiboqqiW8dYFRl0bo7mpmGCLIcnH04skTwbZnSbXTAM
         r0shOUOG3IDi3yhMSihKGl2T9k94paHeFbbWLng0eqAzz16dpWAO1O6hsmVnjQ5/B9xf
         jx8Lx8CS1cs7H/GbTdhiTp54drGOlhOJ1UUFdSO0KdclhbGf3uHdh8Or8NT2Hy3QUoLI
         +AvQ==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20130820;
        h=x-gm-message-state:mime-version:in-reply-to:references:date
         :message-id:subject:from:to;
        bh=t7WJukmlIEdKyMKrbSsjceWqWy2lqzAGLIA5sdw5vCg=;
        b=jaIvZD3Ssax4G2g41YNIXOEed9y3+/5QgtbioJmoj2a8ZwsLEE4CUhDxdpgprJ1lko
         /X1mGx+J2ZonXH19Da1hOGY5z7CWGxXwGFvJ0SEMEERkhx5SzuS82wZkABid3C/w3TJo
         JzOMXb4YzyPcmprOdvqmzZm3qTeO5N/yko+3VpdWUWzA2kRxaaVmUcM7U+Ybrirc6vuZ
         QG01lMTMlE1Brm2TRlPRylmtxFqIQcUIaGtPJueoCWbQZivc/Dh8KCC/uIoDSld0oCIJ
         s76cFLCv3Hk7jXMDl2uA9O/MvVN6XCZ6skRyGd787JovFjVqyaM79vaVH9wJvk/aEHUq
         prdw==
X-Gm-Message-State: AOPr4FVK7khiK8svY9GHJ6mQiv+DXs0PWnp6WTQJjxuF1xMTVgevMmAolxPZCP8hkVZp5vsJTQZd6fpHrUsSwA==
MIME-Version: 1.0
X-Received: by 10.50.147.67 with SMTP id ti3mr12281584igb.48.1460578970025;
 Wed, 13 Apr 2016 13:22:50 -0700 (PDT)
Received: by 10.64.110.71 with HTTP; Wed, 13 Apr 2016 13:22:49 -0700 (PDT)
In-Reply-To: <d0381bdbd4e837df219d9c96a34f9773a12.20160413145251@mail148.suw14.mcdlv.net>
References: <d0381bdbd4e837df219d9c96a34f9773a12.20160413145251@mail148.suw14.mcdlv.net>
Date: Thu, 14 Apr 2016 08:22:49 +1200
Message-ID: <CAO07Ljv16xWwkmsrA_ZRfFvhKzKAkchq0Lds06JRPhb99Qtt+A@mail.gmail.com>
Subject: Re: Important subscription notice from Taiga.io
From: Rob <r.brown.bayliss@gmail.com>
To: "Taiga.io" <noreply@taiga.io>
Content-Type: multipart/alternative; boundary=089e0149503aacd0020530638ab9

What the fuck?  What happened  to open source? I set up our personal server
for my sons school CS project, now you say I need to pay for it?   It's his
school homework WTF? Like WTF?  We make no money, he is at school.
Seriously, are you guys full of shit

On 14 April 2016 at 02:53, Taiga.io <noreply@taiga.io> wrote:

> View this email in your browser
> <http://us9.campaign-archive2.com/?u=d0381bdbd4e837df219d9c96a&id=32b4579657&e=34f9773a12>
>
> <http://taiga.us9.list-manage.com/track/click?u=d0381bdbd4e837df219d9c96a&id=50805021fb&e=34f9773a12>
> Important subscription notice from Taiga.io
>
> Dear *Taiga user,*
>
> You are receiving this email because you are the Project Owner of
> 2 projects on Taiga.io, your free, open source, agile project management
> tool.
>
> *Between now and April 30th, Project Owners with more than 1 private
> project will need to subscribe to one of our paid plans. *
>
> On Taiga.io pricing tiers are determined by the number of private projects
> and project members associated with your account. You are considered a
> Project Owner if you either created a project or you accepted that a
> project's ownership be transferred to you. Projects to which you belong,
> but don't own are not counted towards your plan.
> Your recommended Plan
>
> Based on the 2 projects on your account, we recommend that you subscribe
> to the *Sprout** Plan*
>
> <http://taiga.us9.list-manage.com/track/click?u=d0381bdbd4e837df219d9c96a&id=2a92041df0&e=34f9773a12>
> Sprout Plan  $19/month
>
>    - Up to 5 private projects
>    - *Unlimited* public projects!
>    - Up to 25 members per private project
>
> To subscribe, click on the link below. You will be asked to enter a credit
> card, but no charges will be processed until May 1st. You can continue
> enjoying Taiga.io's service for free until then.
> SUBSCRIBE TO YOUR RECOMMENDED PLAN
> <http://taiga.us9.list-manage.com/track/click?u=d0381bdbd4e837df219d9c96a&id=7a45095cbc&e=34f9773a12>

----- Message truncated -----
	
Click here to Reply or Forward
7.51 GB (50%) of 15 GB used
Manage
Terms - Privacy
Last account activity: 0 minutes ago
Currently being used in 1 other location  Details

**Comment by yakky** [comment]
@rob-bb It seems only fair to pay the taiga team to user their bandwidth and hardware to run your projects on their servers
I you can still install taiga on your own server and it won't cost you a penny.

**Comment by rob-bb** [comment]
Ok. I do run it on my own server, so did I misunderstand the email?  Is it still free for me to run on our own server?

Why did I receive an email telling me it was going to cost me $20 a month if that is not the case?

**Comment by diacritica** [comment]
@rob-bb perhaps because you have a taiga.io user too and you own some projects there. The email says "You are receiving this email because you are the Project Owner of 2 projects on Taiga.io" so perhaps you might want to go to taiga.io and delete those projects or export them or make them public, etc if you don't want to pay for the taiga.io service.

**Comment by adebayo-dealdey** [comment]
@rob-bb I also received the same email and seeing someone who is calm enough to type in a url, navigate to issue page, calm enough to create an issue but not calm enough not to Cause is defective to me. I had had several issues with taiga and I have always talked to @superalex  who seems to be understanding enough to give reasonable responses to questions been asked or issues being raised. I am not here to raise this issue again but please, these guys have done tons of job to get here and they deserve applaud instead of insults, read your mail better next time. @yakky @diacritica thanks for giving that simple response.

**Comment by rob-bb** [comment]
Sure man, any one else want to jump on the beat up wagon, just be sure that you have never mis read or mis understood before throwing that first stone ok?

**Comment by diacritica** [comment]
Let's leave it here, thanks! :)
