### ISSUE TITLE
Rendering bug in Chrome (flashing cards)

### ISSUE THREAD

**Issue by GriffinSauce** [taigaio/taiga-front#960]
My colleague and I are experiencing a strange rendering bug. On mouseover some cards flash in and out, sometimes partly.

![taiga_bug](https://cloud.githubusercontent.com/assets/5630996/14598413/663c36e2-0552-11e6-968c-e2dd07584311.gif)

Happens on:
- Chrome 49.0.2623.112 (64 bit) on a Macbook Pro, El Capitan
- Chrome 50.0.2661.75 (32-bit) on a Surfacebook Pro

Does not happen on:
- Safari
- Edge browser

I've seen this type of bug before, it is most likely in Webkit and requires some CSS hack to fix.
Adding `transform: translateZ(0);` seems to fix it. Probably because it pushes those elements into a GPU rendering layer, but in my experience this bug can also just _seem_ fixed when you change something in the Chrome Inspector.

**Comment by Xaviju** [comment]
Weird!
Never seen that before. We are using Chromium on Linux and do not have that strange behavior. 

It happens all the time across the taskboard/kanban or just for this cards?
Do you know where to find this rendering bug in webkit the issues to gather more information?
Do the console is sending any error messages?

Is any other having this problems?

Thanks for reporting

**Comment by GriffinSauce** [comment]
It happens only for these cards. (at the bottom of the board)

I can't find a specific Chromium bug, this one might be related?
https://bugs.chromium.org/p/chromium/issues/detail?id=543324

No errors in the console, but I have noticed that it doesn't happen on my second screen (non-retina), but only on my Macbook's internal retina screen. The same goes for my colleagues Surfacebook, it flickers on the high res screen only. That's pretty strong proof that the problem lies in the rendering engine (which would also explain why translateZ forces a fix)

So far we've only seen it in our two cases.

**Comment by Xaviju** [comment]
Seems related. I'll try to reproduce it. 
I wouldn't like to add the translate hack if its not completely necessary.

Is your project public? Can you share the URL so we can see it?

Thanks for reporting

Someone else experiencing this?

**Comment by GriffinSauce** [comment]
Agreed, the hack is not beautiful. No sorry, our project is private.
