### ISSUE TITLE
Prevent 'ESC' from closing 'New Issue' editor if data entered. 

### ISSUE THREAD

**Issue by strayobject** [taigaio/taiga-front#964]
This is a feature request for the frontend.

It would be nice if once data is entered, i.e. Issue Subject or Description, hitting an `ESC` key did not automatically close the editor, but rather prompt before closing. This would prevent the accidental closure.

**Comment by superalex** [comment]
Thank you very much for your feedback @strayobject 

We had an existing enhancement request for this feature (https://tree.taiga.io/project/taiga/issue/3370), I've just added your comments there.

Regards!,

**Comment by strayobject** [comment]
Thank you, sorry about duplicating.
