### ISSUE TITLE
User isnt receiving Password Recover email

### ISSUE THREAD

**Issue by neomacedo** [taigaio/taiga-front#978]
I have one user on my project who have lost your passwd.. so hes trying to recorver it..

But when type your email on the recover page, its seems a message saying to check the email box for a password reset message. 

But he cant receive it.

Can i as admin to reset it for him?

**Comment by superalex** [comment]
Hello @neomacedo 

If you are a superuser from the platform you can do it using the django-admin interface (probably served in the /admin url). If you have access to the server you could also execute something like "python manage.py changepassword USERNAME"

Regards,
