### ISSUE TITLE
Not receiving project export email

### ISSUE THREAD

**Issue by danwalmsley** [taigaio/taiga-front#979]
I managed to export one of my projects,
but the second I never get the email.

**Comment by superalex** [comment]
Hello @danwalmsley,

Is this happening on your own instance or in tree.taiga.io?

**Comment by danwalmsley** [comment]
Hi, this is on tree.taiga.io, trying to move to our own instance.

**Comment by superalex** [comment]
Do you remember when did you generate the export aprox? (it's an asynchronous task that can take hours until finished, our queues are receiving a lot of export tasks these days)

**Comment by danwalmsley** [comment]
I kicked one off yester day, my project is  https://tree.taiga.io/project/danwalmsley-ultralaminator/

I tried several times.

**Comment by superalex** [comment]
We have tried too and everything workid ok (I've contacted you from my Taiga account to give you the exported project url), did you check your spam inbox?.

Regards!,

**Comment by danwalmsley** [comment]
@superalex many thanks for your help on this, I checked junk but nothing there.
