### ISSUE TITLE
CSV file import fails

### ISSUE THREAD

**Issue by paulomago** [taigaio/taiga-front#980]
When the description of user story has a line break, the exported CSV file import fails. 
Because line break create a new line in CSV file that doesn't respect import layout.

**Comment by superalex** [comment]
Hello @paulomago 

How are you trying to import this CSV files?, the format should be ok according to the CSV specification, libreoffice or google spreadsheets doesn't have problems with them...

**Comment by paulomago** [comment]
I'm using ms excel.
I tested the CSV file generated by CSV Lint.
Result: http://csvlint.io/validation/5720df486373767e2b000213

**Comment by superalex** [comment]
Hello @paulomago 

I think that example is a false positive about line breaking, there is an error saying "Your CSV appears to be encoded in ASCII-8BIT. We recommend you use UTF-8.", we encode the csv files exported by Taiga in utf-8, did you modify the file before testing it on csvlint?, could you test with an unmodified one?.

Regards,
