### ISSUE TITLE
[UI enhancements] Receive a special notification when I'm directly mentioned in a task/issue via @MyName

### ISSUE THREAD

**Issue by spottheplot** [taigaio/taiga-front#982]
In a project with lots of task updates, I usually miss those tasks where I'm mentioned directly. I'd really like being able to filter, or knowing where am I required at a glance.

**Comment by bameda** [comment]
Hi @spottheplot , you should select "Only involved"  in the Notificacion panel of your user profile

![image](https://cloud.githubusercontent.com/assets/877218/14862782/3f781a90-0cb3-11e6-872e-f1af3259839d.png)

or in the main panel of your project

![image](https://cloud.githubusercontent.com/assets/877218/14863038/5cf3de96-0cb4-11e6-8e91-d594680b0edc.png)


Regards
