### ISSUE TITLE
Add permission to allow external users to comment on any issue

### ISSUE THREAD

**Issue by tuxayo** [taigaio/taiga-front#991]
In the context of a project using Taiga as it's main issue tracker.

It would be very useful to allow external users to comment on any issue.

- So they can comment on their own issue
- So they can help to reproduce and provide more details about bugs
- So they can participate in the discussions on feature request
- So they can help other users who asked a question

If I understand correctly, this is not currently possible without allowing external user to **edit** any issue right?

**Comment by bameda** [comment]
We are working on it, I hope it can be ready for the next release of Taiga.

https://tree.taiga.io/project/taiga/us/2929?kanban-status=211691

**Comment by tuxayo** [comment]
Awesome, looking forward to it!
