### ISSUE TITLE
@mentions with dashes do not work

### ISSUE THREAD

**Issue by Juanlu001** [taigaio/taiga-front#993]
See:

https://tree.taiga.io/project/olea-pycones-2016/us/14?kanban-status=709091

(last comment, 04 May 2016 22:40)

**Comment by bameda** [comment]
Ummmmm, It seems a problem with the markdown parser and the dash symbol...

https://github.com/taigaio/taiga-back/blob/master/taiga/mdrender/extensions/mentions.py#L34

**Comment by bameda** [comment]
https://tree.taiga.io/project/taiga/issue/4151

ok, I'll fix it tomorrow morning

**Comment by Juanlu001** [comment]
Cool, thank you! :smile:

**Comment by bameda** [comment]
Fixed https://github.com/taigaio/taiga-back/commit/4516dbca492c1ba436c0033f3ecb5ed68b1fb7b1
