### ISSUE TITLE
"Change Plan" page comes all times

### ISSUE THREAD

**Issue by digiajay** [taigaio/taiga-front#996]
Hi,

I had 3 private projects which was blocked since this May start.  I can convert those projects into public to continue using it.  However, I'm NOT able to manage the projects.  Always I end-up with the "Change plan" page.  It's very urgent for us to access Taiga and our team got stuck due to this paid plan issue.  

Thanks,
Ajay

**Comment by superalex** [comment]
Hello @digiajay 

Please write to support@taiga.io indicating your username/email and your blocked projects.

Regards!,

**Comment by ahmednaguib** [comment]
I think this issue is valid. I have the same problem with my account as well.

**Comment by superalex** [comment]
@ahmednaguib it's not valid issue for two reasons:
 - It's not related to the taiga-front code
 - It's related to the service offered in tree.taiga.io

Please, contact support@taiga.io with the details about your user and projects. 

All the info about blocked projects can be found here: https://tree.taiga.io/support/subscription-and-plans/payment-process-faqs/
