### ISSUE TITLE
Error when upload files to wiki page

### ISSUE THREAD

**Issue by danielRomero** [taigaio/taiga-front#997]
Hello,

When I try to attach a file to new Wiki page, it throw this error on browser's console and file is not uploaded

<code>iterable.length has been deprecated, use iterable.size or iterable.count(). This warning will become a silent error in a future version. .get@https://tree.taiga.io/v-1462392000254/js/libs.js:22:17142
Pa@https://tree.taiga.io/v-1462392000254/js/libs.js:6:30456
Kn@https://tree.taiga.io/v-1462392000254/js/libs.js:6:7663
Yn/<@https://tree.taiga.io/v-1462392000254/js/libs.js:6:7437
i@https://tree.taiga.io/v-1462392000254/js/libs.js:5:28674
Yn@https://tree.taiga.io/v-1462392000254/js/libs.js:6:7377
W/lc<@https://tree.taiga.io/v-1462392000254/js/libs.js:7:11667
Ar/<@https://tree.taiga.io/v-1462392000254/js/libs.js:6:12185
Xo/<@https://tree.taiga.io/v-1462392000254/js/libs.js:6:27972
t</t.prototype.create@https://tree.taiga.io/v-1462392000254/js/app.js:16:15648
t/n/</<@https://tree.taiga.io/v-1462392000254/js/app.js:13:24469
mn/this.$get</p.prototype.$eval@https://tree.taiga.io/v-1462392000254/js/libs.js:10:11972
mn/this.$get</p.prototype.$apply@https://tree.taiga.io/v-1462392000254/js/libs.js:10:12201
t/n/<@https://tree.taiga.io/v-1462392000254/js/app.js:13:24442
Z.event.dispatch@https://tree.taiga.io/v-1462392000254/js/libs.js:4:22498
Z.event.add/m.handle@https://tree.taiga.io/v-1462392000254/js/libs.js:4:19308
 libs.js:22:17234</code>

**Comment by superalex** [comment]
Thanks for reporting @danielRomero 

We must control that situation, before attaching a document to a wiki page we must ensure it exists, I'm controlling it in this PR https://github.com/taigaio/taiga-front/pull/1002, I hope it can be merged soon.

Regards!,
