### ISSUE TITLE
Deleting private project doesn't remove it from count of private projects

### ISSUE THREAD

**Issue by jbarket** [taigaio/taiga-front#999]
I deleted a private project, but it still believes I have a private project. On the main page, I see the "You don't have any projects yet" text and there are none listed, but when checking the Paid Plans page or attempting to create a project, both believe I still have 1 private project.

If there's anything I can provide screenshot wise to help illustrate this, let me know. Username is jbarket

**Comment by superalex** [comment]
Hello @jbarket 

It should be fixed now, according to our systems you own no private projects.

Regards,
